import {Controller,Get,Post,Patch,Delete,Param,Query,Body,Req,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {geographyKind,geographyCreate,geographyUpdate,marketSettings} from '@haven/contracts';
import {Identity,transaction,pool,data,fail,idempotent} from '../platform/core.js';
import {event} from '@haven/database';
const tables={cities:'cities',districts:'districts',neighborhoods:'neighborhoods',lines:'transit_lines',stations:'transit_stations',communities:'communities',buildings:'buildings'} as const;
const columns={cities:{country:'country',currency:'currency',timezone:'timezone'},districts:{cityId:'city_id'},neighborhoods:{districtId:'district_id'},lines:{cityId:'city_id'},stations:{cityId:'city_id',lineId:'line_id',districtId:'district_id',latitude:'latitude',longitude:'longitude'},communities:{districtId:'district_id',neighborhoodId:'neighborhood_id',address:'address',builtYear:'built_year',amenities:'amenities'},buildings:{communityId:'community_id',floors:'floors',completedYear:'completed_year'}} as const;
type Kind=z.infer<typeof geographyKind>;
async function city(c:pg.PoolClient,id:string){const result=(await c.query("SELECT * FROM cities WHERE (slug=$1 OR id::text=$1) AND status='active'",[id])).rows[0];if(!result)fail(404,'This city is not available','NOT_FOUND');return result;}
async function validateParents(c:pg.PoolClient,kind:Kind,body:any){
 for(const [field,table] of [['cityId','cities'],['districtId','districts'],['neighborhoodId','neighborhoods'],['lineId','transit_lines'],['communityId','communities']])if(body[field]){const row=(await c.query(`SELECT * FROM ${table} WHERE id=$1 AND status='active' FOR SHARE`,[body[field]])).rows[0];if(!row)fail(400,'Choose an active parent location','INVALID_PARENT');if(field==='districtId'&&body.cityId&&row.city_id!==body.cityId||field==='lineId'&&body.cityId&&row.city_id!==body.cityId||field==='neighborhoodId'&&row.district_id!==body.districtId)fail(400,'The selected parent locations belong to different cities or districts','INVALID_PARENT');}
 if(kind==='cities')return;
}
function selection(kind:Kind){return kind==='communities'?'*,ST_Y(location::geometry)::float8 AS latitude,ST_X(location::geometry)::float8 AS longitude':'*';}
@Controller('api/v1')
export class GeographyController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('cities/:city/geography') async geography(@Param('city') selected:string){return transaction(null,async c=>{const record=await city(c,selected);const districts=(await c.query("SELECT * FROM districts WHERE city_id=$1 ORDER BY name,id",[record.id])).rows;const neighborhoods=(await c.query('SELECT n.* FROM neighborhoods n JOIN districts d ON d.id=n.district_id WHERE d.city_id=$1 ORDER BY n.name,n.id',[record.id])).rows;const lines=(await c.query('SELECT * FROM transit_lines WHERE city_id=$1 ORDER BY name,id',[record.id])).rows;const stations=(await c.query('SELECT * FROM transit_stations WHERE city_id=$1 ORDER BY name,id',[record.id])).rows;return data({city:record,districts,neighborhoods,lines,stations});});}
 @Get('ops/geography/:kind') async records(@Req() req:FastifyRequest,@Param('kind') input:string,@Query('city') selected='bj'){
  const actor=await this.identity.actor(req,['admin']),kind=geographyKind.parse(input);
  return transaction(actor,async c=>{const record=kind==='cities'?null:await city(c,selected),filters={cities:'TRUE',districts:'city_id=$1',neighborhoods:'district_id IN (SELECT id FROM districts WHERE city_id=$1)',lines:'city_id=$1',stations:'city_id=$1',communities:'district_id IN (SELECT id FROM districts WHERE city_id=$1)',buildings:'community_id IN (SELECT co.id FROM communities co JOIN districts d ON d.id=co.district_id WHERE d.city_id=$1)'};return data((await c.query(`SELECT ${selection(kind)} FROM ${tables[kind]} WHERE ${filters[kind]} ORDER BY name,id`,kind==='cities'?[]:[record!.id])).rows);});
 }
 @Post('ops/geography/:kind') async create(@Req() req:FastifyRequest,@Param('kind') input:string,@Body() body:unknown){
  const actor=await this.identity.actor(req,['admin']),kind=geographyKind.parse(input),x=geographyCreate.parse(body);if(kind!==x.kind)fail(400,'The location type does not match the route');
  return transaction(actor,c=>idempotent(c,actor,req,x,async()=>{await validateParents(c,kind,x);const entries=Object.entries({name:'name',slug:'slug',aliases:'aliases',...columns[kind]}),values=entries.map(([key])=>(x as any)[key]),names=entries.map(([,name])=>name),expressions=entries.map((_,i)=>'$'+(i+1));if(kind==='communities'){names.push('location');expressions.push(`ST_SetSRID(ST_MakePoint($${values.length+1},$${values.length+2}),4326)::geography`);values.push((x as any).longitude,(x as any).latitude);}const result=(await c.query(`INSERT INTO ${tables[kind]}(${names.join(',')}) VALUES(${expressions.join(',')}) RETURNING ${selection(kind)}`,values)).rows[0];if(kind==='cities')await c.query('INSERT INTO market_config(id,data) VALUES($1,$2)',[x.slug,JSON.stringify({name:x.name,currency:(x as any).currency,timezone:(x as any).timezone,areaUnit:'m²',annualRate:'3.50',rentPeriod:'month',supportEmail:'support@example.test',demo:true})]);await event(c,actor,result.id,'geography.created',{kind});return data(result);}));
 }
 @Patch('ops/geography/:kind/:id') async update(@Req() req:FastifyRequest,@Param('kind') input:string,@Param('id') id:string,@Body() body:unknown){
  const actor=await this.identity.actor(req,['admin']),kind=geographyKind.parse(input),x=geographyUpdate.parse(body);if(kind!==x.kind)fail(400,'The location type does not match the route');
  return transaction(actor,async c=>{const previous=(await c.query(`SELECT * FROM ${tables[kind]} WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!previous)fail(404,'Location not found');if(previous.version!==x.version||previous.status!=='active')fail(409,'This location changed or was archived. Refresh before editing.','VERSION_CONFLICT');if(previous.slug!==x.slug)fail(400,'Location slugs cannot be changed','IMMUTABLE_SLUG');await validateParents(c,kind,x);const entries=Object.entries({name:'name',aliases:'aliases',...columns[kind]}),values:any[]=entries.map(([key])=>(x as any)[key]),sets=entries.map(([,name],i)=>name+'=$'+(i+1));if(kind==='communities'){sets.push(`location=ST_SetSRID(ST_MakePoint($${values.length+1},$${values.length+2}),4326)::geography`);values.push((x as any).longitude,(x as any).latitude);}values.push(id);const result=(await c.query(`UPDATE ${tables[kind]} SET ${sets.join(',')},version=version+1 WHERE id=$${values.length} RETURNING ${selection(kind)}`,values)).rows[0];if(kind==='cities')await c.query("UPDATE market_config SET data=data||$2::jsonb,version=version+1 WHERE id=$1",[x.slug,JSON.stringify({name:x.name,currency:(x as any).currency,timezone:(x as any).timezone})]);await event(c,actor,id,'geography.updated',{kind});return data(result);});
 }
 @Delete('ops/geography/:kind/:id') async archive(@Req() req:FastifyRequest,@Param('kind') input:string,@Param('id') id:string,@Body() body:unknown){const actor=await this.identity.actor(req,['admin']),kind=geographyKind.parse(input),x=z.object({version:z.number().int().positive()}).parse(body);return transaction(actor,async c=>{const previous=(await c.query(`SELECT * FROM ${tables[kind]} WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!previous)fail(404,'Location not found');if(previous.version!==x.version||previous.status!=='active')fail(409,'This location changed or was archived','VERSION_CONFLICT');const result=(await c.query(`UPDATE ${tables[kind]} SET status='archived',version=version+1 WHERE id=$1 RETURNING ${selection(kind)}`,[id])).rows[0];await event(c,actor,id,'geography.archived',{kind});return data(result);});}
 @Patch('ops/cities/:city/market') async market(@Req() req:FastifyRequest,@Param('city') selected:string,@Body() body:unknown){const actor=await this.identity.actor(req,['admin']),x=marketSettings.parse(body);return transaction(actor,async c=>{const record=await city(c,selected),previous=(await c.query('SELECT * FROM market_config WHERE id=$1 FOR UPDATE',[record.slug])).rows[0];if(!previous||previous.version!==x.version)fail(409,'Market settings changed; refresh before editing','VERSION_CONFLICT');const {version:_version,...settings}=x;const result=(await c.query('UPDATE market_config SET data=data||$2::jsonb,version=version+1 WHERE id=$1 RETURNING data,version',[record.slug,JSON.stringify(settings)])).rows[0];await event(c,actor,record.id,'geography.market_updated');return data(result);});}
 @Get('communities/:id/statistics') async statistics(@Param('id') id:string){return transaction(null,async c=>{const community=(await c.query('SELECT co.id,ci.currency FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE co.id::text=$1 OR co.slug=$1',[id])).rows[0];if(!community)fail(404,'Community not found');const rows=(await c.query(`WITH grouped AS (SELECT transaction,count(*)::int AS count,array_agg(price::numeric ORDER BY price::numeric) FILTER(WHERE price IS NOT NULL AND currency=$2 AND (transaction='sale' OR "rentPeriod"='month')) AS prices FROM public_listings WHERE "communityId"=$1 AND segment='residential' GROUP BY transaction) SELECT transaction,count,coalesce(cardinality(prices),0)::int AS priced_count,round((prices[(cardinality(prices)+1)/2]+prices[(cardinality(prices)+2)/2])/2,2)::text AS median_price FROM grouped`,[community.id,community.currency])).rows;const group=(kind:string)=>{const row=rows.find(row=>row.transaction===kind);return {count:row?.count||0,pricedCount:row?.priced_count||0,medianPrice:row?.median_price||null,currency:community.currency};};return data({sale:group('sale'),rent:group('rent'),asOf:new Date().toISOString(),definition:'Published residential asking inventory; median priced sale offers in the city currency and monthly rents only. Missing prices excluded. Not completed transactions.'});});}
 @Get('communities/:id/listings') async listings(@Param('id') id:string,@Query() input:unknown){const q=z.object({transaction:z.enum(['sale','rent']).default('sale'),page:z.coerce.number().int().min(1).max(500).default(1),limit:z.coerce.number().int().min(1).max(50).default(20)}).parse(input);return transaction(null,async c=>{const community=(await c.query('SELECT id FROM communities WHERE id::text=$1 OR slug=$1',[id])).rows[0];if(!community)fail(404,'Community not found');const total=Number((await c.query('SELECT count(*) FROM public_listings WHERE "communityId"=$1 AND transaction=$2 AND segment=$3',[community.id,q.transaction,'residential'])).rows[0].count);const records=(await c.query('SELECT * FROM public_listings WHERE "communityId"=$1 AND transaction=$2 AND segment=$3 ORDER BY "publishedAt" DESC,id LIMIT $4 OFFSET $5',[community.id,q.transaction,'residential',q.limit,(q.page-1)*q.limit])).rows;return data(records,{total,page:q.page,limit:q.limit});});}
 @Get('communities/:id/buildings') async buildings(@Param('id') id:string){return data((await pool.query("SELECT b.id,b.slug,b.name,b.floors,b.completed_year FROM buildings b JOIN communities co ON co.id=b.community_id WHERE co.id::text=$1 OR co.slug=$1 ORDER BY b.name,b.id",[id])).rows);}
}
