import {z} from 'zod';
import {Controller,Get,Param,Query,Post,Body} from '@nestjs/common';
import {listingFilters,geographyFilters} from '@haven/contracts';
import {searchListings} from './search.js';
import {mortgage} from '@haven/contracts/mortgage';
import {pool,data,fail,transaction} from '../platform/core.js';
@Controller('api/v1')
export class DiscoveryController{
 @Get('cities') async cities(){return data((await pool.query('SELECT * FROM cities ORDER BY name')).rows);}
 @Get('cities/:id/districts') async districts(@Param('id') id:string){return data((await pool.query('SELECT d.* FROM districts d JOIN cities c ON c.id=d.city_id WHERE c.slug=$1 OR c.id::text=$1 ORDER BY d.name',[id])).rows);}
 @Get('config') async market(@Query('city') selected='bj'){const result=(await pool.query('SELECT m.data,m.version FROM market_config m JOIN cities c ON c.slug=m.id WHERE c.slug=$1',[selected])).rows[0];if(!result)fail(404,'Market settings are not available','NOT_FOUND');return data(result);}
 @Get('listings') async listings(@Query() input:unknown){const q=listingFilters.parse(input);return searchListings(q);}
 @Get('listings/:id') async listing(@Param('id') id:string,@Query('city') selected?:string){return transaction(null,async c=>{const r=await c.query('SELECT * FROM public_listings WHERE (id::text=$1 OR slug=$1) AND ($2::text IS NULL OR city=$2)',[id,selected||null]);if(!r.rowCount)fail(404,'This property is no longer available','NOT_FOUND');return data(r.rows[0]);});}
 @Get('listings/:id/similar') async similar(@Param('id') id:string){return transaction(null,async c=>data((await c.query('SELECT * FROM public_listings WHERE id::text<>$1 AND transaction=(SELECT transaction FROM public_listings WHERE id::text=$1) ORDER BY "publishedAt" DESC LIMIT 4',[id])).rows));}
 @Get('search/suggest') async suggestions(@Query() input:unknown){const x=z.strictObject({city:z.string().regex(/^[a-z0-9-]{1,50}$/).default('bj'),q:z.string().trim().max(120).default('')}).parse(input);if(!x.q)return data([]);const pattern='%'+x.q.replace(/[\\%_]/g,'\\$&')+'%';return data((await pool.query(`SELECT * FROM (
 SELECT co.id,co.name,co.slug,'community'::text AS kind,ci.slug AS city FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND co.status='active' AND (co.name ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(co.aliases) a WHERE a ILIKE $2))
 UNION ALL SELECT d.id,d.name,d.slug,'district',ci.slug FROM districts d JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND d.status='active' AND (d.name ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(d.aliases) a WHERE a ILIKE $2))
 UNION ALL SELECT n.id,n.name,n.slug,'neighborhood',ci.slug FROM neighborhoods n JOIN districts d ON d.id=n.district_id JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND n.status='active' AND (n.name ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(n.aliases) a WHERE a ILIKE $2))
 ) suggestions ORDER BY name,kind,id LIMIT 8`,[x.city,pattern])).rows);}

 @Get('communities') async communities(@Query() input:unknown){const q=geographyFilters.parse(input);return transaction(null,async c=>{const city=(await c.query('SELECT id FROM cities WHERE slug=$1',[q.city])).rows[0];if(!city)fail(404,'City not found');if(q.districtId&&!(await c.query('SELECT 1 FROM districts WHERE id=$1 AND city_id=$2',[q.districtId,city.id])).rowCount)fail(400,'Choose a district in the selected city','INVALID_PARENT');const values:unknown[]=[city.id,'%'+q.text+'%'],where=['d.city_id=$1',"(co.name ILIKE $2 OR co.address ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(co.aliases) alias WHERE alias ILIKE $2))"];if(q.districtId){values.push(q.districtId);where.push('d.id=$3');}const clause=where.join(' AND '),total=Number((await c.query('SELECT count(*) FROM communities co JOIN districts d ON d.id=co.district_id WHERE '+clause,values)).rows[0].count);const result=await c.query('SELECT co.id,co.slug,co.name,co.address,co.built_year AS "builtYear",co.amenities,co.photos,d.name AS district,d.id AS "districtId",ci.slug AS city,round(ST_Y(co.location::geometry)::numeric,3)::float8 AS latitude,round(ST_X(co.location::geometry)::numeric,3)::float8 AS longitude FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE '+clause+' ORDER BY co.name,co.id LIMIT $'+(values.length+1)+' OFFSET $'+(values.length+2),[...values,q.limit,(q.page-1)*q.limit]);return data(result.rows,{total,page:q.page,limit:q.limit});});}
 @Get('communities/:id') async community(@Param('id') id:string,@Query('city') selected?:string){const r=await pool.query('SELECT co.id,co.slug,co.name,co.address,co.built_year AS "builtYear",co.amenities,co.photos,d.name AS district,d.id AS "districtId",ci.slug AS city,round(ST_Y(co.location::geometry)::numeric,3)::float8 AS latitude,round(ST_X(co.location::geometry)::numeric,3)::float8 AS longitude FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE (co.id::text=$1 OR co.slug=$1) AND ($2::text IS NULL OR ci.slug=$2)',[id,selected||null]);if(!r.rowCount)fail(404,'Community not found');return data(r.rows[0]);}
 @Get('agents') async agents(@Query('city') selected='bj'){return data((await pool.query('SELECT a.id,a.name,a.slug,a.biography,a.languages,a.districts,a.verified_until AS "verifiedUntil",a.photo,a.public_email AS "publicEmail" FROM agents a WHERE EXISTS(SELECT 1 FROM districts d JOIN cities c ON c.id=d.city_id WHERE c.slug=$1 AND d.name=ANY(a.districts)) ORDER BY a.name',[selected])).rows);}
 @Get('agents/:id') async agent(@Param('id') id:string){const r=await pool.query('SELECT id,name,slug,biography,languages,districts,verified_until AS "verifiedUntil",photo,public_email AS "publicEmail" FROM agents WHERE id::text=$1 OR slug=$1',[id]);if(!r.rowCount)fail(404,'Agent not found');return data(r.rows[0]);}
 @Get('developments') async developments(@Query('city') selected='bj'){return data((await pool.query('SELECT de.*,co.name AS community,d.name AS district FROM developments de JOIN communities co ON co.id=de.community_id JOIN districts d ON d.id=co.district_id WHERE de.status IN ($1,$2,$3) AND d.city_id=(SELECT id FROM cities WHERE slug=$4) ORDER BY de.name',['on_sale','coming_soon','sold_out',selected])).rows.map(({organization_id:_org,...r})=>r));}
 @Get('developments/:id') async development(@Param('id') id:string,@Query('city') selected?:string){const r=await pool.query('SELECT de.id,de.slug,de.name,de.description,de.status,de.price_min,de.price_max,de.currency,de.price_basis,de.completion_date,de.photos,de.features,de.inventory_at,co.name AS community,d.name AS district FROM developments de JOIN communities co ON co.id=de.community_id JOIN districts d ON d.id=co.district_id WHERE (de.id::text=$1 OR de.slug=$1) AND de.status IN ($2,$3,$4) AND ($5::text IS NULL OR d.city_id=(SELECT id FROM cities WHERE slug=$5))',[id,'on_sale','coming_soon','sold_out',selected||null]);if(!r.rowCount)fail(404,'Development not found');const plans=(await pool.query('SELECT * FROM floor_plans WHERE development_id=$1',[r.rows[0].id])).rows;return data({...r.rows[0],floorPlans:plans});}
 @Get('renovation/providers') async providers(@Query('city') selected='bj'){return data((await pool.query("SELECT id,slug,name,description,categories,districts,photos FROM providers p WHERE status='approved' AND EXISTS(SELECT 1 FROM districts d JOIN cities c ON c.id=d.city_id WHERE c.slug=$1 AND d.name=ANY(p.districts)) ORDER BY name",[selected])).rows);}
 @Get('renovation/providers/:id') async provider(@Param('id') id:string){const r=await pool.query("SELECT id,slug,name,description,categories,districts,photos FROM providers WHERE (id::text=$1 OR slug=$1) AND status='approved'",[id]);if(!r.rowCount)fail(404,'Provider not found');return data(r.rows[0]);}
 @Post('tools/mortgage-estimate') estimate(@Body() input:unknown){return data(mortgage(input));}
}
