import {publicProviders,publicProvider} from '../services/provider-catalog.js';
import {providerFilters} from '@haven/contracts';
import {agentDirectoryFilters} from '@haven/contracts';
import {agentDirectory,agentDetail,publicAgentProfile} from '../services/agent-directory.js';
import {publicAgentInventory} from '../inventory/agent-inventory.js';
import {searchDevelopments} from './development-search.js';
import {developmentFilters} from '@haven/contracts';
import {publicRentalTerms} from './rental-detail.js';
import {z} from 'zod';
import {Controller,Get,Param,Query,Post,Body} from '@nestjs/common';
import {listingFilters,geographyFilters} from '@haven/contracts';
import {rankingExpressions} from './ranking-policy.js';
import {rankedListings} from './rankings.js';
import {rankingFilters} from '@haven/contracts';
import {searchListings,mapListings} from './search.js';
import {mortgage} from './mortgage-engine.js';
import {defaultMortgageEstimateNotes} from '@haven/contracts/mortgage';
import {pool,data,fail,transaction,env} from '../platform/core.js';
@Controller('api/v1')
export class DiscoveryController{
 @Get('cities') async cities(){return data((await pool.query('SELECT * FROM cities ORDER BY name')).rows);}
 @Get('cities/:id/districts') async districts(@Param('id') id:string){return data((await pool.query('SELECT d.* FROM districts d JOIN cities c ON c.id=d.city_id WHERE c.slug=$1 OR c.id::text=$1 ORDER BY d.name',[id])).rows);}
 @Get('config') async market(@Query('city') selected='bj'){const result=(await pool.query('SELECT m.data,m.version FROM market_config m JOIN cities c ON c.slug=m.id WHERE c.slug=$1',[selected])).rows[0];if(!result)fail(404,'Market settings are not available','NOT_FOUND');return data(result);}
 @Get('listings') async listings(@Query() input:unknown){const q=listingFilters.parse(input);return searchListings(q);}
 @Get('listings/map') async mapListings(@Query() input:unknown){return mapListings(listingFilters.parse(input));}
 @Get('map/config') mapConfiguration(){return data({style:env.MAP_STYLE_URL||null,attribution:env.MAP_ATTRIBUTION||(env.MAP_STYLE_URL?'Community positions rounded to 3 decimal places':'Local synthetic map · Community positions rounded to 3 decimal places')});}
 @Get('listings/facets') async facets(@Query() input:unknown){const x=z.strictObject({city:z.string().regex(/^[a-z0-9-]{1,50}$/).default('bj')}).parse(input);return transaction(null,async c=>{const result:Record<string,string[]>={};for(const field of ['finishing','heating','furnishing','buildingType','features','ownership','holdingPeriod']){const column=['features','ownership','holdingPeriod'].includes(field)?'unnest("'+field+'")':'"'+field+'"';result[field]=(await c.query(`SELECT DISTINCT value FROM(SELECT ${column} AS value FROM public_listings WHERE city=$1) choices WHERE value IS NOT NULL ORDER BY value LIMIT 100`,[x.city])).rows.map(row=>row.value);}return data(result);});}
 @Get('listings/:id') async listing(@Param('id') id:string,@Query('city') selected?:string){return transaction(null,async c=>{const r=await c.query(`SELECT *,${rankingExpressions().disclosure} FROM public_listings WHERE (id::text=$1 OR slug=$1) AND ($2::text IS NULL OR city=$2)`,[id,selected||null]);if(!r.rowCount)fail(404,'This property is no longer available','NOT_FOUND');const listing=r.rows[0];return data({...listing,rentalTerms:listing.transaction==='rent'?await publicRentalTerms(c,listing.id):null});});}
 @Get('listings/:id/agents') async listingAgents(@Param('id') id:string,@Query('city') selected?:string){return transaction(null,async c=>{const source=(await c.query('SELECT id FROM public_listings WHERE (id::text=$1 OR slug=$1) AND ($2::text IS NULL OR city=$2)',[id,selected||null])).rows[0];if(!source)fail(404,'This property is no longer available','NOT_FOUND');return data((await c.query('SELECT * FROM public_listing_agents($1)',[source.id])).rows);});}
 @Get('listings/:id/similar') async similar(@Param('id') id:string){const source=await transaction(null,async c=>(await c.query('SELECT id,city,transaction,segment FROM public_listings WHERE id::text=$1 OR slug=$1',[id])).rows[0]);if(!source)fail(404,'This property is no longer available','NOT_FOUND');return rankedListings(rankingFilters.parse({city:source.city,transaction:source.transaction,segment:source.segment,limit:4,period:'30d'}),source.id);}
 @Get('search/suggest') async suggestions(@Query() input:unknown){const x=z.strictObject({city:z.string().regex(/^[a-z0-9-]{1,50}$/).default('bj'),q:z.string().trim().max(120).default('')}).parse(input);if(!x.q)return data([]);const pattern='%'+x.q.replace(/[\\%_]/g,'\\$&')+'%';return data((await pool.query(`SELECT * FROM (
 SELECT co.id,co.name,co.slug,'community'::text AS kind,ci.slug AS city FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND co.status='active' AND (co.name ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(co.aliases) a WHERE a ILIKE $2))
 UNION ALL SELECT d.id,d.name,d.slug,'district',ci.slug FROM districts d JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND d.status='active' AND (d.name ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(d.aliases) a WHERE a ILIKE $2))
 UNION ALL SELECT n.id,n.name,n.slug,'neighborhood',ci.slug FROM neighborhoods n JOIN districts d ON d.id=n.district_id JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND n.status='active' AND (n.name ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(n.aliases) a WHERE a ILIKE $2))
 ) suggestions ORDER BY name,kind,id LIMIT 8`,[x.city,pattern])).rows);}

 @Get('communities') async communities(@Query() input:unknown){const q=geographyFilters.parse(input);return transaction(null,async c=>{const city=(await c.query('SELECT id FROM cities WHERE slug=$1',[q.city])).rows[0];if(!city)fail(404,'City not found');if(q.districtId&&!(await c.query('SELECT 1 FROM districts WHERE id=$1 AND city_id=$2',[q.districtId,city.id])).rowCount)fail(400,'Choose a district in the selected city','INVALID_PARENT');const values:unknown[]=[city.id,'%'+q.text+'%'],where=['d.city_id=$1',"(co.name ILIKE $2 OR co.address ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(co.aliases) alias WHERE alias ILIKE $2))"];if(q.districtId){values.push(q.districtId);where.push('d.id=$3');}const clause=where.join(' AND '),total=Number((await c.query('SELECT count(*) FROM communities co JOIN districts d ON d.id=co.district_id WHERE '+clause,values)).rows[0].count);const result=await c.query('SELECT co.id,co.slug,co.name,co.address,co.built_year AS "builtYear",co.amenities,co.photos,d.name AS district,d.id AS "districtId",ci.slug AS city,round(ST_Y(co.location::geometry)::numeric,3)::float8 AS latitude,round(ST_X(co.location::geometry)::numeric,3)::float8 AS longitude FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE '+clause+' ORDER BY co.name,co.id LIMIT $'+(values.length+1)+' OFFSET $'+(values.length+2),[...values,q.limit,(q.page-1)*q.limit]);return data(result.rows,{total,page:q.page,limit:q.limit});});}
 @Get('communities/:id') async community(@Param('id') id:string,@Query('city') selected?:string){const r=await pool.query('SELECT co.id,co.slug,co.name,co.address,co.built_year AS "builtYear",co.amenities,co.photos,d.name AS district,d.id AS "districtId",ci.slug AS city,round(ST_Y(co.location::geometry)::numeric,3)::float8 AS latitude,round(ST_X(co.location::geometry)::numeric,3)::float8 AS longitude FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE (co.id::text=$1 OR co.slug=$1) AND ($2::text IS NULL OR ci.slug=$2)',[id,selected||null]);if(!r.rowCount)fail(404,'Community not found');return data(r.rows[0]);}
 @Get('agents') async agents(@Query() input:unknown){const x=agentDirectoryFilters.parse(input);return agentDirectory(x);}
 @Get('agents/:id') async agent(@Param('id') id:string,@Query('city') selected='bj'){return agentDetail(id,selected);}
 @Get('agents/:id/listings') async agentListings(@Param('id') id:string,@Query() input:unknown){const x=agentDirectoryFilters.parse(input);return transaction(null,async c=>{const p=await publicAgentProfile(c,id,x.city),r=await publicAgentInventory(c,p.id,x.city,x.page,x.limit);return data(r.rows,{total:r.total,page:x.page,limit:x.limit});});}
 @Get('developments') async developments(@Query() input:unknown){return searchDevelopments(developmentFilters.parse(input));}
 @Get('developments/:id') async development(@Param('id') id:string,@Query('city') selected?:string){const r=await pool.query(`SELECT de.id,de.version,de.community_id,de.slug,de.name,de.description,de.status,de.price_min,de.price_max,de.currency,de.price_basis,de.completion_date,de.photos,de.features,de.inventory_at,round(ST_Y(co.location::geometry)::numeric,3)::float8 AS latitude,round(ST_X(co.location::geometry)::numeric,3)::float8 AS longitude,co.name AS community,d.name AS district,COALESCE((public_curated_boost('development',de.id)->>'sponsored')::boolean,false) AS sponsored,public_curated_boost('development',de.id)->>'label' AS "curationLabel" FROM developments de JOIN communities co ON co.id=de.community_id JOIN districts d ON d.id=co.district_id WHERE (de.id::text=$1 OR de.slug=$1) AND de.status IN ($2,$3,$4) AND ($5::text IS NULL OR d.city_id=(SELECT id FROM cities WHERE slug=$5))`,[id,'on_sale','coming_soon','sold_out',selected||null]);if(!r.rowCount)fail(404,'Development not found');const plans=(await pool.query("SELECT * FROM floor_plans WHERE development_id=$1 AND publication_status='published' ORDER BY name,id",[r.rows[0].id])).rows;const phases=(await pool.query("SELECT id,name,status FROM development_phases WHERE development_id=$1 AND status IN ('coming_soon','on_sale','sold_out') ORDER BY name,id",[r.rows[0].id])).rows;return data({...r.rows[0],floorPlans:plans,phases});}
 @Get('renovation/providers') async providers(@Query() input:unknown){const x=providerFilters.parse(input);return publicProviders(x);}
 @Get('renovation/providers/:id') async provider(@Param('id') id:string,@Query('city') selected?:string){return publicProvider(id,selected);}
 @Post('tools/mortgage-estimate') async estimate(@Body() input:unknown,@Query('city') selected='bj'){const calculated=mortgage(input);const market=(await pool.query("SELECT c.slug,c.currency,m.version,m.data FROM cities c JOIN market_config m ON m.id=c.slug WHERE c.slug=$1 AND c.status='active'",[z.string().regex(/^[a-z0-9-]{1,50}$/).parse(selected)])).rows[0];if(!market)fail(404,'Active market settings are not available');return data({...calculated,city:market.slug,currency:market.currency,marketVersion:market.version,estimateNotes:market.data.mortgageEstimateNotes||defaultMortgageEstimateNotes});}
}
