import type pg from 'pg';
import type {z} from 'zod';
import type {projectBuildingCreate,projectBuildingUpdate} from '@haven/contracts';
import type {Actor} from '@haven/database';
import {fail} from '../platform/core.js';
// Geography owns canonical building mutations. Inventory calls this port
// inside its scoped project transaction; root locks precede building locks.
async function scopedProject(c:pg.PoolClient,a:Actor,id:string,version:number){const project=(await c.query('SELECT * FROM developments WHERE id=$1 AND (organization_id=$2 OR $3) FOR UPDATE',[id,a.orgId,a.roles.includes('admin')])).rows[0];if(!project||!a.roles.some(role=>['developer','admin'].includes(role)))fail(404,'Assigned project not found');if(project.version!==version)fail(409,'Project changed. Reload before saving.');return project;}
async function phase(c:pg.PoolClient,id:string,phaseId:string|null){if(phaseId&&!(await c.query('SELECT 1 FROM development_phases WHERE id=$1 AND development_id=$2',[phaseId,id])).rowCount)fail(400,'Choose a phase within this project','INVALID_PHASE');}
export async function createDevelopmentBuilding(c:pg.PoolClient,a:Actor,id:string,x:z.infer<typeof projectBuildingCreate>){const source=await scopedProject(c,a,id,x.projectVersion);if(source.status==='sold_out')fail(409,'Reopen sales before adding a building');await phase(c,id,x.phaseId);if((await c.query('SELECT 1 FROM buildings WHERE community_id=$1 AND slug=$2',[source.community_id,x.slug])).rowCount)fail(409,'This building URL name already exists in the community. Choose another URL name.','BUILDING_URL_EXISTS');return (await c.query('INSERT INTO buildings(community_id,development_id,phase_id,slug,name,floors,completed_year) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[source.community_id,id,x.phaseId,x.slug,x.name,x.floors,x.completedYear])).rows[0];}
export async function updateDevelopmentBuilding(c:pg.PoolClient,a:Actor,id:string,buildingId:string,x:z.infer<typeof projectBuildingUpdate>){const source=await scopedProject(c,a,id,x.projectVersion);if(source.status==='sold_out')fail(409,'Reopen sales before editing a building');const row=(await c.query('SELECT * FROM buildings WHERE id=$1 AND development_id=$2 FOR UPDATE',[buildingId,id])).rows[0];if(!row)fail(404,'Project building not found');if(row.version!==x.version)fail(409,'Building changed. Reload before saving.');await phase(c,id,x.phaseId);return (await c.query('UPDATE buildings SET name=$2,phase_id=$3,floors=$4,completed_year=$5,status=$6,version=version+1 WHERE id=$1 RETURNING *',[buildingId,x.name,x.phaseId,x.floors,x.completedYear,x.status])).rows[0];}
