import type {z} from 'zod';
import {developmentFilters} from '@haven/contracts';
import {transaction,data,fail} from '../platform/core.js';
type Filters=z.infer<typeof developmentFilters>;
export async function searchDevelopments(q:Filters){return transaction(null,async c=>{
 const city=(await c.query("SELECT id,currency FROM cities WHERE slug=$1 AND status='active'",[q.city])).rows[0];if(!city)fail(404,'City not found');if(q.currency&&q.currency!==city.currency)fail(400,'Use the selected city currency for development budgets','MIXED_CURRENCY');if(q.districtId&&!(await c.query('SELECT 1 FROM districts WHERE id=$1 AND city_id=$2',[q.districtId,city.id])).rowCount)fail(400,'Choose a district within this city','INVALID_DISTRICT');
 const values:unknown[]=[city.id,city.currency],where=["de.status IN('coming_soon','on_sale','sold_out')",'d.city_id=$1','de.currency=$2'];const bind=(value:unknown)=>{values.push(value);return '$'+values.length;};
 if(q.districtId)where.push('d.id='+bind(q.districtId));if(q.status)where.push('de.status='+bind(q.status));if(q.priceBasis)where.push('de.price_basis='+bind(q.priceBasis==='per_area'?'per m²':'starting total'));if(q.minPrice!==undefined)where.push('de.price_min>='+bind(q.minPrice)+'::numeric');if(q.maxPrice!==undefined)where.push('de.price_min<='+bind(q.maxPrice)+'::numeric');if(q.text)where.push('(de.name ILIKE '+bind('%'+q.text.replace(/[\\%_]/g,'\\$&')+'%')+' OR co.name ILIKE $'+values.length+')');
 const types=["f.development_id=de.id","f.publication_status='published'"];if(q.beds!==undefined)types.push('f.beds='+bind(q.beds));if(q.minArea!==undefined)types.push('f.area_max>='+bind(q.minArea)+'::numeric');if(q.maxArea!==undefined)types.push('f.area_min<='+bind(q.maxArea)+'::numeric');if(types.length>2)where.push('EXISTS(SELECT 1 FROM floor_plans f WHERE '+types.join(' AND ')+')');
 const joins=' FROM developments de JOIN communities co ON co.id=de.community_id AND co.status=\'active\' JOIN districts d ON d.id=co.district_id AND d.status=\'active\' WHERE '+where.join(' AND '),total=Number((await c.query('SELECT count(*)'+joins,values)).rows[0].count),offset=(q.page-1)*q.limit;if(offset>10000)fail(400,'Development page exceeds the bounded limit','PAGE_LIMIT');const orders={name:'de.name ASC',price_asc:'de.price_min ASC NULLS LAST',price_desc:'de.price_min DESC NULLS LAST',newest:'de.inventory_at DESC'};const rows=(await c.query(`SELECT de.*,co.name AS community,d.name AS district,coalesce((public_curated_boost('development',de.id)->>'sponsored')::boolean,false) AS sponsored,public_curated_boost('development',de.id)->>'label' AS "curationLabel",(SELECT count(*)::int FROM floor_plans f WHERE f.development_id=de.id AND f.publication_status='published' AND f.available>0) AS "availableTypes"`+joins+' ORDER BY '+orders[q.sort]+',de.id ASC LIMIT '+bind(q.limit)+' OFFSET '+bind(offset),values)).rows.map(({organization_id:_,...row})=>row);
 return data(rows,{total,page:q.page,limit:q.limit,currency:city.currency,searchMode:'sql',pagination:'bounded-offset',maxOffset:10000,budgetDefinition:'recorded-starting-price-in-selected-basis'});
});}
