import {managementGrantPage} from '@haven/contracts';
import {managementPortfolio} from './grants.js';
import {Controller,Get,Post,Patch,Param,Req,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import {z} from 'zod';
import Decimal from 'decimal.js';
import {money,maintenanceTransitions,transition} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import type pg from 'pg';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const roles=['property_manager','admin'];
const finance=['finance'];
async function lease(c:pg.PoolClient,id:string){const r=await c.query('SELECT * FROM leases WHERE id=$1 FOR UPDATE',[id]);if(!r.rowCount)fail(404,'Lease not found');return r.rows[0];}
async function grant(c:pg.PoolClient,a:Actor,unit:string){if((await c.query('SELECT management_unit_grant_lock($1,$2) AS version',[unit,a.orgId])).rows[0].version===null)fail(403,'A current management grant and assigned team membership are required');}
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Use a valid date');
@Controller('api/v1')
export class ManagementController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/managed-properties') async properties(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,roles),x=managementGrantPage.parse(input);return transaction(a,async c=>data(await managementPortfolio(c,x.page),{page:x.page,limit:20}));}
 @Get('ops/tenants') async tenants(@Req() req:FastifyRequest){const a=await this.identity.actor(req,roles);return transaction(a,async c=>data((await c.query('SELECT id,name,email,user_id FROM tenants')).rows));}
 @Get('ops/leases') async leases(@Req() req:FastifyRequest){const a=await this.identity.actor(req,roles);return transaction(a,async c=>data((await c.query('SELECT l.*,t.name AS tenant,co.name AS community FROM leases l JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id ORDER BY l.start_date DESC')).rows));}
 @Post('ops/leases/:id/end') async end(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles);const x=z.object({reason:z.string().min(5).max(500)}).parse(body);return transaction(a,async c=>{const l=await lease(c,id);await grant(c,a,l.unit_id);if(l.status!=='active')fail(409,'Lease is not active');await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=$1",[id]);await event(c,a,id,'lease.ended',{reason:x.reason});return data({status:'ended'});});}
 @Post('ops/leases/:id/renew') async renew(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles);const x=z.object({startDate:date,endDate:date,rent:money}).parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const l=await lease(c,id);await grant(c,a,l.unit_id);if(!['active','ended'].includes(l.status))fail(409,'Renew an active or ended lease');if(x.startDate<=new Date(l.end_date).toISOString().slice(0,10)||x.startDate>x.endDate||new Decimal(x.rent).lte(0))fail(400,'Renewal must start after the current term and have valid dates and positive rent');const r=await c.query('INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[l.organization_id,l.unit_id,l.tenant_id,x.startDate,x.endDate,x.rent,l.currency]);await event(c,a,r.rows[0].id,'lease.renewal_drafted',{previousLease:id});return data(r.rows[0]);}));}
 @Post('ops/charges/:id/reverse') async reverseCharge(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,finance);const x=z.object({reason:z.string().min(5).max(500)}).parse(body);return transaction(a,async c=>{const ch=(await c.query('SELECT * FROM charges WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!ch)fail(404,'Charge not found');const l=await lease(c,ch.lease_id);await grant(c,a,l.unit_id);if(ch.reverses_id)fail(409,'Cannot reverse a reversal');const existing=await c.query('SELECT * FROM charges WHERE reverses_id=$1',[id]);if(existing.rowCount)return data(existing.rows[0]);const reversed=await c.query('INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind,reverses_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[ch.lease_id,ch.organization_id,ch.period,ch.due_date,ch.amount,ch.currency,'reversal:'+id,id]);await c.query('UPDATE allocations SET reversed_at=now() WHERE charge_id=$1 AND reversed_at IS NULL',[id]);await event(c,a,id,'charge.reversed',{reason:x.reason});return data(reversed.rows[0]);});}
 @Get('me/owner-leases') async ownerLeases(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT l.id,l.start_date,l.end_date,l.rent::text,l.currency,l.status,co.name AS community FROM leases l JOIN management_grants g ON g.unit_id=l.unit_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE g.owner_id=$1 AND g.expires_at>now()',[a.id])).rows));}
 @Post('ops/charges/generate') async generate(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,finance);const x=z.object({period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}).parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const start=x.period+'-01',end=new Date(Date.UTC(Number(x.period.slice(0,4)),Number(x.period.slice(5,7)),0)).toISOString().slice(0,10);const leases=(await c.query("SELECT * FROM leases WHERE status='active' AND start_date<=$2 AND end_date>=$1 ORDER BY id FOR UPDATE",[start,end])).rows;let generated=0;for(const l of leases){await grant(c,a,l.unit_id);const from=Math.max(Date.parse(start),new Date(l.start_date).getTime()),to=Math.min(Date.parse(end),new Date(l.end_date).getTime());const days=(Date.parse(end)-Date.parse(start))/86400000+1,occupied=(to-from)/86400000+1;const amount=new Decimal(l.rent).mul(occupied).div(days).toFixed(2);const r=await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,$3,$3,$4,$5) ON CONFLICT(lease_id,period,kind) DO NOTHING RETURNING id",[l.id,l.organization_id,start,amount,l.currency]);if(r.rowCount){generated++;await event(c,a,r.rows[0].id,'charge.posted');}}return data({generated,period:x.period,proration:'Calendar days occupied / days in month'});}));}
 @Get('ops/charges') async charges(@Req() req:FastifyRequest){const a=await this.identity.actor(req,roles);return transaction(a,async c=>data((await c.query('SELECT ch.*,co.name AS community FROM charges ch JOIN leases l ON l.id=ch.lease_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id ORDER BY ch.due_date DESC')).rows));}
 @Get('ops/payment-records') async payments(@Req() req:FastifyRequest){const a=await this.identity.actor(req,finance);return transaction(a,async c=>data((await c.query('SELECT * FROM payments ORDER BY created_at DESC')).rows));}
 @Post('ops/payment-records') async payment(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,finance);const x=z.object({leaseId:z.string().uuid(),amount:money,currency:z.literal('CNY'),source:z.enum(['bank_statement','receipt','manual_evidence']),reference:z.string().trim().min(3).max(120)}).parse(body);if(new Decimal(x.amount).lte(0))fail(400,'Amount must be positive');return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const l=await lease(c,x.leaseId);await grant(c,a,l.unit_id);if(l.currency!==x.currency)fail(400,'Payment currency must match the lease');const r=await c.query('INSERT INTO payments(lease_id,organization_id,amount,currency,source,reference,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[l.id,l.organization_id,x.amount,x.currency,x.source,x.reference,a.id]);await event(c,a,r.rows[0].id,'payment.recorded');return data(r.rows[0]);}));}
 @Post('ops/allocations') async allocate(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,finance);const x=z.object({paymentId:z.string().uuid(),chargeId:z.string().uuid(),amount:money}).parse(body);if(new Decimal(x.amount).lte(0))fail(400,'Allocation must be positive');return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[x.paymentId])).rows[0],ch=(await c.query('SELECT * FROM charges WHERE id=$1 FOR UPDATE',[x.chargeId])).rows[0];if(!p||!ch)fail(404,'Payment or charge not found');const l=await lease(c,p.lease_id);await grant(c,a,l.unit_id);if(p.lease_id!==ch.lease_id||p.currency!==ch.currency||p.reverses_id||ch.reverses_id)fail(400,'Allocation requires the same lease and currency');if((await c.query('SELECT 1 FROM payments WHERE reverses_id=$1',[p.id])).rowCount||(await c.query('SELECT 1 FROM charges WHERE reverses_id=$1',[ch.id])).rowCount)fail(409,'Reversed records cannot be allocated');const used=await c.query('SELECT coalesce(sum(amount),0)::text AS amount FROM allocations WHERE payment_id=$1 AND reversed_at IS NULL',[p.id]);const paid=await c.query('SELECT coalesce(sum(amount),0)::text AS amount FROM allocations WHERE charge_id=$1 AND reversed_at IS NULL',[ch.id]);if(new Decimal(p.amount).minus(used.rows[0].amount).lt(x.amount)||new Decimal(ch.amount).minus(paid.rows[0].amount).lt(x.amount))fail(409,'Allocation exceeds available payment or outstanding charge');const r=await c.query('INSERT INTO allocations(payment_id,charge_id,organization_id,amount) VALUES($1,$2,$3,$4) RETURNING *',[p.id,ch.id,p.organization_id,x.amount]);await event(c,a,r.rows[0].id,'payment.allocated');return data(r.rows[0]);}));}
 @Post('ops/payment-records/:id/reverse') async reverse(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,finance);const x=z.object({reason:z.string().min(5).max(500)}).parse(body);return transaction(a,async c=>{const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p)fail(404,'Payment not found');const l=await lease(c,p.lease_id);await grant(c,a,l.unit_id);if(p.reverses_id)fail(409,'A reversal cannot itself be reversed');const existing=await c.query('SELECT * FROM payments WHERE reverses_id=$1',[id]);if(existing.rowCount)return data(existing.rows[0]);const r=await c.query('INSERT INTO payments(lease_id,organization_id,amount,currency,source,reference,actor_id,reverses_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[p.lease_id,p.organization_id,p.amount,p.currency,'reversal',x.reason,a.id,id]);await c.query('UPDATE allocations SET reversed_at=now() WHERE payment_id=$1 AND reversed_at IS NULL',[id]);await event(c,a,id,'payment.reversed');return data(r.rows[0]);});}
 @Post('ops/deposits') async deposit(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,finance);const x=z.object({leaseId:z.string().uuid(),kind:z.enum(['received','released']),amount:money,reason:z.string().min(5).max(500)}).parse(body);if(new Decimal(x.amount).lte(0))fail(400,'Amount must be positive');return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const l=await lease(c,x.leaseId);await grant(c,a,l.unit_id);const balance=(await c.query("SELECT coalesce(sum(CASE WHEN kind='received' THEN amount ELSE -amount END),0)::text AS balance FROM deposits WHERE lease_id=$1",[l.id])).rows[0].balance;if(x.kind==='released'&&new Decimal(balance).lt(x.amount))fail(409,'Release exceeds held deposit');const r=await c.query('INSERT INTO deposits(lease_id,organization_id,kind,amount,currency,reason,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[l.id,l.organization_id,x.kind,x.amount,l.currency,x.reason,a.id]);await event(c,a,r.rows[0].id,'deposit.'+x.kind);return data(r.rows[0]);}));}
 @Get('me/leases') async tenantLeases(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT l.id,l.start_date,l.end_date,l.rent::text,l.currency,l.status,co.name AS community FROM leases l JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE t.user_id=$1',[a.id])).rows));}
 @Get('me/charges') async tenantCharges(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT ch.id,ch.lease_id,ch.period,ch.due_date,ch.amount::text,ch.currency,ch.kind,ch.reverses_id FROM charges ch JOIN leases l ON l.id=ch.lease_id JOIN tenants t ON t.id=l.tenant_id WHERE t.user_id=$1 ORDER BY ch.due_date DESC',[a.id])).rows));}
 @Get('leases/:id/statement') async statement(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>{const l=(await c.query('SELECT id,unit_id,tenant_id,rent::text,currency,start_date,end_date,status,organization_id FROM leases WHERE id=$1',[id])).rows[0];if(!l)fail(404,'Lease not found');if(!a.roles.some(r=>roles.includes(r))&&!(await c.query('SELECT 1 FROM tenants WHERE id=$1 AND user_id=$2',[l.tenant_id,a.id])).rowCount&&!(await c.query('SELECT 1 FROM management_grants WHERE unit_id=$1 AND owner_id=$2 AND expires_at>now()',[l.unit_id,a.id])).rowCount)fail(404,'Lease not found');const charges=(await c.query('SELECT id,period,due_date,amount::text,currency,kind,reverses_id FROM charges WHERE lease_id=$1 ORDER BY due_date',[id])).rows;const payments=(await c.query('SELECT id,amount::text,currency,source,reference,reverses_id,created_at FROM payments WHERE lease_id=$1 ORDER BY created_at',[id])).rows;const allocations=(await c.query('SELECT a.id,a.payment_id,a.charge_id,a.amount::text,a.reversed_at FROM allocations a JOIN payments p ON p.id=a.payment_id WHERE p.lease_id=$1',[id])).rows;const deposits=(await c.query('SELECT id,kind,amount::text,currency,reason,created_at FROM deposits WHERE lease_id=$1 ORDER BY created_at',[id])).rows;const activeCharges=charges.filter(r=>!r.reverses_id&&!charges.some(x=>x.reverses_id===r.id));const activePayments=payments.filter(r=>!r.reverses_id&&!payments.some(x=>x.reverses_id===r.id));const sum=(rows:typeof charges)=>rows.reduce((s,r)=>s.plus(r.amount),new Decimal(0));const charged=sum(activeCharges),recorded=sum(activePayments),allocated=sum(allocations.filter(r=>!r.reversed_at));return data({lease:{id:l.id,currency:l.currency,rent:l.rent,startDate:l.start_date,endDate:l.end_date,status:l.status},charges,payments,allocations,deposits,totals:{charges:charged.toFixed(2),recordedPayments:recorded.toFixed(2),allocated:allocated.toFixed(2),outstanding:charged.minus(allocated).toFixed(2),credit:recorded.minus(allocated).toFixed(2),depositHeld:deposits.reduce((s,r)=>s.plus(new Decimal(r.amount).mul(r.kind==='received'?1:-1)),new Decimal(0)).toFixed(2)},note:'Recorded payment evidence and allocations. No funds are transferred.'});});}
 @Get('me/maintenance') async tenantMaintenance(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT id,lease_id,title,description,category,urgency,status,assignee,public_note,version,created_at FROM maintenance WHERE user_id=$1 ORDER BY created_at DESC',[a.id])).rows));}
 @Post('me/maintenance') async request(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req);const x=z.object({leaseId:z.string().uuid(),title:z.string().min(5).max(120),description:z.string().min(10).max(3000),category:z.enum(['Plumbing','Electrical','Heating','Appliance','Other']),urgency:z.enum(['Routine','Urgent','Emergency'])}).parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const l=(await c.query("SELECT l.* FROM leases l JOIN tenants t ON t.id=l.tenant_id WHERE l.id=$1 AND t.user_id=$2 AND l.status='active'",[x.leaseId,a.id])).rows[0];if(!l)fail(404,'Active linked lease not found');const r=await c.query('INSERT INTO maintenance(lease_id,organization_id,user_id,title,description,category,urgency) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,status',[l.id,l.organization_id,a.id,x.title,x.description,x.category,x.urgency]);await event(c,a,r.rows[0].id,'maintenance.opened');return data(r.rows[0]);}));}
 @Get('ops/maintenance') async maintenance(@Req() req:FastifyRequest){const a=await this.identity.actor(req,roles);return transaction(a,async c=>data((await c.query('SELECT * FROM maintenance ORDER BY created_at DESC')).rows));}
 @Patch('ops/maintenance/:id') async maintain(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles);const x=z.object({status:z.string(),version:z.number().int(),assignee:z.string().max(100).optional(),publicNote:z.string().max(2000).optional(),internalNote:z.string().max(2000).optional()}).parse(body);return transaction(a,async c=>{const r=(await c.query('SELECT * FROM maintenance WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)fail(404,'Request not found');const l=await lease(c,r.lease_id);await grant(c,a,l.unit_id);if(r.version!==x.version)fail(409,'Request has changed; refresh it');transition(maintenanceTransitions,r.status,x.status);await c.query('UPDATE maintenance SET status=$2,version=version+1,assignee=coalesce($3,assignee),public_note=coalesce($4,public_note),internal_note=coalesce($5,internal_note) WHERE id=$1',[id,x.status,x.assignee,x.publicNote,x.internalNote]);await event(c,a,id,'maintenance.'+x.status);return data({id,status:x.status,version:r.version+1});});}
}
