import {managementGrantPage,statementQuery} from '@haven/contracts';
import {managementPortfolio} from './grants.js';
import {Controller,Get,Param,Req,Query,Res,Inject} from '@nestjs/common';
import type {FastifyRequest,FastifyReply} from 'fastify';
import {z} from 'zod';
import {leaseStatement,statementCSV,statementHTML} from './statements.js';
import {Identity,data,transaction} from '../platform/core.js';
const roles=['property_manager','admin'];
const finance=['finance'];
@Controller('api/v1')
export class ManagementController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/managed-properties') async properties(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,roles),x=managementGrantPage.parse(input);return transaction(a,async c=>data(await managementPortfolio(c,x.page),{page:x.page,limit:20}));}
 @Get('ops/tenants') async tenants(@Req() req:FastifyRequest){const a=await this.identity.actor(req,roles);return transaction(a,async c=>data((await c.query('SELECT id,name,email,user_id FROM tenants')).rows));}
 @Get('ops/leases') async leases(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['property_manager','finance','admin']);return transaction(a,async c=>data((await c.query('SELECT l.*,t.name AS tenant,co.name AS community FROM leases l JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id ORDER BY l.start_date DESC')).rows));}
 @Get('me/owner-leases') async ownerLeases(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req),x=managementGrantPage.parse(input);return transaction(a,async c=>data((await c.query('SELECT l.id,l.start_date::text,l.end_date::text,l.rent::text,l.currency,l.status,co.name AS community FROM leases l JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE management_owner_lease_access(l.id) ORDER BY l.start_date DESC,l.id DESC LIMIT 20 OFFSET $1',[(x.page-1)*20])).rows,{page:x.page,limit:20}));}
 @Get('ops/charges') async charges(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['property_manager','finance','admin']);return transaction(a,async c=>data((await c.query('SELECT ch.*,co.name AS community FROM charges ch JOIN leases l ON l.id=ch.lease_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id ORDER BY ch.due_date DESC')).rows));}
 @Get('ops/payment-records') async payments(@Req() req:FastifyRequest){const a=await this.identity.actor(req,finance);return transaction(a,async c=>data((await c.query('SELECT * FROM payments ORDER BY created_at DESC')).rows));}
 @Get('me/leases') async tenantLeases(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query("SELECT l.id,l.start_date,l.end_date,l.rent::text,l.currency,l.status,co.name AS community FROM leases l JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE t.user_id=$1 AND l.status IN ('active','ended')",[a.id])).rows));}
 @Get('me/charges') async tenantCharges(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT ch.id,ch.lease_id,ch.period,ch.due_date,ch.amount::text,ch.currency,ch.kind,ch.reverses_id FROM charges ch JOIN leases l ON l.id=ch.lease_id JOIN tenants t ON t.id=l.tenant_id WHERE t.user_id=$1 ORDER BY ch.due_date DESC',[a.id])).rows));}
 @Get('leases/:id/statement') async statement(@Req() req:FastifyRequest,@Param('id') id:string,@Query() input:unknown={}){const a=await this.identity.actor(req),x=statementQuery.parse(input);return transaction(a,async c=>data(await leaseStatement(c,z.uuid().parse(id),x)));}
 @Get('leases/:id/statement.csv') async statementCSV(@Req() req:FastifyRequest,@Param('id') id:string,@Query() input:unknown={},@Res() reply:FastifyReply){const a=await this.identity.actor(req),x=statementQuery.parse(input);return transaction(a,async c=>{const r=await leaseStatement(c,z.uuid().parse(id),x,true);return reply.header('Content-Type','text/csv; charset=utf-8').header('Cache-Control','no-store').header('Content-Disposition','attachment; filename="lease-statement.csv"').send(statementCSV(r));});}
 @Get('leases/:id/statement/print') async statementPrint(@Req() req:FastifyRequest,@Param('id') id:string,@Query() input:unknown={},@Res() reply:FastifyReply){const a=await this.identity.actor(req),x=statementQuery.parse(input);return transaction(a,async c=>{const r=await leaseStatement(c,z.uuid().parse(id),x,true);return reply.header('Content-Type','text/html; charset=utf-8').header('Cache-Control','no-store').header('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'").send(statementHTML(r));});}
}
