import type pg from 'pg';
import {managementDashboardQuery,managementDashboardRecord} from '@haven/contracts';
import {fail} from '../platform/core.js';
export async function managementDashboard(c:pg.PoolClient,input:unknown={}){
 const x=managementDashboardQuery.parse(input),date=x.date||new Date().toISOString().slice(0,10);if(date>new Date().toISOString().slice(0,10))fail(400,'Choose today or an earlier recorded date');
 if(!(await c.query('SELECT management_inviter_lock(org_id()) OR management_finance_lock(org_id()) AS admitted')).rows[0].admitted)fail(403,'A current manager or finance membership in the selected management organization is required');
 // Materialize each charge balance once; disable per-request JIT compilation
 // for the RLS-expanded report plan rather than paying compilation for every refresh.
 await c.query('SET LOCAL jit=off');
 const r=(await c.query(`WITH portfolio AS(SELECT DISTINCT g.unit_id FROM management_grants g WHERE g.organization_id=org_id() AND management_grant_valid(g.id)),occupation AS(SELECT management_unit_occupation_on(unit_id,$1::date) state FROM portfolio),contracts AS(SELECT l.id,l.currency FROM leases l JOIN portfolio p ON p.unit_id=l.unit_id WHERE l.organization_id=org_id() AND l.status IN('active','ended')),originals AS(SELECT ch.* FROM charges ch JOIN contracts l ON l.id=ch.lease_id WHERE ch.status='posted' AND ch.reverses_id IS NULL AND ch.created_at<($1::date+1)::timestamp AT TIME ZONE 'UTC'),balances AS MATERIALIZED(
 SELECT ch.id,ch.currency,$1::date-ch.due_date AS age,greatest(ch.amount-coalesce((SELECT sum(rv.amount) FROM charges rv WHERE rv.reverses_id=ch.id AND rv.status='posted' AND rv.created_at<($1::date+1)::timestamp AT TIME ZONE 'UTC'),0)-coalesce((SELECT sum(a.amount) FROM allocations a JOIN payments p ON p.id=a.payment_id WHERE a.charge_id=ch.id AND a.created_at<($1::date+1)::timestamp AT TIME ZONE 'UTC' AND (a.reversed_at IS NULL OR a.reversed_at>=($1::date+1)::timestamp AT TIME ZONE 'UTC') AND p.status='posted' AND p.lease_id=ch.lease_id AND p.currency=ch.currency AND coalesce(p.posted_at,p.created_at)<($1::date+1)::timestamp AT TIME ZONE 'UTC'),0),0) amount FROM originals ch
 ),currency_sums AS(SELECT currency,count(*) FILTER(WHERE amount>0)::int charges,round(coalesce(sum(amount) FILTER(WHERE age<=0),0),2)::text AS "notDue",round(coalesce(sum(amount) FILTER(WHERE age BETWEEN 1 AND 30),0),2)::text AS "days1to30",round(coalesce(sum(amount) FILTER(WHERE age BETWEEN 31 AND 60),0),2)::text AS "days31to60",round(coalesce(sum(amount) FILTER(WHERE age BETWEEN 61 AND 90),0),2)::text AS "days61to90",round(coalesce(sum(amount) FILTER(WHERE age>90),0),2)::text AS "daysOver90",round(coalesce(sum(amount),0),2)::text AS total FROM balances GROUP BY currency)
 SELECT org_id() AS "organizationId",statement_timestamp()::text AS "asOf",jsonb_build_object('units',(SELECT count(*)::int FROM portfolio),'occupied',(SELECT count(*)::int FROM occupation WHERE state='occupied'),'vacant',(SELECT count(*)::int FROM occupation WHERE state='vacant'),'unknownHistory',(SELECT count(*)::int FROM occupation WHERE state='unknown')) AS occupancy,coalesce((SELECT jsonb_agg(to_jsonb(s) ORDER BY currency) FROM currency_sums s),'[]') AS arrears,management_maintenance_counts_on($1::date) AS maintenance,EXISTS(SELECT 1 FROM originals ch JOIN contracts l ON l.id=ch.lease_id WHERE ch.currency<>l.currency) OR EXISTS(SELECT 1 FROM allocations a JOIN originals ch ON ch.id=a.charge_id JOIN payments p ON p.id=a.payment_id WHERE a.created_at<($1::date+1)::timestamp AT TIME ZONE 'UTC' AND (p.currency<>ch.currency OR p.lease_id<>ch.lease_id)) AS mixed`,[date])).rows[0];
 if(r.mixed)fail(409,'Historical financial currencies or allocation links conflict with their leases. Request a ledger review');
 return managementDashboardRecord.parse({...r,date,timeZone:'UTC',definitions:{scope:'Current selected management organization and current valid property grants; revoked or foreign properties are excluded even for historical dates.',occupancy:'Granted unit records, including rooms, at the end of the selected UTC date. Recorded activation and ending timestamps bound contract terms; parent/room exclusive occupation also blocks the related unit. Undated ended-contract history is unknown and excluded from vacant.',arrears:'Outstanding posted original charges recorded through the selected UTC day, less linked charge reversals and allocations effective that day. Payment evidence alone does not settle rent. Later allocation undo restores debt. Positive balances age by due date; today/future due dates are not due. Currencies remain separate; deposits are excluded.',maintenance:'Latest immutable maintenance status recorded through the selected UTC day. Requests without a dated public history are counted as unknown, not assigned an invented past status. No private text or identities are projected.'}});
}
