import {Controller,Get,Post,Param,Query,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event} from '@haven/database';
import {depositMovement,depositLedgerQuery} from '@haven/contracts';
import {source} from './payment-evidence.js';
import {financialLock} from './payment-allocations.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const fields='id,lease_id AS "leaseId",version,kind,direction,amount::text,currency,reason,actor_id AS "actorId",created_at AS at,liability_version AS "liabilityVersion",held_before::text AS "heldBefore",held_after::text AS "heldAfter",(liability_version IS NOT NULL) AS native';
async function totals(c:pg.PoolClient,id:string){return (await c.query("SELECT count(*)::int AS version,coalesce(sum(CASE WHEN coalesce(direction,CASE WHEN kind='received' THEN 'increase' ELSE 'decrease' END)='increase' THEN amount ELSE -amount END),0)::numeric(18,2)::text AS held FROM deposits WHERE lease_id=$1",[id])).rows[0];}
@Controller('api/v1')
export class DepositsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/leases/:leaseId/deposit-ledger') async ledger(@Req() req:FastifyRequest,@Param('leaseId') id:string,@Query() input:unknown={}){const a=await this.identity.actor(req,['finance']),x=depositLedgerQuery.parse(input);z.uuid().parse(id);return transaction(a,async c=>{await financialLock(c,id);const {org:_org,...s}=await source(c,a,id),t=await totals(c,id),items=(await c.query('SELECT '+fields+' FROM deposits WHERE lease_id=$1 ORDER BY created_at DESC,id DESC LIMIT 20 OFFSET $2',[id,(x.page-1)*20])).rows;return data({...s,liabilityVersion:t.version,held:t.held,page:x.page,limit:20,total:t.version,items,note:'Recorded deposit liability only; deposits are excluded from rent income. No funds are transferred. Historical adjustments without direction retain the prior decrease convention.'});});}
 @Post('ops/deposits') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=depositMovement.parse(body);return transaction(a,async c=>{await source(c,a,x.leaseId);return idempotent(c,a,req,x,async()=>{await financialLock(c,x.leaseId);const s=await source(c,a,x.leaseId),t=await totals(c,x.leaseId);if(s.leaseVersion!==x.leaseVersion||s.unitVersion!==x.unitVersion||s.grantVersion!==x.grantVersion||t.version!==x.liabilityVersion)fail(409,'Lease, grant or deposit liability changed. Refresh the ledger');if(s.currency!==x.currency)fail(400,'Deposit currency must match the lease');const held=(await c.query('SELECT ($1::numeric+CASE WHEN $2=\'increase\' THEN $3::numeric ELSE -$3::numeric END)::numeric(18,2)::text AS amount,($1::numeric+CASE WHEN $2=\'increase\' THEN $3::numeric ELSE -$3::numeric END)<0 AS exceeds',[t.held,x.direction,x.amount])).rows[0];if(held.exceeds)fail(409,'Release or decrease exceeds held deposit');const r=(await c.query('INSERT INTO deposits(lease_id,organization_id,kind,direction,amount,currency,reason,actor_id,liability_version,lease_version,unit_version,grant_version,held_before,held_after) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING '+fields,[x.leaseId,s.org,x.kind,x.direction,x.amount,x.currency,x.reason,a.id,t.version+1,x.leaseVersion,x.unitVersion,x.grantVersion,t.held,held.amount])).rows[0];await event(c,a,r.id,'deposit.'+x.kind,{leaseId:x.leaseId,liabilityVersion:r.liabilityVersion,direction:x.direction,heldBefore:t.held,heldAfter:held.amount});return data(r);});});}
}
