import {Controller,Get,Post,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event,type Actor} from '@haven/database';
import {financialRecordType,financialReversal} from '@haven/contracts';
import {source} from './payment-evidence.js';
import {financialLock} from './payment-allocations.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
type RecordType='charge'|'payment';
const table=(type:RecordType)=>type==='charge'?'charges':'payments';
async function root(c:pg.PoolClient,type:RecordType,id:string,lock=false){const r=(await c.query(`SELECT * FROM ${table(type)} WHERE id=$1${lock?' FOR UPDATE':''}`,[id])).rows[0];if(!r)fail(404,'Granted financial record not found');return r;}
async function detail(c:pg.PoolClient,a:Actor,type:RecordType,id:string){const r=await root(c,type,id),{org:_org,...s}=await source(c,a,r.lease_id),reversal=(await c.query(`SELECT r.id,r.created_at AS at,e.reason,e.actor_id AS "actorId",(e.original_id IS NOT NULL) AS native FROM ${table(type)} r LEFT JOIN financial_reversal_evidence e ON e.reversal_id=r.id WHERE r.reverses_id=$1`,[id])).rows[0];if(reversal){const audit=(await c.query("SELECT payload->'undoneAllocationIds' AS ids FROM outbox WHERE aggregate_id=$1 AND kind=$2 AND payload->>'reversalId'=$3 ORDER BY created_at,id LIMIT 1",[id,type+'.reversed',reversal.id])).rows[0];reversal.undoneAllocationIds=audit?.ids||[];}return {id,recordType:type,version:r.version,...s,currency:r.currency,amount:r.amount,reference:type==='payment'?r.reference:String(r.period).slice(0,10)+' · '+r.kind,eligible:r.status==='posted'&&!r.reverses_id&&!reversal,reversesId:r.reverses_id,reversal:reversal||null};}
@Controller('api/v1')
export class FinancialReversalsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/financial-records/:recordType/:id/reversal') async read(@Req() req:FastifyRequest,@Param('recordType') recordType:string,@Param('id') id:string){const a=await this.identity.actor(req,['finance']),type=financialRecordType.parse(recordType);z.uuid().parse(id);return transaction(a,async c=>data(await detail(c,a,type,id)));}
 @Post('ops/charges/:id/reverse') async reverseCharge(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=financialReversal.parse(body);return this.reverse(req,a,'charge',z.uuid().parse(id),x);}
 @Post('ops/payment-records/:id/reverse') async reversePayment(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=financialReversal.parse(body);return this.reverse(req,a,'payment',z.uuid().parse(id),x);}
 private async reverse(req:FastifyRequest,a:Actor,type:RecordType,id:string,x:z.infer<typeof financialReversal>){return transaction(a,async c=>{await detail(c,a,type,id);return idempotent(c,a,req,x,async()=>{const hint=await root(c,type,id);await financialLock(c,hint.lease_id);const r=await root(c,type,id,true),s=await source(c,a,r.lease_id);if(r.version!==x.version||s.leaseVersion!==x.leaseVersion||s.unitVersion!==x.unitVersion||s.grantVersion!==x.grantVersion)fail(409,'Financial record or property authority changed. Refresh the reversal');if(r.status!=='posted'||r.reverses_id)fail(409,'Only an original posted record can be reversed');const existing=(await c.query(`SELECT id FROM ${table(type)} WHERE reverses_id=$1`,[id])).rows[0];if(existing){const evidence=(await c.query('SELECT reason FROM financial_reversal_evidence WHERE reversal_id=$1',[existing.id])).rows[0];if(evidence&&evidence.reason!==x.reason)fail(409,'This record already has a retained reversal reason');return data(await detail(c,a,type,id));}const reversalId=crypto.randomUUID();await c.query('INSERT INTO financial_reversal_evidence(record_type,original_id,reversal_id,organization_id,lease_id,original_version,lease_version,unit_version,grant_version,reason,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[type,id,reversalId,s.org,r.lease_id,r.version,x.leaseVersion,x.unitVersion,x.grantVersion,x.reason,a.id]);if(type==='payment')await c.query("INSERT INTO payments(id,lease_id,organization_id,amount,currency,source,reference,actor_id,reverses_id,lease_version,unit_version,grant_version,posted_at,posted_by) VALUES($1,$2,$3,$4,$5,'reversal',$6,$7,$8,$9,$10,$11,statement_timestamp(),$7)",[reversalId,r.lease_id,r.organization_id,r.amount,r.currency,x.reason,a.id,id,x.leaseVersion,x.unitVersion,x.grantVersion]);else await c.query("INSERT INTO charges(id,lease_id,organization_id,period,due_date,amount,currency,kind,reverses_id,generated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[reversalId,r.lease_id,r.organization_id,r.period,r.due_date,r.amount,r.currency,'reversal:'+id,id,a.id]);const undone=(await c.query(`UPDATE allocations SET reversed_at=statement_timestamp(),reversed_by=$2,version=version+1 WHERE ${type==='payment'?'payment_id':'charge_id'}=$1 AND reversed_at IS NULL RETURNING id`,[id,a.id])).rows.map(v=>v.id);await event(c,a,id,type+'.reversed',{reversalId,originalVersion:r.version,leaseId:r.lease_id,undoneAllocationIds:undone});return data(await detail(c,a,type,id));});});}
}
