import {Controller,Get,Post,Patch,Param,Req,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event,type Actor} from '@haven/database';
import {managementGrantCreate,managementGrantUpdate,managementGrantPage} from '@haven/contracts';
import {managementOwnerUnits,managementOwnerUnit} from '../inventory/management-authority.js';
import {Identity,transaction,data,fail,idempotent} from '../platform/core.js';
const currentProjection=`SELECT g.id,g.unit_id,g.organization_id,o.name AS organization,management_owner_label(g.id) AS owner,g.version,g.status,g.starts_at,g.expires_at,g.created_at IS NULL AS historical,management_grant_valid(g.id) AS effective,(g.unit_snapshot->>'version')::int AS "unitVersion",g.owner_authority_version AS "ownerGrantVersion",co.name AS community,ci.slug AS city,ci.currency,u.area::text,u.beds,coalesce((SELECT jsonb_agg(jsonb_build_object('version',a.grant_version,'action',a.action,'note',a.note,'at',a.at) ORDER BY a.grant_version) FROM management_grant_activity a WHERE a.grant_id=g.id),'[]') AS activity FROM management_grants g JOIN units u ON u.id=g.unit_id JOIN communities co ON co.id=u.community_id JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id JOIN organizations o ON o.id=g.organization_id`;
const projection=currentProjection.replace('co.name AS community,ci.slug AS city,ci.currency,u.area::text,u.beds',"coalesce(g.unit_snapshot->>'community',co.name) AS community,coalesce(g.unit_snapshot->>'city',ci.slug) AS city,coalesce(g.unit_snapshot->>'currency',ci.currency) AS currency,coalesce(g.unit_snapshot->>'area',u.area::text) AS area,coalesce((g.unit_snapshot->>'beds')::int,u.beds) AS beds");
export async function managementPortfolio(c:pg.PoolClient,page=1){return (await c.query(currentProjection.replace("(g.unit_snapshot->>'version')::int",'u.version')+' WHERE management_grant_valid(g.id) AND (management_team(g.organization_id) OR management_admin()) ORDER BY co.name,g.unit_id,g.id LIMIT 20 OFFSET $1',[(page-1)*20])).rows;}
async function record(c:pg.PoolClient,id:string,professional=false){const r=(await c.query((professional?currentProjection:projection)+` WHERE g.id=$1 AND ${professional?'management_grant_valid(g.id) AND (management_team(g.organization_id) OR management_admin())':'g.owner_id=actor_id()'}`,[id])).rows[0];if(!r)fail(404,'Management grant not found');return r;}
async function destination(c:pg.PoolClient,id:string){const name=(await c.query('SELECT management_destination($1) name',[id])).rows[0].name;if(!name)fail(404,'This management organization is not currently available');return name;}
function validateExpiry(value:string){if(Date.parse(value)<=Date.now())fail(400,'Choose a future expiry for this management grant');}
@Controller('api/v1')
export class ManagementGrantsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('me/management-grant-units') async units(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,['owner']),x=managementGrantPage.parse(input);return transaction(a,async c=>data(await managementOwnerUnits(c,a,x.page),{page:x.page,limit:20}));}
 @Get('me/management-grant-units/:id') async unit(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['owner']);return transaction(a,async c=>{const snapshot=(await c.query('SELECT owner_management_unit($1) AS snapshot',[z.uuid().parse(id)])).rows[0].snapshot;if(!snapshot)fail(404,'A current owner authorization for this unit is required');return data(snapshot);});}
 @Get('me/management-organizations') async organizations(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['owner']);return transaction(a,async c=>data((await c.query("SELECT o.id,o.name FROM organizations o WHERE o.type='manager' AND management_destination(o.id) IS NOT NULL ORDER BY o.name,o.id LIMIT 100")).rows));}
 @Get('me/management-grants') async list(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req),x=managementGrantPage.parse(input);return transaction(a,async c=>data((await c.query(projection+' WHERE g.owner_id=actor_id() ORDER BY g.expires_at DESC,g.id LIMIT 20 OFFSET $1',[(x.page-1)*20])).rows,{page:x.page,limit:20}));}
 @Get('me/management-grants/:id') async detail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>data(await record(c,z.uuid().parse(id))));}
 @Get('ops/managed-properties/:id') async professional(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['property_manager','admin']);return transaction(a,async c=>data(await record(c,z.uuid().parse(id),true)));}
 @Post('me/management-grants') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['owner']),x=managementGrantCreate.parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{validateExpiry(x.expiresAt);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['management-unit:'+x.organizationId+':'+x.unitId]);const unit=await managementOwnerUnit(c,a,x.unitId,x.unitVersion,x.ownerGrantVersion);await destination(c,x.organizationId);if((await c.query('SELECT id FROM management_grants WHERE unit_id=$1 AND organization_id=$2',[x.unitId,x.organizationId])).rowCount)fail(409,'A management grant already records this unit and organization. Renew its existing record or request an owner-link review.');const r=(await c.query(`INSERT INTO management_grants(unit_id,organization_id,owner_id,expires_at,starts_at,owner_authority_id,owner_authority_version,unit_snapshot,consent_at,created_at,updated_at) VALUES($1,$2,$3,$4,now(),$5,$6,$7,now(),now(),now()) RETURNING id`,[x.unitId,x.organizationId,a.id,x.expiresAt,unit.ownerGrantId,unit.ownerGrantVersion,unit])).rows[0];await activity(c,a,r.id,1,'granted','Owner authorized this management organization until the recorded expiry.');return data(await record(c,r.id));}));}
 @Patch('me/management-grants/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['owner']),x=managementGrantUpdate.parse(body);z.uuid().parse(id);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const g=(await c.query('SELECT * FROM management_grants WHERE id=$1 AND owner_id=actor_id() FOR UPDATE',[id])).rows[0];if(!g)fail(404,'Management grant not found');if(g.version!==x.version)fail(409,'Management grant changed. Refresh before updating');if(x.action==='revoke'){if(g.status!=='active')fail(409,'This grant is already revoked');await c.query("UPDATE management_grants SET status='revoked',version=version+1,updated_at=now() WHERE id=$1",[id]);await activity(c,a,id,g.version+1,'revoked',x.reason);}else{validateExpiry(x.expiresAt);const unit=await managementOwnerUnit(c,a,g.unit_id,x.unitVersion,x.ownerGrantVersion);await destination(c,g.organization_id);await c.query("UPDATE management_grants SET status='active',starts_at=now(),expires_at=$2,owner_authority_id=$3,owner_authority_version=$4,unit_snapshot=$5,consent_at=now(),updated_at=now(),version=version+1 WHERE id=$1",[id,x.expiresAt,unit.ownerGrantId,unit.ownerGrantVersion,unit]);await activity(c,a,id,g.version+1,'renewed','Owner renewed this management organization’s authorization until the recorded expiry.');}return data(await record(c,id));}));}
}
async function activity(c:pg.PoolClient,a:Actor,id:string,version:number,action:string,note:string){await c.query('INSERT INTO management_grant_activity(grant_id,grant_version,action,note,actor_id) VALUES($1,$2,$3,$4,$5)',[id,version,action,note,a.id]);await event(c,a,id,'management-grant.'+action,{version});}
