import {withdrawLeaseOffers} from '../inventory/lease-availability.js';
import {Controller,Get,Post,Patch,Param,Req,Res,Body,Inject} from '@nestjs/common';
import type {FastifyRequest,FastifyReply} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event,type Actor} from '@haven/database';
import {leaseDraftCreate,leaseDraftUpdate,leaseActivation} from '@haven/contracts';
import {leaseDocument,leaseUnit} from '../inventory/lease-documents.js';
import {readPrivateObject} from '../inventory/media.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
export async function manager(c:pg.PoolClient,a:Actor){if(!a.orgId||!(await c.query('SELECT management_inviter_lock($1) valid',[a.orgId])).rows[0].valid)fail(403,'Current property manager membership required');return a.orgId;}
export async function source(c:pg.PoolClient,a:Actor,unitId:string){const org=await manager(c,a),admission=(await c.query('SELECT management_unit_grant_lock($1,$2) version',[unitId,org])).rows[0].version;if(admission===null)fail(404,'Current management property grant required');const unit=await leaseUnit(c,unitId,org),grant=(await c.query('SELECT id,version FROM management_grants WHERE unit_id=$1 AND organization_id=$2 AND management_grant_valid(id)',[unitId,org])).rows[0];return {unit,grant,org};}
export async function detail(c:pg.PoolClient,id:string){const row=(await c.query(`SELECT l.id,l.unit_id AS "unitId",l.tenant_id AS "tenantId",l.version,l.status,co.name AS community,t.name AS tenant,l.unit_version AS "unitVersion",l.grant_version AS "grantVersion",l.tenant_version AS "tenantVersion",l.start_date::text AS "startDate",l.end_date::text AS "endDate",l.rent::text,l.currency,l.rent_period AS "rentPeriod",l.due_day AS "dueDay",coalesce((SELECT jsonb_agg(jsonb_build_object('assetId',d.asset_id,'version',d.asset_version,'label',d.label,'url','/api/v1/ops/leases/'||l.id||'/documents/'||d.asset_id) ORDER BY d.asset_id) FROM lease_documents d WHERE d.lease_id=l.id),'[]') AS documents,coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'action',h.action,'at',h.at) ORDER BY h.version) FROM lease_draft_history h WHERE h.lease_id=l.id),'[]') AS activity FROM leases l JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE l.id=$1 AND l.drafted_by IS NOT NULL AND management_unit_granted(l.unit_id,l.organization_id)`,[id])).rows[0];if(!row)fail(404,'Native managed lease draft not found');return row;}
export async function terms(c:pg.PoolClient,a:Actor,unitId:string,tenantId:string,x:{unitVersion:number;grantVersion:number;tenantVersion:number;currency:string}){const s=await source(c,a,unitId);if(s.unit.version!==x.unitVersion||s.grant.version!==x.grantVersion)fail(409,'Property or grant changed. Refresh before saving');if(s.unit.currency!==x.currency)fail(400,'Lease currency must match the canonical property market');const t=(await c.query('SELECT id,version FROM tenants WHERE id=$1 AND organization_id=$2',[tenantId,s.org])).rows[0];if(!t||!(await c.query('SELECT management_tenant_unit_authorized($1,$2,$3) valid',[tenantId,unitId,s.org])).rows[0].valid)fail(404,'Verified tenant link for this property is required');if(t.version!==x.tenantVersion)fail(409,'Tenant profile changed. Refresh before saving');return s;}
export async function documents(c:pg.PoolClient,a:Actor,id:string,entries:{assetId:string;version:number;label:string}[]){const existing=(await c.query('SELECT asset_id,asset_version FROM lease_documents WHERE lease_id=$1',[id])).rows;for(const d of entries){const retained=existing.some(e=>e.asset_id===d.assetId&&e.asset_version===d.version);await leaseDocument(c,a,d.assetId,d.version,!retained);if(retained)await c.query('UPDATE lease_documents SET label=$3 WHERE lease_id=$1 AND asset_id=$2',[id,d.assetId,d.label]);else await c.query('INSERT INTO lease_documents(lease_id,asset_id,asset_version,label) VALUES($1,$2,$3,$4)',[id,d.assetId,d.version,d.label]);}await c.query('DELETE FROM lease_documents WHERE lease_id=$1 AND NOT(asset_id=ANY($2::uuid[]))',[id,entries.map(d=>d.assetId)]);}

export async function history(c:pg.PoolClient,a:Actor,id:string,action:string){const row=await detail(c,id);await c.query('INSERT INTO lease_draft_history(lease_id,version,action,snapshot,actor_id) VALUES($1,$2,$3,$4,$5)',[id,row.version,action,row,a.id]);await event(c,a,id,'lease.'+action,{version:row.version});return row;}
@Controller('api/v1')
export class LeaseDraftsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/lease-draft-options/:unitId') async options(@Req() req:FastifyRequest,@Param('unitId') id:string){const a=await this.identity.actor(req,['property_manager']);return transaction(a,async c=>{const s=await source(c,a,z.uuid().parse(id));return data({unitId:id,unitVersion:s.unit.version,grantVersion:s.grant.version,currency:s.unit.currency,community:s.unit.community,tenants:(await c.query('SELECT t.id,t.name,t.version FROM tenants t JOIN(SELECT tenant_id AS id FROM tenant_invitations WHERE organization_id=$1 AND unit_id=$2 AND status=\'accepted\' AND management_grant_valid(grant_id) UNION SELECT tenant_id AS id FROM leases WHERE organization_id=$1 AND unit_id=$2) authorized ON authorized.id=t.id WHERE t.organization_id=$1 ORDER BY t.name,t.id LIMIT 100',[s.org,id])).rows});});}
 @Get('ops/lease-drafts/:id') async read(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['property_manager']);return transaction(a,async c=>{await manager(c,a);return data(await detail(c,z.uuid().parse(id)));});}
 @Post('ops/leases') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=leaseDraftCreate.parse(body);return transaction(a,async c=>{await source(c,a,x.unitId);return idempotent(c,a,req,x,async()=>{const s=await terms(c,a,x.unitId,x.tenantId,x);for(const d of x.documents)await leaseDocument(c,a,d.assetId,d.version);const l=(await c.query('INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency,drafted_by,management_grant_id,grant_version,unit_version,tenant_version,rent_period,due_day) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id',[s.org,x.unitId,x.tenantId,x.startDate,x.endDate,x.rent,x.currency,a.id,s.grant.id,x.grantVersion,x.unitVersion,x.tenantVersion,x.rentPeriod,x.dueDay])).rows[0];await documents(c,a,l.id,x.documents);await history(c,a,l.id,'drafted');return data(await detail(c,l.id));});});}
 @Patch('ops/lease-drafts/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=leaseDraftUpdate.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await manager(c,a);await detail(c,id);return idempotent(c,a,req,x,async()=>{const l=(await c.query('SELECT * FROM leases WHERE id=$1 AND drafted_by IS NOT NULL FOR UPDATE',[id])).rows[0];if(!l)fail(404,'Native lease draft not found');if(l.status!=='draft'||l.version!==x.version)fail(409,'Lease changed or is no longer a draft');await terms(c,a,l.unit_id,l.tenant_id,x);await c.query('UPDATE leases SET start_date=$2,end_date=$3,rent=$4,currency=$5,grant_version=$6,unit_version=$7,tenant_version=$8,rent_period=$9,due_day=$10,version=version+1 WHERE id=$1',[id,x.startDate,x.endDate,x.rent,x.currency,x.grantVersion,x.unitVersion,x.tenantVersion,x.rentPeriod,x.dueDay]);await documents(c,a,id,x.documents);await history(c,a,id,'draft_updated');return data(await detail(c,id));});});}
 @Post('ops/leases/:id/activate') async activate(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=leaseActivation.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await manager(c,a);await detail(c,id);return idempotent(c,a,req,x,async()=>{const org=await manager(c,a),resource=(await c.query('SELECT unit_id,status FROM leases WHERE id=$1 AND organization_id=$2 AND drafted_by IS NOT NULL',[id,org])).rows[0];if(!resource)fail(404,'Native managed lease not found');if(resource.status!=='draft')fail(409,'Lease is no longer a draft');await c.query('SELECT lock_rental_scope($1)',[resource.unit_id]);const l=(await c.query('SELECT *,start_date::text AS starts,end_date::text AS ends FROM leases WHERE id=$1 AND organization_id=$2 FOR UPDATE',[id,org])).rows[0];if(l.version!==x.version||l.status!=='draft')fail(409,'Lease changed or is no longer a draft');if(l.unit_version!==x.unitVersion||l.grant_version!==x.grantVersion||l.tenant_version!==x.tenantVersion)fail(409,'Refresh and save the current draft authority before activating');const current=await terms(c,a,l.unit_id,l.tenant_id,{...x,currency:l.currency});const today=(await c.query('SELECT (statement_timestamp() AT TIME ZONE $1)::date::text AS today',[current.unit.timezone])).rows[0].today;if(l.ends<today)fail(409,'An expired lease term cannot be activated');if(!(await c.query('SELECT rental_lease_interval_free($1,$2,$3,$4) valid',[l.unit_id,l.starts,l.ends,id])).rows[0].valid)fail(409,'An exclusive tenancy overlaps this term');await c.query("UPDATE leases SET status='active',version=version+1 WHERE id=$1",[id]);await withdrawLeaseOffers(c,a,l.unit_id,org);await history(c,a,id,'activated');return data(await detail(c,id));});});}
 @Get('ops/leases/:leaseId/documents/:id') async download(@Req() req:FastifyRequest,@Param('leaseId') leaseId:string,@Param('id') id:string,@Res() reply:FastifyReply){const a=await this.identity.actor(req,['property_manager']);return transaction(a,async c=>{await manager(c,a);const root=await detail(c,z.uuid().parse(leaseId));await source(c,a,root.unitId);const d=(await c.query('SELECT asset_version FROM lease_documents WHERE lease_id=$1 AND asset_id=$2',[leaseId,z.uuid().parse(id)])).rows[0];if(!d)fail(404,'Lease document not found');const m=await leaseDocument(c,a,id,d.asset_version,false),bytes=await readPrivateObject('quarantine/'+m.object_key);await event(c,a,leaseId,'lease.document_downloaded');return reply.header('Content-Type','application/pdf').header('Content-Disposition','attachment; filename="lease-document.pdf"').header('Cache-Control','no-store').send(bytes);});}
}
