import {Controller,Get,Post,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event} from '@haven/database';
import {leaseRenewal,leaseEnding} from '@haven/contracts';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
import {manager,source,terms,documents,history,detail} from './lease-drafts.js';
async function workflow(c:pg.PoolClient,id:string){const l=(await c.query(`SELECT l.id,l.version,l.status,l.unit_id AS "unitId",l.tenant_id AS "tenantId",co.name AS community,t.name AS tenant,l.start_date::text AS "startDate",l.end_date::text AS "endDate",l.rent::text,l.currency,l.due_day AS "dueDay",(l.drafted_by IS NOT NULL) AS native,(SELECT previous_lease_id FROM lease_renewals WHERE lease_id=l.id) AS "previousLeaseId",(SELECT lease_id FROM lease_renewals WHERE previous_lease_id=l.id) AS "nextLeaseId",(SELECT jsonb_build_object('version',e.version,'kind',e.kind,'reason',e.reason,'at',e.at,'availabilityReviewRequired',e.availability_review_required) FROM lease_endings e WHERE e.lease_id=l.id) AS ending,coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'action',h.action,'at',h.at,'reason',coalesce(h.snapshot->>'reason',(SELECT reason FROM lease_renewals r WHERE r.lease_id=l.id AND h.action='renewal_drafted'))) ORDER BY h.version) FROM lease_draft_history h WHERE h.lease_id=l.id),'[]') AS activity FROM leases l JOIN tenants t ON t.id=l.tenant_id JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE l.id=$1 AND management_unit_granted(l.unit_id,l.organization_id)`,[id])).rows[0];if(!l)fail(404,'Managed lease not found');return l;}
@Controller('api/v1')
export class LeaseLifecycleController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/leases/:id/workflow') async read(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['property_manager']);return transaction(a,async c=>{await manager(c,a);return data(await workflow(c,z.uuid().parse(id)));});}
 @Post('ops/leases/:id/renew') async renew(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=leaseRenewal.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await manager(c,a);await workflow(c,id);return idempotent(c,a,req,x,async()=>{const resource=await workflow(c,id);await c.query('SELECT lock_rental_scope($1)',[resource.unitId]);const l=(await c.query('SELECT *,end_date::text AS ends FROM leases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!l||l.version!==x.version||!['active','ended'].includes(l.status))fail(409,'Refresh the active or ended lease before renewal');if(x.startDate<=l.ends)fail(400,'The next term must start after the original end date');if((await c.query('SELECT 1 FROM lease_renewals WHERE previous_lease_id=$1',[id])).rowCount)fail(409,'This term already has a renewal. Open the retained next term');const s=await terms(c,a,l.unit_id,l.tenant_id,x);if(!(await c.query('SELECT rental_lease_interval_free($1,$2,$3,NULL) valid',[l.unit_id,x.startDate,x.endDate])).rows[0].valid)fail(409,'The next term overlaps another active tenancy');const next=(await c.query('INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency,drafted_by,management_grant_id,grant_version,unit_version,tenant_version,rent_period,due_day) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id',[s.org,l.unit_id,l.tenant_id,x.startDate,x.endDate,x.rent,x.currency,a.id,s.grant.id,x.grantVersion,x.unitVersion,x.tenantVersion,x.rentPeriod,x.dueDay])).rows[0];await documents(c,a,next.id,x.documents);await c.query('INSERT INTO lease_renewals(previous_lease_id,lease_id,previous_version,reason,actor_id) VALUES($1,$2,$3,$4,$5)',[id,next.id,l.version,x.reason,a.id]);await history(c,a,next.id,'renewal_drafted');await event(c,a,id,'lease.renewal_linked',{version:l.version,nextLease:next.id,reason:x.reason});return data(await detail(c,next.id));});});}
 @Post('ops/leases/:id/end') async end(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=leaseEnding.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await manager(c,a);await workflow(c,id);return idempotent(c,a,req,x,async()=>{const resource=await workflow(c,id);await c.query('SELECT lock_rental_scope($1)',[resource.unitId]);const l=(await c.query('SELECT * FROM leases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!l||l.status!=='active'||l.version!==x.version)fail(409,'Refresh the current active lease before ending');await source(c,a,l.unit_id);await c.query('INSERT INTO lease_endings(lease_id,version,kind,reason,actor_id) VALUES($1,$2,$3,$4,$5)',[id,l.version+1,x.kind,x.reason,a.id]);await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=$1",[id]);const row=await workflow(c,id);await c.query('INSERT INTO lease_draft_history(lease_id,version,action,snapshot,actor_id) VALUES($1,$2,$3,$4,$5)',[id,row.version,x.kind==='terminated'?'terminated':'ended',{...row,reason:x.reason},a.id]);await event(c,a,id,'lease.ended',{version:row.version,kind:x.kind,reason:x.reason,availabilityReviewRequired:true});return data(await workflow(c,id));});});}
}
