import {Controller,Get,Post,Patch,Param,Query,Req,Res,Body,Inject} from '@nestjs/common';
import type {FastifyRequest,FastifyReply} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event,type Actor} from '@haven/database';
import {maintenanceCreate,maintenanceWorkflow,maintenancePageQuery,maintenanceOptionsQuery,maintenanceTransitions,transition} from '@haven/contracts';
import {manager} from './lease-drafts.js';
import {leaseUnit} from '../inventory/lease-documents.js';
import {readPrivateObject} from '../inventory/media.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
async function source(c:pg.PoolClient,a:Actor,id:string,professional:boolean){if(!professional){const r=(await c.query('SELECT tenant_maintenance_source($1) AS source',[id])).rows[0].source;if(!r)fail(404,'Active linked lease with current property management authority required');return r;}const org=await manager(c,a),l=(await c.query("SELECT l.*,t.user_id FROM leases l JOIN tenants t ON t.id=l.tenant_id WHERE l.id=$1 AND l.organization_id=$2 AND l.status IN ('active','ended') FOR SHARE OF l,t",[id,org])).rows[0];if(!l)fail(404,'Currently managed lease required');const grant=(await c.query('SELECT management_unit_grant_lock($1,$2) AS version',[l.unit_id,org])).rows[0].version;if(grant===null)fail(404,'Current management grant required');const u=await leaseUnit(c,l.unit_id,org);return {leaseId:id,leaseVersion:l.version,unitId:l.unit_id,unitVersion:u.version,grantVersion:grant,organizationId:org,userId:l.user_id,community:u.community};}
async function compare(c:pg.PoolClient,a:Actor,id:string,professional:boolean,x:{leaseVersion:number;unitVersion:number;grantVersion:number|null}){const s=await source(c,a,id,professional);if(s.leaseVersion!==x.leaseVersion||s.unitVersion!==x.unitVersion||s.grantVersion!==x.grantVersion)fail(409,'Lease or property authority changed. Refresh maintenance options');return s;}
async function root(c:pg.PoolClient,id:string,lock=false){const r=(await c.query('SELECT * FROM maintenance WHERE id=$1 AND maintenance_scope(id)'+(lock?' FOR UPDATE':''),[id])).rows[0];if(!r)fail(404,'Authorized maintenance request not found');return r;}
async function detail(c:pg.PoolClient,a:Actor,id:string,professional:boolean){const r=await root(c,id);let s:any;if(professional)s=await source(c,a,r.lease_id,true);else{if(r.user_id!==a.id||!(await c.query('SELECT tenant_lease_lock($1) valid',[r.lease_id])).rows[0].valid)fail(404,'Own linked maintenance request not found');s=(await c.query('SELECT l.version AS "leaseVersion",u.version AS "unitVersion" FROM leases l JOIN units u ON u.id=l.unit_id WHERE l.id=$1',[r.lease_id])).rows[0];s.grantVersion=null;}const photos=(await c.query("SELECT p.asset_id AS id,m.version,p.caption,'/api/v1/maintenance/'||p.request_id||'/photos/'||p.asset_id AS url FROM maintenance_photos p CROSS JOIN LATERAL maintenance_private_photo(p.request_id,p.asset_id) m WHERE p.request_id=$1 ORDER BY p.asset_id",[id])).rows,activity=(await c.query('SELECT version,status,public_note AS "publicNote",at FROM maintenance_history WHERE request_id=$1 ORDER BY version',[id])).rows,assignees=professional?(await c.query("SELECT DISTINCT p.id,p.display_name AS name FROM profiles p JOIN memberships m ON m.user_id=p.id WHERE p.state='active' AND m.status='active' AND m.role='property_manager' AND m.organization_id=$1 ORDER BY p.display_name,p.id",[a.orgId])).rows:[],assigned=(await c.query('SELECT display_name AS name FROM profiles WHERE id=$1',[r.assignee_id])).rows[0]?.name||r.assignee||null;return {id,leaseId:r.lease_id,version:r.version,title:r.title,description:r.description,category:r.category,urgency:r.urgency,status:r.status,requestedBy:r.opened_by===null?'historical':r.opened_by===r.user_id?'tenant':'management',at:r.created_at,assignedTo:assigned,assigneeId:professional?r.assignee_id:null,publicNote:r.public_note,leaseVersion:s.leaseVersion,unitVersion:s.unitVersion,grantVersion:s.grantVersion,photos,activity,assignees};}
async function activity(c:pg.PoolClient,a:Actor,id:string){const r=await root(c,id);await c.query('INSERT INTO maintenance_history(request_id,version,status,public_note,assignee_id,actor_id,at) SELECT id,version,status,public_note,assignee_id,$2,updated_at FROM maintenance WHERE id=$1',[id,a.id]);await event(c,a,id,'maintenance.'+r.status,{version:r.version,leaseId:r.lease_id});}
@Controller('api/v1')
export class MaintenanceController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 private async options(req:FastifyRequest,input:unknown,professional:boolean){const a=await this.identity.actor(req,professional?['property_manager']:[]),x=maintenanceOptionsQuery.parse(input);return transaction(a,async c=>{if(professional)await manager(c,a);const rows=(await c.query("SELECT l.id FROM leases l WHERE "+(professional?"l.organization_id=$1 AND l.status IN ('active','ended') AND management_unit_granted(l.unit_id,l.organization_id)":"l.status='active' AND l.tenant_id IN (SELECT id FROM tenants WHERE user_id=$1::uuid) AND tenant_lease_access(l.id) AND tenant_maintenance_source(l.id) IS NOT NULL")+' AND ($3::uuid IS NULL OR l.id=$3) ORDER BY l.start_date DESC,l.id DESC LIMIT 20 OFFSET $2',professional?[a.orgId,(x.page-1)*20,x.leaseId||null]:[a.id,(x.page-1)*20,x.leaseId||null])).rows,items=[];for(const r of rows){const {organizationId:_org,userId:_user,...s}=await source(c,a,r.id,professional);items.push(s);}return data(items,{page:x.page,limit:20});});}
 @Get('me/maintenance-options') async tenantOptions(@Req() req:FastifyRequest,@Query() input:unknown={}){return this.options(req,maintenanceOptionsQuery.parse(input),false);}
 @Get('ops/maintenance-options') async professionalOptions(@Req() req:FastifyRequest,@Query() input:unknown={}){return this.options(req,maintenanceOptionsQuery.parse(input),true);}
 private async list(req:FastifyRequest,input:unknown,professional:boolean){const a=await this.identity.actor(req,professional?['property_manager']:[]),x=maintenancePageQuery.parse(input);return transaction(a,async c=>{if(professional)await manager(c,a);const filter=professional?'organization_id=$1':'user_id=$1',value=professional?a.orgId:a.id,total=(await c.query('SELECT count(*)::int n FROM maintenance WHERE '+filter+' AND maintenance_scope(id)',[value])).rows[0].n,rows=(await c.query('SELECT id FROM maintenance WHERE '+filter+' AND maintenance_scope(id) ORDER BY created_at DESC,id DESC LIMIT 20 OFFSET $2',[value,(x.page-1)*20])).rows,items=[];for(const r of rows)items.push(await detail(c,a,r.id,professional));return data({page:x.page,limit:20,total,items});});}
 @Get('me/maintenance') async tenantList(@Req() req:FastifyRequest,@Query() input:unknown={}){return this.list(req,maintenancePageQuery.parse(input),false);}
 @Get('ops/maintenance') async professionalList(@Req() req:FastifyRequest,@Query() input:unknown={}){return this.list(req,maintenancePageQuery.parse(input),true);}
 @Get('me/maintenance/:id') async tenantRead(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>data(await detail(c,a,z.uuid().parse(id),false)));}
 @Get('ops/maintenance/:id') async professionalRead(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['property_manager']);return transaction(a,async c=>{await manager(c,a);return data(await detail(c,a,z.uuid().parse(id),true));});}
 private async create(req:FastifyRequest,body:unknown,professional:boolean){const a=await this.identity.actor(req,professional?['property_manager']:[]),x=maintenanceCreate.parse(body);return transaction(a,async c=>{await source(c,a,x.leaseId,professional);return idempotent(c,a,req,x,async()=>{const s=await compare(c,a,x.leaseId,professional,x);for(const p of x.photos){const asset=(await c.query("SELECT id FROM media_assets WHERE id=$1 AND version=$2 AND owner_id=$3 AND visibility='private' AND purpose='photo' AND status='approved' AND scan_at IS NOT NULL AND variants->>'display' IS NOT NULL FOR SHARE",[p.assetId,p.version,a.id])).rows[0];if(!asset)fail(404,'Current owned scanned private photo required');}const r=(await c.query('INSERT INTO maintenance(lease_id,organization_id,user_id,title,description,category,urgency,opened_by,lease_version,unit_version,grant_version,updated_by,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$8,statement_timestamp()) RETURNING id',[x.leaseId,s.organizationId,s.userId,x.title,x.description,x.category,x.urgency,a.id,x.leaseVersion,x.unitVersion,x.grantVersion])).rows[0];for(const p of x.photos)await c.query('INSERT INTO maintenance_photos(request_id,asset_id,asset_version,caption,actor_id) VALUES($1,$2,$3,$4,$5)',[r.id,p.assetId,p.version,p.caption,a.id]);await activity(c,a,r.id);return data(await detail(c,a,r.id,professional));});});}
 @Post('me/maintenance') async tenantCreate(@Req() req:FastifyRequest,@Body() body:unknown){return this.create(req,maintenanceCreate.parse(body),false);}
 @Post('ops/maintenance') async professionalCreate(@Req() req:FastifyRequest,@Body() body:unknown){return this.create(req,maintenanceCreate.parse(body),true);}
 @Patch('ops/maintenance/:id') async change(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=maintenanceWorkflow.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await manager(c,a);await detail(c,a,id,true);return idempotent(c,a,req,x,async()=>{const r=await root(c,id,true);await compare(c,a,r.lease_id,true,x);if(r.version!==x.version)fail(409,'Maintenance request changed. Refresh its current version');transition(maintenanceTransitions,r.status,x.status);let assigned=null;if(x.assigneeId){assigned=(await c.query("SELECT p.display_name FROM profiles p JOIN memberships m ON m.user_id=p.id WHERE p.id=$1 AND p.state='active' AND m.status='active' AND m.organization_id=$2 AND m.role='property_manager' FOR SHARE OF p,m",[x.assigneeId,a.orgId])).rows[0];if(!assigned)fail(404,'Current same-team manager assignee required');}await c.query('UPDATE maintenance SET status=$2,assignee_id=$3,assignee=$4,public_note=coalesce($5,public_note),version=version+1,lease_version=$6,unit_version=$7,grant_version=$8,updated_by=$9,updated_at=statement_timestamp() WHERE id=$1',[id,x.status,x.assigneeId,assigned?.display_name||null,x.publicNote,x.leaseVersion,x.unitVersion,x.grantVersion,a.id]);await activity(c,a,id);return data(await detail(c,a,id,true));});});}
 @Get('maintenance/:requestId/photos/:id') async photo(@Req() req:FastifyRequest,@Param('requestId') requestId:string,@Param('id') id:string,@Res() reply:FastifyReply){const a=await this.identity.actor(req);z.uuid().parse(requestId);z.uuid().parse(id);return transaction(a,async c=>{const m=(await c.query('SELECT * FROM maintenance_private_photo($1,$2)',[requestId,id])).rows[0];if(!m)fail(404,'Authorized approved request photo not found');const bytes=await readPrivateObject(m.display_key);await event(c,a,requestId,'maintenance.photo_viewed');return reply.header('Content-Type','image/webp').header('Cache-Control','no-store').send(bytes);});}
}
