import {Controller,Get,Post,Patch,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event,type Actor} from '@haven/database';
import {paymentEvidenceCreate,paymentEvidenceUpdate,paymentEvidencePost} from '@haven/contracts';
import {leaseUnit} from '../inventory/lease-documents.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
async function finance(c:pg.PoolClient,a:Actor){if(!a.orgId||!(await c.query('SELECT management_finance_lock($1) valid',[a.orgId])).rows[0].valid)fail(403,'Current finance membership required');return a.orgId;}
async function source(c:pg.PoolClient,a:Actor,leaseId:string){const org=await finance(c,a),l=(await c.query("SELECT * FROM leases WHERE id=$1 AND organization_id=$2 AND status IN ('active','ended')",[leaseId,org])).rows[0];if(!l)fail(404,'Active or ended granted lease not found');const grant=(await c.query('SELECT management_unit_grant_lock($1,$2) version',[l.unit_id,org])).rows[0].version;if(grant===null)fail(404,'Current property finance authority required');const unit=await leaseUnit(c,l.unit_id,org);return {leaseId,leaseVersion:l.version,unitVersion:unit.version,grantVersion:grant,currency:l.currency,org};}
async function authority(c:pg.PoolClient,a:Actor,leaseId:string,x:{leaseVersion:number;unitVersion:number;grantVersion:number;currency?:string}){const s=await source(c,a,leaseId);if(s.leaseVersion!==x.leaseVersion||s.unitVersion!==x.unitVersion||s.grantVersion!==x.grantVersion)fail(409,'Lease or property authority changed. Refresh and save the current draft');if(x.currency!==undefined&&s.currency!==x.currency)fail(400,'Payment currency must match the lease');return s;}
async function detail(c:pg.PoolClient,id:string){const p=(await c.query(`SELECT p.id,p.lease_id AS "leaseId",p.version,p.status,p.amount::text,p.currency,p.source,p.reference,p.lease_version AS "leaseVersion",p.unit_version AS "unitVersion",p.grant_version AS "grantVersion",p.created_at AS "createdAt",p.posted_at AS "postedAt",p.posted_by AS "postedBy",(p.lease_version IS NOT NULL) AS native,coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'action',h.action,'at',h.at) ORDER BY h.version) FROM payment_evidence_history h WHERE h.payment_id=p.id),'[]') AS activity FROM payments p JOIN leases l ON l.id=p.lease_id WHERE p.id=$1 AND management_unit_granted(l.unit_id,l.organization_id)`,[id])).rows[0];if(!p)fail(404,'Managed payment evidence not found');return p;}
async function history(c:pg.PoolClient,a:Actor,id:string,action:string){const row=await detail(c,id);await c.query('INSERT INTO payment_evidence_history(payment_id,version,action,snapshot,actor_id) VALUES($1,$2,$3,$4,$5)',[id,row.version,action,row,a.id]);await event(c,a,id,action==='posted'?'payment.recorded':'payment.'+action,{version:row.version,status:row.status,leaseId:row.leaseId});return detail(c,id);}
@Controller('api/v1')
export class PaymentEvidenceController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/payment-evidence-options/:leaseId') async options(@Req() req:FastifyRequest,@Param('leaseId') id:string){const a=await this.identity.actor(req,['finance']);return transaction(a,async c=>{const {org:_org,...s}=await source(c,a,z.uuid().parse(id));return data(s);});}
 @Get('ops/payment-records/:id') async read(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['finance']);return transaction(a,async c=>{await finance(c,a);return data(await detail(c,z.uuid().parse(id)));});}
 @Post('ops/payment-records') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=paymentEvidenceCreate.parse(body);return transaction(a,async c=>{await source(c,a,x.leaseId);return idempotent(c,a,req,x,async()=>{await c.query('SELECT id FROM leases WHERE id=$1 FOR SHARE',[x.leaseId]);const s=await authority(c,a,x.leaseId,x),p=(await c.query("INSERT INTO payments(lease_id,organization_id,amount,currency,source,reference,actor_id,status,lease_version,unit_version,grant_version) VALUES($1,$2,$3,$4,$5,$6,$7,'draft',$8,$9,$10) RETURNING id",[x.leaseId,s.org,x.amount,x.currency,x.source,x.reference,a.id,x.leaseVersion,x.unitVersion,x.grantVersion])).rows[0];return data(await history(c,a,p.id,'drafted'));});});}
 @Patch('ops/payment-records/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=paymentEvidenceUpdate.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await finance(c,a);await detail(c,id);return idempotent(c,a,req,x,async()=>{const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p||p.status!=='draft'||p.version!==x.version)fail(409,'Refresh the current payment draft before editing');await authority(c,a,p.lease_id,x);await c.query('UPDATE payments SET amount=$2,currency=$3,source=$4,reference=$5,lease_version=$6,unit_version=$7,grant_version=$8,version=version+1 WHERE id=$1',[id,x.amount,x.currency,x.source,x.reference,x.leaseVersion,x.unitVersion,x.grantVersion]);return data(await history(c,a,id,'draft_updated'));});});}
 @Post('ops/payment-records/:id/post') async post(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=paymentEvidencePost.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await finance(c,a);await detail(c,id);return idempotent(c,a,req,x,async()=>{const p=(await c.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p||p.status!=='draft'||p.version!==x.version)fail(409,'Refresh the current unposted payment draft');if(p.lease_version!==x.leaseVersion||p.unit_version!==x.unitVersion||p.grant_version!==x.grantVersion)fail(409,'Save the current authority in the draft before posting');await authority(c,a,p.lease_id,{...x,currency:p.currency});await c.query("UPDATE payments SET status='posted',posted_at=statement_timestamp(),posted_by=$2,version=version+1 WHERE id=$1",[id,a.id]);return data(await history(c,a,id,'posted'));});});}
}
