import {Controller,Get,Post,Req,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {event,type Actor} from '@haven/database';
import {chargeGeneration,chargePreviewQuery} from '@haven/contracts';
import {leaseUnit} from '../inventory/lease-documents.js';
import {chargeConfiguration} from '../geography/charge-config.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
async function finance(c:pg.PoolClient,a:Actor){if(!a.orgId||!(await c.query('SELECT management_finance_lock($1) valid',[a.orgId])).rows[0].valid)fail(403,'Current finance membership required');return a.orgId;}
async function scope(c:pg.PoolClient,a:Actor,id:string){const org=await finance(c,a),l=(await c.query('SELECT l.*,l.start_date::text AS starts,l.end_date::text AS ends,t.name AS tenant FROM leases l JOIN tenants t ON t.id=l.tenant_id WHERE l.id=$1 AND l.organization_id=$2',[id,org])).rows[0];if(!l)fail(404,'Currently granted lease not found');const grantVersion=(await c.query('SELECT management_unit_grant_lock($1,$2) version',[l.unit_id,org])).rows[0].version;if(grantVersion===null)fail(404,'Current property authority required');return {l,grantVersion,unit:await leaseUnit(c,l.unit_id,org),config:await chargeConfiguration(c,l.unit_id,org)};}
function calculation(l:any,config:any,period:string){const first=period+'-01',next=new Date(first+'T00:00:00.000Z');next.setUTCMonth(next.getUTCMonth()+1);const last=new Date(next.getTime()-86400000).toISOString().slice(0,10),from=l.starts>first?l.starts:first,to=l.ends<last?l.ends:last,monthDays=Number(last.slice(8)),occupiedDays=(Date.parse(to)-Date.parse(from))/86400000+1;if(occupiedDays<1)return null;const [whole,fraction='']=l.rent.split('.'),cents=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0')),numerator=config.proration==='calendar_days'?BigInt(occupiedDays):BigInt(monthDays),denominator=BigInt(monthDays),rounded=(cents*numerator+denominator/2n)/denominator,amount=(rounded/100n).toString()+'.'+(rounded%100n).toString().padStart(2,'0');if(rounded<=0n)fail(409,'Prorated rent rounds to zero; review the configured term');const dueDay=l.due_day??config.legacyDueDay,scheduled=period+'-'+String(dueDay).padStart(2,'0'),dueDate=scheduled<from?from:scheduled;return {amount,dueDate,occupiedDays,monthDays,proration:config.proration,dueDaySource:l.due_day===null?'configured_historical_default':'lease'};}
@Controller('api/v1')
export class RecurringChargesController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/charge-generation-preview') async preview(@Req() req:FastifyRequest,@Query() input:unknown){const a=await this.identity.actor(req,['finance']),x=chargePreviewQuery.parse(input);return transaction(a,async c=>{const org=await finance(c,a),first=x.period+'-01',count=(await c.query("SELECT count(*)::int n FROM leases WHERE organization_id=$1 AND status='active' AND start_date<($2::date+interval '1 month') AND end_date>=$2",[org,first])).rows[0].n,rows=(await c.query("SELECT id FROM leases WHERE organization_id=$1 AND status='active' AND start_date<($2::date+interval '1 month') AND end_date>=$2 ORDER BY id LIMIT 20 OFFSET $3",[org,first,(x.page-1)*20])).rows,items=[];for(const r of rows){const s=await scope(c,a,r.id),calc=calculation(s.l,s.config,x.period);if(calc)items.push({leaseId:r.id,leaseVersion:s.l.version,unitVersion:s.unit.version,grantVersion:s.grantVersion,configVersion:s.config.version,community:s.unit.community,tenant:s.l.tenant,currency:s.l.currency,rent:s.l.rent,...calc,exists:!!(await c.query("SELECT 1 FROM charges WHERE lease_id=$1 AND period=$2 AND kind='rent'",[r.id,first])).rowCount});}return data({period:x.period,page:x.page,limit:20,total:count,items});});}
 @Post('ops/charges/generate') async generate(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['finance']),x=chargeGeneration.parse(body);return transaction(a,async c=>{await finance(c,a);for(const item of [...x.items].sort((a,b)=>a.leaseId.localeCompare(b.leaseId)))await scope(c,a,item.leaseId);return idempotent(c,a,req,x,async()=>{let generated=0,existing=0;const chargeIds=[];for(const item of [...x.items].sort((a,b)=>a.leaseId.localeCompare(b.leaseId))){await c.query('SELECT id FROM leases WHERE id=$1 FOR UPDATE',[item.leaseId]);const s=await scope(c,a,item.leaseId);if(s.l.status!=='active'||s.l.version!==item.leaseVersion||s.unit.version!==item.unitVersion||s.grantVersion!==item.grantVersion||s.config.version!==item.configVersion)fail(409,'Lease, authority or charge policy changed. Refresh the preview');const calc=calculation(s.l,s.config,x.period);if(!calc)fail(409,'The lease is outside this charge period');const snapshot={...item,...calc,period:x.period,rent:s.l.rent,currency:s.l.currency,configCity:s.config.city,rounding:'half_up_to_cent'},r=await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind,generated_by,generation_snapshot) VALUES($1,$2,$3,$4,$5,$6,'rent',$7,$8) ON CONFLICT(lease_id,period,kind) DO NOTHING RETURNING id",[s.l.id,s.l.organization_id,x.period+'-01',calc.dueDate,calc.amount,s.l.currency,a.id,snapshot]);if(r.rowCount){generated++;chargeIds.push(r.rows[0].id);await event(c,a,r.rows[0].id,'charge.posted',{version:1,leaseVersion:s.l.version,period:x.period,configVersion:s.config.version});}else{existing++;chargeIds.push((await c.query("SELECT id FROM charges WHERE lease_id=$1 AND period=$2 AND kind='rent'",[s.l.id,x.period+'-01'])).rows[0].id);}}return data({period:x.period,generated,existing,chargeIds});});});}
}
