import type pg from 'pg';
import type {StatementRecord} from '@haven/contracts';
import {statementQuery,statementRecord} from '@haven/contracts';
import {fail} from '../platform/core.js';

// One SQL snapshot includes original posted entries and immutable linked corrections.
// Dates are stored ledger timestamps in UTC; rent due dates remain informational.
const ledger=`WITH entries AS (
 SELECT c.id,CASE WHEN c.reverses_id IS NULL THEN 'charge' ELSE 'charge_reversal' END AS kind,c.created_at AS at,c.version,CASE WHEN c.reverses_id IS NULL THEN c.amount ELSE -c.amount END AS amount,c.currency,NULL::uuid AS payment_id,c.id AS charge_id,c.reverses_id,c.period::text AS rent_period,c.due_date::text AS due_date,NULL::timestamptz AS reversed_at,NULL::text AS deposit_kind,NULL::text AS direction,c.generated_by IS NULL AS historical FROM charges c WHERE c.lease_id=$1 AND c.status='posted'
 UNION ALL SELECT p.id,CASE WHEN p.reverses_id IS NULL THEN 'payment' ELSE 'payment_reversal' END,coalesce(p.posted_at,p.created_at),p.version,CASE WHEN p.reverses_id IS NULL THEN p.amount ELSE -p.amount END,p.currency,p.id,NULL,p.reverses_id,NULL,NULL,NULL,NULL,NULL,p.posted_at IS NULL FROM payments p WHERE p.lease_id=$1 AND p.status='posted'
 UNION ALL SELECT a.id,'allocation',a.created_at,a.version,a.amount,p.currency,p.id,c.id,NULL,NULL,NULL,a.reversed_at,NULL,NULL,a.allocated_by IS NULL FROM allocations a JOIN payments p ON p.id=a.payment_id JOIN charges c ON c.id=a.charge_id WHERE p.lease_id=$1 AND c.lease_id=$1 AND p.status='posted' AND c.status='posted'
 UNION ALL SELECT a.id,'allocation_undo',a.reversed_at,a.version,-a.amount,p.currency,p.id,c.id,NULL,NULL,NULL,a.reversed_at,NULL,NULL,a.reversed_by IS NULL FROM allocations a JOIN payments p ON p.id=a.payment_id JOIN charges c ON c.id=a.charge_id WHERE p.lease_id=$1 AND c.lease_id=$1 AND p.status='posted' AND c.status='posted' AND a.reversed_at IS NOT NULL
 UNION ALL SELECT d.id,'deposit',d.created_at,d.version,CASE WHEN coalesce(d.direction,CASE WHEN d.kind='received' THEN 'increase' ELSE 'decrease' END)='increase' THEN d.amount ELSE -d.amount END,d.currency,NULL,NULL,NULL,NULL,NULL,NULL,d.kind,d.direction,d.liability_version IS NULL FROM deposits d WHERE d.lease_id=$1
), windows AS (SELECT 'opening' AS bucket,NULL::timestamptz AS lo,$2::date::timestamp AT TIME ZONE 'UTC' AS hi UNION ALL SELECT 'movements',$2::date::timestamp AT TIME ZONE 'UTC',($3::date+1)::timestamp AT TIME ZONE 'UTC' UNION ALL SELECT 'totals',NULL,($3::date+1)::timestamp AT TIME ZONE 'UTC'), sums AS (
 SELECT w.bucket,coalesce(sum(e.amount) FILTER(WHERE e.kind IN('charge','charge_reversal')),0) AS charged,coalesce(sum(e.amount) FILTER(WHERE e.kind IN('payment','payment_reversal')),0) AS recorded,coalesce(sum(e.amount) FILTER(WHERE e.kind IN('allocation','allocation_undo')),0) AS allocated,coalesce(sum(e.amount) FILTER(WHERE e.kind='deposit'),0) AS held FROM windows w LEFT JOIN entries e ON (w.lo IS NULL OR e.at>=w.lo) AND e.at<w.hi GROUP BY w.bucket
), period_entries AS (SELECT * FROM entries WHERE at>=$2::date::timestamp AT TIME ZONE 'UTC' AND at<($3::date+1)::timestamp AT TIME ZONE 'UTC'), page AS (SELECT * FROM period_entries ORDER BY at DESC,id DESC,kind LIMIT $4 OFFSET $5)
SELECT statement_timestamp()::text AS "asOf",(SELECT count(*)::int FROM period_entries) AS total,EXISTS(SELECT 1 FROM entries WHERE currency<>$6) AS mixed,
 (SELECT jsonb_object_agg(bucket,jsonb_build_object('charges',round(charged,2)::text,'recordedPayments',round(recorded,2)::text,'allocated',round(allocated,2)::text,'outstanding',round(charged-allocated,2)::text,'credit',round(recorded-allocated,2)::text,'depositHeld',round(held,2)::text)) FROM sums) AS balances,
 coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'kind',kind,'recordedAt',at,'version',version,'amount',round(amount,2)::text,'currency',currency,'paymentId',payment_id,'chargeId',charge_id,'reversesId',reverses_id,'rentPeriod',rent_period,'dueDate',due_date,'reversedAt',reversed_at,'depositKind',deposit_kind,'direction',direction,'historical',historical) ORDER BY at DESC,id DESC,kind) FROM page),'[]') AS entries`;

export async function leaseStatement(c:pg.PoolClient,id:string,input:unknown={},exportAll=false):Promise<StatementRecord>{
 const parsed=statementQuery.parse(input),x={...parsed,to:parsed.to||new Date().toISOString().slice(0,10)};if(x.from>x.to)fail(400,'Start must precede the end date');const scope=(await c.query('SELECT management_statement_lock($1) scope',[id])).rows[0].scope;
 if(!scope)fail(404,'Currently authorized active or ended lease not found');
 const lease=(await c.query(`SELECT l.id,l.version,co.name AS community,l.currency,l.rent::text,l.start_date::text AS "startDate",l.end_date::text AS "endDate",l.status FROM leases l JOIN units u ON u.id=l.unit_id JOIN communities co ON co.id=u.community_id WHERE l.id=$1`,[id])).rows[0];
 if(!lease)fail(404,'Lease not found');
 const limit=exportAll?10000:20,r=(await c.query(ledger,[id,x.from,x.to,limit,exportAll?0:(x.page-1)*20,lease.currency])).rows[0];
 if(r.mixed)fail(409,'Historical currencies conflict with this lease. Request a ledger review; currencies cannot be combined');
 if(exportAll&&r.total>limit)fail(409,'Export exceeds 10,000 entries. Select a shorter period; no partial export was produced');
 const entries=r.entries as StatementRecord['entries'],absolute=(v:string)=>v.replace(/^-/,''),charges=entries.filter(e=>e.kind==='charge'||e.kind==='charge_reversal').map(e=>({id:e.id,period:e.rentPeriod!,due_date:e.dueDate!,amount:absolute(e.amount),currency:e.currency,kind:e.kind,reverses_id:e.reversesId})),payments=entries.filter(e=>e.kind==='payment'||e.kind==='payment_reversal').map(e=>({id:e.id,amount:absolute(e.amount),currency:e.currency,source:'recorded_evidence',reference:'Recorded payment evidence',reverses_id:e.reversesId,created_at:e.recordedAt})),allocations=entries.filter(e=>e.kind==='allocation').map(e=>({id:e.id,payment_id:e.paymentId!,charge_id:e.chargeId!,amount:e.amount,reversed_at:e.reversedAt})),deposits=entries.filter(e=>e.kind==='deposit').map(e=>({id:e.id,kind:e.depositKind!,direction:e.direction,amount:absolute(e.amount),currency:e.currency,reason:'Recorded deposit liability evidence',created_at:e.recordedAt}));
 return statementRecord.parse({lease,scope,asOf:r.asOf,period:{from:x.from,to:x.to,timeZone:'UTC',basis:'recorded_ledger_time'},page:exportAll?1:x.page,limit,total:r.total,...r.balances,entries,charges,payments,allocations,deposits,note:'Recorded ledger time in UTC, with inclusive start/end dates. Payment evidence uses recorded posting time, or stored creation time for historical records without posting time. Rent periods and due dates are informational. Source versions are current stored versions. Deposits are separate liabilities, never rent income. Historical deposit adjustments without direction retain the original decrease convention. No funds are transferred.'});
}
const quote=(v:string)=>'"'+(/^[\s]*[=+@-]/.test(v)&&!/^[-]?\d+\.\d{2}$/.test(v)?"'"+v:v).replaceAll('"','""')+'"';
const labels={charges:'Rent charges',recordedPayments:'Payment evidence',allocated:'Allocations',outstanding:'Outstanding balance',credit:'Unallocated credit',depositHeld:'Deposit liability'};
export function statementCSV(r:StatementRecord){const rows=[['Haven recorded lease statement'],['Lease',r.lease.id],['Lease version',String(r.lease.version)],['Lease status',r.lease.status],['Term start',r.lease.startDate],['Term end',r.lease.endDate],['Property',r.lease.community],['Currency',r.lease.currency],['Authorized scope',r.scope],['Period from',r.period.from],['Period to',r.period.to],['Time zone',r.period.timeZone],['Snapshot',r.asOf],['Definitions',r.note],[],['Balance','Opening','Period movement','Closing']];for(const [k,label] of Object.entries(labels)){const key=k as keyof typeof r.totals;rows.push([label,r.opening[key],r.movements[key],r.totals[key]]);}rows.push([],['Source ID','Type','Recorded at','Current source version','Signed amount', 'Currency','Payment ID','Charge ID','Reverses ID','Rent period','Due date','Historical provenance']);for(const e of r.entries)rows.push([e.id,e.kind,e.recordedAt,String(e.version),e.amount,e.currency,e.paymentId||'',e.chargeId||'',e.reversesId||'',e.rentPeriod||'',e.dueDate||'',e.historical?'Original attribution unknown':'Native recorded source']);return '\ufeff'+rows.map(row=>row.map(quote).join(',')).join('\r\n')+'\r\n';}
const html=(v:string)=>v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function statementHTML(r:StatementRecord){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recorded lease statement</title><style>body{font:16px/1.5 Arial;margin:24px;color:#202c29}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border:1px solid #bbb;padding:8px;text-align:left;overflow-wrap:anywhere}th{background:#edf2ee}.scroll{overflow:auto}h1{font-size:28px}@media print{body{margin:0}thead{display:table-header-group}tr{break-inside:avoid}.scroll{overflow:visible}}</style></head><body><h1>Recorded lease statement</h1><p>${html(r.lease.community)} · ${html(r.lease.currency)} · ${html(r.lease.id)}</p><p>Lease version ${r.lease.version} · ${html(r.lease.status)} · term ${html(r.lease.startDate)} – ${html(r.lease.endDate)}</p><p>${html(r.period.from)} – ${html(r.period.to)} inclusive · UTC · ${html(r.scope)} scope</p><p>Snapshot ${html(r.asOf)}. ${html(r.note)}</p><table><caption>Reconciled balances (${html(r.lease.currency)})</caption><thead><tr><th>Balance</th><th>Opening</th><th>Period movement</th><th>Closing</th></tr></thead><tbody>${Object.entries(labels).map(([k,label])=>{const key=k as keyof typeof r.totals;return `<tr><th>${html(label)}</th><td>${r.opening[key]}</td><td>${r.movements[key]}</td><td>${r.totals[key]}</td></tr>`;}).join('')}</tbody></table><h2>All ${r.total} period entries</h2><div class="scroll"><table><caption>Original sources and linked corrections</caption><thead><tr><th>Recorded at</th><th>Type</th><th>Signed amount (${html(r.lease.currency)})</th><th>Source</th><th>Linked source / dates</th></tr></thead><tbody>${r.entries.map(e=>`<tr><td>${html(e.recordedAt)}</td><td>${html(e.kind.replaceAll('_',' '))}${e.historical?' (historical provenance)':''}</td><td>${e.amount}</td><td>${html(e.id)} · version ${e.version}</td><td>${html([e.reversesId,e.paymentId,e.chargeId,e.rentPeriod,e.dueDate].filter(Boolean).join(' · '))}</td></tr>`).join('')}</tbody></table></div><p>Use your browser Print command to print or save as PDF. This is bookkeeping evidence, not proof of funds transfer.</p></body></html>`;}
