import {Controller,Get,Post,Patch,Param,Req,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import {z} from 'zod';
import {tenantInvite,tenantInviteDecision,managementGrantPage} from '@haven/contracts';
import {Identity,transaction,data,fail,idempotent} from '../platform/core.js';
const projection=`SELECT i.id,i.organization_id AS "organizationId",o.name AS organization,i.unit_id AS "unitId",tenant_invitation_community(i.id) AS community,i.name,i.email,CASE WHEN i.status='pending' AND i.expires_at<=statement_timestamp() THEN 'expired' ELSE i.status END AS status,i.version,i.expires_at AS "expiresAt",i.tenant_id AS "tenantId",coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'action',h.action,'at',h.at) ORDER BY h.version) FROM tenant_invitation_activity h WHERE h.invitation_id=i.id),'[]') AS activity FROM tenant_invitations i JOIN organizations o ON o.id=i.organization_id`;
@Controller('api/v1')
export class TenantLinksController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/tenant-invitations') async invitations(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,['property_manager']),x=managementGrantPage.parse(input);return transaction(a,async c=>{if(!(await c.query('SELECT management_inviter_lock($1) valid',[a.orgId])).rows[0].valid)fail(403,'Current property manager membership is required');return data((await c.query(projection+' WHERE i.organization_id=$1 ORDER BY i.created_at DESC,i.id LIMIT 20 OFFSET $2',[a.orgId,(x.page-1)*20])).rows);});}
 @Get('me/tenant-invitations') async ownInvitations(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req),x=managementGrantPage.parse(input);return transaction(a,async c=>data((await c.query(projection+' WHERE tenant_invitation_recipient(i.email) ORDER BY i.created_at DESC,i.id LIMIT 20 OFFSET $1',[(x.page-1)*20])).rows));}
 @Post('ops/tenant-invitations') async invite(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['property_manager']),x=tenantInvite.parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{if(!(await c.query('SELECT management_inviter_lock($1) valid',[a.orgId])).rows[0].valid)fail(403,'Current property manager membership is required');const g=(await c.query('SELECT id,unit_id,version FROM management_grants WHERE id=$1 AND organization_id=$2 AND management_grant_valid(id)',[x.grantId,a.orgId])).rows[0];if(!g)fail(404,'Current granted property not found');if(g.version!==x.grantVersion)fail(409,'Property grant changed. Refresh before inviting');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['tenant-invite:'+g.id+':'+x.email]);if((await c.query("SELECT id FROM tenant_invitations WHERE organization_id=$1 AND unit_id=$2 AND email=$3 AND status='pending'",[a.orgId,g.unit_id,x.email])).rowCount)fail(409,'An invitation is already recorded. Cancel it before inviting again.');const row=(await c.query('INSERT INTO tenant_invitations(organization_id,grant_id,grant_version,unit_id,email,name,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[a.orgId,g.id,g.version,g.unit_id,x.email,x.name,a.id])).rows[0];return data((await c.query(projection+' WHERE i.id=$1',[row.id])).rows[0]);}));}
 @Patch('tenant-invitations/:id') async decide(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),x=tenantInviteDecision.parse(body);z.uuid().parse(id);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const i=(await c.query('SELECT * FROM tenant_invitations WHERE id=$1',[id])).rows[0];if(!i)fail(404,'Invitation not found');if(i.version!==x.version||i.status!=='pending')fail(409,'Invitation changed. Refresh before deciding');if(x.action==='cancel'){if(!(await c.query('SELECT management_inviter_lock($1) valid',[a.orgId])).rows[0].valid||i.organization_id!==a.orgId)fail(404,'Invitation not found');await c.query("UPDATE tenant_invitations SET status='cancelled',version=version+1,reason=$2 WHERE id=$1",[id,x.reason]);}else{if(i.expires_at.getTime()<=Date.now())fail(409,'Invitation expired');if(!(await c.query('SELECT tenant_invitation_recipient($1) valid',[i.email])).rows[0].valid)fail(404,'Invitation not found');await c.query('SELECT decide_tenant_invitation($1,$2,$3,$4)',[id,x.version,x.action,x.reason]);}return data((await c.query(projection+' WHERE i.id=$1',[id])).rows[0]);}));}
 @Get('me/tenant-profiles') async profiles(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT t.id,t.name,t.email,o.name AS organization FROM tenants t JOIN organizations o ON o.id=t.organization_id WHERE t.user_id=$1 ORDER BY t.id LIMIT 100',[a.id])).rows));}
 @Get('me/tenant-profiles/:id') async profile(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>{const row=(await c.query('SELECT t.id,t.name,t.email,o.name AS organization FROM tenants t JOIN organizations o ON o.id=t.organization_id WHERE t.id=$1 AND t.user_id=$2',[z.uuid().parse(id),a.id])).rows[0];if(!row)fail(404,'Tenant profile not found');return data(row);});}
}
