'use client';
import {useEffect,useState} from 'react';
import {sdk} from '@haven/contracts';
import {ErrorBox,Spinner} from '@haven/ui';
type Session=NonNullable<Awaited<ReturnType<typeof sdk.DigitizationCaptureController_session>>['data']>;
type Upload=Awaited<ReturnType<typeof sdk.DigitizationCaptureController_uploads>>['data'][number];
export function DigitizationCaptureChecklist({workspaceId}:{workspaceId:string}){
 const [session,setSession]=useState<Session|null>(null),[uploads,setUploads]=useState<Upload[]>([]),[name,setName]=useState(''),[selectedUpload,setSelectedUpload]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(true),[partCount,setPartCount]=useState<number|null>(null);
 async function load(){const [saved,available]=await Promise.all([sdk.DigitizationCaptureController_session({params:{id:workspaceId}}),sdk.DigitizationCaptureController_uploads({params:{id:workspaceId}})]);setSession(saved.data);setUploads(available.data);}
 useEffect(()=>{let active=true;Promise.all([sdk.DigitizationCaptureController_session({params:{id:workspaceId}}),sdk.DigitizationCaptureController_uploads({params:{id:workspaceId}})]).then(([saved,available])=>{if(active){setSession(saved.data);setUploads(available.data);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Capture unavailable.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[workspaceId]);
 useEffect(()=>{setPartCount(null);const clip=session?.clips.find(c=>c.roomId===session.activeRoomId);if(!clip)return;let active=true;
 sdk.DigitizationController_workspace({params:{id:workspaceId}}).then(workspace=>workspace.data.target.type==='listing'?sdk.DigitizationCaptureController_readListing({params:{listingId:workspace.data.target.id,uploadId:clip.uploadId}}):sdk.DigitizationCaptureController_readIntake({params:{id:workspaceId,uploadId:clip.uploadId}})).then(upload=>{if(active)setPartCount(upload.data.parts.length);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Clip resume unavailable.');});return()=>{active=false;};},[workspaceId,session?.activeRoomId,session?.clips]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Capture save failed.');}finally{setBusy(false);}}
 async function save(state:Session['state']=session!.state){if(!session)return;const {version,inputRevision,rooms,clips,activeRoomId}=session;const result=await sdk.DigitizationCaptureController_saveSession({params:{id:workspaceId,sessionId:session.id},body:{version,inputRevision,rooms,clips,activeRoomId,state}});setSession(result.data);setNotice('Capture checklist saved privately.');}
 const open=session&&['draft','recording'].includes(session.state),editable=open&&!session.stale;
 return <section className="workspace-panel" aria-label="Room capture checklist"><h2>Room capture checklist</h2><p>Save rooms, the current room and your clip uploads to continue later. Uploaded clips remain private and require validation before processing.</p>{error&&<ErrorBox message={error}/>} {notice&&<p role="status">{notice}</p>}{busy&&<Spinner/>}
 {!open?<button className="button" disabled={busy} onClick={()=>void action(async()=>{const workspace=await sdk.DigitizationController_workspace({params:{id:workspaceId}});setSession((await sdk.DigitizationCaptureController_startSession({params:{id:workspaceId},body:{workspaceVersion:workspace.data.version}})).data);})}>Start room capture</button>:<>
 {session.stale&&<p role="status">Inputs changed. Discard this checklist before starting another capture.</p>}
 <fieldset disabled={busy||!editable}><legend>Capture rooms</legend><label>New capture room <input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><button className="button" disabled={!name.trim()||session.rooms.length>=200} onClick={()=>{const id=crypto.randomUUID();setSession({...session,rooms:[...session.rooms,{id,name:name.trim(),completed:false}],activeRoomId:session.activeRoomId??id});setName('');}}>Add capture room</button>
 <label>Current capture room <select value={session.activeRoomId??''} onChange={e=>setSession({...session,activeRoomId:e.target.value||null})}><option value="">Choose room</option>{session.rooms.map(room=><option key={room.id} value={room.id}>{room.name}</option>)}</select></label>
 {session.rooms.map(room=><label key={room.id}><input type="checkbox" checked={room.completed} onChange={e=>setSession({...session,rooms:session.rooms.map(r=>r.id===room.id?{...r,completed:e.target.checked}:r)})}/> {room.name} captured</label>)}
 <label>Available clip upload <select value={selectedUpload} onChange={e=>setSelectedUpload(e.target.value)}><option value="">Choose your upload</option>{uploads.filter(u=>!session.clips.some(c=>c.uploadId===u.id)).map((upload,index)=><option key={upload.id} value={upload.id}>Clip {index+1} · {upload.state} · {upload.bytes.toLocaleString()} bytes</option>)}</select></label><button className="button" disabled={!selectedUpload||!session.activeRoomId||session.clips.length>=256} onClick={()=>{setSession({...session,clips:[...session.clips,{roomId:session.activeRoomId!,uploadId:selectedUpload}],state:'recording'});setSelectedUpload('');}}>Link clip to current room</button>
 <p>{session.clips.length} linked clip uploads.{partCount!==null&&` Current room: ${partCount} uploaded parts recovered.`}</p><button className="button" onClick={()=>void action(()=>save())}>Save capture checklist</button><button className="button" onClick={()=>void action(()=>save('complete'))}>Finish capture checklist</button></fieldset>
 <button className="button" disabled={busy} onClick={()=>void action(async()=>{await load();const saved=(await sdk.DigitizationCaptureController_session({params:{id:workspaceId}})).data;if(!saved)throw Error('Capture session unavailable.');const {version,inputRevision,rooms,clips,activeRoomId}=saved;setSession((await sdk.DigitizationCaptureController_saveSession({params:{id:workspaceId,sessionId:saved.id},body:{version,inputRevision,rooms,clips,activeRoomId,state:'cancelled'}})).data);setNotice('Checklist discarded. Uploads retain their separate status.');})}>Discard capture checklist</button><button className="button" disabled={busy} onClick={()=>void action(load)}>Reload saved checklist</button>
 </>}
 </section>;
}
