'use client';
import {useState,useEffect,useCallback} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,priceLabel} from '@haven/contracts';
import {DraftListingWorkbench,MediaStudio,Dialog,Spinner,ErrorBox,Empty,Badge} from '@haven/ui';
const statuses=['draft','submitted','under_review','published','rejected','paused','sold','leased','expired','archived'];
const blank={q:'',status:'',transaction:'',segment:'',mine:false};
function parameters(filters:typeof blank){const params=new URLSearchParams();for(const [name,value] of Object.entries(filters))if(value)params.set(name,String(value));return params.toString();}
export function InventoryWorkbench({roles}:{roles:string[]}){
 const [draftRevision,setDraftRevision]=useState(0);
 const client=useQueryClient(),[filters,setFilters]=useState(blank),[applied,setApplied]=useState(blank),[modal,setModal]=useState<{mode:'detail'|'edit'|'status';row:any}|null>(null),[media,setMedia]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[opening,setOpening]=useState(false);
 const records=useQuery({queryKey:['ops','inventory',parameters(applied)],queryFn:()=>api<any[]>('/ops/listings?'+parameters(applied)),retry:false});
 const refresh=useCallback(async()=>{await client.invalidateQueries({queryKey:['ops']});},[client]);
 const refreshDrafts=async()=>{setDraftRevision(value=>value+1);await refresh();};
 const close=useCallback(()=>setModal(null),[]);
 const open=useCallback(async(id:string,mode:'detail'|'edit'|'status')=>{setError('');setOpening(true);try{const row=(await api<any>('/ops/listings/'+id+'/workbench')).data;if(mode==='edit'&&!row.can_edit)throw new Error('This property cannot be edited by your account.');setModal({mode,row});}catch(error){setError(error instanceof Error?error.message:'Unable to open this property');}finally{setOpening(false);}},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),initial={q:params.get('q')||'',status:params.get('status')||'',transaction:params.get('transaction')||'',segment:params.get('segment')||'',mine:params.get('mine')==='true'};setFilters(initial);setApplied(initial);if(params.get('edit'))void open(params.get('edit')!,'edit');},[open]);
 function apply(values:typeof blank){setFilters(values);setApplied(values);window.history.replaceState(null,'',window.location.pathname+(parameters(values)?'?'+parameters(values):''));}
 return <>{roles.some(role=>['agent','agency_manager','admin'].includes(role))&&<DraftListingWorkbench key={draftRevision} request={api} onChanged={refresh}/>}
 <section className="workspace-panel inventory-workbench"><h2>Property inventory</h2>
 <form className="inventory-filters" onSubmit={event=>{event.preventDefault();apply(filters);}}><label className="field"><span>Search records</span><input aria-label="Search records" value={filters.q} maxLength={160} onChange={event=>setFilters({...filters,q:event.target.value})} placeholder="Property title or community"/></label>{[['status','Listing status',statuses],['transaction','Transaction',['sale','rent']],['segment','Property segment',['residential','commercial']]].map(([key,label,options])=><label className="field" key={key as string}><span>{label as string}</span><select aria-label={label as string} value={filters[key as keyof typeof blank] as string} onChange={event=>setFilters({...filters,[key as string]:event.target.value})}><option value="">All</option>{(options as string[]).map(value=><option value={value} key={value}>{value.replaceAll('_',' ')}</option>)}</select></label>)}<label className="checkbox-field"><input type="checkbox" checked={filters.mine} onChange={event=>setFilters({...filters,mine:event.target.checked})}/>Assigned to me</label><div className="row-actions"><button className="button">Apply inventory filters</button><button className="button secondary" type="button" onClick={()=>apply(blank)}>Reset inventory filters</button></div></form>
 {notice&&<p role="status">{notice}</p>}{error&&<ErrorBox message={error}/ >}{opening&&<Spinner/>}
 {records.isPending?<Spinner/>:records.isError?<ErrorBox message={records.error.message} retry={()=>void records.refetch()}/>:!records.data?.data.length?<Empty title="No matching properties" description="Change or reset your inventory filters."/>:<><p className="fine-print">{records.data.data.length} properties · Actions follow your current assignment and property state.</p><div className="table-scroll ops-table"><table><thead><tr>{['Property','Community','Type','Price','Status','Version','Actions'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{records.data.data.map(row=><tr key={row.id} data-record-id={row.id}><td data-label="Property">{row.title}</td><td data-label="Community">{row.community}</td><td data-label="Type">{row.transaction} · {row.segment}</td><td data-label="Price">{priceLabel(row.price,row.currency,row.rent_period)}</td><td data-label="Status"><Badge>{row.status}</Badge></td><td data-label="Version">{row.version}</td><td className="actions" data-label="Actions"><div className="row-actions">{row.can_media&&<><button className="button secondary" onClick={()=>void open(row.id,'detail')}>Details</button><button className="button secondary" onClick={()=>setMedia(row.id)}>Media</button></>}{row.can_edit&&<button className="button secondary" onClick={()=>void open(row.id,'edit')}>{row.status==='published'?'Propose changes':'Edit'}</button>}{row.allowed_transitions.length>0&&<button className="button secondary" onClick={()=>void open(row.id,'status')}>Status</button>}{!row.can_media&&<span>Assignment required</span>}</div></td></tr>)}</tbody></table></div></>}
 </section>
 {media&&<Dialog title="Property media" onClose={()=>{setMedia('');void refreshDrafts();}}><MediaStudio listingId={media} request={api}/></Dialog>}
 {modal&&<Dialog title={modal.mode==='detail'?'Property details':modal.mode==='status'?'Change listing status':modal.row.status==='published'?'Propose published changes':'Edit listing'} onClose={close}>{modal.mode==='detail'?<><h3>{modal.row.title}</h3><Badge>{modal.row.status}</Badge><p>{modal.row.description}</p><dl className="inventory-facts">{[['Community',modal.row.community],['Area',modal.row.area+' m²'],['Layout',modal.row.beds+' bedrooms · '+modal.row.living_rooms+' living · '+modal.row.baths+' bathrooms'],['Price',priceLabel(modal.row.price,modal.row.currency,modal.row.rent_period)],['Features',modal.row.features.join(', ')||'None supplied'],['Furnishing',modal.row.furnishing],['Availability',modal.row.available_from?.slice(0,10)||'Not supplied']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{modal.row.can_edit&&<button className="button" onClick={()=>setModal({...modal,mode:'edit'})}>{modal.row.status==='published'?'Propose changes':'Edit'}</button>}</>:<InventoryForm mode={modal.mode} row={modal.row} saved={async()=>{close();setNotice('Record saved');await refreshDrafts();}}/>}</Dialog>}
 </>;
}
function InventoryForm({row,mode,saved}:{row:any;mode:'edit'|'status';saved:()=>Promise<void>}){
 const [values,setValues]=useState({title:row.title,description:row.description,price:row.price||'',features:(row.features as string[]).join(', '),furnishing:row.furnishing,availableFrom:row.available_from?.slice(0,10)||'',reason:'',status:'',verified:false}),[errors,setErrors]=useState<Record<string,string[]>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const field=(name:keyof typeof values,label:string,type='text')=><label className="field"><span>{label}</span>{type==='textarea'?<textarea aria-label={label} aria-invalid={!!errors[name]} value={values[name] as string} onChange={event=>setValues({...values,[name]:event.target.value})} disabled={busy}/>:<input type={type} aria-label={label} aria-invalid={!!errors[name]} value={values[name] as string} onChange={event=>setValues({...values,[name]:event.target.value})} disabled={busy}/ >}{errors[name]?.map(message=><small className="field-error" key={message}>{message}</small>)}</label>;
 return <form className="field-form" noValidate onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');setErrors({});try{await api('/ops/listings/'+row.id+(mode==='status'?'/transition':''),{method:mode==='status'?'POST':'PATCH',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify(mode==='status'?{status:values.status,reason:values.reason,verified:values.verified,version:row.version}:{title:values.title,description:values.description,price:values.price,features:values.features.split(',').map(value=>value.trim()).filter(Boolean),furnishing:values.furnishing,availableFrom:values.availableFrom||null,reason:values.reason,version:row.version})});await saved();}catch(error){setError(error instanceof Error?error.message:'Unable to save this property');setErrors((error as any).fieldErrors||{});}finally{setBusy(false);}}}>
 {mode==='status'?<><label className="field"><span>Next status</span><select aria-label="Next status" aria-invalid={!!errors.status} value={values.status} disabled={busy} onChange={event=>setValues({...values,status:event.target.value})}><option value="">Select…</option>{row.allowed_transitions.map((status:string)=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select>{errors.status?.map(message=><small className="field-error" key={message}>{message}</small>)}</label>{field('reason','Reason for the change','textarea')}<label className="checkbox-field"><input type="checkbox" checked={values.verified} disabled={busy} onChange={event=>setValues({...values,verified:event.target.checked})}/>I have verified property facts and authority to list.</label></>:<>{field('title','Title')}{field('description','Description','textarea')}{field('price','Price ('+row.currency+')')}{field('features','Features (separate with commas)')}{field('furnishing','Furnishing')}{field('availableFrom','Available from','date')}{field('reason','Reason for the proposed changes','textarea')}{row.status==='published'&&<p className="fine-print">Approved details remain public while these changes await independent review.</p>}</>}
 {error&&<ErrorBox message={error}/>}<button className="button" disabled={busy}>{busy?'Saving…':'Save'}</button>
 </form>;
}
