'use client';
import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {sdk,ApiError,managementDashboardQuery} from '@haven/contracts';
import {Spinner,ErrorBox,Empty} from '@haven/ui';
export function ManagementDashboard({scopeKey}:{scopeKey:string}){
 const [date,setDate]=useState(''),[draft,setDraft]=useState(''),[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const d=new URLSearchParams(location.search).get('dashboardDate')||new Date().toISOString().slice(0,10);setDate(d);setDraft(d);setReady(true);},[]);
 const q=useQuery({queryKey:['ops','management-dashboard',scopeKey,date],enabled:ready,queryFn:({signal})=>sdk.ManagementController_dashboard({query:{date},signal}),retry:false,gcTime:0});
 function submit(){const parsed=managementDashboardQuery.safeParse({date:draft});if(!parsed.success){setError('Use a real YYYY-MM-DD date');return;}setError('');if(draft===date)void q.refetch();setDate(draft);const u=new URL(location.href);u.searchParams.set('dashboardDate',draft);history.replaceState(null,'',u);}
 return <section aria-label="Management source dashboard" className="management-source-dashboard"><div className="section-heading"><h2>Management dashboard</h2><button className="button secondary" disabled={q.isFetching} onClick={()=>void q.refetch()}>Refresh dashboard</button></div><form className="dashboard-period" onSubmit={e=>{e.preventDefault();submit();}}><label>Recorded date (UTC)<input aria-label="Dashboard recorded date" type="date" max={new Date().toISOString().slice(0,10)} value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="button secondary" disabled={q.isFetching}>Load dashboard date</button></form>{error&&<ErrorBox message={error}/>} {q.isPending?<Spinner/>:q.isError?<ErrorBox message={q.error instanceof ApiError?q.error.message:'Dashboard could not load'} retry={()=>q.refetch()}/>:<><p>Current selected management organization. Effective date: <time>{q.data.data.date}</time>, end of day UTC. Snapshot: {q.data.data.asOf}.</p><div className="stat-grid">{([['units','Granted units'],['occupied','Occupied units'],['vacant','Vacant units'],['unknownHistory','Unknown occupancy history']] as const).map(([k,label])=><article className="stat-card" key={k} aria-label={label}><span>{label}</span><strong data-metric={k}>{q.data.data.occupancy[k]}</strong></article>)}</div><p className="fine-print">{q.data.data.definitions.scope} {q.data.data.definitions.occupancy}</p><h3>Arrears aging by currency</h3><p className="fine-print">{q.data.data.definitions.arrears}</p>{!q.data.data.arrears.length?<Empty title="No posted charges in this scope" description="Recorded charges will appear here under their currency."/>:q.data.data.arrears.map(r=><article className="dashboard-currency" key={r.currency}><h4>{r.currency} · {r.charges} outstanding charges</h4><dl>{([['notDue','Not due'],['days1to30','1–30 days overdue'],['days31to60','31–60 days overdue'],['days61to90','61–90 days overdue'],['daysOver90','Over 90 days overdue'],['total','Total outstanding']] as const).map(([k,label])=><div key={k}><dt>{label}</dt><dd>{r.currency} {r[k]}</dd></div>)}</dl></article>)}<h3>Maintenance status counts</h3><p className="fine-print">{q.data.data.definitions.maintenance}</p><dl className="dashboard-maintenance">{q.data.data.maintenance.counts.map(r=><div key={r.status}><dt>{r.status.replaceAll('_',' ')}</dt><dd>{r.count}</dd></div>)}<div><dt>Unknown maintenance history</dt><dd>{q.data.data.maintenance.unknownHistory}</dd></div></dl></> }</section>;
}
