'use client';
import {useState,useCallback} from 'react';
import {Dialog,Empty,Badge,ErrorBox} from '@haven/ui';
import {priceLabel} from '@haven/contracts';
export function ModerationListings({rows,onDecision}:{rows:any[];onDecision:(id:string,input:any)=>Promise<void>}){
 const [selected,setSelected]=useState<any>(null),[reason,setReason]=useState(''),[status,setStatus]=useState(''),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const close=useCallback(()=>setSelected(null),[]);
 function open(row:any){setSelected(row);setReason('');setStatus(row.status==='submitted'?'under_review':'published');setVerified(false);setError('');}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await onDecision(selected.id,{status,version:selected.version,reason,verified});close();}catch(error){setError(error instanceof Error?error.message:'Unable to save this decision');}finally{setBusy(false);}}
 return <section className="listing-review-queue"><h2>Property publication queue</h2>{!rows.length?<Empty title="No properties awaiting review" description="Submitted property drafts appear here for publication review."/>:rows.map(row=><article className="review-card" key={row.id} id={'listing-review-'+row.id}><h3>{row.title}</h3><Badge>{row.status.replaceAll('_',' ')}</Badge><p>{row.area} m² · {row.beds} bedrooms · {priceLabel(row.price,row.currency)} · {row.community}</p><p>{row.description}</p><div className="review-photos">{row.photos.map((photo:string)=><img key={photo} src={photo} alt="Approved property photograph"/>)}</div><button className="button small" onClick={()=>open(row)}>Review property</button></article>)}{selected&&<Dialog title="Review property publication" onClose={close}><p>{selected.title}</p><form className="field-form" onSubmit={submit}><label className="field"><span>Publication decision</span><select aria-label="Publication decision" disabled={busy} value={status} onChange={event=>setStatus(event.target.value)}><option value={selected.status==='submitted'?'under_review':'published'}>{selected.status==='submitted'?'Begin review':'Approve and publish'}</option><option value="rejected">Reject with a reason</option></select></label><label className="field"><span>Decision reason</span><textarea aria-label="Decision reason" required minLength={5} maxLength={1000} disabled={busy} value={reason} onChange={event=>setReason(event.target.value)}/></label>{status==='published'&&<label className="checkbox-field"><input type="checkbox" checked={verified} required disabled={busy} onChange={event=>setVerified(event.target.checked)}/>I verified property facts, listing authority, eligible agent and approved photos.</label>}{error&&<ErrorBox message={error}/>}<button className="button" type="submit" disabled={busy}>{busy?'Saving decision…':'Save publication decision'}</button></form></Dialog>}</section>;
}
