import {createRequire} from 'node:module';
import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFile} from 'node:fs/promises';
import {transaction} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),retained=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});test.afterAll(()=>retained.end());
const origin=(process.env.PUBLIC_WEB_URL||'http://localhost:8088');
test('Q04 / A06 fresh account downloads only its own data, confirms deletion, revokes both real sessions and cannot sign back into Haven',async({page,browser},info)=>{
 const username='a06-'+crypto.randomUUID(),email=username+'@example.test',password='Privacy-'+crypto.randomUUID()+'!9';let id='';const other=await browser.newContext({baseURL:origin}),second=await other.newPage();
 try{
  await page.goto('/api/v1/auth/login?prompt=login&returnTo=%2Faccount%2Fprivacy');await page.getByRole('link',{name:'Register',exact:true}).click();await page.locator('#firstName').fill('Privacy');await page.locator('#lastName').fill('Fixture');await page.locator('#email').fill(email);await page.locator('#username').fill(username);await page.locator('#password').fill(password);await page.locator('#password-confirm').fill(password);await page.getByRole('button',{name:'Register',exact:true}).click();await expect(page).toHaveURL(origin+'/account/privacy');id=(await(await page.request.get('/api/v1/me')).json()).data.id;
  await second.goto('/api/v1/auth/login?prompt=login&returnTo=%2Faccount%2Fprivacy');await second.getByRole('textbox',{name:'Username or email'}).fill(username);await second.getByLabel('Password',{exact:true}).fill(password);await second.getByRole('button',{name:'Sign In',exact:true}).click();await expect(second).toHaveURL(origin+'/account/privacy');expect((await(await second.request.get('/api/v1/me')).json()).data.id).toBe(id);
  await page.goto(origin+'/bj/buy/home-1');await page.getByRole('checkbox',{name:'Allow my property activity to contribute to recommendations',exact:true}).check();await expect.poll(async()=>{const response=await page.request.get(origin+'/api/v1/me/analytics-consent');return (await response.json()).data.enabled;}).toBe(true);await page.goto(origin+'/account/privacy');
  const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download personal data',exact:true}).click();const download=await downloading;expect(download.suggestedFilename()).toBe('haven-personal-export.json');const report=JSON.parse(await readFile((await download.path())!,'utf8'));expect(report.profile).toMatchObject({id,email});expect(report.records.tenantPayments).toEqual([]);expect(JSON.stringify(report)).not.toMatch(/encrypted_tokens|access_token|refresh_token|object_key|SESSION_KEY/);await expect(page.getByRole('main').getByRole('status')).toContainText('export has been downloaded');
  await page.getByRole('button',{name:'Request account deletion',exact:true}).click();await expect(page.getByLabel('Deletion confirmation',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(page.getByRole('main').getByRole('alert')).toContainText('exactly to confirm');await page.getByLabel('Deletion confirmation',{exact:true}).fill('DELETE MY ACCOUNT');
  const axe=await new AxeBuilder({page}).include('main').analyze();expect(axe.violations.filter(row=>row.impact==='serious'||row.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/a06-privacy-${info.project.name}.png`,scale:'css'});
  await page.getByRole('button',{name:'Request account deletion',exact:true}).click();await expect(page.getByRole('heading',{name:'Deletion requested',exact:true})).toBeVisible();await expect(page.getByRole('main').getByRole('status')).toContainText('all Haven sessions have been revoked');expect((await page.request.get('/api/v1/me')).status()).toBe(401);expect((await second.request.get('/api/v1/me')).status()).toBe(401);expect((await second.request.get('/api/v1/me/export')).status()).toBe(401);expect((await retained.query('SELECT enabled,version FROM analytics_consent WHERE user_id=$1',[id])).rows).toEqual([{enabled:false,version:2}]);await transaction(workerActor,async c=>{expect((await c.query('SELECT state FROM profiles WHERE id=$1',[id])).rows[0].state).toBe('deletion_requested');expect((await c.query('SELECT count(*)::int n FROM sessions WHERE user_id=$1',[id])).rows[0].n).toBe(0);expect((await c.query('SELECT count(*)::int n FROM account_deletion_requests WHERE user_id=$1',[id])).rows[0].n).toBe(1);});
  await page.goto('/api/v1/auth/login?prompt=login&returnTo=%2Faccount%2Fprivacy');await page.getByRole('textbox',{name:'Username or email'}).fill(username);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign In',exact:true}).click();await expect(page.locator('body')).toContainText('This account is not active');
 }finally{await other.close();// The isolated database retains the original deletion request and revoked profile.
}
});
