import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
import {fixtureAccountState} from '../support/account-fixture';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(()=>fixtures.end());
test.use({actionTimeout:15000});
const origin=(process.env.PUBLIC_WEB_URL||'http://localhost:8088');
async function save(page:any){await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Your profile has been saved.'})).toBeVisible();}
test('Q04 / A01 own display name/date preference survives refresh and sign-in; other profiles and expired sessions cannot be edited',async({page},info)=>{
 test.setTimeout(180000);await login(page,'buyer',origin,'/account/profile');const previous=(await (await page.request.get('/api/v1/me')).json()).data,name='Profile '+info.project.name;
 try{
  await page.getByLabel('Display name',{exact:true}).fill(' ');await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByLabel('Display name',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(page.getByText('Enter a display name between 2 and 80 characters.',{exact:true})).toBeVisible();
  await page.getByLabel('Display name',{exact:true}).fill(name);await page.getByLabel('Account date format',{exact:true}).selectOption('en-US');await save(page);await page.reload();await expect(page.getByLabel('Display name',{exact:true})).toHaveValue(name);await expect(page.getByLabel('Account date format',{exact:true})).toHaveValue('en-US');await expect(page.getByText('Email verified by the sign-in service',{exact:true})).toBeVisible();
  const denied=await page.request.patch('/api/v1/profiles/00000000-0000-4000-8000-000000000002',{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{displayName:'Not permitted',locale:'en-US',version:1}});expect(denied.status()).toBe(404);
  const manage=page.getByRole('link',{name:'Manage sign-in and contact details',exact:true});await expect(manage).toHaveAttribute('href',process.env.OIDC_ISSUER+'/account/');const [account]=await Promise.all([page.waitForEvent('popup'),manage.click()]);try{await account.waitForLoadState('networkidle');if(await account.getByRole('heading',{name:'Sign in to your account',exact:true}).isVisible()){await account.getByRole('textbox',{name:'Username or email'}).fill('buyer');await account.getByLabel('Password',{exact:true}).fill(process.env.DEV_PASSWORD!);await account.getByRole('button',{name:'Sign In',exact:true}).click();}await expect(account.getByRole('heading',{name:/personal info/i})).toBeVisible();}finally{await account.close();}
  await login(page,'buyer',origin,'/account/profile');await expect(page.getByLabel('Display name',{exact:true})).toHaveValue(name);
  const session=(await page.context().cookies()).find(cookie=>cookie.name==='haven_session')!.value;await fixtures.query("UPDATE sessions SET expires_at=now()-interval '1 hour' WHERE id=$1",[session]);await page.getByLabel('Display name',{exact:true}).fill('Expired change');await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByText('Your session expired. Sign in again to continue.',{exact:true})).toBeVisible();await expect(page.getByLabel('Display name',{exact:true})).toHaveCount(0);
  await login(page,'buyer',origin,'/account/profile');await expect(page.getByLabel('Display name',{exact:true})).toHaveValue(name);
  const accessibility=await new AxeBuilder({page}).include('main').analyze();expect(accessibility.violations.filter(issue=>issue.impact==='serious'||issue.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/a01-profile-${info.project.name}.png`,scale:'css'});
 }finally{const current=await page.request.get('/api/v1/me');if(current.ok()){const row=(await current.json()).data;await page.request.patch('/api/v1/profiles/'+row.id,{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{displayName:previous.displayName,locale:previous.locale,version:row.version}});}}
});
test('Q04 / A01 account API outage shows retry without claiming logout',async({page})=>{
 await login(page,'buyer',origin,'/account/profile');await page.route('**/api/v1/me',route=>route.fulfill({status:503,json:{error:{code:'TEMPORARY_UNAVAILABLE',message:'Account temporarily unavailable'}}}));await page.reload();await expect(page.locator('main').getByRole('alert')).toContainText('Account temporarily unavailable');await expect(page.getByRole('button',{name:'Sign in or create an account',exact:true})).toHaveCount(0);await page.unroute('**/api/v1/me');await page.getByRole('button',{name:'Try again',exact:false}).click();await expect(page.getByLabel('Display name',{exact:true})).toBeVisible();
});
async function suspendRecoveryFixture(profileId:string){const c=await fixtures.connect();try{await c.query('BEGIN');await fixtureAccountState(c,'suspended','WHERE id=$1',[profileId]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test('Q04 / A01 identity-managed registration and email recovery reset a synthetic account password and preserve its local profile',async({page},info)=>{
 test.setTimeout(180000);const username='a01-'+crypto.randomUUID(),email=username+'@example.test',password='Initial-'+crypto.randomUUID()+'!9',replacement='Recovered-'+crypto.randomUUID()+'!9';let profileId='';
 try{
  await page.goto('/api/v1/auth/login?prompt=login&returnTo=%2Faccount%2Fprofile');await page.getByRole('link',{name:'Register',exact:true}).click();await page.locator('#firstName').fill('Profile');await page.locator('#lastName').fill('Recovery');await page.locator('#email').fill(email);await page.locator('#username').fill(username);await page.locator('#password').fill(password);await page.locator('#password-confirm').fill(password);await page.getByRole('button',{name:'Register',exact:true}).click();await expect(page).toHaveURL(origin+'/account/profile');
  profileId=(await (await page.request.get('/api/v1/me')).json()).data.id;await page.getByLabel('Display name',{exact:true}).fill('Recovery profile '+info.project.name);await save(page);await page.getByRole('link',{name:'Recover sign-in access',exact:true}).click();await page.getByRole('link',{name:/forgot password/i}).click();const confirmation=page.getByText(/receive an email shortly/i),reset=page.locator('#kc-reset-password-form');await expect(reset.or(confirmation)).toBeVisible();if(await reset.isVisible()){await reset.locator('#username').fill(username);await reset.getByRole('button',{name:'Submit',exact:true}).click();}await expect(confirmation).toBeVisible();
  let message:any;await expect.poll(async()=>{const r=await fetch((process.env.IDENTITY_MAIL_API_URL||process.env.MAIL_API_URL||'http://mail:8025')+'/api/v1/search?query='+encodeURIComponent('to:'+email));const body=await r.json();message=body.messages?.[0];return !!message;}).toBe(true);
  const body=await (await fetch((process.env.IDENTITY_MAIL_API_URL||process.env.MAIL_API_URL||'http://mail:8025')+'/api/v1/message/'+message.ID)).json(),text=String(body.HTML||body.Text),links=text.match(/https?:\/\/[^\s<>"']+/g)||[],action=links.map(link=>link.replaceAll('&amp;','&')).find(link=>link.includes('/login-actions/action-token'))!;expect(!!action).toBe(true);const destination=new URL(action);expect(destination.origin).toBe(new URL(process.env.OIDC_ISSUER!).origin);await page.goto(action);await page.locator('#password-new').fill(replacement);await page.locator('#password-confirm').fill(replacement);await page.getByRole('button',{name:'Submit',exact:true}).click();
  // Complete a fresh standard PKCE sign-in after the identity action.
  await page.goto('/api/v1/auth/login?prompt=login&returnTo=%2Faccount%2Fprofile');await page.getByRole('textbox',{name:'Username or email'}).fill(username);await page.getByLabel('Password',{exact:true}).fill(replacement);await page.getByRole('button',{name:'Sign In',exact:true}).click();await expect(page).toHaveURL(origin+'/account/profile');await expect(page.getByLabel('Display name',{exact:true})).toHaveValue('Recovery profile '+info.project.name);const recovered=(await (await page.request.get('/api/v1/me')).json()).data;await expect(page.getByText(recovered.emailVerified?'Email verified by the sign-in service':'Email not yet verified',{exact:true})).toBeVisible();expect(recovered.contactSyncedAt).toBeTruthy();
 }finally{if(profileId)await suspendRecoveryFixture(profileId);}
});
