import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
import {transaction} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(()=>fixtures.end());
const origin='http://localhost:8088';
async function history(page:any){const response=await page.request.get('/api/v1/me/history');expect(response.ok()).toBe(true);return (await response.json()).data;}
async function mutate(page:any,path:string,data:any,method='PATCH'){const response=await page.request.fetch('/api/v1'+path,{method,headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data});expect(response.ok()).toBe(true);return(await response.json()).data;}
async function reset(page:any){let current=await history(page);if(current.enabled)current=await mutate(page,'/me/history/preferences',{version:current.version,enabled:false});if(current.entries.length)await mutate(page,'/me/history',{version:current.version},'DELETE');}
async function accessible(page:any){const result=await new AxeBuilder({page}).include('main').analyze();expect(result.violations.filter(issue=>issue.impact==='serious'||issue.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
test('A03 opt-in visits persist, turning history off stops collection, remove/clear work and clearing preserves another user history',async({page},info)=>{
 try{
  await login(page,'owner');await reset(page);const current=await history(page);await mutate(page,'/me/history/preferences',{version:current.version,enabled:true});await page.goto('/bj/buy/home-2');await expect(page.getByText('This visit is in your browsing history.',{exact:true})).toBeVisible();
  await login(page,'buyer');await reset(page);await page.goto('/bj/buy/home-1');await expect(page.getByRole('checkbox',{name:'Keep my browsing history',exact:true})).not.toBeChecked();expect((await history(page)).entries).toHaveLength(0);
  await page.getByRole('checkbox',{name:'Keep my browsing history',exact:true}).check();await expect(page.getByText('This visit is in your browsing history.',{exact:true})).toBeVisible();await page.goto('/account/history');await expect(page.locator('[data-history-id="10000000-0000-4000-8000-000000002000"]')).toBeVisible();await page.reload();await expect(page.getByRole('link',{name:'Light-filled home beside the gardens',exact:true})).toBeVisible();await accessible(page);await page.screenshot({path:`evidence/a03-history-${info.project.name}.png`,scale:'css'});
  await page.getByRole('checkbox',{name:'Keep my browsing history',exact:true}).uncheck();await expect(page.getByRole('status').filter({hasText:'Browsing history disabled.'})).toBeVisible();await page.goto('/bj/buy/home-2');await expect(page.getByRole('checkbox',{name:'Keep my browsing history',exact:true})).not.toBeChecked();expect((await history(page)).entries).toHaveLength(1);await page.goto('/account/history');await page.getByRole('button',{name:'Remove visit',exact:true}).click();await expect(page.getByRole('heading',{name:'No browsing history',exact:true})).toBeVisible();
  await page.getByRole('checkbox',{name:'Keep my browsing history',exact:true}).check();await expect(page.getByRole('status').filter({hasText:'Browsing history enabled.'})).toBeVisible();await page.goto('/bj/buy/home-1');await expect(page.getByText('This visit is in your browsing history.',{exact:true})).toBeVisible();await page.goto('/account/history');await page.getByRole('button',{name:'Clear browsing history',exact:true}).click();await expect(page.getByRole('heading',{name:'No browsing history',exact:true})).toBeVisible();expect((await history(page)).entries).toHaveLength(0);
  await login(page,'owner',origin,'/account/history');await expect(page.locator('[data-history-id]')).toHaveCount(1);await expect(page.getByRole('button',{name:'Remove visit',exact:true})).toBeVisible();
 }finally{await login(page,'owner');await reset(page);await login(page,'buyer');await reset(page);}
});
test('A03 saved eligible home opens detail; actual archive keeps unavailable saved/history entries without private fields and supports removal',async({page},info)=>{
 const slug='a03-browser-'+crypto.randomUUID(),title='Browsing-history fixture '+info.project.name;
 const id=await transaction(workerActor,async c=>(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,$2,description,transaction,segment,currency,price,photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id`,[slug,title])).rows[0].id,fixtures);
 try{
  await login(page,'buyer');await reset(page);const current=await history(page);await mutate(page,'/me/history/preferences',{version:current.version,enabled:true});await page.goto('/bj/buy/'+slug);await expect(page.getByText('This visit is in your browsing history.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.toast')).toContainText('Home saved');await page.goto('/account/favorites');await page.locator('[data-listing-id="'+id+'"]').getByRole('link',{name:title,exact:true}).click();await expect(page).toHaveURL(origin+'/bj/buy/'+slug);
  await login(page,'agent','http://localhost:8089','/ops/listings');const archived=await apiRequest(page,'/ops/listings/'+id+'/transition',{version:1,status:'archived',reason:'Archive synthetic history fixture after public verification'});expect(archived.ok()).toBe(true);await transaction(workerActor,c=>c.query("UPDATE listings SET title='PRIVATE_ARCHIVED_TITLE',description='PRIVATE_ARCHIVED_DESCRIPTION' WHERE id=$1",[id]),fixtures);
  await login(page,'buyer',origin,'/account/favorites');const unavailable=page.locator('[data-unavailable-id="'+id+'"]');await expect(unavailable.getByRole('heading',{name:'Saved property is unavailable',exact:true})).toBeVisible();expect((await page.request.get('/api/v1/listings/'+slug)).status()).toBe(404);expect((await page.request.get('/api/v1/me/favorites')).status()).toBe(200);expect(await page.locator('main').innerText()).not.toContain('PRIVATE_ARCHIVED');await expect(page.locator('a[href="/bj/buy/'+slug+'"]')).toHaveCount(0);await accessible(page);await page.screenshot({path:`evidence/a03-unavailable-saved-${info.project.name}.png`,scale:'css'});await unavailable.getByRole('button',{name:'Remove',exact:true}).click();await expect(unavailable).toHaveCount(0);
  await page.goto('/account/history');const visit=page.locator('[data-unavailable-id="'+id+'"]');await expect(visit.getByRole('heading',{name:'Previously viewed property is unavailable',exact:true})).toBeVisible();expect(await page.locator('main').innerText()).not.toContain('PRIVATE_ARCHIVED');await accessible(page);await page.screenshot({path:`evidence/a03-unavailable-history-${info.project.name}.png`,scale:'css'});await visit.getByRole('button',{name:'Remove',exact:true}).click();await expect(visit).toHaveCount(0);expect((await history(page)).entries.some((entry:any)=>entry.listing.id===id)).toBe(false);
 }finally{await login(page,'buyer');await reset(page);await transaction(workerActor,async c=>{await c.query('DELETE FROM favorites WHERE listing_id=$1',[id]);await c.query("UPDATE listings SET status='archived' WHERE id=$1",[id]);},fixtures);}
});
