import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixturePool=new Pool({connectionString:process.env.DATABASE_URL});
async function staff(work:(c:any)=>Promise<any>){const c=await fixturePool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const result=await work(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
test.afterAll(()=>fixturePool.end());
test('C02 commercial criteria persist with explicit monthly/yearly per-usable-area cards and no residential filters',async({page},info)=>{
 const rows=await staff(async c=>{const rows=[];for(const period of ['month','year']){const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'C02 browser office',description,'rent','commercial','CNY','6421.75',$2,photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",['c02-browser-'+crypto.randomUUID(),period])).rows[0];await c.query("INSERT INTO commercial_details(listing_id,property_type,gross_area,usable_area,area_basis,rent_basis,fit_out,permitted_uses) VALUES($1,'office','180.25','150.75','usable','per_area','Furnished',ARRAY['Office'])",[row.id]);rows.push(row);}return rows;});
 try{await page.goto('/bj/commercial');await expect(page.getByRole('button',{name:'Bedrooms',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Commercial filters',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Transaction',{exact:true}).selectOption('rent');await dialog.getByLabel('Property type',{exact:true}).selectOption('office');await dialog.getByLabel('Fit-out',{exact:true}).fill('Furnished');await dialog.getByLabel('Permitted use',{exact:true}).fill('Office');await dialog.getByLabel('Minimum price (CNY)',{exact:true}).fill('6421.75');await dialog.getByLabel('Maximum price (CNY)',{exact:true}).fill('6421.75');await dialog.getByRole('button',{name:'Apply filters',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText(['Choose total or per-area prices before comparing','Choose a commercial rental billing period before comparing']);await dialog.getByLabel('Price basis',{exact:true}).selectOption('per_area');await dialog.getByLabel('Area basis',{exact:true}).selectOption('usable');await dialog.getByLabel('Billing period',{exact:true}).selectOption('month');const axe=await new AxeBuilder({page}).include('dialog').analyze();expect(axe.violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/c02-filters-${info.project.name}.png`,scale:'css'});await dialog.getByRole('button',{name:'Apply filters',exact:true}).click();await expect.poll(()=>new URL(page.url()).searchParams.get('rentPeriod')).toBe('month');await page.reload();let card=page.locator('[data-listing-id="'+rows[0].id+'"]');await expect(card).toBeVisible();await expect(card.locator('.card-bottom')).toContainText('CNY 6,421.75 / m² (usable) / month');await expect(card).toContainText('180.25 m² gross');await expect(card).toContainText('150.75 m² usable');await expect(card).not.toContainText('Rental mode not provided');await expect(page.locator('[data-listing-id="'+rows[1].id+'"]')).toHaveCount(0);await page.getByRole('button',{name:'Commercial filters',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Fit-out',{exact:true})).toHaveValue('Furnished');await dialog.getByLabel('Billing period',{exact:true}).selectOption('year');await dialog.getByRole('button',{name:'Apply filters',exact:true}).click();await expect.poll(()=>new URL(page.url()).searchParams.get('rentPeriod')).toBe('year');card=page.locator('[data-listing-id="'+rows[1].id+'"]');await expect(card).toBeVisible();await expect(card.locator('.card-bottom')).toContainText('/ year');await expect(page.locator('[data-listing-id="'+rows[0].id+'"]')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/c02-cards-${info.project.name}.png`,scale:'css'});
 }finally{await staff(c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[rows.map(row=>row.id)]));}
});
