import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('M01 inquiry participants open the actual resource conversation; unrelated accounts cannot read or join its WebSocket room',async({page},info)=>{
 test.setTimeout(180000);const agent=crypto.randomUUID(),slug='m01-browser-'+agent;let lead:string|undefined,thread:string|undefined;
 const socket=async(id:string)=>page.evaluate(id=>new Promise<string>(resolve=>{const ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/api/v1/realtime/conversations/'+id),timer=setTimeout(()=>{ws.close();resolve('timeout');},10000);ws.onmessage=e=>{clearTimeout(timer);const value=JSON.parse(e.data);ws.close();resolve(value.type+':'+value.conversationId);};ws.onerror=()=>{clearTimeout(timer);resolve('denied');};}),id);
 try{await staff(c=>c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'M01 browser agent',$3,'Synthetic linked conversation fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]));
 await login(page,'buyer','http://localhost:8088','/account/messages');const response=await page.request.post('/api/v1/inquiries',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{resourceId:agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M01 browser customer',email:'fixture@example.test',phone:'123456789',message:'Please discuss this agent service with me.',consent:true}});expect(response.ok()).toBe(true);const receipt=(await response.json()).data;lead=receipt.id;thread=receipt.conversationId;expect(thread).toBeTruthy();const detail=(await (await page.request.get('/api/v1/conversations/'+thread)).json()).data;expect(detail).toMatchObject({lead_id:lead,resource_id:agent,resource_type:'agent',state:'active'});expect(detail.members.map((m:any)=>m.user_id)).toEqual(expect.arrayContaining(['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000003']));
 await page.goto('/account/messages?conversation='+thread);await expect(page.getByLabel('Conversation participants')).toContainText('Agent inquiry');expect(await socket(thread!)).toBe('subscribed:'+thread);const wrongRoom=await page.evaluate(id=>new Promise<number>(resolve=>{const ws=new WebSocket('ws://'+location.host+'/api/v1/realtime/conversations/'+id),timer=setTimeout(()=>{ws.close();resolve(0);},10000);ws.onmessage=()=>ws.send(JSON.stringify({type:'subscribe',conversationId:crypto.randomUUID()}));ws.onclose=e=>{clearTimeout(timer);resolve(e.code);};}),thread!);expect(wrongRoom).toBe(1008);await page.screenshot({path:`evidence/m01-consumer-${info.project.name}.png`,scale:'css'});
 await login(page,'agent','http://localhost:8089','/ops/messages?conversation='+thread);await expect(page.getByLabel('Conversation participants')).toContainText('Agent inquiry');expect((await page.request.get('http://localhost:8089/api/v1/conversations/'+thread)).ok()).toBe(true);expect(await socket(thread!)).toBe('subscribed:'+thread);expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/m01-agent-${info.project.name}.png`,scale:'css'});
 await login(page,'outsider','http://localhost:8089','/ops/messages');expect((await page.request.get('http://localhost:8089/api/v1/conversations/'+thread)).status()).toBe(404);expect((await page.request.get('http://localhost:8089/api/v1/conversations/'+thread+'/messages')).status()).toBe(404);expect(await socket(thread!)).toBe('denied');expect((await apiRequest(page,'/conversations/'+thread+'/messages',{version:0,conversationVersion:detail.version,body:'Unrelated actor must be denied',clientId:crypto.randomUUID()})).status()).toBe(404);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await staff(async c=>{if(lead)await c.query('DELETE FROM leads WHERE id=$1',[lead]);if(thread){await c.query('DELETE FROM messages WHERE conversation_id=$1',[thread]);await c.query('DELETE FROM conversations WHERE id=$1',[thread]);}await c.query('UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1',[agent]);});}
});
