import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('L02 agent filters, contacts and qualifies an assigned inquiry, retries a private note and restores the recorded timeline after refresh',async({page},info)=>{
 test.setTimeout(120000);const id=crypto.randomUUID(),agent=crypto.randomUUID(),other=crypto.randomUUID(),name='L02 browser client '+id.slice(0,8),hidden='L02 unassigned '+other.slice(0,8),text='Private CRM note <script>window.__crmExecuted=true</script>';let saved:any,key:string|undefined;
 try{await staff(async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'L02 browser fixture agent',$3,'Explicit synthetic CRM eligibility fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2030-01-01')",[agent,org,'l02-'+agent]);await c.query("INSERT INTO leads(id,user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message) VALUES($1,'00000000-0000-4000-8000-000000000001',$2,$3,$3,'agent',$4,'l02-browser@example.test','123456789','Synthetic assigned CRM inquiry')",[id,org,agent,name]);await c.query("INSERT INTO leads(id,user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,NULL,$3,'agent',$4,'l02-hidden@example.test','123456789','Personal ownership must not broaden professional access')",[other,org,agent,hidden]);});
 await login(page,'agent','http://localhost:8089','/ops/leads');await expect(page.getByRole('region',{name:'Inquiry queue',exact:true})).not.toContainText(hidden);await page.getByLabel('Search contacts',{exact:true}).fill(name);await page.getByRole('button',{name:'Apply inquiry filters',exact:true}).click();await expect(page).toHaveURL(new RegExp('text=L02'));await expect(page.locator('.record-row')).toHaveCount(1);await page.getByRole('button',{name:'Open inquiry for '+name,exact:true}).click();await expect(page).toHaveURL(new RegExp('lead='+id));const dialog=page.getByRole('dialog',{name:'Inquiry details',exact:true});await dialog.getByLabel('Next lead stage',{exact:true}).selectOption('contacted');await dialog.getByRole('button',{name:'Save lead stage',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Lead stage saved.');await expect(dialog.getByRole('region',{name:'Lead timeline',exact:true})).toContainText('Stage: new → contacted');await dialog.getByLabel('Next lead stage',{exact:true}).selectOption('qualified');await dialog.getByRole('button',{name:'Save lead stage',exact:true}).click();await expect(dialog.getByRole('region',{name:'Lead timeline',exact:true})).toContainText('Stage: contacted → qualified');
 await dialog.getByLabel('Private team note',{exact:true}).fill(text);let lost=true;await page.route('**/api/v1/ops/leads/'+id+'/notes',async route=>{const response=await route.fetch();if(lost&&response.ok()){lost=false;key=route.request().headers()['idempotency-key'];saved=(await response.json()).data;await route.abort('failed');}else{expect(route.request().headers()['idempotency-key']).toBe(key);await route.fulfill({response});}});await dialog.getByRole('button',{name:'Save private note',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Private team note',{exact:true})).toHaveValue(text);await dialog.getByRole('button',{name:'Save private note',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('Private note saved.');await expect(dialog.getByLabel('Private team note',{exact:true})).toHaveValue('');await expect(dialog.getByRole('region',{name:'Lead timeline',exact:true})).toContainText(text);expect(await page.evaluate(()=>(window as any).__crmExecuted)).toBeUndefined();expect(await staff(async c=>(await c.query("SELECT count(*)::int n FROM lead_activity WHERE lead_id=$1 AND kind='note'",[id])).rows[0].n)).toBe(1);expect(saved.lead.status).toBe('qualified');await page.unroute('**/api/v1/ops/leads/'+id+'/notes');await page.reload();await expect(dialog).toBeVisible();await expect(dialog.getByRole('region',{name:'Lead timeline',exact:true})).toContainText(text);await expect(dialog.getByLabel('Next lead stage',{exact:true})).toHaveValue('');expect((await new AxeBuilder({page}).include('dialog').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/l02-crm-${info.project.name}.png`,scale:'css'});
 expect((await apiRequest(page,'/ops/leads/'+id,{version:saved.lead.version,status:'won'},'PATCH')).status()).toBe(409);expect((await apiRequest(page,'/ops/leads/'+id+'/notes',{version:1,text:'Stale browser note'})).status()).toBe(409);await login(page,'outsider','http://localhost:8089','/ops/leads');expect((await page.request.get('/api/v1/ops/leads/'+id)).status()).toBe(404);expect((await page.request.get('/api/v1/ops/leads/'+id+'/timeline')).status()).toBe(404);expect((await apiRequest(page,'/ops/leads/'+id+'/notes',{version:saved.lead.version,text:'Foreign browser note'})).status()).toBe(404);await expect(page.locator('main')).not.toContainText(name);await expect(page.locator('main')).not.toContainText(text);
 }finally{await staff(async c=>{await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=ANY($1::uuid[])",[[id,other]]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}
});
