import '../support/env';
import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import AxeBuilder from '@axe-core/playwright';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
const created:string[]=[];
async function staff(work:(client:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const result=await work(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
async function fixture(title:string){const row=await staff(async c=>(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,$2,'Synthetic ranking browser fixture','sale','residential','CNY','9876123.47',photos,'published',now()-interval '40 days' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug,version`,['ranking-browser-'+crypto.randomUUID(),title])).rows[0]);created.push(row.id);return row;}
async function count(id:string){return staff(async c=>Number((await c.query('SELECT count(*) FROM listing_view_events WHERE listing_id=$1',[id])).rows[0].count));}
test.afterAll(async()=>{try{await staff(async c=>{await c.query('DELETE FROM curated_boosts WHERE resource_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM listing_view_events WHERE listing_id=ANY($1::uuid[])',[created]);await c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=ANY($1::uuid[])",[created]);});}finally{await fixtures.end();}});
test('D06 authorized curation appears with a sponsorship label and public period; version and role boundaries reject invalid changes',async({page},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);const title='Ranking placement '+info.project.name+' '+crypto.randomUUID().slice(0,8),resource=await fixture(title),label='Sponsored fixture '+info.project.name;
 await login(page,'admin','http://localhost:8089','/ops/rankings');await page.getByRole('button',{name:'Add curation',exact:true}).click();await page.getByLabel('Find a published listing',{exact:true}).fill(title);await expect(page.locator('option[value="'+resource.id+'"]')).toHaveCount(1);await page.getByLabel('Eligible property',{exact:true}).selectOption(resource.id);await page.getByLabel('Public placement label',{exact:true}).fill(label);await page.getByLabel('Ranking boost points',{exact:true}).fill('100');await page.getByRole('checkbox',{name:'Sponsored placement',exact:true}).check();await page.getByRole('button',{name:'Save placement',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Curation saved at version 1'})).toBeVisible();
 const record=(await(await page.request.get('http://localhost:8089/api/v1/ops/ranking-boosts?city=bj')).json()).data.find((x:any)=>x.resource_id===resource.id);expect(record.sponsored).toBe(true);
 const query=new URLSearchParams({transaction:'sale',segment:'residential',minPrice:'9876123.47',maxPrice:'9876123.47'});await page.goto('http://localhost:8088/bj/rankings?'+query);const card=page.locator('[data-ranking-id="'+resource.id+'"]');await expect(card).toContainText(title);await expect(card.locator('.sponsored-label')).toHaveText('Sponsored');await expect(card).toContainText(label);await expect(page.locator('.ranking-period')).toContainText('Rule 1');await page.getByLabel('Ranking period',{exact:true}).selectOption('30d');await expect(page).toHaveURL(/period=30d/);await page.reload();await expect(page.getByLabel('Ranking period',{exact:true})).toHaveValue('30d');await expect(card.locator('.sponsored-label')).toBeVisible();
 const axe=await new AxeBuilder({page}).include('main').analyze();expect(axe.violations.filter(x=>['serious','critical'].includes(x.impact||''))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/d06-rankings-${info.project.name}.png`});
 const update={resourceType:'listing',resourceId:resource.id,city:'bj',points:100,sponsored:true,publicLabel:label,startsAt:record.starts_at,endsAt:record.ends_at,status:'paused',version:record.version};await page.goto('http://localhost:8089/ops/rankings');await page.locator('tr[data-curation-id="'+record.id+'"]').getByRole('button',{name:'Edit placement',exact:true}).click();await page.getByLabel('Placement status',{exact:true}).selectOption('paused');await page.getByRole('button',{name:'Save placement',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Curation saved at version 2'})).toBeVisible();expect((await apiRequest(page,'/ops/ranking-boosts/'+record.id,{...update,status:'active'},'PATCH')).status()).toBe(409);await page.goto('http://localhost:8088/bj/rankings?'+query+'&period=30d');await expect(card).toContainText(title);await expect(card.locator('.sponsored-label')).toHaveCount(0);
 await login(page,'agent','http://localhost:8089','/ops/rankings');await expect(page.getByRole('heading',{name:'This workspace is not assigned to you',exact:true})).toBeVisible();expect((await apiRequest(page,'/ops/ranking-boosts',{...update,version:undefined})).status()).toBe(403);
});
test('D06 activity is opt-in and account/day/event dedupe prevents repeated visits from inflating ranking signals',async({page},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);const resource=await fixture('Consented ranking '+info.project.name+' '+crypto.randomUUID().slice(0,8));await login(page,'buyer');await page.goto('/bj/buy/'+resource.slug);const checkbox=page.getByRole('checkbox',{name:'Allow my property views to contribute to rankings',exact:true});await expect(checkbox).toBeVisible();expect(await count(resource.id)).toBe(0);await checkbox.check();await expect.poll(()=>count(resource.id)).toBe(1);await page.reload();await expect(checkbox).toBeChecked();await expect(page.locator('.activity-consent')).toContainText('already counted');expect(await count(resource.id)).toBe(1);
 const headers={Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},eventId=crypto.randomUUID();for(const id of [eventId,eventId,crypto.randomUUID()]){const result=await page.request.post('/api/v1/listings/'+resource.id+'/view',{headers:{...headers,'idempotency-key':crypto.randomUUID()},data:{eventId:id,version:resource.version,consent:true}});expect(result.ok()).toBe(true);expect((await result.json()).data.counted).toBe(false);}expect(await count(resource.id)).toBe(1);
 await checkbox.uncheck();await page.reload();await expect(checkbox).not.toBeChecked();expect(await count(resource.id)).toBe(1);await page.locator('.activity-consent').scrollIntoViewIfNeeded();await page.screenshot({path:`evidence/d06-consent-${info.project.name}.png`});
 await login(page,'tenant');await page.goto('/bj/buy/'+resource.slug);await expect(checkbox).not.toBeChecked();await checkbox.check();await expect.poll(()=>count(resource.id)).toBe(2);const raw=await(await page.request.get('/api/v1/rankings?'+new URLSearchParams({city:'bj',minPrice:'9876123.47',maxPrice:'9876123.47'}))).json();expect(raw.data.find((x:any)=>x.id===resource.id).viewCount).toBe(2);expect(JSON.stringify(raw)).not.toContain('user_id');
});
