import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {screenshotReady} from '../../scripts/screenshot-ready';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
const created:string[]=[];
async function staff(work:(client:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const result=await work(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
test.afterAll(async()=>{try{await staff(async c=>{await c.query('DELETE FROM curated_boosts WHERE resource_id=ANY($1::uuid[])',[created]);await c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=ANY($1::uuid[])",[created]);});}finally{await fixtures.end();}});
const entries=[['Buy a home','buy'],['New homes','new-homes'],['Rent a home','rent'],['Renovation','renovation'],['Commercial','commercial'],['Communities','communities'],['Find an agent','agents'],['Support','support'],['Mortgage tools','tools/mortgage'],['List a property','list-property']];
test('D07 every home category and ranking shortcut navigates to its functional selected-city route in observed order',async({page},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);await page.goto('/bj');await expect(page.locator('[data-home-feed="resale"] .listing-card')).toHaveCount(6);await expect(page.locator('[data-home-feed="developments"] .directory-card')).toHaveCount(3);await expect(page.locator('[data-home-feed="rentals"] .listing-card')).toHaveCount(3);expect(await page.getByRole('region',{name:'Explore property categories'}).getByRole('link').allTextContents()).toEqual(entries.map(([name])=>name));
 for(const [label,path] of entries){await page.goto('/bj');const link=page.getByRole('region',{name:'Explore property categories'}).getByRole('link',{name:label,exact:true});await expect(link).toHaveAttribute('href','/bj/'+path);await link.click();await expect(page).toHaveURL('http://localhost:8088/bj/'+path);await expect(page.locator('#main')).toBeVisible();await expect(page.locator('#main h1')).toBeVisible();await expect(page.locator('#main .error-box')).toHaveCount(0);}
 for(const [label,path] of [['Homes for sale rankings','/bj/rankings?transaction=sale&segment=residential&period=7d'],['Rental rankings','/bj/rankings?transaction=rent&segment=residential&period=7d'],['Browse the property map','/bj/map']]){await page.goto('/bj');await page.getByRole('navigation',{name:'Property ranking shortcuts'}).getByRole('link',{name:label,exact:true}).click();await expect(page).toHaveURL('http://localhost:8088'+path);await expect(page.locator('#main h1')).toBeVisible();}
 await page.goto('/bj');await expect(page.locator('[data-home-feed="rentals"] .listing-card')).toHaveCount(3);const axe=await new AxeBuilder({page}).include('#main').analyze();expect(axe.violations.filter(x=>['serious','critical'].includes(x.impact||''))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await screenshotReady(page,true);await page.screenshot({path:`evidence/d07-home-${info.project.name}.png`,fullPage:true,scale:'css'});
});
test('D07 genuine eligible curation is displayed and an empty city has useful sections without wrong-city cards or dead carousel controls',async({page},info)=>{
 const resource=await staff(async c=>(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'D07 curated browser '||$2::text,'Synthetic home curation','sale','residential','CNY','1234567.89',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug`,['home-browser-'+crypto.randomUUID(),info.project.name])).rows[0]);created.push(resource.id);
 await staff(c=>c.query(`INSERT INTO curated_boosts(resource_type,resource_id,city,points,sponsored,public_label,starts_at,ends_at,created_by,updated_by) VALUES('listing',$1,'bj',100,true,'Synthetic D07 placement',now()-interval '1 hour',now()+interval '1 day','00000000-0000-4000-8000-000000000010','00000000-0000-4000-8000-000000000010')`,[resource.id]));
 await page.goto('/bj');const curated=page.locator('[data-home-feed="curated-resale"]');await expect(curated.locator('[data-listing-id="'+resource.id+'"]')).toBeVisible();await expect(curated.locator('.sponsored-label')).toHaveText('Sponsored');await curated.locator('[data-listing-id="'+resource.id+'"] .card-title').click();await expect(page).toHaveURL('/bj/buy/'+resource.slug);await expect(page.locator('.detail-tags .sponsored-label')).toBeVisible();
 await staff(c=>c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=$1",[resource.id]));await page.goto('/bj');await expect(page.locator('[data-listing-id="'+resource.id+'"]')).toHaveCount(0);
 await page.goto('/sh');await expect(page.locator('[data-home-feed="resale"]')).toContainText('No homes for sale in Shanghai yet');await expect(page.locator('[data-home-feed="developments"]')).toContainText('No new-home recommendations in Shanghai yet');await expect(page.locator('[data-home-feed="rentals"]')).toContainText('No rental recommendations in Shanghai yet');await expect(page.locator('.listing-card,.directory-card')).toHaveCount(0);await expect(page.locator('[data-home-feed^="curated"]')).toHaveCount(0);await expect(page.locator('[data-home-feed]').getByRole('button',{name:/next|previous/i})).toHaveCount(0);
 for(const [label,path] of [['Browse homes for sale','/sh/buy'],['Browse new homes','/sh/new-homes'],['Browse this category','/sh/rent']])await expect(page.getByRole('link',{name:label,exact:true})).toHaveAttribute('href',path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/d07-empty-${info.project.name}.png`,fullPage:true,scale:'css'});
});
