import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const WEB=process.env.PUBLIC_WEB_URL||'http://localhost:8088',OPS=process.env.PUBLIC_OPS_URL||'http://localhost:8089';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});test.afterAll(()=>fixtures.end());
test('S03 native English editorial draft preview publication interval and taxonomy with actual public properties',async({page},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);const title='S03 native selection '+crypto.randomUUID(),property='S03 native property '+crypto.randomUUID();const c=await fixtures.connect();let source:{id:string;version:number};try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true),set_config('app.admin','true',true)");const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0];source=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,$3,description,'sale','residential','CNY','123456.78','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,version",[unit.id,'s03-native-'+crypto.randomUUID(),property])).rows[0];await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
 await login(page,'admin',OPS,'/ops/rankings');await page.getByRole('button',{name:'New home section',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Edit home section',exact:true});await dialog.getByLabel('Section title',{exact:true}).fill(title);await dialog.getByLabel('English section copy',{exact:true}).fill('Current synthetic home selected with an English editorial heading.');await dialog.getByLabel('Section order',{exact:true}).fill('2');await dialog.getByLabel('Find editorial property',{exact:true}).fill(property);await dialog.getByRole('button',{name:'Search editorial properties',exact:true}).click();await dialog.getByLabel('Add editorial property',{exact:true}).selectOption(source.id);let lost=false,id='';await page.route('**/api/v1/ops/home-content',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;const r=await route.fetch();expect(r.ok(),await r.text()).toBe(true);id=(await r.json()).data.id;await route.abort();}else await route.continue();});await dialog.getByRole('button',{name:'Save home draft',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Section title',{exact:true})).toHaveValue(title);await dialog.getByRole('button',{name:'Save home draft',exact:true}).click();await expect(dialog).not.toBeVisible();await page.unroute('**/api/v1/ops/home-content');const row=page.locator('[data-home-section="'+id+'"]');await expect(row).toContainText('version 1');await row.getByRole('button',{name:'Preview '+title,exact:true}).click();dialog=page.getByRole('dialog',{name:'Home section preview',exact:true});await expect(dialog).toContainText(property);await expect(dialog).toContainText('Private draft preview');await expect(dialog.getByRole('link',{name:'View current public property',exact:true})).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/s03-preview-${info.project.name}.png`,scale:'css'});await dialog.getByRole('button',{name:'Close dialog',exact:true}).click();
 const publicPage=await page.context().newPage();await publicPage.goto(WEB+'/bj');await expect(publicPage.locator('[data-home-feed="editorial-'+id+'"]')).toHaveCount(0);await row.getByRole('button',{name:'Publish '+title,exact:true}).click();await expect(row).toContainText('published version 2');await publicPage.reload();const section=publicPage.locator('[data-home-feed="editorial-'+id+'"]');await expect(section.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(section).toContainText(property);expect((await new AxeBuilder({page:publicPage}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(publicPage.viewportSize()!.width);await publicPage.screenshot({path:`evidence/s03-published-${info.project.name}.png`,scale:'css'});
 const revised=title+' revised';await row.getByRole('button',{name:'Edit '+title,exact:true}).click();dialog=page.getByRole('dialog',{name:'Edit home section',exact:true});await dialog.getByLabel('Section title',{exact:true}).fill(revised);await dialog.getByRole('button',{name:'Save home draft',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(row).toContainText('version 3');await publicPage.reload();await expect(section.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(section.getByRole('heading',{name:revised,exact:true})).toHaveCount(0);await row.getByRole('button',{name:'Publish '+revised,exact:true}).click();await expect(row).toContainText('published version 4');await publicPage.reload();await expect(section.getByRole('heading',{name:revised,exact:true})).toBeVisible();
 const oldLabel=await page.getByLabel('Category label buy',{exact:true}).inputValue();await page.getByLabel('Category label buy',{exact:true}).fill('S03 approved English homes');await page.getByRole('button',{name:'Save category buy',exact:true}).click();await expect(page.getByRole('button',{name:'Save category buy',exact:true})).toBeEnabled();await expect(page.getByLabel('Category label buy',{exact:true})).toHaveValue('S03 approved English homes');await publicPage.reload();await expect(section).toContainText('S03 approved English homes');await page.getByLabel('Category active buy',{exact:true}).uncheck();await page.getByRole('button',{name:'Save category buy',exact:true}).click();await expect(page.getByRole('button',{name:'Save category buy',exact:true})).toBeEnabled();await expect(page.getByLabel('Category active buy',{exact:true})).not.toBeChecked();await publicPage.reload();await expect(section).toHaveCount(0);await page.getByLabel('Category active buy',{exact:true}).check();await page.getByLabel('Category label buy',{exact:true}).fill(oldLabel);await page.getByRole('button',{name:'Save category buy',exact:true}).click();await expect(page.getByRole('button',{name:'Save category buy',exact:true})).toBeEnabled();await expect(page.getByLabel('Category active buy',{exact:true})).toBeChecked();await publicPage.reload();await expect(section).toBeVisible();
 await fixtures.query("UPDATE listings SET status='withdrawn',version=version+1 WHERE id=$1",[source.id]);await publicPage.reload();await expect(section).toHaveCount(0);await row.getByRole('button',{name:'Publish '+revised,exact:true}).click();await expect(page.getByRole('region',{name:'Home content editor',exact:true}).getByRole('alert')).toContainText('eligible');await row.getByRole('button',{name:'Archive '+revised,exact:true}).click();await expect(row).toContainText('archived');await page.reload();await expect(row).toContainText('archived');await publicPage.close();await login(page,'buyer',WEB,'/account');expect((await page.request.get(WEB+'/api/v1/ops/home-content?city=bj')).status()).toBe(403);expect((await page.request.get(WEB+'/api/v1/ops/home-content/'+id+'/preview')).status()).toBe(403);
});
