import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});

test('M03 unread read-cursor updates, refresh selection and failed draft retry work in native consumer and professional inboxes',async({page},info)=>{
 test.setTimeout(180000);const agent=crypto.randomUUID(),slug='m03-browser-'+agent,ids:string[]=[],leads:string[]=[];
 try{await staff(c=>c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'M03 browser agent',$3,'Synthetic unread/selection fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]));await login(page,'buyer','http://localhost:8088','/account/messages');
 for(let i=0;i<2;i++){const response=await page.request.post('/api/v1/inquiries',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{resourceId:agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M03 customer',email:'m03-'+agent+'@example.test',phone:'123456789',message:'Selection fixture '+i,consent:true}});expect(response.ok()).toBe(true);const r=(await response.json()).data;ids.push(r.conversationId);leads.push(r.id);}
 const first=ids[0],second=ids[1];await page.goto('/account/messages?conversation='+first);await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toBeEnabled();await page.getByRole('textbox',{name:'Your message',exact:true}).fill('A retained draft for the first room.');
 await page.locator('.inbox aside button').nth(0).click();await expect(page).toHaveURL(new RegExp('conversation='+second));await page.locator('[data-conversation-id="'+first+'"]').click();await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toHaveValue('A retained draft for the first room.');await page.locator('[data-conversation-id="'+second+'"]').click();await page.getByRole('textbox',{name:'Your message',exact:true}).fill('M03 second room only '+agent);await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.message')).toContainText('M03 second room only');await page.reload();await expect(page).toHaveURL(new RegExp('conversation='+second));await expect(page.locator('.message')).toContainText('M03 second room only');
 const message='M03 unconfirmed draft '+agent;await page.route('**/api/v1/conversations/'+second+'/messages',async route=>{if(route.request().method()==='POST')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'TEST_UNAVAILABLE',message:'Synthetic temporary service failure'}})});else await route.continue();});await page.getByRole('textbox',{name:'Your message',exact:true}).fill(message);await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.chat-composer:visible').getByRole('alert')).toContainText('Message not confirmed');await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toHaveValue(message);await expect(page.locator('.message').filter({hasText:message})).toHaveCount(0);await page.unroute('**/api/v1/conversations/'+second+'/messages');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.message').filter({hasText:message})).toHaveCount(1);
 // Two incoming messages remain unread while the professional opens the other room.
 await login(page,'agent','http://localhost:8089','/ops/messages?conversation='+first);await expect(page.locator('[data-conversation-id="'+second+'"]').getByLabel('2 unread messages',{exact:true})).toBeVisible();expect((await (await page.request.get('http://localhost:8089/api/v1/conversations/'+second+'/read-cursor')).json()).data.sequence).toBe('0');await page.locator('.inbox aside button').nth(0).click();await expect(page.locator('.message').filter({hasText:message})).toBeVisible();await expect.poll(async()=>(await (await page.request.get('http://localhost:8089/api/v1/conversations/'+second+'/read-cursor')).json()).data.sequence).toBe('2');await expect(page.locator('[data-conversation-id="'+second+'"]').getByLabel('2 unread messages',{exact:true})).toHaveCount(0);await page.reload();await expect(page).toHaveURL(new RegExp('conversation='+second));await expect(page.locator('.message').filter({hasText:message})).toBeVisible();await page.getByRole('textbox',{name:'Reply to client',exact:true}).fill('M03 native professional reply.');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.message').filter({hasText:'M03 native professional reply.'})).toBeVisible();
 expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/m03-inbox-${info.project.name}.png`,scale:'css'});
 await login(page,'buyer','http://localhost:8088','/account/messages?conversation='+first);await expect(page.locator('[data-conversation-id="'+second+'"]').getByLabel('1 unread messages',{exact:true})).toBeVisible();await page.locator('.inbox aside button').nth(0).click();await expect(page.locator('.message').filter({hasText:'M03 native professional reply.'})).toBeVisible();await expect.poll(async()=>(await (await page.request.get('/api/v1/conversations/'+second+'/read-cursor')).json()).data.sequence).toBe('3');await expect(page.locator('[data-conversation-id="'+second+'"]').getByLabel('1 unread messages',{exact:true})).toHaveCount(0);expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);
 }finally{await staff(async c=>{await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=ANY($1::uuid[])",[leads]);await c.query("UPDATE conversations SET state='closed',version=version+1 WHERE id=ANY($1::uuid[])",[ids]);await c.query('UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1',[agent]);});}
});
