import '../support/env';
import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg');
const fixtures=new Pool({connectionString:process.env.DATABASE_URL});test.afterAll(()=>fixtures.end());
test('I07 agent creates, uploads, orders media, edits facts, filters and submits through the workbench',async({page},info)=>{
 test.setTimeout(180000);const title='Inventory workbench '+info.project.name+' '+crypto.randomUUID();
 await login(page,'agent','http://localhost:8089','/ops/listings');
 await page.getByRole('button',{name:'Create property draft',exact:true}).click();
 await page.getByRole('button',{name:'Save property draft',exact:true}).click();await expect(page.getByRole('dialog').locator('.field-error')).not.toHaveCount(0);
 await page.getByLabel('Existing property unit',{exact:true}).selectOption('10000000-0000-4000-8000-000000001000');await page.getByLabel('Property title',{exact:true}).fill(title);await page.getByLabel('Property description',{exact:true}).fill('Complete property facts entered through the inventory workbench.');await page.getByLabel('Asking price (decimal amount)',{exact:true}).fill('2450000.75');await page.getByRole('button',{name:'Save property draft',exact:true}).click();
 await expect(page.locator('.draft-workbench').getByRole('status')).toHaveText('Property draft saved');
 await page.getByLabel('Search records',{exact:true}).fill(title);await page.getByLabel('Listing status',{exact:true}).selectOption('draft');await page.getByRole('button',{name:'Apply inventory filters',exact:true}).click();await expect(page.locator('.inventory-workbench tbody tr')).toHaveCount(1);await page.reload();await expect(page.getByLabel('Search records',{exact:true})).toHaveValue(title);
 const row=page.locator('.inventory-workbench tbody tr');const id=await row.getAttribute('data-record-id');
 await row.getByRole('button',{name:'Details',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Complete property facts');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await row.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('x');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog').locator('.field-error')).not.toHaveCount(0);await page.getByLabel('Title',{exact:true}).fill(title);await page.getByLabel('Features (separate with commas)',{exact:true}).fill('Near metro, Balcony');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await row.getByRole('button',{name:'Media',exact:true}).click();await page.getByLabel('Media type',{exact:true}).selectOption('photo');await page.getByLabel('Media title',{exact:true}).fill('Workbench property photograph');await page.getByLabel('Rights / source',{exact:true}).fill('Project synthetic fixture');await page.getByLabel('Property media file',{exact:true}).setInputFiles('apps/web/public/homes/home-1.jpg');await page.getByRole('checkbox',{name:'I have the rights and permission to publish this media.',exact:true}).check();await page.getByRole('button',{name:'Upload and submit for review',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Upload prepared and submitted'})).toBeVisible();
 await page.getByRole('button',{name:'Edit details / hotspots',exact:true}).click();await page.getByLabel('Edit display order',{exact:true}).fill('7');await page.getByRole('button',{name:'Submit media revision',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Revision submitted for review'})).toBeVisible();const assets=(await(await page.request.get('http://localhost:8089/api/v1/ops/listings/'+id+'/media')).json()).data.media;expect(assets).toHaveLength(1);expect(assets[0].pending_position).toBe(7);
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.locator('.draft-workbench .record-row').filter({hasText:title}).getByRole('button',{name:'Submit for review',exact:true}).click();await expect(page.locator('.draft-workbench').getByRole('status')).toHaveText('Property submitted for review');
 await page.getByRole('button',{name:'Reset inventory filters',exact:true}).click();await page.getByLabel('Search records',{exact:true}).fill(title);await page.getByLabel('Listing status',{exact:true}).selectOption('submitted');await page.getByRole('button',{name:'Apply inventory filters',exact:true}).click();await expect(row).toContainText('submitted');await expect(row.getByRole('button',{name:'Edit',exact:true})).toHaveCount(0);await expect(row.getByRole('button',{name:'Status',exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'evidence/i07-workbench-'+info.project.name+'.png',fullPage:true});
});
test('I07 unassigned edit buttons, direct edit links and all private mutation APIs deny access',async({page},info)=>{
 const title='Unassigned workbench '+info.project.name+' '+crypto.randomUUID(),c=await fixtures.connect();let id:string;
 try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");id=(await c.query(`INSERT INTO listings(unit_id,organization_id,slug,title,description,transaction,segment,currency,price,status) SELECT unit_id,organization_id,$1,$2,description,transaction,segment,currency,price,'published' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id`,['unassigned-'+crypto.randomUUID(),title])).rows[0].id;await c.query('COMMIT');}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}
 await login(page,'agent','http://localhost:8089','/ops/listings');await page.getByLabel('Search records',{exact:true}).fill(title);await page.getByRole('button',{name:'Apply inventory filters',exact:true}).click();const row=page.locator('tr[data-record-id="'+id+'"]');await expect(row).toHaveCount(0);const queue=await page.request.get('/api/v1/ops/listings?q='+encodeURIComponent(title)+'&mine=false');expect(queue.ok()).toBe(true);expect((await queue.json()).data).toEqual([]);await expect(page.locator('.draft-workbench')).not.toContainText(title);
 for(const suffix of ['/draft','/workbench','/media'])expect((await page.request.get('http://localhost:8089/api/v1/ops/listings/'+id+suffix)).status()).toBe(404);
 expect((await apiRequest(page,'/ops/listings/'+id,{title,price:'100.25',version:1},'PATCH')).status()).toBe(404);
 await page.goto('http://localhost:8089/ops/listings?edit='+id);await expect(page.locator('.inventory-workbench .error-box')).toContainText('Assigned property not found');await expect(page.getByRole('dialog')).toHaveCount(0);
 await login(page,'outsider','http://localhost:8089','/ops/listings');expect((await page.request.get('http://localhost:8089/api/v1/ops/listings/'+id+'/workbench')).status()).toBe(404);
});
