import {test,expect} from '@playwright/test';
import {login,apiRequest} from '../support/browser';
const existing='10000000-0000-4000-8000-000000001000';
const base={unitId:existing,title:'A newly prepared property draft',description:'A private draft with complete English property facts for review.',transaction:'sale',segment:'residential',currency:'CNY',price:'2450000.75',rentPeriod:null,furnishing:'Unfurnished',availableFrom:null,features:['Near metro']};
test('I02 agent creates a new unit draft, edits it, refreshes and rejects stale and foreign edits',async({page},info)=>{
 await login(page,'agent','http://localhost:8089','/ops/listings');await page.getByRole('button',{name:'Create property draft',exact:true}).click();await page.getByLabel('Enter a new property unit',{exact:true}).check();
 await page.getByRole('combobox',{name:'Community',exact:true}).selectOption('10000000-0000-4000-8000-000000000040');await page.getByLabel('Private unit address',{exact:true}).fill('PRIVATE_DRAFT_'+crypto.randomUUID());await page.getByLabel('Area (m²)',{exact:true}).fill('81.25');await page.getByLabel('Property title',{exact:true}).fill('Browser draft '+info.project.name+' '+crypto.randomUUID());const title=await page.getByLabel('Property title',{exact:true}).inputValue();await page.getByLabel('Property description',{exact:true}).fill(base.description);await page.getByLabel('Asking price (decimal amount)',{exact:true}).fill(base.price);await page.getByRole('button',{name:'Save property draft',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Property draft saved'})).toBeVisible();
 await page.reload();const row=page.locator('.draft-workbench .record-row').filter({hasText:title});await expect(row).toBeVisible();await row.getByRole('button',{name:'Edit draft',exact:true}).click();await expect(page.getByLabel('Asking price (decimal amount)',{exact:true})).toHaveValue(base.price);await page.getByLabel('Property title',{exact:true}).fill(title+' updated');await page.getByRole('button',{name:'Save property draft',exact:true}).click();await expect(page.locator('.draft-workbench').getByRole('heading',{name:title+' updated',exact:true})).toBeVisible();
 const records=(await (await page.request.get('http://localhost:8089/api/v1/ops/listings')).json()).data;const record=records.find((row:any)=>row.title===title+' updated');expect(record).toBeTruthy();
 const detail=(await (await page.request.get('http://localhost:8089/api/v1/ops/listings/'+record.id+'/draft')).json()).data;const edit={...base,title:detail.title,version:detail.version-1};delete (edit as any).unitId;expect((await apiRequest(page,'/ops/listings/'+record.id+'/draft',edit,'PATCH')).status()).toBe(409);
 const publicResponse=await page.request.get('http://localhost:8088/api/v1/listings/'+record.slug);expect(publicResponse.status()).toBe(404);expect(await publicResponse.text()).not.toContain('PRIVATE_DRAFT');
 await page.screenshot({path:`evidence/draft-inventory-${info.project.name}.png`,fullPage:true});await login(page,'outsider','http://localhost:8089','/ops/listings');expect((await page.request.get('http://localhost:8089/api/v1/ops/listings/'+record.id+'/draft')).status()).toBe(404);expect((await apiRequest(page,'/ops/listings/'+record.id+'/draft',{...edit,version:detail.version},'PATCH')).status()).toBe(404);
});
test('I02 owner edits only owned drafts and cannot bypass new-property ownership review',async({page},info)=>{
 const editedTitle='Owner edited their private property draft '+info.project.name+' '+crypto.randomUUID();
 await login(page,'owner');let response=await page.request.post('/api/v1/ops/listings',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:base});expect(response.status()).toBe(201);const row=(await response.json()).data;response=await page.request.patch('/api/v1/ops/listings/'+row.id+'/draft',{headers:{Origin:'http://localhost:8088'},data:{...base,title:editedTitle,version:row.version}});expect(response.status()).toBe(200);
 await page.goto('/account/properties');await expect(page.getByRole('heading',{name:editedTitle,exact:true})).toBeVisible();
 const forged={...base,unitId:undefined,unit:{communityId:'10000000-0000-4000-8000-000000000040',area:'80',beds:2,livingRooms:1,baths:1,orientation:'South',floor:1,privateAddress:'Unverified owner address'}};expect((await page.request.post('/api/v1/ops/listings',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:forged})).status()).toBe(403);
 await login(page,'buyer');expect((await page.request.get('/api/v1/ops/listings/'+row.id+'/draft')).status()).toBe(403);
});
