import {test,expect} from '@playwright/test';
import {login,apiRequest} from '../support/browser';
test('I03 author submits a private draft and moderator reviews, rejects incomplete publication and returns a reason',async({page},info)=>{
 const title='Workflow browser '+info.project.name+' '+crypto.randomUUID();
 await login(page,'agent','http://localhost:8089','/ops/listings');
 const response=await apiRequest(page,'/ops/listings',{unitId:'10000000-0000-4000-8000-000000001000',title,description:'A complete description for a property whose photographs still need review.',transaction:'sale',segment:'residential',currency:'CNY',price:'2450000.75',rentPeriod:null,furnishing:'Unfurnished',availableFrom:null,features:[]});expect(response.status()).toBe(201);const draft=(await response.json()).data;
 await page.reload();const authorRow=page.locator('.draft-workbench .record-row').filter({hasText:title});await authorRow.getByRole('button',{name:'Submit for review',exact:true}).click();await expect(page.locator('.draft-workbench').getByRole('status')).toHaveText('Property submitted for review');await expect(authorRow).toHaveCount(0);
 expect((await apiRequest(page,'/ops/listings/'+draft.id+'/transition',{status:'under_review',version:2})).status()).toBe(403);
 const submittedRow=page.getByRole('row').filter({hasText:title});await expect(submittedRow).toContainText('submitted');await expect(submittedRow.getByRole('button',{name:'Status',exact:true})).toHaveCount(0);
 await login(page,'moderator','http://localhost:8089','/ops/listings');const row=page.getByRole('row').filter({hasText:title});await row.getByRole('button',{name:'Status',exact:true}).click();await page.getByRole('combobox',{name:'Next status',exact:true}).selectOption('under_review');await page.getByRole('textbox',{name:'Reason for the change',exact:true}).fill('Checking property facts and approved photographs');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(row).toContainText('under_review');
 await row.getByRole('button',{name:'Status',exact:true}).click();await page.getByRole('combobox',{name:'Next status',exact:true}).selectOption('published');await page.getByRole('textbox',{name:'Reason for the change',exact:true}).fill('Attempting publication before photos are approved');await page.getByRole('checkbox',{name:'I have verified property facts and authority to list.',exact:true}).check();await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Publication requires complete facts');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 expect((await apiRequest(page,'/ops/listings/'+draft.id+'/transition',{status:'rejected',version:3})).status()).toBe(400);
 await row.getByRole('button',{name:'Status',exact:true}).click();await page.getByRole('combobox',{name:'Next status',exact:true}).selectOption('rejected');await page.getByRole('textbox',{name:'Reason for the change',exact:true}).fill('Please supply approved property photographs');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(row).toContainText('rejected');
 await login(page,'agent','http://localhost:8089','/ops/listings');await expect(page.locator('.draft-workbench .record-row').filter({hasText:title}).getByRole('button',{name:'Edit draft',exact:true})).toBeVisible();expect((await page.request.get('http://localhost:8088/api/v1/listings/'+draft.slug)).status()).toBe(404);
});
