import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const WEB=process.env.PUBLIC_WEB_URL||'http://localhost:8088',OPS=process.env.PUBLIC_OPS_URL||'http://localhost:8089';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});test.afterAll(()=>fixtures.end());
test('Q05 / P15 native management dashboard restores recorded dates and current property scope',async({page},info)=>{
 test.setTimeout(240000);const c=await fixtures.connect();let unit:string,listing:string,slug:string,email:string;try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true),set_config('app.admin','true',true)");unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0].id;slug='p15-native-'+crypto.randomUUID();listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,'00000000-0000-4000-8000-000000000002',agent_id,$2,'P15 synthetic available rental',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit,slug])).rows[0].id;await c.query("INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,'entire','month','CNY')",[listing]);await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,'00000000-0000-4000-8000-000000000002','recorded_listing',$2)",[unit,listing]);email=(await c.query("SELECT email FROM profiles WHERE id='00000000-0000-4000-8000-000000000005'")).rows[0].email;await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
 await login(page,'owner',WEB,'/account/management');const own=(await (await page.request.get(WEB+'/api/v1/me/management-grant-units/'+unit)).json()).data,g=(await (await page.request.post(WEB+'/api/v1/me/management-grants',{headers:{Origin:WEB,'Idempotency-Key':crypto.randomUUID()},data:{version:0,unitId:unit,unitVersion:own.version,ownerGrantVersion:own.ownerGrantVersion,organizationId:'10000000-0000-4000-8000-000000000002',expiresAt:'2036-12-31T00:00:00.000Z',consent:true}})).json()).data;expect(g.id).toBeTruthy();await login(page,'manager',OPS,'/ops/management');const invitation=(await (await page.request.post(OPS+'/api/v1/ops/tenant-invitations',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,grantId:g.id,grantVersion:g.version,name:'P15 verified native tenant',email}})).json()).data;expect(invitation.id).toBeTruthy();await login(page,'tenant',WEB,'/tenant/profile');const acceptance=await page.request.patch(WEB+'/api/v1/tenant-invitations/'+invitation.id,{headers:{Origin:WEB,'Idempotency-Key':crypto.randomUUID()},data:{version:1,action:'accept',consent:true,reason:'Verified native tenant accepts this property account link.'}});expect(acceptance.ok()).toBe(true);const tenantId=(await acceptance.json()).data.tenantId;
 await login(page,'manager',OPS,'/ops/management');const options=(await (await page.request.get(OPS+'/api/v1/ops/lease-draft-options/'+unit)).json()).data,create=await page.request.post(OPS+'/api/v1/ops/leases',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,unitId:unit,tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===tenantId).version,startDate:'2026-01-01',endDate:'2028-12-31',rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]}});expect(create.ok()).toBe(true);const lease=(await create.json()).data;const headers={Origin:OPS,'Idempotency-Key':crypto.randomUUID()},activation=await page.request.post(OPS+'/api/v1/ops/leases/'+lease.id+'/activate',{headers,data:{version:lease.version,unitVersion:lease.unitVersion,grantVersion:lease.grantVersion,tenantVersion:lease.tenantVersion,confirm:true}});expect(activation.ok()).toBe(true);
 const charge=(await fixtures.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,'10000000-0000-4000-8000-000000000002','2026-10-01','2026-10-05','200.20','CNY') RETURNING id,version",[lease.id])).rows[0];
 const source=(await (await page.request.get(OPS+'/api/v1/ops/payment-evidence-options/'+lease.id)).json()).data,sentinel='P15 PRIVATE FINANCE SOURCE '+crypto.randomUUID(),draft=await page.request.post(OPS+'/api/v1/ops/payment-records',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{...source,version:0,amount:'250.25',source:'bank_statement',reference:sentinel}});expect(draft.ok()).toBe(true);const payment=(await draft.json()).data,posting=await page.request.post(OPS+'/api/v1/ops/payment-records/'+payment.id+'/post',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:payment.version,leaseVersion:payment.leaseVersion,unitVersion:payment.unitVersion,grantVersion:payment.grantVersion,confirm:true}});expect(posting.ok()).toBe(true);const posted=(await posting.json()).data;
 const ledger=(await (await page.request.get(OPS+'/api/v1/ops/leases/'+lease.id+'/allocation-ledger')).json()).data,allocation=await page.request.post(OPS+'/api/v1/ops/allocations',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,leaseId:lease.id,leaseVersion:ledger.leaseVersion,unitVersion:ledger.unitVersion,grantVersion:ledger.grantVersion,paymentId:posted.id,paymentVersion:posted.version,chargeId:charge.id,chargeVersion:charge.version,amount:'50.05',currency:'CNY',confirm:true}});expect(allocation.ok()).toBe(true);
 const liability=(await (await page.request.get(OPS+'/api/v1/ops/leases/'+lease.id+'/deposit-ledger')).json()).data,deposited=await page.request.post(OPS+'/api/v1/ops/deposits',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,leaseId:lease.id,leaseVersion:liability.leaseVersion,unitVersion:liability.unitVersion,grantVersion:liability.grantVersion,liabilityVersion:liability.liabilityVersion,kind:'received',direction:'increase',amount:'100.10',currency:'CNY',reason:sentinel,confirm:true}});expect(deposited.ok()).toBe(true);
 await page.goto(OPS+'/ops/management');await page.getByRole('button',{name:'Dashboard',exact:true}).click();const panel=page.getByRole('region',{name:'Management source dashboard',exact:true});await expect(panel.getByRole('heading',{name:'Management dashboard',exact:true})).toBeVisible();const today=new Date().toISOString().slice(0,10),response=await page.request.get(OPS+'/api/v1/ops/management-dashboard?date='+today);expect(response.ok()).toBe(true);const dashboard=(await response.json()).data;for(const [key,label] of [['units','Granted units'],['occupied','Occupied units'],['vacant','Vacant units'],['unknownHistory','Unknown occupancy history']] as const)await expect(panel.getByRole('article',{name:label,exact:true}).locator('strong')).toHaveText(String(dashboard.occupancy[key]));const currency=panel.locator('.dashboard-currency').filter({has:page.getByRole('heading',{name:/^CNY/})});await expect(currency.locator('div').filter({has:page.getByText('Total outstanding',{exact:true})}).locator('dd')).toHaveText('CNY '+dashboard.arrears.find((x:any)=>x.currency==='CNY').total);await expect(panel).not.toContainText(sentinel);
 const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);await panel.getByLabel('Dashboard recorded date',{exact:true}).fill(yesterday);await panel.getByRole('button',{name:'Load dashboard date',exact:true}).focus();await page.keyboard.press('Enter');await expect(panel).toContainText('Effective date: '+yesterday);await page.reload();await expect(panel.getByLabel('Dashboard recorded date',{exact:true})).toHaveValue(yesterday);await expect(panel).toContainText('Effective date: '+yesterday);await panel.getByLabel('Dashboard recorded date',{exact:true}).fill(today);await panel.getByRole('button',{name:'Load dashboard date',exact:true}).click();await expect(panel).toContainText('Effective date: '+today);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/p15-dashboard-${info.project.name}.png`,scale:'css'});
 await page.goto(OPS+'/ops');await expect(page.getByRole('region',{name:'Management source dashboard',exact:true})).toBeVisible();expect((await page.request.get(OPS+'/api/v1/ops/dashboard')).ok()).toBe(true);
 await login(page,'owner',WEB,'/account/management');expect((await page.request.patch(WEB+'/api/v1/me/management-grants/'+g.id,{headers:{Origin:WEB,'Idempotency-Key':crypto.randomUUID()},data:{version:g.version,action:'revoke',reason:'P15 owner removes this property from current dashboard authority.'}})).ok()).toBe(true);await login(page,'manager',OPS,'/ops');const after=await page.request.get(OPS+'/api/v1/ops/management-dashboard?date='+today);expect(after.ok()).toBe(true);const d=(await after.json()).data;expect(d.occupancy.units).toBe(dashboard.occupancy.units-1);expect(d.occupancy.occupied).toBe(dashboard.occupancy.occupied-1);await expect(page.getByRole('article',{name:'Granted units',exact:true}).locator('strong')).toHaveText(String(d.occupancy.units));await login(page,'buyer',WEB,'/account');expect((await page.request.get(WEB+'/api/v1/ops/management-dashboard')).status()).toBe(403);
});
