import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(()=>fixtures.end());
async function findGrant(page:import('@playwright/test').Page,id:string){
 const row=page.locator('[data-management-grant="'+id+'"]');
 for(let n=1;n<=100;n++){
  await expect(page.locator('.management-grants > .loading')).toHaveCount(0);
  if(await row.count())return row;
  const next=page.getByRole('button',{name:'Next grant page',exact:true});
  await expect(next).toBeEnabled();
  const response=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).searchParams.get('page')===String(n+1)&&/\/api\/v1\/(me\/management-grants|ops\/managed-properties)$/.test(new URL(r.url()).pathname));
  await next.click();const loaded=await response;expect(loaded.ok()).toBe(true);await loaded.finished();
 }
 throw new Error('Created grant was not found within the bounded native pagination');
}

test('Q05 / P01 owner authorizes canonical property, retries lost receipt, manager portfolio and revocation',async({page,browser},info)=>{
 test.setTimeout(180000);let unit:string;const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true),set_config('app.admin','true',true)");unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0].id;const l=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status) SELECT $1,organization_id,'00000000-0000-4000-8000-000000000002',agent_id,$2,'P01 browser ownership fixture',description,'sale','residential','CNY','2400000.75','draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit,'p01-browser-'+crypto.randomUUID()])).rows[0];await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,'00000000-0000-4000-8000-000000000002','recorded_listing',$2)",[unit,l.id]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
 await login(page,'owner',(process.env.PUBLIC_WEB_URL||'http://localhost:8088'),'/account/management');const select=page.getByLabel('Recorded owned property',{exact:true});for(let n=0;n<20;n++){await expect(select).toBeVisible();if(await select.locator('option[value="'+unit+'"]') .count())break;await page.getByRole('button',{name:'Next property page',exact:true}).click();}await select.selectOption(unit);await page.getByLabel('Management organization',{exact:true}).selectOption('10000000-0000-4000-8000-000000000002');await page.getByLabel('Grant expiry (UTC)',{exact:true}).fill('2030-12-31T00:00');await page.getByRole('checkbox').check();let lost=false,id='';await page.route('**/api/v1/me/management-grants',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;const response=await route.fetch();expect(response.ok()).toBe(true);id=(await response.json()).data.id;await route.abort();}else await route.continue();});await page.getByRole('button',{name:'Save management grant',exact:true}).click();await expect(page.locator('.management-grants').getByRole('alert')).toBeVisible();await expect(select).toHaveValue(unit);await page.getByRole('button',{name:'Save management grant',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Management grant saved'})).toBeVisible();const row=await findGrant(page,id);await expect(row).toContainText(unit);await expect(row).toContainText('Current');
 const managerContext=await browser.newContext({...info.project.use,baseURL:(process.env.PUBLIC_OPS_URL||'http://localhost:8089')}),managerPage=await managerContext.newPage();try{await login(managerPage,'manager',(process.env.PUBLIC_OPS_URL||'http://localhost:8089'),'/ops/management');await managerPage.getByRole('button',{name:'Properties',exact:true}).click();await expect(await findGrant(managerPage,id)).toContainText(unit);expect((await new AxeBuilder({page:managerPage}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await managerPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await managerPage.screenshot({path:`evidence/p01-manager-${info.project.name}.png`,scale:'css'});await row.getByRole('button',{name:'Revoke authorization',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Reason for revocation',{exact:true}).fill('Owner ended this synthetic browser management grant.');await dialog.getByRole('button',{name:'Confirm revocation',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(row).toContainText('Revoked');await managerPage.getByRole('button',{name:'Refresh grants',exact:true}).click();await expect(managerPage.locator('[data-management-grant="'+id+'"]')).toHaveCount(0);expect((await managerPage.request.get((process.env.PUBLIC_OPS_URL||'http://localhost:8089')+'/api/v1/ops/managed-properties/'+id)).status()).toBe(404);await row.getByText('Authorization history',{exact:true}).click();await expect(row).toContainText('Owner ended this synthetic browser management grant.');expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/p01-owner-${info.project.name}.png`,scale:'css'});}finally{await managerContext.close();}
});
