import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg');
const fixtures=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(()=>fixtures.end());
async function cards(page:any){return page.locator('.map-list .listing-card').evaluateAll((elements:HTMLElement[])=>elements.map(x=>x.dataset.listingId));}
test('D05 real MapLibre clusters, selected cards and URL bounds synchronize with the same public list criteria',async({page},info)=>{
 const group=(await fixtures.query(`SELECT "communityId",count(*) FROM public_listings WHERE city='bj' AND transaction='sale' AND segment='residential' AND latitude IS NOT NULL GROUP BY "communityId" HAVING count(*)>1 ORDER BY count(*) DESC,"communityId" LIMIT 1`)).rows[0];expect(group).toBeTruthy();
 const expected=(await fixtures.query(`SELECT id,title FROM public_listings WHERE city='bj' AND transaction='sale' AND segment='residential' AND "communityId"=$1 ORDER BY "publishedAt" DESC NULLS LAST,id LIMIT 20`,[group.communityId])).rows;
 await page.goto('/bj/map?'+new URLSearchParams({communityId:group.communityId,transaction:'sale',segment:'residential',sort:'newest'}));await expect.poll(()=>cards(page)).toEqual(expected.map(x=>x.id));await expect(page.locator('.map-canvas')).toHaveAttribute('data-map-ready','true');
 await expect(page.locator('.map-cluster-count').first()).toBeVisible();const canvas=page.locator('.maplibregl-canvas');await canvas.click({position:{x:(await canvas.boundingBox())!.width/2,y:(await canvas.boundingBox())!.height/2}});await expect(page.locator('.map-cluster-list')).toBeVisible();await expect(page.locator('.map-cluster-list')).toContainText('properties in this area');
 await page.getByRole('button',{name:'Close area properties',exact:true}).click();await page.getByLabel('Select a property on the map').selectOption(expected[0].id);await expect(page.getByRole('region',{name:'Selected property',exact:true})).toContainText(expected[0].title);await expect(page.locator('.map-property.selected')).toHaveCount(1);
 await expect(page.getByRole('button',{name:'Search this area',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Search this area',exact:true}).click();await expect(page).toHaveURL(/bounds=/);const applied=page.url();const bounds=new URL(applied).searchParams.get('bounds')!.split(',').map(Number);
 const bounded=(await fixtures.query(`SELECT id FROM public_listings WHERE city='bj' AND transaction='sale' AND segment='residential' AND "communityId"=$1 AND longitude BETWEEN $2 AND $4 AND latitude BETWEEN $3 AND $5 ORDER BY "publishedAt" DESC NULLS LAST,id LIMIT 20`,[group.communityId,...bounds])).rows.map(x=>x.id);await expect.poll(()=>cards(page)).toEqual(bounded);await page.reload();await expect.poll(()=>cards(page)).toEqual(bounded);
 const axe=await new AxeBuilder({page}).include('main').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.locator('.property-map').scrollIntoViewIfNeeded();await page.screenshot({path:`evidence/d05-map-${info.project.name}.png`});
 await page.getByRole('button',{name:'Clear map area',exact:true}).click();await expect(page).not.toHaveURL(/bounds=/);await page.goBack();await expect(page).toHaveURL(applied);await expect.poll(()=>cards(page)).toEqual(bounded);await page.getByRole('link',{name:'List view',exact:true}).click();await expect(page).toHaveURL(/\/bj\/search\?/);expect(new URL(page.url()).searchParams.get('bounds')).toBe(new URL(applied).searchParams.get('bounds'));await expect(page.locator('.listing-card')).toHaveCount(bounded.length);
});
test('D05 a genuine tile failure and unavailable WebGL retain the matching property list and attribution',async({page},info)=>{
 const expected=(await fixtures.query(`SELECT id FROM public_listings WHERE city='bj' AND transaction='sale' AND segment='residential' ORDER BY "publishedAt" DESC NULLS LAST,id LIMIT 20`)).rows.map(x=>x.id);
 await page.route('**/api/v1/map/config',async route=>{const response=await route.fetch(),body=await response.json();body.data.style='http://localhost:8088/d05-map-style.json';body.data.attribution='D05 controlled tile fixture';await route.fulfill({response,json:body});});
 await page.route('**/d05-map-style.json',route=>route.fulfill({json:{version:8,sources:{fixture:{type:'raster',tiles:['http://localhost:8088/d05-failed-tile/{z}/{x}/{y}.png'],tileSize:256,attribution:'D05 tile attribution'}},layers:[{id:'tiles',type:'raster',source:'fixture'}]}}));await page.route('**/d05-failed-tile/**',route=>route.fulfill({status:503,body:'Tile provider unavailable'}));
 await page.goto('/bj/map?transaction=sale&segment=residential&sort=newest');await expect.poll(()=>cards(page)).toEqual(expected);await expect(page.locator('.map-failure')).toContainText('Map tiles are unavailable');await expect(page.locator('.map-attribution')).toContainText('D05 controlled tile fixture');await page.screenshot({path:`evidence/d05-tile-failure-${info.project.name}.png`});
 await page.unroute('**/api/v1/map/config');await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(context:any,...args:any[]){if(String(context).includes('webgl'))return null;return (original as any).call(this,context,...args);} as any;});await page.reload();await expect.poll(()=>cards(page)).toEqual(expected);await expect(page.locator('.map-failure')).toContainText('cannot display the map');
});
