import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('M02 native lost-ACK retry keeps text/files and creates one inert message; current participants download its private PDF',async({page},info)=>{
 test.setTimeout(180000);const agent=crypto.randomUUID(),slug='m02-browser-'+agent,pdf=Buffer.from('%PDF-1.4\n1 0 obj << /Type /Catalog >> endobj\n%%EOF'),text='<script>globalThis.chatExecuted=true</script> M02 '+agent.slice(0,8);let lead:string|undefined,thread:string|undefined;
 try{await staff(c=>c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'M02 browser agent',$3,'Synthetic durable message fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]));await login(page,'buyer','http://localhost:8088','/account/messages');const inquiry=await page.request.post('/api/v1/inquiries',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{resourceId:agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M02 browser customer',email:'browser-'+agent+'@example.test',phone:'123456789',message:'Discuss this actual private conversation.',consent:true}});expect(inquiry.ok()).toBe(true);const receipt=(await inquiry.json()).data;lead=receipt.id;thread=receipt.conversationId;await page.reload();await expect(page.getByLabel('Conversation participants')).toContainText('Agent inquiry');
 await page.getByRole('textbox',{name:'Your message',exact:true}).fill(text);await page.getByLabel('Attach images or PDF',{exact:true}).setInputFiles({name:'inspection-note.pdf',mimeType:'application/pdf',buffer:pdf});await page.getByLabel('I have permission to share these files with the conversation participants.',{exact:true}).check();let lost=true,clientId:string|undefined;await page.route('**/api/v1/conversations/'+thread+'/messages',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const body=route.request().postDataJSON(),response=await route.fetch();if(lost&&response.ok()){lost=false;clientId=body.clientId;await route.abort('failed');}else{expect(body.clientId).toBe(clientId);await route.fulfill({response});}});
 await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toHaveValue(text);await expect(page.getByLabel('I have permission to share these files with the conversation participants.',{exact:true})).toBeChecked();await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toHaveValue('');await page.unroute('**/api/v1/conversations/'+thread+'/messages');await expect(page.getByText(text,{exact:true})).toHaveCount(1);expect(await page.evaluate(()=>typeof(globalThis as any).chatExecuted)).toBe('undefined');const records=(await (await page.request.get('/api/v1/conversations/'+thread+'/messages')).json()).data;expect(records).toHaveLength(1);const message=records[0],attachment=message.attachments[0];expect(message.sequence).toBe('1');expect(message.body).toBe(text);expect(attachment.available).toBe(true);expect(await staff(async c=>(await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='message.persisted'",[thread])).rows[0].n)).toBe(1);const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'inspection-note.pdf',exact:true}).click();expect(await readFile((await (await downloadPromise).path())!)).toEqual(pdf);expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/m02-consumer-${info.project.name}.png`,scale:'css'});
 await login(page,'agent','http://localhost:8089','/ops/messages');await expect(page.getByText(text,{exact:true})).toBeVisible();expect((await page.request.get('http://localhost:8089'+attachment.url)).ok()).toBe(true);await page.getByRole('textbox',{name:'Reply to client',exact:true}).fill('The file reached its current assigned agent.');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.message').filter({hasText:'The file reached its current assigned agent.'})).toBeVisible();expect((await (await page.request.get('http://localhost:8089/api/v1/conversations/'+thread+'/messages')).json()).data.map((m:any)=>m.sequence)).toEqual(['1','2']);expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/m02-agent-${info.project.name}.png`,scale:'css'});
 await login(page,'outsider','http://localhost:8089','/ops/messages');expect((await page.request.get('http://localhost:8089'+attachment.url)).status()).toBe(404);expect((await apiRequest(page,'/conversations/'+thread+'/messages',{version:0,conversationVersion:2,clientId:crypto.randomUUID(),body:'Unrelated sender',attachments:[]})).status()).toBe(404);
 }finally{await staff(async c=>{if(lead)await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=$1",[lead]);if(thread)await c.query("UPDATE conversations SET state='closed',version=version+1 WHERE id=$1",[thread]);await c.query('UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1',[agent]);});}
});
