import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test.use({actionTimeout:15000});
test('T02 method changes show exact fixture cents, expanded schedule and English invalid-input states',async({page},info)=>{
 await page.goto('/bj/tools/mortgage');await expect(page.getByLabel('Nominal annual interest rate (%)',{exact:true})).toHaveValue('3.50');await page.getByLabel('Property price (CNY)',{exact:true}).fill('120000');await page.getByLabel('Down payment (CNY)',{exact:true}).fill('0');await page.getByLabel('Nominal annual interest rate (%)',{exact:true}).fill('6');await page.getByLabel('Loan term (years)',{exact:true}).fill('10');await page.getByRole('button',{name:'Calculate payments',exact:true}).click();await expect(page.locator('.mortgage-monthly')).toHaveText('CNY 1,332.25');await expect(page.locator('.mortgage-totals')).toContainText('CNY 39,869.30');await expect(page.getByRole('table')).toContainText('6% nominal annual rate');await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(12);await page.getByRole('button',{name:'Show full schedule',exact:true}).click();await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(120);await expect(page.getByRole('table').locator('tbody tr').last()).toContainText('0.00');await page.getByLabel('Repayment method',{exact:true}).selectOption('equal_principal');await expect(page.locator('.mortgage-monthly')).toHaveCount(0);await page.getByRole('button',{name:'Calculate payments',exact:true}).click();await expect(page.locator('.mortgage-monthly')).toHaveText('CNY 1,600.00');await expect(page.locator('.mortgage-totals')).toContainText('CNY 36,300.00');await expect(page.locator('.mortgage-results')).toContainText('later payments decrease');await expect(page.getByRole('table')).toContainText('Equal principal');await expect(page.locator('.mortgage-results')).toContainText('no lender approval');expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/t02-mortgage-${info.project.name}.png`,scale:'css'});
 for(const [field,value,message] of [['Down payment (CNY)','130000','Down payment must be less'],['Down payment (CNY)','120000','loan principal must be positive'],['Property price (CNY)','broken','Enter a property price'],['Loan term (years)','0','Enter a whole loan term'],['Nominal annual interest rate (%)','-1','between 0 and 30']]){await page.getByLabel('Property price (CNY)',{exact:true}).fill('120000');await page.getByLabel('Down payment (CNY)',{exact:true}).fill('0');await page.getByLabel('Loan term (years)',{exact:true}).fill('10');await page.getByLabel('Nominal annual interest rate (%)',{exact:true}).fill('6');await page.getByLabel(field,{exact:true}).fill(value);await page.getByRole('button',{name:'Calculate payments',exact:true}).click();await expect(page.locator('#mortgage-error').getByRole('alert')).toContainText(message);await expect(page.locator('.mortgage-monthly')).toHaveCount(0);await expect(page.locator('main#main')).not.toContainText('NaN');await expect(page.getByLabel(field,{exact:true})).toHaveValue(value);}
});

test('T03 downloaded schedule matches displayed exact totals and configured notes with safe Unicode title',async({page},info)=>{
 await page.goto('/bj/tools/mortgage');await page.getByLabel('Property price (CNY)',{exact:true}).fill('120000');await page.getByLabel('Down payment (CNY)',{exact:true}).fill('0');await page.getByLabel('Nominal annual interest rate (%)',{exact:true}).fill('6');await page.getByLabel('Loan term (years)',{exact:true}).fill('10');const response=page.waitForResponse(r=>r.url().includes('/api/v1/tools/mortgage-estimate')&&r.request().method()==='POST');await page.getByRole('button',{name:'Calculate payments',exact:true}).click();const result=(await (await response).json()).data;await expect(page.locator('[data-mortgage-estimate-notes]')).toHaveText(result.estimateNotes);await expect(page.locator('.mortgage-results')).toContainText('no lender approval');const title=' =SUM(A1) · 北京 "Home"';await page.getByLabel('Schedule title (optional; avoid personal details)',{exact:true}).fill(title);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export repayment schedule',exact:true}).click();const download=await pending;expect(download.suggestedFilename()).toBe('haven-repayment-schedule.csv');const {readFile}=await import('node:fs/promises'),{readCsv,csvCents}=await import('../support/csv'),rows=readCsv(await readFile((await download.path())!,'utf8')),start=rows.findIndex(row=>row[0]==='Month'),schedule=rows.slice(start+1),metadata=new Map(rows.slice(0,start).map(row=>[row[0],row[1]]));expect(rows[0]).toEqual(['Schedule title',"'"+title]);expect(metadata.get('Estimate notes')).toBe(result.estimateNotes);expect(metadata.get('Market configuration version')).toBe(String(result.marketVersion));expect(schedule).toHaveLength(result.months);for(const [column,total] of [[1,result.principal],[2,result.totalInterest],[3,result.totalRepaid]] as const)expect(schedule.reduce((sum,row)=>sum+csvCents(row[column]),0n)).toBe(csvCents(total));expect(schedule.at(-1)?.[4]).toBe('0.00');expect(metadata.get('Total repaid')).toBe(result.totalRepaid);expect(metadata.get('Total interest')).toBe(result.totalInterest);expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/t03-mortgage-${info.project.name}.png`,scale:'css'});
});
