import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {login} from '../support/browser';
import {transaction} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {alertServiceCall} from '../../apps/worker/src/alerts';
const origin='http://localhost:8088',headers=()=>({Origin:origin,'Idempotency-Key':crypto.randomUUID()});
test('A05 optional preferences persist, real matching alert displays acceptance and can be read, opt-out prevents the next send',async({page},info)=>{
 await login(page,'buyer');const me=(await(await page.request.get('/api/v1/me')).json()).data,id=me.id,label='A05BROWSER'+crypto.randomUUID().replaceAll('-','');let searchId='';
 // Isolated fixture verification represents a verified identity claim; it does not exercise provider verification.
 await transaction(workerActor,c=>c.query('UPDATE profiles SET email_verified=true WHERE id=$1',[id]));
 async function setOff(){const prefs=(await(await page.request.get('/api/v1/me/notification-preferences')).json()).data;const result=await page.request.patch('/api/v1/me/notification-preferences',{headers:headers(),data:{...prefs,emailEnabled:false,inAppEnabled:false}});expect(result.ok()).toBe(true);}
 async function publish(){return transaction(workerActor,async c=>{const listing=(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,$2,description,'sale',segment,'CNY',price,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,version`,['a05-browser-'+crypto.randomUUID(),label])).rows[0],event=crypto.randomUUID();await c.query("INSERT INTO outbox(id,aggregate_id,kind,payload,dispatched_at) VALUES($1,$2,'listing.published','{}',now())",[event,listing.id]);return {...listing,event};});}
 try{
  await setOff();await page.goto('/account/notifications');await expect(page.getByLabel('Email alerts',{exact:true})).not.toBeChecked();await expect(page.getByLabel('In-app alerts',{exact:true})).not.toBeChecked();await page.getByLabel('Email alerts',{exact:true}).check();await expect(page.getByRole('status')).toContainText('preferences saved');await page.getByLabel('In-app alerts',{exact:true}).check();await expect.poll(async()=> (await(await page.request.get('/api/v1/me/notification-preferences')).json()).data.inAppEnabled).toBe(true);await page.reload();await expect(page.getByLabel('Email alerts',{exact:true})).toBeChecked();await expect(page.getByLabel('In-app alerts',{exact:true})).toBeChecked();
  const created=await page.request.post('/api/v1/me/saved-searches',{headers:headers(),data:{version:0,name:'Browser alert '+label,filters:{city:'bj',currency:'CNY',transaction:'sale',text:label},cadence:'daily'}});expect(created.ok()).toBe(true);searchId=(await created.json()).data.id;const listing=await publish(),service={plan:(id:string,listingVersion:number)=>alertServiceCall('/plan/'+id,'POST',{version:0,listingVersion}),deliver:(id:string,version:number)=>alertServiceCall('/'+id+'/deliver','POST',{version})};await service.plan(listing.event,listing.version);const digest=(await transaction(workerActor,c=>c.query('SELECT * FROM alert_digests WHERE search_id=$1',[searchId]))).rows[0];await transaction(workerActor,c=>c.query("UPDATE alert_digests SET due_at=now()-interval '1 second' WHERE id=$1",[digest.id]));expect((await service.deliver(digest.id,digest.version)).status).toBe('accepted');await page.reload();await expect(page.getByRole('heading',{name:'Accepted by email provider',exact:true}).first()).toBeVisible();const notice=page.locator('article').filter({has:page.getByRole('heading',{name:'New homes for Browser alert '+label,exact:true})});await expect(notice.getByText('Unread',{exact:true})).toBeVisible();await notice.getByRole('button',{name:'Mark as read',exact:true}).click();await expect(notice.getByText('Read',{exact:true})).toBeVisible();await page.reload();await expect(notice.getByText('Read',{exact:true})).toBeVisible();
  const axe=await new AxeBuilder({page}).include('main').analyze();expect(axe.violations.filter(row=>row.impact==='serious'||row.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/a05-notifications-${info.project.name}.png`,scale:'css'});
  const next=await publish();await service.plan(next.event,next.version);const queued=(await transaction(workerActor,c=>c.query("SELECT * FROM alert_digests WHERE search_id=$1 AND status='queued'",[searchId]))).rows[0];await page.getByLabel('Email alerts',{exact:true}).uncheck();await expect(page.getByRole('status')).toContainText('preferences saved');await page.getByLabel('In-app alerts',{exact:true}).uncheck();await expect.poll(async()=> (await(await page.request.get('/api/v1/me/notification-preferences')).json()).data.inAppEnabled).toBe(false);await transaction(workerActor,c=>c.query("UPDATE alert_digests SET due_at=now()-interval '1 second' WHERE id=$1",[queued.id]));expect((await service.deliver(queued.id,queued.version)).status).toBe('cancelled');const count=await fetch('http://mail:8025/api/v1/search?query='+encodeURIComponent('message-id:alert-'+queued.id+'@'+new URL(process.env.PUBLIC_WEB_URL!).hostname)).then(r=>r.json());expect(count.messages_count).toBe(0);
 }finally{await setOff();if(searchId){const searches=(await(await page.request.get('/api/v1/me/saved-searches')).json()).data,row=searches.find((row:any)=>row.id===searchId);if(row)await page.request.delete('/api/v1/me/saved-searches/'+searchId,{headers:headers(),data:{version:row.version}});}await transaction(workerActor,c=>c.query('UPDATE profiles SET email_verified=false WHERE id=$1',[id]));}
});
test('A05 preference outage rolls back optimism and a stale version reloads the current choice',async({page})=>{
 await login(page,'owner');await page.goto('/account/notifications');const checkbox=page.getByLabel('In-app alerts',{exact:true}),before=await checkbox.isChecked();await page.route('**/api/v1/me/notification-preferences',async route=>{if(route.request().method()==='PATCH')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'PROVIDER_UNAVAILABLE',message:'Preferences temporarily unavailable',requestId:'a05-fixture'}})});else await route.continue();});await checkbox.setChecked(!before);await expect(page.getByRole('main').getByRole('alert')).toContainText('Preferences temporarily unavailable');await expect(checkbox).toBeChecked({checked:before});await page.unroute('**/api/v1/me/notification-preferences');const prefs=(await(await page.request.get('/api/v1/me/notification-preferences')).json()).data;await page.request.patch('/api/v1/me/notification-preferences',{headers:headers(),data:{...prefs,inAppEnabled:!before}});await checkbox.setChecked(!before);await expect(page.getByRole('main').getByRole('alert')).toContainText('preferences changed');await expect(checkbox).toBeChecked({checked:!before});const fresh=(await(await page.request.get('/api/v1/me/notification-preferences')).json()).data;await page.request.patch('/api/v1/me/notification-preferences',{headers:headers(),data:{...fresh,inAppEnabled:before}});
});
