import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixturePool=new Pool({connectionString:process.env.DATABASE_URL});
async function staff(work:(c:any)=>Promise<any>){const c=await fixturePool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const result=await work(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
test.afterAll(()=>fixturePool.end());
test('O05 owner proposes an exact price, independent approval publishes it, and pause/renew/completion remain scoped',async({page},info)=>{
 test.setTimeout(180000);const title='O05 browser owned '+info.project.name+' '+crypto.randomUUID(),source=await staff(async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0];const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,created_by,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,$3,description,'sale','residential','CNY','2450000.25',photos,'published',owner_id,now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug,owner_id",[unit.id,'o05-browser-'+crypto.randomUUID(),title])).rows[0];await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3)",[unit.id,row.owner_id,row.id]);return row;});
 try{await login(page,'owner','http://localhost:8088','/bj/list-property');let row=page.getByRole('article',{name:'Owner listing '+title,exact:true});await expect(row).toContainText('CNY 2,450,000.25');await row.getByRole('button',{name:'Request price change',exact:true}).click();await row.getByLabel('Proposed asking price',{exact:true}).fill('2650000.75');await row.getByLabel('Reason for your request',{exact:true}).fill('O05 browser synthetic owner price reason');await row.getByRole('button',{name:'Submit price revision',exact:true}).click();await expect(row).toContainText('awaiting independent review');expect((await (await page.request.get('/api/v1/listings/'+source.slug)).json()).data.price).toBe('2450000.25');const axe=await new AxeBuilder({page}).include('section[aria-label="Owner listing controls"]').analyze();expect(axe.violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await row.screenshot({path:`evidence/o05-pending-${info.project.name}.png`,scale:'css'});
 await login(page,'moderator','http://localhost:8089','/ops/reviews');const revision=page.locator('.review-card').filter({has:page.getByRole('heading',{name:title,exact:true})});await revision.getByRole('button',{name:'Approve revision',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Approve revision',exact:true});await dialog.getByLabel('I have verified these changes and the authority to list.',{exact:true}).check();await dialog.getByLabel('Revision decision reason',{exact:true}).fill('Independent synthetic owner authority and price review');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.ops-notice')).toContainText('Review saved');expect((await (await page.request.get('http://localhost:8089/api/v1/listings/'+source.slug)).json()).data.price).toBe('2650000.75');
 await login(page,'owner','http://localhost:8088','/bj/list-property');row=page.getByRole('article',{name:'Owner listing '+title,exact:true});await expect(row).toContainText('CNY 2,650,000.75');await row.getByRole('button',{name:'Pause listing',exact:true}).click();await row.getByLabel('Reason for your request',{exact:true}).fill('O05 owner temporarily pauses public availability');await row.getByRole('button',{name:'Confirm listing status',exact:true}).click();await expect(row.getByRole('button',{name:'Request renewed review',exact:true})).toBeVisible();expect((await page.request.get('/api/v1/listings/'+source.slug)).status()).toBe(404);await row.getByRole('button',{name:'Request renewed review',exact:true}).click();await row.getByLabel('Reason for your request',{exact:true}).fill('O05 owner requests renewed independent review');await row.getByRole('button',{name:'Submit renewed review',exact:true}).click();await expect(row).toContainText('Renewal submitted for independent review');expect((await page.request.get('/api/v1/listings/'+source.slug)).status()).toBe(404);await row.screenshot({path:`evidence/o05-renewal-${info.project.name}.png`,scale:'css'});
 const current=(await (await page.request.get('/api/v1/me/owner-listings')).json()).data.find((r:any)=>r.id===source.id);expect((await page.request.post('/api/v1/ops/listings/'+source.id+'/transition',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{version:current.version,status:'published',verified:true}})).status()).toBe(403);
 await login(page,'moderator','http://localhost:8089','/ops/reviews');expect((await apiRequest(page,'/ops/listings/'+source.id+'/transition',{status:'under_review',version:current.version,reason:'Independent review of owner renewal request'})).status()).toBe(201);expect((await apiRequest(page,'/ops/listings/'+source.id+'/transition',{status:'published',version:current.version+1,verified:true,reason:'Independent renewal authority and availability checked'})).status()).toBe(201);await login(page,'owner','http://localhost:8088','/bj/list-property');row=page.getByRole('article',{name:'Owner listing '+title,exact:true});await row.getByRole('button',{name:'Mark sold',exact:true}).click();await row.getByLabel('Reason for your request',{exact:true}).fill('O05 synthetic owner records sale completion');await row.getByRole('button',{name:'Confirm listing status',exact:true}).click();await expect(row).toContainText('sold');await expect(row.getByRole('button',{name:'Request price change',exact:true})).toHaveCount(0);expect((await page.request.get('/api/v1/listings/'+source.slug)).status()).toBe(404);
 }finally{await staff(c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[source.id]));}
});
test('O05 owned unknown amounts stay unknown and commercial rental prices retain exact area basis and billing period',async({page},info)=>{
 const title='O05 amount context '+info.project.name+' '+crypto.randomUUID();const ids=await staff(async c=>{const ids=[];for(const kind of ['unknown','commercial']){const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0];const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status) SELECT $1,organization_id,owner_id,agent_id,$2,$3,description,$4,$5,'CNY',$6,$7,photos,'draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,owner_id",[unit.id,'o05-context-'+crypto.randomUUID(),title+' '+kind,kind==='commercial'?'rent':'sale',kind==='commercial'?'commercial':'residential',kind==='commercial'?'2400.75':null,kind==='commercial'?'year':null])).rows[0];if(kind==='commercial')await c.query("INSERT INTO commercial_details(listing_id,property_type,gross_area,usable_area,area_basis,rent_basis,fit_out,floor,parking_spaces,permitted_uses) VALUES($1,'office','180.25','150.75','usable','per_area','Furnished',7,2,ARRAY['Office'])",[row.id]);await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3)",[unit.id,row.owner_id,row.id]);ids.push(row.id);}return ids;});
 try{await login(page,'owner','http://localhost:8088','/bj/list-property');const unknown=page.getByRole('article',{name:'Owner listing '+title+' unknown',exact:true});await expect(unknown).toContainText('Price not provided');await expect(unknown.getByRole('button',{name:'Request price change',exact:true})).toHaveCount(0);const commercial=page.getByRole('article',{name:'Owner listing '+title+' commercial',exact:true});await expect(commercial).toContainText('CNY 2,400.75 / m² (usable) / year');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await commercial.screenshot({path:`evidence/o05-commercial-${info.project.name}.png`,scale:'css'});
 }finally{await staff(c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[ids]));}
});
