import '../support/env';
import {test,expect} from '@playwright/test';
import fs from 'node:fs';
test.skip(process.env.HAVEN_BROWSER_LAB!=='true','Opt-in measured lab; no field-vitals claim');
for(const route of ['/bj','/bj/buy?sort=newest','/bj/buy/home-1'])test('Q07 mobile lab '+route,async({page,context},info)=>{
 test.setTimeout(120000);const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:1600000/8,uploadThroughput:750000/8});
 await page.addInitScript(()=>{
  const lab={lcp:0,cls:0,session:0,firstShift:0,lastShift:0,lcpElement:null as unknown,shifts:[] as unknown[],events:[] as {id:number;duration:number;name:string}[],eventTiming:PerformanceObserver.supportedEntryTypes.includes('event')};(window as any).__havenLab=lab;
  new PerformanceObserver(list=>{for(const e of list.getEntries()){lab.lcp=e.startTime;const item=e as any;lab.lcpElement={tag:item.element?.tagName,className:item.element?.className,url:item.url,size:item.size,renderTime:item.renderTime,loadTime:item.loadTime};}}).observe({type:'largest-contentful-paint',buffered:true});
  new PerformanceObserver(list=>{for(const entry of list.getEntries()){const e=entry as any;if(e.hadRecentInput)continue;lab.shifts.push({at:e.startTime,value:e.value,sources:e.sources?.map((s:any)=>({tag:s.node?.tagName,className:s.node?.className,previous:s.previousRect,current:s.currentRect}))});if(!lab.firstShift||e.startTime-lab.lastShift>1000||e.startTime-lab.firstShift>5000){lab.firstShift=e.startTime;lab.session=0;}lab.lastShift=e.startTime;lab.session+=e.value;lab.cls=Math.max(lab.cls,lab.session);}}).observe({type:'layout-shift',buffered:true});
  if(lab.eventTiming)new PerformanceObserver(list=>{for(const entry of list.getEntries()){const e=entry as any;if(e.interactionId)lab.events.push({id:e.interactionId,duration:e.duration,name:e.name});}}).observe({type:'event',buffered:true,durationThreshold:16} as any);
 });
 const response=await page.goto(route);expect(response?.ok()).toBe(true);await expect(page.locator('#main')).toBeVisible();await expect(page.locator('.error-box')).toHaveCount(0);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(3000);
 for(let i=0;i<3;i++){await page.locator('.city-control').click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}await page.waitForTimeout(600);
 const result=await page.evaluate(()=>{const v=(window as any).__havenLab;return {...v,labInpUpperBoundMs:Math.max(16,...v.events.map((e:any)=>e.duration)),resources:performance.getEntriesByType('resource').map((r:any)=>({name:r.name,startTime:r.startTime,duration:r.duration,bytes:r.transferSize})),navigation:JSON.parse(JSON.stringify(performance.getEntriesByType('navigation')[0])),userAgent:navigator.userAgent};});
 const report={label:'P',fieldMeasurement:false,emulatedDevice:true,route,viewport:info.project.use.viewport,cpuSlowdown:4,network:{latencyMs:150,downloadBitsPerSecond:1600000,uploadBitsPerSecond:750000},interaction:'Three actual city-dialog open/close cycles',inpMethod:'Maximum Event Timing interaction duration in this short lab; 16 ms observation threshold upper bound when no slower event is emitted',...result,targets:{lcpMs:2500,inpMs:200,cls:.1}};
 fs.mkdirSync('evidence/performance',{recursive:true});fs.writeFileSync('evidence/performance/lab-'+info.project.name+'-'+route.replace(/[^a-z0-9]/gi,'-')+'.json',JSON.stringify(report,null,2)+'\n');expect(result.eventTiming).toBe(true);expect(result.lcp).toBeGreaterThan(0);expect(result.lcp).toBeLessThanOrEqual(2500);expect(result.labInpUpperBoundMs).toBeLessThanOrEqual(200);expect(result.cls).toBeLessThanOrEqual(.1);
});
