import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {login} from '../support/browser';
const OPS=process.env.PUBLIC_OPS_URL||'http://localhost:8089',agentId='00000000-0000-4000-8000-000000000003',adminId='00000000-0000-4000-8000-000000000010';
test('S04 actual admin grants and revokes staff, suspends agent with lost response, revokes real sessions and retains immutable history',async({page,browser},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);const agentContext=await browser.newContext({viewport:page.viewportSize()!,isMobile:info.project.name==='mobile',hasTouch:info.project.name==='mobile'}),agent=await agentContext.newPage();
 await login(agent,'agent',OPS,'/ops/listings');await login(page,'admin',OPS,'/ops/admin');const region=page.getByRole('region',{name:'Platform account administration',exact:true});await region.getByLabel('Find platform account',{exact:true}).fill(agentId);await region.getByRole('button',{name:'Search accounts',exact:true}).click();await region.getByRole('button',{name:'Manage account '+agentId,exact:true}).click();const dialog=page.getByRole('dialog',{name:'Account administration',exact:true});await expect(dialog).toContainText('Agent Demo');const before=(await (await page.request.get(OPS+'/api/v1/ops/users/'+agentId)).json()).data;let clean=false;
 try{
 await dialog.getByLabel('Administration reason',{exact:true}).fill('S04 native approved editorial permission for this synthetic agent.');await dialog.getByLabel('Platform staff role',{exact:true}).selectOption('editor');await dialog.getByRole('button',{name:'Save staff permission and revoke sessions',exact:true}).click();await expect(dialog).toContainText('editor · active');expect((await agent.request.get(OPS+'/api/v1/me')).status()).toBe(401);await login(agent,'agent',OPS,'/ops/rankings');await expect(agent.getByRole('heading',{name:'Home sections and taxonomy',exact:true})).toBeVisible();
 await dialog.getByLabel('Administration reason',{exact:true}).fill('S04 native withdrawing the temporary synthetic editorial assignment.');await dialog.getByLabel('Platform staff role',{exact:true}).selectOption('editor');await dialog.getByLabel('Staff permission state',{exact:true}).selectOption('revoked');await dialog.getByRole('button',{name:'Save staff permission and revoke sessions',exact:true}).click();await expect(dialog).toContainText('editor · revoked');expect((await agent.request.get(OPS+'/api/v1/me')).status()).toBe(401);await login(agent,'agent',OPS,'/ops/listings');expect((await agent.request.get(OPS+'/api/v1/ops/home-content?city=bj')).status()).toBe(403);
 const reason='S04 native audited synthetic agent suspension '+crypto.randomUUID();await dialog.getByLabel('Administration reason',{exact:true}).fill(reason);let lost=false;await page.route('**/api/v1/ops/users/'+agentId+'/suspend',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;const r=await route.fetch();expect(r.ok(),await r.text()).toBe(true);await route.abort();}else await route.continue();});await dialog.getByRole('button',{name:'Suspend account and revoke sessions',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Administration reason',{exact:true})).toHaveValue(reason);expect((await agent.request.get(OPS+'/api/v1/me')).status()).toBe(401);expect((await agent.request.get(OPS+'/api/v1/ops/listings')).status()).toBe(401);await dialog.getByRole('button',{name:'Suspend account and revoke sessions',exact:true}).click();await expect(dialog.getByRole('button',{name:'Reactivate account',exact:true})).toBeVisible();await page.unroute('**/api/v1/ops/users/'+agentId+'/suspend');const suspended=(await (await page.request.get(OPS+'/api/v1/ops/users/'+agentId)).json()).data;expect(suspended.state).toBe('suspended');expect(suspended.version).toBe(before.version+1);expect(suspended.activity.filter((h:any)=>h.reason===reason)).toHaveLength(1);await expect(dialog).toContainText(reason);expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/s04-suspension-${info.project.name}.png`,scale:'css'});
 await page.reload();await expect(dialog).toContainText(reason);await dialog.getByLabel('Administration reason',{exact:true}).fill('S04 native approved reinstatement after synthetic test review.');await dialog.getByRole('button',{name:'Reactivate account',exact:true}).click();await expect(dialog.getByRole('button',{name:'Suspend account and revoke sessions',exact:true})).toBeVisible();await login(agent,'agent',OPS,'/ops/listings');expect((await agent.request.get(OPS+'/api/v1/me')).ok()).toBe(true);expect((await agent.request.get(OPS+'/api/v1/ops/users')).status()).toBe(403);expect((await agent.request.post(OPS+'/api/v1/ops/users/'+agentId+'/staff',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,profileVersion:suspended.version+1,role:'admin',status:'active',reason:'Unauthorized self escalation must be refused.'}})).status()).toBe(403);await page.screenshot({path:`evidence/s04-history-${info.project.name}.png`,scale:'css'});await dialog.getByRole('button',{name:'Close dialog',exact:true}).click();await expect(region.getByRole('link',{name:'Review agent credentials',exact:true})).toHaveAttribute('href','/ops/credential-reviews');await expect(region.getByRole('link',{name:'Review listing publication',exact:true})).toHaveAttribute('href','/ops/reviews');await region.getByLabel('Find platform account',{exact:true}).fill(adminId);await region.getByRole('button',{name:'Search accounts',exact:true}).click();await region.getByRole('button',{name:'Manage account '+adminId,exact:true}).click();await expect(dialog).toContainText('You cannot change your own account state or staff authority.');await expect(dialog.getByLabel('Administration reason',{exact:true})).toHaveCount(0);clean=true;
 }finally{await page.unroute('**/api/v1/ops/users/'+agentId+'/suspend');if(!clean){const response=await page.request.get(OPS+'/api/v1/ops/users/'+agentId);if(response.ok()){let r=(await response.json()).data;if(r.state==='suspended'){await page.request.post(OPS+'/api/v1/ops/users/'+agentId+'/suspend',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:r.version,action:'reactivate',reason:'S04 authorized cleanup restores the synthetic agent after a failed test.'}});r=(await (await page.request.get(OPS+'/api/v1/ops/users/'+agentId)).json()).data;}const permission=r.staff.find((s:any)=>s.role==='editor');if(permission?.status==='active')await page.request.post(OPS+'/api/v1/ops/users/'+agentId+'/staff',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:permission.version,profileVersion:r.version,role:'editor',status:'revoked',reason:'S04 authorized cleanup revokes the synthetic temporary staff permission.'}});}}await agentContext.close();}
});
