import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('V01 native vendor saves one lost-ACK draft with declared scanned portfolio; independent reviewer publishes it in the selected area',async({page},info)=>{
 test.setTimeout(180000);const title='V01 native provider '+crypto.randomUUID().slice(0,8);let id:string|undefined;
 try{await login(page,'vendor','http://localhost:8089','/ops/providers');await page.getByRole('button',{name:'New provider profile',exact:true}).click();await page.getByLabel('Provider name',{exact:true}).fill(title);await page.getByLabel('Service description',{exact:true}).fill('A synthetic service profile for native workflow verification, not a verified actual business.');await page.getByLabel('Chaoyang',{exact:true}).check();await page.getByLabel('Portfolio photo (JPEG or PNG)',{exact:true}).setInputFiles('apps/web/public/homes/home-1.jpg');await page.getByLabel('Photo description',{exact:true}).fill('Synthetic portfolio room');await page.getByLabel('Portfolio sharing rights',{exact:true}).fill('Supplied synthetic photograph permitted for local acceptance tests.');await page.getByLabel('Portfolio caption',{exact:true}).fill('Local acceptance portfolio example.');await page.getByRole('button',{name:'Add portfolio photo',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Photo ready'})).toBeVisible();let lost=true,key:string|undefined;
 await page.route('**/api/v1/me/providers',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch();if(lost&&response.ok()){lost=false;key=route.request().headers()['idempotency-key'];id=(await response.json()).data.id;await route.abort();}else{expect(route.request().headers()['idempotency-key']).toBe(key);await route.fulfill({response});}});await page.getByRole('button',{name:'Save provider draft',exact:true}).click();await expect(page.locator('[aria-label="My provider profiles"]').getByRole('alert')).toBeVisible();await expect(page.getByLabel('Provider name',{exact:true})).toHaveValue(title);await page.getByRole('button',{name:'Save provider draft',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Draft saved'})).toBeVisible();await page.unroute('**/api/v1/me/providers');const owned=(await (await page.request.get('http://localhost:8089/api/v1/me/providers')).json()).data;expect(owned.filter((p:any)=>p.name===title)).toHaveLength(1);id=owned.find((p:any)=>p.name===title).id;expect((await page.request.get('http://localhost:8089/api/v1/renovation/providers/'+id+'?city=bj')).status()).toBe(404);
 await page.getByRole('button',{name:'Submit provider for review',exact:true}).click();await expect(page.getByRole('button',{name:'Withdraw provider submission',exact:true})).toBeVisible();await expect(page.getByLabel('Provider name',{exact:true})).toBeDisabled();expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/v01-vendor-${info.project.name}.png`,scale:'css'});
 await login(page,'moderator','http://localhost:8089','/ops/provider-reviews');const card=page.locator('[data-provider-id="'+id+'"]');await expect(card).toContainText(title);await expect(card).toContainText('Declared rights');await card.getByLabel('Decision reason for '+title,{exact:true}).fill('Independent synthetic profile and declared portfolio review completed.');await card.getByLabel('I reviewed the profile, service areas and declared portfolio rights.',{exact:true}).check();await card.getByRole('button',{name:'Approve profile',exact:true}).click();await expect(card).toHaveCount(0);await page.getByLabel('Review state',{exact:true}).selectOption('approved');await expect(card).toContainText(title);expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/v01-review-${info.project.name}.png`,scale:'css'});const publicRow=(await (await page.request.get('http://localhost:8089/api/v1/renovation/providers/'+id+'?city=bj')).json()).data;expect(publicRow.name).toBe(title);expect(publicRow.photos).toHaveLength(1);expect((await page.request.get('http://localhost:8089'+publicRow.photos[0])).ok()).toBe(true);expect(publicRow).not.toHaveProperty('owner_id');expect(publicRow).not.toHaveProperty('review_note');const area=await staff(async c=>(await c.query("SELECT d.id FROM districts d JOIN cities ci ON ci.id=d.city_id WHERE ci.slug='bj' AND d.name='Chaoyang'")).rows[0].id);expect((await (await page.request.get('http://localhost:8089/api/v1/renovation/providers?city=bj&districtId='+area+'&text='+encodeURIComponent(title))).json()).data.map((p:any)=>p.id)).toEqual([id]);expect((await page.request.get('http://localhost:8089/api/v1/renovation/providers/'+id+'?city=sh')).status()).toBe(404);
 await login(page,'vendor','http://localhost:8089','/ops/providers');await page.getByRole('button',{name:title+' · approved',exact:true}).click();await page.getByLabel('Service description',{exact:true}).fill('Changed synthetic service facts must return to an unpublished draft for another review.');await page.getByRole('button',{name:'Save provider draft',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Draft saved'})).toBeVisible();expect((await page.request.get('http://localhost:8089/api/v1/renovation/providers/'+id+'?city=bj')).status()).toBe(404);
 }finally{if(id)await staff(c=>c.query("UPDATE providers SET status='draft',version=version+1 WHERE id=$1",[id]));}
});
