import '../support/env';
import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url));
const {Pool}=require('pg');const fixtures=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(()=>fixtures.end());
async function fixture(title:string){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const row=(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,created_by,published_at)
 SELECT unit_id,organization_id,owner_id,agent_id,$1,$2,description,transaction,segment,currency,'2450000.25',photos,'published','00000000-0000-4000-8000-000000000003',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug`,['browser-revision-'+crypto.randomUUID(),title])).rows[0];await c.query('COMMIT');return row;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
async function projected(id:string){const response=await fetch(process.env.SEARCH_URL+'/indexes/listings/documents/'+id,{headers:{Authorization:'Bearer '+process.env.SEARCH_KEY}});if(response.status===404)return null;if(!response.ok)throw Error('Search projection unavailable: '+response.status);return response.json();}
test('I05/I06 approved price changes publish atomically, rejected changes stay private and public history excludes notes',async({page},info)=>{
 test.setTimeout(180000);const title='Verified revision fixture '+info.project.name+' '+crypto.randomUUID();const property=await fixture(title),note='PRIVATE_REVISION_BROWSER_'+crypto.randomUUID();
 await login(page,'agent','http://localhost:8089','/ops/listings');const row=page.locator('tr[data-record-id="'+property.id+'"]');await row.getByRole('button',{name:'Propose changes',exact:true}).click();await page.getByRole('textbox',{name:'Price (CNY)',exact:true}).fill('2650000.75');await page.getByRole('textbox',{name:'Reason for the proposed changes',exact:true}).fill(note);const pending=page.waitForResponse(response=>response.url().endsWith('/ops/listings/'+property.id)&&response.request().method()==='PATCH');await page.getByRole('button',{name:'Save',exact:true}).click();const submitted=await pending;expect(submitted.status()).toBe(200);const revision=(await submitted.json()).data;await expect(page.getByRole('dialog')).toHaveCount(0);
 let publicRow=(await(await page.request.get('http://localhost:8088/api/v1/listings/'+property.slug)).json()).data;expect(publicRow.price).toBe('2450000.25');expect(publicRow.version).toBe(1);expect(JSON.stringify(publicRow)).not.toContain(note);await expect.poll(async()=>(await projected(property.id))?.price,{timeout:20000}).toBe('2450000.25');expect((await apiRequest(page,'/ops/revisions/'+revision.id+'/approve',{version:1,reason:'Agent must not approve this revision',verified:true})).status()).toBe(403);
 await login(page,'moderator','http://localhost:8089','/ops/reviews');const review=page.locator('#revision-'+revision.id);await review.getByRole('button',{name:'Approve revision',exact:true}).click();await page.getByRole('checkbox',{name:'I have verified these changes and the authority to list.',exact:true}).check();await page.getByRole('textbox',{name:'Revision decision reason',exact:true}).fill('Independent revised property facts verified');const approved=page.waitForResponse(response=>response.url().endsWith('/ops/revisions/'+revision.id+'/approve')&&response.request().method()==='POST');await page.getByRole('button',{name:'Save',exact:true}).click();const approval=await approved;expect(approval.status()).toBe(201);await expect(review).toHaveCount(0);const replay=await page.request.post(approval.url(),{headers:{Origin:'http://localhost:8089','idempotency-key':approval.request().headers()['idempotency-key']},data:approval.request().postDataJSON()});expect(replay.status()).toBe(201);
 publicRow=(await(await page.request.get('http://localhost:8088/api/v1/listings/'+property.slug)).json()).data;expect(publicRow.price).toBe('2650000.75');expect(publicRow.version).toBe(2);await expect.poll(async()=>(await projected(property.id))?.price,{timeout:20000}).toBe('2650000.75');const history=(await(await page.request.get('http://localhost:8088/api/v1/listings/'+property.slug+'/history')).json()).data;expect(history.prices).toHaveLength(1);expect(JSON.stringify(history)).not.toMatch(/PRIVATE_|actor_id|private_reason|review_reason/);
 await login(page,'buyer');await page.goto('/bj/buy/'+property.slug);await expect(page.locator('.public-history')).toContainText('2650000.75');await expect(page.locator('body')).not.toContainText(note);await page.screenshot({path:`evidence/approved-price-history-${info.project.name}.png`,fullPage:true});
 await login(page,'agent','http://localhost:8089','/ops/listings');const rejected=await apiRequest(page,'/ops/listings/'+property.id,{title,price:'2750000.75',version:2,reason:'Unverified proposed second asking price'},'PATCH');expect(rejected.status()).toBe(200);const rejectedId=(await rejected.json()).data.id;await login(page,'moderator','http://localhost:8089','/ops/reviews');const rejectedCard=page.locator('#revision-'+rejectedId);await rejectedCard.getByRole('button',{name:'Reject revision',exact:true}).click();await page.getByRole('textbox',{name:'Revision rejection reason',exact:true}).fill('The proposed second asking price lacks supporting evidence');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(rejectedCard).toHaveCount(0);const finalRow=(await(await page.request.get('http://localhost:8088/api/v1/listings/'+property.slug)).json()).data;expect(finalRow.price).toBe('2650000.75');expect(finalRow.version).toBe(2);const finalHistory=(await(await page.request.get('http://localhost:8088/api/v1/listings/'+property.slug+'/history')).json()).data;expect(finalHistory.prices).toHaveLength(1);
});
