import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('Q04 / V03 native consumer lost receipt retry, assigned vendor contact and retained customer timeline',async({page},info)=>{
 test.setTimeout(180000);await login(page,'buyer');const result=await page.request.get('/api/v1/renovation/providers?city=bj');expect(result.ok()).toBe(true);const providers=(await result.json()).data,p=providers.find((v:any)=>v.id==='10000000-0000-4000-8000-000000004000');expect(p).toBeTruthy();await page.goto('/bj/renovation/'+p.slug);await page.getByRole('button',{name:'Request a quote',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Tell us about your project',exact:true});const description='V03 '+crypto.randomUUID()+' — Please discuss repainting this synthetic test apartment.';await dialog.getByLabel('Project description',{exact:true}).fill(description);await dialog.getByLabel('Your name',{exact:true}).fill('Synthetic Customer');await dialog.getByLabel('Email address',{exact:true}).fill('quote-browser@example.test');await dialog.getByLabel('Phone number',{exact:true}).fill('+86 130 0000 0000');await dialog.getByLabel(/Estimated budget/).fill('4321.50');await dialog.getByRole('checkbox').check();let lost=false;await page.route('**/api/v1/quote-requests',async route=>{if(!lost){lost=true;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort();}else await route.continue();});await dialog.getByRole('button',{name:'Request a quote',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Project description',{exact:true})).toHaveValue(description);await dialog.getByRole('button',{name:'Request a quote',exact:true}).click();await expect(dialog.getByRole('heading',{name:'Quote request saved',exact:true})).toBeVisible();await expect(dialog).toContainText('No contract or payment');const link=dialog.getByRole('link',{name:'View request and timeline',exact:true}),href=await link.getAttribute('href');expect(href).toBeTruthy();const id=new URL(href!,'http://localhost').searchParams.get('quote')!;const connection=await fixtures.connect();let count;try{await connection.query('BEGIN');await connection.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");count=(await connection.query('SELECT count(*)::int n FROM quotes WHERE description=$1',[description])).rows[0].n;await connection.query('COMMIT');}finally{connection.release();}expect(count).toBe(1);await link.click();const selected=page.getByLabel('Selected quote request',{exact:true});await expect(selected).toContainText(description);await expect(selected).toContainText('CNY 4321.50');await expect(selected).toContainText('Nonbinding request submitted');await page.reload();await expect(selected).toContainText(description);
 await login(page,'vendor',(process.env.PUBLIC_OPS_URL||'http://localhost:8089'),'/ops/quotes?quote='+id);await expect(selected).toContainText(description);await selected.getByLabel('Next status',{exact:true}).selectOption('contacted');await selected.getByLabel('Update shared with customer',{exact:true}).fill('Contacted customer about this nonbinding project.');await selected.getByRole('button',{name:'Save request status',exact:true}).click();await expect(selected).toContainText('Contacted customer about this nonbinding project.');expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/v03-vendor-${info.project.name}.png`,scale:'css'});
 await login(page,'buyer',(process.env.PUBLIC_WEB_URL||'http://localhost:8088'),'/account/quotes?quote='+id);await expect(selected).toContainText('Contacted customer about this nonbinding project.');await expect(selected.getByRole('button',{name:'Save request status',exact:true})).toHaveCount(0);expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/v03-customer-${info.project.name}.png`,scale:'css'});
});
