import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});


test('M04 native live reconnect recovers missing messages in order; revoked assignment and expired session close existing rooms',async({page,browser},info)=>{
 test.setTimeout(180000);const agent=crypto.randomUUID(),slug='m04-browser-'+agent;let lead:string|undefined,thread:string|undefined;const other=await browser.newContext(),agentPage=await other.newPage();
 try{await staff(c=>c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'M04 browser agent',$3,'Synthetic live recovery fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]));
 await page.addInitScript(()=>{const Native=window.WebSocket;(globalThis as any).m04Sockets=[];window.WebSocket=class extends Native{constructor(url:string|URL,protocols?:string|string[]){super(url,protocols);(globalThis as any).m04Sockets.push(this);}};});
 await login(page,'buyer','http://localhost:8088','/account/messages');const response=await page.request.post('/api/v1/inquiries',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{resourceId:agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M04 customer',email:'m04-'+agent+'@example.test',phone:'123456789',message:'Test actual reconnect recovery.',consent:true}});expect(response.ok()).toBe(true);const inquiry=(await response.json()).data;lead=inquiry.id;thread=inquiry.conversationId;
 await login(agentPage,'agent','http://localhost:8089','/ops/messages?conversation='+thread);const version=(await (await agentPage.request.get('http://localhost:8089/api/v1/conversations/'+thread)).json()).data.version;
 const send=async(body:string,clientId=crypto.randomUUID())=>{const r=await agentPage.request.post('http://localhost:8089/api/v1/conversations/'+thread+'/messages',{headers:{Origin:'http://localhost:8089'},data:{version:0,conversationVersion:version,clientId,body}});expect(r.ok()).toBe(true);return(await r.json()).data;};
 for(let i=1;i<=3;i++)await send('M04 baseline '+i);await page.goto('/account/messages?conversation='+thread);await expect(page.locator('.message')).toHaveCount(3);await expect(page.getByLabel('Conversation connection')).toContainText('Live updates connected');
 // Block HTTP history after initial load: recovered bubbles must come from WebSocket frames.
 await page.route('**/api/v1/conversations/'+thread+'/messages*',route=>route.request().method()==='GET'?route.abort():route.continue());await page.context().setOffline(true);await page.evaluate(()=>{for(const socket of (globalThis as any).m04Sockets)socket.close();});await expect(page.getByLabel('Conversation connection')).toContainText('reconnecting');const missing=[];for(let i=4;i<=6;i++)missing.push(await send('M04 missing '+i));await expect(page.locator('.message')).toHaveCount(3);await page.context().setOffline(false);await expect(page.getByLabel('Conversation connection')).toContainText('Live updates connected');await expect(page.locator('.message')).toHaveCount(6);expect(await page.locator('.message').evaluateAll(nodes=>nodes.slice(-3).map(n=>n.getAttribute('data-message-id')))).toEqual(missing.map(m=>m.id));
 // Native socket send commits before receipt; replaying its client ID produces one row.
 const clientId=crypto.randomUUID();const receipt=await page.evaluate(({id,version,clientId})=>new Promise<any>((resolve,reject)=>{const socket=(globalThis as any).m04Sockets.filter((s:WebSocket)=>s.readyState===1).at(-1),timer=setTimeout(()=>reject(Error('Socket receipt timed out')),15000);const on=(event:MessageEvent)=>{const frame=JSON.parse(event.data);if(frame.type==='receipt'&&frame.message.body==='M04 socket send'){clearTimeout(timer);socket.removeEventListener('message',on);resolve(frame.message);}};socket.addEventListener('message',on);socket.send(JSON.stringify({type:'send',conversationId:id,message:{version:0,conversationVersion:version,clientId,body:'M04 socket send'}}));}),{id:thread!,version,clientId});expect(receipt.sequence).toBe('7');const replay=await page.request.post('/api/v1/conversations/'+thread+'/messages',{headers:{Origin:'http://localhost:8088'},data:{version:0,conversationVersion:version,clientId,body:'M04 socket send'}});expect(replay.ok()).toBe(true);expect((await replay.json()).data.id).toBe(receipt.id);await expect(page.locator('.message')).toHaveCount(7);await page.unroute('**/api/v1/conversations/'+thread+'/messages*');
 await expect.poll(async()=>(await (await page.request.get('/api/v1/conversations/'+thread+'/read-cursor')).json()).data.sequence).toBe('7');await page.getByLabel('Saved messages',{exact:true}).evaluate(el=>{el.scrollTop=0;el.dispatchEvent(new Event('scroll',{bubbles:true}));});await send('M04 incoming while reading older history');await expect(page.locator('.message')).toHaveCount(8);expect((await (await page.request.get('/api/v1/conversations/'+thread+'/read-cursor')).json()).data.sequence).toBe('7');await page.getByLabel('Saved messages',{exact:true}).focus();await page.getByLabel('Saved messages',{exact:true}).press('Control+End');await expect.poll(async()=>(await (await page.request.get('/api/v1/conversations/'+thread+'/read-cursor')).json()).data.sequence).toBe('8');
 expect((await new AxeBuilder({page}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/m04-live-${info.project.name}.png`,scale:'css'});
 // Source reassignment immediately removes the existing professional grant.
 await staff(c=>c.query('UPDATE leads SET agent_id=NULL,version=version+1 WHERE id=$1',[lead]));await expect(agentPage.getByLabel('Conversation connection')).toContainText('Conversation access ended');await expect(agentPage.getByRole('textbox',{name:'Reply to client',exact:true})).toBeDisabled();expect((await agentPage.request.get('http://localhost:8089/api/v1/conversations/'+thread+'/messages')).status()).toBe(404);
 // Expire this browser’s actual server session, without exposing cookie values.
 const cookies=await page.context().cookies(),session=cookies.find(c=>c.name==='haven_session')?.value;expect(session).toBeTruthy();await staff(c=>c.query("UPDATE sessions SET expires_at=now()-interval '1 second' WHERE id=$1",[session]));await expect(page.getByLabel('Conversation connection')).toContainText('Conversation access ended');await expect(page.getByRole('textbox',{name:'Your message',exact:true})).toBeDisabled();expect((await page.request.get('/api/v1/conversations/'+thread+'/messages')).status()).toBe(401);
 }finally{await page.context().setOffline(false);await other.close();await staff(async c=>{if(lead)await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=$1",[lead]);if(thread)await c.query("UPDATE conversations SET state='closed',version=version+1 WHERE id=$1",[thread]);await c.query('UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1',[agent]);});}
});
