import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {transaction,pool} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
test.afterAll(()=>pool.end());
test('R03 rental detail shows exact amounts and recorded utility terms; missing terms are explicit and leased property has no booking action',async({page},info)=>{
 const rows=await transaction(workerActor,async c=>{const rows=[];for(const missing of [false,true]){const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'R03 browser fixture',description,'rent','residential','CNY','4500.25','month',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug",['r03-browser-'+crypto.randomUUID()])).rows[0];if(!missing)await c.query("INSERT INTO rental_terms(listing_id,rental_mode,billing_period,deposit_amount,currency,minimum_months,utilities,move_in_date) VALUES($1,'entire','month','9000.50','CNY',12,ARRAY['Water included','Electricity billed separately'],'2026-11-01')",[row.id]);rows.push(row);}return rows;});
 try{await page.goto('/bj/rent/'+rows[0].slug);let section=page.locator('.rental-detail-terms');await expect(section.getByText('CNY 4,500.25 per month',{exact:true})).toBeVisible();await expect(section.getByText('CNY 9,000.50',{exact:true})).toBeVisible();await expect(section.getByText('Water included · Electricity billed separately',{exact:true})).toBeVisible();await expect(section.getByText('12 months',{exact:true})).toBeVisible();await expect(section.getByText('2026-11-01',{exact:true})).toBeVisible();await section.scrollIntoViewIfNeeded();const axe=await new AxeBuilder({page}).include('.rental-detail-terms').analyze();expect(axe.violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`evidence/r03-terms-${info.project.name}.png`,scale:'css'});await page.goto('/bj/rent/'+rows[1].slug);section=page.locator('.rental-detail-terms');await expect(section.getByRole('status')).toContainText('Rental terms are unavailable');await expect(section.getByText('Not provided',{exact:true})).toHaveCount(5);await expect(section).not.toContainText('CNY 0.00');await section.scrollIntoViewIfNeeded();await page.screenshot({path:`evidence/r03-missing-${info.project.name}.png`,scale:'css'});await transaction(workerActor,c=>c.query("UPDATE listings SET status='leased',version=version+1 WHERE id=$1",[rows[0].id]));await page.goto('/bj/rent/'+rows[0].slug);await expect(page.getByRole('button',{name:'Request a viewing',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'This page is unavailable.',exact:true})).toBeVisible();}finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[rows.map(row=>row.id)]));}
});
