import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),created:string[]=[];
async function staff(work:(client:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const result=await work(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
test.afterAll(async()=>{try{await staff(c=>c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=ANY($1::uuid[])",[created]));}finally{await fixtures.end();}});
test('D08 published detail gallery supports keyboard/swipe/Escape/focus, real approximate map and community navigation without covered content',async({page},info)=>{
 await page.goto('/bj/buy/home-1');const gallery=page.locator('#main > .detail-gallery, #main > .property-gallery .detail-gallery').first();await expect(gallery.locator('.gallery-count')).toContainText('1 / 2');await gallery.getByRole('button',{name:'Open property gallery',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Property gallery',exact:true});await expect(dialog).toBeVisible();await page.keyboard.press('ArrowRight');await expect(dialog.locator('.gallery-count')).toContainText('2 / 2');await page.keyboard.press('ArrowLeft');await expect(dialog.locator('.gallery-count')).toContainText('1 / 2');await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(gallery.getByRole('button',{name:'Open property gallery',exact:true})).toBeFocused();
 if(info.project.name==='mobile'){await gallery.scrollIntoViewIfNeeded();const box=(await gallery.boundingBox())!,session=await page.context().newCDPSession(page),y=Math.max(10,box.y+box.height/2);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width*.8,y}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+box.width*.2,y}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await session.detach();await expect(gallery.locator('.gallery-count')).toContainText('2 / 2');}else{await gallery.getByRole('button',{name:'Next photo',exact:true}).click();await expect(gallery.locator('.gallery-count')).toContainText('2 / 2');}
 await expect(page.locator('.agent-mini')).toContainText('Local property agent · Credentials unverified');await expect(page.getByRole('button',{name:'Request a viewing',exact:true})).toBeEnabled();await page.locator('.detail-map').scrollIntoViewIfNeeded();await expect(page.locator('.detail-map .map-canvas')).toHaveAttribute('data-map-ready','true');await expect(page.locator('.map-attribution')).toContainText('rounded to 3 decimal places');await expect(page.locator('.detail-map .location-card')).not.toContainText('undefined');
 const axe=await new AxeBuilder({page}).include('#main').analyze();expect(axe.violations.filter(x=>['serious','critical'].includes(x.impact||''))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 if(info.project.name==='mobile'){await page.getByRole('button',{name:'Request a viewing',exact:true}).scrollIntoViewIfNeeded();const action=await page.getByRole('button',{name:'Request a viewing',exact:true}).boundingBox(),nav=await page.getByRole('navigation',{name:'Mobile navigation',exact:true}).boundingBox();expect(action!.y+action!.height).toBeLessThanOrEqual(nav!.y);}
 await page.screenshot({path:`evidence/d08-detail-${info.project.name}.png`,scale:'css'});await page.locator('.facts-table').getByRole('link',{name:'Willow Park',exact:true}).click();await expect(page).toHaveURL(/\/bj\/communities\//);await expect(page.locator('#main h1')).toHaveText('Willow Park');await page.goBack();await expect(page.locator('#main h1')).toHaveText('Light-filled home beside the gardens');
});
test('D08 withdrawn property is unavailable with no booking; missing photos/public coordinates have useful safe fallback',async({page},info)=>{
 const resource=await staff(async c=>(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,published_at) SELECT unit_id,organization_id,owner_id,NULL,$1,'D08 unavailable '||$2::text,'Synthetic unavailable fixture','sale','residential','CNY','1111111.25','{}','published',NULL FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug`,['detail-browser-'+crypto.randomUUID(),info.project.name])).rows[0]);created.push(resource.id);
 await page.route('**/api/v1/listings/'+resource.slug+'?city=bj',async route=>{const response=await route.fetch(),body=await response.json();body.data.latitude=null;body.data.longitude=null;await route.fulfill({response,json:body});});
 await page.goto('/bj/buy/'+resource.slug+'?media=photo');await expect(page.locator('.photo-fallback')).toContainText('Photo unavailable');await expect(page.getByRole('button',{name:'Open property gallery',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Request a viewing',exact:true})).toBeDisabled();await expect(page.getByText('No eligible viewing agent is currently assigned.',{exact:true})).toBeVisible();await expect(page.getByText(/Publication date unavailable/)).toBeVisible();await expect(page.getByText('Approximate map location is not provided. Ask the property team about this community.',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Open map',exact:true})).toHaveCount(0);
 await staff(c=>c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=$1",[resource.id]));await page.reload();await expect(page.getByRole('heading',{name:'This page is unavailable.',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Request a viewing',exact:true})).toHaveCount(0);expect((await page.request.get('/api/v1/listings/'+resource.id)).status()).toBe(404);await page.screenshot({path:`evidence/d08-unavailable-${info.project.name}.png`,scale:'css'});
});
