import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {login} from '../support/browser';
test.use({actionTimeout:15000});
const origin='http://localhost:8088';
async function own(page:any){return (await (await page.request.get('/api/v1/me/saved-searches')).json()).data;}
async function remove(page:any,id:string){const row=(await own(page)).find((row:any)=>row.id===id);if(row){const response=await page.request.delete('/api/v1/me/saved-searches/'+id,{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{version:row.version}});expect(response.ok()).toBe(true);}}
test('A04 complex rental filters save/refresh/restore, edit through results, pause/resume and delete; another user cannot edit',async({page},info)=>{
 const name='Rental search '+info.project.name+' '+crypto.randomUUID(),params=new URLSearchParams({currency:'CNY',rentPeriod:'month',minPrice:'2000.00',maxPrice:'15000.00',beds:'1,2',minArea:'60',maxArea:'140',orientation:'South,East',furnishing:'Furnished',elevator:'true',sort:'price_asc'});let id='';
 try{
  await login(page,'buyer');await page.goto('/bj/rent?'+params);await page.getByRole('button',{name:'Save search',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Search name',{exact:true}).fill(' ');await dialog.getByRole('button',{name:'Save search',exact:true}).click();await expect(dialog.getByLabel('Search name',{exact:true})).toHaveAttribute('aria-invalid','true');await dialog.getByLabel('Search name',{exact:true}).fill(name);await dialog.getByLabel('Alert frequency preference',{exact:true}).selectOption('daily');await dialog.getByRole('button',{name:'Save search',exact:true}).click();await expect(page.locator('.toast')).toContainText('Search saved');const saved=(await own(page)).find((row:any)=>row.name===name);id=saved.id;expect(saved.filters).toMatchObject({city:'bj',transaction:'rent',segment:'residential',currency:'CNY',rentPeriod:'month',beds:'1,2',orientation:'East,South',minPrice:'2000.00',maxPrice:'15000.00',furnishing:'Furnished',elevator:'true',sort:'price_asc'});
  await page.goto('/account/searches');await page.reload();let row=page.locator('[data-saved-search-id="'+id+'"]');await expect(row.getByRole('heading',{name,exact:true})).toBeVisible();await row.getByRole('link',{name:'View results',exact:true}).click();await expect(page).toHaveURL(origin+saved.restoreUrl);for(const [key,value] of Object.entries(saved.filters))if(key!=='city')expect(new URL(page.url()).searchParams.get(key)).toBe(value);
  await page.goto('/account/searches');row=page.locator('[data-saved-search-id="'+id+'"]');await row.getByRole('link',{name:'Edit criteria in results',exact:true}).click();await page.getByRole('button',{name:/^All filters/}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Maximum price (CNY)',{exact:true}).fill('12000.00');await dialog.getByRole('button',{name:'Apply filters',exact:true}).click();expect(new URL(page.url()).searchParams.get('editSearch')).toBe(id);await page.getByRole('button',{name:'Save search',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Search name',{exact:true})).toHaveValue(name);await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.locator('.toast')).toContainText('Saved search updated');expect((await own(page)).find((row:any)=>row.id===id).filters.maxPrice).toBe('12000.00');
  await page.goto('/account/searches');row=page.locator('[data-saved-search-id="'+id+'"]');await row.getByRole('button',{name:'Edit preferences',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Search name',{exact:true}).fill(name+' edited');await dialog.getByLabel('Alert frequency preference',{exact:true}).selectOption('weekly');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(row.getByRole('heading',{name:name+' edited',exact:true})).toBeVisible();await row.getByRole('button',{name:'Pause search',exact:true}).click();await expect(row.getByRole('button',{name:'Resume search',exact:true})).toBeVisible();await row.getByRole('button',{name:'Check matching homes',exact:true}).click();await expect(row.getByRole('status')).toContainText('not currently eligible');await row.getByRole('button',{name:'Resume search',exact:true}).click();await expect(row.getByRole('button',{name:'Pause search',exact:true})).toBeVisible();await row.getByRole('button',{name:'Check matching homes',exact:true}).click();await expect(row.getByRole('status')).toContainText('current matching homes');
  const axe=await new AxeBuilder({page}).include('main').analyze();expect(axe.violations.filter(issue=>issue.impact==='serious'||issue.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);const selected=page.getByRole('navigation',{name:'Account navigation'}).getByRole('link',{name:'Saved searches',exact:true});const box=await selected.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/a04-searches-${info.project.name}.png`,scale:'css'});
  await login(page,'owner');const denied=await page.request.patch('/api/v1/me/saved-searches/'+id,{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{name:'Unauthorized edit',filters:saved.filters,cadence:'weekly',paused:false,version:1}});expect(denied.status()).toBe(404);expect((await own(page)).some((row:any)=>row.id===id)).toBe(false);
  await login(page,'buyer',origin,'/account/searches');row=page.locator('[data-saved-search-id="'+id+'"]');await row.getByRole('button',{name:'Delete search',exact:true}).click();await expect(row).toHaveCount(0);await page.reload();expect((await own(page)).some((row:any)=>row.id===id)).toBe(false);
 }finally{await login(page,'buyer');if(id)await remove(page,id);}
});
test('A04 stale preference edit shows conflict/reload and invalid or mixed-currency criteria are rejected',async({page})=>{
 await login(page,'buyer');const name='Stale search '+crypto.randomUUID(),input={name,filters:{city:'bj',currency:'CNY',transaction:'sale'},cadence:'weekly',version:0};let id='';
 try{
  const created=await page.request.post('/api/v1/me/saved-searches',{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:input});expect(created.ok()).toBe(true);id=(await created.json()).data.id;await page.goto('/account/searches');await page.locator('[data-saved-search-id="'+id+'"]').getByRole('button',{name:'Edit preferences',exact:true}).click();let dialog=page.getByRole('dialog');const changed=await page.request.patch('/api/v1/me/saved-searches/'+id,{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{name:name+' changed',filters:input.filters,cadence:'daily',paused:false,version:1}});expect(changed.ok()).toBe(true);await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Saved search changed');await expect(dialog.getByRole('button',{name:'Save changes',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Reload saved search',exact:true}).click();await expect(page).toHaveURL(new RegExp('editSearch='+id));await page.getByRole('button',{name:'Save search',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Search name',{exact:true})).toHaveValue(name+' changed');await expect(dialog.getByLabel('Alert frequency preference',{exact:true})).toHaveValue('daily');await dialog.getByRole('button',{name:'Close dialog',exact:true}).click();
  const invalid=await page.request.post('/api/v1/me/saved-searches',{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{...input,filters:{...input.filters,minPrice:'5000',maxPrice:'1000'}}});expect(invalid.status()).toBe(400);const currency=await page.request.post('/api/v1/me/saved-searches',{headers:{Origin:origin,'Idempotency-Key':crypto.randomUUID()},data:{...input,filters:{...input.filters,currency:'USD'}}});expect(currency.status()).toBe(400);expect((await currency.json()).error.code).toBe('CURRENCY_MISMATCH');
 }finally{if(id)await remove(page,id);}
});
