import '../support/env';
import {test,expect} from '@playwright/test';
import {login} from '../support/browser';
import {createRequire} from 'node:module';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg');
const fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});
test.afterAll(()=>fixtures.end());
import fs from 'node:fs';
test.skip(process.env.HAVEN_HTTPS_STAGING!=='true','Requires the owned real HTTPS staging stack');
const web=process.env.PUBLIC_WEB_URL!,ops=process.env.PUBLIC_OPS_URL!;
const task=process.env.HAVEN_VERIFICATION_TASK==='Q10'?'Q10':'Q08';
test(task+' real HTTPS inquiry persists with a native receipt and secure guest cookies',async({page},info)=>{
 expect(web.startsWith('https://')).toBe(true);await page.goto(web+'/bj/buy/home-1');await expect(page.locator('#main')).toBeVisible();const contact=page.getByRole('button',{name:'Send an inquiry',exact:true});await contact.click();const dialog=page.getByRole('dialog'),email='q08-'+crypto.randomUUID()+'@example.test';for(const [name,value] of [['Your name','Q08 HTTPS '+info.project.name],['Email address',email],['Phone number','+86 138 0000 0000'],['How can we help?','Authorized synthetic HTTPS staging inquiry.']])await dialog.getByLabel(name,{exact:true}).fill(value);await dialog.getByRole('checkbox').check();const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/guest-inquiries')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Send inquiry',exact:true}).click();const actual=await response;expect(actual.status()).toBe(201);const id=(await actual.json()).data.id;await expect(dialog.getByRole('heading',{name:'Your inquiry is saved.',exact:true})).toBeVisible();const row=await fixtures.query('SELECT email,user_id FROM leads WHERE id=$1',[id]);expect(row.rows).toEqual([{email,user_id:null}]);const cookies=await page.context().cookies();expect(cookies.find(c=>c.name==='haven_inquiry')).toMatchObject({secure:true,httpOnly:true,sameSite:'Lax'});await page.screenshot({path:'evidence/'+task.toLowerCase()+'-https-inquiry-'+info.project.name+'.png',scale:'css'});fs.writeFileSync('evidence/'+task.toLowerCase()+'-https-inquiry-'+info.project.name+'.json',JSON.stringify({label:'P',positiveMocked:false,protocol:'HTTPS',certificateTrust:'Browser pins the exact generated leaf SPKI; separate curl verifies private CA and hostname',receipt:id,nativeLeadMatched:true},null,2)+'\n');
});
test(task+' production staff MFA and scanned private document remain scoped through HTTPS',async({page,browser},info)=>{
 test.setTimeout(180000);await login(page,'manager',ops,'/ops/management');const own=(await(await page.request.get(ops+'/api/v1/me')).json()).data;expect(own.roles).toContain('property_manager');expect((await page.context().cookies()).find(c=>c.name==='haven_session')?.secure).toBe(true);const pdf=Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF');const intent=await page.request.post(ops+'/api/v1/media/upload-intents',{headers:{Origin:ops},data:{mime:'application/pdf',size:pdf.length,rights:'Authorized synthetic private PDF for staging recovery verification.',visibility:'private',purpose:'document'}});expect(intent.ok()).toBe(true);const asset=(await intent.json()).data;const uploaded=await page.request.put(ops+asset.uploadUrl,{headers:{Origin:ops,'Content-Type':'application/pdf'},data:pdf});expect(uploaded.ok()).toBe(true);const status=(await(await page.request.get(ops+'/api/v1/media/'+asset.id+'/status')).json()).data;expect(status.status).toBe('approved');expect(status.scan_at).toBeTruthy();const link=await page.request.post(ops+'/api/v1/documents/'+asset.id+'/download-link',{headers:{Origin:ops}});expect(link.ok()).toBe(true);const ticket=(await link.json()).data.url,document=await page.request.get(ops+ticket);expect(document.ok()).toBe(true);expect(await document.body()).toEqual(pdf);const consumer=await browser.newContext({...info.project.use,baseURL:web});try{const buyer=await consumer.newPage();await login(buyer,'buyer',web,'/account');expect((await buyer.request.get(web+ticket)).status()).toBe(403);}finally{await consumer.close();}await page.screenshot({path:'evidence/'+task.toLowerCase()+'-https-staff-'+info.project.name+'.png',scale:'css'});fs.writeFileSync('evidence/'+task.toLowerCase()+'-https-staff-'+info.project.name+'.json',JSON.stringify({label:'P',positiveMocked:false,protocol:'HTTPS',staffMfa:'Actual OTP-required identity login and production actor admission',asset:asset.id,scanned:true,nativeBytesMatched:true,foreignTicketStatus:403},null,2)+'\n');
});
