import fs from 'node:fs';
import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const WEB=process.env.PUBLIC_WEB_URL||'http://localhost:8088',OPS=process.env.PUBLIC_OPS_URL||'http://localhost:8089';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});test.afterAll(()=>fixtures.end());
test('Q05 / P14 native owner and tenant period statements export actual reconciled ledger sources',async({page},info)=>{
 test.setTimeout(240000);const c=await fixtures.connect();let unit:string,listing:string,slug:string,email:string;try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true),set_config('app.admin','true',true)");unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0].id;slug='p14-native-'+crypto.randomUUID();listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,'00000000-0000-4000-8000-000000000002',agent_id,$2,'P14 synthetic available rental',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit,slug])).rows[0].id;await c.query("INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,'entire','month','CNY')",[listing]);await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,'00000000-0000-4000-8000-000000000002','recorded_listing',$2)",[unit,listing]);email=(await c.query("SELECT email FROM profiles WHERE id='00000000-0000-4000-8000-000000000005'")).rows[0].email;await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
 await login(page,'owner',WEB,'/account/management');const own=(await (await page.request.get(WEB+'/api/v1/me/management-grant-units/'+unit)).json()).data,g=(await (await page.request.post(WEB+'/api/v1/me/management-grants',{headers:{Origin:WEB,'Idempotency-Key':crypto.randomUUID()},data:{version:0,unitId:unit,unitVersion:own.version,ownerGrantVersion:own.ownerGrantVersion,organizationId:'10000000-0000-4000-8000-000000000002',expiresAt:'2036-12-31T00:00:00.000Z',consent:true}})).json()).data;expect(g.id).toBeTruthy();await login(page,'manager',OPS,'/ops/management');const invitation=(await (await page.request.post(OPS+'/api/v1/ops/tenant-invitations',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,grantId:g.id,grantVersion:g.version,name:'P14 verified native tenant',email}})).json()).data;expect(invitation.id).toBeTruthy();await login(page,'tenant',WEB,'/tenant/profile');const acceptance=await page.request.patch(WEB+'/api/v1/tenant-invitations/'+invitation.id,{headers:{Origin:WEB,'Idempotency-Key':crypto.randomUUID()},data:{version:1,action:'accept',consent:true,reason:'Verified native tenant accepts this property account link.'}});expect(acceptance.ok()).toBe(true);const tenantId=(await acceptance.json()).data.tenantId;
 await login(page,'manager',OPS,'/ops/management');const options=(await (await page.request.get(OPS+'/api/v1/ops/lease-draft-options/'+unit)).json()).data,create=await page.request.post(OPS+'/api/v1/ops/leases',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,unitId:unit,tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===tenantId).version,startDate:'2026-01-01',endDate:'2028-12-31',rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]}});expect(create.ok()).toBe(true);const lease=(await create.json()).data;const headers={Origin:OPS,'Idempotency-Key':crypto.randomUUID()},activation=await page.request.post(OPS+'/api/v1/ops/leases/'+lease.id+'/activate',{headers,data:{version:lease.version,unitVersion:lease.unitVersion,grantVersion:lease.grantVersion,tenantVersion:lease.tenantVersion,confirm:true}});expect(activation.ok()).toBe(true);
 const charge=(await fixtures.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,'10000000-0000-4000-8000-000000000002','2026-10-01','2026-10-05','200.20','CNY') RETURNING id,version",[lease.id])).rows[0];
 const source=(await (await page.request.get(OPS+'/api/v1/ops/payment-evidence-options/'+lease.id)).json()).data,sentinel='P14 PRIVATE FINANCE SOURCE '+crypto.randomUUID(),draft=await page.request.post(OPS+'/api/v1/ops/payment-records',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{...source,version:0,amount:'250.25',source:'bank_statement',reference:sentinel}});expect(draft.ok()).toBe(true);const payment=(await draft.json()).data,posting=await page.request.post(OPS+'/api/v1/ops/payment-records/'+payment.id+'/post',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:payment.version,leaseVersion:payment.leaseVersion,unitVersion:payment.unitVersion,grantVersion:payment.grantVersion,confirm:true}});expect(posting.ok()).toBe(true);const posted=(await posting.json()).data;
 const ledger=(await (await page.request.get(OPS+'/api/v1/ops/leases/'+lease.id+'/allocation-ledger')).json()).data,allocation=await page.request.post(OPS+'/api/v1/ops/allocations',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,leaseId:lease.id,leaseVersion:ledger.leaseVersion,unitVersion:ledger.unitVersion,grantVersion:ledger.grantVersion,paymentId:posted.id,paymentVersion:posted.version,chargeId:charge.id,chargeVersion:charge.version,amount:'50.05',currency:'CNY',confirm:true}});expect(allocation.ok()).toBe(true);
 const liability=(await (await page.request.get(OPS+'/api/v1/ops/leases/'+lease.id+'/deposit-ledger')).json()).data,deposited=await page.request.post(OPS+'/api/v1/ops/deposits',{headers:{Origin:OPS,'Idempotency-Key':crypto.randomUUID()},data:{version:0,leaseId:lease.id,leaseVersion:liability.leaseVersion,unitVersion:liability.unitVersion,grantVersion:liability.grantVersion,liabilityVersion:liability.liabilityVersion,kind:'received',direction:'increase',amount:'100.10',currency:'CNY',reason:sentinel,confirm:true}});expect(deposited.ok()).toBe(true);
 await page.goto(OPS+'/ops/management?tab=leases');const leaseRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'Lease history '+lease.id,exact:true})});await leaseRow.getByRole('button',{name:'Statement',exact:true}).click();const managerDialog=page.getByRole('dialog',{name:'Lease statement',exact:true});await expect(managerDialog).toContainText('professional scope');await expect(managerDialog.getByRole('row',{name:'Outstanding balance 0.00 150.15 150.15',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await managerDialog.getByRole('button',{name:'Close dialog',exact:true}).click();
 await login(page,'owner',WEB,'/account/statements?lease='+lease.id);const report=page.getByRole('region',{name:'Recorded lease statement',exact:true});await expect(report.getByRole('heading',{name:/CNY/})).toBeVisible();const balance=report.getByRole('region',{name:'Statement balances',exact:true});await expect(balance.getByRole('row',{name:'Outstanding balance 0.00 150.15 150.15',exact:true})).toBeVisible();await expect(balance.getByRole('row',{name:'Deposit liability 0.00 100.10 100.10',exact:true})).toBeVisible();await expect(report).not.toContainText(sentinel);
 const today=new Date().toISOString().slice(0,10);await report.getByLabel('Statement period from',{exact:true}).fill(today);await report.getByLabel('Statement period to',{exact:true}).fill(today);await report.getByRole('button',{name:'Load statement period',exact:true}).click();await expect(report).toContainText(today+' – '+today);await page.reload();await expect(page.getByLabel('Statement period from',{exact:true})).toHaveValue(today);await expect(balance.getByRole('row',{name:'Outstanding balance 0.00 150.15 150.15',exact:true})).toBeVisible();
 const [download]=await Promise.all([page.waitForEvent('download',{timeout:20000}),report.getByRole('button',{name:'Download statement CSV',exact:true}).click()]),csv=fs.readFileSync((await download.path())!,'utf8');expect(csv).toContain('"Outstanding balance","0.00","150.15","150.15"');expect(csv).toContain('"Deposit liability","0.00","100.10","100.10"');expect(csv).toContain(charge.id);expect(csv).toContain(posted.id);expect(csv).not.toContain(sentinel);
 const [print]=await Promise.all([page.waitForEvent('popup'),report.getByRole('link',{name:'Open full print statement',exact:true}).click()]);await expect(print.getByRole('heading',{name:'Recorded lease statement',exact:true})).toBeVisible();await expect(print.getByRole('heading',{name:'All 4 period entries',exact:true})).toBeVisible();await expect(print.locator('body')).not.toContainText(sentinel);expect((await page.request.get(print.url())).headers()['content-security-policy']).toContain("default-src 'none'");await print.close();expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/p14-owner-statement-${info.project.name}.png`,scale:'css'});
 await login(page,'tenant',WEB,'/tenant/leases?lease='+lease.id);await page.getByText('Period statement and exports',{exact:true}).click();await expect(page.getByRole('region',{name:'Statement balances',exact:true}).getByRole('row',{name:'Outstanding balance 0.00 150.15 150.15',exact:true})).toBeVisible();const [tenantDownload]=await Promise.all([page.waitForEvent('download',{timeout:20000}),page.getByRole('button',{name:'Download statement CSV',exact:true}).click()]);expect(fs.readFileSync((await tenantDownload.path())!,'utf8')).not.toContain(sentinel);const tenantResponse=await page.request.get(WEB+'/api/v1/leases/'+lease.id+'/statement');expect(tenantResponse.ok()).toBe(true);expect(await tenantResponse.text()).not.toContain(sentinel);expect(await tenantResponse.text()).not.toContain('actor_id');expect(await tenantResponse.text()).not.toContain('organization_id');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/p14-tenant-statement-${info.project.name}.png`,scale:'css'});
 await login(page,'owner',WEB,'/account/statements?lease='+lease.id);await expect(page.getByRole('button',{name:'Download statement CSV',exact:true})).toBeVisible();const revoke=await page.request.patch(WEB+'/api/v1/me/management-grants/'+g.id,{headers:{Origin:WEB,'Idempotency-Key':crypto.randomUUID()},data:{version:g.version,action:'revoke',reason:'P14 native owner revokes statement authority.'}});expect(revoke.ok()).toBe(true);await page.getByRole('button',{name:'Download statement CSV',exact:true}).click();await expect(report.getByRole('alert')).toContainText('Currently authorized');expect((await page.request.get(WEB+'/api/v1/leases/'+lease.id+'/statement/print')).status()).toBe(404);
 await login(page,'buyer',WEB,'/account');for(const suffix of ['statement','statement.csv','statement/print'])expect((await page.request.get(WEB+'/api/v1/leases/'+lease.id+'/'+suffix)).status()).toBe(404);
});
