import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {login} from '../support/browser';
const WEB=process.env.PUBLIC_WEB_URL||'http://localhost:8088',OPS=process.env.PUBLIC_OPS_URL||'http://localhost:8089';
test('S02 native assigned support escalation resolution private note and reporter reopening',async({page},info)=>{
 test.setTimeout(180000);const title='S02 native request '+crypto.randomUUID(),sentinel='PRIVATE-SUPPORT-'+crypto.randomUUID();
 await login(page,'buyer',WEB,'/bj/support');await page.getByRole('button',{name:'New support request',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Support request',exact:true});await dialog.getByLabel('Support subject',{exact:true}).fill(title);await dialog.getByLabel('Support description',{exact:true}).fill('Please explain the recorded synthetic support workflow.');await dialog.getByLabel('Confirm support case sharing',{exact:true}).check();await dialog.getByRole('button',{name:'Send request',exact:true}).click();dialog=page.getByRole('dialog',{name:'Support case',exact:true});await expect(dialog).toContainText('version 1');const id=new URL(page.url()).searchParams.get('case')!;expect(id).toBeTruthy();
 await login(page,'support',OPS,'/ops/support?case='+id);dialog=page.getByRole('dialog',{name:'Support case',exact:true});await dialog.getByLabel('Support assignee',{exact:true}).selectOption('00000000-0000-4000-8000-000000000009');await dialog.getByLabel('Public support reply',{exact:true}).fill('We have assigned the case for review.');await dialog.getByRole('button',{name:'Triage case',exact:true}).click();await expect(dialog).toContainText('version 2');
 await dialog.getByLabel('Support case action',{exact:true}).selectOption('note');await dialog.getByLabel('Private support note',{exact:true}).fill(sentinel);await dialog.getByRole('button',{name:'Private internal note',exact:true}).click();await expect(dialog).toContainText('version 3');await expect(dialog).toContainText(sentinel);
 await dialog.getByLabel('Support case action',{exact:true}).selectOption('escalate');await dialog.getByLabel('Public case message',{exact:true}).fill('The assigned team has escalated the review.');await dialog.getByRole('button',{name:'Escalate case',exact:true}).click();await expect(dialog).toContainText('version 4');await expect(dialog.getByLabel('Support case action',{exact:true})).toHaveValue('comment');
 await dialog.getByLabel('Support case action',{exact:true}).selectOption('resolve');await dialog.getByLabel('Public case message',{exact:true}).fill('The support review is complete and the issue is resolved.');await dialog.getByRole('button',{name:'Resolve case',exact:true}).click();await expect(dialog).toContainText('version 5');await expect(dialog.getByLabel('Support case action',{exact:true})).toHaveCount(0);
 expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/s02-resolution-${info.project.name}.png`,scale:'css'});
 await dialog.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByLabel('Support status filter',{exact:true}).selectOption('resolved');await page.getByLabel('Support category filter',{exact:true}).selectOption('General');await page.getByLabel('Support assignee filter',{exact:true}).selectOption('00000000-0000-4000-8000-000000000009');await page.reload();await expect(page.getByLabel('Support status filter',{exact:true})).toHaveValue('resolved');await expect(page.getByLabel('Support assignee filter',{exact:true})).toHaveValue('00000000-0000-4000-8000-000000000009');await expect(page.getByRole('button',{name:'View support case '+id,exact:true})).toBeVisible();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download matching case metadata',exact:true}).click();const file=await downloaded;expect(file.suggestedFilename()).toBe('support-case-metadata.csv');const stream=await file.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));const csv=Buffer.concat(chunks).toString('utf8');expect(csv).toContain(id);expect(csv).not.toContain(sentinel);expect(csv).not.toContain(title);
 await login(page,'buyer',WEB,'/bj/support?case='+id);dialog=page.getByRole('dialog',{name:'Support case',exact:true});await expect(dialog).toContainText('The support review is complete and the issue is resolved.');await expect(dialog).not.toContainText(sentinel);let record=(await (await page.request.get(WEB+'/api/v1/support-cases/'+id)).json()).data;expect(record.internalNotes).toBeUndefined();expect(JSON.stringify(record)).not.toContain(sentinel);expect(record.activity).toHaveLength(5);expect(record.activity[2]).toMatchObject({action:'status_updated',message:null});expect(record.canReopen).toBe(true);await dialog.getByLabel('Public case message',{exact:true}).fill('The reporter needs one more review of the recorded issue.');let lost=false;await page.route('**/api/v1/support-cases/'+id,async route=>{if(route.request().method()==='PATCH'&&!lost){lost=true;const r=await route.fetch();expect(r.ok(),await r.text()).toBe(true);await route.abort();}else await route.continue();});await dialog.getByRole('button',{name:'Reopen resolved case',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Public case message',{exact:true})).toHaveValue('The reporter needs one more review of the recorded issue.');await dialog.getByRole('button',{name:'Reopen resolved case',exact:true}).click();await expect(dialog).toContainText('version 6');await page.unroute('**/api/v1/support-cases/'+id);await page.reload();record=(await (await page.request.get(WEB+'/api/v1/support-cases/'+id)).json()).data;expect(record.status).toBe('open');expect(record.assigned).toBe(false);expect(record.activity).toHaveLength(6);await dialog.getByLabel('Public case message',{exact:true}).fill('Additional public information from the original reporter.');await dialog.getByRole('button',{name:'Public comment',exact:true}).click();await expect(dialog).toContainText('version 7');expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);await page.screenshot({path:`evidence/s02-reopened-${info.project.name}.png`,scale:'css'});
 await login(page,'owner',WEB,'/account');expect((await page.request.get(WEB+'/api/v1/support-cases/'+id)).status()).toBe(404);expect((await page.request.get(WEB+'/api/v1/ops/support-cases/export')).status()).toBe(403);
});
