import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL});test.afterAll(()=>fixtures.end());
test('P02 native manager invitation and verified recipient acceptance recover lost receipts and isolate tenant profile',async({page,browser},info)=>{
 test.setTimeout(180000);const c=await fixtures.connect();let email:string;try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true),set_config('app.admin','true',true)");email=(await c.query("SELECT email FROM profiles WHERE id='00000000-0000-4000-8000-000000000005'")).rows[0].email;await c.query('COMMIT');}finally{c.release();}
 await login(page,'manager','http://localhost:8089','/ops/management');await page.getByRole('button',{name:'Tenants',exact:true}).click();const granted=await page.request.get('http://localhost:8089/api/v1/ops/managed-properties'),g=(await granted.json()).data.find((x:any)=>x.unit_id==='10000000-0000-4000-8000-000000001060');expect(g).toBeTruthy();await page.getByLabel('Granted property',{exact:true}).selectOption(g.id);const name='P02 browser tenant '+info.project.name+' '+crypto.randomUUID().slice(0,8);await page.getByLabel('Tenant name',{exact:true}).fill(name);await page.getByLabel('Tenant account email',{exact:true}).fill(email);let lost=false,id='';await page.route('**/api/v1/ops/tenant-invitations',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;const r=await route.fetch();expect(r.ok()).toBe(true);id=(await r.json()).data.id;await route.abort();}else await route.continue();});await page.getByRole('button',{name:'Save tenant invitation',exact:true}).click();await expect(page.locator('.tenant-links').getByRole('alert')).toBeVisible();await expect(page.getByLabel('Tenant account email',{exact:true})).toHaveValue(email);await page.getByRole('button',{name:'Save tenant invitation',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Tenant account invitation saved'})).toBeVisible();await expect(page.locator('[data-tenant-invitation="'+id+'"]')).toContainText(name);
 const ctx=await browser.newContext({...info.project.use,baseURL:'http://localhost:8088'}),tenant=await ctx.newPage();try{await login(tenant,'tenant','http://localhost:8088','/tenant/profile');const row=tenant.locator('[data-tenant-invitation="'+id+'"]');await expect(row).toContainText(name);await row.getByRole('button',{name:'Accept account link',exact:true}).click();const dialog=tenant.getByRole('dialog');await dialog.getByLabel('Decision reason',{exact:true}).fill('Verified tenant accepts this management account link.');await dialog.getByRole('checkbox').check();let lostAcceptance=false;await tenant.route('**/api/v1/tenant-invitations/'+id,async route=>{if(!lostAcceptance){lostAcceptance=true;const r=await route.fetch();expect(r.ok()).toBe(true);await route.abort();}else await route.continue();});await dialog.getByRole('button',{name:'Confirm decision',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByRole('checkbox')).toBeChecked();await dialog.getByRole('button',{name:'Confirm decision',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(row).toContainText('accepted');const own=await tenant.request.get('/api/v1/me/tenant-profiles'),profiles=(await own.json()).data;expect(profiles.length).toBeGreaterThan(0);const profile=profiles[0];expect((await tenant.request.get('/api/v1/me/tenant-profiles/'+profile.id)).status()).toBe(200);await row.getByText('Invitation history',{exact:true}).click();await expect(row).toContainText('accepted');expect((await new AxeBuilder({page:tenant}).include('main#main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await tenant.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await tenant.screenshot({path:`evidence/p02-tenant-${info.project.name}.png`,scale:'css'});await page.getByRole('button',{name:'Refresh tenant links',exact:true}).click();await expect(page.locator('[data-tenant-invitation="'+id+'"]')).toContainText('accepted');expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/p02-manager-${info.project.name}.png`,scale:'css'});await login(tenant,'buyer','http://localhost:8088','/tenant/profile');expect((await tenant.request.get('/api/v1/me/tenant-profiles/'+profile.id)).status()).toBe(404);await expect(tenant.locator('[data-tenant-invitation="'+id+'"]')).toHaveCount(0);}finally{await ctx.close();}
});
