import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('L05 confirmed calendar reschedule preserves the original on conflict and retries a lost receipt; assigned actions cancel, complete and record no-show',async({page},info)=>{
 test.setTimeout(240000);const id=crypto.randomUUID(),agent=crypto.randomUUID(),slug='l05-browser-'+id,title='L05 calendar '+id.slice(0,8),date=new Date(Date.now()+86400000).toISOString().slice(0,10),query='?from='+date+'&to='+date;const past:any[]=[];
 try{await staff(async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'L05 browser agent',$3,'Explicit synthetic calendar fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,$5,'Synthetic calendar acceptance fixture','sale','residential','CNY','2100000.25','published')",[id,org,agent,slug,title]);for(const n of [3,4])past.push((await c.query("INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at,status,property_zone) VALUES($1,'00000000-0000-4000-8000-000000000001',$2,now()-make_interval(days=>$3)-interval '2 hours',now()-make_interval(days=>$3)-interval '1 hour','confirmed','Asia/Shanghai') RETURNING *",[id,agent,n])).rows[0]);});
 await login(page,'agent','http://localhost:8089','/ops/availability?property='+id);expect((await apiRequest(page,'/ops/viewing-availability/'+id,{version:0,listingVersion:1,agentId:agent,status:'active',durationMinutes:60,bufferMinutes:15,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'},'PUT')).ok()).toBe(true);
 await login(page,'buyer');const booking={version:0,listingId:id,listingVersion:1,scheduleVersion:1,agentId:agent,startAt:date+'T01:00:00.000Z'},response=await page.request.post('/api/v1/viewings',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:booking});expect(response.status()).toBe(201);const row=(await response.json()).data,record=()=>page.locator('.record-row[data-record-id="'+row.id+'"]');
 await login(page,'agent','http://localhost:8089','/ops/viewings'+query+'&status=requested');await record().getByRole('button',{name:'Confirm',exact:true}).click();await expect(record()).toHaveCount(0);
 await login(page,'buyer','http://localhost:8088','/account/viewings'+query+'&status=confirmed');await expect(record()).toContainText('09:00 GMT+8 – 10:00');await record().getByRole('button',{name:'Reschedule viewing',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Reschedule viewing',exact:true});await dialog.getByLabel('New viewing date',{exact:true}).fill(date);await dialog.getByLabel('New available viewing time',{exact:true}).selectOption(date+'T04:00:00.000Z');
 const conflict=await page.request.post('/api/v1/viewings',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{...booking,startAt:date+'T04:00:00.000Z'}});expect(conflict.status()).toBe(201);const conflicting=(await conflict.json()).data;await dialog.getByRole('button',{name:'Save new viewing time',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('original booking is preserved');expect(await staff(async c=>(await c.query('SELECT status,version,start_at FROM viewings WHERE id=$1',[row.id])).rows[0])).toMatchObject({status:'confirmed',version:2,start_at:new Date(booking.startAt)});expect((await page.request.post('/api/v1/viewings/'+conflicting.id+'/cancel',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{version:1}})).ok()).toBe(true);
 let lost=true,key:string|undefined;await page.route('**/api/v1/viewings/'+row.id+'/reschedule',async route=>{const r=await route.fetch();if(lost&&r.ok()){lost=false;key=route.request().headers()['idempotency-key'];await route.abort('failed');}else{expect(route.request().headers()['idempotency-key']).toBe(key);await route.fulfill({response:r});}});await dialog.getByRole('button',{name:'Save new viewing time',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('New available viewing time',{exact:true})).toHaveValue(date+'T04:00:00.000Z');expect((await new AxeBuilder({page}).include('dialog').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/l05-reschedule-${info.project.name}.png`,scale:'css'});await dialog.getByRole('button',{name:'Save new viewing time',exact:true}).click();await expect(dialog).toHaveCount(0);await page.unroute('**/api/v1/viewings/'+row.id+'/reschedule');await page.getByLabel('Viewing status',{exact:true}).selectOption('requested');await page.getByRole('button',{name:'Apply calendar filters',exact:true}).click();await expect(page).toHaveURL(/status=requested/);await expect(record()).toContainText('12:00 GMT+8 – 13:00');expect((await (await page.request.get('/api/v1/me/viewings'+query+'&status=requested')).json()).data.find((r:any)=>r.id===row.id).version).toBe(3);await page.reload();await expect(record()).toContainText('Requested');expect((await (await page.request.get('/api/v1/viewing-slots?listingId='+id+'&date='+date+'&days=1')).json()).data.slots.some((s:any)=>s.startAt===booking.startAt)).toBe(true);expect(await staff(async c=>(await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='viewing.rescheduled'",[row.id])).rows[0].n)).toBe(1);
 await login(page,'agent','http://localhost:8089','/ops/viewings'+query+'&status=requested');await record().getByRole('button',{name:'Confirm',exact:true}).click();await expect(record()).toHaveCount(0);await page.getByLabel('Viewing status',{exact:true}).selectOption('confirmed');await page.getByRole('button',{name:'Apply calendar filters',exact:true}).click();await record().getByRole('button',{name:'Cancel viewing',exact:true}).click();await expect(record()).toHaveCount(0);expect((await (await page.request.get('http://localhost:8088/api/v1/viewing-slots?listingId='+id+'&date='+date+'&days=1')).json()).data.slots.some((s:any)=>s.startAt===date+'T04:00:00.000Z')).toBe(true);
 const localDate=(value:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(value);await page.goto('http://localhost:8089/ops/viewings?from='+localDate(past[1].start_at)+'&to='+localDate(past[0].start_at)+'&status=confirmed');const completed=page.locator('.record-row[data-record-id="'+past[0].id+'"]'),missed=page.locator('.record-row[data-record-id="'+past[1].id+'"]');await completed.getByRole('button',{name:'Mark completed',exact:true}).click();await expect(completed).toHaveCount(0);await missed.getByRole('button',{name:'Mark no-show',exact:true}).click();await expect(missed).toHaveCount(0);await page.getByLabel('Viewing status',{exact:true}).selectOption('');await page.getByRole('button',{name:'Apply calendar filters',exact:true}).click();await expect(completed).toContainText('Completed');await expect(missed).toContainText('No-show');expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/l05-outcomes-${info.project.name}.png`,scale:'css'});
 await login(page,'outsider','http://localhost:8089','/ops/viewings');expect((await apiRequest(page,'/ops/viewings/'+row.id+'/cancel',{version:5})).status()).toBe(404);expect((await apiRequest(page,'/ops/viewings/'+past[0].id+'/outcome',{version:2,status:'no_show'})).status()).toBe(404);await expect(page.locator('main')).not.toContainText(title);
 }finally{await staff(async c=>{await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=$1 AND status IN('requested','confirmed')",[id]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[id]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}
});
