import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('L03 agent authors working hours and private blocks; buyer sees valid property-zone times and paused empty state',async({page},info)=>{
 test.setTimeout(150000);const id=crypto.randomUUID(),agent=crypto.randomUUID(),slug='l03-browser-'+id,date=new Date(Date.now()+86400000).toISOString().slice(0,10),reason='L03 private browser unavailable '+id;
 try{await staff(async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'L03 browser agent',$3,'Explicit synthetic availability fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,'L03 browser viewing property','Synthetic viewing policy acceptance fixture','sale','residential','CNY','2100000.25','published')",[id,org,agent,slug]);});
 await login(page,'agent','http://localhost:8089','/ops/availability?property='+id);await expect(page.getByLabel('Property availability',{exact:true})).toHaveValue(id);await expect(page.locator('main')).toContainText('Asia/Shanghai');
 for(const day of ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])await page.getByLabel(day,{exact:true}).check();await page.getByRole('button',{name:'Save working hours',exact:true}).click();await expect(page.getByRole('heading',{name:'Unavailable interval',exact:true})).toBeVisible();
 await page.getByLabel('Unavailable from',{exact:true}).fill(date+'T10:00');await page.getByLabel('Unavailable until',{exact:true}).fill(date+'T11:00');await page.getByLabel('Private interval reason',{exact:true}).fill(reason);await page.getByRole('button',{name:'Save unavailable interval',exact:true}).click();await expect(page.locator('.review-card')).toContainText(reason);await page.reload();await expect(page.locator('.review-card')).toContainText(reason);
 const slots=(await (await page.request.get('http://localhost:8088/api/v1/viewing-slots?listingId='+id+'&date='+date+'&days=1')).json()).data;expect(slots.slots.some((s:any)=>s.startAt===date+'T01:00:00.000Z')).toBe(false);expect(slots.slots.some((s:any)=>s.startAt===date+'T03:15:00.000Z')).toBe(true);expect(JSON.stringify(slots)).not.toContain(reason);
 expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/l03-availability-${info.project.name}.png`,scale:'css'});
 await login(page,'buyer','http://localhost:8088','/bj/buy/'+slug);await page.getByRole('button',{name:'Request a viewing',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Asia/Shanghai');await dialog.getByLabel('Viewing date',{exact:true}).fill(date);await expect(dialog.getByLabel('Available viewing time',{exact:true})).toContainText('11:15');await dialog.getByLabel('Available viewing time',{exact:true}).selectOption(date+'T03:15:00.000Z');await expect(dialog.getByLabel('Available viewing time',{exact:true}).locator('option:checked')).toContainText('GMT+8');expect((await new AxeBuilder({page}).include('dialog').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/l03-viewing-times-${info.project.name}.png`,scale:'css'});
 await login(page,'agent','http://localhost:8089','/ops/availability?property='+id);await page.getByRole('button',{name:'Cancel unavailable interval',exact:true}).click();await expect(page.locator('.review-card')).toContainText('cancelled');const restored=(await (await page.request.get('http://localhost:8088/api/v1/viewing-slots?listingId='+id+'&date='+date+'&days=1')).json()).data;expect(restored.slots.some((s:any)=>s.startAt===date+'T01:00:00.000Z')).toBe(true);await page.getByLabel('Availability status',{exact:true}).selectOption('paused');await page.getByRole('button',{name:'Save working hours',exact:true}).click();await expect(page.getByRole('heading',{name:'Unavailable interval',exact:true})).toHaveCount(0);
 await login(page,'buyer','http://localhost:8088','/bj/buy/'+slug);await page.getByRole('button',{name:'Request a viewing',exact:true}).click();await expect(dialog.getByLabel('Available viewing time',{exact:true})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Request viewing',exact:true})).toBeDisabled();await expect(dialog.getByRole('status')).toContainText('The assigned agent has not published viewing availability.');
 }finally{await staff(async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[id]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}
});
