import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('L04 consumer retries a lost reservation receipt; concurrent requests conflict and actual assigned agent confirms once',async({page},info)=>{
 test.setTimeout(150000);const id=crypto.randomUUID(),agent=crypto.randomUUID(),slug='l04-browser-'+id,title='L04 reservation '+id.slice(0,8),date=new Date(Date.now()+86400000).toISOString().slice(0,10);let saved:any,submitted:any,key:string|undefined;
 try{await staff(async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'L04 browser agent',$3,'Explicit synthetic reservation fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,$5,'Synthetic transactional reservation acceptance fixture','sale','residential','CNY','2100000.25','published')",[id,org,agent,slug,title]);});
 await login(page,'agent','http://localhost:8089','/ops/availability?property='+id);const read=(await (await page.request.get('http://localhost:8089/api/v1/ops/viewing-availability/'+id)).json()).data;expect((await apiRequest(page,'/ops/viewing-availability/'+id,{version:0,listingVersion:read.listing.version,agentId:agent,status:'active',durationMinutes:45,bufferMinutes:30,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'},'PUT')).ok()).toBe(true);
 await login(page,'buyer','http://localhost:8088','/bj/buy/'+slug);await page.getByRole('button',{name:'Request a viewing',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Viewing date',{exact:true}).fill(date);await dialog.getByLabel('Available viewing time',{exact:true}).selectOption(date+'T01:00:00.000Z');await expect(dialog.getByRole('status')).toContainText('09:00 GMT+8 – 09:45');let lost=true;
 await page.route('**/api/v1/viewings',async route=>{const response=await route.fetch();if(lost&&response.ok()){lost=false;key=route.request().headers()['idempotency-key'];submitted=route.request().postDataJSON();saved=(await response.json()).data;await route.abort('failed');}else{expect(route.request().headers()['idempotency-key']).toBe(key);await route.fulfill({response});}});
 await dialog.getByRole('button',{name:'Request viewing',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Available viewing time',{exact:true})).toHaveValue(date+'T01:00:00.000Z');await dialog.getByRole('button',{name:'Request viewing',exact:true}).click();await expect(page.locator('.toast')).toContainText('Viewing requested');await page.unroute('**/api/v1/viewings');expect(submitted).toMatchObject({version:0,listingId:id,listingVersion:1,scheduleVersion:1,agentId:agent});expect(saved).toMatchObject({property_zone:'Asia/Shanghai',buffer_minutes:30,status:'requested',version:1});expect(Date.parse(saved.end_at)-Date.parse(saved.start_at)).toBe(45*60000);expect(await staff(async c=>(await c.query('SELECT count(*)::int n FROM viewings WHERE listing_id=$1',[id])).rows[0].n)).toBe(1);
 const body={...submitted,startAt:date+'T04:00:00.000Z'},send=()=>page.request.post('/api/v1/viewings',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:body}),races=await Promise.all([send(),send()]);expect(races.map(r=>r.status()).sort()).toEqual([201,409]);const second=(await races.find(r=>r.status()===201)!.json()).data;expect((await page.request.post('/api/v1/viewings/'+second.id+'/cancel',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{version:second.version}})).ok()).toBe(true);
 await login(page,'outsider','http://localhost:8089','/ops/viewings');expect((await apiRequest(page,'/ops/viewings/'+saved.id+'/confirm',{version:1,listingVersion:1,scheduleVersion:1})).status()).toBe(404);
 await login(page,'agent','http://localhost:8089','/ops/viewings');const row=page.locator('.record-row[data-record-id="'+saved.id+'"]');await expect(row).toHaveCount(1);await row.getByRole('button',{name:'Confirm',exact:true}).click();await expect(row).toContainText('Confirmed');expect((await apiRequest(page,'/ops/viewings/'+saved.id+'/confirm',{version:1,listingVersion:1,scheduleVersion:1})).status()).toBe(409);expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/l04-confirmed-${info.project.name}.png`,scale:'css'});
 await login(page,'buyer','http://localhost:8088','/account/viewings');const own=page.locator('.record-row').filter({hasText:title}).filter({hasText:'confirmed'});await expect(own).toHaveCount(1);await own.getByRole('button',{name:'Cancel viewing',exact:true}).click();await expect(page.locator('.record-row').filter({hasText:title}).filter({hasText:'cancelled'})).toHaveCount(2);expect((await (await page.request.get('/api/v1/viewing-slots?listingId='+id+'&date='+date+'&days=1')).json()).data.slots.some((s:any)=>s.startAt===submitted.startAt)).toBe(true);
 }finally{await staff(async c=>{await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=$1 AND status IN('requested','confirmed')",[id]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[id]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}
});
