import '../support/env';
import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {deliverViewingReminder} from '../../apps/worker/src/viewing-reminders';
import {login,apiRequest} from '../support/browser';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.DATABASE_URL}),org='10000000-0000-4000-8000-000000000001';
async function staff(work:(c:any)=>Promise<any>){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.admin','true',true),set_config('app.actor','00000000-0000-4000-8000-000000000010',true)");const r=await work(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
test.afterAll(()=>fixtures.end());test.use({actionTimeout:15000});
test('L06 native professional CSV downloads are scoped and formula-safe; confirmation sends one actual reminder and cancellation invalidates retry',async({page},info)=>{
 test.setTimeout(180000);const id=crypto.randomUUID(),agent=crypto.randomUUID(),lead=crypto.randomUUID(),slug='l06-browser-'+id,title='L06 reminder '+id.slice(0,8),marker='L06'+id.slice(0,8),name='=HYPERLINK("https://invalid.test","'+marker+'")',date=new Date(Date.now()+172800000).toISOString().slice(0,10),query='?from='+date+'&to='+date;
 try{await staff(async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,'00000000-0000-4000-8000-000000000003',$2,'L06 browser agent',$3,'Synthetic reminder fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,org,slug]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,$5,'Synthetic reminder fixture','sale','residential','CNY','2100000.25','published')",[id,org,agent,slug,title]);await c.query("INSERT INTO leads(id,user_id,organization_id,resource_id,resource_type,agent_id,name,email,phone,message) VALUES($1,'00000000-0000-4000-8000-000000000001',$2,$3,'listing',$4,$5,'fixture@example.test','+86123456789','PRIVATE MESSAGE NEVER EXPORT')",[lead,org,id,agent,name]);});
 await login(page,'agent','http://localhost:8089','/ops/leads?text='+marker);await expect(page.locator('main')).toContainText(name);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export inquiries CSV',exact:true}).click();const download=await downloadPromise,content=await readFile((await download.path())!,'utf8');expect(content).toContain('"\'=HYPERLINK');expect(content).toContain(lead);expect(content).not.toContain('PRIVATE MESSAGE');await expect(page.getByRole('status').filter({hasText:'Exported 1 assigned records.'})).toBeVisible();expect((await new AxeBuilder({page}).include('main').analyze()).violations.filter(v=>v.impact==='serious'||v.impact==='critical')).toEqual([]);await page.screenshot({path:`evidence/l06-exports-${info.project.name}.png`,scale:'css'});
 expect((await apiRequest(page,'/ops/viewing-availability/'+id,{version:0,listingVersion:1,agentId:agent,status:'active',durationMinutes:60,bufferMinutes:15,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'},'PUT')).ok()).toBe(true);
 await login(page,'buyer','http://localhost:8088','/account/viewings'+query);const slots=(await (await page.request.get('/api/v1/viewing-slots?listingId='+id+'&date='+date+'&days=1')).json()).data;const booking=await page.request.post('http://localhost:8088/api/v1/viewings',{headers:{Origin:'http://localhost:8088','idempotency-key':crypto.randomUUID()},data:{version:0,listingId:id,listingVersion:slots.listingVersion,scheduleVersion:slots.scheduleVersion,agentId:agent,startAt:date+'T01:00:00.000Z'}});expect(booking.ok()).toBe(true);const row=(await booking.json()).data;
 await login(page,'agent','http://localhost:8089','/ops/viewings'+query+'&status=requested');const record=()=>page.locator('.record-row[data-record-id="'+row.id+'"]');await record().getByRole('button',{name:'Confirm',exact:true}).click();await expect(record()).toHaveCount(0);const reminder=await staff(async c=>(await c.query('SELECT * FROM viewing_reminders WHERE viewing_id=$1',[row.id])).rows[0]);await staff(c=>c.query("UPDATE viewing_reminders SET due_at=now()-interval '1 second' WHERE id=$1",[reminder.id]));await deliverViewingReminder(reminder.id);await deliverViewingReminder(reminder.id);expect(await staff(async c=>(await c.query('SELECT status FROM viewing_reminders WHERE id=$1',[reminder.id])).rows[0].status)).toBe('accepted');const messageId='viewing-'+reminder.id+'@'+new URL(process.env.PUBLIC_WEB_URL!).hostname;expect((await (await fetch('http://mail:8025/api/v1/search?query='+encodeURIComponent('message-id:'+messageId))).json()).messages_count).toBe(1);
 await page.goto('http://localhost:8089/ops/viewings'+query+'&status=confirmed');await expect(record()).toContainText(title);const viewingDownloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export viewings CSV',exact:true}).click();expect(await readFile((await (await viewingDownloadPromise).path())!,'utf8')).toContain(row.id);await record().getByRole('button',{name:'Cancel viewing',exact:true}).click();await expect(record()).toHaveCount(0);
 await login(page,'buyer','http://localhost:8088','/account/notifications');await expect(page.locator('main#main')).toContainText('Upcoming viewing: '+title);await expect(page.locator('main#main article').filter({has:page.getByRole('heading',{name:'Upcoming viewing: '+title,exact:true})}).getByRole('link',{name:'Review viewing calendar',exact:true})).toHaveAttribute('href','/account/viewings');await page.screenshot({path:`evidence/l06-notification-${info.project.name}.png`,scale:'css'});
 await login(page,'outsider','http://localhost:8089','/ops/leads?text='+marker);await expect(page.locator('main')).not.toContainText(name);const response=await page.request.get('http://localhost:8089/api/v1/ops/lead-queue/export?text='+marker);expect(response.ok()).toBe(true);expect((await response.json()).data.records).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await staff(async c=>{await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=$1 AND status IN('requested','confirmed')",[id]);await c.query('DELETE FROM leads WHERE id=$1',[lead]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[id]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}
});
