import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {login} from '../support/browser';
import {screenshotReady} from '../../scripts/screenshot-ready';
const screens=JSON.parse(fs.readFileSync('docs/reference/screens.json','utf8')),folder='evidence/visual/q02-auth',records:any[]=[];
const persona=(id:string)=>id==='account-owner'?'owner':['tenant','account-tenant'].includes(id)?'tenant':id==='account-management'||id==='ops-management'?'manager':id==='ops-developments'?'developer':id==='ops-quotes'?'vendor':id==='ops-reviews'?'moderator':id==='ops-support'?'support':['ops-listings','ops-leads','ops-viewings','ops-messages'].includes(id)?'agent':id.startsWith('ops')||id==='operations'?'admin':'buyer';
test.afterAll(()=>{fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(folder+'/manifest.json',JSON.stringify({evidenceLabel:'P',referenceParity:'unverified',scope:'Current authenticated local synthetic private pages, actual OIDC and strict staff MFA; captures exclude authentication screens.',screens:records},null,2)+'\n');});
for(const role of ['buyer','owner','tenant','manager','developer','vendor','moderator','support','agent','admin'])test('Q02 actual authenticated '+role+' entry evidence at both mobile widths',async({page})=>{test.setTimeout(180000);const selected=screens.filter((s:any)=>(s.localRoute.startsWith('/account')||s.localRoute.startsWith('/tenant')||s.localRoute.startsWith('/ops'))&&persona(s.id)===role);fs.mkdirSync(folder,{recursive:true});for(const origin of [process.env.PUBLIC_WEB_URL||'http://localhost:8088',process.env.PUBLIC_OPS_URL||'http://localhost:8089']){const routes=selected.filter((s:any)=>s.localRoute.startsWith('/ops')===(origin===(process.env.PUBLIC_OPS_URL||'http://localhost:8089')));if(!routes.length)continue;await login(page,role,origin,routes[0].localRoute);expect((await page.request.get(origin+'/api/v1/me')).ok()).toBe(true);for(const width of [375,390]){await page.setViewportSize({width,height:width===375?812:844});for(const screen of routes){expect((await page.goto(origin+screen.localRoute))?.status(),screen.id).toBe(200);await page.waitForLoadState('networkidle');await screenshotReady(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);const file=screen.id+'-'+width+'.png',bytes=await page.screenshot({path:folder+'/'+file,fullPage:true,animations:'disabled'});records.push({id:screen.id,route:screen.localRoute,persona:role,viewport:{width,height:width===375?812:844},file,sha256:createHash('sha256').update(bytes).digest('hex'),capturedAt:new Date().toISOString(),evidenceLabel:'P',referenceParity:'unverified',state:'actual authenticated current workflow; permission/empty states remain visible'});}}}});
