import {Body,Controller,Get,HttpCode,Inject,Param,Post,Req} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type {Actor} from '@haven/database';
import type pg from 'pg';
import {z} from 'zod';
import {digitizationCaptureCreate,digitizationCapturePart,digitizationCaptureVersion,digitizationCaptureComplete,digitizationCaptureSessionCreate,digitizationCaptureSessionSave} from '@haven/contracts';
import {createCaptureSession,readCaptureSession,saveCaptureSession} from './capture-session.js';
import {finalizeCapture} from './capture-finalization.js';
import {Identity,data,fail,idempotent,transaction} from '../../platform/core.js';
import {digitizationListingAccess} from '../property-access.js';
import {checkedWorkspace,requireDigitizationAgency} from './intakes.js';
import {captureColumns,captureRecord,checkedCapture,reserveCapture,provisionCapture,readCapture,capturePartGrant,captureUploadOrigin,requestCaptureCancellation,finishCaptureCancellation} from './capture.js';
async function engine(c:pg.PoolClient,a:Actor,target:string,listing:boolean){z.uuid().parse(target);await requireDigitizationAgency(c,a);if(!listing){await checkedWorkspace(c,target,'intake');return target;}await digitizationListingAccess(c,a,target);const row=(await c.query("SELECT id FROM property_digitizations WHERE listing_id=$1 AND state='active'",[target])).rows[0];if(!row)fail(404,'Create a digitization workspace before capture.');return row.id;}
@Controller('api/v1')
export class DigitizationCaptureController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/digitizations/:id/capture-uploads') async uploads(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['agent','agency_manager']);z.uuid().parse(id);return transaction(a,async c=>{await requireDigitizationAgency(c,a);await checkedWorkspace(c,id);return data((await c.query(`SELECT ${captureColumns} FROM digitization_capture_uploads WHERE digitization_id=$1 AND created_by=$2 AND state IN('uploading','complete') ORDER BY created_at DESC,id DESC LIMIT 100`,[id,a.id])).rows.map(row=>captureRecord(row)));});}
 @Get('ops/digitizations/:id/capture-session') async session(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['agent','agency_manager']);z.uuid().parse(id);return transaction(a,async c=>data(await readCaptureSession(c,a,id)));}
 @Post('ops/digitizations/:id/capture-session') async startSession(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager']),x=digitizationCaptureSessionCreate.parse(body);z.uuid().parse(id);return transaction(a,async c=>{await requireDigitizationAgency(c,a);await checkedWorkspace(c,id);return idempotent(c,a,req,x,async()=>data(await createCaptureSession(c,a,id,x.workspaceVersion)));});}
 @Post('ops/digitizations/:id/capture-session/:sessionId') async saveSession(@Req() req:FastifyRequest,@Param('id') id:string,@Param('sessionId') sessionId:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager']),x=digitizationCaptureSessionSave.parse(body);z.uuid().parse(id);z.uuid().parse(sessionId);return transaction(a,async c=>{await requireDigitizationAgency(c,a);await checkedWorkspace(c,id);return idempotent(c,a,req,x,async()=>data(await saveCaptureSession(c,a,id,sessionId,x)));});}
 private async complete(req:FastifyRequest,target:string,listing:boolean,id:string,x:z.infer<typeof digitizationCaptureComplete>){const a=await this.identity.actor(req,['agent','agency_manager']);z.uuid().parse(id);const saved=await transaction(a,async c=>{const workspace=await engine(c,a,target,listing);await checkedCapture(c,a,workspace,id);return idempotent(c,a,req,x,async()=>{const row=await checkedCapture(c,a,workspace,id,x.version);if(row.state!=='uploading')fail(409,'Capture does not accept completion.','CAPTURE_NOT_COMPLETABLE');return {engine:workspace,id,version:x.version,checksum:x.checksum};});});return data(await finalizeCapture(a,saved.engine,saved.id,saved.version,saved.checksum));}
 @Post('ops/digitization-intakes/:id/capture-uploads/:uploadId/complete') @HttpCode(202) async completeIntake(@Req() req:FastifyRequest,@Param('id') id:string,@Param('uploadId') uploadId:string,@Body() body:unknown){const x=digitizationCaptureComplete.parse(body);return this.complete(req,id,false,uploadId,x);}
 @Post('ops/listings/:listingId/digitization/capture-uploads/:uploadId/complete') @HttpCode(202) async completeListing(@Req() req:FastifyRequest,@Param('listingId') listingId:string,@Param('uploadId') uploadId:string,@Body() body:unknown){const x=digitizationCaptureComplete.parse(body);return this.complete(req,listingId,true,uploadId,x);}
 private async create(req:FastifyRequest,target:string,listing:boolean,x:z.infer<typeof digitizationCaptureCreate>){const a=await this.identity.actor(req,['agent','agency_manager']);captureUploadOrigin();const saved=await transaction(a,async c=>{const id=await engine(c,a,target,listing);const receipt=await idempotent(c,a,req,x,()=>reserveCapture(c,a,id,x));return {engine:id,id:receipt.id};});return data(await provisionCapture(a,saved.engine,saved.id));}
 private async read(req:FastifyRequest,target:string,listing:boolean,id:string){const a=await this.identity.actor(req,['agent','agency_manager']);z.uuid().parse(id);const workspace=await transaction(a,c=>engine(c,a,target,listing));return data(await readCapture(a,workspace,id));}
 private async part(req:FastifyRequest,target:string,listing:boolean,id:string,x:z.infer<typeof digitizationCapturePart>){const a=await this.identity.actor(req,['agent','agency_manager']);z.uuid().parse(id);const saved=await transaction(a,async c=>{const workspace=await engine(c,a,target,listing);await checkedCapture(c,a,workspace,id);const receipt=await idempotent(c,a,req,x,async()=>({engine:workspace,id,version:x.version,partNumber:x.partNumber}));return receipt;});return data(await capturePartGrant(a,saved.engine,saved.id,x));}
 private async cancel(req:FastifyRequest,target:string,listing:boolean,id:string,x:z.infer<typeof digitizationCaptureVersion>){const a=await this.identity.actor(req,['agent','agency_manager']);z.uuid().parse(id);const saved=await transaction(a,async c=>{const workspace=await engine(c,a,target,listing);await checkedCapture(c,a,workspace,id);await idempotent(c,a,req,x,()=>requestCaptureCancellation(c,a,workspace,id,x.version));return {engine:workspace};});return data(await finishCaptureCancellation(a,saved.engine,id));}
 @Post('ops/digitization-intakes/:id/capture-uploads') async createIntake(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const x=digitizationCaptureCreate.parse(body);return this.create(req,id,false,x);}
 @Get('ops/digitization-intakes/:id/capture-uploads/:uploadId') async readIntake(@Req() req:FastifyRequest,@Param('id') id:string,@Param('uploadId') uploadId:string){return this.read(req,id,false,uploadId);}
 @Post('ops/digitization-intakes/:id/capture-uploads/:uploadId/parts') async partIntake(@Req() req:FastifyRequest,@Param('id') id:string,@Param('uploadId') uploadId:string,@Body() body:unknown){const x=digitizationCapturePart.parse(body);return this.part(req,id,false,uploadId,x);}
 @Post('ops/digitization-intakes/:id/capture-uploads/:uploadId/cancel') async cancelIntake(@Req() req:FastifyRequest,@Param('id') id:string,@Param('uploadId') uploadId:string,@Body() body:unknown){const x=digitizationCaptureVersion.parse(body);return this.cancel(req,id,false,uploadId,x);}
 @Post('ops/listings/:listingId/digitization/capture-uploads') async createListing(@Req() req:FastifyRequest,@Param('listingId') listingId:string,@Body() body:unknown){const x=digitizationCaptureCreate.parse(body);return this.create(req,listingId,true,x);}
 @Get('ops/listings/:listingId/digitization/capture-uploads/:uploadId') async readListing(@Req() req:FastifyRequest,@Param('listingId') listingId:string,@Param('uploadId') uploadId:string){return this.read(req,listingId,true,uploadId);}
 @Post('ops/listings/:listingId/digitization/capture-uploads/:uploadId/parts') async partListing(@Req() req:FastifyRequest,@Param('listingId') listingId:string,@Param('uploadId') uploadId:string,@Body() body:unknown){const x=digitizationCapturePart.parse(body);return this.part(req,listingId,true,uploadId,x);}
 @Post('ops/listings/:listingId/digitization/capture-uploads/:uploadId/cancel') async cancelListing(@Req() req:FastifyRequest,@Param('listingId') listingId:string,@Param('uploadId') uploadId:string,@Body() body:unknown){const x=digitizationCaptureVersion.parse(body);return this.cancel(req,listingId,true,uploadId,x);}
}
