import type pg from 'pg';
import {event,type Actor} from '@haven/database';
import {env,fail,transaction} from '../../platform/core.js';
import {checkedWorkspace} from './intakes.js';
import {capturePartBytes,captureStorage,captureObjectKey,startCaptureMultipart,captureParts,signCapturePart,abortCaptureMultipart,assembledCaptureBytes} from './multipart.js';
export const captureColumns=`id,digitization_id AS "digitizationId",organization_id AS "organizationId",created_by AS "createdBy",object_key AS "objectKey",upload_id AS "uploadId",expected_bytes AS "expectedBytes",mime,state,version,expires_at AS "expiresAt"`;
const columns=captureColumns;
export function captureRecord(row:any,parts:any[]=[]){return {id:row.id,digitizationId:row.digitizationId,version:row.version,state:row.state,mime:row.mime,bytes:Number(row.expectedBytes),partBytes:capturePartBytes,expiresAt:row.expiresAt.toISOString(),parts:parts.map(p=>({partNumber:p.PartNumber,bytes:p.Size,etag:p.ETag}))};}
export async function checkedCapture(c:pg.PoolClient,a:Actor,engine:string,id:string,version?:number){await checkedWorkspace(c,engine);const row=(await c.query(`SELECT ${columns} FROM digitization_capture_uploads WHERE id=$1 AND digitization_id=$2 AND created_by=$3 FOR UPDATE`,[id,engine,a.id])).rows[0];if(!row)fail(404,'Capture upload not found');if(version!==undefined&&row.version!==version)fail(409,'Capture upload changed. Reload before continuing.','VERSION_CONFLICT');return row;}
export async function reserveCapture(c:pg.PoolClient,a:Actor,engine:string,x:{digitizationVersion:number;bytes:number;mime:string;rights:string}){const workspace=await checkedWorkspace(c,engine);if(workspace.version!==x.digitizationVersion)fail(409,'Digitization changed. Reload before capture.','VERSION_CONFLICT');if(workspace.state!=='active')fail(409,'Digitization no longer accepts capture.','WORKFLOW_CONFLICT');if(!(await c.query('SELECT digitization_capture_quota($1,$2) AS allowed',[engine,x.bytes])).rows[0].allowed)fail(429,'Property capture quota exceeded. Remove unused captures before retrying.','CAPTURE_QUOTA_EXCEEDED');const id=crypto.randomUUID();const row=(await c.query(`INSERT INTO digitization_capture_uploads(id,digitization_id,organization_id,created_by,object_key,mime,expected_bytes,rights) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING ${columns}`,[id,engine,workspace.organizationId,a.id,captureObjectKey(id),x.mime,x.bytes,x.rights])).rows[0];await event(c,a,engine,'digitization.capture_reserved',{captureUploadId:id,version:1});return {id:row.id};}
export async function provisionCapture(a:Actor,engine:string,id:string){const row=await transaction(a,c=>checkedCapture(c,a,engine,id));if(row.state!=='provisioning')return captureRecord(row);if(row.expiresAt<=new Date())fail(409,'Capture reservation expired.');const storage=captureStorage();let uploadId:string|undefined;try{uploadId=await startCaptureMultipart(storage,row.objectKey,row.mime);const current=await transaction(a,async c=>{await checkedCapture(c,a,engine,id,row.version);const result=(await c.query(`UPDATE digitization_capture_uploads SET upload_id=$2,state='uploading',version=version+1 WHERE id=$1 RETURNING ${columns}`,[id,uploadId])).rows[0];await event(c,a,engine,'digitization.capture_started',{captureUploadId:id,version:result.version});return result;});return captureRecord(current);}catch(error){if(uploadId)await abortCaptureMultipart(storage,row.objectKey,uploadId).catch(()=>undefined);throw error;}finally{storage.destroy();}}
export async function readCapture(a:Actor,engine:string,id:string){const row=await transaction(a,c=>checkedCapture(c,a,engine,id));if(row.state!=='uploading')return captureRecord(row);const storage=captureStorage();try{let parts;try{parts=await captureParts(storage,row.objectKey,row.uploadId);}catch(error:any){if(error.name!=='NoSuchUpload')throw error;if(await assembledCaptureBytes(storage,row.objectKey)!==Number(row.expectedBytes))fail(422,'Stored capture size does not match.','CAPTURE_OBJECT_MISMATCH');await transaction(a,c=>checkedCapture(c,a,engine,id,row.version));return {...captureRecord(row),completionRequired:true};}await transaction(a,c=>checkedCapture(c,a,engine,id,row.version));return captureRecord(row,parts);}finally{storage.destroy();}}
export function captureUploadOrigin(){const raw=process.env.CAPTURE_UPLOAD_ORIGIN;if(!raw)fail(503,'Capture upload origin is not configured.','CAPTURE_UNAVAILABLE');const url=new URL(raw);if(url.username||url.password||url.pathname!=='/'||url.search||url.hash||env.NODE_ENV==='production'&&url.protocol!=='https:'||!['http:','https:'].includes(url.protocol))fail(503,'Capture upload origin is invalid.','CAPTURE_UNAVAILABLE');return url.origin;}
export async function capturePartGrant(a:Actor,engine:string,id:string,x:{version:number;partNumber:number}){const origin=captureUploadOrigin(),row=await transaction(a,c=>checkedCapture(c,a,engine,id,x.version));if(row.state!=='uploading'||row.expiresAt<=new Date())fail(409,'Capture upload is no longer active.','WORKFLOW_CONFLICT');const count=Math.ceil(Number(row.expectedBytes)/capturePartBytes);if(x.partNumber>count)fail(422,'Part is outside this capture.','CAPTURE_PART_INVALID');const bytes=Math.min(capturePartBytes,Number(row.expectedBytes)-(x.partNumber-1)*capturePartBytes),signer=captureStorage(origin);try{return {url:await signCapturePart(signer,row.objectKey,row.uploadId,x.partNumber,bytes),method:'PUT' as const,bytes,expiresIn:600 as const,partNumber:x.partNumber};}finally{signer.destroy();}}
export async function requestCaptureCancellation(c:pg.PoolClient,a:Actor,engine:string,id:string,version:number){const row=await checkedCapture(c,a,engine,id,version);if(!['provisioning','uploading','cancel_requested','cancelled'].includes(row.state))fail(409,'Capture can no longer be cancelled.','WORKFLOW_CONFLICT');if(['provisioning','uploading'].includes(row.state))await c.query("UPDATE digitization_capture_uploads SET state='cancel_requested',version=version+1 WHERE id=$1",[id]);return {id};}
export async function finishCaptureCancellation(a:Actor,engine:string,id:string){const row=await transaction(a,c=>checkedCapture(c,a,engine,id));if(row.state==='cancelled')return captureRecord(row);if(row.state!=='cancel_requested')fail(409,'Capture cancellation was not requested.','WORKFLOW_CONFLICT');if(row.uploadId){const storage=captureStorage();try{await abortCaptureMultipart(storage,row.objectKey,row.uploadId);}catch(e:any){if(e.name!=='NoSuchUpload')throw e;}finally{storage.destroy();}}return transaction(a,async c=>{const current=await checkedCapture(c,a,engine,id);if(current.state==='cancelled')return captureRecord(current);if(current.version!==row.version)fail(409,'Capture changed during cancellation.','VERSION_CONFLICT');const r=(await c.query(`UPDATE digitization_capture_uploads SET state='cancelled',version=version+1 WHERE id=$1 RETURNING ${columns}`,[id])).rows[0];await event(c,a,engine,'digitization.capture_cancelled',{captureUploadId:id,version:r.version});return captureRecord(r);});}
