import type {FastifyReply,FastifyRequest} from 'fastify';
import {setTimeout as delay} from 'node:timers/promises';
import {Identity,fail,transaction} from '../../platform/core.js';
import {checkedWorkspace,requireDigitizationAgency} from './intakes.js';
import {digitizationListingAccess} from '../property-access.js';
export async function streamDigitizationEvents(identity:Identity,req:FastifyRequest,reply:FastifyReply,target:string,listing:boolean){
 const value=req.headers['last-event-id'];if(value!==undefined&&(typeof value!=='string'||!/^\d{1,19}$/.test(value)||BigInt(value)>9223372036854775807n))fail(422,'Invalid progress resume cursor.','EVENT_CURSOR_INVALID');let cursor=value||'0';
 async function read(){const a=await identity.actor(req,['agent','agency_manager']);return transaction(a,async c=>{await requireDigitizationAgency(c,a);let id=target;if(listing){await digitizationListingAccess(c,a,target);const row=(await c.query("SELECT id FROM property_digitizations WHERE listing_id=$1 AND state='active'",[target])).rows[0];if(!row)fail(404,'Digitization workspace not found');id=row.id;}await checkedWorkspace(c,id,listing?'listing':'intake',listing?target:undefined);if(!(await c.query('SELECT digitization_private_access($1) AS allowed',[id])).rows[0].allowed)fail(403,'Source evidence access has expired.','EVIDENCE_ACCESS_EXPIRED');return (await c.query(`SELECT sequence::text,id,digitization_id AS "propertyId",organization_id AS "organizationId",run_id AS "runId",kind,state,created_at AS timestamp FROM digitization_events WHERE digitization_id=$1 AND sequence>$2::bigint ORDER BY sequence LIMIT 100`,[id,cursor])).rows;});}
 let rows=await read();const abort=new AbortController(),deadline=setTimeout(()=>abort.abort(),55000);reply.raw.on('close',()=>abort.abort());reply.hijack();reply.raw.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store','X-Accel-Buffering':'no','X-Request-Id':req.id});reply.raw.write('retry: 2000\n\n');
 async function write(value:string){if(reply.raw.write(value))return;await new Promise<void>((resolve,reject)=>{const done=()=>{reply.raw.off('drain',drain);abort.signal.removeEventListener('abort',cancel);};const drain=()=>{done();resolve();},cancel=()=>{done();reject(new Error('closed'));};reply.raw.once('drain',drain);abort.signal.addEventListener('abort',cancel,{once:true});if(abort.signal.aborted)cancel();});}
 try{while(!abort.signal.aborted){for(const row of rows){if(abort.signal.aborted)break;await write(`id: ${row.sequence}\nevent: ${row.kind}\ndata: ${JSON.stringify({...row,timestamp:row.timestamp.toISOString()})}\n\n`);cursor=row.sequence;}await write(': heartbeat\n\n');await delay(rows.length===100?1:2000,undefined,{signal:abort.signal});rows=await read();}}catch{/* Closing revocation/expiration never emits private diagnostic text. */}finally{clearTimeout(deadline);abort.abort();reply.raw.end();}
}
