import {S3Client,CreateMultipartUploadCommand,UploadPartCommand,ListPartsCommand,CompleteMultipartUploadCommand,AbortMultipartUploadCommand,HeadObjectCommand,GetObjectCommand} from '@aws-sdk/client-s3';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import {createHash} from 'node:crypto';
import {env,fail} from '../../platform/core.js';
const bucket='haven-private';
export const capturePartBytes=8*1024*1024,captureClipBytes=2*1024*1024*1024;
export function captureStorage(endpoint=env.S3_ENDPOINT){return new S3Client({requestChecksumCalculation:'WHEN_REQUIRED',responseChecksumValidation:'WHEN_REQUIRED',region:'us-east-1',endpoint,forcePathStyle:true,credentials:{accessKeyId:env.S3_ACCESS_KEY,secretAccessKey:env.S3_SECRET_KEY}});}
export function captureObjectKey(id:string){if(!/^[a-f0-9-]{36}$/.test(id))fail(422,'Invalid capture identity');return 'capture/'+id;}
export async function startCaptureMultipart(client:S3Client,key:string,mime:string){const r=await client.send(new CreateMultipartUploadCommand({Bucket:bucket,Key:key,ContentType:mime}));if(!r.UploadId)throw Error('Storage did not create a multipart execution');return r.UploadId;}
export async function signCapturePart(client:S3Client,key:string,uploadId:string,part:number,bytes:number){if(!Number.isInteger(part)||part<1||part>256||!Number.isInteger(bytes)||bytes<1||bytes>capturePartBytes)fail(422,'Invalid capture part bounds');return getSignedUrl(client,new UploadPartCommand({Bucket:bucket,Key:key,UploadId:uploadId,PartNumber:part,ContentLength:bytes}),{expiresIn:600});}
export async function captureParts(client:S3Client,key:string,uploadId:string,signal=AbortSignal.timeout(120000)){const parts=[];let marker:string|undefined;do{const result=await client.send(new ListPartsCommand({Bucket:bucket,Key:key,UploadId:uploadId,PartNumberMarker:marker}),{abortSignal:signal});parts.push(...result.Parts||[]);if(!result.IsTruncated)break;marker=result.NextPartNumberMarker;if(!marker)throw Error('Invalid multipart pagination');}while(parts.length<=256);if(parts.length>256)fail(413,'Capture has too many parts');return parts;}
export async function completeCaptureMultipart(client:S3Client,key:string,uploadId:string,expectedBytes:number,signal=AbortSignal.timeout(120000)){const parts=await captureParts(client,key,uploadId,signal);if(!parts.length||expectedBytes<1||expectedBytes>captureClipBytes||parts.reduce((n,p)=>n+(p.Size||0),0)!==expectedBytes||parts.some((p,i)=>p.PartNumber!==i+1||!p.ETag||(p.Size||0)>capturePartBytes||i<parts.length-1&&(p.Size||0)<5*1024*1024))fail(422,'Stored capture parts do not match the declared upload','CAPTURE_OBJECT_MISMATCH');await client.send(new CompleteMultipartUploadCommand({Bucket:bucket,Key:key,UploadId:uploadId,MultipartUpload:{Parts:parts.map(p=>({ETag:p.ETag,PartNumber:p.PartNumber}))}}),{abortSignal:signal});const head=await client.send(new HeadObjectCommand({Bucket:bucket,Key:key}),{abortSignal:signal});if(head.ContentLength!==expectedBytes)fail(422,'Stored capture size does not match','CAPTURE_OBJECT_MISMATCH');return {bytes:head.ContentLength,etag:head.ETag};}
export async function assembledCaptureBytes(client:S3Client,key:string){const result=await client.send(new HeadObjectCommand({Bucket:bucket,Key:key}),{abortSignal:AbortSignal.timeout(5000)});return result.ContentLength;}
export async function hashCaptureObject(client:S3Client,key:string,maxBytes:number){const result=await client.send(new GetObjectCommand({Bucket:bucket,Key:key}));if(!result.Body||!result.ContentLength||result.ContentLength>maxBytes){(result.Body as any)?.destroy?.();fail(413,'Capture exceeds the declared limit');}const hash=createHash('sha256');let bytes=0;for await(const part of result.Body as AsyncIterable<Uint8Array>){bytes+=part.byteLength;if(bytes>maxBytes){(result.Body as any).destroy?.();fail(413,'Capture exceeds the declared limit');}hash.update(part);}if(bytes!==result.ContentLength)fail(422,'Capture transfer was incomplete');return {sha256:hash.digest('hex'),bytes};}
export async function abortCaptureMultipart(client:S3Client,key:string,uploadId:string){await client.send(new AbortMultipartUploadCommand({Bucket:bucket,Key:key,UploadId:uploadId}));}
