http:
  routers:
    capture-parts:
      entryPoints: [ops, web]
      rule: PathPrefix(`/haven-private/capture/`) && Method(`PUT`)
      priority: 110
      service: capture-storage
    conversation-web:
      entryPoints: [web]
      rule: PathPrefix(`/api/v1/realtime/conversations/`)
      priority: 100
      service: conversation-api
    conversation-ops:
      entryPoints: [ops]
      rule: PathPrefix(`/api/v1/realtime/conversations/`)
      priority: 100
      service: conversation-api
    web:
      entryPoints: [web]
      rule: PathPrefix(`/`)
      service: web
    ops:
      entryPoints: [ops]
      rule: PathPrefix(`/`)
      service: ops
    auth:
      entryPoints: [auth]
      rule: PathPrefix(`/`)
      service: identity
    mail:
      entryPoints: [mail]
      rule: PathPrefix(`/`)
      service: mail
  services:
    capture-storage:
      loadBalancer:
        passHostHeader: true
        servers: [{url: 'http://storage:8333'}]
    conversation-api:
      loadBalancer:
        servers: [{url: 'http://api:4000'}]
    web:
      loadBalancer:
        servers: [{url: 'http://web:3000'}]
    ops:
      loadBalancer:
        servers: [{url: 'http://ops:3001'}]
    identity:
      loadBalancer:
        servers: [{url: 'http://identity:8080'}]
    mail:
      loadBalancer:
        servers: [{url: 'http://mail:8025'}]
