import {signInquiryClient,signGatewayClient} from '@haven/config';
import {NextRequest} from 'next/server';
export async function forward(req:NextRequest,{params}:{params:Promise<{path:string[]}>}){
 const {path}=await params;if(path.some(p=>p==='..'))return Response.json({error:{message:'Invalid path'}},{status:400});const requestId=crypto.randomUUID();const origin=process.env.PUBLIC_APP_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088';
 if(!['GET','HEAD'].includes(req.method)&&req.headers.get('origin')!==origin)return Response.json({error:{code:'CSRF_REJECTED',message:'Untrusted request origin',requestId}},{status:403,headers:{'X-Request-Id':requestId}});
 const headers=new Headers();for(const key of ['content-type','cookie','idempotency-key','origin','x-organization-id','range']){const value=req.headers.get(key);if(value)headers.set(key,value);}headers.set('x-bff-origin',origin);
 const address=req.headers.get('x-real-ip')||'';if(address){try{headers.set('x-haven-gateway-client',signGatewayClient({address,origin,method:req.method,path:req.nextUrl.pathname},process.env.SESSION_KEY!));}catch{/* An invalid client address retains transport-based limits. */}}
 if(['v1/inquiry-session','v1/guest-inquiries','v1/inquiries'].includes(path.join('/'))){try{headers.set('x-haven-inquiry-client',signInquiryClient({address:req.headers.get('x-real-ip')||'',origin,method:req.method,path:req.nextUrl.pathname},process.env.SESSION_KEY!));}catch{return Response.json({error:{code:'CLIENT_CONTEXT_UNAVAILABLE',message:'The inquiry service is temporarily unavailable. Please try again.',requestId}},{status:503});}}

 try{const response=await fetch((process.env.API_INTERNAL_URL||'http://api:4000')+'/api/'+path.map(encodeURIComponent).join('/')+req.nextUrl.search,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:await req.arrayBuffer()}:{}),redirect:'manual',cache:'no-store',signal:AbortSignal.timeout(path.includes('media')?120000:30000)});const outgoing=new Headers();for(const key of ['content-type','location','cache-control','x-request-id','content-disposition','content-range','accept-ranges','content-length','content-security-policy']){const value=response.headers.get(key);if(value)outgoing.set(key,value);}for(const value of response.headers.getSetCookie())outgoing.append('set-cookie',value);const json=response.headers.get('content-type')?.includes('json');const body=json&&![204,205,304].includes(response.status)?await response.arrayBuffer():response.body;if(json)outgoing.delete('content-length');return new Response(body,{status:response.status,headers:outgoing});}catch{return Response.json({error:{code:'SERVICE_UNAVAILABLE',message:'The service is temporarily unavailable. Please try again.',requestId}},{status:503,headers:{'X-Request-Id':requestId}});}
}
export {forward as GET,forward as POST,forward as PUT,forward as PATCH,forward as DELETE};
