import {Injectable,HttpException} from '@nestjs/common';
import {createCipheriv,createDecipheriv,randomBytes,createHash} from 'node:crypto';
import {createRemoteJWKSet,jwtVerify} from 'jose';
import {pool,transaction,type Actor} from '@haven/database';
import {config} from '@haven/config';
import {requiresStaffMfa} from '../identity/mfa-policy.js';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
export const env=config();
export function fail(status:number,message:string,code='INVALID_REQUEST'):never{throw new HttpException({code,message},status);}
export function encrypt(value:unknown){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',Buffer.from(env.SESSION_KEY,'hex'),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64url');}
export function decrypt<T>(value:string):T{const b=Buffer.from(value,'base64url');const decipher=createDecipheriv('aes-256-gcm',Buffer.from(env.SESSION_KEY,'hex'),b.subarray(0,12));decipher.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(b.subarray(28)),decipher.final()]).toString());}
export function cookie(req:FastifyRequest,name:string){return req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1);}
const jwks=createRemoteJWKSet(new URL(env.OIDC_INTERNAL_URL+'/protocol/openid-connect/certs'));
@Injectable()
export class Identity{
 async actor(req:FastifyRequest,required:string[]=[]):Promise<Actor>{const token=cookie(req,'haven_session');if(!token)fail(401,'Sign in to continue','AUTH_REQUIRED');const r=await pool.query('SELECT s.*,p.state FROM sessions s JOIN profiles p ON p.id=s.user_id WHERE s.id=$1 AND s.expires_at>now()',[token]);if(!r.rowCount||r.rows[0].state!=='active')fail(401,'Your session has expired. Please sign in again.','SESSION_EXPIRED');let tokens=decrypt<{access_token:string;refresh_token:string}>(r.rows[0].encrypted_tokens);let payload;
 try{payload=(await jwtVerify(tokens.access_token,jwks,{issuer:env.OIDC_ISSUER,audience:env.OIDC_CLIENT_ID})).payload;}catch{const refresh=await fetch(env.OIDC_INTERNAL_URL+'/protocol/openid-connect/token',{method:'POST',body:new URLSearchParams({grant_type:'refresh_token',refresh_token:tokens.refresh_token,client_id:env.OIDC_CLIENT_ID})});if(!refresh.ok){await pool.query('DELETE FROM sessions WHERE id=$1',[token]);fail(401,'Your session has expired. Please sign in again.','SESSION_EXPIRED');}tokens=await refresh.json() as typeof tokens;try{payload=(await jwtVerify(tokens.access_token,jwks,{issuer:env.OIDC_ISSUER,audience:env.OIDC_CLIENT_ID})).payload;}catch{fail(401,'Invalid identity session');}await pool.query('UPDATE sessions SET encrypted_tokens=$2 WHERE id=$1',[token,encrypt(tokens)]);}
 if(payload.sub!==undefined){const profile=await pool.query('SELECT subject FROM profiles WHERE id=$1',[r.rows[0].user_id]);if(profile.rows[0].subject!==payload.sub)fail(401,'Invalid identity session');}
 const memberships=await pool.query("SELECT organization_id,role FROM memberships WHERE user_id=$1 AND status='active' ORDER BY organization_id NULLS LAST,role",[r.rows[0].user_id]);const selected=req.headers['x-organization-id'];if(selected!==undefined&&(typeof selected!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(selected)))fail(400,'Invalid organization selection');const orgId=selected||memberships.rows.find(x=>x.organization_id)?.organization_id||null;if(selected&&!memberships.rows.some(x=>x.organization_id===selected))fail(403,'This organization is not assigned to you','FORBIDDEN');const roles=memberships.rows.filter(x=>x.organization_id===null||x.organization_id===orgId).map(x=>x.role);if(requiresStaffMfa(env.NODE_ENV,roles,payload.acr))fail(403,'Staff sign-in requires multi-factor authentication','MFA_REQUIRED');if(required.length&&!required.some(x=>roles.includes(x)))fail(403,'You do not have permission for this action','FORBIDDEN');return{id:r.rows[0].user_id,orgId,roles};}
}
export async function idempotent<T>(c:pg.PoolClient,actor:Actor,req:FastifyRequest,body:unknown,work:()=>Promise<T>):Promise<T>{const key=req.headers['idempotency-key'];if(typeof key!=='string'||key.length<8||key.length>100)fail(400,'A valid Idempotency-Key is required');const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)])):value;const hash=createHash('sha256').update(JSON.stringify({method:req.method,url:req.url,organizationId:actor.orgId,body:canonical(body)})).digest('hex');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[actor.id+key]);const existing=await c.query('SELECT * FROM idempotency WHERE actor_id=$1 AND key=$2',[actor.id,key]);if(existing.rowCount){if(existing.rows[0].request_hash!==hash)fail(409,'This request key was already used with different data','IDEMPOTENCY_CONFLICT');return existing.rows[0].response;}const result=await work();await c.query('INSERT INTO idempotency(actor_id,key,request_hash,response) VALUES($1,$2,$3,$4)',[actor.id,key,hash,JSON.stringify(result)]);return result;}
export const data=<T>(value:T,meta?:Record<string,unknown>)=>({data:value,...(meta?{meta}:{})});
export {pool,transaction};
