'use client';
import {useState,type FormEvent} from 'react';
import {sdk,profileUpdate,ApiError,type AccountProfile} from '@haven/contracts';
import {ErrorBox} from '@haven/ui';
export function ProfileSettings({profile,onSaved,onExpired}:{profile:AccountProfile;onSaved:(profile:AccountProfile)=>void;onExpired:()=>void}){
 const [draft,setDraft]=useState({displayName:profile.displayName,locale:profile.locale==='en-US'?'en-US':'en-GB',version:profile.version}),[fields,setFields]=useState<Record<string,string[]>>({}),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false);
 function reset(value:AccountProfile){setDraft({displayName:value.displayName,locale:value.locale==='en-US'?'en-US':'en-GB',version:value.version});setFields({});setConflict(false);setError('');}
 async function reload(){setBusy(true);try{const result=await sdk.IdentityController_me({});reset(result.data);onSaved(result.data);}catch(e){if(e instanceof ApiError&&e.status===401)onExpired();else setError(e instanceof Error?e.message:'Your profile could not be loaded.');}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();setSaved('');setError('');const parsed=profileUpdate.safeParse(draft);if(!parsed.success){setFields(parsed.error.flatten().fieldErrors);return;}setFields({});setBusy(true);
  try{const result=await sdk.ProfileController_update({params:{id:profile.id},body:parsed.data});reset(result.data);onSaved(result.data);setSaved('Your profile has been saved.');}
  catch(e){if(e instanceof ApiError){if(e.status===401){onExpired();return;}setFields(e.fieldErrors);setConflict(e.code==='PROFILE_CHANGED');}setError(e instanceof Error?e.message:'Your profile could not be saved.');}finally{setBusy(false);}
 }
 return <section className="account-profile" aria-labelledby="profile-heading"><h2 id="profile-heading">Your profile</h2><p>Your display name is used in your account. Sign-in credentials and contact verification are managed by the secure sign-in service.</p>{error&&<ErrorBox message={error}/>}<p role="status">{saved}</p><form className="field-form" noValidate onSubmit={submit}>
  <label className="field"><span>Display name</span><input name="displayName" aria-label="Display name" value={draft.displayName} maxLength={80} disabled={busy} aria-invalid={!!fields.displayName?.length} aria-describedby={fields.displayName?.length?'profile-name-error':undefined} onChange={event=>setDraft(value=>({...value,displayName:event.target.value}))}/>{fields.displayName?.length&&<span id="profile-name-error" role="alert">{fields.displayName.join(' ')}</span>}</label>
  <label className="field"><span>Account date format</span><select aria-label="Account date format" value={draft.locale} disabled={busy} aria-invalid={!!fields.locale?.length} onChange={event=>setDraft(value=>({...value,locale:event.target.value}))}><option value="en-GB">English (UK)</option><option value="en-US">English (US)</option></select>{fields.locale?.length&&<span role="alert">{fields.locale.join(' ')}</span>}</label>
  <button className="button" disabled={busy||conflict}>{busy?'Saving…':'Save profile'}</button>{conflict&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void reload()}>Reload current profile</button>}
 </form><h3>Sign-in and contact</h3><dl className="facts-table"><div><dt>Email</dt><dd>{profile.email||'Not provided'}</dd></div><div><dt>Verification</dt><dd>{profile.emailVerified===null?'Verification status unavailable. Sign in again to refresh.':profile.emailVerified?'Email verified by the sign-in service':'Email not yet verified'}</dd></div><div><dt>Contact status checked</dt><dd>{profile.contactSyncedAt?new Date(profile.contactSyncedAt).toLocaleString(draft.locale,{timeZone:'UTC'})+' UTC':'Not yet confirmed'}</dd></div></dl><div className="account-links"><a href={profile.identityAccountUrl} target="_blank" rel="noopener noreferrer">Manage sign-in and contact details</a><a href="/api/v1/auth/login?prompt=login&returnTo=%2Faccount%2Fprofile">Recover sign-in access</a></div><p className="fine-print">Contact details, passwords and verification are updated with the sign-in service. To recover access, choose “Forgot password?” on its sign-in screen.</p></section>;
}
