'use client';
import {useEffect,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {sdk} from '@haven/contracts';
export function ActivityConsent({listingId,version,accountId,signIn}:{listingId:string;version:number;accountId?:string;signIn:()=>void}){
 const [status,setStatus]=useState('No optional activity is recorded without your permission.'),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pendingChoice,setPendingChoice]=useState<boolean|null>(null);const eventId=useRef(crypto.randomUUID()),keys=useRef(new Map<string,string>());const q=useQuery({queryKey:['analytics-consent',accountId],enabled:!!accountId,retry:false,queryFn:()=>sdk.DiscoveryEventsController_consent({})});const allowed=q.data?.data.enabled||false;
 useEffect(()=>{if(!accountId||!allowed){setStatus('No optional activity is recorded without your permission.');return;}const controller=new AbortController();setStatus('Recording your permitted activity…');sdk.DiscoveryEventsController_view({params:{id:listingId},body:{eventId:eventId.current,version,consent:true},signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setStatus(result.data.counted?'Your permitted activity was recorded.':'This property was already counted for your account today.');}).catch(()=>{if(!controller.signal.aborted)setStatus('Activity could not be recorded. Your browsing is still available.');});return()=>controller.abort();},[accountId,allowed,listingId,version,retry]);
 return <section className="detail-section activity-consent"><h2>Help improve recommendations</h2><p>Optional property impressions, views, saves, inquiry, viewing and quote request counts improve recommendations and aggregate reports. Messages, contact details, documents and private addresses are excluded. Counts are deduplicated; turning this off stops future optional signals and retains earlier anonymous aggregate counts.</p>{accountId?<label className="checkbox-field"><input aria-label="Allow my property activity to contribute to recommendations" type="checkbox" checked={pendingChoice??allowed} disabled={busy||q.isPending||q.isError} onChange={async e=>{const enabled=e.target.checked,body={enabled,version:q.data!.data.version},fingerprint=JSON.stringify(body);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());setPendingChoice(enabled);setBusy(true);setError('');try{await sdk.DiscoveryEventsController_changeConsent({body,headers:{'Idempotency-Key':keys.current.get(fingerprint)!}});await q.refetch();}catch(e){setError(e instanceof Error?e.message:'Consent could not be saved.');}finally{setPendingChoice(null);setBusy(false);}}}/>Allow my property views to contribute to rankings</label>:<button className="button secondary small" onClick={signIn}>Sign in to choose activity sharing</button>}{q.isError&&accountId&&<p role="alert">Activity preference could not load. <button className="text-link" onClick={()=>q.refetch()}>Retry preference</button></p>}{error&&<p role="alert">{error}</p>}<p className="fine-print" role="status">{status}</p>{allowed&&status.startsWith('Activity could not')&&<button className="text-link" onClick={()=>setRetry(value=>value+1)}>Retry activity recording</button>}</section>;
}
