'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk} from '@haven/contracts';
export function ActivityConsent({listingId,version,accountId,signIn}:{listingId:string;version:number;accountId?:string;signIn:()=>void}){
 const [allowed,setAllowed]=useState(false),[status,setStatus]=useState('No activity is recorded without your permission.'),[retry,setRetry]=useState(0);const eventId=useRef(crypto.randomUUID());const key='haven.activity-consent:'+accountId;
 useEffect(()=>{if(!accountId)return;try{setAllowed(localStorage.getItem(key)==='true');}catch{/* Consent defaults to off when storage is unavailable. */}},[accountId,key]);
 useEffect(()=>{if(!accountId||!allowed){setStatus('No activity is recorded without your permission.');return;}const controller=new AbortController();setStatus('Recording your permitted activity…');sdk.DiscoveryEventsController_view({params:{id:listingId},body:{eventId:eventId.current,version,consent:true},signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setStatus(result.data.counted?'Your permitted activity was recorded.':'This property was already counted for your account today.');}).catch(()=>{if(!controller.signal.aborted)setStatus('Activity could not be recorded. Your browsing is still available.');});return()=>controller.abort();},[accountId,allowed,listingId,version,retry]);
 return <section className="detail-section activity-consent"><h2>Help improve recommendations</h2><p>With your permission, a signed-in property view can contribute to the public activity ranking. Turning this off stops future signals. Messages, contact details and private addresses are excluded.</p>{accountId?<label className="checkbox-field"><input type="checkbox" checked={allowed} onChange={event=>{setAllowed(event.target.checked);try{localStorage.setItem(key,String(event.target.checked));}catch{/* The current choice still applies to this visit. */}}}/>Allow my property views to contribute to rankings</label>:<button className="button secondary small" onClick={signIn}>Sign in to choose activity sharing</button>}<p className="fine-print" role="status">{status}</p>{allowed&&status.startsWith('Activity could not')&&<button className="text-link" onClick={()=>setRetry(value=>value+1)}>Retry activity recording</button>}</section>;
}
