'use client';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {sdk,ApiError,type Listing} from '@haven/contracts';
import {Spinner,Empty,ErrorBox} from '@haven/ui';
function useHistory(accountId?:string){return useQuery({queryKey:['browsing-history',accountId],queryFn:({signal})=>sdk.BrowsingHistoryController_read({signal}),enabled:!!accountId,retry:false});}
export function UnavailableProperty({id,title,onRemove}:{id:string;title:string;onRemove:()=>void}){return <article className="record-row" data-unavailable-id={id}><div><h3>{title}</h3><p>This property is no longer publicly available. Its private details cannot be opened.</p></div><button className="button secondary small" onClick={onRemove}>Remove</button></article>;}
export function BrowsingHistory({accountId,card}:{accountId:string;card:(listing:Listing)=>React.ReactNode}){
 const history=useHistory(accountId),client=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[optimisticEnabled,setOptimisticEnabled]=useState<boolean>();
 async function change(work:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await work();await client.invalidateQueries({queryKey:['browsing-history',accountId]});setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Browsing history could not be changed.');if(e instanceof ApiError&&e.status===401)client.clear();else if(e instanceof ApiError&&e.status===409)await client.invalidateQueries({queryKey:['browsing-history',accountId]});}finally{setBusy(false);setOptimisticEnabled(undefined);}}
 if(history.isPending)return <Spinner/>;if(history.isError)return <ErrorBox message={history.error.message} retry={()=>history.refetch()}/>;const value=history.data.data;
 return <section aria-labelledby="history-heading"><h2 id="history-heading">Browsing history</h2><p>Keep up to 100 recent property visits in your account. History is private and separate from sharing views for public rankings. Turning it off stops new visits; remove or clear existing visits below.</p>{error&&<ErrorBox message={error}/>}<p role="status">{notice}</p><label className="checkbox-field"><input type="checkbox" checked={optimisticEnabled??value.enabled} disabled={busy} onChange={event=>{const enabled=event.target.checked;setOptimisticEnabled(enabled);void change(()=>sdk.BrowsingHistoryController_preferences({body:{version:value.version,enabled}}),enabled?'Browsing history enabled.':'Browsing history disabled.');}}/>Keep my browsing history</label><button className="button secondary" disabled={busy||!value.entries.length} onClick={()=>void change(()=>sdk.BrowsingHistoryController_clear({body:{version:value.version}}),'Your browsing history has been cleared.')}>Clear browsing history</button>
 {!value.entries.length?<Empty title="No browsing history" description={value.enabled?'Property visits will appear here when you browse.':'Enable history to keep future property visits.'}/>:<div className="listing-grid">{value.entries.map(entry=><div key={entry.listing.id} data-history-id={entry.listing.id}>{entry.listing.available?card(entry.listing):<UnavailableProperty id={entry.listing.id} title={entry.listing.title} onRemove={()=>void change(()=>sdk.BrowsingHistoryController_remove({params:{id:entry.listing.id},body:{version:value.version}}),'Visit removed from your browsing history.')}/>}<p className="fine-print">Visited {new Date(entry.viewedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</p>{entry.listing.available&&<button className="button secondary small" disabled={busy} onClick={()=>void change(()=>sdk.BrowsingHistoryController_remove({params:{id:entry.listing.id},body:{version:value.version}}),'Visit removed from your browsing history.')}>Remove visit</button>}</div>)}</div>}
 </section>;
}
export function HistoryConsent({accountId,listingId,listingVersion,signIn}:{accountId?:string;listingId:string;listingVersion:number;signIn:()=>void}){
 const history=useHistory(accountId),client=useQueryClient(),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[optimisticEnabled,setOptimisticEnabled]=useState<boolean>(),[retry,setRetry]=useState(0),attempted=useRef(new Set<string>()),visitKey=(accountId||'guest')+':'+listingId,currentVisit=useRef(visitKey);currentVisit.current=visitKey;
 useEffect(()=>{if(!accountId||!history.data?.data.enabled||attempted.current.has(visitKey))return;attempted.current.add(visitKey);setStatus('Saving this visit to your private history…');sdk.BrowsingHistoryController_record({params:{id:listingId},body:{version:history.data.data.version,listingVersion}}).then(async()=>{await client.invalidateQueries({queryKey:['browsing-history',accountId]});if(currentVisit.current===visitKey)setStatus('This visit is in your browsing history.');}).catch(async e=>{if(e instanceof ApiError&&e.status===409)await client.invalidateQueries({queryKey:['browsing-history',accountId]});if(currentVisit.current===visitKey)setStatus(e instanceof Error?e.message:'This visit could not be saved.');});},[accountId,history.data?.data.enabled,listingId,listingVersion,client,visitKey,retry]);
 async function choose(enabled:boolean){if(!history.data)return;setOptimisticEnabled(enabled);setBusy(true);setStatus('');try{await sdk.BrowsingHistoryController_preferences({body:{version:history.data.data.version,enabled}});await client.invalidateQueries({queryKey:['browsing-history',accountId]});if(!enabled)setStatus('New visits will not be saved. Existing history is kept until you remove it.');}catch(e){setStatus(e instanceof Error?e.message:'History preferences could not be saved.');if(e instanceof ApiError&&e.status===409)await client.invalidateQueries({queryKey:['browsing-history',accountId]});}finally{setBusy(false);setOptimisticEnabled(undefined);}}
 return <section className="detail-section"><h2>Your browsing history</h2><p>With your permission, keep recent property visits privately in your account. You can turn history off, remove visits or clear it at any time.</p>{!accountId?<button className="button secondary small" onClick={signIn}>Sign in to choose browsing history</button>:history.isPending?<Spinner/>:history.isError?<ErrorBox message={history.error.message} retry={()=>history.refetch()}/>:<label className="checkbox-field"><input type="checkbox" checked={optimisticEnabled??history.data.data.enabled} disabled={busy} onChange={event=>void choose(event.target.checked)}/>Keep my browsing history</label>}<p role="status">{status}</p>{accountId&&<a className="text-link" href="/account/history">Manage browsing history</a>}{status&&!status.startsWith('This visit is')&&!status.startsWith('Saving')&&history.data?.data.enabled&&<button className="text-link" onClick={()=>{attempted.current.delete(visitKey);setRetry(value=>value+1);}}>Retry saving this visit</button>}</section>;
}
