'use client';
import type {ReactNode} from 'react';
import {useQuery} from '@tanstack/react-query';
import {sdk,type Listing} from '@haven/contracts';
import {Spinner,ErrorBox,Empty} from '@haven/ui';
import {ArrowUpRight} from 'lucide-react';
export function HomeDiscoverySections({city,card,developmentCard}:{city:{slug:string;name:string};card:(listing:Listing)=>ReactNode;developmentCard:(development:any)=>ReactNode}){
 const result=useQuery({queryKey:['public','/discovery/home?city='+city.slug],queryFn:({signal})=>sdk.HomeDiscoveryController_home({query:{city:city.slug},signal})});
 const saleRank='/'+city.slug+'/rankings?transaction=sale&segment=residential&period=7d',rentRank='/'+city.slug+'/rankings?transaction=rent&segment=residential&period=7d';
 function feed(id:string,title:string,copy:string,href:string,records:any[],render:(record:any)=>ReactNode,curated=false){if(curated&&!records.length)return null;return <section className="home-section shell" data-home-feed={id} aria-label={title}><div className="section-heading"><div><span className="eyebrow">{curated?'CURATED FOR YOUR CITY':'MORE PLACES TO START'}</span><h2>{title}<span className="accent-dot">.</span></h2><p>{copy}</p></div><a href={href} className="text-link">Explore {id.includes('development')?'new homes':id==='rentals'?'rentals':'homes for sale'}<ArrowUpRight size={17}/></a></div>{records.length?<div className="listing-grid">{records.map(render)}</div>:<Empty title={'No '+(id==='rentals'?'rental':'new-home')+' recommendations in '+city.name+' yet'} description="Explore this category for current availability or choose another city."><a className="button secondary" href={href}>Browse this category</a></Empty>}</section>;}
 return <><nav className="home-ranking-shortcuts shell" aria-label="Property ranking shortcuts"><div><span className="eyebrow">WHAT TO EXPLORE NEXT</span><h2>Explore the rankings</h2><p>See eligible properties with a clear scoring rule.</p></div><a className="button secondary" href={saleRank}>Homes for sale rankings<ArrowUpRight size={17}/></a><a className="button secondary" href={rentRank}>Rental rankings<ArrowUpRight size={17}/></a><a className="text-link" href={'/'+city.slug+'/map'}>Browse the property map<ArrowUpRight size={17}/></a></nav>{result.isPending?<section className="shell"><Spinner/></section>:result.isError?<section className="home-section shell"><ErrorBox message={result.error.message} retry={()=>result.refetch()}/></section>:<>{result.data.data.sections.map(s=><section className="home-section shell" data-home-feed={'editorial-'+s.id} key={s.id} aria-label={s.title}><div className="section-heading"><div><span className="eyebrow">{s.categoryLabel}</span><h2>{s.title}</h2><p>{s.copy}</p></div><a className="text-link" href={s.url}>Explore {s.categoryLabel}<ArrowUpRight size={17}/></a></div><div className="listing-grid">{s.category==='new-homes'?s.developments.map(developmentCard):s.listings.map(card)}</div></section>)}{feed('curated-resale','Selected homes for sale','Published homes with current editorial placements. Paid placements are labeled.', '/'+city.slug+'/buy',result.data.data.curatedResale,card,true)}{feed('curated-developments','Selected new developments','Current selections in '+city.name+'. Paid placements are labeled.','/'+city.slug+'/new-homes',result.data.data.curatedDevelopments,developmentCard,true)}{feed('rentals','Rentals for your next move','Recommended homes to rent in '+city.name+'. Compare amounts with their rental periods.','/'+city.slug+'/rent',result.data.data.rentals,card)}</>}</>;
}
