'use client';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {sdk,ApiError} from '@haven/contracts';
import {Spinner,ErrorBox,Empty,Badge} from '@haven/ui';
const labels={queued:'Scheduled',processing:'Checking provider acceptance',accepted:'Accepted by email provider',in_app:'Added to your notifications',failed:'Email acceptance unconfirmed · retry pending',cancelled:'Cancelled'};
export function NotificationSettings({accountId}:{accountId:string}){
 const client=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const preferences=useQuery({queryKey:['notification-preferences',accountId],queryFn:({signal})=>sdk.NotificationsController_preferences({signal})});
 const notifications=useQuery({queryKey:['notifications',accountId],queryFn:({signal})=>sdk.NotificationsController_read({signal})});
 const deliveries=useQuery({queryKey:['alert-deliveries',accountId],queryFn:({signal})=>sdk.NotificationsController_deliveries({signal}),refetchInterval:10000});
 async function refresh(){await Promise.all([preferences.refetch(),notifications.refetch(),deliveries.refetch()]);}
 async function mutate(work:()=>Promise<unknown>,success:string){setBusy(true);setError('');setNotice('');try{await work();await refresh();setNotice(success);}catch(e){setError(e instanceof Error?e.message:'Notifications could not be updated.');if(e instanceof ApiError&&e.status===401)client.clear();else await refresh();}finally{setBusy(false);}}
 function preference(channel:'emailEnabled'|'inAppEnabled',enabled:boolean){if(!preferences.data)return;const current=preferences.data;client.setQueryData(['notification-preferences',accountId],{data:{...current.data,[channel]:enabled}});void mutate(()=>sdk.NotificationsController_update({body:{...current.data,[channel]:enabled}}),'Alert preferences saved.');}
 if(preferences.isPending||notifications.isPending||deliveries.isPending)return <Spinner/>;
 const failure=preferences.error||notifications.error||deliveries.error;if(failure)return <ErrorBox message={failure.message} retry={()=>void refresh()}/>;
 return <section aria-labelledby="notification-heading"><h2 id="notification-heading">Notifications and alerts</h2><p>Choose optional updates for your saved searches. Both channels start off. Daily digests are scheduled at midnight UTC; weekly digests are scheduled on Monday at midnight UTC.</p>{error&&<ErrorBox message={error} retry={()=>void refresh()}/>}<p role="status">{notice}</p><fieldset disabled={busy} className="field-form"><legend>Optional saved-search alerts</legend><label className="checkbox-field"><input type="checkbox" checked={preferences.data!.data.emailEnabled} onChange={e=>preference('emailEnabled',e.target.checked)}/>Email alerts</label><label className="checkbox-field"><input type="checkbox" checked={preferences.data!.data.inAppEnabled} onChange={e=>preference('inAppEnabled',e.target.checked)}/>In-app alerts</label></fieldset><p className="fine-print">Email alerts require a verified email from the sign-in service. Verify your address in <a href="/account/profile">your profile</a>, then sign in again. Necessary inquiry confirmations are separate from optional alerts.</p><a href="/account/searches">Manage or pause saved searches</a><h3>Your notifications</h3>{notifications.data!.data.length?<div className="record-list">{notifications.data!.data.map(row=><article className="record-row" key={row.id}><div><h4>{row.title}</h4><p>{row.body}</p><time dateTime={row.createdAt}>{row.createdAt.slice(0,16).replace('T',' ')} UTC</time>{row.link&&<p><a href={row.link}>Review saved searches</a></p>}</div><Badge>{row.readAt?'Read':'Unread'}</Badge>{!row.readAt&&<button className="button secondary small" disabled={busy} onClick={()=>void mutate(()=>sdk.NotificationsController_markRead({params:{id:row.id},body:{version:row.version}}),'Notification marked as read.')}>Mark as read</button>}</article>)}</div>:<Empty title="No notifications yet" description="Your updates will appear here."/>}<h3>Saved-search delivery history</h3><p className="fine-print">Provider acceptance confirms that the email provider accepted a message. It does not confirm inbox delivery or that you read it.</p>{deliveries.data!.data.length?<div className="record-list">{deliveries.data!.data.map(row=><article className="record-row" key={row.id}><div><h4>{labels[row.status]}</h4><p>Scheduled: {row.dueAt.slice(0,16).replace('T',' ')} UTC · Attempts: {row.attempts}</p>{row.acceptanceRecordedAt&&<p>Acceptance recorded: {row.acceptanceRecordedAt.slice(0,16).replace('T',' ')} UTC</p>}</div>{row.status==='failed'&&<button className="button secondary small" disabled={busy} onClick={()=>void mutate(()=>sdk.NotificationsController_retry({params:{id:row.id},body:{version:row.version}}),'Alert queued for another acceptance check.')}>Retry alert</button>}</article>)}</div>:<Empty title="No saved-search deliveries yet" description="Enable a channel and save a search to receive new matching homes."/>}</section>;
}
