import {publicRequestKey} from './public-query';
import {cache} from 'react';
import {cookies,headers} from 'next/headers';
import {signGatewayClient} from '@haven/config';
import {notFound,redirect} from 'next/navigation';
import {publicNames} from './seo';
export const pageSource=cache(async(route:string,query='')=>{const path=route?route.split('/'):[],jar=await cookies(),incoming=await headers(),preferred=jar.get('haven_city')?.value||'bj',base=(process.env.API_INTERNAL_URL||'http://api:4000')+'/api/v1';const gatewayHeaders=(endpoint:string)=>{const origin=process.env.PUBLIC_WEB_URL||'http://localhost:8088',result:Record<string,string>={'x-bff-origin':origin},address=incoming.get('x-real-ip')||'';if(address)try{result['x-haven-gateway-client']=signGatewayClient({address,origin,method:'GET',path:'/api/v1'+endpoint.split('?')[0]},process.env.SESSION_KEY!);}catch{/* Preserve bounded transport fallback. */}return result;};let cities:any[]|null=null;try{const r=await fetch(base+'/cities',{headers:gatewayHeaders('/cities'),cache:'no-store',signal:AbortSignal.timeout(8000)});if(r.ok)cities=(await r.json()).data;}catch{/* Missing source is displayed as a retryable state and noindexed. */}
 const fallback=cities?.some(c=>c.slug==='bj')?'bj':cities?.[0]?.slug||'bj';if(!path.length)redirect('/'+(cities?.some(c=>c.slug===preferred)?preferred:fallback));const privateRoot=['account','tenant'].includes(path[0]),selected=privateRoot?(cities?.some(c=>c.slug===preferred)?preferred:fallback):path[0];const city=cities?.find(c=>c.slug===selected)||{id:'',slug:selected,name:selected,currency:'',timezone:''};if(!privateRoot&&(cities&&!cities.some(c=>c.slug===selected)||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(selected)))notFound();const section=privateRoot?path[0]:path[1]||'home',detail=privateRoot?path[1]:path[2],privatePage=privateRoot||['account','tenant','ops'].includes(section);if(!privatePage&&(path.length>3||section!=='home'&&!publicNames[section]))notFound();
 const endpoints:Record<string,string>={home:'/discovery/home?city='+selected,buy:'/listings?city='+selected+'&transaction=sale&segment=residential',rent:'/listings?city='+selected+'&transaction=rent&segment=residential',commercial:'/listings?city='+selected+'&segment=commercial','new-homes':'/developments?city='+selected,communities:'/communities?city='+selected,agents:'/agents?city='+selected,renovation:'/renovation/providers?city='+selected,search:'/listings?city='+selected},details:Record<string,string>={buy:'/listings/',rent:'/listings/',commercial:'/listings/','new-homes':'/developments/',communities:'/communities/',agents:'/agents/',renovation:'/renovation/providers/'};
 if(detail&&!privatePage&&!details[section]&&!(section==='tools'&&detail==='mortgage'))notFound();let initial:any=null,error:string|null=cities?null:'The location service is temporarily unavailable. Please retry.';let endpoint=detail&&details[section]?details[section]+encodeURIComponent(detail)+'?city='+selected:endpoints[section];if(endpoint&&query&&!detail&&['buy','rent','commercial','search','communities','new-homes','agents','renovation'].includes(section))endpoint+='&'+query;if(endpoint){try{const r=await fetch(base+endpoint,{headers:gatewayHeaders(endpoint),cache:'no-store',signal:AbortSignal.timeout(8000)});if(r.status===404)notFound();const result=await r.json();if(!r.ok)error=result.error?.message||'The service is temporarily unavailable';else initial=result;}catch(e){if(e instanceof Error&&e.message.includes('NEXT_HTTP_ERROR_FALLBACK'))throw e;error='The service is temporarily unavailable. Please try again.';}}return {city,section,detail,initial,initialEndpoint:publicRequestKey(endpoint),error,privatePage};});
