'use client';
import {useEffect,useRef,useState} from 'react';
type Hotspot={targetId:string;label:string;yaw:number;pitch:number};
export function Panorama({scene,onScene}:{scene:{title:string;url:string;hotspots:Hotspot[]};onScene:(id:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),frame=useRef<HTMLDivElement>(null),draw=useRef<()=>void>(()=>{});
 const [view,setView]=useState({yaw:0,pitch:0,fov:70}),[error,setError]=useState(''),[message,setMessage]=useState('');
 const camera=useRef(view),drag=useRef<{x:number;y:number}|null>(null);camera.current=view;
 useEffect(()=>{draw.current();},[view]);
 useEffect(()=>{
  const element=canvas.current;if(!element)return;
  setError('');setView({yaw:0,pitch:0,fov:70});
  const gl=element.getContext('webgl',{alpha:false,antialias:true});
  if(!gl){setError('Interactive rendering is unavailable. The panorama image is shown below.');return;}
  const shader=(type:number,source:string)=>{const result=gl.createShader(type)!;gl.shaderSource(result,source);gl.compileShader(result);if(!gl.getShaderParameter(result,gl.COMPILE_STATUS))throw new Error('Panorama shader compilation failed');return result;};
  let program:WebGLProgram|undefined,texture:WebGLTexture|undefined,buffer:WebGLBuffer|undefined,observer:ResizeObserver|undefined,alive=true;
  const image=new Image();
  try{
   program=gl.createProgram()!;
   const vertex=shader(gl.VERTEX_SHADER,'attribute vec2 position;varying vec2 uv;void main(){uv=position;gl_Position=vec4(position,0.,1.);}');
   const fragment=shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec2 uv;uniform sampler2D panorama;uniform vec3 camera;uniform float aspect;void main(){float f=tan(radians(camera.z)*0.5);vec3 ray=normalize(vec3(uv.x*aspect*f,uv.y*f,1.));float p=radians(camera.y),y=radians(camera.x);ray=vec3(ray.x,ray.y*cos(p)+ray.z*sin(p),ray.z*cos(p)-ray.y*sin(p));ray=vec3(ray.x*cos(y)+ray.z*sin(y),ray.y,ray.z*cos(y)-ray.x*sin(y));vec2 point=vec2(atan(ray.x,ray.z)/6.2831853+0.5,asin(clamp(ray.y,-1.,1.))/3.1415926+0.5);gl_FragColor=texture2D(panorama,point);}`);
   gl.attachShader(program,vertex);gl.attachShader(program,fragment);gl.linkProgram(program);gl.deleteShader(vertex);gl.deleteShader(fragment);
   if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Panorama renderer initialization failed');
   gl.useProgram(program);buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);
   const position=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,2,gl.FLOAT,false,0,0);
   texture=gl.createTexture()!;gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
   const cameraUniform=gl.getUniformLocation(program,'camera'),aspectUniform=gl.getUniformLocation(program,'aspect');
   image.onload=()=>{if(!alive)return;gl.bindTexture(gl.TEXTURE_2D,texture!);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,1);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,image);draw.current=()=>{const ratio=Math.min(devicePixelRatio||1,2),width=Math.max(1,Math.round(element.clientWidth*ratio)),height=Math.max(1,Math.round(element.clientHeight*ratio));element.width=width;element.height=height;gl.viewport(0,0,width,height);gl.uniform3f(cameraUniform,camera.current.yaw,camera.current.pitch,camera.current.fov);gl.uniform1f(aspectUniform,width/height);gl.drawArrays(gl.TRIANGLES,0,6);};observer=new ResizeObserver(()=>draw.current());observer.observe(element);draw.current();};
   image.onerror=()=>{if(alive)setError('The panorama could not be loaded. Choose another scene or try again.');};image.src=scene.url;
  }catch{setError('Interactive rendering is unavailable. The panorama image is shown below.');}
  return()=>{alive=false;image.onload=null;image.onerror=null;observer?.disconnect();draw.current=()=>{};if(buffer)gl.deleteBuffer(buffer);if(texture)gl.deleteTexture(texture);if(program)gl.deleteProgram(program);};
 },[scene.url]);
 const turn=(yaw:number,pitch:number)=>setView(v=>({...v,yaw:(v.yaw+yaw)%360,pitch:Math.max(-80,Math.min(80,v.pitch+pitch))}));
 return <div ref={frame} className="panorama-frame"><p className="fine-print">Drag to look around. Arrow keys rotate the view. Use the zoom buttons to change the field of view.</p>{error?<><p role="status">{error}</p><img src={scene.url} alt={scene.title+' panoramic image'} className="panorama-fallback"/></>:<div className="panorama-surface"><canvas ref={canvas} aria-label={'360 degree view: '+scene.title} role="img" tabIndex={0} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();turn(e.key==='ArrowLeft'?-10:e.key==='ArrowRight'?10:0,e.key==='ArrowUp'?10:e.key==='ArrowDown'?-10:0);}}} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current){turn((drag.current.x-e.clientX)*0.25,(e.clientY-drag.current.y)*0.25);drag.current={x:e.clientX,y:e.clientY};}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>{scene.hotspots.map((h,index)=>{const yaw=((h.yaw-view.yaw+540)%360)-180,pitch=h.pitch-view.pitch;if(Math.abs(yaw)>view.fov||Math.abs(pitch)>45)return null;return <button key={index} className="panorama-hotspot" style={{left:50+yaw/view.fov*50+'%',top:50-pitch/90*100+'%'}} onClick={()=>onScene(h.targetId)} aria-label={'Go to '+h.label}>{h.label} →</button>;})}</div>}<div className="media-controls"><button className="button secondary small" onClick={()=>turn(-15,0)} aria-label="Turn left">←</button><button className="button secondary small" onClick={()=>turn(15,0)} aria-label="Turn right">→</button><button className="button secondary small" onClick={()=>turn(0,15)} aria-label="Look up">↑</button><button className="button secondary small" onClick={()=>turn(0,-15)} aria-label="Look down">↓</button><button className="button secondary small" onClick={()=>setView(v=>({...v,fov:Math.max(30,v.fov-10)}))} aria-label="Zoom in">+</button><button className="button secondary small" onClick={()=>setView(v=>({...v,fov:Math.min(100,v.fov+10)}))} aria-label="Zoom out">−</button><button className="button secondary small" onClick={()=>setView({yaw:0,pitch:0,fov:70})}>Reset view</button><button className="button secondary small" onClick={()=>frame.current?.requestFullscreen().catch(()=>setMessage('Full screen is unavailable in this browser.'))}>Full screen</button></div><output className="fine-print" aria-live="off">View {Math.round(view.yaw)}° / {Math.round(view.pitch)}° · Field of view {view.fov}°</output>{message&&<p role="status">{message}</p>}</div>;
}
