'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {useQuery} from '@tanstack/react-query';
import {sdk,providerFilters,providerCategory} from '@haven/contracts';
import {Dialog,ErrorBox,Empty} from '@haven/ui';
import {House} from 'lucide-react';
export function ProviderDirectoryFilters({city}:{city:{slug:string;name:string}}){const params=useSearchParams(),router=useRouter(),[error,setError]=useState(''),areas=useQuery({queryKey:['provider-areas',city.slug],queryFn:()=>sdk.DiscoveryController_districts({params:{id:city.slug}})});return <form className="provider-directory-filters" aria-label="Find service providers" key={params.toString()} onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(Array.from(new FormData(e.currentTarget)).map(([k,v])=>[k,String(v).trim()]).filter(([,v])=>v)),parsed=providerFilters.safeParse({...values,city:city.slug});if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join(' · '));return;}setError('');const query=new URLSearchParams(values);router.push('/'+city.slug+'/renovation'+(query.size?'?'+query:''));}}><label className="field"><span>Provider name or service</span><input name="text" aria-label="Provider name or service" defaultValue={params.get('text')||''} maxLength={120}/></label><label className="field"><span>Service category</span><select name="category" aria-label="Service category" defaultValue={params.get('category')||''}><option value="">All categories</option>{providerCategory.options.map(c=><option key={c}>{c}</option>)}</select></label><label className="field"><span>Provider service area</span><select key={city.slug+':'+(params.get('districtId')||'')+':'+!!areas.data} name="districtId" aria-label="Provider service area" defaultValue={params.get('districtId')||''} disabled={areas.isPending||areas.isError}><option value="">All areas in {city.name}</option>{areas.data?.data.filter(d=>d.status==='active').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="button">Search providers</button><a className="button secondary" href={'/'+city.slug+'/renovation'}>Clear provider filters</a>{areas.isError&&<ErrorBox message={areas.error.message} retry={()=>areas.refetch()}/ >}{error&&<ErrorBox message={error}/>}</form>;}
type Provider=Awaited<ReturnType<typeof sdk.DiscoveryController_provider>>['data'];
function Image({url,alt}:{url:string;alt:string}){const [failed,setFailed]=useState(false),image=useRef<HTMLImageElement>(null);useEffect(()=>{if(image.current?.complete&&!image.current.naturalWidth)setFailed(true);},[url]);return !failed?<img ref={image} src={url} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>:<div className="photo-fallback" role="img" aria-label={alt+' — image unavailable'}><House aria-hidden size={32}/><span>Portfolio image unavailable</span></div>;}
export function ProviderPortfolio({provider}:{provider:Provider}){const [selected,setSelected]=useState<number|null>(null),items=provider.portfolio.length?provider.portfolio:provider.photos.map((url,i)=>({url,alt:provider.name+' portfolio photo '+(i+1),caption:''}));const move=(offset:number)=>setSelected(i=>i===null?null:(i+offset+items.length)%items.length);return <section className="detail-section provider-public-portfolio" aria-label="Service provider portfolio"><h2>Portfolio</h2>{!items.length?<Empty title="No portfolio images supplied" description="You can still ask the provider about services or request a nonbinding quote."/>:<><p>Explore the provider’s supplied project images. Discuss your own scope and requirements with the team.</p><div className="provider-portfolio-grid">{items.map((item,i)=><figure key={item.url}><button type="button" aria-label={'Open portfolio photo '+(i+1)} onClick={()=>setSelected(i)}><Image key={item.url} url={item.url} alt={item.alt}/></button><figcaption>{item.caption||item.alt}</figcaption></figure>)}</div></>}{selected!==null&&<Dialog title={provider.name+' portfolio'} onClose={()=>setSelected(null)} onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='ArrowRight'){e.preventDefault();move(1);}}}><div className="provider-portfolio-viewer"><Image key={items[selected].url} url={items[selected].url} alt={items[selected].alt}/><p>{items[selected].caption||items[selected].alt}</p><p role="status">Photo {selected+1} of {items.length}</p><div className="dialog-actions"><button className="button secondary" disabled={items.length<2} onClick={()=>move(-1)}>Previous portfolio photo</button><button className="button secondary" disabled={items.length<2} onClick={()=>move(1)}>Next portfolio photo</button></div></div></Dialog>}</section>;}
