'use client';
import {useState,type FormEvent} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {sdk,savedSearchCreate,savedSearchUpdate,ApiError} from '@haven/contracts';
import {Dialog,Spinner,Empty,ErrorBox,Badge} from '@haven/ui';
type SavedSearch=Awaited<ReturnType<typeof sdk.SavedSearchController_read>>['data'][number];
function CityLabel({slug}:{slug?:string}){const cities=useQuery({queryKey:['cities'],queryFn:()=>sdk.DiscoveryController_cities({}),enabled:!!slug});return <>{cities.data?.data.find(city=>city.slug===slug)?.name||slug||'City needs review'}</>;}

export function SavedSearchDialog({filters,current,onClose,onSaved}:{filters:Record<string,string>;current?:SavedSearch;onClose:()=>void;onSaved:()=>void}){
 const client=useQueryClient();const [conflict,setConflict]=useState(false);const [name,setName]=useState(current?.name||''),[cadence,setCadence]=useState<'daily'|'weekly'>(current?.cadence||'weekly'),[paused,setPaused]=useState(current?.paused||false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string[]>>({});
 async function submit(event:FormEvent){event.preventDefault();setError('');const parsed=current?savedSearchUpdate.safeParse({name,cadence,filters,paused,version:current.version}):savedSearchCreate.safeParse({name,cadence,filters,version:0});if(!parsed.success){setFields(parsed.error.flatten().fieldErrors);return;}setFields({});setBusy(true);try{if(current)await sdk.SavedSearchController_update({params:{id:current.id},body:{name,cadence,filters,paused,version:current.version}});else await sdk.SavedSearchController_create({body:{name,cadence,filters,version:0}});onSaved();onClose();}catch(e){if(e instanceof ApiError){setFields(e.fieldErrors);setConflict(e.status===409);if(e.status===401)client.clear();}setError(e instanceof Error?e.message:'The search could not be saved.');}finally{setBusy(false);}}
 return <Dialog title={current?'Update saved search':'Save this search'} onClose={onClose}><p>Keep these filters for <CityLabel slug={filters.city}/>. Prices are in {filters.currency||'the city currency'}. Open the results to adjust location, price, layout and other criteria.</p>{error&&<ErrorBox message={error}/>}<form className="field-form" noValidate onSubmit={submit}><label className="field"><span>Search name</span><input aria-label="Search name" value={name} maxLength={80} disabled={busy} aria-invalid={!!fields.name?.length} aria-describedby={fields.name?.length?'search-name-error':undefined} onChange={event=>setName(event.target.value)}/>{fields.name?.length&&<span id="search-name-error" role="alert">{fields.name.join(' ')}</span>}</label><label className="field"><span>Alert frequency preference</span><select aria-label="Alert frequency preference" value={cadence} disabled={busy} onChange={event=>setCadence(event.target.value as 'daily'|'weekly')}><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label>{current&&<label className="checkbox-field"><input type="checkbox" checked={paused} disabled={busy} onChange={event=>setPaused(event.target.checked)}/>Pause this saved search</label>}{fields.filters?.length&&<p role="alert">{fields.filters.join(' ')}</p>}<button className="button" disabled={busy||conflict}>{busy?'Saving…':current?'Save changes':'Save search'}</button>{conflict&&current&&<button type="button" className="button secondary" onClick={async()=>{setBusy(true);try{const own=await sdk.SavedSearchController_read({}),latest=own.data.find(row=>row.id===current.id);if(!latest)throw Error('This saved search is no longer available.');window.location.assign(latest.restoreUrl+'&editSearch='+latest.id);}catch(e){setError(e instanceof Error?e.message:'Saved search could not be reloaded.');setBusy(false);}}}>Reload saved search</button>}</form></Dialog>;
}
export function SavedSearches({accountId,city}:{accountId:string;city:{slug:string;currency:string}}){
 const client=useQueryClient(),searches=useQuery({queryKey:['saved-searches',accountId],queryFn:({signal})=>sdk.SavedSearchController_read({signal})}),[editing,setEditing]=useState<SavedSearch|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[matches,setMatches]=useState<Record<string,Awaited<ReturnType<typeof sdk.SavedSearchController_matches>>['data']>>({});
 async function change(row:SavedSearch,remove=false){setBusy(row.id);setError('');try{if(remove)await sdk.SavedSearchController_remove({params:{id:row.id},body:{version:row.version}});else await sdk.SavedSearchController_update({params:{id:row.id},body:{name:row.name,filters:row.filters,cadence:row.cadence,version:row.version,paused:!row.paused}});await client.invalidateQueries({queryKey:['saved-searches',accountId]});setMatches(value=>{const next={...value};delete next[row.id];return next;});setNotice(remove?'Saved search deleted.':row.paused?'Saved search resumed.':'Saved search paused.');}catch(e){setError(e instanceof Error?e.message:'The saved search could not be changed.');if(e instanceof ApiError&&e.status===401)client.clear();else if(e instanceof ApiError&&e.status===409)await client.invalidateQueries({queryKey:['saved-searches',accountId]});}finally{setBusy('');}}
 async function check(row:SavedSearch){setBusy(row.id);setError('');try{const result=await sdk.SavedSearchController_matches({params:{id:row.id}});setMatches(value=>({...value,[row.id]:result.data}));}catch(e){setError(e instanceof Error?e.message:'Matches could not be checked.');}finally{setBusy('');}}
 if(searches.isPending)return <Spinner/>;if(searches.isError)return <ErrorBox message={searches.error.message} retry={()=>searches.refetch()}/>;
 return <section aria-labelledby="saved-search-heading"><h2 id="saved-search-heading">Saved searches</h2><p>Return to your filters, choose daily or weekly updates, or pause a search.</p>{error&&<ErrorBox message={error}/>}<p role="status">{notice}</p>{!searches.data.data.length?<Empty title="No saved searches yet" description="Choose your filters in property results, then save the search."><a className="button" href={'/'+city.slug+'/buy'}>Explore homes</a></Empty>:<div className="record-list">{searches.data.data.map(row=><article className="record-row" key={row.id} data-saved-search-id={row.id}><div><h3>{row.name}</h3><p><CityLabel slug={row.filters.city}/> · {row.filters.currency||'Currency needs review'} · {row.cadence==='daily'?'Daily':'Weekly'} updates preference</p><Badge>{row.paused?'Paused':'Saved'}</Badge><p className="fine-print">{row.alertEligible?'Eligible for matching alerts.':'Alerts paused or criteria need review.'}</p>{row.criteriaVersion===0&&<p role="status">Review these older criteria before enabling matching alerts.</p>}<div className="account-links"><a href={row.restoreUrl}>View results</a>{row.criteriaVersion===1&&<a href={row.restoreUrl+'&editSearch='+row.id}>Edit criteria in results</a>}</div><button className="button secondary small" disabled={!!busy} onClick={()=>setEditing(row)}>Edit preferences</button><button className="button secondary small" disabled={!!busy||row.criteriaVersion===0} onClick={()=>void change(row)}>{row.paused?'Resume search':'Pause search'}</button><button className="button secondary small" disabled={!!busy} onClick={()=>void change(row,true)}>Delete search</button><button className="button secondary small" disabled={!!busy} onClick={()=>void check(row)}>Check matching homes</button>{matches[row.id]&&<div role="status">{matches[row.id].eligible?`${matches[row.id].listings.length} current matching homes (up to 50).`:'This search is not currently eligible for alerts.'}</div>}</div></article>)}</div>}{editing&&<SavedSearchDialog current={editing} filters={{...editing.filters,city:editing.filters.city||city.slug,currency:editing.filters.currency||city.currency}} onClose={()=>setEditing(null)} onSaved={()=>{void client.invalidateQueries({queryKey:['saved-searches',accountId]});setNotice('Saved search updated.');}}/>}</section>;
}
export function SaveAppliedSearch({city,section,query,accountId,onClose,onSaved}:{city:{slug:string;currency:string};section:string;query:URLSearchParams;accountId?:string;onClose:()=>void;onSaved:()=>void}){
 const editId=query.get('editSearch'),searches=useQuery({queryKey:['saved-searches',accountId],queryFn:({signal})=>sdk.SavedSearchController_read({signal}),enabled:!!editId&&!!accountId});
 const filters=Object.fromEntries(Array.from(query).filter(([key,value])=>value&&!['page','cursor','limit','editSearch','city'].includes(key)));filters.city=city.slug;filters.currency=city.currency;if(section==='buy'){filters.transaction='sale';filters.segment='residential';}else if(section==='rent'){filters.transaction='rent';filters.segment='residential';}else if(section==='commercial')filters.segment='commercial';
 if(!accountId)return <Dialog title="Sign in to save this search" onClose={onClose}><p>Your session is unavailable. Sign in again to save your search.</p><a className="button" href={'/api/v1/auth/login?returnTo='+encodeURIComponent('/'+city.slug+'/'+section+'?'+query.toString())}>Sign in</a></Dialog>;
 if(editId){if(searches.isPending)return <Dialog title="Load saved search" onClose={onClose}><Spinner/></Dialog>;if(searches.isError)return <Dialog title="Load saved search" onClose={onClose}><ErrorBox message={searches.error.message} retry={()=>searches.refetch()}/></Dialog>;const current=searches.data.data.find(row=>row.id===editId);if(!current)return <Dialog title="Saved search unavailable" onClose={onClose}><p>This saved search is unavailable for your account.</p></Dialog>;return <SavedSearchDialog filters={filters} current={current} onClose={onClose} onSaved={onSaved}/>;}
 return <SavedSearchDialog filters={filters} onClose={onClose} onSaved={onSaved}/>;
}
