'use client';
import {useEffect,useRef,useState} from 'react';
import {modelVertices,projectModel,type ModelFloor,type ModelCamera} from './spatial-model';
export function TourModel({floors,onRoom,controlsVisible=true}:{floors:ModelFloor[];controlsVisible?:boolean;onRoom:(floorId:string,sceneId:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),draw=useRef<()=>void>(()=>{}),drag=useRef<{x:number;y:number}|null>(null);
 const [camera,setCamera]=useState<ModelCamera>({yaw:-30,pitch:50,zoom:1.3}),[error,setError]=useState(''),[ready,setReady]=useState(false),[aspect,setAspect]=useState(1.5);const pose=useRef(camera);pose.current=camera;
 useEffect(()=>{draw.current();},[camera]);
 useEffect(()=>{const element=canvas.current;if(!element)return;setError('');setReady(false);const gl=element.getContext('webgl',{alpha:false,antialias:true});if(!gl){setError('3D rendering is unavailable. Use the interactive floor plan to explore rooms.');return;}let program:WebGLProgram|undefined,buffer:WebGLBuffer|undefined,observer:ResizeObserver|undefined;
 try{const shader=(type:number,source:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Shader failed');return s;};const vs=shader(gl.VERTEX_SHADER,'attribute vec3 position;attribute vec3 color;varying vec3 tint;void main(){gl_Position=vec4(position,1.);tint=color;}'),fs=shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 tint;void main(){gl_FragColor=vec4(tint,1.);}');program=gl.createProgram()!;gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Program failed');gl.useProgram(program);buffer=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const [name,offset] of [['position',0],['color',12]] as const){const attribute=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(attribute);gl.vertexAttribPointer(attribute,3,gl.FLOAT,false,24,offset);}gl.enable(gl.DEPTH_TEST);const vertices=modelVertices(floors);draw.current=()=>{const width=Math.max(1,element.clientWidth),height=Math.max(1,element.clientHeight),ratio=Math.min(devicePixelRatio||1,2);element.width=width*ratio;element.height=height*ratio;gl.viewport(0,0,element.width,element.height);setAspect(width/height);gl.clearColor(0.09,0.14,0.16,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const data=new Float32Array(vertices.flatMap(vertex=>[...projectModel(vertex.point,floors,pose.current,width/height),...vertex.color]));gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,vertices.length);setReady(true);};observer=new ResizeObserver(()=>draw.current());observer.observe(element);draw.current();}catch{setError('3D rendering failed. Use the interactive floor plan to explore rooms.');}
 return()=>{draw.current=()=>{};observer?.disconnect();if(buffer)gl.deleteBuffer(buffer);if(program)gl.deleteProgram(program);};},[floors]);
 function turn(yaw:number,pitch:number){setCamera(value=>({...value,yaw:value.yaw+yaw,pitch:Math.min(80,Math.max(15,value.pitch+pitch))}));}
 return <div className="tour-model"><p className="fine-print">Plan-derived 3D model · drag to orbit · select a room to enter its panorama.</p><label className="field model-room-picker" hidden={!controlsVisible}><span>Enter a room</span><select aria-label="3D room" value="" onChange={event=>{const [floorId,sceneId]=event.target.value.split(':');if(floorId&&sceneId)onRoom(floorId,sceneId);}}><option value="">Choose a room and floor</option>{floors.flatMap(floor=>floor.spatial.rooms.map(room=><option key={floor.id+room.id} value={floor.id+':'+room.sceneId}>{room.label} · {floor.spatial.name}</option>))}</select></label>{error?<p role="status">{error}</p>:<><div className="model-surface"><canvas ref={canvas} role="img" aria-label="Interactive 3D property model" tabIndex={0} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();turn(event.key==='ArrowLeft'?-10:event.key==='ArrowRight'?10:0,event.key==='ArrowUp'?5:event.key==='ArrowDown'?-5:0);}}} onPointerDown={event=>{drag.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(drag.current){turn((event.clientX-drag.current.x)*0.4,(event.clientY-drag.current.y)*0.3);drag.current={x:event.clientX,y:event.clientY};}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>{floors.flatMap(floor=>floor.spatial.rooms.map(room=>{const x=(room.camera.x-0.5)*floor.spatial.widthMetres,z=(room.camera.y-0.5)*floor.spatial.depthMetres,[px,py]=projectModel([x,floor.spatial.elevationMetres+0.2,z],floors,camera,aspect);return <button key={floor.id+room.id} className="model-room" aria-label={room.label+' on '+floor.spatial.name} style={{left:(px+1)*50+'%',top:(1-py)*50+'%'}} onClick={()=>onRoom(floor.id,room.sceneId)}>{room.label}</button>;}))}</div><p className={ready?'visually-hidden':'model-state'} role="status">{ready?'3D model ready':'Loading 3D model…'}</p><div className="media-controls" hidden={!controlsVisible}><button className="button secondary small" onClick={()=>turn(-15,0)}>Orbit left</button><button className="button secondary small" onClick={()=>turn(15,0)}>Orbit right</button><button className="button secondary small" disabled={camera.zoom>=2.5} onClick={()=>setCamera(value=>({...value,zoom:Math.min(2.5,value.zoom+0.2)}))}>3D zoom in</button><button className="button secondary small" disabled={camera.zoom<=0.6} onClick={()=>setCamera(value=>({...value,zoom:Math.max(0.6,value.zoom-0.2)}))}>3D zoom out</button><button className="button secondary small" onClick={()=>setCamera({yaw:-30,pitch:50,zoom:1.3})}>Reset model</button></div><output hidden={!controlsVisible}>Orbit {Math.round(camera.yaw)}° · Tilt {Math.round(camera.pitch)}°</output></>}</div>;
}
