import {publicPageQuery} from '../../public-query';
import type {Metadata} from 'next';
import {permanentRedirect} from 'next/navigation';
import ConsumerApp from '../../consumer';
import {pageSource} from '../../page-source';
import {pageMetadata,publicStructuredData,canonicalPath} from '../../seo';
type Inputs={params:Promise<{path?:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
export async function generateMetadata({params,searchParams}:Inputs):Promise<Metadata>{const {path=[]}=await params,s=await pageSource(path.join('/'),publicPageQuery(await searchParams));const record=s.detail&&s.initial?.data&&!Array.isArray(s.initial.data)?s.initial.data:null,canonical=canonicalPath(s.city.slug,s.section,record);if(!s.privatePage&&!s.error&&(record||s.section==='tools')&&canonical!=='/'+path.join('/'))permanentRedirect(canonical);return pageMetadata(s.city,s.section,s.detail&&s.initial?.data&&!Array.isArray(s.initial.data)?s.initial.data:null,await searchParams,s.error,s.privatePage);}
export default async function Page({params,searchParams}:Inputs){const {path=[]}=await params,s=await pageSource(path.join('/'),publicPageQuery(await searchParams)),record=s.detail&&s.initial?.data&&!Array.isArray(s.initial.data)?s.initial.data:null;const canonical=canonicalPath(s.city.slug,s.section,record);if(!s.privatePage&&!s.error&&(record||s.section==='tools')&&canonical!=='/'+path.join('/'))permanentRedirect(canonical);const structured=publicStructuredData(s.city,s.section,record,s.error,s.privatePage);return <>{structured&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/>}<ConsumerApp workspaceUrl={(process.env.PUBLIC_OPS_URL||'http://localhost:8089')+'/ops'} city={s.city} section={s.section} detail={s.detail} initial={s.initial} initialEndpoint={s.initialEndpoint} initialError={s.error}/></>;}
