import { z } from 'zod';
import Decimal from 'decimal.js';
export type Listing={id:string;slug:string;title:string;description:string;transaction:'sale'|'rent';segment:'residential'|'commercial';price:string|null;currency:string;rentPeriod:string|null;area:string;beds:number;livingRooms:number;baths:number;orientation:string;features:string[];photos:string[];city:string;district:string;community:string;communityId:string;agentId:string;version:number;publishedAt:string;latitude:number;longitude:number;status:string;furnishing:string;availableFrom:string|null};
export type ApiEnvelope<T>={data:T;meta?:Record<string,unknown>;error?:{code:string;message:string;fieldErrors?:Record<string,string[]>;requestId:string}};
export const money=z.string().regex(/^\d+(\.\d{1,2})?$/,'Use a positive decimal amount').refine(x=>Number(x)<=1e12,'Amount too large');
const facet=z.string().trim().min(1).max(240).regex(/^[\p{L}\p{N} _'.,-]+$/u,'Choose valid facet values').refine(v=>v.split(',').length<=20&&v.split(',').every(x=>x.trim().length>0),'Choose up to 20 values').transform(v=>[...new Set(v.split(',').map(x=>x.trim()))].sort().join(','));
const uuidFacet=z.string().max(740).refine(v=>v.split(',').length<=20&&v.split(',').every(x=>z.uuid().safeParse(x).success),'Choose valid identifiers');
export const listingFilters=z.strictObject({city:z.string().regex(/^[a-z0-9-]{1,50}$/).default('bj'),district:facet.optional(),districtId:uuidFacet.optional(),communityId:uuidFacet.optional(),neighborhoodId:uuidFacet.optional(),transaction:z.enum(['sale','rent']).optional(),segment:z.enum(['residential','commercial']).optional(),text:z.string().trim().max(120).optional(),currency:z.string().regex(/^[A-Z]{3}$/).optional(),rentPeriod:z.enum(['day','month','year']).optional(),minPrice:money.optional(),maxPrice:money.optional(),beds:z.coerce.number().int().min(0).max(20).optional(),livingRooms:z.coerce.number().int().min(0).max(20).optional(),minArea:z.coerce.number().min(0).max(1e6).optional(),maxArea:z.coerce.number().min(0).max(1e6).optional(),orientation:facet.optional(),furnishing:facet.optional(),features:facet.optional(),elevator:z.enum(['true','false']).optional(),sort:z.enum(['recommended','price_asc','price_desc','newest','area_desc']).default('recommended'),limit:z.coerce.number().int().min(1).max(50).default(20),page:z.coerce.number().int().min(1).max(500).default(1),cursor:z.string().min(1).max(2000).optional()}).superRefine((x,ctx)=>{if(x.minPrice!==undefined&&x.maxPrice!==undefined&&new Decimal(x.minPrice).gt(x.maxPrice))ctx.addIssue({code:'custom',path:['minPrice'],message:'Minimum price must not exceed maximum price'});if(x.minArea!==undefined&&x.maxArea!==undefined&&x.minArea>x.maxArea)ctx.addIssue({code:'custom',path:['minArea'],message:'Minimum area must not exceed maximum area'});if(x.rentPeriod&&x.transaction==='sale')ctx.addIssue({code:'custom',path:['rentPeriod'],message:'Rent period requires rental inventory'});if(x.cursor&&x.page!==1)ctx.addIssue({code:'custom',path:['cursor'],message:'Use cursor or page, not both'});});
export const inquirySchema=z.object({resourceId:z.string().uuid(),resourceType:z.enum(['listing','development','agent','provider']).default('listing'),name:z.string().trim().min(2).max(80),email:z.string().email(),phone:z.string().trim().min(7).max(30),message:z.string().trim().min(5).max(2000),consent:z.literal(true)});
export const ownerSchema=z.object({title:z.string().trim().min(8).max(160),transaction:z.enum(['sale','rent']),districtId:z.string().uuid(),communityId:z.string().uuid(),area:z.string().regex(/^\d+(\.\d{1,2})?$/).refine(x=>Number(x)>0&&Number(x)<1e5),beds:z.coerce.number().int().min(0).max(20),livingRooms:z.coerce.number().int().min(0).max(10),price:money,description:z.string().min(20).max(5000),contact:z.string().min(7).max(100),consent:z.boolean()});
export const listingTransitions:Record<string,string[]>={draft:['submitted'],submitted:['under_review','rejected'],under_review:['published','rejected'],rejected:['submitted'],published:['paused','sold','leased','expired','archived'],paused:['submitted','archived'],sold:['archived'],leased:['archived'],expired:['submitted','archived']};
export const leadTransitions:Record<string,string[]>={new:['assigned','contacted','lost'],assigned:['contacted','lost'],contacted:['qualified','lost'],qualified:['viewing','offer','lost'],viewing:['offer','lost'],offer:['won','lost']};
export const maintenanceTransitions:Record<string,string[]>={open:['triaged'],triaged:['assigned'],assigned:['in_progress'],in_progress:['resolved'],resolved:['closed','reopened'],reopened:['triaged','assigned']};
export class WorkflowError extends Error{readonly code='INVALID_TRANSITION';readonly statusCode=409;}
export function transition(map:Record<string,string[]>,from:string,to:string){if(!map[from]?.includes(to))throw new WorkflowError(`Cannot move ${from} to ${to}`);return to;}
export function priceLabel(price:string|null,currency='CNY',period?:string|null){return price===null?'Price on request':new Intl.NumberFormat('en-GB',{style:'currency',currency,maximumFractionDigits:0}).format(Number(price))+(period?` / ${period}`:'');}
