import {z} from 'zod';
export const marketCurrency=z.string().regex(/^[A-Z]{3}$/).refine(v=>Intl.supportedValuesOf('currency').includes(v),'Choose a supported ISO currency');
export const marketTimezone=z.string().max(80).refine(v=>v==='UTC'||Intl.supportedValuesOf('timeZone').includes(v),'Choose a supported IANA timezone');
export const marketCountry=z.string().regex(/^[A-Z]{2}$/).refine(v=>{try{const name=new Intl.DisplayNames(['en'],{type:'region',fallback:'none'}).of(v);return !!name&&v!=='ZZ';}catch{return false;}},'Choose a known country code');
export const credentialRules=z.object({holderMinLength:z.number().int().min(2).max(120).default(2),registrationMinLength:z.number().int().min(3).max(100).default(3),issuerMinLength:z.number().int().min(2).max(120).default(2),maxValidityDays:z.number().int().min(1).max(36500).default(36500)}).strict().default({holderMinLength:2,registrationMinLength:3,issuerMinLength:2,maxValidityDays:36500});
export const ownershipTag=z.object({key:z.string().regex(/^[a-z][a-z0-9_]{1,39}$/),label:z.string().trim().min(2).max(80),explanation:z.string().trim().min(5).max(300)}).strict();
export const contactLinks=z.object({supportPhone:z.string().regex(/^\+[1-9][0-9 -]{5,24}$/).nullable().default(null),supportWebsite:z.url().refine(v=>new URL(v).protocol==='https:'&& !new URL(v).username&&!new URL(v).password,'Use an HTTPS public website').nullable().default(null),iosApp:z.url().refine(v=>new URL(v).protocol==='https:'&&!new URL(v).username&&!new URL(v).password,'Use an HTTPS app target').nullable().default(null),androidApp:z.url().refine(v=>new URL(v).protocol==='https:'&&!new URL(v).username&&!new URL(v).password,'Use an HTTPS app target').nullable().default(null)}).strict().default({supportPhone:null,supportWebsite:null,iosApp:null,androidApp:null});
export const extraMarketPolicy={country:marketCountry.optional(),currency:marketCurrency.optional(),timezone:marketTimezone.optional(),cityVersion:z.number().int().positive().optional(),credentialRules,ownershipTags:z.array(ownershipTag).max(16).refine(v=>new Set(v.map(t=>t.key)).size===v.length,'Unique ownership keys required').default([]),contactLinks};
export const marketHistory=z.array(z.object({version:z.number().int().positive(),actorId:z.uuid().nullable(),at:z.string().nullable(),historical:z.boolean(),data:z.record(z.string(),z.unknown())}));
