import {z} from 'zod';
import {operations} from './generated/operations';
import {digitizationSchemas} from './digitization';
export const errorSchema=z.object({error:z.object({code:z.string(),message:z.string(),requestId:z.string(),recoverable:z.boolean().optional(),action:z.string().optional(),fieldErrors:z.record(z.string(),z.array(z.string())).optional()})});
export function createOpenApi(){
 const paths:Record<string,Record<string,object>>={};
 for(const [id,op] of Object.entries(operations)){
  const stream=['DigitizationController_intakeEvents','DigitizationController_listingEvents'].includes(id);
  const route=op.path.replace(/:(\w+)/g,'{$1}'),binary=['DigitizationArtifactController_geometrySvg','DigitizationArtifactController_preview','MediaController_view','MediaController_video','MediaController_download','LeaseDraftsController_download','TenantLeasesController_download','MaintenanceController_photo','ManagementController_statementCSV','ManagementController_statementPrint','AdministrationController_supportAttachment','AdministrationController_supportExport','AdministrationController_analyticsExport'].includes(id),redirect=['IdentityController_login','IdentityController_callback'].includes(id);
  const query=z.toJSONSchema(op.query,{io:'input',target:'openapi-3.0'}),params=z.toJSONSchema(op.params,{io:'input',target:'openapi-3.0'});
  const parameters=[];for(const [location,schema] of [['path',params],['query',query]] as const)for(const [name,value] of Object.entries(schema.properties||{}))parameters.push({name,in:location,required:location==='path'||schema.required?.includes(name)||false,schema:value});
  if(id.startsWith('NotificationWorkerController_'))parameters.push({name:'x-alert-timestamp',in:'header',required:true,schema:{type:'string',pattern:'^[0-9]{13}$'}});
  if(id.startsWith('DigitizationWorkerController_'))parameters.push({name:'x-digitization-timestamp',in:'header',required:true,schema:{type:'string',pattern:'^[0-9]{13}$'}});
  if(id==='MediaController_video')parameters.push({name:'Range',in:'header',required:false,schema:{type:'string'}});
  if(stream)parameters.push({name:'Last-Event-ID',in:'header',required:false,schema:{type:'string',pattern:'^[0-9]{1,19}$'}});
  const success=redirect?'302':op.method==='POST'&&id!=='IdentityController_logout'?'201':'200';
  const responseSchema=redirect?undefined:stream?{type:'string',description:'Resumable SSE stream; periodic current session, membership, target and evidence authority checks; bounded reconnect policy.'}:binary?{type:'string',format:'binary'}:z.toJSONSchema(z.object({data:op.response,meta:z.record(z.string(),z.json()).optional()}),{target:'openapi-3.0'});
  const responses:Record<string,object>={[success]:{description:redirect?'Identity provider redirect':'Successful response',...(responseSchema?{content:{[stream?'text/event-stream':binary?(id==='DigitizationArtifactController_geometrySvg'?'image/svg+xml':id==='DigitizationArtifactController_preview'?'image/png':(id==='ManagementController_statementCSV'||id==='AdministrationController_supportExport'||id==='AdministrationController_analyticsExport')?'text/csv':id==='ManagementController_statementPrint'?'text/html':id==='MediaController_video'?'video/mp4':['MediaController_view','MaintenanceController_photo','ManagementController_statementCSV','ManagementController_statementPrint','AdministrationController_supportAttachment','AdministrationController_supportExport','AdministrationController_analyticsExport'].includes(id)?'image/webp':'application/pdf'):'application/json']:{schema:responseSchema}}}:{})}};
  if(id==='MediaController_video')responses['206']={description:'Partial video content',content:{'video/mp4':{schema:{type:'string',format:'binary'}}}};
  for(const code of [400,401,403,404,409,413,416,422,429,500,503])responses[String(code)]={description:'Stable API error',content:{'application/json':{schema:{$ref:'#/components/schemas/ApiError'}}}};
  const requestBody=id==='MediaController_content'?{required:true,content:Object.fromEntries(['image/jpeg','image/png','application/pdf','video/mp4','video/webm'].map(mime=>[mime,{schema:{type:'string',format:'binary'}}]))}:op.body.safeParse(undefined).success?undefined:{required:true,content:{'application/json':{schema:z.toJSONSchema(op.body,{io:'input',target:'openapi-3.0'})}}};
  paths[route]||={};paths[route][op.method.toLowerCase()]={operationId:id,tags:[id.split('Controller_')[0]],parameters,responses,...(requestBody?{requestBody}:{}),security:id.startsWith('DigitizationWorkerController_')?[{digitizationHmac:[]}]:id.startsWith('NotificationWorkerController_')?[{serviceHmac:[]}]:(/^DiscoveryController_/.test(id)||['HealthController_live','HealthController_ready','GeographyController_geography','GeographyController_buildings','GeographyController_statistics','GeographyController_listings'].includes(id))||id==='RichMediaController_publicMedia'||redirect||['MediaController_view','MediaController_video'].includes(id)?[]:[{session:[]}]};
 }
 return {openapi:'3.0.3',info:{title:'Haven Real Estate API',version:'1.0.0'},servers:[{url:'/'}],paths,components:{securitySchemes:{digitizationHmac:{type:'apiKey',in:'header',name:'x-digitization-signature',description:'Separate coordinator HMAC SHA-256 of timestamp, method, exact path and canonical JSON body digest; timestamp expires after 60 seconds. Current initiating-actor authority is checked for every command.'},serviceHmac:{type:'apiKey',in:'header',name:'x-alert-signature',description:'HMAC SHA-256 of timestamp, method, exact path and canonical JSON body digest using a purpose-derived server key; timestamp expires after 60 seconds.'},session:{type:'apiKey',in:'cookie',name:'haven_session'}},schemas:{...Object.fromEntries(Object.entries(digitizationSchemas).map(([name,schema])=>[name,z.toJSONSchema(schema,{io:'input',target:'openapi-3.0'})])),ApiError:z.toJSONSchema(errorSchema,{target:'openapi-3.0'})}}};
}
