import {z} from 'zod';
const point=z.object({x:z.number().min(0).max(1),y:z.number().min(0).max(1)});
export const mappedRoom=z.object({id:z.string().regex(/^[a-zA-Z0-9_-]{1,50}$/),label:z.string().trim().min(2).max(80),sceneId:z.string().uuid(),polygon:z.array(point).min(3).max(24),heightMetres:z.number().min(1).max(12).default(2.7),camera:point.extend({headingDegrees:z.number().min(-180).max(180)})}).superRefine((room,ctx)=>{
 const cross=(a:{x:number;y:number},b:{x:number;y:number},c:{x:number;y:number})=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
 for(let i=0;i<room.polygon.length;i++)for(let j=i+2;j<room.polygon.length;j++){if(i===0&&j===room.polygon.length-1)continue;const a=room.polygon[i],b=room.polygon[(i+1)%room.polygon.length],c=room.polygon[j],d=room.polygon[(j+1)%room.polygon.length];if(cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0){ctx.addIssue({code:'custom',path:['polygon'],message:'Room edges must not intersect'});return;}}
 let sign=0,area=0;for(let i=0;i<room.polygon.length;i++){const a=room.polygon[i],b=room.polygon[(i+1)%room.polygon.length],c=room.polygon[(i+2)%room.polygon.length];area+=a.x*b.y-b.x*a.y;const turn=(b.x-a.x)*(c.y-b.y)-(b.y-a.y)*(c.x-b.x);if(Math.abs(turn)<1e-8){ctx.addIssue({code:'custom',path:['polygon'],message:'Use a convex room outline without repeated or collinear corners'});return;}if(sign&&Math.sign(turn)!==sign){ctx.addIssue({code:'custom',path:['polygon'],message:'Room outlines must be convex and must not cross'});return;}sign=Math.sign(turn);}
 if(Math.abs(area)<0.0002)ctx.addIssue({code:'custom',path:['polygon'],message:'Room outline is too small'});
 for(let i=0;i<room.polygon.length;i++){const a=room.polygon[i],b=room.polygon[(i+1)%room.polygon.length];if(Math.sign((b.x-a.x)*(room.camera.y-a.y)-(b.y-a.y)*(room.camera.x-a.x))!==sign)ctx.addIssue({code:'custom',path:['camera'],message:'Place the camera inside its room outline'});}
});
export const floorLayout=z.object({name:z.string().trim().min(2).max(80),level:z.number().int().min(-10).max(100),widthMetres:z.number().min(1).max(500),depthMetres:z.number().min(1).max(500),elevationMetres:z.number().min(-50).max(500),northDegrees:z.number().min(-180).max(180),rooms:z.array(mappedRoom).min(1).max(60)}).superRefine((floor,ctx)=>{if(new Set(floor.rooms.map(room=>room.id)).size!==floor.rooms.length||new Set(floor.rooms.map(room=>room.sceneId)).size!==floor.rooms.length)ctx.addIssue({code:'custom',path:['rooms'],message:'Each room and panorama viewpoint must be unique within this floor'});});
export const propertyMediaMetadata=z.object({hotspots:z.array(z.object({targetId:z.string().uuid(),label:z.string().min(2).max(80),yaw:z.number().min(-180).max(180),pitch:z.number().min(-80).max(80)})).max(20).default([]),caption:z.string().max(1000).default(''),spatial:floorLayout.optional()});
export type FloorLayout=z.infer<typeof floorLayout>;
export type MappedRoom=z.infer<typeof mappedRoom>;
