import {z} from 'zod';
const version=z.number().int().positive(),category=z.enum(['General','Listing complaint','Account','Viewing','Other']);
export const supportPageQuery=z.object({status:z.enum(['open','triaged','escalated','resolved']).optional(),category:category.optional(),assigneeId:z.uuid().optional(),page:z.coerce.number().int().min(1).max(10000).default(1)}).strict();
export const supportCreate=z.object({version:z.literal(0),subject:z.string().trim().min(5).max(120),description:z.string().trim().min(10).max(3000),category,listing:z.object({id:z.uuid(),version}).strict().nullable().default(null),attachments:z.array(z.object({assetId:z.uuid(),version,label:z.string().trim().min(2).max(120)}).strict()).max(6).default([]).refine(v=>new Set(v.map(a=>a.assetId)).size===v.length,'Duplicate attachment'),consent:z.literal(true)}).strict().refine(v=>v.category!=='Listing complaint'||v.listing!==null,'Select the published listing for this complaint');
export const supportTriage=z.object({version,assigneeId:z.uuid(),publicReply:z.string().trim().min(5).max(2000)}).strict();
export const supportRecord=z.object({id:z.uuid(),version,subject:z.string(),description:z.string(),category:z.string(),status:z.string(),publicReply:z.string().nullable(),createdAt:z.string(),updatedAt:z.string().nullable(),historical:z.boolean(),listing:z.object({id:z.uuid(),version,title:z.string(),url:z.string()}).nullable(),assigned:z.boolean(),assigneeId:z.uuid().nullable(),attachments:z.array(z.object({id:z.uuid(),version,label:z.string(),mime:z.string(),url:z.string()})),canAct:z.boolean(),canComment:z.boolean(),canReopen:z.boolean(),internalNotes:z.array(z.object({id:z.string(),version:version.nullable(),body:z.string(),at:z.string().nullable(),historical:z.boolean()})).optional(),activity:z.array(z.object({version,status:z.string(),message:z.string().nullable(),at:z.string(),action:z.string()}))});
export const supportPage=z.object({page:version,limit:z.literal(20),total:z.number().int().nonnegative(),items:z.array(supportRecord)});
export const supportAssignees=z.array(z.object({id:z.uuid(),name:z.string()}));
export type SupportRecord=z.infer<typeof supportRecord>;

export const supportWorkflow=z.object({version,action:z.enum(['comment','note','assign','escalate','deescalate','resolve','reopen']),assigneeId:z.uuid().optional(),publicReply:z.string().trim().max(2000).optional(),internalNote:z.string().trim().min(1).max(2000).optional()}).strict().superRefine((v,c)=>{if(v.action==='note'){if(!v.internalNote||v.publicReply)c.addIssue({code:'custom',message:'A private note only is required',path:['internalNote']});}else{if(v.internalNote)c.addIssue({code:'custom',message:'Use the separate private note action',path:['internalNote']});const min=['escalate','deescalate','resolve','reopen'].includes(v.action)?10:v.action==='assign'?5:1;if((v.publicReply?.length||0)<min)c.addIssue({code:'custom',message:'Explain this public case action',path:['publicReply']});}if(v.action==='assign'&&!v.assigneeId)c.addIssue({code:'custom',message:'Choose current support staff',path:['assigneeId']});if(v.action!=='assign'&&v.assigneeId)c.addIssue({code:'custom',message:'Assignee applies only to handoff',path:['assigneeId']});});

export const supportPublicAction=z.object({version,action:z.enum(['comment','reopen']),publicReply:z.string().trim().min(1).max(2000)}).strict().refine(v=>v.action!=='reopen'||v.publicReply.length>=10,'Explain why this resolved case needs reopening');
