import {createHmac,createSecretKey,timingSafeEqual,type KeyObject} from 'node:crypto';
import {isIP} from 'node:net';
type Context={address:string;origin:string;method:string;path:string;at:number};
const purpose='haven-inquiry-client-v1:';
// Reuse only the current process key; a changed key replaces it immediately.
let preparedKey:KeyObject|undefined,preparedHex:string|undefined;
function signingKey(key:string){if(!preparedKey||preparedHex!==key){const next=createSecretKey(Buffer.from(key,'hex'));preparedKey=next;preparedHex=key;}return preparedKey;}
export function signInquiryClient(context:Omit<Context,'at'>,key:string,now=Date.now()){if(!isIP(context.address))throw new Error('Verified gateway client address unavailable');const encoded=Buffer.from(JSON.stringify({...context,at:Math.floor(now/1000)})).toString('base64url'),mac=createHmac('sha256',signingKey(key)).update(purpose+encoded).digest('hex');return encoded+'.'+mac;}
export function verifyInquiryClient(value:unknown,key:string,expected:{origin:string;method:string;path:string},now=Date.now()):string|null{if(typeof value!=='string'||value.length>2000)return null;const [encoded,signature,...extra]=value.split('.');if(extra.length||!encoded||!signature||!/^[a-f0-9]{64}$/.test(signature))return null;const actual=Buffer.from(signature,'hex'),wanted=createHmac('sha256',signingKey(key)).update(purpose+encoded).digest();if(actual.length!==wanted.length||!timingSafeEqual(actual,wanted))return null;try{const c=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')) as Context;if(!isIP(c.address)||!Number.isInteger(c.at)||c.at>Math.floor(now/1000)+5||c.at<Math.floor(now/1000)-30||c.origin!==expected.origin||c.method!==expected.method||c.path!==expected.path)return null;return c.address;}catch{return null;}}

const gatewayPurpose='haven-gateway-client-v1:';
export function signGatewayClient(context:Omit<Context,'at'>,key:string,now=Date.now()){if(!isIP(context.address))throw new Error('Verified gateway client address unavailable');const encoded=Buffer.from(JSON.stringify({...context,at:Math.floor(now/1000)})).toString('base64url'),mac=createHmac('sha256',signingKey(key)).update(gatewayPurpose+encoded).digest('hex');return encoded+'.'+mac;}
export function verifyGatewayClient(value:unknown,key:string,expected:{origin:string;method:string;path:string},now=Date.now()):string|null{if(typeof value!=='string'||value.length>2000)return null;const [encoded,signature,...extra]=value.split('.');if(extra.length||!encoded||!signature||!/^[a-f0-9]{64}$/.test(signature))return null;const actual=Buffer.from(signature,'hex'),wanted=createHmac('sha256',signingKey(key)).update(gatewayPurpose+encoded).digest();if(actual.length!==wanted.length||!timingSafeEqual(actual,wanted))return null;try{const c=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')) as Context;if(!isIP(c.address)||!Number.isInteger(c.at)||c.at>Math.floor(now/1000)+5||c.at<Math.floor(now/1000)-30||c.origin!==expected.origin||c.method!==expected.method||c.path!==expected.path)return null;return c.address;}catch{return null;}}
