import {createRequire} from 'node:module';
import {platformStaff} from '../../apps/api/src/administration/platform-users';
import {fixtureAccountState} from '../support/account-fixture';
import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {PrivacyController} from '../../apps/api/src/identity/privacy';
import type {Identity} from '../../apps/api/src/platform/core';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),historicalFixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});
afterAll(async()=>{await historicalFixtures.end();await pool.end();});
const req=(method='GET')=>({method,url:'/api/v1/me/privacy',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
async function fixture(role='consumer'){const id=crypto.randomUUID(),actor:Actor={id,orgId:role==='admin'?'10000000-0000-4000-8000-000000000001':null,roles:[role]};await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,display_name,email,email_verified) VALUES($1,$2,$3,$4,true)",[id,'privacy-'+id,'Privacy '+id,'privacy-'+id+'@example.test']);if(role==='admin')await platformStaff(c,workerActor,{...req('POST'),url:'/api/v1/ops/users/'+id+'/staff'},id,{version:0,profileVersion:1,role:'admin',status:'active',reason:'Synthetic privacy export administrator fixture.'});else await c.query('INSERT INTO memberships(user_id,role) VALUES($1,$2)',[id,role]);});return{id,actor,controller:new PrivacyController({actor:async()=>actor} as unknown as Identity)};}
async function financial(f:Awaited<ReturnType<typeof fixture>>){return transaction(workerActor,async c=>{const tenant=crypto.randomUUID(),lease=crypto.randomUUID(),payment=crypto.randomUUID(),reversal=crypto.randomUUID(),charge=crypto.randomUUID();await c.query("INSERT INTO tenants(id,organization_id,user_id,name,email) VALUES($1,'10000000-0000-4000-8000-000000000001',$2,'Privacy tenant','privacy-tenant@example.test')",[tenant,f.id]);await c.query("INSERT INTO leases(id,organization_id,unit_id,tenant_id,start_date,end_date,rent,currency,status) SELECT $1,organization_id,unit_id,$2,'2035-01-01','2035-12-31','1234.56','CNY','draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000'",[lease,tenant]);await c.query("INSERT INTO charges(id,lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'10000000-0000-4000-8000-000000000001','2035-01-01','2035-01-01','1234.56','CNY')",[charge,lease]);await c.query("INSERT INTO payments(id,lease_id,organization_id,amount,currency,source,reference,actor_id) VALUES($1,$2,'10000000-0000-4000-8000-000000000001','1234.56','CNY','fixture',$3,$4)",[payment,lease,'OWN_PAYMENT_'+f.id,f.id]);await c.query("INSERT INTO payments(id,lease_id,organization_id,amount,currency,source,reference,actor_id,reverses_id) VALUES($1,$2,'10000000-0000-4000-8000-000000000001','1234.56','CNY','reversal',$3,$4,$5)",[reversal,lease,'OWN_REVERSAL_'+f.id,f.id,payment]);return{lease,payment,reversal,charge};});}
it('A06 one-snapshot personal export excludes another persona even for an administrator and keeps money as decimal strings',async()=>{
 const f=await fixture('admin'),other=await fixture();await financial(f);await financial(other);await transaction(workerActor,async c=>{for(const user of [f.id,other.id]){const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,area,beds,living_rooms,baths FROM units LIMIT 1 RETURNING id,organization_id")).rows[0];await c.query("INSERT INTO unit_private_details(unit_id,organization_id,private_address) VALUES($1,$2,$3)",[unit.id,unit.organization_id,'OWN_ADDRESS_'+user]);await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price) SELECT $1,organization_id,$2,agent_id,$3,'Own privacy home',description,transaction,segment,currency,price FROM listings WHERE id='10000000-0000-4000-8000-000000002000'",[unit.id,user,'a06-own-'+user]);await c.query("INSERT INTO notifications(user_id,title,body) VALUES($1,'Own update','My notification')",[user]);}await c.query("INSERT INTO sessions(id,user_id,encrypted_tokens,expires_at) VALUES($1,$2,'PRIVATE_SESSION_TOKEN',now()+interval '1 hour')",['privacy-'+f.id,f.id]);});
 // Preserved historical support rows exercise export omission, not current staff mutation.
 for(const user of [f.id,other.id])await historicalFixtures.query("INSERT INTO support_cases(user_id,subject,description,category,internal_note,public_reply) VALUES($1,$2,'My personal request','account','INTERNAL_PRIVACY_SENTINEL','Public reply')",[user,'PERSONAL_SUBJECT_'+user]);
 for(const user of [f.id,other.id])await transaction({...f.actor,id:user},c=>c.query("INSERT INTO recent_searches(user_id,city,query) VALUES($1,'bj',$2)",[user,'PERSONAL_QUERY_'+user]));
 const exported=(await f.controller.export(req())).data;expect(exported.profile.id).toBe(f.id);expect(exported.records.recentSearches).toHaveLength(1);expect(exported.records.ownedPrivateUnits).toHaveLength(1);expect(exported.records.ownedPrivateUnits[0].private_address).toBe('OWN_ADDRESS_'+f.id);expect(exported.records.tenantPayments).toHaveLength(2);expect(exported.records.tenantPayments.every((row:any)=>row.amount==='1234.56')).toBe(true);expect(exported.records.tenantCharges[0].amount).toBe('1234.56');expect(exported.records.tenantLeases[0].rent).toBe('1234.56');const json=JSON.stringify(exported);expect(json).not.toContain(other.id);expect(json).not.toContain('PRIVATE_SESSION_TOKEN');expect(json).not.toContain('encrypted_tokens');expect(json).not.toContain('INTERNAL_PRIVACY_SENTINEL');expect(exported.retention.classes.some(row=>row.category.includes('reversals'))).toBe(true);await transaction(workerActor,c=>fixtureAccountState(c,'suspended',"WHERE id=ANY($1::uuid[])",[[f.id,other.id]]));
});
it('A06 strict confirmed versioned deletion revokes every own session/optional channel and preserves posted finance plus reversal history',async()=>{
 const f=await fixture(),other=await fixture(),finance=await financial(f);const before=(await transaction(workerActor,c=>c.query('SELECT to_jsonb(p) row FROM payments p WHERE lease_id=$1 ORDER BY id',[finance.lease]))).rows;await transaction(workerActor,async c=>{for(const user of [f.id,other.id])for(let n=0;n<2;n++)await c.query("INSERT INTO sessions(id,user_id,encrypted_tokens,expires_at) VALUES($1,$2,'encrypted-fixture',now()+interval '1 hour')",['privacy-'+user+'-'+n,user]);await c.query('INSERT INTO browsing_history_settings(user_id,enabled) VALUES($1,true)',[f.id]);await c.query('INSERT INTO notification_preferences(user_id,email_enabled,in_app_enabled) VALUES($1,true,true)',[f.id]);await c.query("INSERT INTO saved_searches(user_id,name,filters,cadence,criteria_version,paused) VALUES($1,'Own paused on deletion','{\"city\":\"bj\",\"currency\":\"CNY\"}','daily',1,false)",[f.id]);});
 await transaction(f.actor,c=>c.query('INSERT INTO analytics_consent(user_id,enabled,version) VALUES($1,true,1)',[f.id]));const input={version:1,confirmation:'DELETE MY ACCOUNT',reason:'Privacy fixture'};await expect(f.controller.requestDeletion(req('POST'),{...input,version:9})).rejects.toMatchObject({status:409});await expect(f.controller.requestDeletion(req('POST'),{...input,userId:other.id})).rejects.toMatchObject({name:'ZodError'});await expect(f.controller.requestDeletion(req('POST'),{...input,confirmation:'delete'})).rejects.toMatchObject({name:'ZodError'});const request=req('POST'),receipt=await f.controller.requestDeletion(request,input);expect(receipt.data).toMatchObject({status:'requested',accessRevoked:true,retentionPolicyVersion:1});expect(await f.controller.requestDeletion(request,input)).toEqual(receipt);
 await transaction(workerActor,async c=>{expect((await c.query('SELECT state,version FROM profiles WHERE id=$1',[f.id])).rows[0]).toEqual({state:'deletion_requested',version:2});expect((await c.query('SELECT count(*)::int n FROM sessions WHERE user_id=$1',[f.id])).rows[0].n).toBe(0);expect((await c.query('SELECT count(*)::int n FROM sessions WHERE user_id=$1',[other.id])).rows[0].n).toBe(2);expect((await c.query('SELECT email_enabled,in_app_enabled FROM notification_preferences WHERE user_id=$1',[f.id])).rows[0]).toEqual({email_enabled:false,in_app_enabled:false});expect((await c.query('SELECT enabled,version FROM browsing_history_settings WHERE user_id=$1',[f.id])).rows[0]).toEqual({enabled:false,version:2});expect((await c.query('SELECT paused,version FROM saved_searches WHERE user_id=$1',[f.id])).rows[0]).toEqual({paused:true,version:2});expect((await historicalFixtures.query('SELECT enabled,version FROM analytics_consent WHERE user_id=$1',[f.id])).rows[0]).toEqual({enabled:false,version:2});expect((await c.query('SELECT id FROM platform_administration_history WHERE target_id=$1',[f.id])).rowCount).toBe(0);expect((await c.query('SELECT to_jsonb(p) row FROM payments p WHERE lease_id=$1 ORDER BY id',[finance.lease])).rows).toEqual(before);expect((await c.query('SELECT count(*)::int n FROM charges WHERE lease_id=$1',[finance.lease])).rows[0].n).toBe(1);expect((await c.query("SELECT count(*)::int n FROM audit_events WHERE resource_id=$1 AND action='account.deletion_requested'",[f.id])).rows[0].n).toBe(1);});await expect(f.controller.export(req())).rejects.toMatchObject({status:401});expect((await transaction(other.actor,c=>c.query('SELECT id FROM account_deletion_requests WHERE user_id=$1',[f.id]))).rowCount).toBe(0);await transaction(workerActor,c=>fixtureAccountState(c,'suspended',"WHERE id=$1",[other.id]));
});
it('A06 online export refuses over-limit data rather than silently omitting records',async()=>{
 const f=await fixture();await transaction(f.actor,c=>c.query("INSERT INTO recent_searches(user_id,city,query) SELECT $1,'bj','export-limit-'||n FROM generate_series(1,2001) n",[f.id]));await expect(f.controller.export(req())).rejects.toMatchObject({status:413});await transaction(workerActor,c=>fixtureAccountState(c,'suspended',"WHERE id=$1",[f.id]));
});
it('Q04 own staff deletion keeps original permission history, advances revoked membership versions and never records an administrator reactivation',async()=>{
 const f=await fixture('admin');const before=(await transaction(workerActor,c=>c.query('SELECT to_jsonb(h) row FROM platform_administration_history h WHERE target_id=$1 ORDER BY id',[f.id]))).rows;expect(before).toHaveLength(1);
 await transaction(workerActor,c=>c.query("INSERT INTO sessions(id,user_id,encrypted_tokens,expires_at) VALUES($1,$2,'synthetic-not-a-provider-token',now()+interval '1 hour')",['staff-privacy-'+f.id,f.id]));
 const response=await f.controller.requestDeletion(req('POST'),{version:1,confirmation:'DELETE MY ACCOUNT',reason:'Synthetic staff privacy request.'});expect(response.data.accessRevoked).toBe(true);
 await transaction(workerActor,async c=>{expect((await c.query('SELECT status,version FROM memberships WHERE user_id=$1',[f.id])).rows).toEqual([{status:'inactive',version:2}]);expect((await c.query('SELECT to_jsonb(h) row FROM platform_administration_history h WHERE target_id=$1 ORDER BY id',[f.id])).rows).toEqual(before);expect((await c.query('SELECT id FROM sessions WHERE user_id=$1',[f.id])).rowCount).toBe(0);expect((await c.query("SELECT action FROM audit_events WHERE resource_id=$1 AND action IN('account.deletion_requested','account.reactivated') ORDER BY action",[f.id])).rows).toEqual([{action:'account.deletion_requested'}]);});
 await expect(f.controller.export(req())).rejects.toMatchObject({status:401});
});
