import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {AgentCredentialsController} from '../../apps/api/src/services/agent-credentials';
import {MediaController} from '../../apps/api/src/inventory/media';
import {DiscoveryController} from '../../apps/api/src/geography/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const agent:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:'10000000-0000-4000-8000-000000000001',roles:['agent']},moderator:Actor={id:'00000000-0000-4000-8000-000000000008',orgId:null,roles:['moderator']},other:Actor={id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agent']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),controller=(a:Actor)=>new AgentCredentialsController(identity(a)),req=(query={})=>({method:'POST',url:'/api/v1/me/agent-profiles',headers:{'idempotency-key':crypto.randomUUID()},query} as unknown as FastifyRequest),ids:string[]=[],assets:string[]=[];
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query('DELETE FROM agent_credential_review_grants WHERE credential_id IN(SELECT id FROM agent_credentials WHERE agent_id=ANY($1::uuid[]))',[ids]);await c.query('DELETE FROM agent_credentials WHERE agent_id=ANY($1::uuid[])',[ids]);await c.query('DELETE FROM agents WHERE id=ANY($1::uuid[])',[ids]);await c.query('DELETE FROM media_assets WHERE id=ANY($1::uuid[])',[assets]);});}finally{await pool.end();}});
async function fixture(){const id=crypto.randomUUID();ids.push(id);await transaction(workerActor,c=>c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city) SELECT $1,user_id,organization_id,'B01 synthetic agent',$2,biography,languages,districts,'bj' FROM agents WHERE user_id=$3 LIMIT 1",[id,'b01-'+id,agent.id]));const bytes=Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF'),media=new MediaController(identity(agent)),upload=(await media.intent(req(),{mime:'application/pdf',size:bytes.length,rights:'Synthetic credential evidence for integration checks',visibility:'private'})).data;assets.push(upload.id);await media.content({...req({signature:new URL(upload.uploadUrl,'http://localhost').searchParams.get('signature')}),headers:{'content-type':'application/pdf'}} as FastifyRequest,upload.id,bytes);const credential=(await controller(agent).submit(req(),id,{version:0,profileVersion:1,holderName:'Synthetic holder',registrationReference:'SYNTHETIC-B01-PRIVATE',issuer:'Synthetic verification fixture',expiresOn:'2099-12-31',documentId:upload.id})).data;return {id,credential,mediaId:upload.id};}
it('B01 independent approval produces a badge; own/private projections omit internal notes and document identifiers',async()=>{const f=await fixture(),own=controller(agent),review=controller(moderator);expect((await new DiscoveryController().agent(f.id,'bj')).data).toMatchObject({credentialStatus:'unverified',verifiedUntil:null});const reviewingMedia=new MediaController(identity(moderator));await expect(reviewingMedia.downloadLink(req(),f.mediaId)).rejects.toMatchObject({status:404});const queue=(await review.queue(req(),{})).data;expect(queue.find(r=>r.id===f.credential.id)?.canReview).toBe(true);expect((await reviewingMedia.downloadLink(req(),f.mediaId)).data.expiresIn).toBe(60);await expect(controller(other).credentials(req(),f.id)).rejects.toMatchObject({status:404});await expect(own.review(req(),f.credential.id,{version:1,decision:'approved',verified:true,reason:'Self approval must not be allowed'})).rejects.toMatchObject({status:403});await expect(controller({...agent,roles:['admin']}).review(req(),f.credential.id,{version:1,decision:'approved',verified:true,reason:'Admin cannot approve their own credential'})).rejects.toMatchObject({status:403});await expect(review.review(req(),f.credential.id,{version:1,decision:'approved',reason:'Missing independent confirmation'})).rejects.toMatchObject({status:400});await review.review(req(),f.credential.id,{version:1,decision:'approved',verified:true,reason:'PRIVATE MODERATOR REASON B01 actual synthetic review'});await expect(transaction({...agent,roles:['admin']},c=>c.query("UPDATE agent_credentials SET expires_on='2100-12-31',version=version+1 WHERE id=$1",[f.credential.id]))).rejects.toMatchObject({code:'42501'});await expect(transaction(agent,c=>c.query('DELETE FROM agent_credentials WHERE id=$1',[f.credential.id]))).rejects.toMatchObject({code:'42501'});const publicRow=(await new DiscoveryController().agent(f.id,'bj')).data;expect(publicRow).toMatchObject({credentialStatus:'approved'});expect(JSON.stringify(publicRow)).not.toMatch(/SYNTHETIC-B01-PRIVATE|PRIVATE MODERATOR REASON/);expect(JSON.stringify(publicRow)).not.toContain(f.mediaId);expect(JSON.stringify((await own.credentials(req(),f.id)).data)).not.toContain('PRIVATE MODERATOR REASON');await expect(reviewingMedia.downloadLink(req(),f.mediaId)).rejects.toMatchObject({status:404});await expect(review.review(req(),f.credential.id,{version:1,decision:'revoked',reason:'Stale credential version rejected'})).rejects.toMatchObject({status:409});});
it('B01 expiry and revocation remove the badge immediately',async()=>{const f=await fixture(),review=controller(moderator);await review.review(req(),f.credential.id,{version:1,decision:'approved',verified:true,reason:'Independently reviewed synthetic credential'});await transaction(workerActor,c=>c.query("UPDATE agent_credentials SET expires_on=current_date-1,version=version+1 WHERE id=$1",[f.credential.id]));expect((await new DiscoveryController().agent(f.id,'bj')).data).toMatchObject({credentialStatus:'expired',verifiedUntil:null});await review.review(req(),f.credential.id,{version:3,decision:'revoked',reason:'Revoked synthetic fixture credential'});expect((await new DiscoveryController().agent(f.id,'bj')).data).toMatchObject({credentialStatus:'revoked',verifiedUntil:null});});
it('B01 public identity changes invalidate approval; self-granted expiry and cross-agency authoring are denied',async()=>{const f=await fixture();await controller(moderator).review(req(),f.credential.id,{version:1,decision:'approved',verified:true,reason:'Independent synthetic credential confirmation'});const own=controller(agent),p=(await own.read(req())).data.find(r=>r.id===f.id);await expect(transaction(agent,c=>c.query("UPDATE agents SET verified_until='2098-12-31',version=version+1 WHERE id=$1",[f.id]))).rejects.toMatchObject({code:'42501'});await expect(transaction(other,c=>c.query("UPDATE agents SET name='Foreign forged name',version=version+1 WHERE id=$1",[f.id]))).rejects.toMatchObject({code:'42501'});await own.update(req(),f.id,{version:p.version,city:'bj',name:'Changed public identity',biography:p.biography,languages:p.languages,districtIds:p.districtIds,publicEmail:'synthetic@example.test',contactConsent:false});expect((await new DiscoveryController().agent(f.id,'bj')).data).toMatchObject({credentialStatus:'unverified',verifiedUntil:null,publicEmail:null});});
