import {AdministrationController} from '../../apps/api/src/administration/controller';
import '../support/env';
import {it,expect,beforeAll,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {AgentDashboardController} from '../../apps/api/src/administration/agent-dashboard';
import {agentDashboard} from '../../packages/contracts/src/agent-dashboard';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',foreignOrg='10000000-0000-4000-8000-000000000005',people:any[]=[],listings:string[]=[],leads:string[]=[],viewings:string[]=[],identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),req={} as FastifyRequest;
async function property(c:any,p:any,status:string){const id=crypto.randomUUID(),unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,orientation,floor) SELECT community_id,$1,area,beds,living_rooms,baths,orientation,floor FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id",[p.orgId])).rows[0];await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,$7,$2,$3,$4,$5,'Explicit synthetic dashboard inventory fixture','sale','residential','CNY','1200000.25',$6)",[id,p.orgId,p.agent,'b05-'+id,'B05 property '+id,status,unit.id]);listings.push(id);return id;}
async function lead(c:any,p:any,status:string,customer='00000000-0000-4000-8000-000000000001'){const id=crypto.randomUUID();await c.query("INSERT INTO leads(id,user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message,status) VALUES($1,$2,$3,$4,$4,'agent',$5,'fixture@example.test','00000000','Explicit synthetic dashboard lead',$6)",[id,customer,p.orgId,p.agent,'B05 customer '+id,status]);leads.push(id);return id;}
async function viewing(c:any,p:any,listing:string,day:number,status:string,customer='00000000-0000-4000-8000-000000000001'){const id=crypto.randomUUID(),start=new Date(Date.now()+day*86400000),end=new Date(start.getTime()+3600000);await c.query('INSERT INTO viewings(id,listing_id,user_id,agent_id,start_at,end_at,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,listing,customer,p.agent,start,end,status]);viewings.push(id);return id;}
beforeAll(async()=>{await transaction(workerActor,async c=>{for(const agency of [org,org,foreignOrg]){const id=crypto.randomUUID(),agent=crypto.randomUUID();await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'B05 synthetic member',true)",[id,'b05-'+id,'b05-'+id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,'agent')",[id,agency]);await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,$4,$5,'Explicit synthetic dashboard eligibility fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2030-01-01')",[agent,id,agency,'B05 '+id,'b05-'+id]);people.push({id,agent,orgId:agency,roles:['agent']});}const published=await property(c,people[0],'published');await property(c,people[0],'draft');const other=await property(c,people[1],'published'),foreign=await property(c,people[2],'published');await lead(c,people[0],'new');await lead(c,people[0],'new');await lead(c,people[0],'contacted');await lead(c,people[1],'new',people[0].id);await lead(c,people[2],'new');await viewing(c,people[0],published,1,'confirmed');await viewing(c,people[0],published,2,'cancelled');await viewing(c,people[0],published,-2,'confirmed');await viewing(c,people[1],other,3,'confirmed',people[0].id);await viewing(c,people[2],foreign,1,'confirmed');});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=ANY($1::uuid[])",[leads]);await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE id=ANY($1::uuid[])",[viewings]);await c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=ANY($1::uuid[])",[people.map(p=>p.id)]);await c.query("UPDATE profiles SET state='suspended' WHERE id=ANY($1::uuid[])",[people.map(p=>p.id)]);});}finally{await pool.end();}});
it('B05 counts and previews match exact assigned fixture records and exclude foreign and personally owned-but-unassigned activity',async()=>{const before=Date.now(),d=(await new AgentDashboardController(identity(people[0])).overview(req)).data;expect(agentDashboard.parse(d)).toEqual(d);const legacy=(await new AdministrationController(identity(people[0])).dashboard(req)).data;expect(legacy.counts).toEqual(d.counts);expect(legacy).not.toHaveProperty('leases');expect(d.scope).toBe('assigned');expect(d.counts).toEqual({inventory:2,published:1,newLeads:2,upcoming:1});expect(d.inventory.map(r=>r.id).sort()).toEqual(listings.slice(0,2).sort());expect(d.newLeads.map(r=>r.id).sort()).toEqual(leads.slice(0,2).sort());expect(d.upcoming.map(r=>r.id)).toEqual([viewings[0]]);const privateFields=/"(?:email|phone|message|internal_note|private_address|unit_id|owner_id)"/;expect(JSON.stringify(d)).not.toMatch(privateFields);expect(JSON.stringify(d)).not.toContain(people[2].orgId);expect(JSON.stringify(d)).not.toContain(listings[3]);expect(Date.parse(d.asOf)).toBeGreaterThanOrEqual(before-1000);expect(Date.parse(d.asOf)).toBeLessThanOrEqual(Date.now()+1000);expect(d.definitions.newLeads).toContain('current CRM status');});
it('B05 manager scope comes from actual agency membership; role removal, cross-agency selection and empty-source states are explicit',async()=>{const forged={...people[0],roles:['admin','agency_manager']};expect((await new AgentDashboardController(identity(forged)).overview(req)).data.scope).toBe('assigned');await expect(new AgentDashboardController(identity({...people[0],orgId:foreignOrg})).overview(req)).rejects.toMatchObject({status:403});await transaction(workerActor,c=>c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=$1",[people[0].id]));try{await expect(new AgentDashboardController(identity(people[0])).overview(req)).rejects.toMatchObject({status:403});}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='active',version=version+1 WHERE user_id=$1",[people[0].id]));}const manager:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:org,roles:['admin','agency_manager']},d=(await new AgentDashboardController(identity(manager)).overview(req)).data;expect(d.scope).toBe('agency');expect(d.inventory.some(r=>r.id===listings[3])).toBe(false);const expected=(await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM listings WHERE organization_id=$1 AND status NOT IN('sold','leased','archived')",[org]))).rows[0].n;expect(d.counts.inventory).toBe(expected);await transaction(workerActor,async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[listings[3]]);await c.query("UPDATE leads SET status='contacted',version=version+1 WHERE id=$1",[leads[4]]);await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE id=$1",[viewings[4]]);});const empty=(await new AgentDashboardController(identity(people[2])).overview(req)).data;expect(empty.counts).toEqual({inventory:0,published:0,newLeads:0,upcoming:0});expect(empty.inventory).toEqual([]);expect(empty.newLeads).toEqual([]);expect(empty.upcoming).toEqual([]);expect(JSON.stringify(empty)).not.toMatch(/salesTotal|commission|revenue|performanceScore/);});
it('B05 count totals are independent of bounded stable previews and update from current source states',async()=>{const actor=people[0],controller=new AgentDashboardController(identity(actor)),before=(await controller.overview(req)).data.counts.inventory;await transaction(workerActor,async c=>{for(let i=0;i<7;i++)await property(c,actor,'draft');});const after=(await controller.overview(req)).data;expect(after.counts.inventory).toBe(before+7);expect(after.inventory).toHaveLength(5);expect((await controller.overview(req)).data.inventory.map(r=>r.id)).toEqual(after.inventory.map(r=>r.id));await transaction(workerActor,c=>c.query("UPDATE leads SET status='assigned',version=version+1 WHERE id=$1",[leads[0]]));expect((await controller.overview(req)).data.counts.newLeads).toBe(1);});
