import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {createRequire} from 'node:module';
import type {FastifyRequest} from 'fastify';
import {transaction,event,type Actor} from '../../packages/database/src/index';
import type {Identity} from '../../apps/api/src/platform/core';
import {AdministrationController} from '../../apps/api/src/administration/controller';
import {DiscoveryEventsController} from '../../apps/api/src/engagement/discovery-events';
import {projectAnalytics} from '../../apps/worker/src/analytics';
import {analyticsCSV} from '../../apps/api/src/administration/analytics';
import {marketAdmin,marketRequest} from '../support/market-admin';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});afterAll(()=>fixtures.end());
const admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin']},buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),ops=(a=admin)=>new AdministrationController(identity(a)),signals=new DiscoveryEventsController(identity(buyer)),req=(method='GET',url='/api/v1/ops/analytics')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),sentinel='S06_PRIVATE_MESSAGE_DOCUMENT_CONTACT_SENTINEL';
async function source(){const city='s06-'+crypto.randomUUID();const market=(await marketAdmin.create(marketRequest('POST','/api/v1/ops/geography/cities'),'cities',{kind:'cities',name:'S06 synthetic funnel fixture',slug:city,aliases:[],country:'CN',currency:'CNY',timezone:'Asia/Shanghai'})).data;const c=await fixtures.connect();try{await c.query('BEGIN');const d=crypto.randomUUID();await c.query("INSERT INTO districts(id,city_id,name,slug) VALUES($1,$2,'S06 synthetic district',$3)",[d,market.id,'s06-'+d]);const co=crypto.randomUUID();await c.query("INSERT INTO communities(id,district_id,name,slug,address,built_year,location) SELECT $1,$2,'S06 synthetic community',$3,address,built_year,location FROM communities LIMIT 1",[co,d,'s06-'+co]);const u=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT $1,organization_id,'80.00',2,1,1 FROM units LIMIT 1 RETURNING id",[co])).rows[0];const l=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'S06 synthetic available home',description,'sale','residential','CNY','123456.78','published',now() FROM listings WHERE agent_id IS NOT NULL LIMIT 1 RETURNING id,version,agent_id,organization_id",[u.id,'s06-'+crypto.randomUUID()])).rows[0];await c.query('COMMIT');return {city,l};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
it('S06 six declared consented source events project exact unique counts; retries, repeated-source events and concurrent workers cannot double count or expose private text',async()=>{
 const f=await source(),old=(await signals.consent(req())).data;if(!old.enabled)await signals.changeConsent(req('PATCH','/api/v1/me/analytics-consent'),{version:old.version,enabled:true});const day=new Date().toISOString().slice(0,10),filter={city:f.city,from:day,to:day};try{
 const r=req('POST','/api/v1/listings/'+f.l.id+'/impression'),body={eventId:crypto.randomUUID(),version:f.l.version,consent:true};await signals.impression(r,f.l.id,body);await signals.impression(r,f.l.id,body);await signals.impression(req('POST','/api/v1/listings/'+f.l.id+'/impression'),f.l.id,{...body,eventId:crypto.randomUUID()});await signals.view(req('POST','/api/v1/listings/'+f.l.id+'/view'),f.l.id,{...body,eventId:crypto.randomUUID()});
 // Trusted source fixtures exercise the transactional event port without bypassing analytics ingestion/deduplication.
 await transaction(buyer,async c=>{await event(c,buyer,f.l.id,'favorite.saved',{userId:buyer.id,privateText:sentinel});await event(c,buyer,f.l.id,'favorite.saved',{privateText:sentinel});await event(c,buyer,f.l.id,'message.sent',{message:sentinel,document:sentinel});});
 const lead=(await fixtures.query("INSERT INTO leads(user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message) VALUES($1,$2,$3,$4,'listing','S06 synthetic person','synthetic@example.test','+8613800000000',$5) RETURNING id",[buyer.id,f.l.organization_id,f.l.agent_id,f.l.id,sentinel])).rows[0];const viewing=(await transaction(admin,c=>c.query("INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at) VALUES($1,$2,$3,'2044-01-01'::timestamptz+$4*interval '1 hour','2044-01-01'::timestamptz+($4+1)*interval '1 hour') RETURNING id",[f.l.id,buyer.id,f.l.agent_id,Math.floor(Math.random()*100000)]),fixtures)).rows[0];const quote=(await fixtures.query("INSERT INTO quotes(provider_id,organization_id,user_id,description,city) SELECT id,organization_id,$1,$2,$3 FROM providers LIMIT 1 RETURNING id",[buyer.id,sentinel,f.city])).rows[0];expect(quote).toBeDefined();await transaction(buyer,async c=>{for(const [id,kind] of [[lead.id,'inquiry.submitted'],[viewing.id,'viewing.requested'],[quote.id,'quote.requested']]){await event(c,buyer,id,kind,{privateText:sentinel});await event(c,buyer,id,kind,{privateText:sentinel});}});
 const pending=(await ops().analytics(req(),filter)).data;expect(pending.projectionLag).toBe(6);await Promise.all([projectAnalytics(),projectAnalytics()]);const report=(await ops().analytics(req(),filter)).data;expect(report.projectionLag).toBe(0);expect(report.rows.map(r=>r.count)).toEqual([1,1,1,1,1,1]);await projectAnalytics();expect((await ops().analytics(req(),filter)).data.rows).toEqual(report.rows);expect((await ops().analytics(req(),{...filter,category:'resale'})).data.rows.map(r=>r.count)).toEqual([1,1,1,1,1,0]);expect((await ops().analytics(req(),{...filter,category:'renovation'})).data.rows.map(r=>r.count)).toEqual([0,0,0,0,0,1]);expect(JSON.stringify(report)+analyticsCSV(report)).not.toContain(sentinel);expect((await ops().audit(req(),{resourceId:lead.id})).data.rows).toHaveLength(2);expect(JSON.stringify((await ops().audit(req(),{resourceId:lead.id})).data)).not.toContain(sentinel);expect((await transaction(admin,c=>c.query("UPDATE analytics_events SET kind='quote_requested'"))).rowCount).toBe(0);expect((await transaction(admin,c=>c.query('UPDATE analytics_daily SET count=999'))).rowCount).toBe(0);
 }finally{const current=(await signals.consent(req())).data;if(!old.enabled&&current.enabled)await signals.changeConsent(req('PATCH','/api/v1/me/analytics-consent'),{version:current.version,enabled:false});}
});
it('S06 actual administrator scope, explicit consent/version/state, validated filters and private projection policies deny forged access',async()=>{for(const a of [buyer,{...buyer,roles:['admin']}]){await expect(ops(a).analytics(req(),{from:'2026-10-06',to:'2026-10-06'})).rejects.toMatchObject({status:403});await expect(ops(a).audit(req(),{})).rejects.toMatchObject({status:403});expect((await transaction(a,c=>c.query('SELECT * FROM analytics_events'))).rows).toEqual([]);await expect(transaction(a,c=>c.query('SELECT project_analytics_batch(10)'))).rejects.toMatchObject({code:'42501'});}await expect(ops().analytics(req(),{from:'2026-02-30',to:'2026-10-06'})).rejects.toThrow();await expect(ops().analytics(req(),{from:'2027-01-01',to:'2026-01-01'})).rejects.toThrow();const old=(await signals.consent(req())).data;await expect(signals.changeConsent(req('PATCH'),{version:old.version,enabled:old.enabled})).rejects.toMatchObject({status:409});await expect(signals.changeConsent(req('PATCH'),{version:old.version+100,enabled:!old.enabled})).rejects.toMatchObject({status:409});await expect(signals.impression(req('POST'),crypto.randomUUID(),{eventId:crypto.randomUUID(),version:1,consent:true})).rejects.toMatchObject({status:403});});
it('S06 direct agent and provider inquiries use declared scoped categories without exposing their private contact/message fixtures',async()=>{const old=(await signals.consent(req())).data;if(!old.enabled)await signals.changeConsent(req('PATCH'),{version:old.version,enabled:true});const day=new Date().toISOString().slice(0,10);try{for(const [type,table,category] of [['agent','agents','agents'],['provider','providers','renovation']]){let target=(await fixtures.query('SELECT id,city,organization_id FROM '+table+' WHERE city IS NOT NULL LIMIT 1')).rows[0];if(!target){const id=crypto.randomUUID();const sql=type==='agent'?"INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city) SELECT $1,user_id,organization_id,'S06 synthetic scoped agent',$2,biography,languages,districts,'bj' FROM agents LIMIT 1 RETURNING id,city,organization_id":"INSERT INTO providers(id,organization_id,name,slug,description,categories,districts,photos,city) SELECT $1,organization_id,'S06 synthetic scoped provider',$2,description,categories,districts,photos,'bj' FROM providers LIMIT 1 RETURNING id,city,organization_id";target=(await transaction(admin,c=>c.query(sql,[id,'s06-'+id]),fixtures)).rows[0];}expect(target).toBeDefined();const filter={city:target.city,category,from:day,to:day},before=(await ops().analytics(req(),filter)).data.rows.find(r=>r.kind==='inquiry_submitted')!.count;const lead=(await fixtures.query("INSERT INTO leads(user_id,organization_id,resource_id,resource_type,name,email,phone,message) VALUES($1,$2,$3,$4,'S06 synthetic contact','private@example.test','+8613800000000',$5) RETURNING id",[buyer.id,target.organization_id,target.id,type,sentinel])).rows[0];await transaction(buyer,async c=>{await event(c,buyer,lead.id,'inquiry.submitted',{privateText:sentinel});await event(c,buyer,lead.id,'inquiry.submitted',{privateText:sentinel});});await projectAnalytics();const after=(await ops().analytics(req(),filter)).data;expect(after.rows.find(r=>r.kind==='inquiry_submitted')!.count).toBe(before+1);expect(JSON.stringify(after)).not.toContain(sentinel);}}finally{const current=(await signals.consent(req())).data;if(!old.enabled&&current.enabled)await signals.changeConsent(req('PATCH'),{version:current.version,enabled:false});}});
