import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import {DiscoveryController} from '../../apps/api/src/geography/controller';
import {responses} from '../../packages/contracts/src/responses';
import type {Identity} from '../../apps/api/src/platform/core';
const buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},engagement=new EngagementController({actor:async()=>buyer} as unknown as Identity),created:string[]=[];
const req=()=>({method:'POST',url:'/api/v1/inquiries',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
const body=(id:string)=>({resourceId:id,resourceType:'listing',resourceVersion:1,name:'Synthetic business buyer',email:'c03@example.test',phone:'123456789',message:'Please confirm this office is suitable for our business.',consent:true});
async function fixture(){return transaction(workerActor,async c=>{const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'C03 office fixture',description,'rent','commercial','CNY','2400.75','year',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING *",['c03-'+crypto.randomUUID()])).rows[0];created.push(row.id);await c.query("INSERT INTO commercial_details(listing_id,property_type,gross_area,usable_area,area_basis,rent_basis,fit_out,floor,parking_spaces,permitted_uses) VALUES($1,'office','180.25','150.75','usable','per_area','Furnished',7,2,ARRAY['Office','Research'])",[row.id]);return row;});}
afterAll(async()=>{try{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[created]));}finally{await pool.end();}});
it('C03 public business facts and inquiry preserve an immutable exact submitted context in the assigned agency without private disclosure',async()=>{const row=await fixture(),detail=responses.DiscoveryController_listing.parse(JSON.parse(JSON.stringify((await new DiscoveryController().listing(row.id,'bj')).data)));expect(detail).toMatchObject({propertyType:'office',grossArea:'180.25',usableArea:'150.75',areaBasis:'usable',priceBasis:'per_area',commercialFloor:7,parkingSpaces:2,fitOut:'Furnished'});expect(JSON.stringify(detail)).not.toMatch(/private_address|organization_id|owner_id/);const request=req(),first=await engagement.inquiry(request,body(row.id));expect((await engagement.inquiry(request,body(row.id))).data.id).toBe(first.data.id);const lead=(await transaction(workerActor,c=>c.query('SELECT * FROM leads WHERE id=$1',[first.data.id]))).rows[0];expect(lead).toMatchObject({organization_id:row.organization_id,agent_id:row.agent_id,resource_id:row.id,resource_version:1,commercial_context:{segment:'commercial',transaction:'rent',propertyType:'office',currency:'CNY',price:'2400.75',priceBasis:'per_area',rentPeriod:'year',areaBasis:'usable',grossArea:'180.25',usableArea:'150.75',fitOut:'Furnished',floor:7,parkingSpaces:2,permittedUses:['Office','Research'],version:1}});const assigned=new EngagementController({actor:async()=>({id:'00000000-0000-4000-8000-000000000003',orgId:row.organization_id,roles:['agent']})} as unknown as Identity);expect((await assigned.leads(req())).data.some(x=>x.id===lead.id)).toBe(true);await transaction(workerActor,c=>c.query("UPDATE listings SET price='2600.75',version=version+1 WHERE id=$1",[row.id]));expect((await transaction(buyer,c=>c.query('SELECT commercial_context FROM leads WHERE id=$1',[lead.id]))).rows[0].commercial_context.price).toBe('2400.75');await expect(transaction(workerActor,c=>c.query("UPDATE leads SET commercial_context='{}' WHERE id=$1",[lead.id]))).rejects.toMatchObject({code:'23514'});const foreign=new EngagementController({actor:async()=>({id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agency_manager']})} as unknown as Identity);expect((await foreign.leads(req())).data.some(x=>x.id===lead.id)).toBe(false);await expect(foreign.lead(req(),lead.id,{version:1,status:'contacted'})).rejects.toMatchObject({status:404});});
it('C03 commercial submissions require a current version and reject withdrawn/expired offers at API and direct database insertion',async()=>{const row=await fixture();await expect(engagement.inquiry(req(),{...body(row.id),resourceVersion:undefined})).rejects.toMatchObject({status:400});await expect(engagement.inquiry(req(),{...body(row.id),resourceVersion:2})).rejects.toMatchObject({status:409});await expect(transaction(buyer,c=>c.query("INSERT INTO leads(user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message) VALUES($1,$2,$3,$4,'listing','Buyer','c03@example.test','123456789','Office inquiry')",[buyer.id,row.organization_id,row.agent_id,row.id]))).rejects.toMatchObject({code:'23514'});await expect(transaction(buyer,c=>c.query("INSERT INTO leads(user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message,resource_version) VALUES($1,$2,NULL,$3,'listing','Buyer','c03@example.test','123456789','Office inquiry',1)",[buyer.id,row.organization_id,row.id]))).rejects.toMatchObject({code:'42501'});await transaction(workerActor,c=>c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=$1",[row.id]));await expect(engagement.inquiry(req(),body(row.id))).rejects.toMatchObject({status:404});await expect(new DiscoveryController().listing(row.id,'bj')).rejects.toMatchObject({status:404});const expired=await fixture();await transaction(workerActor,c=>c.query("UPDATE listings SET expires_at=now()-interval '1 second' WHERE id=$1",[expired.id]));await expect(engagement.inquiry(req(),body(expired.id))).rejects.toMatchObject({status:404});});
