import {createRequire} from 'node:module';
import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {DraftInventoryController} from '../../apps/api/src/inventory/drafts';
import type {Identity} from '../../apps/api/src/platform/core';
import {requireCommercialFacts} from '../../apps/api/src/inventory/commercial-facts';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),pg=require('pg');
const agent:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:'10000000-0000-4000-8000-000000000001',roles:['agent']},controller=new DraftInventoryController({actor:async()=>agent} as unknown as Identity),created:string[]=[];
const req=()=>({method:'POST',url:'/api/v1/ops/listings',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
const commercial={propertyType:'office',grossArea:'180.25',usableArea:'150.75',areaBasis:'usable',priceBasis:'per_area',fitOut:'Furnished',floor:7,parkingSpaces:2,permittedUses:['Office','Research']};
const base={unitId:'10000000-0000-4000-8000-000000001000',title:'C01 annual office offer',description:'Synthetic annual commercial per-area rent with declared usable pricing area and office use.',transaction:'rent',segment:'commercial',currency:'CNY',price:'2400.75',rentPeriod:'year',furnishing:'Furnished',availableFrom:null,features:[],commercial};
afterAll(async()=>{try{await transaction(workerActor,c=>c.query('DELETE FROM listings WHERE id=ANY($1::uuid[])',[created]));}finally{await pool.end();}});
it('C01 creates an annual-per-usable-area office offer with exact decimal facts, scoped draft read and versioned edits; sale basis has no rental period',async()=>{const request=req(),first=(await controller.create(request,base)).data;created.push(first.id);expect((await controller.create(request,base)).data.id).toBe(first.id);expect(first).toMatchObject({price:'2400.75',rent_period:'year',segment:'commercial',commercial:{...commercial,version:1}});const stored=(await transaction(workerActor,c=>c.query('SELECT * FROM commercial_details WHERE listing_id=$1',[first.id]))).rows[0];expect(stored).toMatchObject({gross_area:'180.25',usable_area:'150.75',area_basis:'usable',sale_basis:null,rent_basis:'per_area'});await transaction(agent,c=>requireCommercialFacts(c,first.id));const {unitId:_unit,...edit}=base;void _unit;expect((await controller.update(req(),first.id,{...edit,price:'2500.25',version:1,commercial:{...commercial,parkingSpaces:3}})).data).toMatchObject({price:'2500.25',version:2,commercial:{parkingSpaces:3,version:2}});await expect(controller.update(req(),first.id,{...edit,version:1})).rejects.toMatchObject({status:409});const foreign=new DraftInventoryController({actor:async()=>({id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agent']})} as unknown as Identity);await expect(foreign.read(req(),first.id)).rejects.toMatchObject({status:404});await expect(foreign.update(req(),first.id,{...edit,version:2})).rejects.toMatchObject({status:404});const sale=(await controller.create(req(),{...base,transaction:'sale',rentPeriod:null,price:'3500000.75',commercial:{...commercial,priceBasis:'total',areaBasis:'gross'}})).data;created.push(sale.id);expect(sale).toMatchObject({rent_period:null,commercial:{priceBasis:'total',areaBasis:'gross'}});expect((await transaction(workerActor,c=>c.query('SELECT sale_basis,rent_basis FROM commercial_details WHERE listing_id=$1',[sale.id]))).rows[0]).toEqual({sale_basis:'total',rent_basis:null});});
it('C01 rejects absent price/area definitions, nonpositive/invalid usable area, contradictory transactions and mixed subtype fields; SQL cannot store a sale basis on a rental',async()=>{for(const facts of [{...commercial,priceBasis:undefined},{...commercial,areaBasis:undefined},{...commercial,usableArea:'0.00'},{...commercial,usableArea:'180.26'},{...commercial,grossArea:'1e4'},{...commercial,usableArea:'150.755'},{...commercial,parkingSpaces:-1}])await expect(controller.create(req(),{...base,commercial:facts})).rejects.toMatchObject({name:'ZodError'});for(const input of [{...base,commercial:undefined},{...base,rentPeriod:null},{...base,transaction:'sale',rentPeriod:'year'},{...base,segment:'residential'}])await expect(controller.create(req(),input)).rejects.toMatchObject({name:'ZodError'});const row=(await controller.create(req(),base)).data;created.push(row.id);await expect(transaction(workerActor,c=>c.query('UPDATE commercial_details SET rent_basis=NULL WHERE listing_id=$1',[row.id]))).rejects.toMatchObject({code:'23514'});await expect(transaction(workerActor,c=>c.query("UPDATE commercial_details SET sale_basis='total' WHERE listing_id=$1",[row.id]))).rejects.toMatchObject({code:'23514'});await expect(transaction(workerActor,c=>c.query('UPDATE commercial_details SET usable_area=0 WHERE listing_id=$1',[row.id]))).rejects.toMatchObject({code:'23514'});});

it('C01 schema-owner bootstrap imports unknown historical areas without inventing a basis; application actors cannot forge that legacy marker',async()=>{const bootstrap=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL});const client=await bootstrap.connect();try{await client.query('BEGIN');for(const tx of ['sale','rent']){const listing=(await client.query("INSERT INTO listings(unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status) SELECT unit_id,organization_id,agent_id,$1,'C01 legacy bootstrap fixture','Unknown historical area definition is deliberately retained',$2,'commercial','CNY','1.00',CASE WHEN $2='rent' THEN 'year' ELSE NULL END,'draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",['c01-bootstrap-'+crypto.randomUUID(),tx])).rows[0];const imported=(await client.query("INSERT INTO commercial_details(listing_id,property_type,gross_area,usable_area,fit_out,permitted_uses,rent_basis,sale_basis,area_basis,legacy_incomplete) VALUES($1,'office','180.25','150.75','Basic fit-out',ARRAY['Office'],$2,$3,NULL,true) RETURNING *",[listing.id,tx==='rent'?'per_area':null,tx==='sale'?'total':null])).rows[0];expect(imported).toMatchObject({legacy_incomplete:true,area_basis:null,sale_basis:tx==='sale'?'total':null,rent_basis:tx==='rent'?'per_area':null});}await client.query('ROLLBACK');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();await bootstrap.end();}const row=(await controller.create(req(),base)).data;created.push(row.id);await expect(transaction(agent,c=>c.query('UPDATE commercial_details SET legacy_incomplete=true WHERE listing_id=$1',[row.id]))).rejects.toMatchObject({code:'42501'});});
