import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {pool,transaction} from '../../packages/database/src/index';
import {workerActor,initializeSearch,createProcessor} from '../../apps/worker/src/processor';
import {listingFilters,publicListingSearchDocument} from '../../packages/contracts/src/index';
import {searchListings,compileListingSearch} from '../../apps/api/src/geography/search';
afterAll(()=>pool.end());
it('C02 furnished office rentals compare explicit periods, price bases and area definitions in SQL and indexed search',async()=>{
 await initializeSearch();const fixtures=await transaction(workerActor,async c=>{const rows=[];for(const entry of [{period:'month',basis:'per_area',area:'usable',fit:'Furnished',type:'office'},{period:'year',basis:'per_area',area:'usable',fit:'Furnished',type:'office'},{period:'month',basis:'total',area:'usable',fit:'Furnished',type:'office'},{period:'month',basis:'per_area',area:'gross',fit:'Furnished',type:'office'},{period:'month',basis:'per_area',area:'usable',fit:'Basic fit-out',type:'office'},{period:'month',basis:'per_area',area:'usable',fit:'Furnished',type:'retail'}]){const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'C02 synthetic office fixture',description,'rent','commercial','CNY','2400.75',$2,photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",['c02-'+crypto.randomUUID(),entry.period])).rows[0];await c.query("INSERT INTO commercial_details(listing_id,property_type,gross_area,usable_area,fit_out,permitted_uses,rent_basis,area_basis,parking_spaces) VALUES($1,$2,'180.25','150.75',$3,ARRAY['Office'],$4,$5,2)",[row.id,entry.type,entry.fit,entry.basis,entry.area]);const event=(await c.query("INSERT INTO outbox(aggregate_id,kind,payload,dispatched_at) VALUES($1,'listing.published','{}',now()) RETURNING id",[row.id])).rows[0];rows.push({...row,event:event.id});}return rows;});
 try{for(const row of fixtures)await createProcessor()({data:{id:row.event}});const criteria=listingFilters.parse({city:'bj',segment:'commercial',transaction:'rent',propertyType:'office',fitOut:'Furnished',permittedUse:'Office',rentPeriod:'month',priceBasis:'per_area',areaBasis:'usable',minArea:150,maxArea:151,minPrice:'2400.75',maxPrice:'2400.75',sort:'price_asc'}),found=await searchListings(criteria);expect(found.data.map(x=>x.id)).toEqual([fixtures[0].id]);expect(found.meta).toMatchObject({searchMode:'meilisearch',rentalPeriod:'month',billingPeriodSource:'requested'});expect(found.data[0]).toMatchObject({grossArea:'180.25',usableArea:'150.75',areaBasis:'usable',priceBasis:'per_area',fitOut:'Furnished',permittedUses:['Office']});expect((await searchListings(criteria,'http://127.0.0.1:1')).data.map(x=>x.id)).toEqual([fixtures[0].id]);expect((await searchListings({...criteria,rentPeriod:'year'})).data.map(x=>x.id)).toEqual([fixtures[1].id]);expect((await searchListings({...criteria,priceBasis:'total'})).data.map(x=>x.id)).toEqual([fixtures[2].id]);expect((await searchListings({...criteria,areaBasis:'gross',minArea:180,maxArea:181})).data.map(x=>x.id)).toEqual([fixtures[3].id]);const doc=publicListingSearchDocument(found.data[0]);expect(doc).toMatchObject({grossAreaNumber:180.25,usableAreaNumber:150.75,projectionSchemaVersion:5});expect(doc).not.toHaveProperty('organization_id');expect(compileListingSearch(criteria).where).toContain('"usableArea"::numeric');expect(compileListingSearch(criteria).filter).toContain('permittedUses = "Office"');
 }finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[fixtures.map(x=>x.id)]));}
});
it('C02 rejects residential filters and incomplete commercial comparison bases rather than normalizing months to years',()=>{const base={segment:'commercial',transaction:'rent',priceBasis:'per_area',areaBasis:'usable',rentPeriod:'month',minPrice:'1.00'};for(const input of [{...base,rentPeriod:undefined},{...base,priceBasis:undefined},{...base,areaBasis:undefined},{...base,transaction:undefined},{...base,beds:2},{...base,rentalMode:'entire'},{segment:'commercial',minArea:1},{segment:'commercial',sort:'area_desc'},{propertyType:'office'}])expect(listingFilters.safeParse(input).success).toBe(false);expect(listingFilters.safeParse({segment:'commercial',transaction:'rent',propertyType:'office',fitOut:'Furnished'}).success).toBe(true);});
