import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import {ConversationsController} from '../../apps/api/src/engagement/conversations';
import {LeadAssignmentsController} from '../../apps/api/src/engagement/lead-assignments';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',foreign='10000000-0000-4000-8000-000000000005',buyer:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']},other:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:org,roles:['admin','agency_manager']},people:(Actor&{agent:string})[]=[],leads:string[]=[],threads:string[]=[];
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),engagement=(a:Actor)=>new EngagementController(identity(a)),conversations=(a:Actor)=>new ConversationsController(identity(a)),req=(url='/api/v1/inquiries')=>({method:'POST',url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
beforeAll(async()=>{await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'M01 customer',true)",[buyer.id,'m01-'+buyer.id,'m01-'+buyer.id+'@example.test']);for(const agency of [org,org,foreign]){const id=crypto.randomUUID(),agent=crypto.randomUUID();await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'M01 professional',true)",[id,'m01-'+id,'m01-'+id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,'agent')",[id,agency]);await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'M01 synthetic agent',$4,'Synthetic membership acceptance fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,id,agency,'m01-'+agent]);people.push({id,agent,orgId:agency,roles:['agent']});}});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=ANY($1::uuid[])",[leads]);await c.query("UPDATE conversations SET state='closed',version=version+1 WHERE id=ANY($1::uuid[])",[threads]);await c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=ANY($1::uuid[])",[people.map(p=>p.id)]);await c.query("UPDATE profiles SET state='archived' WHERE id=ANY($1::uuid[])",[[buyer.id,...people.map(p=>p.id)]]);});}finally{await pool.end();}});
async function inquiry(){const r=(await engagement(buyer).inquiry(req(),{resourceId:people[0].agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M01 customer',email:'fixture@example.test',phone:'123456789',message:'A real linked inquiry for this agent',consent:true})).data;leads.push(r.id);threads.push(r.conversationId!);return r;}
it('M01 an actual account inquiry persists exact resource context and customer/assigned-agent grants before either participant reads or sends',async()=>{const lead=await inquiry(),id=lead.conversationId!;const own=(await conversations(buyer).detail(req(),id)).data,assigned=(await conversations(people[0]).detail(req(),id)).data;expect(own).toMatchObject({lead_id:lead.id,resource_id:people[0].agent,resource_type:'agent',resource_version:1,state:'active'});expect(assigned.members.map(m=>m.user_id)).toContain(buyer.id);expect(assigned.members.map(m=>m.user_id)).toContain(people[0].id);expect((await engagement(buyer).conversations(req())).data.some(r=>r.id===id)).toBe(true);const sent=await engagement(people[0]).message(req(),id,{body:'Your inquiry reached its assigned agent.',clientId:crypto.randomUUID()});expect((await engagement(buyer).messages(req(),id)).data.some(m=>m.id===sent.data.id)).toBe(true);});
it('M01 unrelated same-agency and foreign actors cannot read, send, insert membership or mutate source-owned context, even with broader supplied role labels',async()=>{const lead=await inquiry(),id=lead.conversationId!;for(const a of [other,people[1],people[2],{...people[1],roles:['admin','agency_manager']}]){await expect(conversations(a).detail(req(),id)).rejects.toMatchObject({status:404});await expect(engagement(a).messages(req(),id)).rejects.toMatchObject({status:404});await expect(engagement(a).message(req(),id,{body:'Guessed ID attack',clientId:crypto.randomUUID()})).rejects.toMatchObject({status:404});expect((await engagement(a).conversations(req())).data.some(r=>r.id===id)).toBe(false);}await expect(transaction(people[1],c=>c.query("INSERT INTO conversation_members(conversation_id,user_id,kind,provenance) VALUES($1,$2,'agent','recorded_lead')",[id,people[1].id]))).rejects.toMatchObject({code:'42501'});await expect(transaction(buyer,c=>c.query('UPDATE conversations SET agent_id=$2,version=version+1 WHERE id=$1',[id,people[1].agent]))).rejects.toMatchObject({code:'42501'});await expect(transaction(buyer,c=>c.query('INSERT INTO messages(conversation_id,sender_id,client_id,sequence,body) VALUES($1,$2,$3,1000,$4)',[id,people[0].id,crypto.randomUUID(),'Impersonation']))).rejects.toMatchObject({code:'42501'});});
it('M01 current lead reassignment transfers persisted grants and immediately revokes the old agent; membership revocation denies subsequent reads',async()=>{const lead=await inquiry(),id=lead.conversationId!,assignments=new LeadAssignmentsController(identity(manager));await assignments.assign(req('/api/v1/ops/leads/'+lead.id+'/assignment'),lead.id,{version:1,agentId:people[1].agent,reason:'Assign the actual inquiry to another eligible agent'});await expect(conversations(people[0]).detail(req(),id)).rejects.toMatchObject({status:404});expect((await conversations(people[1]).detail(req(),id)).data.members).toEqual(expect.arrayContaining([expect.objectContaining({user_id:people[1].id,kind:'agent'})]));expect((await conversations(buyer).detail(req(),id)).data.lead_id).toBe(lead.id);await transaction(workerActor,c=>c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=$1 AND organization_id=$2",[people[1].id,org]));try{await expect(conversations(people[1]).detail(req(),id)).rejects.toMatchObject({status:404});}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='active',version=version+1 WHERE user_id=$1 AND organization_id=$2",[people[1].id,org]));}});
