import {createRequire} from 'node:module';
import {DepositsController} from '../../apps/api/src/management/deposits';
import {ManagementController} from '../../apps/api/src/management/controller';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),legacyFixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});afterAll(()=>legacyFixtures.end());
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P10 verified synthetic tenant',true)",[tenant.id,'p10-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P10 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P10 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p10-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P10 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
async function financial(amount='250.25',charged='200.20'){const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(l.id),amount})).data,posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(p))).data,ch=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2028-01-01','2028-01-05',$3,'CNY') RETURNING id,version",[l.id,manager.orgId,charged])).rows[0]);return {...f,l,p:posted,ch};}

const deposits=(a=manager)=>new DepositsController(identity(a));
async function movement(id:string,patch:any={}){const l=(await deposits().ledger(req('GET'),id,{})).data;return {version:0,leaseId:id,leaseVersion:l.leaseVersion,unitVersion:l.unitVersion,grantVersion:l.grantVersion,liabilityVersion:l.liabilityVersion,kind:'received',direction:'increase',amount:'1000.10',currency:l.currency,reason:'Verified synthetic deposit receipt evidence.',confirm:true,...patch};}
it('P10 received, partial release and explicit bidirectional adjustments reconcile liability without changing rent totals',async()=>{const f=await financial(),statements=new ManagementController(identity(manager)),before=(await statements.statement(req('GET'),f.l.id)).data.totals;const r=(await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(f.l.id))).data;expect(r).toMatchObject({heldBefore:'0.00',heldAfter:'1000.10',liabilityVersion:1,native:true,actorId:manager.id});await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(f.l.id,{kind:'released',direction:'decrease',amount:'250.25'}));await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(f.l.id,{kind:'adjusted',direction:'increase',amount:'0.15'}));await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(f.l.id,{kind:'adjusted',direction:'decrease',amount:'0.05'}));const ledger=(await deposits().ledger(req('GET'),f.l.id,{})).data;expect(ledger).toMatchObject({held:'749.95',liabilityVersion:4,total:4,limit:20});expect(ledger.items.find((i:any)=>i.id===r.id)).toEqual(r);const after=(await statements.statement(req('GET'),f.l.id)).data;expect(after.totals).toEqual({...before,depositHeld:'749.95'});expect(after.payments).toHaveLength(1);expect(after.charges).toHaveLength(1);expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='deposit.received'",[r.id]))).rows[0].n).toBe(1);},90000);
it('P10 excess, stale authority, invalid decimals, wrong currency and unconfirmed movements deny without liability changes; SQL rejects bypass',async()=>{const f=await fixture(),l=await active(f);await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(l.id,{amount:'100.10'}));const x=await movement(l.id,{kind:'released',direction:'decrease',amount:'100.11'});await expect(deposits().create(req('POST','/api/v1/ops/deposits'),x)).rejects.toMatchObject({status:409});for(const patch of [{liabilityVersion:0},{leaseVersion:999},{unitVersion:999},{grantVersion:999},{currency:'USD'},{confirm:false},{amount:-1},{amount:1.01},{amount:'-1.00'},{amount:'1e2'},{amount:'0.00'},{amount:'1.00\n'},{reason:'x'},{direction:'increase'}])await expect(deposits().create(req('POST','/api/v1/ops/deposits'),{...x,...patch})).rejects.toBeDefined();await expect(transaction(manager,c=>c.query("INSERT INTO deposits(lease_id,organization_id,kind,direction,amount,currency,reason,actor_id,liability_version,lease_version,unit_version,grant_version,held_before,held_after) VALUES($1,$2,'released','decrease','100.11','CNY','Direct runtime excessive release',$3,2,$4,$5,$6,'100.10','0.00')",[l.id,manager.orgId,manager.id,x.leaseVersion,x.unitVersion,x.grantVersion]))).rejects.toMatchObject({code:'23514'});await expect(transaction(manager,c=>c.query("UPDATE deposits SET amount='0.01' WHERE lease_id=$1",[l.id]))).rejects.toMatchObject({code:'42501'});expect((await deposits().ledger(req('GET'),l.id,{})).data).toMatchObject({held:'100.10',liabilityVersion:1,total:1});},90000);
it('P10 concurrent releases use one liability version and receipt replay remains scoped after revocation',async()=>{const f=await fixture(),l=await active(f),r=req('POST','/api/v1/ops/deposits'),x=await movement(l.id,{amount:'100.10'}),first=(await deposits().create(r,x)).data;expect((await deposits().create(r,x)).data.id).toBe(first.id);const release=await movement(l.id,{kind:'released',direction:'decrease',amount:'70.05'}),results=await Promise.allSettled([deposits().create(req('POST','/api/v1/ops/deposits'),release),deposits().create(req('POST','/api/v1/ops/deposits'),release)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);expect((await deposits().ledger(req('GET'),l.id,{})).data).toMatchObject({held:'30.05',liabilityVersion:2,total:2});await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner revoked deposit recording authority.'});await expect(deposits().create(r,x)).rejects.toMatchObject({status:404});},90000);
it('P10 actual foreign finance and manager-only identities cannot read or mutate another deposit ledger',async()=>{const f=await fixture(),l=await active(f),x=await movement(l.id),foreign:Actor={id:crypto.randomUUID(),orgId:crypto.randomUUID(),roles:['finance']};await transaction(workerActor,async c=>{await c.query("INSERT INTO organizations(id,name,type) VALUES($1,'P10 synthetic foreign management','manager')",[foreign.orgId]);await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P10 synthetic foreign finance',true)",[foreign.id,'p10-foreign-'+foreign.id,foreign.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,'finance','active')",[foreign.id,foreign.orgId]);});try{await expect(deposits(foreign).ledger(req('GET'),l.id,{})).rejects.toMatchObject({status:404});await expect(deposits(foreign).create(req('POST','/api/v1/ops/deposits'),x)).rejects.toMatchObject({status:404});await expect(deposits(tenant).create(req('POST','/api/v1/ops/deposits'),x)).rejects.toMatchObject({status:403});const only:Actor={id:crypto.randomUUID(),orgId:manager.orgId,roles:['property_manager']};await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P10 synthetic manager only',true)",[only.id,'p10-only-'+only.id,only.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,'property_manager','active')",[only.id,only.orgId]);});await expect(deposits(only).create(req('POST','/api/v1/ops/deposits'),x)).rejects.toMatchObject({status:403});expect((await deposits().ledger(req('GET'),l.id,{})).data.total).toBe(0);}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='revoked',version=version+1 WHERE user_id=$1",[foreign.id]));}},90000);
it('P10 historical adjustments preserve prior decrease convention and unknown provenance, while subsequent native release is exact',async()=>{const f=await fixture(),l=await active(f);await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(l.id,{amount:'100.10'}));await legacyFixtures.query("INSERT INTO deposits(lease_id,organization_id,kind,amount,currency,reason,actor_id) VALUES($1,$2,'adjusted','1.01','CNY','Historical synthetic adjustment without source metadata',$3)",[l.id,manager.orgId,manager.id]);const ledger=(await deposits().ledger(req('GET'),l.id,{})).data;expect(ledger).toMatchObject({held:'99.09',liabilityVersion:2});expect(ledger.items.find((i:any)=>i.kind==='adjusted')).toMatchObject({direction:null,heldBefore:null,heldAfter:null,liabilityVersion:null,native:false});await deposits().create(req('POST','/api/v1/ops/deposits'),await movement(l.id,{kind:'released',direction:'decrease',amount:'99.09'}));expect((await deposits().ledger(req('GET'),l.id,{})).data.held).toBe('0.00');},90000);
