import {publishDevelopmentFixture} from '../support/development-review';
import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {DevelopmentProjectsController} from '../../apps/api/src/inventory/development-projects';
import {DevelopmentInventoryController} from '../../apps/api/src/inventory/development-inventory';
import {DevelopmentPricingController} from '../../apps/api/src/inventory/development-pricing';
import {InventoryController} from '../../apps/api/src/inventory/controller';
import {developmentFilters} from '../../packages/contracts/src/index';
import {searchDevelopments} from '../../apps/api/src/geography/development-search';
import type {Identity} from '../../apps/api/src/platform/core';
const actor:Actor={id:'00000000-0000-4000-8000-000000000006',orgId:'10000000-0000-4000-8000-000000000003',roles:['developer']},identity={actor:async()=>actor} as unknown as Identity,projects=new DevelopmentProjectsController(identity),inventory=new DevelopmentInventoryController(identity),pricing=new DevelopmentPricingController(identity),legacy=new InventoryController(identity),created:string[]=[];
const req=(method='POST')=>({method,url:'/api/v1/ops/developments',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
async function project(basis:'per_area'|'starting_total',minimum:string|null,communityId='10000000-0000-4000-8000-000000000040'){const source=(await projects.create(req(),{communityId,name:'N03 Discovery '+crypto.randomUUID(),slug:'n03-'+crypto.randomUUID(),description:'Synthetic development prices with a declared price basis and recorded layout range.'})).data;created.push(source.id);await pricing.update(req('PATCH'),source.id,{version:1,priceBasis:basis,minimum,maximum:null});const type=(await inventory.createType(req(),source.id,{projectVersion:2,name:'N03 2-bedroom range',beds:2,livingRooms:1,baths:1,areaMin:'80.25',areaMax:'95.75',mediaId:null,mediaVersion:null})).data;await inventory.updateType(req('PATCH'),source.id,type.id,{projectVersion:3,version:1,name:type.name,beds:2,livingRooms:1,baths:1,areaMin:'80.25',areaMax:'95.75',mediaId:null,mediaVersion:null,status:'published'});const published=await publishDevelopmentFixture(actor,source.id,4);return {...source,version:published.version};}
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query('DELETE FROM floor_plans WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM developments WHERE id=ANY($1::uuid[])',[created]);});}finally{await pool.end();}});
it('N03 development SQL search returns expected city/district/budget/basis/status/type-range IDs, stable pages, unknown prices and explicit public fields',async()=>{
 const per=await project('per_area','18456.75'),total=await project('starting_total','18456.75'),unknown=await project('per_area',null),otherDistrict=await project('per_area','18456.75','10000000-0000-4000-8000-000000000041'),district=(await transaction(null,c=>c.query('SELECT district_id FROM communities WHERE id=$1',[per.community_id]))).rows[0].district_id;const q=developmentFilters.parse({city:'bj',districtId:district,priceBasis:'per_area',minPrice:'18456.75',maxPrice:'18456.75',beds:2,minArea:'88.50',maxArea:'89.25',sort:'price_asc'}),found=await searchDevelopments(q);expect(found.data.map(row=>row.id)).toEqual([per.id]);expect(found.meta).toMatchObject({currency:'CNY',searchMode:'sql',budgetDefinition:'recorded-starting-price-in-selected-basis'});expect(found.data[0]).toMatchObject({price_min:'18456.75',price_max:null,price_basis:'per m²',availableTypes:0});expect(JSON.stringify(found)).not.toMatch(/organization_id|private_address|unit_id/);expect((await searchDevelopments({...q,priceBasis:'starting_total'})).data.map(row=>row.id)).toEqual([total.id]);expect((await searchDevelopments({...q,minArea:'100.00',maxArea:'110.00'})).data).toEqual([]);const unknownResult=await searchDevelopments(developmentFilters.parse({city:'bj',text:unknown.name}));expect(unknownResult.data[0]).toMatchObject({id:unknown.id,price_min:null,price_max:null,price_basis:'per m²'});await legacy.editDevelopment(req('PATCH'),per.id,{version:per.version,status:'sold_out'});expect((await searchDevelopments({...q,status:'sold_out'})).data.map(row=>row.id)).toEqual([per.id]);expect((await searchDevelopments({...q,status:'on_sale'})).data).toEqual([]);const all=developmentFilters.parse({city:'bj',priceBasis:'per_area',minPrice:'18456.75',maxPrice:'18456.75',sort:'price_asc',limit:1});const first=await searchDevelopments(all),second=await searchDevelopments({...all,page:2});expect([...first.data,...second.data].map(row=>row.id)).toEqual([per.id,otherDistrict.id].sort());expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/developments?city=bj&priceBasis=starting_total&minPrice=18456.75&maxPrice=18456.75').then(r=>r.json())).data.map((row:any)=>row.id)).toEqual([total.id]);
});
it('N03 rejects mixed/unspecified price basis and invalid ranges; developer pricing is scoped/versioned/decimal and SQL cannot advertise a maximum without a starting price',async()=>{
 for(const input of [{minPrice:'10.00'},{sort:'price_asc'},{priceBasis:'per_area',minPrice:'20.00',maxPrice:'10.00'},{minArea:'100.00',maxArea:'90.00'},{priceBasis:'total_inferred'},{priceBasis:'per_area',minPrice:'1e5'}])expect(developmentFilters.safeParse(input).success).toBe(false);await expect(searchDevelopments(developmentFilters.parse({city:'bj',currency:'USD',priceBasis:'per_area',minPrice:'1.00'}))).rejects.toMatchObject({status:400});const source=await project('starting_total','2450000.75');await expect(pricing.update(req('PATCH'),source.id,{version:1,priceBasis:'starting_total',minimum:'2450000.75',maximum:null})).rejects.toMatchObject({status:409});for(const minimum of [2450000.75,'-1.00','0.00','1e6','1.005'])await expect(pricing.update(req('PATCH'),source.id,{version:source.version,priceBasis:'starting_total',minimum,maximum:null})).rejects.toMatchObject({name:'ZodError'});await expect(transaction(workerActor,c=>c.query('UPDATE developments SET price_min=NULL,price_max=1 WHERE id=$1',[source.id]))).rejects.toMatchObject({code:'23514'});const other=new DevelopmentPricingController({actor:async()=>({...actor,id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005'})} as unknown as Identity);await expect(other.update(req('PATCH'),source.id,{version:source.version,priceBasis:'per_area',minimum:'30000.25',maximum:null})).rejects.toMatchObject({status:404});
});
