import '../support/env';
import fs from 'node:fs';
import {MediaController} from '../../apps/api/src/inventory/media';
import {RichMediaController} from '../../apps/api/src/inventory/rich-media';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {DevelopmentProjectsController} from '../../apps/api/src/inventory/development-projects';
import {DevelopmentInventoryController} from '../../apps/api/src/inventory/development-inventory';
import {InventoryController} from '../../apps/api/src/inventory/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const actor:Actor={id:'00000000-0000-4000-8000-000000000006',orgId:'10000000-0000-4000-8000-000000000003',roles:['developer']},identity={actor:async()=>actor} as unknown as Identity,projects=new DevelopmentProjectsController(identity),inventory=new DevelopmentInventoryController(identity),legacy=new InventoryController(identity),created:string[]=[],assets:string[]=[];
const request=(method='POST')=>({method,url:'/api/v1/ops/developments',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
const facts={name:'Range type',beds:2,livingRooms:1,baths:1,areaMin:'80.25',areaMax:'95.75',mediaId:null,mediaVersion:null};
async function fixture(){const source=(await projects.create(request(),{communityId:'10000000-0000-4000-8000-000000000040',slug:'n02-'+crypto.randomUUID(),name:'N02 inventory fixture',description:'A synthetic floor-plan type range and separately recorded offered units.'})).data;created.push(source.id);return source;}
async function approvedDrawing(projectId:string,projectVersion:number){const upload=new MediaController(identity),bytes=fs.readFileSync('packages/test-support/assets/property-plan.png'),intent=(await upload.intent(request(),{mime:'image/png',size:bytes.length,rights:'Project generated synthetic drawing',visibility:'public',purpose:'floor_plan'})).data;assets.push(intent.id);const url=new URL(intent.uploadUrl,'http://localhost');await upload.content({headers:{'content-type':'image/png'},query:{signature:url.searchParams.get('signature')}} as unknown as FastifyRequest,intent.id,bytes);const rich=new RichMediaController(identity),attached=(await rich.attach(request(),'developments',projectId,{assetId:intent.id,kind:'floor_plan',title:'Synthetic approved range drawing',version:projectVersion,position:0,metadata:{caption:'Illustrative synthetic plan, not measured.',hotspots:[]}})).data;await expect(inventory.createType(request(),projectId,{...facts,projectVersion:projectVersion+1,mediaId:attached.id,mediaVersion:attached.version})).rejects.toMatchObject({status:400});const moderator=new RichMediaController({actor:async()=>({id:'00000000-0000-4000-8000-000000000008',orgId:null,roles:['moderator']})} as unknown as Identity);await moderator.review(request(),attached.id,{decision:'approved',version:attached.version,reason:'Reviewed synthetic drawing and publication rights'});return {id:attached.id,version:attached.version+1};}
afterAll(async()=>{try{await transaction(workerActor,async c=>{const units=(await c.query('DELETE FROM development_offered_units WHERE development_id=ANY($1::uuid[]) RETURNING unit_id',[created])).rows.map(row=>row.unit_id);await c.query('DELETE FROM units WHERE id=ANY($1::uuid[])',[units]);await c.query('DELETE FROM listing_media WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM media_assets WHERE id=ANY($1::uuid[])',[assets]);await c.query('DELETE FROM floor_plans WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM buildings WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM development_phases WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM developments WHERE id=ANY($1::uuid[])',[created]);});}finally{await pool.end();}});
it('N02 publishes exact decimal range with an approved drawing, keeps types distinct from individual offered units and derives nonnegative availability with timestamps',async()=>{
 const source=await fixture(),building=(await projects.createBuilding(request(),source.id,{projectVersion:1,phaseId:null,name:'N02 building',slug:'n02-building-'+crypto.randomUUID(),floors:10,completedYear:null})).data;
 const drawing=await approvedDrawing(source.id,2);const type=(await inventory.createType(request(),source.id,{...facts,projectVersion:4,mediaId:drawing.id,mediaVersion:drawing.version})).data;expect(type).toMatchObject({area_min:'80.25',area_max:'95.75',publication_status:'draft',inventory_mode:'units',available:0,projectVersion:5});const unit=(await inventory.createUnit(request(),source.id,{projectVersion:5,typeVersion:1,floorPlanId:type.id,buildingId:building.id,unitLabel:'Recorded unit A',area:'88.50',status:'available'})).data;expect(unit).toMatchObject({floor_plan_id:type.id,status:'available',projectVersion:6});expect(unit.unit_id).not.toBe(type.id);expect((await inventory.units(request(),source.id)).data[0]).toMatchObject({area:'88.50',building_id:building.id});const media=(await transaction(workerActor,c=>c.query('SELECT version FROM listing_media WHERE id=$1',[drawing.id]))).rows[0];const published=(await inventory.updateType(request('PATCH'),source.id,type.id,{...facts,projectVersion:6,version:1,status:'published',mediaId:drawing.id,mediaVersion:media.version})).data;expect(published.published_at).toBeTruthy();expect(published.available).toBe(1);await legacy.editDevelopment(request('PATCH'),source.id,{version:7,status:'on_sale'});const publicDetail=(await fetch('http://localhost:8088/api/v1/developments/'+source.id).then(r=>r.json())).data;expect(publicDetail.floorPlans).toHaveLength(1);expect(publicDetail.floorPlans[0]).toMatchObject({area_min:'80.25',area_max:'95.75',available:1,photo:published.photo});expect((await inventory.updateUnit(request('PATCH'),source.id,unit.id,{projectVersion:8,version:1,status:'reserved'})).data.projectVersion).toBe(9);expect((await legacy.plans(request(),source.id)).data[0].available).toBe(0);await expect(legacy.editPlan(request('PATCH'),type.id,{available:2,version:9})).rejects.toMatchObject({status:409});await expect(transaction(workerActor,c=>c.query('UPDATE floor_plans SET available=-1 WHERE id=$1',[type.id]))).rejects.toMatchObject({code:'23514'});await expect(transaction(workerActor,c=>c.query('UPDATE floor_plans SET available=2 WHERE id=$1',[type.id]))).rejects.toMatchObject({code:'23514'});expect((await projects.structure(request(),source.id)).data.project.inventory_at).toBeTruthy();
});
it('N02 invalid ranges, foreign/unapproved drawing, wrong building/area, stale versions and incompatible type changes are denied; draft types are private',async()=>{
 const source=await fixture();for(const [areaMin,areaMax] of [['95.75','80.25'],['0.00','10.00'],['80.255','95.75']])await expect(inventory.createType(request(),source.id,{...facts,projectVersion:1,areaMin,areaMax})).rejects.toMatchObject({name:'ZodError'});const foreignProject=await fixture(),foreignMedia=await approvedDrawing(foreignProject.id,1);await expect(inventory.createType(request(),source.id,{...facts,projectVersion:1,mediaId:foreignMedia.id,mediaVersion:foreignMedia.version})).rejects.toMatchObject({status:400});const type=(await inventory.createType(request(),source.id,{...facts,projectVersion:1})).data;await legacy.editDevelopment(request('PATCH'),source.id,{version:2,status:'on_sale'});expect((await fetch('http://localhost:8088/api/v1/developments/'+source.id).then(r=>r.json())).data.floorPlans).toEqual([]);expect((await transaction(null,c=>c.query('SELECT id FROM floor_plans WHERE id=$1',[type.id]))).rows).toEqual([]);const building=(await projects.createBuilding(request(),source.id,{projectVersion:3,phaseId:null,name:'N02 range building',slug:'n02-range-'+crypto.randomUUID(),floors:null,completedYear:null})).data;const body={projectVersion:4,typeVersion:1,floorPlanId:type.id,buildingId:building.id,unitLabel:'Range checked unit',area:'79.99',status:'available' as const};await expect(inventory.createUnit(request(),source.id,body)).rejects.toMatchObject({code:'23514'});await expect(inventory.createUnit(request(),source.id,{...body,area:'88.50',buildingId:crypto.randomUUID()})).rejects.toMatchObject({status:400});const unit=(await inventory.createUnit(request(),source.id,{...body,area:'88.50'})).data;await expect(inventory.updateUnit(request('PATCH'),source.id,unit.id,{projectVersion:4,version:1,status:'sold'})).rejects.toMatchObject({status:409});await expect(inventory.updateType(request('PATCH'),source.id,type.id,{...facts,projectVersion:5,version:1,status:'published',areaMin:'90.00'})).rejects.toMatchObject({code:'23514'});await expect(inventory.createUnit(request(),source.id,{...body,projectVersion:5,typeVersion:99,area:'88.50',unitLabel:'Stale type'})).rejects.toMatchObject({status:409});
});
