import {publishDevelopmentFixture} from '../support/development-review';
import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {DevelopmentProjectsController} from '../../apps/api/src/inventory/development-projects';
import {InventoryController} from '../../apps/api/src/inventory/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const created:string[]=[],organizations:string[]=[];
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query('DELETE FROM buildings WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM development_phases WHERE development_id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM developments WHERE id=ANY($1::uuid[])',[created]);await c.query('DELETE FROM memberships WHERE organization_id=ANY($1::uuid[])',[organizations]);await c.query('DELETE FROM organizations WHERE id=ANY($1::uuid[])',[organizations]);});}finally{await pool.end();}});
const developer:Actor={id:'00000000-0000-4000-8000-000000000006',orgId:'10000000-0000-4000-8000-000000000003',roles:['developer']},identity={actor:async()=>developer} as unknown as Identity,controller=new DevelopmentProjectsController(identity),inventory=new InventoryController(identity);
const req=(url='/api/v1/ops/developments',method='POST')=>({url,method,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
const facts=()=>({communityId:'10000000-0000-4000-8000-000000000040',name:'N01 developer project',slug:'n01-'+crypto.randomUUID(),description:'A synthetic developer-owned project with phases and distinct canonical buildings.'});
it('N01 granted developer creates a valid project, phase and building; exact versions, idempotency and sales workflow preserve parent scope',async()=>{
 const input=facts(),request=req(),source=(await controller.create(request,input)).data;created.push(source.id);expect(source).toMatchObject({organization_id:developer.orgId,status:'draft',version:1,price_min:null,price_max:null});expect((await controller.create(request,input)).data.id).toBe(source.id);const phase=(await controller.createPhase(req(),source.id,{projectVersion:1,name:'East phase',slug:'east'})).data;expect(phase).toMatchObject({development_id:source.id,status:'draft',version:1,projectVersion:2});const building=(await controller.createBuilding(req(),source.id,{projectVersion:2,phaseId:phase.id,name:'East building',slug:'east-building-'+crypto.randomUUID(),floors:12,completedYear:2027})).data;expect(building).toMatchObject({development_id:source.id,phase_id:phase.id,community_id:source.community_id,version:1,projectVersion:3});expect((await controller.structure(req(),source.id)).data.buildings.map(row=>row.id)).toContain(building.id);await expect(controller.createPhase(req(),source.id,{projectVersion:1,name:'Stale phase',slug:'stale'})).rejects.toMatchObject({status:409});const edited=(await controller.updatePhase(req('', 'PATCH'),source.id,phase.id,{projectVersion:3,version:1,name:'East phase updated',status:'coming_soon'})).data;expect(edited).toMatchObject({version:2,projectVersion:4});expect((await controller.updateBuilding(req('', 'PATCH'),source.id,building.id,{projectVersion:4,version:1,phaseId:phase.id,name:'East building updated',floors:13,completedYear:2027,status:'active'})).data).toMatchObject({version:2,projectVersion:5});expect((await publishDevelopmentFixture(developer,source.id,5,'coming_soon')).version).toBe(7);expect((await inventory.editDevelopment(req('', 'PATCH'),source.id,{version:7,status:'on_sale'})).data.version).toBe(8);await expect(inventory.editDevelopment(req('', 'PATCH'),source.id,{version:8,status:'draft'})).rejects.toMatchObject({status:409});expect((await inventory.editDevelopment(req('', 'PATCH'),source.id,{version:8,status:'sold_out'})).data.version).toBe(9);await expect(controller.createPhase(req(),source.id,{projectVersion:9,name:'Closed sales phase',slug:'closed'})).rejects.toMatchObject({status:409});expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int AS count FROM audit_events WHERE resource_id=$1 AND action='development.created'",[source.id]))).rows[0].count).toBe(1);
});
it('N01 foreign developers cannot edit projects/buildings or attach a foreign phase; canonical database rejects cross-project and organization relinking',async()=>{
 const source=(await controller.create(req(),facts())).data,phase=(await controller.createPhase(req(),source.id,{projectVersion:1,name:'Private phase',slug:'private'})).data,building=(await controller.createBuilding(req(),source.id,{projectVersion:2,phaseId:phase.id,name:'Private building',slug:'private-'+crypto.randomUUID(),floors:10,completedYear:null})).data;created.push(source.id);const organization=crypto.randomUUID();organizations.push(organization);await transaction(workerActor,async c=>{await c.query("INSERT INTO organizations(id,name,type) VALUES($1,'N01 foreign developer fixture','developer')",[organization]);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES('00000000-0000-4000-8000-000000000011',$1,'developer','active')",[organization]);});const foreign:Actor={...developer,id:'00000000-0000-4000-8000-000000000011',orgId:organization},other=new DevelopmentProjectsController({actor:async()=>foreign} as unknown as Identity),own=(await other.create(req(),facts())).data;
 created.push(own.id);await expect(other.update(req('', 'PATCH'),source.id,{version:3,name:'Foreign overwrite',description:facts().description,completionDate:null})).rejects.toMatchObject({status:404});await expect(other.createPhase(req(),source.id,{projectVersion:3,name:'Foreign phase',slug:'foreign'})).rejects.toMatchObject({status:404});await expect(other.updateBuilding(req('', 'PATCH'),source.id,building.id,{projectVersion:3,version:1,phaseId:phase.id,name:'Foreign building edit',floors:9,completedYear:null,status:'active'})).rejects.toMatchObject({status:404});await expect(other.createBuilding(req(),own.id,{projectVersion:1,phaseId:phase.id,name:'Invalid foreign phase',slug:'invalid',floors:2,completedYear:null})).rejects.toMatchObject({status:400});expect((await transaction(foreign,c=>c.query("UPDATE buildings SET name='Direct forbidden edit' WHERE id=$1 RETURNING id",[building.id]))).rows).toEqual([]);const foreignPhase=(await other.createPhase(req(),own.id,{projectVersion:1,name:'Own phase',slug:'own'})).data;await expect(transaction(workerActor,c=>c.query('UPDATE buildings SET phase_id=$2 WHERE id=$1',[building.id,foreignPhase.id]))).rejects.toMatchObject({code:'23514'});await expect(transaction(workerActor,c=>c.query('UPDATE developments SET organization_id=$2 WHERE id=$1',[source.id,organization]))).rejects.toMatchObject({code:'23514'});await expect(transaction(workerActor,c=>c.query('UPDATE development_phases SET development_id=$2 WHERE id=$1',[phase.id,own.id]))).rejects.toMatchObject({code:'23514'});
});
