import '../support/env';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {afterAll,expect,it,vi} from 'vitest';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {checkedWorkspace} from '../../apps/api/src/inventory/digitization/intakes';
import {verifySmallDigitizationSource} from '../../apps/api/src/inventory/digitization/source-validation';
import {appendInputRevision} from '../../apps/api/src/inventory/digitization/inputs';
import {createRunGraph,dispatchRunGraph} from '../../apps/api/src/inventory/digitization/workflow';
import {leaseStage} from '../../apps/api/src/inventory/digitization/leases';
import {cpuSourceFingerprint} from '../../apps/api/src/inventory/digitization/execution-scope';
import {startCpuExecution} from '../../apps/api/src/inventory/digitization/execution-start';
import {collectCpuRenders} from '../../apps/api/src/inventory/digitization/execution-results';
import {CpuRunnerClient} from '../../apps/api/src/inventory/digitization/runner-client';
import {readArtifactPreview} from '../../apps/api/src/inventory/digitization/artifact-preview';
import {readPlanPageSelection} from '../../apps/api/src/inventory/digitization/plan-selection';
import {captureStorage} from '../../apps/api/src/inventory/digitization/multipart';
import {scanFile} from '../../apps/api/src/inventory/scanner';
import {reusableStageInputs} from '../../apps/api/src/inventory/digitization/revision-policy';
import {createHash} from 'node:crypto';
const fixture=JSON.parse(readFileSync('infra/generated/integration/plan-editor-reuse.json','utf8')),actor:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:'10000000-0000-4000-8000-000000000001',roles:['agent']},requireApi=createRequire(new URL('../../apps/api/package.json',import.meta.url)),pg=requireApi('pg'),sharp=requireApi('sharp'),{PutObjectCommand,DeleteObjectCommand}=requireApi('@aws-sdk/client-s3'),admin=new pg.Pool({connectionString:process.env.MIGRATION_DATABASE_URL});
afterAll(async()=>Promise.all([pool.end(),admin.end()]));
it('HE-C10 unchanged document pixels reuse real private storage/current lineage; media invalidates synthetic scene approval and preserves OCR dependency identity',async()=>{
 const before=await transaction(actor,async c=>({workspace:await checkedWorkspace(c,fixture.engineId),sources:(await c.query('SELECT source_set FROM property_input_revisions WHERE digitization_id=$1 AND revision=1',[fixture.engineId])).rows[0].source_set})),original=await readArtifactPreview(actor,fixture.engineId,fixture.artifactId),storage=captureStorage(),key=crypto.randomUUID(),photo=await sharp({create:{width:64,height:48,channels:3,background:'#abcabc'}}).png().toBuffer();
 try{
  await scanFile(photo);await storage.send(new PutObjectCommand({Bucket:'haven-private',Key:'quarantine/'+key,Body:photo}));const asset=await transaction(actor,async c=>(await c.query("INSERT INTO media_assets(owner_id,object_key,mime,size,rights,visibility,purpose,status,scan_at) VALUES($1,$2,'image/png',$3,'Self-authored revision cache test pixels','private','photo','approved',now()) RETURNING id,version",[actor.id,key,photo.length])).rows[0]);
  const approvals=await admin.connect();let scene:string,facts:string;try{await approvals.query('BEGIN');await approvals.query("SELECT set_config('app.actor',$1,true),set_config('app.org',$2,true)",[actor.id,actor.orgId]);const rows=(await approvals.query("INSERT INTO approval_records(digitization_id,organization_id,created_by,input_revision,scope,snapshot,decision,reason) VALUES($1,$2,$3,1,'artifact','{\"type\":\"scene\",\"fixtureOnly\":true}','approved','Synthetic approval metadata only; no scene or human approval asserted'),($1,$2,$3,1,'facts','{\"fixtureOnly\":true}','approved','Synthetic facts metadata only; no country measurement asserted') RETURNING id,scope",[fixture.engineId,actor.orgId,actor.id])).rows;scene=rows.find((r:any)=>r.scope==='artifact').id;facts=rows.find((r:any)=>r.scope==='facts').id;await approvals.query('COMMIT');}catch(e){await approvals.query('ROLLBACK');throw e;}finally{approvals.release();}
  const doc=await verifySmallDigitizationSource(actor,fixture.engineId,fixture.sourceAssetId,1,2,'document'),added=await verifySmallDigitizationSource(actor,fixture.engineId,asset.id,asset.version,2,'photo');await transaction(actor,c=>appendInputRevision(c,actor,fixture.engineId,before.workspace.version,[doc,added]));const current=await transaction(actor,async c=>({workspace:await checkedWorkspace(c,fixture.engineId),sources:(await c.query('SELECT source_set FROM property_input_revisions WHERE digitization_id=$1 AND revision=2',[fixture.engineId])).rows[0].source_set}));
  expect(reusableStageInputs('document_ocr',before.sources,current.sources)).toBe(true);expect(reusableStageInputs('scene_export',before.sources,current.sources)).toBe(false);await transaction(actor,async c=>{expect((await c.query('SELECT documents_changed,plans_changed,media_changed FROM digitization_input_changes WHERE digitization_id=$1 AND input_revision=2',[fixture.engineId])).rows[0]).toEqual({documents_changed:false,plans_changed:false,media_changed:true});expect((await c.query('SELECT digitization_approval_current($1,$2,2) allowed',[scene,fixture.engineId])).rows[0].allowed).toBe(false);expect((await c.query('SELECT digitization_approval_current($1,$2,2) allowed',[facts,fixture.engineId])).rows[0].allowed).toBe(true);});
  const stageId=crypto.randomUUID(),runId=crypto.randomUUID(),profile='upright-image-v1',fingerprint=cpuSourceFingerprint(fixture.engineId,actor.orgId!,2,profile,current.sources.find((s:any)=>s.assetId===fixture.sourceAssetId));await transaction(actor,c=>createRunGraph(c,actor,fixture.engineId,current.workspace.version,{schemaVersion:1,id:runId,organizationId:actor.orgId!,creatorId:actor.id,target:current.workspace.target,inputRevision:2,state:'draft',version:1,stages:[{id:stageId,type:'document_rasterize',state:'pending',dependencies:[],profileId:profile,inputFingerprint:fingerprint,inputRevision:2,attempt:0,fencingToken:null,executionId:null,progress:null}],deadline:new Date(Date.now()+120000).toISOString(),budget:{maxSeconds:30,maxScratchBytes:'67108864'}},['plan']));await transaction(actor,c=>dispatchRunGraph(c,actor,fixture.engineId,runId,1));const lease=await transaction(actor,c=>leaseStage(c,actor,fixture.engineId,stageId,2)),client=new CpuRunnerClient(process.env.DIGITIZATION_RUNNER_TEST_ORIGIN!,Buffer.from('test-only-private-key-not-a-production-credential-0000')),submit=vi.spyOn(client,'submit');
  const starts=await Promise.all([1,2].map(()=>startCpuExecution(actor,fixture.engineId,stageId,lease.execution_id,lease.fencing_token,fixture.sourceAssetId,client)));expect(starts.every(s=>s.state==='succeeded')).toBe(true);expect(submit).not.toHaveBeenCalled();submit.mockRestore();const receipt=await collectCpuRenders(actor,fixture.engineId,stageId,lease.execution_id,lease.fencing_token,fixture.sourceAssetId,client);expect(receipt.artifactIds).toHaveLength(1);expect(receipt.artifactIds[0]).not.toBe(fixture.artifactId);
  const output=await readArtifactPreview(actor,fixture.engineId,receipt.artifactIds[0]);expect(output.equals(original)).toBe(true);const selection=await readPlanPageSelection(actor,fixture.engineId,receipt.artifactIds[0],0);expect(selection).toMatchObject({inputRevision:2,width:1024,height:768,unit:'px',scaleStatus:'unscaled'});await expect(readPlanPageSelection(actor,fixture.engineId,fixture.artifactId,0)).rejects.toMatchObject({status:409});
  await transaction(actor,async c=>{const rows=(await c.query('SELECT reused_from_artifact_id,input_revision,checksum,privacy_status,status FROM artifacts WHERE stage_id=$1',[stageId])).rows;expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({reused_from_artifact_id:fixture.artifactId,input_revision:2,checksum:createHash('sha256').update(original).digest('hex'),privacy_status:'pending',status:'private'});expect((await c.query('SELECT state FROM processing_runs WHERE id=$1',[runId])).rows[0].state).toBe('awaiting_review');});
  await expect(readArtifactPreview({...actor,orgId:'10000000-0000-4000-8000-000000000005'},fixture.engineId,receipt.artifactIds[0])).rejects.toMatchObject({status:403});
 }finally{vi.restoreAllMocks();await storage.send(new DeleteObjectCommand({Bucket:'haven-private',Key:'quarantine/'+key}));storage.destroy();}
},30000);
