import {PaymentAllocationsController} from '../../apps/api/src/management/payment-allocations';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {FinancialReversalsController} from '../../apps/api/src/management/financial-reversals';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P09 verified synthetic tenant',true)",[tenant.id,'p09-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P09 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P09 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p09-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P09 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
const allocations=(a=manager)=>new PaymentAllocationsController(identity(a));
async function financial(amount='250.25',charged='200.20'){const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(l.id),amount})).data,posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(p))).data,ch=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2028-01-01','2028-01-05',$3,'CNY') RETURNING id,version",[l.id,manager.orgId,charged])).rows[0]);return {...f,l,p:posted,ch};}
async function allocationBody(f:Awaited<ReturnType<typeof financial>>,amount='50.05'){const ledger=(await allocations().ledger(req('GET'),f.l.id,{})).data;return {version:0,leaseId:f.l.id,leaseVersion:ledger.leaseVersion,unitVersion:ledger.unitVersion,grantVersion:ledger.grantVersion,paymentId:f.p.id,paymentVersion:f.p.version,chargeId:f.ch.id,chargeVersion:f.ch.version,amount,currency:ledger.currency,confirm:true};}

const reversals=(a=manager)=>new FinancialReversalsController(identity(a));
async function reversalBody(f:Awaited<ReturnType<typeof financial>>,type:'payment'|'charge'='payment'){const d=(await reversals().read(req('GET'),type,type==='payment'?f.p.id:f.ch.id)).data;return {version:d.version,leaseVersion:d.leaseVersion,unitVersion:d.unitVersion,grantVersion:d.grantVersion,reason:'Correct duplicate synthetic posted bookkeeping evidence.',confirm:true};}
it('P09 payment reversal preserves original, restores balance and retains one attributed undo across receipt and fresh retries',async()=>{const f=await financial(),x=await allocationBody(f,'100.10'),a=(await allocations().create(req('POST','/api/v1/ops/allocations'),x)).data,original=(await transaction(workerActor,c=>c.query('SELECT * FROM payments WHERE id=$1',[f.p.id]))).rows[0],body=await reversalBody(f),r=req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),result=(await reversals().reversePayment(r,f.p.id,body)).data;expect(result.eligible).toBe(false);expect(result.reversal).toMatchObject({reason:body.reason,actorId:manager.id,native:true,undoneAllocationIds:[a.id]});expect((await reversals().reversePayment(r,f.p.id,body)).data.reversal.id).toBe(result.reversal.id);expect((await reversals().reversePayment(req('POST',r.url),f.p.id,body)).data.reversal.id).toBe(result.reversal.id);expect((await transaction(workerActor,c=>c.query('SELECT * FROM payments WHERE id=$1',[f.p.id]))).rows[0]).toEqual(original);expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals).toMatchObject({recordedPayments:'0.00',allocated:'0.00',outstanding:'200.20',credit:'0.00'});const undo=(await transaction(workerActor,c=>c.query('SELECT version,reversed_by,reversed_at FROM allocations WHERE id=$1',[a.id]))).rows[0];expect(undo.version).toBe(2);expect(undo.reversed_by).toBe(manager.id);expect(undo.reversed_at).toBeTruthy();expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='payment.reversed'",[f.p.id]))).rows[0].n).toBe(1);await expect(reversals().reversePayment(req('POST',r.url),f.p.id,{...body,reason:'Attempt to replace an already retained reason.'})).rejects.toMatchObject({status:409});await expect(transaction(workerActor,c=>c.query("UPDATE payments SET amount='1.00' WHERE id=$1",[f.p.id]))).rejects.toMatchObject({code:'P0001'});expect((await transaction(workerActor,c=>c.query("UPDATE financial_reversal_evidence SET reason='Overwrite immutable reversal history' WHERE original_id=$1",[f.p.id]))).rowCount).toBe(0);expect((await transaction(workerActor,c=>c.query("SELECT reason FROM financial_reversal_evidence WHERE original_id=$1",[f.p.id]))).rows[0].reason).toBe(body.reason);},90000);
it('P09 charge reversal preserves original and restores payment credit without reversing a reversal',async()=>{const f=await financial(),a=(await allocations().create(req('POST','/api/v1/ops/allocations'),await allocationBody(f))).data,original=(await transaction(workerActor,c=>c.query('SELECT * FROM charges WHERE id=$1',[f.ch.id]))).rows[0],body=await reversalBody(f,'charge'),r=(await reversals().reverseCharge(req('POST','/api/v1/ops/charges/'+f.ch.id+'/reverse'),f.ch.id,body)).data;expect(r.reversal.undoneAllocationIds).toEqual([a.id]);expect((await transaction(workerActor,c=>c.query('SELECT * FROM charges WHERE id=$1',[f.ch.id]))).rows[0]).toEqual(original);expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals).toMatchObject({charges:'0.00',allocated:'0.00',outstanding:'0.00',credit:'250.25'});const leaf=(await reversals().read(req('GET'),'charge',r.reversal.id)).data;expect(leaf.eligible).toBe(false);await expect(reversals().reverseCharge(req('POST','/api/v1/ops/charges/'+leaf.id+'/reverse'),leaf.id,{...body,version:leaf.version})).rejects.toMatchObject({status:409});},90000);
it('P09 simultaneous payment reversals and an allocation settle once under the shared finance lock',async()=>{const f=await financial(),body=await reversalBody(f),x=await allocationBody(f),results=await Promise.allSettled([reversals().reversePayment(req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),f.p.id,body),reversals().reversePayment(req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),f.p.id,body),allocations().create(req('POST','/api/v1/ops/allocations'),x)]);expect(results[0].status).toBe('fulfilled');expect(results[1].status).toBe('fulfilled');expect((results[0] as PromiseFulfilledResult<any>).value.data.reversal.id).toBe((results[1] as PromiseFulfilledResult<any>).value.data.reversal.id);if(results[2].status==='rejected')expect(results[2].reason.status).toBe(409);expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals).toMatchObject({recordedPayments:'0.00',allocated:'0.00',outstanding:'200.20'});expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM payments WHERE reverses_id=$1',[f.p.id]))).rows[0].n).toBe(1);},90000);
it('P09 stale versions, confirmation, foreign actual finance and revoked grants deny reversal or receipt without evidence',async()=>{const f=await financial(),body=await reversalBody(f);for(const patch of [{version:999},{leaseVersion:999},{unitVersion:999},{grantVersion:999},{confirm:false},{reason:'x'}])await expect(reversals().reversePayment(req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),f.p.id,{...body,...patch})).rejects.toBeDefined();const foreign:Actor={id:crypto.randomUUID(),orgId:crypto.randomUUID(),roles:['finance']};await transaction(workerActor,async c=>{await c.query("INSERT INTO organizations(id,name,type) VALUES($1,'P09 foreign synthetic manager','manager')",[foreign.orgId]);await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P09 foreign synthetic finance',true)",[foreign.id,'p09-foreign-'+foreign.id,foreign.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,'finance','active')",[foreign.id,foreign.orgId]);});try{await expect(reversals(foreign).read(req('GET'),'payment',f.p.id)).rejects.toMatchObject({status:404});await expect(reversals(foreign).reversePayment(req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),f.p.id,body)).rejects.toMatchObject({status:404});expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM financial_reversal_evidence WHERE original_id=$1',[f.p.id]))).rows[0].n).toBe(0);const r=req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse');await reversals().reversePayment(r,f.p.id,body);await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner revoked current finance authority after reversal.'});await expect(reversals().reversePayment(r,f.p.id,body)).rejects.toMatchObject({status:404});}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='revoked',version=version+1 WHERE user_id=$1",[foreign.id]));}},90000);
it('P09 SQL requires exact linked evidence and commit-time allocation undo atomically',async()=>{const f=await financial();await allocations().create(req('POST','/api/v1/ops/allocations'),await allocationBody(f));await expect(transaction(manager,c=>c.query("INSERT INTO payments(lease_id,organization_id,amount,currency,source,reference,actor_id,reverses_id) VALUES($1,$2,'250.25','CNY','reversal','Unaudited direct runtime reversal',$3,$4)",[f.l.id,manager.orgId,manager.id,f.p.id]))).rejects.toMatchObject({code:'23514'});const body=await reversalBody(f);await expect(transaction(manager,c=>c.query("INSERT INTO financial_reversal_evidence(record_type,original_id,reversal_id,organization_id,lease_id,original_version,lease_version,unit_version,grant_version,reason,actor_id) VALUES('payment',$1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[f.p.id,crypto.randomUUID(),manager.orgId,f.l.id,body.version,body.leaseVersion,body.unitVersion,body.grantVersion,body.reason,manager.id]))).rejects.toMatchObject({code:'23514'});expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals.allocated).toBe('50.05');expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM financial_reversal_evidence WHERE original_id=$1',[f.p.id]))).rows[0].n).toBe(0);},90000);
