import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {createRequire} from 'node:module';
import type {FastifyRequest} from 'fastify';
import type {Identity} from '../../apps/api/src/platform/core';
import {AdministrationController} from '../../apps/api/src/administration/controller';
import {HomeDiscoveryController} from '../../apps/api/src/geography/home';
import {transaction,type Actor} from '../../packages/database/src/index';
const admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin','editor']},buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};
const api=(a=admin)=>new AdministrationController({actor:async()=>a} as unknown as Identity),request=(method='POST',url='/api/v1/ops/home-content')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),publicHome=()=>new HomeDiscoveryController().home({city:'bj'});
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});afterAll(()=>fixtures.end());
async function listing(){const c=await fixtures.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor',$1,true),set_config('app.admin','true',true)",[admin.id]);const u=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'80.00',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0];const l=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'S03 synthetic curated home',description,'sale','residential','CNY','123456.78','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,version",[u.id,'s03-'+crypto.randomUUID()])).rows[0];await c.query('COMMIT');return l;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
const draft=(source:{id:string;version:number})=>({version:0,city:'bj',category:'buy',title:'S03 local English selection '+crypto.randomUUID(),copy:'Current synthetic homes selected for this city.',position:4,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString(),items:[source]});
it('S03 versioned scheduled publication uses the exact eligible snapshot, preserves independent draft edits and current public visibility',async()=>{
 const source=await listing(),x=draft(source);let r=(await api().homeCreate(request(),x)).data;expect(r).toMatchObject({state:'draft',version:1,published:null});expect((await publicHome()).data.sections.some(s=>s.id===r.id)).toBe(false);const preview=(await api().homePreview(request('GET'),r.id)).data;expect(preview.title).toBe(x.title);expect(preview.activity).toHaveLength(1);const req=request('POST','/api/v1/ops/home-content/'+r.id+'/actions');r=(await api().homePublish(req,r.id,{version:1,action:'publish'})).data;expect(r).toMatchObject({state:'published',version:2,publishedVersion:2});expect((await api().homePublish(req,r.id,{version:1,action:'publish'})).data.version).toBe(2);let publicSection=(await publicHome()).data.sections.find(s=>s.id===r.id)!;expect(publicSection.title).toBe(x.title);expect(publicSection.listings.map(l=>l.id)).toEqual([source.id]);expect(JSON.stringify(publicSection)).not.toMatch(/created_by|updated_by|organization_id|actor_id/);
 r=(await api().homeEdit(request('PATCH'),r.id,{...x,version:2,title:'S03 unpublished revised heading',position:1})).data;expect(r.version).toBe(3);expect((await publicHome()).data.sections.find(s=>s.id===r.id)?.title).toBe(x.title);await expect(api().homePublish(request(),r.id,{version:2,action:'publish'})).rejects.toMatchObject({status:409});r=(await api().homePublish(request(),r.id,{version:3,action:'publish'})).data;publicSection=(await publicHome()).data.sections.find(s=>s.id===r.id)!;expect(publicSection.title).toBe('S03 unpublished revised heading');expect(publicSection.position).toBe(1);expect(r.activity.map(h=>h.action)).toEqual(['created','published','edited','published']);
 await fixtures.query("UPDATE listings SET status='withdrawn',version=version+1 WHERE id=$1",[source.id]);expect((await publicHome()).data.sections.some(s=>s.id===r.id)).toBe(false);await expect(api().homePublish(request(),r.id,{version:r.version,action:'publish'})).rejects.toMatchObject({status:400});r=(await api().homePublish(request(),r.id,{version:r.version,action:'archive'})).data;expect(r.state).toBe('archived');expect(r.published).not.toBeNull();await expect(api().homeEdit(request('PATCH'),r.id,{...x,version:r.version})).rejects.toMatchObject({status:409});
});
it('S03 future and expired schedules stay absent; invalid city/category/version/link, guessed preview and forged editor permissions deny',async()=>{
 const source=await listing(),x=draft(source),future={...x,startsAt:new Date(Date.now()+3600000).toISOString(),endsAt:new Date(Date.now()+7200000).toISOString()};let r=(await api().homeCreate(request(),future)).data;r=(await api().homePublish(request(),r.id,{version:1,action:'publish'})).data;expect((await publicHome()).data.sections.some(s=>s.id===r.id)).toBe(false);const expired={...x,startsAt:new Date(Date.now()-7200000).toISOString(),endsAt:new Date(Date.now()-3600000).toISOString()};let old=(await api().homeCreate(request(),expired)).data;old=(await api().homePublish(request(),old.id,{version:1,action:'publish'})).data;expect((await publicHome()).data.sections.some(s=>s.id===old.id)).toBe(false);
 for(const invalid of [{...x,category:'rent'},{...x,items:[{...source,version:source.version+1}]},{...x,city:'missing-city'},{...x,items:[{id:crypto.randomUUID(),version:1}]},{...x,url:'https://foreign.example/'}])await expect(api().homeCreate(request(),invalid)).rejects.toThrow();for(const a of [buyer,{...buyer,roles:['editor','admin']}]){await expect(api(a).homeCreate(request(),x)).rejects.toMatchObject({status:403});await expect(api(a).homePreview(request('GET'),r.id)).rejects.toMatchObject({status:403});expect((await transaction(a,c=>c.query('SELECT * FROM home_sections'))).rowCount).toBe(0);}
 await fixtures.query("INSERT INTO cities(id,slug,name,country,currency,timezone) VALUES($1,$2,'S03 foreign synthetic city','CN','CNY','Asia/Shanghai')",[crypto.randomUUID(),'s03-'+source.id]);const foreign='s03-'+source.id;await fixtures.query("INSERT INTO home_taxonomy(city,category,label) VALUES($1,'buy','Foreign homes')",[foreign]);await expect(api().homeCreate(request(),{...x,city:foreign})).rejects.toMatchObject({status:400});
});
it('S03 actual editor taxonomy is versioned with immutable history; disabled eligibility hides publication and blocks draft admission',async()=>{
 const source=await listing(),x=draft(source);let r=(await api().homeCreate(request(),x)).data;r=(await api().homePublish(request(),r.id,{version:1,action:'publish'})).data;let taxonomy=(await api().homeContent(request('GET'),{city:'bj'})).data.taxonomy.find(t=>t.category==='buy')!;const req=request('POST','/api/v1/ops/home-taxonomy');const input={city:'bj',category:'buy',version:taxonomy.version,label:'S03 English sale taxonomy',active:false};taxonomy=(await api().homeTaxonomy(req,input)).data;expect(taxonomy.active).toBe(false);expect((await api().homeTaxonomy(req,input)).data.version).toBe(taxonomy.version);expect((await publicHome()).data.sections.some(s=>s.id===r.id)).toBe(false);await expect(api().homeCreate(request(),x)).rejects.toMatchObject({status:400});await expect(api().homeTaxonomy(request(),input)).rejects.toMatchObject({status:409});await expect(api({...buyer,roles:['editor']}).homeTaxonomy(request(),{...input,version:taxonomy.version})).rejects.toMatchObject({status:403});expect((await transaction(admin,c=>c.query("UPDATE home_taxonomy_history SET snapshot='{}' WHERE city='bj'"))).rowCount).toBe(0);expect((await transaction(admin,c=>c.query('DELETE FROM home_content_history WHERE section_id=$1',[r.id]))).rowCount).toBe(0);await api().homeTaxonomy(request(),{...input,version:taxonomy.version,active:true});expect((await publicHome()).data.sections.find(s=>s.id===r.id)?.categoryLabel).toBe('S03 English sale taxonomy');await api().homePublish(request(),r.id,{version:r.version,action:'archive'});
});
