import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {LeaseLifecycleController} from '../../apps/api/src/management/lease-lifecycle';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P05 verified synthetic tenant',true)",[tenant.id,'p05-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P05 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P05 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p05-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P05 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const lifecycle=(a=manager)=>new LeaseLifecycleController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>,start='2034-01-01',end='2034-12-31'){const l=await draft(f,start,end);return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function renewalBody(f:Awaited<ReturnType<typeof fixture>>,l:any,startDate='2035-01-01',endDate='2035-12-31'){const o=(await api().options(req('GET'),f.unit.id)).data;return {version:l.version,unitVersion:o.unitVersion,grantVersion:o.grantVersion,tenantVersion:o.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1456.78',currency:o.currency,rentPeriod:'month',dueDay:8,documents:[],reason:'Verified next term agreed by the managed parties.'};}
it('P05 valid next term retains original terms, links history and replays one renewal draft',async()=>{const f=await fixture(),old=await active(f),body=await renewalBody(f,old),r=req('POST','/api/v1/ops/leases/'+old.id+'/renew'),next=(await lifecycle().renew(r,old.id,body)).data;leases.push(next.id);expect(next).toMatchObject({status:'draft',rent:'1456.78',startDate:'2035-01-01',dueDay:8});expect((await lifecycle().renew(r,old.id,body)).data.id).toBe(next.id);const previous=(await lifecycle().read(req('GET'),old.id)).data;expect(previous).toMatchObject({status:'active',rent:'1234.56',endDate:'2034-12-31',nextLeaseId:next.id});expect((await lifecycle().read(req('GET'),next.id)).data).toMatchObject({previousLeaseId:old.id,activity:[{action:'renewal_drafted',reason:body.reason}]});await expect(lifecycle().renew(req('POST','/api/v1/ops/leases/'+old.id+'/renew'),old.id,body)).rejects.toMatchObject({status:409});await expect(api().update(req('PATCH','/api/v1/ops/lease-drafts/'+next.id),next.id,{version:next.version,unitVersion:body.unitVersion,grantVersion:body.grantVersion,tenantVersion:body.tenantVersion,startDate:'2034-12-01',endDate:body.endDate,rent:body.rent,currency:body.currency,rentPeriod:body.rentPeriod,dueDay:body.dueDay,documents:[]})).rejects.toBeDefined();expect((await api().read(req('GET'),next.id)).data.startDate).toBe('2035-01-01');await api().activate(req('POST','/api/v1/ops/leases/'+next.id+'/activate'),next.id,activation(next));});
it('P05 overlapping next terms and stale/currency versions deny renewal without partial linked drafts',async()=>{const f=await fixture(),old=await active(f),other=await active(f,'2035-01-01','2035-12-31'),body=await renewalBody(f,old);for(const patch of [{},{startDate:'2034-12-31'},{version:999},{currency:'USD'},{unitVersion:999}])await expect(lifecycle().renew(req('POST','/api/v1/ops/leases/'+old.id+'/renew'),old.id,{...body,...patch})).rejects.toBeDefined();expect((await lifecycle().read(req('GET'),old.id)).data.nextLeaseId).toBeNull();expect(other.status).toBe('active');});
it('P05 ending records termination reason and original history, never republishes, and revoked authority denies receipt replay',async()=>{const f=await fixture(),l=await active(f),r=req('POST','/api/v1/ops/leases/'+l.id+'/end'),body={version:l.version,kind:'terminated',reason:'Recorded termination after the managed parties agreed.',confirm:true},ended=(await lifecycle().end(r,l.id,body)).data;expect(ended).toMatchObject({status:'ended',version:3,rent:'1234.56',endDate:'2034-12-31',ending:{kind:'terminated',reason:body.reason,availabilityReviewRequired:true}});expect(ended.activity.map((h:any)=>h.action)).toEqual(['drafted','activated','terminated']);expect((await lifecycle().end(r,l.id,body)).data.version).toBe(3);expect((await transaction(null,c=>c.query('SELECT id FROM public_listings WHERE id=$1',[f.listing.id]))).rowCount).toBe(0);expect((await transaction(workerActor,c=>c.query('SELECT status FROM listings WHERE id=$1',[f.listing.id]))).rows[0].status).toBe('leased');expect((await transaction(manager,c=>c.query("UPDATE lease_endings SET reason='changed' WHERE lease_id=$1",[l.id]))).rowCount).toBe(0);expect((await lifecycle().read(req('GET'),l.id)).data.ending?.reason).toBe(body.reason);await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner ended synthetic management authority.'});await expect(lifecycle().end(r,l.id,body)).rejects.toMatchObject({status:404});});
it('P05 concurrent renewal requests yield one retained successor and concurrent endings yield one record',async()=>{const f=await fixture(),l=await active(f),body=await renewalBody(f,l),results=await Promise.allSettled([lifecycle().renew(req('POST','/api/v1/ops/leases/'+l.id+'/renew'),l.id,body),lifecycle().renew(req('POST','/api/v1/ops/leases/'+l.id+'/renew'),l.id,body)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);const next=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value.data;leases.push(next.id);expect((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);const end={version:l.version,kind:'completed',reason:'Recorded completion with availability review required.',confirm:true},ends=await Promise.allSettled([lifecycle().end(req('POST','/api/v1/ops/leases/'+l.id+'/end'),l.id,end),lifecycle().end(req('POST','/api/v1/ops/leases/'+l.id+'/end'),l.id,end)]);expect(ends.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((ends.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);expect((await lifecycle().read(req('GET'),l.id)).data.ending?.kind).toBe('completed');await expect(lifecycle(tenant).read(req('GET'),l.id)).rejects.toMatchObject({status:403});});
it('P05 historical lease ending retains unknown provenance and new renewal uses current native authority',async()=>{const f=await fixture(),id=await transaction(workerActor,async c=>(await c.query("INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency,status) VALUES($1,$2,$3,'2034-01-01','2034-12-31','1234.56','CNY','active') RETURNING id",[manager.orgId,f.unit.id,f.tenantId])).rows[0].id);leases.push(id);const old=(await lifecycle().read(req('GET'),id)).data;expect(old).toMatchObject({native:false,dueDay:null,activity:[]});await expect(transaction(manager,c=>c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=$1",[id]))).rejects.toMatchObject({code:'23514'});await expect(lifecycle().end(req('POST','/api/v1/ops/leases/'+id+'/end'),id,{version:1,kind:'completed',reason:'Recorded completion of retained historical terms.',confirm:false})).rejects.toBeDefined();const ended=(await lifecycle().end(req('POST','/api/v1/ops/leases/'+id+'/end'),id,{version:1,kind:'completed',reason:'Recorded completion of retained historical terms.',confirm:true})).data;expect(ended).toMatchObject({native:false,dueDay:null,version:2,status:'ended',activity:[{action:'ended'}]});const body=await renewalBody(f,ended),next=(await lifecycle().renew(req('POST','/api/v1/ops/leases/'+id+'/renew'),id,body)).data;leases.push(next.id);expect(next).toMatchObject({dueDay:8,status:'draft',rent:'1456.78'});expect((await lifecycle().read(req('GET'),next.id)).data.previousLeaseId).toBe(id);});
