import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P04 verified synthetic tenant',true)",[tenant.id,'p04-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P04 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P04 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p04-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P04 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
it('P04 atomic activation withdraws the public rental offer with exact history, audit and matching receipts',async()=>{const f=await fixture(),l=await draft(f);expect((await transaction(null,c=>c.query('SELECT id FROM public_listings WHERE id=$1',[f.listing.id]))).rowCount).toBe(1);const r=req('POST','/api/v1/ops/leases/'+l.id+'/activate'),active=(await api().activate(r,l.id,activation(l))).data;expect(active).toMatchObject({status:'active',version:2,rent:'1234.56'});expect((await api().activate(r,l.id,activation(l))).data.version).toBe(2);expect((await transaction(null,c=>c.query('SELECT id FROM public_listings WHERE id=$1',[f.listing.id]))).rowCount).toBe(0);const facts=await transaction(workerActor,async c=>({listing:(await c.query('SELECT status,version FROM listings WHERE id=$1',[f.listing.id])).rows[0],history:(await c.query('SELECT previous_status,next_status,actor_id FROM listing_status_history WHERE listing_id=$1',[f.listing.id])).rows,events:(await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='lease.activated'",[l.id])).rows[0].n}));expect(facts.listing).toMatchObject({status:'leased',version:2});expect(facts.history).toEqual([{previous_status:'published',next_status:'leased',actor_id:manager.id}]);expect(facts.events).toBe(1);expect(active.activity.map((h:any)=>h.action)).toEqual(['drafted','activated']);await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner ended synthetic management authority.'});await expect(api().activate(r,l.id,activation(l))).rejects.toMatchObject({status:404});});
it('P04 simultaneous overlapping draft activations yield exactly one success and one current-state conflict',async()=>{const f=await fixture(),a=await draft(f),b=await draft(f),results=await Promise.allSettled([api().activate(req('POST','/api/v1/ops/leases/'+a.id+'/activate'),a.id,activation(a)),api().activate(req('POST','/api/v1/ops/leases/'+b.id+'/activate'),b.id,activation(b))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((results.find(x=>x.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);expect((await transaction(workerActor,c=>c.query("SELECT id FROM leases WHERE unit_id=$1 AND status='active'",[f.unit.id]))).rowCount).toBe(1);});
it('P04 property occupation conflicts with child rooms while sibling rooms can hold separate exclusive terms',async()=>{const property=await fixture(),roomA=await fixture(property.unit.id),roomB=await fixture(property.unit.id),a=await draft(roomA),b=await draft(roomB);await api().activate(req('POST','/api/v1/ops/leases/'+a.id+'/activate'),a.id,activation(a));await api().activate(req('POST','/api/v1/ops/leases/'+b.id+'/activate'),b.id,activation(b));const whole=await draft(property);await expect(api().activate(req('POST','/api/v1/ops/leases/'+whole.id+'/activate'),whole.id,activation(whole))).rejects.toMatchObject({status:409});expect((await transaction(workerActor,c=>c.query('SELECT status FROM listings WHERE id=$1',[roomB.listing.id]))).rows[0].status).toBe('leased');});
it('P04 stale versions, missing confirmation and expired terms deny activation without withdrawing publication',async()=>{const f=await fixture(),l=await draft(f,'2020-01-01','2020-12-31');for(const patch of [{version:999},{confirm:false},{}])await expect(api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,{...activation(l),...patch})).rejects.toBeDefined();expect((await api().read(req('GET'),l.id)).data.status).toBe('draft');expect((await transaction(null,c=>c.query('SELECT id FROM public_listings WHERE id=$1',[f.listing.id]))).rowCount).toBe(1);});
