import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type pg from 'pg';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {submitListingRevision,decideListingRevision} from '../../apps/api/src/inventory/revisions';
const organization='10000000-0000-4000-8000-000000000001';
const admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin']};
const agent:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:organization,roles:['agent']};
const moderator:Actor={id:'00000000-0000-4000-8000-000000000008',orgId:null,roles:['moderator']};
afterAll(()=>pool.end());
async function scope(c:pg.PoolClient,a:Actor){await c.query("SELECT set_config('app.actor',$1,true),set_config('app.org',$2,true),set_config('app.admin',$3,true),set_config('app.review',$4,true),set_config('app.agent_only',$5,true)",[a.id,a.orgId||'',String(a.roles.includes('admin')),String(a.roles.includes('moderator')),String(a.roles.includes('agent'))]);}
async function rollback(work:(c:pg.PoolClient,id:string)=>Promise<void>){const marker=new Error('rollback fixture');try{await transaction(admin,async c=>{const id=(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,created_by,published_at)
 SELECT unit_id,organization_id,owner_id,agent_id,$1,title,description,transaction,segment,currency,'2450000.25',photos,'published',$2,now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id`,['revision-'+crypto.randomUUID(),agent.id])).rows[0].id;await work(c,id);throw marker;});}catch(error){if(error!==marker)throw error;}}
const input={title:'A proposed title visible only after review',price:'2650000.75',version:1,reason:'PRIVATE_REVISION_NOTE_SENTINEL'};
it('I05 pending core edits preserve the public revision, approval publishes one exact price event',async()=>{
 await rollback(async(c,id)=>{await scope(c,agent);const revision=await submitListingRevision(c,agent,id,input);expect((await c.query('SELECT price FROM public_listings WHERE id=$1',[id])).rows[0].price).toBe('2450000.25');await scope(c,moderator);await decideListingRevision(c,moderator,revision.id,{status:'approved',version:1,reason:'Independent revised facts verified',verified:true});expect((await c.query('SELECT title,price,version FROM public_listings WHERE id=$1',[id])).rows[0]).toEqual({title:input.title,price:input.price,version:2});expect((await c.query('SELECT count(*)::int n FROM listing_price_history WHERE listing_id=$1',[id])).rows[0].n).toBe(1);expect((await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='listing.revision_approved'",[id])).rows[0].n).toBe(1);await expect(decideListingRevision(c,moderator,revision.id,{status:'approved',version:1,reason:'Repeated decision must not duplicate',verified:true})).rejects.toMatchObject({status:409});expect((await c.query('SELECT count(*)::int n FROM listing_price_history WHERE listing_id=$1',[id])).rows[0].n).toBe(1);});
});
it('I05 rejected revision preserves public title, price and version without a price event',async()=>{
 await rollback(async(c,id)=>{await scope(c,agent);const revision=await submitListingRevision(c,agent,id,input);await scope(c,moderator);await decideListingRevision(c,moderator,revision.id,{status:'rejected',version:1,reason:'Insufficient evidence for the proposed changes'});expect((await c.query('SELECT price,version FROM public_listings WHERE id=$1',[id])).rows[0]).toEqual({price:'2450000.25',version:1});expect((await c.query('SELECT count(*)::int n FROM listing_price_history WHERE listing_id=$1',[id])).rows[0].n).toBe(0);});
});
it('I05 stale listing revisions and self approval are denied without changing public facts',async()=>{
 await rollback(async(c,id)=>{await scope(c,agent);const revision=await submitListingRevision(c,agent,id,input);await expect(submitListingRevision(c,agent,id,input)).rejects.toMatchObject({status:409});await scope(c,moderator);await c.query('UPDATE listing_revisions SET actor_id=$2 WHERE id=$1',[revision.id,moderator.id]);await expect(decideListingRevision(c,moderator,revision.id,{status:'approved',version:1,reason:'Own proposal must not be approved',verified:true})).rejects.toMatchObject({status:403});await c.query('UPDATE listing_revisions SET actor_id=$2 WHERE id=$1',[revision.id,agent.id]);await c.query('UPDATE listings SET version=version+1 WHERE id=$1',[id]);await expect(decideListingRevision(c,moderator,revision.id,{status:'approved',version:1,reason:'Changed public revision must be rejected',verified:true})).rejects.toMatchObject({status:409});expect((await c.query('SELECT price FROM public_listings WHERE id=$1',[id])).rows[0].price).toBe('2450000.25');});
});
it('I06 public history omits private notes and actor identity and past events cannot be edited',async()=>{
 await rollback(async(c,id)=>{await scope(c,agent);const revision=await submitListingRevision(c,agent,id,input);await scope(c,moderator);await decideListingRevision(c,moderator,revision.id,{status:'approved',version:1,reason:'PRIVATE_DECISION_NOTE_SENTINEL',verified:true});await c.query("INSERT INTO listing_status_history(listing_id,previous_status,next_status,actor_id,reason,listing_version) VALUES($1,'under_review','published',$2,'PRIVATE_STATUS_NOTE_SENTINEL',2)",[id,moderator.id]);await c.query("SELECT set_config('app.actor','',true),set_config('app.review','false',true),set_config('app.org','',true)");expect((await c.query('SELECT * FROM listing_price_history WHERE listing_id=$1',[id])).rowCount).toBe(0);expect((await c.query('SELECT * FROM listing_status_history WHERE listing_id=$1',[id])).rowCount).toBe(0);expect(JSON.stringify((await c.query('SELECT * FROM public_listing_status_history WHERE listing_id=$1',[id])).rows)).not.toMatch(/PRIVATE_|actor_id|reason/);const rows=(await c.query('SELECT * FROM public_listing_price_history WHERE listing_id=$1',[id])).rows;await scope(c,moderator);expect(rows).toHaveLength(1);expect(JSON.stringify(rows)).not.toMatch(/PRIVATE_|actor_id|private_reason|review_reason/);await c.query('SAVEPOINT immutable');await expect(c.query("UPDATE listing_price_history SET next_price='1.00' WHERE listing_id=$1",[id])).rejects.toMatchObject({code:'23514'});await c.query('ROLLBACK TO SAVEPOINT immutable');await c.query('SAVEPOINT immutable_delete');await expect(c.query('DELETE FROM listing_price_history WHERE listing_id=$1',[id])).rejects.toMatchObject({code:'23514'});await c.query('ROLLBACK TO SAVEPOINT immutable_delete');await c.query('SAVEPOINT immutable_status');await expect(c.query("UPDATE listing_status_history SET reason='changed' WHERE listing_id=$1",[id])).rejects.toMatchObject({code:'23514'});await c.query('ROLLBACK TO SAVEPOINT immutable_status');});
});
