import {MaintenanceController} from '../../apps/api/src/management/maintenance';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P12 verified synthetic tenant',true)",[tenant.id,'p12-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P12 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P12 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p12-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P12 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31',documents:{assetId:string;version:number;label:string}[]=[]){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}

const maintenance=(a=tenant)=>new MaintenanceController(identity(a));
async function requestBody(l:any,a=tenant,patch:any={}){const options=(await (a.id===tenant.id?maintenance(a).tenantOptions(req('GET'),{leaseId:l.id}):maintenance(a).professionalOptions(req('GET'),{leaseId:l.id}))).data,s=options.find((r:any)=>r.leaseId===l.id);expect(s).toBeTruthy();return {version:0,leaseId:l.id,leaseVersion:s.leaseVersion,unitVersion:s.unitVersion,grantVersion:s.grantVersion,title:'P12 synthetic kitchen tap request',description:'The supplied synthetic tap photo accompanies a request to inspect a continuous drip.',category:'Plumbing',urgency:'Routine',photos:[],confirm:true,...patch};}
const workflow=(r:any,status='triaged',assigneeId:string|null=null)=>({version:r.version,leaseVersion:r.leaseVersion,unitVersion:r.unitVersion,grantVersion:r.grantVersion,status,assigneeId,publicNote:'The current management team will inspect this request.'});
async function photo(ownerId=tenant.id,patch:any={}){const p={status:'approved',visibility:'private',purpose:'photo',mime:'image/png',scan:new Date(),...patch};return (await transaction(workerActor,c=>c.query("INSERT INTO media_assets(owner_id,object_key,mime,size,rights,visibility,purpose,status,scan_at,variants) VALUES($1,$2,$3,100,'P12 synthetic DB-only sanitized photo metadata',$4,$5,$6,$7,$8) RETURNING id,version",[ownerId,crypto.randomUUID(),p.mime,p.visibility,p.purpose,p.status,p.scan,JSON.stringify({display:'variants/p12-synthetic-'+crypto.randomUUID()+'.webp'})]))).rows[0];}
it('P12 linked tenant creates one versioned request with private owned photo, current manager triages and assigns with exact retained activity',async()=>{const f=await fixture(),l=await active(f),p=await photo(),x=await requestBody(l,tenant,{photos:[{assetId:p.id,version:p.version,caption:'Synthetic dripping kitchen tap'}]}),r=req('POST','/api/v1/me/maintenance'),created=(await maintenance().tenantCreate(r,x)).data;expect((await maintenance().tenantCreate(r,x)).data.id).toBe(created.id);expect(created).toMatchObject({version:1,status:'open',requestedBy:'tenant'});expect(created.photos[0]).toMatchObject({id:p.id,version:p.version,caption:'Synthetic dripping kitchen tap'});expect((await transaction(tenant,c=>c.query('SELECT * FROM maintenance_private_photo($1,$2)',[created.id,p.id]))).rowCount).toBe(1);let team=(await maintenance(manager).professionalRead(req('GET'),created.id)).data;team=(await maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,workflow(team))).data;expect(team).toMatchObject({version:2,status:'triaged'});const assignment=req('PATCH','/api/v1/ops/maintenance/'+team.id),assigned=(await maintenance(manager).change(assignment,team.id,workflow(team,'assigned',manager.id))).data;expect(assigned).toMatchObject({version:3,status:'assigned',assigneeId:manager.id});expect((await maintenance(manager).change(assignment,team.id,workflow(team,'assigned',manager.id))).data.id).toBe(created.id);const own=(await maintenance().tenantRead(req('GET'),created.id)).data;expect(own.activity.map((a:any)=>a.status)).toEqual(['open','triaged','assigned']);expect(own.assignees).toEqual([]);expect(own.assigneeId).toBeNull();expect(JSON.stringify(own)).not.toMatch(/internal_note|internalNote|organization_id|opened_by|object_key/);expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='maintenance.open'",[created.id]))).rows[0].n).toBe(1);},90000);
it('P12 a current manager can create an authorized request that its linked tenant sees, without impersonating tenant creation',async()=>{const f=await fixture(),l=await active(f),p=await photo(manager.id),x=await requestBody(l,manager,{title:'P12 manager created synthetic inspection',photos:[{assetId:p.id,version:p.version,caption:'Manager supplied synthetic tap photo'}]}),created=(await maintenance(manager).professionalCreate(req('POST','/api/v1/ops/maintenance'),x)).data;expect(created.requestedBy).toBe('management');expect((await maintenance().tenantRead(req('GET'),created.id)).data.requestedBy).toBe('management');expect((await maintenance().tenantList(req('GET'),{})).data.items.some((r:any)=>r.id===created.id)).toBe(true);},90000);
it('P12 foreign unit/persona/media, stale source versions, malformed labels and inactive workflow states deny without partial request roots',async()=>{const f=await fixture(),l=await active(f),x=await requestBody(l),foreign:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};await expect(maintenance(foreign).tenantCreate(req('POST','/api/v1/me/maintenance'),x)).rejects.toMatchObject({status:404});const assets=[await photo(manager.id),await photo(tenant.id,{status:'quarantined',scan:null}),await photo(tenant.id,{visibility:'public'}),await photo(tenant.id,{purpose:'document',mime:'application/pdf'})];for(const patch of [{leaseVersion:999},{unitVersion:999},{grantVersion:999},{confirm:false},{title:'x'},{description:'short'},{category:'Unknown'},...assets.map(p=>({photos:[{assetId:p.id,version:p.version,caption:'Unauthorized synthetic photo'}]}))])await expect(maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),{...x,...patch})).rejects.toBeDefined();expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM maintenance WHERE lease_id=$1',[l.id]))).rows[0].n).toBe(0);const pending=await draft(f,'2038-01-01','2038-12-31');await expect(maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),{...x,leaseId:pending.id,leaseVersion:pending.version})).rejects.toMatchObject({status:404});},90000);
it('P12 cross-request photo guessing, invalid transitions, stale request versions and wrong-team assignment deny; revoked grant denies manager and new tenant creates',async()=>{const f=await fixture(),l=await active(f),p=await photo(),created=(await maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),await requestBody(l,tenant,{photos:[{assetId:p.id,version:p.version,caption:'Private synthetic maintenance photo'}]}))).data,foreign:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};await expect(maintenance(foreign).tenantRead(req('GET'),created.id)).rejects.toMatchObject({status:404});await expect(maintenance(foreign).photo(req('GET'),created.id,p.id,{} as any)).rejects.toMatchObject({status:404});await expect(maintenance().photo(req('GET'),crypto.randomUUID(),p.id,{} as any)).rejects.toMatchObject({status:404});let team=(await maintenance(manager).professionalRead(req('GET'),created.id)).data;await expect(maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,workflow(team,'assigned',manager.id))).rejects.toBeDefined();await expect(maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,{...workflow(team),version:999})).rejects.toMatchObject({status:409});team=(await maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,workflow(team))).data;await expect(maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,workflow(team,'assigned',foreign.id))).rejects.toMatchObject({status:404});await expect(maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,workflow(team,'triaged'))).rejects.toBeDefined();const x=await requestBody(l);await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner revoked professional authority for maintenance service.'});await expect(maintenance(manager).professionalRead(req('GET'),created.id)).rejects.toMatchObject({status:404});await expect(maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),x)).rejects.toMatchObject({status:404});expect((await maintenance().tenantRead(req('GET'),created.id)).data.status).toBe('triaged');},90000);
it('P12 SQL rejects unversioned runtime request and immutable photo/history edits; activity is committed with exact database timestamp',async()=>{const f=await fixture(),l=await active(f),x=await requestBody(l);await expect(transaction(tenant,c=>c.query("INSERT INTO maintenance(lease_id,organization_id,user_id,title,description,category,urgency) VALUES($1,$2,$3,'Unversioned native bypass','Synthetic bypass request must not commit','Plumbing','Routine')",[l.id,manager.orgId,tenant.id]))).rejects.toBeDefined();const created=(await maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),x)).data;expect((await transaction(workerActor,c=>c.query('SELECT h.at=r.updated_at AS exact FROM maintenance_history h JOIN maintenance r ON r.id=h.request_id WHERE r.id=$1 AND h.version=r.version',[created.id]))).rows[0].exact).toBe(true);expect((await transaction(workerActor,c=>c.query("UPDATE maintenance_history SET public_note='Altered immutable history' WHERE request_id=$1",[created.id]))).rowCount).toBe(0);expect((await transaction(workerActor,c=>c.query('SELECT public_note FROM maintenance_history WHERE request_id=$1',[created.id]))).rows[0].public_note).toBeNull();},90000);
