import {MaintenanceController} from '../../apps/api/src/management/maintenance';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P13 verified synthetic tenant',true)",[tenant.id,'p13-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P13 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P13 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p13-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P13 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31',documents:{assetId:string;version:number;label:string}[]=[]){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}

const maintenance=(a=tenant)=>new MaintenanceController(identity(a));
async function requestBody(l:any,a=tenant,patch:any={}){const options=(await (a.id===tenant.id?maintenance(a).tenantOptions(req('GET'),{leaseId:l.id}):maintenance(a).professionalOptions(req('GET'),{leaseId:l.id}))).data,s=options.find((r:any)=>r.leaseId===l.id);expect(s).toBeTruthy();return {version:0,leaseId:l.id,leaseVersion:s.leaseVersion,unitVersion:s.unitVersion,grantVersion:s.grantVersion,title:'P13 synthetic kitchen tap request',description:'The supplied synthetic tap photo accompanies a request to inspect a continuous drip.',category:'Plumbing',urgency:'Routine',photos:[],confirm:true,...patch};}
const workflow=(r:any,status='triaged',assigneeId:string|null=null)=>({version:r.version,leaseVersion:r.leaseVersion,unitVersion:r.unitVersion,grantVersion:r.grantVersion,status,assigneeId,publicNote:'The current management team will inspect this request.'});

it('P13 manager resolution and tenant reopen preserve public progression while all tenant APIs exclude internal notes',async()=>{const f=await fixture(),l=await active(f),created=(await maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),await requestBody(l))).data;let team=(await maintenance(manager).professionalRead(req('GET'),created.id)).data;const sentinel='PRIVATE P13 SENTINEL '+crypto.randomUUID();for(const status of ['triaged','assigned','in_progress','resolved']){team=(await maintenance(manager).change(req('PATCH','/api/v1/ops/maintenance/'+team.id),team.id,{...workflow(team,status,manager.id),publicNote:'Public inspection progression: '+status,internalNote:sentinel+' '+status})).data;}expect(team.internalNotes).toHaveLength(4);let own=(await maintenance().tenantRead(req('GET'),created.id)).data;expect(own.canReopen).toBe(true);expect(own.activity.map((h:any)=>h.status)).toEqual(['open','triaged','assigned','in_progress','resolved']);for(const v of [own,(await maintenance().tenantList(req('GET'),{})).data]){expect(JSON.stringify(v)).not.toContain(sentinel);expect(JSON.stringify(v)).not.toContain('internalNotes');}const input={version:own.version,leaseVersion:own.leaseVersion,unitVersion:own.unitVersion,grantVersion:own.grantVersion,action:'reopen',publicNote:'The synthetic tap still leaks after the recorded repair.'},r=req('PATCH','/api/v1/me/maintenance/'+own.id);own=(await maintenance().tenantChange(r,own.id,input)).data;expect(own).toMatchObject({status:'reopened',version:6,canReopen:false});expect((await maintenance().tenantChange(r,own.id,input)).data.version).toBe(6);team=(await maintenance(manager).professionalRead(req('GET'),created.id)).data;expect(team.internalNotes).toHaveLength(4);team=(await maintenance(manager).change(req('PATCH'),team.id,{...workflow(team,'assigned',manager.id),publicNote:'Returning to the authorized assigned team.'})).data;for(const status of ['in_progress','resolved','closed'])team=(await maintenance(manager).change(req('PATCH'),team.id,workflow(team,status,manager.id))).data;await expect(transaction(manager,c=>c.query('INSERT INTO maintenance_internal_notes(request_id,request_version,body,actor_id) VALUES($1,$2,$3,$4)',[team.id,team.version,'A standalone note must not mutate an already closed request.',manager.id]))).rejects.toMatchObject({code:'23514'});own=(await maintenance().tenantRead(req('GET'),team.id)).data;expect(own.canComment).toBe(false);await expect(maintenance().tenantChange(req('PATCH'),own.id,{...input,version:own.version})).rejects.toMatchObject({status:409});},90000);
it('P13 versioned public comments and private-only notes remain immutable, filtered and currently scoped',async()=>{const f=await fixture(),l=await active(f),created=(await maintenance().tenantCreate(req('POST','/api/v1/me/maintenance'),await requestBody(l))).data;let own=(await maintenance().tenantRead(req('GET'),created.id)).data;const comment={version:own.version,leaseVersion:own.leaseVersion,unitVersion:own.unitVersion,grantVersion:own.grantVersion,action:'comment',publicNote:'The authorized tenant adds a synthetic inspection detail.'};own=(await maintenance().tenantChange(req('PATCH'),own.id,comment)).data;expect(own).toMatchObject({version:2,status:'open'});let team=(await maintenance(manager).professionalRead(req('GET'),own.id)).data;team=(await maintenance(manager).change(req('PATCH'),team.id,{...workflow(team,'open'),publicNote:team.publicNote,internalNote:'Private-only synthetic team logistics.'})).data;expect(team).toMatchObject({version:3,status:'open'});expect(team.internalNotes[0].body).toContain('Private-only');expect((await transaction(tenant,c=>c.query('SELECT * FROM maintenance_internal_notes WHERE request_id=$1',[team.id]))).rowCount).toBe(0);expect((await transaction(manager,c=>c.query("UPDATE maintenance_internal_notes SET body='Altered private note' WHERE request_id=$1",[team.id]))).rowCount).toBe(0);const page=(await maintenance(manager).professionalList(req('GET'),{status:'open',category:'Plumbing',urgency:'Routine'})).data;expect(page.items.some((r:any)=>r.id===team.id)).toBe(true);expect((await maintenance(manager).professionalList(req('GET'),{status:'closed'})).data.items.some((r:any)=>r.id===team.id)).toBe(false);await expect(maintenance().tenantChange(req('PATCH'),own.id,comment)).rejects.toMatchObject({status:409});const foreign:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};await expect(maintenance(foreign).tenantChange(req('PATCH'),own.id,{...comment,version:team.version})).rejects.toMatchObject({status:404});await expect(maintenance().tenantChange(req('PATCH'),own.id,{...comment,version:team.version,action:'reopen'})).rejects.toMatchObject({status:409});await new ManagementGrantsController(identity(owner)).update(req('PATCH'),f.g.id,{action:'revoke',version:1,reason:'Owner revoked synthetic maintenance service authority.'});own=(await maintenance().tenantRead(req('GET'),own.id)).data;expect(own.canComment).toBe(false);await expect(maintenance().tenantChange(req('PATCH'),own.id,{...comment,version:own.version})).rejects.toMatchObject({status:404});await expect(maintenance(manager).professionalRead(req('GET'),own.id)).rejects.toMatchObject({status:404});},90000);
