import {managementDashboard} from '../../apps/api/src/management/dashboard';
import {MaintenanceController} from '../../apps/api/src/management/maintenance';
import {createRequire} from 'node:module';
import {FinancialReversalsController} from '../../apps/api/src/management/financial-reversals';
import {PaymentAllocationsController} from '../../apps/api/src/management/payment-allocations';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtureDB=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});
const otherOwner:Actor={id:crypto.randomUUID(),orgId:null,roles:['owner']};
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P15 other synthetic owner',true)",[otherOwner.id,'p15-owner-'+otherOwner.id,otherOwner.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,role,status) VALUES($1,'owner','active')",[otherOwner.id]);});await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P15 verified synthetic tenant',true)",[tenant.id,'p15-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string,currency='CNY',communityId?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT coalesce($4::uuid,community_id),organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P15 room '+crypto.randomUUID().slice(0,8):null,communityId||null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P15 synthetic rental offer',description,'rent','residential',$4,'1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p15-'+crypto.randomUUID(),currency])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month',currency]);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source,currency};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P15 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31',documents:{assetId:string;version:number;label:string}[]=[]){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:f.currency,rentPeriod:'month',dueDay:5,documents})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});await fixtureDB.end();});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2026-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
async function financial(amount='250.25',charged='200.20'){const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(l.id),amount})).data,posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(p))).data,ch=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,created_at) VALUES($1,$2,date_trunc('month',current_date-45)::date,current_date-45,$3,'CNY',now()-interval '90 days') RETURNING id,version",[l.id,manager.orgId,charged])).rows[0]);return {...f,l,p:posted,ch};}

const allocations=()=>new PaymentAllocationsController(identity(manager)),reversals=()=>new FinancialReversalsController(identity(manager));
async function allocated(f:Awaited<ReturnType<typeof financial>>){const l=(await allocations().ledger(req('GET'),f.l.id,{})).data;return allocations().create(req('POST','/api/v1/ops/allocations'),{version:0,leaseId:f.l.id,leaseVersion:l.leaseVersion,unitVersion:l.unitVersion,grantVersion:l.grantVersion,paymentId:f.p.id,paymentVersion:f.p.version,chargeId:f.ch.id,chargeVersion:f.ch.version,amount:'50.05',currency:'CNY',confirm:true});}
const addMoney=(a:string,b:string)=>{const n=BigInt(a.replace('.',''))+BigInt(b.replace('.',''));return (n/100n).toString()+'.'+(n%100n).toString().padStart(2,'0');};
const today=new Date().toISOString().slice(0,10),read=(a=manager,date=today)=>transaction(a,c=>managementDashboard(c,{date}));
const moneyRow=(r:any)=>r.arrears.find((x:any)=>x.currency==='CNY');
it('P15 source counts and aging reconcile, and native payment reversal restores overdue charge debt',async()=>{
 const base=await read(),f=await financial(),vacant=await fixture();await allocated(f);const r=await read();
 expect(r.occupancy.units).toBe(base.occupancy.units+2);expect(r.occupancy.occupied).toBe(base.occupancy.occupied+1);expect(r.occupancy.vacant).toBe(base.occupancy.vacant+1);
 const before=moneyRow(base),after=moneyRow(r);expect(after.days31to60).toBe(addMoney(before?.days31to60||'0.00','150.15'));expect(after.total).toBe(addMoney(before?.total||'0.00','150.15'));
 const source=await transaction(manager,c=>c.query('SELECT count(DISTINCT unit_id)::int n FROM management_grants WHERE organization_id=org_id() AND management_grant_valid(id)'));expect(r.occupancy.units).toBe(source.rows[0].n);expect(r.occupancy.units).toBe(r.occupancy.occupied+r.occupancy.vacant+r.occupancy.unknownHistory);
 const original=(await reversals().read(req('GET'),'payment',f.p.id)).data;await reversals().reversePayment(req(),f.p.id,{version:original.version,leaseVersion:original.leaseVersion,unitVersion:original.unitVersion,grantVersion:original.grantVersion,reason:'P15 verified correction restores posted charge debt.',confirm:true});const reversed=await read();expect(moneyRow(reversed).days31to60).toBe(addMoney(after.days31to60,'50.05'));
 expect(r.definitions.arrears).toContain('due date');expect(r.date).toBe(today);expect(r.timeZone).toBe('UTC');expect(JSON.stringify(r)).not.toContain(f.p.reference);expect(vacant.unit.id).not.toBe(f.unit.id);
},90000);
it('P15 immutable maintenance status, missing history and historical occupancy are declared with no private projection',async()=>{
 const f=await fixture(),l=await active(f),api=new MaintenanceController(identity(tenant)),options=(await api.tenantOptions(req('GET'),{leaseId:l.id})).data.find((r:any)=>r.leaseId===l.id),base=await read();
 const request=(await api.tenantCreate(req(),{version:0,leaseId:l.id,leaseVersion:options.leaseVersion,unitVersion:options.unitVersion,grantVersion:options.grantVersion,title:'P15 synthetic leaking kitchen tap',description:'P15 synthetic continuous drip needs inspection by the current team.',category:'Plumbing',urgency:'Routine',photos:[],confirm:true})).data;
 const team=new MaintenanceController(identity(manager)),detail=(await team.professionalRead(req('GET'),request.id)).data;await team.change(req('PATCH'),request.id,{version:detail.version,leaseVersion:detail.leaseVersion,unitVersion:detail.unitVersion,grantVersion:detail.grantVersion,status:'triaged',assigneeId:null,publicNote:'Current team will inspect this tap.',internalNote:'P15 PRIVATE MAINTENANCE SENTINEL'});
 await transaction(workerActor,c=>c.query("INSERT INTO maintenance(lease_id,organization_id,user_id,title,description,category,urgency,status) VALUES($1,$2,$3,'P15 historical request','P15 PRIVATE LEGACY SENTINEL','Other','Routine','open')",[l.id,manager.orgId,tenant.id]));
 const r=await read(),count=(x:any,status:string)=>x.maintenance.counts.find((v:any)=>v.status===status)?.count||0;expect(count(r,'triaged')).toBe(count(base,'triaged')+1);expect(r.maintenance.unknownHistory).toBe(base.maintenance.unknownHistory+1);expect(JSON.stringify(r)).not.toContain('SENTINEL');expect(JSON.stringify(r)).not.toContain('actor_id');
 const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10),prior=await read(manager,yesterday);expect(prior.occupancy.occupied).toBeLessThan(r.occupancy.occupied);expect(count(prior,'triaged')).toBeLessThan(count(r,'triaged'));expect(prior.definitions.maintenance).toContain('unknown');
},90000);
it('P15 current exact scope omits revoked foreign money and denies forged roles and selected foreign organization',async()=>{
 const f=await financial('9900.99','9000.99');await new ManagementGrantsController(identity(owner)).update(req('PATCH'),f.g.id,{action:'revoke',version:1,reason:'P15 this property is outside current service authority.'});const first=await read();
 await transaction(workerActor,c=>c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind) VALUES($1,$2,'2026-01-01','2026-01-01','999999999.99','CNY','p15-foreign-extra')",[f.l.id,manager.orgId]));expect((await read()).arrears).toEqual(first.arrears);expect((await read()).occupancy).toEqual(first.occupancy);
 for(const a of [owner,{...otherOwner,orgId:manager.orgId,roles:['property_manager','finance','admin']},{...manager,orgId:'10000000-0000-4000-8000-000000000001'}])await expect(read(a)).rejects.toMatchObject({status:403});
 await expect(read(manager,'0000-01-01')).rejects.toThrow();await expect(read(manager,'2999-01-01')).rejects.toMatchObject({status:400});
},90000);
it('P15 all due-date boundaries preserve separate exact USD totals above Number precision',async()=>{
 const communityId=await transaction(workerActor,async c=>{const suffix=crypto.randomUUID(),ci=(await c.query("INSERT INTO cities(slug,name,country,currency,timezone) VALUES($1,'P15 synthetic US market','US','USD','America/New_York') RETURNING id",['p15-'+suffix])).rows[0],d=(await c.query("INSERT INTO districts(city_id,name,slug) VALUES($1,'P15 synthetic district',$2) RETURNING id",[ci.id,'p15-'+suffix])).rows[0];return (await c.query("INSERT INTO communities(district_id,slug,name,address) VALUES($1,$2,'P15 synthetic USD community','Synthetic address') RETURNING id",[d.id,'p15-'+suffix])).rows[0].id;});
 const f=await fixture(undefined,'USD',communityId),l=await active(f);await transaction(workerActor,c=>c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind) SELECT $1,$2,date_trunc('month',current_date)::date,current_date-n,'9007199254740993.01','USD','p15-boundary-'||n FROM unnest(ARRAY[0,1,31,61,91]) n",[l.id,manager.orgId]));const r=await read(),usd=r.arrears.find(x=>x.currency==='USD')!;expect(usd).toMatchObject({notDue:'9007199254740993.01',days1to30:'9007199254740993.01',days31to60:'9007199254740993.01',days61to90:'9007199254740993.01',daysOver90:'9007199254740993.01',total:'45035996273704965.05',charges:5});expect(r.arrears.filter(x=>x.currency==='USD')).toHaveLength(1);
 const financeOnly:Actor={id:crypto.randomUUID(),orgId:manager.orgId,roles:['finance']};await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P15 synthetic finance only',true)",[financeOnly.id,'p15-finance-'+financeOnly.id,financeOnly.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,'finance','active')",[financeOnly.id,manager.orgId]);});const finance=await read(financeOnly);expect(finance.maintenance).toEqual(r.maintenance);expect(finance.arrears).toEqual(r.arrears);expect(finance.occupancy).toEqual(r.occupancy);
 await transaction(workerActor,async c=>{const ch=(await c.query('SELECT id FROM charges WHERE lease_id=$1 ORDER BY due_date LIMIT 1',[l.id])).rows[0],p=(await c.query("INSERT INTO payments(lease_id,organization_id,amount,currency,source,reference,actor_id,status) VALUES($1,$2,'1.01','EUR','bank_statement','P15 historical conflict',$3,'posted') RETURNING id",[l.id,manager.orgId,manager.id])).rows[0];await c.query("INSERT INTO allocations(payment_id,charge_id,organization_id,amount) VALUES($1,$2,$3,'1.01')",[p.id,ch.id,manager.orgId]);});await expect(read()).rejects.toMatchObject({status:409});
},90000);
