import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController,managementPortfolio} from '../../apps/api/src/management/grants';
import {PrivacyController} from '../../apps/api/src/identity/privacy';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},foreign:Actor={id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['property_manager']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a:Actor)=>new ManagementGrantsController(identity(a)),req=(method='POST',url='/api/v1/me/management-grants')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],roots:string[]=[],sources:string[]=[];
async function fixture(){return transaction(workerActor,async c=>{const u=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version")).rows[0];units.push(u.id);const l=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status) SELECT $1,organization_id,$2,agent_id,$3,'P01 canonical ownership fixture',description,'sale','residential','CNY','2400000.75','draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[u.id,owner.id,'p01-'+crypto.randomUUID()])).rows[0];const g=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING id,version",[u.id,owner.id,l.id])).rows[0];sources.push(g.id);return {unit:u,source:g,input:{version:0,unitId:u.id,unitVersion:u.version,ownerGrantVersion:g.version,organizationId:manager.orgId,expiresAt:'2030-12-31T00:00:00.000Z',consent:true}};});}
async function create(){const f=await fixture(),g=(await api(owner).create(req(),f.input)).data;roots.push(g.id);return {...f,g};}
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[roots]);await c.query("UPDATE owner_unit_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[sources]);});});
it('P01 owner grant admits manager to the same canonical unit, retries persist one root and privacy history',async()=>{const f=await fixture(),r=req(),g=(await api(owner).create(r,f.input)).data;roots.push(g.id);expect((await api(owner).create(r,f.input)).data.id).toBe(g.id);expect(g).toMatchObject({unit_id:f.unit.id,version:1,effective:true,historical:false});expect(g.activity).toHaveLength(1);expect((await transaction(manager,c=>managementPortfolio(c))).map(x=>x.id)).toContain(g.id);expect((await api(manager).professional(req('GET'),g.id)).data.unit_id).toBe(f.unit.id);await expect(api(owner).create(req(),f.input)).rejects.toMatchObject({status:409});const counts=await transaction(workerActor,async c=>(await c.query("SELECT (SELECT count(*) FROM units WHERE id=$1)::int units,(SELECT count(*) FROM management_grants WHERE unit_id=$1)::int grants,(SELECT count(*) FROM outbox WHERE aggregate_id=$2 AND kind='management-grant.granted')::int events",[f.unit.id,g.id])).rows[0]);expect(counts).toEqual({units:1,grants:1,events:1});const exported=(await new PrivacyController(identity(owner)).export(req('GET'))).data;expect(exported.records.managementGrants.some((x:any)=>x.id===g.id)).toBe(true);});
it('P01 foreign and forged administrator membership cannot enumerate or guess a granted property',async()=>{const {g}=await create();for(const actor of [foreign,{...foreign,roles:['admin']}]){expect((await transaction(actor,c=>managementPortfolio(c))).map(x=>x.id)).not.toContain(g.id);await expect(api(actor).professional(req('GET'),g.id)).rejects.toMatchObject({status:404});await expect(api(actor).detail(req('GET'),g.id)).rejects.toMatchObject({status:404});}expect((await transaction(manager,c=>c.query("UPDATE management_grants SET expires_at='2040-01-01' WHERE id=$1",[g.id]))).rowCount).toBe(0);expect((await transaction(owner,c=>c.query("UPDATE management_grant_activity SET note='forged history' WHERE grant_id=$1",[g.id]))).rowCount).toBe(0);});
it('P01 expiry, owner source revocation and management revocation immediately deny portfolio access while preserving owner history',async()=>{const {g,source,unit}=await create();await transaction(workerActor,c=>c.query("UPDATE management_grants SET starts_at=now()-interval '2 days',expires_at=now()-interval '1 second' WHERE id=$1",[g.id]));await expect(api(manager).professional(req('GET'),g.id)).rejects.toMatchObject({status:404});const renewed=(await api(owner).update(req('PATCH','/api/v1/me/management-grants/'+g.id),g.id,{action:'renew',version:1,unitVersion:unit.version,ownerGrantVersion:1,expiresAt:'2031-01-01T00:00:00.000Z',consent:true})).data;expect(renewed.effective).toBe(true);await transaction(workerActor,c=>c.query("UPDATE owner_unit_grants SET status='revoked',version=version+1 WHERE id=$1",[source.id]));await expect(api(manager).professional(req('GET'),g.id)).rejects.toMatchObject({status:404});expect((await api(owner).detail(req('GET'),g.id)).data).toMatchObject({effective:false,area:'88.50'});const r=req('PATCH','/api/v1/me/management-grants/'+g.id),body={action:'revoke',version:2,reason:'Owner ended this management authorization.'};expect((await api(owner).update(r,g.id,body)).data.status).toBe('revoked');expect((await api(owner).update(r,g.id,body)).data.version).toBe(3);await expect(api(owner).update(req('PATCH','/api/v1/me/management-grants/'+g.id),g.id,body)).rejects.toMatchObject({status:409});expect((await api(owner).detail(req('GET'),g.id)).data.activity.map((a:any)=>a.action)).toEqual(['granted','renewed','revoked']);});
it('P01 native grant requires current source and unit versions, consent and future expiry',async()=>{const {input}=await fixture();for(const patch of [{unitVersion:999},{ownerGrantVersion:999},{consent:false},{expiresAt:'2020-01-01T00:00:00.000Z'},{organizationId:foreign.orgId}])await expect(api(owner).create(req(),{...input,...patch})).rejects.toBeDefined();await expect(api(foreign).create(req(),input)).rejects.toMatchObject({status:404});});

it('P01 revocation removes lease reads for manager and finance-only sessions; real membership loss denies grant admission',async()=>{const {g,unit}=await create();const lease=await transaction(workerActor,async c=>(await c.query("INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency) VALUES($1,$2,'10000000-0000-4000-8000-000000005000','2030-01-01','2030-12-31','1234.50','CNY') RETURNING id",[manager.orgId,unit.id])).rows[0]);for(const a of [manager,{...manager,roles:['finance']}])expect((await transaction(a,c=>c.query('SELECT id FROM leases WHERE id=$1',[lease.id]))).rowCount).toBe(1);await api(owner).update(req('PATCH','/api/v1/me/management-grants/'+g.id),g.id,{action:'revoke',version:1,reason:'Owner withdrew property authorization.'});for(const a of [manager,{...manager,roles:['finance']}])expect((await transaction(a,c=>c.query('SELECT id FROM leases WHERE id=$1',[lease.id]))).rowCount).toBe(0);const current=await create();await transaction(workerActor,c=>c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=$1 AND organization_id=$2 AND role IN('property_manager','finance')",[manager.id,manager.orgId]));try{await expect(api(manager).professional(req('GET'),current.g.id)).rejects.toMatchObject({status:404});expect((await transaction(manager,c=>c.query('SELECT management_unit_grant_lock($1,$2) AS version',[current.unit.id,manager.orgId]))).rows[0].version).toBeNull();}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='active',version=version+1 WHERE user_id=$1 AND organization_id=$2 AND role IN('property_manager','finance')",[manager.id,manager.orgId]));}});
