import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {workerActor} from '../../apps/worker/src/processor';
import type {Identity} from '../../apps/api/src/platform/core';
import {GeographyController} from '../../apps/api/src/geography/administration';
import {DiscoveryController} from '../../apps/api/src/geography/controller';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
const admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin']},buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};afterAll(()=>pool.end());
const api=(a=admin)=>new GeographyController({actor:async()=>a} as unknown as Identity),req=(url='/api/v1/ops/cities/bj/market',method='PATCH')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
it('S05 native new-market config activation validates ISO/zone, retains exact attributed history and historical money/currency/areas',async()=>{
 const slug='s05-'+crypto.randomUUID(),created=(await api().create(req('/api/v1/ops/geography/cities','POST'),'cities',{kind:'cities',name:'S05 synthetic market',slug,aliases:[],country:'AE',currency:'AED',timezone:'Asia/Dubai'})).data;let current=(await api().marketRead(req(),'bj')).data;const original=current,charges=await transaction(workerActor,c=>c.query('SELECT id,amount::text,currency FROM charges ORDER BY id LIMIT 20')),prices=await transaction(workerActor,c=>c.query('SELECT l.id,l.price::text,l.currency,u.area::text FROM listings l JOIN units u ON u.id=l.unit_id ORDER BY l.id LIMIT 20'));
 expect(charges.rows.length).toBeGreaterThan(0);expect(prices.rows.length).toBeGreaterThan(0);const source=(await api().marketRead(req(),slug)).data;const input={...source.data,version:source.version,cityVersion:source.cityVersion,areaUnit:'sq ft',annualRate:'4.25',credentialRules:{holderMinLength:3,registrationMinLength:4,issuerMinLength:3,maxValidityDays:730},ownershipTags:[{key:'leasehold',label:'Recorded leasehold',explanation:'A recorded market attribute; no tax consequence is inferred.'}],contactLinks:{supportPhone:'+971 40000000',supportWebsite:'https://example.com/support',iosApp:null,androidApp:null}};delete (input as any).name;const ack=req('/api/v1/ops/cities/'+slug+'/market');const saved=(await api().market(ack,slug,input)).data;expect(saved).toMatchObject({version:2,data:{currency:'AED',timezone:'Asia/Dubai',areaUnit:'sq ft'}});expect((await api().market(ack,slug,input)).data.version).toBe(2);const history=(await api().marketHistory(req(),slug)).data;expect(history.at(-1)).toMatchObject({version:2,actorId:admin.id,historical:false});expect(history.at(-1)?.data.ownershipTags).toEqual(input.ownershipTags);expect((await new DiscoveryController().market(slug)).data.data.contactLinks).toEqual(input.contactLinks);
 const old={...current.data,version:current.version,cityVersion:current.cityVersion,currency:'USD',timezone:'UTC',areaUnit:'sq ft'};delete (old as any).name;try{current=(await api().market(req(),'bj',old)).data;expect(current.data.currency).toBe('USD');expect((await transaction(workerActor,c=>c.query('SELECT id,amount::text,currency FROM charges ORDER BY id LIMIT 20'))).rows).toEqual(charges.rows);expect((await transaction(workerActor,c=>c.query('SELECT l.id,l.price::text,l.currency,u.area::text FROM listings l JOIN units u ON u.id=l.unit_id ORDER BY l.id LIMIT 20'))).rows).toEqual(prices.rows);}finally{const restore={...original.data,version:current.version,cityVersion:current.cityVersion};delete (restore as any).name;await api().market(req(),'bj',restore);}
 await expect(api().market(req(),slug,{...input,version:2,currency:'ZZZ'})).rejects.toThrow();await expect(api().market(req(),slug,{...input,version:2,timezone:'Asia/Unknown'})).rejects.toThrow();await expect(api().market(req(),slug,{...input,version:2,contactLinks:{...input.contactLinks,supportWebsite:'javascript:alert(1)'}})).rejects.toThrow();await expect(api().market(req(),slug,{...input,version:2,currency:'USD',cityVersion:999})).rejects.toMatchObject({status:409});await expect(api().market(req(),slug,input)).rejects.toMatchObject({status:409});expect(created.currency).toBe('AED');expect((await transaction(admin,c=>c.query("UPDATE market_configuration_history SET data='{}' WHERE city=$1",[slug]))).rowCount).toBe(0);
});
it('S05 actual admin permission and strict field validation deny forged updates/history, duplicate tags and unknown finance rules',async()=>{const current=(await api().marketRead(req(),'bj')).data;const input={...current.data,version:current.version,cityVersion:current.cityVersion};delete (input as any).name;for(const a of [buyer,{...buyer,roles:['admin']}]){await expect(api(a).market(req(),'bj',input)).rejects.toMatchObject({status:403});await expect(api(a).marketHistory(req(),'bj')).rejects.toMatchObject({status:403});}await expect(api().market(req(),'bj',{...input,ownershipTags:[{key:'same',label:'First',explanation:'First label explanation'},{key:'same',label:'Second',explanation:'Second label explanation'}]})).rejects.toThrow();await expect(api().market(req(),'bj',{...input,chargeProration:'floating_money'})).rejects.toThrow();});
