import {fixtureAccountState} from '../support/account-fixture';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import {ConversationsController} from '../../apps/api/src/engagement/conversations';
import {ChatMediaController} from '../../apps/api/src/inventory/chat-media';
import {MediaController} from '../../apps/api/src/inventory/media';
import type {FastifyReply} from 'fastify';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',foreign='10000000-0000-4000-8000-000000000005',buyer:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']},people:(Actor&{agent:string})[]=[],leads:string[]=[],threads:string[]=[];
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),engagement=(a:Actor)=>new EngagementController(identity(a)),conversations=(a:Actor)=>new ConversationsController(identity(a)),req=(url='/api/v1/inquiries')=>({method:'POST',url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
beforeAll(async()=>{await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'M02 customer',true)",[buyer.id,'m02-'+buyer.id,'m02-'+buyer.id+'@example.test']);for(const agency of [org,org,foreign]){const id=crypto.randomUUID(),agent=crypto.randomUUID();await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'M02 professional',true)",[id,'m02-'+id,'m02-'+id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,'agent')",[id,agency]);await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'M02 synthetic agent',$4,'Synthetic membership acceptance fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,id,agency,'m02-'+agent]);people.push({id,agent,orgId:agency,roles:['agent']});}});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=ANY($1::uuid[])",[leads]);await c.query("UPDATE conversations SET state='closed',version=version+1 WHERE id=ANY($1::uuid[])",[threads]);await c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=ANY($1::uuid[])",[people.map(p=>p.id)]);await fixtureAccountState(c,'suspended',"WHERE id=ANY($1::uuid[])",[[buyer.id,...people.map(p=>p.id)]]);});}finally{await pool.end();}});
async function inquiry(){const r=(await engagement(buyer).inquiry(req(),{resourceId:people[0].agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M02 customer',email:'message-'+buyer.id+'@example.test',phone:'123456789',message:'A real linked inquiry for this agent',consent:true})).data;leads.push(r.id);threads.push(r.conversationId!);return r;}
async function payload(id:string,body:string,attachments:{assetId:string;version:number}[]=[]){return {version:0,conversationVersion:(await conversations(buyer).detail(req(),id)).data.version,body,clientId:crypto.randomUUID(),attachments};}
const pdf=Buffer.from('%PDF-1.4\n1 0 obj << /Type /Catalog >> endobj\n%%EOF');
async function upload(id:string,complete=true){const chat=new ChatMediaController(identity(buyer)),version=(await conversations(buyer).detail(req(),id)).data.version,r=(await chat.intent(req('/api/v1/conversations/'+id+'/attachment-intents'),id,{version:0,conversationVersion:version,mime:'application/pdf',size:pdf.length,filename:'inspection-note.pdf',rights:'I own this synthetic scanner acceptance fixture.'})).data;if(complete){const url=new URL(r.uploadUrl,'http://api'),request={method:'PUT',url:url.pathname,query:{signature:url.searchParams.get('signature')},headers:{'content-type':'application/pdf'}} as unknown as FastifyRequest;await new MediaController(identity(buyer)).content(request,r.id,pdf);}const status=(await new MediaController(identity(buyer)).status(req(),r.id)).data;return {assetId:r.id,version:status.version};}
it('M02 same client ID replay, including concurrent retries, returns one committed message and one event; changed content cannot reuse it',async()=>{const lead=await inquiry(),id=lead.conversationId!,x=await payload(id,'One durable acknowledgement');const results=await Promise.all([engagement(buyer).message(req(),id,x),engagement(buyer).message(req(),id,x)]);expect(results[0]).toEqual(results[1]);expect((await engagement(buyer).message(req(),id,x)).data.id).toBe(results[0].data.id);await expect(engagement(buyer).message(req(),id,{...x,body:'Different content'})).rejects.toMatchObject({status:409});expect((await engagement(buyer).messages(req(),id)).data).toHaveLength(1);expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='message.persisted'",[id]))).rows[0].n).toBe(1);await expect(transaction(buyer,c=>c.query("UPDATE messages SET body='Changed after acknowledgement' WHERE id=$1",[results[0].data.id]))).rejects.toMatchObject({code:'42501'});});
it('M02 concurrent different participants receive unique ordered BIGINT sequences; stale grants and cross-room client ID reuse persist no new message',async()=>{const lead=await inquiry(),id=lead.conversationId!,x=await payload(id,'Concurrent message');const results=await Promise.all([engagement(buyer).message(req(),id,x),engagement(people[0]).message(req(),id,{...x,clientId:crypto.randomUUID(),body:'Assigned agent response'}),engagement(buyer).message(req(),id,{...x,clientId:crypto.randomUUID(),body:'Third response'})]);expect(new Set(results.map(r=>r.data.sequence)).size).toBe(3);expect((await engagement(buyer).messages(req(),id)).data.map(m=>m.sequence)).toEqual(['1','2','3']);await expect(engagement(buyer).message(req(),id,{...x,conversationVersion:1,clientId:crypto.randomUUID()})).rejects.toMatchObject({status:409});const second=(await inquiry()).conversationId!;await expect(engagement(buyer).message(req(),second,x)).rejects.toMatchObject({status:409});await expect(transaction(buyer,c=>c.query('INSERT INTO messages(conversation_id,sender_id,client_id,sequence,body,request_hash,context_version) VALUES($1,$2,$3,1000,$4,$5,$6)',[id,buyer.id,crypto.randomUUID(),'Unordered raw message','0'.repeat(64),x.conversationVersion]))).rejects.toMatchObject({code:'23514'});expect((await engagement(buyer).messages(req(),second)).data).toEqual([]);});
it('M02 script markup stays literal plain text and Unicode normalizes; control characters are rejected before persistence',async()=>{const id=(await inquiry()).conversationId!,x=await payload(id,'<script>globalThis.chatExecuted=true</script> cafe\u0301');const saved=(await engagement(buyer).message(req(),id,x)).data;expect(saved.body).toBe('<script>globalThis.chatExecuted=true</script> café');await expect(engagement(buyer).message(req(),id,{...x,clientId:crypto.randomUUID(),body:'Bad\u0001control'})).rejects.toBeDefined();expect((await engagement(buyer).messages(req(),id)).data).toHaveLength(1);});
it('M02 scanned owned private files commit with the message and are readable only by its current participants; replay grants remain exact',async()=>{const id=(await inquiry()).conversationId!,attachment=await upload(id),x=await payload(id,'Read the attached inspection note',[attachment]),saved=(await engagement(buyer).message(req(),id,x)).data;expect(saved.attachments).toMatchObject([{assetId:attachment.assetId,version:attachment.version,filename:'inspection-note.pdf',available:true}]);let bytes:Buffer|undefined;const reply={header:()=>reply,send:(body:Buffer)=>{bytes=body;return body;}} as unknown as FastifyReply;await new ChatMediaController(identity(people[0])).download(req(),id,attachment.assetId,reply);expect(bytes).toEqual(pdf);await expect(new ChatMediaController(identity(people[1])).download(req(),id,attachment.assetId,reply)).rejects.toMatchObject({status:404});await expect(new ChatMediaController(identity(people[2])).download(req(),id,attachment.assetId,reply)).rejects.toMatchObject({status:404});expect((await engagement(buyer).message(req(),id,x)).data.id).toBe(saved.id);expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM message_attachments WHERE message_id=$1',[saved.id]))).rows[0].n).toBe(1);});
it('M02 foreign/unscanned/stale and other-conversation files are denied without partial message/event/attachment writes',async()=>{const id=(await inquiry()).conversationId!,pending=await upload(id,false),x=await payload(id,'Do not publish a partial message',[pending]);await expect(engagement(buyer).message(req(),id,x)).rejects.toMatchObject({status:404});const owned=await upload(id);await expect(engagement(people[0]).message(req(),id,{...x,attachments:[owned]})).rejects.toMatchObject({status:404});await expect(engagement(buyer).message(req(),id,{...x,attachments:[{...owned,version:1}]})).rejects.toMatchObject({status:409});const otherId=(await inquiry()).conversationId!,otherFile=await upload(otherId);await expect(engagement(buyer).message(req(),id,{...x,attachments:[otherFile]})).rejects.toMatchObject({status:404});expect((await engagement(buyer).messages(req(),id)).data).toEqual([]);expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='message.persisted'",[id]))).rows[0].n).toBe(0);});
