import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {createRequire} from 'node:module';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {createProcessor,workerActor} from '../../apps/worker/src/processor';
import {deliverAlertDigest} from '../../apps/worker/src/alerts';
import {SavedSearchController} from '../../apps/api/src/engagement/saved-searches';
import {NotificationsController,NotificationWorkerController} from '../../apps/api/src/engagement/notifications';
import {AlertService} from '../../apps/api/src/engagement/alert-service';
import {createAlertMailSender} from '../../apps/api/src/engagement/mail-sender';
import type {Identity} from '../../apps/api/src/platform/core';
const require=createRequire(new URL('../../apps/worker/package.json',import.meta.url)),{Queue,Worker,QueueEvents}=require('bullmq');
afterAll(()=>pool.end());
const req=(method='POST')=>({method,url:'/api/v1/me/notifications',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
async function fixture(emailVerified=true){const user=crypto.randomUUID(),actor:Actor={id:user,orgId:null,roles:['consumer']};await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,display_name,email,email_verified) VALUES($1,$2,'Alert fixture',$3,$4)",[user,'alerts-'+user,'alert-'+user+'@example.test',emailVerified]));const identity={actor:async()=>actor} as unknown as Identity,notifications=new NotificationsController(identity),searches=new SavedSearchController(identity);return {user,actor,notifications,searches};}
async function publish(label:string){return transaction(workerActor,async c=>{const listing=(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,$2,description,'sale',segment,'CNY',price,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,version`,['a05-'+crypto.randomUUID(),label])).rows[0];const event=crypto.randomUUID();await c.query("INSERT INTO outbox(id,aggregate_id,kind,payload,dispatched_at) VALUES($1,$2,'listing.published','{}',now())",[event,listing.id]);return {...listing,event};});}
async function search(f:Awaited<ReturnType<typeof fixture>>,label:string){return(f.searches.create(req(),{version:0,name:'New matching homes',filters:{city:'bj',currency:'CNY',transaction:'sale',text:label},cadence:'daily'})).then(r=>r.data);}
async function accelerate(id:string){await transaction(workerActor,c=>c.query("UPDATE alert_digests SET due_at=now()-interval '1 second',updated_at=now()-interval '1 minute' WHERE id=$1",[id]));}
async function mailCount(id:string){return(await fetch('http://mail:8025/api/v1/search?query='+encodeURIComponent('message-id:alert-'+id+'@'+new URL(process.env.PUBLIC_WEB_URL!).hostname)).then(r=>r.json())).messages_count;}
async function queueDelivery(id:string){const redis=new URL(process.env.REDIS_URL!),connection={host:redis.hostname,port:Number(redis.port)||6379,maxRetriesPerRequest:null},name='a05-'+crypto.randomUUID(),queue=new Queue(name,{connection}),events=new QueueEvents(name,{connection}),worker=new Worker(name,job=>deliverAlertDigest(job.data.id),{connection});try{await events.waitUntilReady();const job=await queue.add('alert',{id},{attempts:5,backoff:{type:'exponential',delay:100}});return await job.waitUntilFinished(events,20000);}finally{await worker.close();await queue.obliterate({force:true});await events.close();await queue.close();}}
it('A05 a real publication worker plans one daily digest; BullMQ delivers one provider-accepted email and one in-app notification; replay stays deduplicated',async()=>{
 const f=await fixture(),label='A05'+crypto.randomUUID().replaceAll('-','');await f.notifications.update(req('PATCH'),{version:0,emailEnabled:true,inAppEnabled:true});await search(f,label);const listing=await publish(label);const project=createProcessor();await project({data:{id:listing.event}});const alerts=(await f.notifications.deliveries(req('GET'))).data;expect(alerts).toHaveLength(1);const digest=alerts[0];expect(digest).toMatchObject({status:'queued',attempts:0,acceptanceRecordedAt:null});expect(new Date(digest.dueAt).getUTCHours()).toBe(0);expect(new Date(digest.dueAt).getTime()).toBeGreaterThan(Date.now());await accelerate(digest.id);expect(await queueDelivery(digest.id)).toMatchObject({status:'accepted',attempts:1});expect(await mailCount(digest.id)).toBe(1);await project({data:{id:listing.event}});await queueDelivery(digest.id);const service=new AlertService();expect((await service.plan(listing.event,listing.version)).data.replayed).toBe(true);expect(await mailCount(digest.id)).toBe(1);const notices=(await f.notifications.read(req('GET'))).data;expect(notices).toHaveLength(1);expect(notices[0]).toMatchObject({deliveryStatus:'accepted',readAt:null});const read=req('PATCH');await f.notifications.markRead(read,notices[0].id,{version:1});expect(await f.notifications.markRead(read,notices[0].id,{version:1})).toEqual({data:{read:true}});expect((await f.notifications.read(req('GET'))).data[0].readAt).toBeTruthy();await expect(f.notifications.markRead(req('PATCH'),notices[0].id,{version:1})).rejects.toMatchObject({status:409});
 await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=$1",[f.user]));
});
it('A05 opt-out and paused searches cancel queued optional email; unverified email cannot opt in',async()=>{
 const unverified=await fixture(false);await expect(unverified.notifications.update(req('PATCH'),{version:0,emailEnabled:true,inAppEnabled:false})).rejects.toMatchObject({status:409});expect((await unverified.notifications.preferences(req('GET'))).data).toEqual({version:0,emailEnabled:false,inAppEnabled:false});
 for(const reason of ['optout','paused','withdrawn']){const f=await fixture(),label='A05'+crypto.randomUUID().replaceAll('-','');await f.notifications.update(req('PATCH'),{version:0,emailEnabled:true,inAppEnabled:true});const saved=await search(f,label),listing=await publish(label),service=new AlertService();expect((await service.plan(listing.event,listing.version)).data.planned).toBe(1);const digest=(await f.notifications.deliveries(req('GET'))).data[0];if(reason==='optout')await f.notifications.update(req('PATCH'),{version:1,emailEnabled:false,inAppEnabled:false});if(reason==='paused')await f.searches.update(req('PATCH'),saved.id,{name:saved.name,filters:saved.filters,cadence:saved.cadence,version:1,paused:true});if(reason==='withdrawn')await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[listing.id]));await accelerate(digest.id);expect((await service.deliver(digest.id,digest.version)).data.status).toBe('cancelled');expect(await mailCount(digest.id)).toBe(0);expect((await f.notifications.read(req('GET'))).data).toEqual([]);await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=$1",[f.user]));}
});
it('A05 a crash after SMTP acceptance freezes the batch and reconciles the provider receipt without a second email',async()=>{
 const f=await fixture(),label='A05'+crypto.randomUUID().replaceAll('-','');await f.notifications.update(req('PATCH'),{version:0,emailEnabled:true,inAppEnabled:true});await search(f,label);const listing=await publish(label),service=new AlertService(createAlertMailSender(),async()=>{throw Error('SIMULATED_POST_ACCEPTANCE_CRASH');});await service.plan(listing.event,listing.version);const digest=(await f.notifications.deliveries(req('GET'))).data[0];await accelerate(digest.id);await expect(service.deliver(digest.id,digest.version)).rejects.toThrow('SIMULATED_POST_ACCEPTANCE_CRASH');const processing=(await f.notifications.deliveries(req('GET'))).data[0];expect(processing).toMatchObject({status:'processing',attempts:1,acceptanceRecordedAt:null});expect(await mailCount(digest.id)).toBe(1);expect((await f.notifications.read(req('GET'))).data).toEqual([]);await f.notifications.update(req('PATCH'),{version:1,emailEnabled:false,inAppEnabled:false});await accelerate(digest.id);expect((await new AlertService().deliver(digest.id,processing.version)).data.status).toBe('accepted');expect(await mailCount(digest.id)).toBe(1);expect((await f.notifications.read(req('GET'))).data).toEqual([]);await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=$1",[f.user]));
});
it('A05 failed provider acceptance is truthful; own retry is versioned and scoped, other users and unsigned service calls are denied',async()=>{
 const f=await fixture(),other=await fixture(),label='A05'+crypto.randomUUID().replaceAll('-','');await f.notifications.update(req('PATCH'),{version:0,emailEnabled:true,inAppEnabled:false});await search(f,label);const listing=await publish(label),service=new AlertService({lookup:async()=>null,send:async()=>{throw Error('PROVIDER_OUTAGE');}});await service.plan(listing.event,listing.version);const digest=(await f.notifications.deliveries(req('GET'))).data[0];await accelerate(digest.id);const failed=(await service.deliver(digest.id,digest.version)).data;expect(failed).toMatchObject({status:'failed',attempts:1,errorCode:'MAIL_SEND_UNCONFIRMED',acceptanceRecordedAt:null});expect(await mailCount(digest.id)).toBe(0);expect((await other.notifications.deliveries(req('GET'))).data).toEqual([]);await expect(other.notifications.retry(req(),digest.id,{version:failed.version})).rejects.toMatchObject({status:404});await expect(f.notifications.retry(req(),digest.id,{version:1})).rejects.toMatchObject({status:409});const retry=req();const queued=(await f.notifications.retry(retry,digest.id,{version:failed.version})).data;expect(queued).toMatchObject({status:'queued',attempts:0,version:failed.version+1});expect((await f.notifications.retry(retry,digest.id,{version:failed.version})).data).toEqual(queued);await expect(new NotificationWorkerController().read(req('GET'),digest.id)).rejects.toMatchObject({status:401});expect((await new AlertService().deliver(digest.id,queued.version)).data.status).toBe('accepted');expect(await mailCount(digest.id)).toBe(1);await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=ANY($1::uuid[])",[[f.user,other.user]]));
});
it('A05 necessary inquiry confirmations use the same provider receipt contract independently of optional opt-out',async()=>{
 const f=await fixture(),lead=crypto.randomUUID(),eventId=crypto.randomUUID();await transaction(workerActor,async c=>{await c.query("INSERT INTO leads(id,user_id,organization_id,resource_id,resource_type,name,email,phone,message) VALUES($1,$2,'10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000002000','listing','Alert fixture','transactional@example.test','123456789','Synthetic inquiry confirmation')",[lead,f.user]);await c.query("INSERT INTO outbox(id,aggregate_id,kind,payload,dispatched_at) VALUES($1,$2,'inquiry.submitted','{}',now())",[eventId,lead]);});
 const service=new AlertService();expect((await service.confirmInquiry(eventId)).data).toEqual({accepted:true});expect((await service.confirmInquiry(eventId)).data).toEqual({accepted:true});const notices=(await f.notifications.read(req('GET'))).data;expect(notices).toHaveLength(1);expect(notices[0]).toMatchObject({title:'Inquiry received',deliveryStatus:'accepted'});expect((await fetch('http://mail:8025/api/v1/search?query='+encodeURIComponent('message-id:'+eventId+'@haven.local')).then(r=>r.json())).messages_count).toBe(1);expect((await f.notifications.preferences(req('GET'))).data).toMatchObject({emailEnabled:false,inAppEnabled:false});await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=$1",[f.user]));
});
it('A05 weekly UTC digests group current matches, reject currency leakage and deduplicate concurrent planning',async()=>{
 const f=await fixture(),label='A05'+crypto.randomUUID().replaceAll('-','');await f.notifications.update(req('PATCH'),{version:0,emailEnabled:false,inAppEnabled:true});await f.searches.create(req(),{version:0,name:'Weekly in-app matches',filters:{city:'bj',currency:'CNY',transaction:'sale',text:label},cadence:'weekly'});const service=new AlertService(),first=await publish(label);const planned=await Promise.all([service.plan(first.event,first.version),service.plan(first.event,first.version)]);expect(planned.map(row=>row.data.replayed).sort()).toEqual([false,true]);const second=await publish(label);await service.plan(second.event,second.version);const foreign=await publish(label);await transaction(workerActor,c=>c.query("UPDATE listings SET currency='USD' WHERE id=$1",[foreign.id]));expect((await service.plan(foreign.event,foreign.version)).data.planned).toBe(0);const digest=(await f.notifications.deliveries(req('GET'))).data[0];expect((await f.notifications.deliveries(req('GET'))).data).toHaveLength(1);expect(new Date(digest.dueAt).getUTCDay()).toBe(1);expect(new Date(digest.dueAt).getUTCHours()).toBe(0);expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM alert_digest_items WHERE digest_id=$1',[digest.id]))).rows[0].n).toBe(2);await accelerate(digest.id);expect((await service.deliver(digest.id,digest.version)).data.status).toBe('in_app');expect(await mailCount(digest.id)).toBe(0);expect((await f.notifications.read(req('GET'))).data).toHaveLength(1);await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=$1",[f.user]));
});
