import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {InventoryController} from '../../apps/api/src/inventory/controller';
import {NotificationsController} from '../../apps/api/src/engagement/notifications';
import {responses} from '../../packages/contracts/src/responses';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},moderator:Actor={id:'00000000-0000-4000-8000-000000000008',orgId:null,roles:['moderator']},foreign:Actor={id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agency_manager']},identity=(actor:Actor)=>({actor:async()=>actor} as unknown as Identity),controller=(actor:Actor)=>new InventoryController(identity(actor)),request=()=>({method:'PATCH',url:'/api/v1/ops/owner-submissions/assignment',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),ids:string[]=[],users:string[]=[];
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query('DELETE FROM owner_submissions WHERE id=ANY($1::uuid[])',[ids]);await c.query('DELETE FROM memberships WHERE user_id=ANY($1::uuid[])',[users]);await c.query('DELETE FROM profiles WHERE id=ANY($1::uuid[])',[users]);});}finally{await pool.end();}});
async function fixture(){const row=(await controller(owner).createOwnerDraft(request(),{version:0,city:'bj'})).data;ids.push(row.id);await transaction(workerActor,c=>c.query("UPDATE owner_submissions SET status='submitted',data=data||'{\"title\":\"O04 synthetic assignment request\"}',version=version+1 WHERE id=$1",[row.id]));return {...row,version:2};}
it('O04 moderator assignment is idempotent/versioned, owner progress and notifications are safe, and private rejection notes remain hidden',async()=>{
 const row=await fixture(),reviewing=controller(moderator),agent=(await reviewing.ownerAgents(request())).data[0];expect(agent).toBeTruthy();const req=request(),result=(await reviewing.assignOwnerAgent(req,row.id,{version:2,agentId:agent.id})).data;expect(result.version).toBe(3);expect((await reviewing.assignOwnerAgent(req,row.id,{version:2,agentId:agent.id})).data.version).toBe(3);await expect(reviewing.assignOwnerAgent(request(),row.id,{version:2,agentId:agent.id})).rejects.toMatchObject({status:409});
 const progress=(await controller(owner).ownerProgress(request(),row.id)).data;expect(progress.map(r=>r.kind)).toEqual(['submitted','assigned']);expect(progress[1].agent_name).toBe(agent.name);responses.InventoryController_ownerProgress.parse(JSON.parse(JSON.stringify(progress)));
 const note='O04 private credential concern '+crypto.randomUUID();await reviewing.review(request(),row.id,{version:3,status:'rejected',reason:note});const saved=(await controller(owner).ownerDraft(request(),row.id)).data;expect(JSON.stringify(saved)).not.toContain(note);expect(saved.data).not.toHaveProperty('reviewReason');expect((await transaction(owner,c=>c.query('SELECT * FROM owner_submission_review_notes WHERE submission_id=$1',[row.id]))).rowCount).toBe(0);expect((await transaction(moderator,c=>c.query('SELECT note FROM owner_submission_review_notes WHERE submission_id=$1',[row.id]))).rows[0].note).toBe(note);
 const notices=(await new NotificationsController(identity(owner)).read(request())).data.filter(r=>r.link?.includes(row.id));expect(notices).toHaveLength(3);expect(JSON.stringify(notices)).not.toContain(note);expect(notices.some(r=>r.body.includes(agent.name))).toBe(true);expect((await controller(owner).ownerProgress(request(),row.id)).data.at(-1).kind).toBe('rejected');await expect(reviewing.assignOwnerAgent(request(),row.id,{version:4,agentId:agent.id})).rejects.toMatchObject({status:409});
});
it('O04 only the owning agency manager can reassign; foreign agency, owners and direct owner forgery fail',async()=>{
 const foreignId=crypto.randomUUID();users.push(foreignId);await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,display_name,email) VALUES($1,$2,'O04 foreign agency manager','o04-foreign@example.test')",[foreignId,foreignId]);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,'agency_manager','active')",[foreignId,foreign.orgId]);});const foreignManager={...foreign,id:foreignId};const row=await fixture(),reviewing=controller(moderator),agent=(await reviewing.ownerAgents(request())).data.find(a=>a.organization_id!==foreign.orgId);expect(agent).toBeTruthy();await reviewing.assignOwnerAgent(request(),row.id,{version:2,agentId:agent.id});await expect(controller(foreignManager).assignOwnerAgent(request(),row.id,{version:3,agentId:agent.id})).rejects.toMatchObject({status:404});expect((await controller(foreignManager).ownerAssignmentQueue(request())).data.some(r=>r.id===row.id)).toBe(false);
 const manager=(await transaction(workerActor,c=>c.query("SELECT user_id FROM memberships WHERE organization_id=$1 AND role='agency_manager' AND status='active' ORDER BY user_id LIMIT 1",[agent.organization_id]))).rows[0];expect(manager).toBeTruthy();const managerActor:Actor={id:manager.user_id,orgId:agent.organization_id,roles:['agency_manager']};const managing=controller(managerActor);expect((await transaction(managerActor,c=>c.query('SELECT data FROM owner_submissions WHERE id=$1',[row.id]))).rowCount).toBe(0);expect((await managing.ownerAssignmentQueue(request())).data.some(r=>r.id===row.id)).toBe(true);expect((await managing.assignOwnerAgent(request(),row.id,{version:3,agentId:agent.id})).data.version).toBe(4);
 await expect(controller(foreignManager).ownerProgress(request(),row.id)).rejects.toMatchObject({status:404});await expect(transaction(owner,c=>c.query('UPDATE owner_submissions SET assigned_agent_id=NULL,version=version+1 WHERE id=$1',[row.id]))).rejects.toMatchObject({code:'42501'});await expect(transaction(owner,c=>c.query("UPDATE owner_submissions SET status='approved',version=version+1 WHERE id=$1",[row.id]))).rejects.toMatchObject({code:'42501'});expect((await transaction(owner,c=>c.query("UPDATE owner_submission_progress SET kind='approved' WHERE submission_id=$1 RETURNING id",[row.id]))).rowCount).toBe(0);
});
