import {fixtureAccountState} from '../support/account-fixture';
import {assignListing} from '../../apps/api/src/inventory/assignments';
import '../support/env';
import {it,expect,afterAll,beforeAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {DraftInventoryController} from '../../apps/api/src/inventory/drafts';
import {PrivacyController} from '../../apps/api/src/identity/privacy';
import {DiscoveryController} from '../../apps/api/src/geography/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:crypto.randomUUID(),orgId:null,roles:['owner']},controller=new DraftInventoryController({actor:async()=>owner} as unknown as Identity),created:string[]=[],units:string[]=[];
beforeAll(()=>transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,display_name,email,email_verified) VALUES($1,$2,'O01 isolated owner',$3,true)",[owner.id,'o01-'+owner.id,'o01-'+owner.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,role) VALUES($1,'owner')",[owner.id]);}));
const req=()=>({method:'POST',url:'/api/v1/ops/listings',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
const base={title:'O01 owned private draft',description:'Synthetic owner facts with a recorded grant and private contact preference.',transaction:'sale',segment:'residential',currency:'CNY',price:'2400000.75',rentPeriod:null,furnishing:'Unfurnished',availableFrom:null,features:[]};
async function fixture(granted=true){return transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id",[])).rows[0];units.push(unit.id);const source=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status) SELECT $1,organization_id,$2,agent_id,$3,'O01 server recorded ownership fixture',description,'sale','residential','CNY','2400000.75','draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'o01-source-'+crypto.randomUUID()])).rows[0];created.push(source.id);let grant;if(granted)grant=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING *",[unit.id,owner.id,source.id])).rows[0];return {unit,source,grant};});}
afterAll(async()=>{try{await transaction(workerActor,async c=>{// Retain synthetic ownership and assignment audit records until this isolated test database is disposed.
await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[]) AND status<>'archived'",[created]);await fixtureAccountState(c,'suspended',"WHERE id=$1",[owner.id]);});}finally{await pool.end();}});
it('O01 owner creates an exact private draft using a current explicit grant; contact audience isolates reviewers then the assigned team',async()=>{const {unit,grant}=await fixture();expect((await controller.grants(req())).data.some(row=>row.id===grant.id)).toBe(true);expect((await controller.units(req())).data.find(row=>row.id===unit.id)).toMatchObject({ownerGrantVersion:1});const input={...base,unitId:unit.id,ownerGrantVersion:1,ownerContact:{contact:'o01-private@example.test',audience:'reviewers_only'}},request=req(),row=(await controller.create(request,input)).data;created.push(row.id);expect((await controller.create(request,input)).data.id).toBe(row.id);expect(row).toMatchObject({owner_id:owner.id,status:'draft',price:'2400000.75',ownerContact:input.ownerContact});expect((await controller.read(req(),row.id)).data.ownerContact).toEqual(input.ownerContact);const exported=(await new PrivacyController({actor:async()=>owner} as unknown as Identity).export(req())).data;expect(exported.records.ownerContacts.some((entry:any)=>entry.listing_id===row.id&&entry.contact===input.ownerContact.contact)).toBe(true);expect(exported.records.ownerGrants.some((entry:any)=>entry.id===grant.id)).toBe(true);expect((await new DiscoveryController().listings({city:'bj',text:base.title})).data.some(x=>x.id===row.id)).toBe(false);await expect(new DiscoveryController().listing(row.slug,'bj')).rejects.toMatchObject({status:404});const agent:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:'10000000-0000-4000-8000-000000000001',roles:['agent']};expect((await transaction(agent,c=>c.query('SELECT contact FROM listing_owner_contacts WHERE listing_id=$1',[row.id]))).rowCount).toBe(0);const {unitId:_unitId,ownerGrantVersion:_version,...edit}=input;void _unitId;void _version;expect((await controller.update(req(),row.id,{...edit,version:1,ownerContact:{...input.ownerContact,audience:'assigned_team'}})).data).toMatchObject({version:2,ownerContact:{audience:'assigned_team'}});const assignedAgent='10000000-0000-4000-8000-000000000060';if(row.agent_id!==assignedAgent)await transaction({...workerActor,orgId:agent.orgId},c=>assignListing(c,{...workerActor,orgId:agent.orgId},{listingId:row.id,agentId:assignedAgent,version:2,policy:'preserve_leads',reason:'Synthetic owner contact test establishes actual team assignment.'}));expect((await transaction(agent,c=>c.query('SELECT contact FROM listing_owner_contacts WHERE listing_id=$1',[row.id]))).rows[0].contact).toBe(input.ownerContact.contact);expect((await transaction({id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agency_manager']},c=>c.query('SELECT contact FROM listing_owner_contacts WHERE listing_id=$1',[row.id]))).rowCount).toBe(0);await expect(controller.update(req(),row.id,{...edit,version:1})).rejects.toMatchObject({status:409});});
it('O01 foreign/missing/stale/revoked/expired grants reject private drafts and direct grant forgery fails',async()=>{const {unit,grant,source}=await fixture(),input={...base,unitId:unit.id,ownerGrantVersion:1};await expect(controller.create(req(),{...input,ownerGrantVersion:undefined})).rejects.toMatchObject({status:400});await expect(controller.create(req(),{...input,ownerGrantVersion:2})).rejects.toMatchObject({status:409});const foreign=new DraftInventoryController({actor:async()=>({id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['owner']})} as unknown as Identity);await expect(foreign.create(req(),input)).rejects.toMatchObject({status:404});await expect(transaction(owner,c=>c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3)",[unit.id,owner.id,source.id]))).rejects.toMatchObject({code:'42501'});const draft=(await controller.create(req(),input)).data;created.push(draft.id);await transaction(workerActor,c=>c.query("UPDATE owner_unit_grants SET status='revoked',version=version+1 WHERE id=$1",[grant.id]));await expect(controller.create(req(),{...input,ownerGrantVersion:2})).rejects.toMatchObject({status:404});const {unitId:_unit,ownerGrantVersion:_version,...edit}=input;void _unit;void _version;await expect(controller.update(req(),draft.id,{...edit,version:1})).rejects.toMatchObject({status:404});await transaction(workerActor,c=>c.query("UPDATE owner_unit_grants SET status='active',expires_at=now()-interval '1 second',version=version+1 WHERE id=$1",[grant.id]));await expect(controller.create(req(),{...input,ownerGrantVersion:3})).rejects.toMatchObject({status:404});const missing=await fixture(false);await expect(controller.create(req(),{...input,unitId:missing.unit.id})).rejects.toMatchObject({status:404});expect((await controller.units(req())).data.some(row=>row.id===missing.unit.id)).toBe(false);});
