import {PaymentAllocationsController} from '../../apps/api/src/management/payment-allocations';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {ManagementController} from '../../apps/api/src/management/controller';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P08 verified synthetic tenant',true)",[tenant.id,'p08-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P08 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P08 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p08-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P08 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
const allocations=(a=manager)=>new PaymentAllocationsController(identity(a));
async function financial(amount='250.25',charged='200.20'){const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(l.id),amount})).data,posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(p))).data,ch=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2028-01-01','2028-01-05',$3,'CNY') RETURNING id,version",[l.id,manager.orgId,charged])).rows[0]);return {...f,l,p:posted,ch};}
async function allocationBody(f:Awaited<ReturnType<typeof financial>>,amount='50.05'){const ledger=(await allocations().ledger(req('GET'),f.l.id,{})).data;return {version:0,leaseId:f.l.id,leaseVersion:ledger.leaseVersion,unitVersion:ledger.unitVersion,grantVersion:ledger.grantVersion,paymentId:f.p.id,paymentVersion:f.p.version,chargeId:f.ch.id,chargeVersion:f.ch.version,amount,currency:ledger.currency,confirm:true};}
it('P08 partial allocation leaves exact outstanding and credit, matching receipt creates one root, and settlement retains overpayment',async()=>{const f=await financial(),x=await allocationBody(f),r=req('POST','/api/v1/ops/allocations'),a=(await allocations().create(r,x)).data;expect(a).toMatchObject({amount:'50.05',version:1,leaseId:f.l.id,reversedAt:null});expect((await allocations().create(r,x)).data.id).toBe(a.id);let ledger=(await allocations().ledger(req('GET'),f.l.id,{})).data;expect(ledger.totals).toEqual({charges:'200.20',recordedPayments:'250.25',allocated:'50.05',outstanding:'150.15',credit:'200.20'});expect(ledger.payments.find((p:any)=>p.id===f.p.id).available).toBe('200.20');expect(ledger.charges.find((c:any)=>c.id===f.ch.id).outstanding).toBe('150.15');await allocations().create(req('POST','/api/v1/ops/allocations'),await allocationBody(f,'150.15'));ledger=(await allocations().ledger(req('GET'),f.l.id,{})).data;expect(ledger.totals).toMatchObject({allocated:'200.20',outstanding:'0.00',credit:'50.05'});expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='payment.allocated'",[a.id]))).rows[0].n).toBe(1);},90000);
it.each([['100.10','200.20'],['200.20','100.10']])('P08 concurrent allocations respect payment %s and charge %s caps',async(payment,charge)=>{const f=await financial(payment,charge),x=await allocationBody(f,'70.00'),r=await Promise.allSettled([allocations().create(req('POST','/api/v1/ops/allocations'),x),allocations().create(req('POST','/api/v1/ops/allocations'),x)]);expect(r.filter(i=>i.status==='fulfilled')).toHaveLength(1);expect((r.find(i=>i.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);const ledger=(await allocations().ledger(req('GET'),f.l.id,{})).data;expect(ledger.totals.allocated).toBe('70.00');expect(payment==='100.10'?ledger.totals.credit:ledger.totals.outstanding).toBe('30.10');expect(payment==='100.10'?ledger.totals.outstanding:ledger.totals.credit).toBe('130.20');},90000);
it('P08 cross-lease, currency, stale versions, confirmation and over-allocation deny without changing balances',async()=>{const f=await financial(),other=await financial(),x=await allocationBody(f);for(const patch of [{chargeId:other.ch.id},{paymentId:other.p.id},{currency:'USD'},{paymentVersion:999},{chargeVersion:999},{leaseVersion:999},{grantVersion:999},{unitVersion:999},{amount:'999.00'},{confirm:false},{amount:50.05}])await expect(allocations().create(req('POST','/api/v1/ops/allocations'),{...x,...patch})).rejects.toBeDefined();expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals.allocated).toBe('0.00');await expect(allocations(tenant).ledger(req('GET'),f.l.id,{})).rejects.toMatchObject({status:403});},90000);
it('P08 PostgreSQL independently serializes direct allocations and prevents immutable amount edits',async()=>{const f=await financial('100.10','200.20'),x=await allocationBody(f,'70.00'),insert=()=>transaction(manager,c=>c.query('INSERT INTO allocations(payment_id,charge_id,organization_id,amount,allocated_by,payment_version,charge_version,lease_version,unit_version,grant_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[x.paymentId,x.chargeId,manager.orgId,x.amount,manager.id,x.paymentVersion,x.chargeVersion,x.leaseVersion,x.unitVersion,x.grantVersion])),r=await Promise.allSettled([insert(),insert()]);expect(r.filter(i=>i.status==='fulfilled')).toHaveLength(1);expect((r.find(i=>i.status==='rejected') as PromiseRejectedResult).reason.code).toBe('23514');const id=(r.find(i=>i.status==='fulfilled') as PromiseFulfilledResult<any>).value.rows[0].id;await expect(transaction(manager,c=>c.query("UPDATE allocations SET amount='1.00',version=version+1 WHERE id=$1",[id]))).rejects.toMatchObject({code:'23514'});expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals.credit).toBe('30.10');},90000);
it('P08 actual finance-only staff can allocate, manager-only and guessed foreign staff cannot, and revoked grants deny receipts',async()=>{const f=await financial(),actors:Actor[]=[{id:crypto.randomUUID(),orgId:manager.orgId,roles:['finance']},{id:crypto.randomUUID(),orgId:manager.orgId,roles:['property_manager']}];await transaction(workerActor,async c=>{for(const a of actors){await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P08 scoped synthetic professional',true)",[a.id,'p08-role-'+a.id,a.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,$3,'active')",[a.id,a.orgId,a.roles[0]]);}});try{const x=await allocationBody(f),r=req('POST','/api/v1/ops/allocations');await expect(allocations(actors[1]).create(req('POST','/api/v1/ops/allocations'),x)).rejects.toMatchObject({status:403});await expect(allocations({id:'00000000-0000-4000-8000-000000000011',orgId:manager.orgId,roles:['finance']}).create(req(),x)).rejects.toMatchObject({status:403});expect((await allocations(actors[0]).create(r,x)).data.amount).toBe('50.05');await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner revoked allocation management authority.'});await expect(allocations(actors[0]).create(r,x)).rejects.toMatchObject({status:404});}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='revoked',version=version+1 WHERE user_id=ANY($1::uuid[])",[actors.map(a=>a.id)]));}},90000);
it('P08 allocation and existing linked reversal share lock order and retained undo versions',async()=>{const f=await financial(),x=await allocationBody(f),a=(await allocations().create(req('POST','/api/v1/ops/allocations'),x)).data;await new ManagementController(identity(manager)).reverse(req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),f.p.id,{reason:'Recorded original payment reversal after allocation.'});const row=(await transaction(workerActor,c=>c.query('SELECT version,reversed_by,reversed_at FROM allocations WHERE id=$1',[a.id]))).rows[0];expect(row.version).toBe(2);expect(row.reversed_by).toBe(manager.id);expect(row.reversed_at).toBeTruthy();expect((await allocations().ledger(req('GET'),f.l.id,{})).data.totals).toMatchObject({recordedPayments:'0.00',allocated:'0.00',outstanding:'200.20',credit:'0.00'});await expect(allocations().create(req('POST','/api/v1/ops/allocations'),x)).rejects.toMatchObject({status:409});},90000);
