import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {ManagementController} from '../../apps/api/src/management/controller';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P07 verified synthetic tenant',true)",[tenant.id,'p07-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P07 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P07 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p07-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P07 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
it('P07 native draft stays out of balances and tenant reads; posting exact evidence retains history and audit once',async()=>{const f=await fixture(),l=await active(f),x=await body(l.id),r=req('POST','/api/v1/ops/payment-records'),p=(await payments().create(r,x)).data;expect(p).toMatchObject({status:'draft',amount:'100.10',native:true,version:1,postedAt:null});expect((await payments().create(r,x)).data.id).toBe(p.id);expect((await transaction(tenant,c=>c.query('SELECT id FROM payments WHERE id=$1',[p.id]))).rowCount).toBe(0);expect((await new ManagementController(identity(manager)).statement(req('GET'),l.id)).data.totals.recordedPayments).toBe('0.00');const posting=req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),posted=(await payments().post(posting,p.id,postBody(p))).data;expect(posted).toMatchObject({status:'posted',version:2,amount:'100.10',postedBy:manager.id});expect(posted.postedAt).toBeTruthy();expect((await payments().post(posting,p.id,postBody(p))).data.version).toBe(2);expect(posted.activity.map((a:any)=>a.action)).toEqual(['drafted','posted']);expect((await transaction(tenant,c=>c.query('SELECT id FROM payments WHERE id=$1',[p.id]))).rowCount).toBe(1);expect((await new ManagementController(identity(manager)).statement(req('GET'),l.id)).data.totals).toMatchObject({recordedPayments:'100.10',credit:'100.10'});const audit=await transaction(workerActor,async c=>({audit:(await c.query("SELECT actor_id FROM audit_events WHERE resource_id=$1 AND action='payment.recorded'",[p.id])).rows,event:(await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='payment.recorded'",[p.id])).rows[0].n}));expect(audit).toEqual({audit:[{actor_id:manager.id}],event:1});});
it('P07 edits only current drafts, retains original amount snapshots and denies posted amount changes at API and database',async()=>{const f=await fixture(),l=await active(f),x=await body(l.id),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),x)).data,{leaseId:_leaseId,...terms}=x,update={...terms,version:p.version,amount:'250.25',reference:'Corrected exact recorded receipt reference'};const edited=(await payments().update(req('PATCH','/api/v1/ops/payment-records/'+p.id),p.id,update)).data;expect(edited).toMatchObject({amount:'250.25',version:2,status:'draft'});await expect(payments().update(req('PATCH','/api/v1/ops/payment-records/'+p.id),p.id,update)).rejects.toMatchObject({status:409});const posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(edited))).data;expect(posted.version).toBe(3);await expect(payments().update(req('PATCH','/api/v1/ops/payment-records/'+p.id),p.id,{...update,version:3,amount:'500.00'})).rejects.toMatchObject({status:409});await expect(transaction(manager,c=>c.query("UPDATE payments SET amount='500.00' WHERE id=$1",[p.id]))).rejects.toMatchObject({code:'P0001'});expect((await transaction(workerActor,c=>c.query("SELECT snapshot->>'amount' AS amount FROM payment_evidence_history WHERE payment_id=$1 ORDER BY version",[p.id]))).rows.map(r=>r.amount)).toEqual(['100.10','250.25','250.25']);});
it('P07 negative/float/scientific money, foreign currency and stale authority deny creation with no payment roots',async()=>{const f=await fixture(),l=await active(f),x=await body(l.id);for(const patch of [{amount:'-1.00'},{amount:100.1},{amount:'1e2'},{amount:'0.00'},{currency:'USD'},{leaseVersion:999},{grantVersion:999},{unitVersion:999}])await expect(payments().create(req('POST','/api/v1/ops/payment-records'),{...x,...patch})).rejects.toBeDefined();expect((await transaction(workerActor,c=>c.query('SELECT id FROM payments WHERE lease_id=$1',[l.id]))).rowCount).toBe(0);await expect(payments(tenant).options(req('GET'),l.id)).rejects.toMatchObject({status:403});});
it('P07 posting requires current saved versions and confirmation, concurrent attempts create one post, and revoked grants deny receipts',async()=>{const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),await body(l.id))).data;for(const patch of [{version:999},{grantVersion:999},{confirm:false}])await expect(payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,{...postBody(p),...patch})).rejects.toBeDefined();const r=req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),other=req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),results=await Promise.allSettled([payments().post(r,p.id,postBody(p)),payments().post(other,p.id,postBody(p))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);{const winner=results[0].status==='fulfilled'?r:other;await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner revoked payment evidence management authority.'});await expect(payments().post(winner,p.id,postBody(p))).rejects.toMatchObject({status:404});}});
it('P07 drafts cannot be allocated or reversed before posting and actual manager-only authority cannot record payments',async()=>{const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),await body(l.id))).data,charge=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2028-01-01','2028-01-05','100.10','CNY') RETURNING id",[l.id,manager.orgId])).rows[0].id);const management=new ManagementController(identity(manager));await expect(management.allocate(req('POST','/api/v1/ops/allocations'),{paymentId:p.id,chargeId:charge,amount:'100.10'})).rejects.toMatchObject({status:409});await expect(management.reverse(req('POST','/api/v1/ops/payment-records/'+p.id+'/reverse'),p.id,{reason:'Draft evidence must never reverse recorded funds.'})).rejects.toMatchObject({status:409});const a:Actor={id:crypto.randomUUID(),orgId:manager.orgId,roles:['property_manager']};await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P07 synthetic non-finance manager',true)",[a.id,'p07-role-'+a.id,a.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,'property_manager','active')",[a.id,a.orgId]);});try{await expect(payments(a).create(req('POST','/api/v1/ops/payment-records'),await body(l.id))).rejects.toMatchObject({status:403});}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='revoked',version=version+1 WHERE user_id=$1",[a.id]));}});
