import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {createRequire} from 'node:module';
import type {FastifyRequest} from 'fastify';
import type {Identity} from '../../apps/api/src/platform/core';
import {AdministrationController} from '../../apps/api/src/administration/controller';
import {transaction,type Actor} from '../../packages/database/src/index';
const admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin']},consumer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};
const api=(a=admin)=>new AdministrationController({actor:async()=>a} as unknown as Identity),request=(method='POST',url='/api/v1/ops/users')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});afterAll(()=>fixtures.end());
async function target(){const id=crypto.randomUUID();await fixtures.query("INSERT INTO profiles(id,subject,display_name,email,email_verified) VALUES($1,$2,'S04 synthetic target',$3,true)",[id,'s04-'+id,'s04-'+id+'@example.test']);await fixtures.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,'10000000-0000-4000-8000-000000000001','agent')",[id]);return id;}
it('S04 native suspension is current-version audited, revokes agent sessions, preserves immutable original history and permits explicit reactivation',async()=>{
 const id=await target(),session='s04-'+crypto.randomUUID();await fixtures.query("INSERT INTO sessions(id,user_id,encrypted_tokens,expires_at) VALUES($1,$2,'synthetic-not-a-provider-token',now()+interval '1 hour')",[session,id]);const x={version:1,action:'suspend',reason:'S04 reviewed synthetic abusive agent report.'},req=request('POST','/api/v1/ops/users/'+id+'/suspend');let r=(await api().suspend(req,id,x)).data;expect(r).toMatchObject({state:'suspended',version:2});expect((await fixtures.query('SELECT id FROM sessions WHERE user_id=$1',[id])).rowCount).toBe(0);expect(r.activity[0]).toMatchObject({kind:'account.suspended',actorId:admin.id,reason:x.reason,before:{state:'active',version:1},after:{state:'suspended',version:2}});expect((await api().suspend(req,id,x)).data.version).toBe(2);await expect(api().suspend(request(),id,{...x,action:'reactivate'})).rejects.toMatchObject({status:409});await expect(api().staff(request(),id,{version:0,profileVersion:2,role:'support',status:'active',reason:'Suspended targets cannot gain new staff permissions.'})).rejects.toMatchObject({status:409});r=(await api().suspend(request(),id,{...x,version:2,action:'reactivate',reason:'S04 reviewed synthetic reinstatement decision.'})).data;expect(r).toMatchObject({state:'active',version:3});expect(r.activity.map(h=>h.kind)).toEqual(['account.suspended','account.reactivated']);expect((await transaction(admin,c=>c.query("UPDATE platform_administration_history SET reason='Tampered immutable history' WHERE target_id=$1",[id]))).rowCount).toBe(0);expect((await transaction(admin,c=>c.query('DELETE FROM platform_administration_history WHERE target_id=$1',[id]))).rowCount).toBe(0);await expect(transaction(admin,c=>c.query("UPDATE audit_events SET action='tampered' WHERE resource_id=$1",[id]))).rejects.toThrow();
});
it('S04 staff grants use original profile and permission versions, revoke sessions, retain history and cannot self-escalate or grant finance',async()=>{
 const id=await target(),x={version:0,profileVersion:1,role:'editor',status:'active',reason:'S04 approved synthetic editorial staff assignment.'},req=request('POST','/api/v1/ops/users/'+id+'/staff');let r=(await api().staff(req,id,x)).data;expect(r.staff).toHaveLength(1);expect(r.staff[0]).toMatchObject({role:'editor',status:'active',version:1});expect((await api().staff(req,id,x)).data.staff[0].version).toBe(1);expect(r.activity[0]).toMatchObject({kind:'staff.permission_changed',actorId:admin.id,before:null,after:{role:'editor',status:'active',version:1}});const granted:Actor={id,orgId:null,roles:['editor']};expect((await api(granted).homeContent(request('GET'),{city:'bj'})).data.sections).toBeDefined();await expect(api(granted).staff(request(),id,{...x,role:'admin'})).rejects.toMatchObject({status:403});await expect(api().staff(request(),admin.id,{...x,profileVersion:1,role:'admin'})).rejects.toMatchObject({status:403});await expect(api().staff(request(),id,{...x,role:'finance'})).rejects.toThrow();await expect(api().staff(request(),id,{...x,profileVersion:2,role:'support'})).rejects.toMatchObject({status:409});
 r=(await api().staff(request(),id,{...x,version:1,status:'revoked',reason:'S04 withdrawn synthetic editorial assignment.'})).data;expect(r.staff[0]).toMatchObject({status:'revoked',version:2});await expect(api(granted).homeContent(request('GET'),{city:'bj'})).rejects.toMatchObject({status:403});await expect(api().staff(request(),id,{...x,version:1,status:'active'})).rejects.toMatchObject({status:409});expect(r.activity).toHaveLength(2);r=(await api().staff(request(),id,{...x,version:2,status:'active'})).data;expect(r.staff[0].version).toBe(3);expect((await transaction(granted,c=>c.query('SELECT * FROM platform_administration_history WHERE target_id=$1',[id]))).rowCount).toBe(0);
});
it('S04 non-admin/forged claims deny account reads/actions and SQL platform escalation; competing current versions cannot both commit',async()=>{
 const id=await target(),x={version:1,action:'suspend',reason:'S04 current-version synthetic abuse review.'};for(const a of [consumer,{...consumer,roles:['admin','editor']}]){await expect(api(a).users(request('GET'),{})).rejects.toMatchObject({status:403});await expect(api(a).user(request('GET'),id)).rejects.toMatchObject({status:403});await expect(api(a).suspend(request(),id,x)).rejects.toMatchObject({status:403});await expect(api(a).staff(request(),id,{version:0,profileVersion:1,role:'admin',status:'active',reason:'Forged platform administrator must be refused.'})).rejects.toMatchObject({status:403});await expect(transaction(a,c=>c.query("INSERT INTO memberships(user_id,organization_id,role,change_reason) VALUES($1,NULL,'admin','Forged SQL administrator must be refused')",[consumer.id]))).rejects.toThrow();await expect(transaction(a,c=>c.query("UPDATE profiles SET state='suspended',version=version+1 WHERE id=$1",[id]))).rejects.toThrow();}
 const result=await Promise.allSettled([api().suspend(request(),id,x),api().suspend(request(),id,{...x,reason:'Second competing current-version synthetic review.'})]);expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await api().user(request('GET'),id)).data.activity).toHaveLength(1);await expect(api().suspend(request(),admin.id,x)).rejects.toMatchObject({status:403});const page=(await api().users(request('GET'),{text:id,state:'suspended'})).data;expect(page.items.map(x=>x.id)).toEqual([id]);expect(page.limit).toBe(20);expect((await api().users(request('GET'),{text:'s04-no-such-account'})).data.items).toEqual([]);
});
