import {fixtureAccountState} from '../support/account-fixture';
import '../support/env';
import {readFile} from 'node:fs/promises';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ProviderCatalogController,publicProviders,publicProvider} from '../../apps/api/src/services/provider-catalog';
import {MediaController} from '../../apps/api/src/inventory/media';
import {providerFilters,type ProviderInput} from '../../packages/contracts/src/providers';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000004',foreignOrg=crypto.randomUUID(),vendors:Actor[]=[],ids:string[]=[],reviewer:Actor={id:'00000000-0000-4000-8000-000000000008',orgId:'10000000-0000-4000-8000-000000000001',roles:['moderator']};let district:string;
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),controller=(a:Actor)=>new ProviderCatalogController(identity(a)),req=(method='POST',path='/api/v1/me/providers',key=crypto.randomUUID())=>({method,url:path,headers:{'idempotency-key':key}} as unknown as FastifyRequest);
beforeAll(async()=>{await transaction(workerActor,async c=>{await c.query("INSERT INTO organizations(id,name,type) VALUES($1,'V02 synthetic foreign vendor','vendor')",[foreignOrg]);for(const agency of [org,org,foreignOrg]){const id=crypto.randomUUID();await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'V02 synthetic vendor',true)",[id,'v02-'+id,'v02-'+id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,'vendor')",[id,agency]);vendors.push({id,orgId:agency,roles:['vendor']});}district=(await c.query("SELECT d.id FROM districts d JOIN cities ci ON ci.id=d.city_id WHERE ci.slug='bj' AND d.name='Chaoyang'")).rows[0].id;});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE providers SET status='draft',version=version+1 WHERE id=ANY($1::uuid[])",[ids]);await c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=ANY($1::uuid[])",[vendors.map(v=>v.id)]);await fixtureAccountState(c,'suspended',"WHERE id=ANY($1::uuid[])",[vendors.map(v=>v.id)]);});}finally{await pool.end();}});
const draft=(portfolio:ProviderInput['portfolio']=[]):ProviderInput=>({version:0,name:'V02 native vendor '+crypto.randomUUID().slice(0,8),description:'A synthetic service provider acceptance profile, not a verified actual business.',city:'bj',categories:['Renovation'],districtIds:[district],portfolio});
async function photo(a=vendors[0],complete=true){const bytes=await readFile('apps/web/public/homes/home-1.jpg'),media=new MediaController(identity(a)),intent=(await media.intent(req(),{mime:'image/jpeg',size:bytes.length,rights:'Supplied synthetic JPEG acceptance fixture; permission for local tests.',visibility:'public',purpose:'photo'})).data;if(complete){const url=new URL(intent.uploadUrl,'http://api');await media.content({method:'PUT',url:url.pathname,query:{signature:url.searchParams.get('signature')},headers:{'content-type':'image/jpeg'}} as unknown as FastifyRequest,intent.id,bytes);}const asset=(await media.status(req('GET'),intent.id)).data;return {assetId:intent.id,version:asset.version,alt:'Synthetic portfolio room',caption:'Local scanner acceptance fixture',rights:'Supplied synthetic photo permitted for acceptance tests.'};}
async function create(x=draft()){const r=(await controller(vendors[0]).create(req(),x)).data;ids.push(r.id);return r;}

it('V02 filters published providers by exact category/canonical area/text/city with bounded stable pages; other areas and unknown matches remain empty',async()=>{
 const p=await create(draft([await photo()]));await controller(vendors[0]).submit(req('POST','/api/v1/me/providers/'+p.id+'/submit'),p.id,{version:1});await controller(reviewer).review(req('PATCH','/api/v1/ops/provider-reviews/'+p.id),p.id,{version:2,decision:'approved',verified:true,reason:'Independent synthetic directory review'});const result=await publicProviders(providerFilters.parse({city:'bj',districtId:district,category:'Renovation',text:p.name,limit:1}));expect(result.data.map(r=>r.id)).toEqual([p.id]);expect(result.meta).toMatchObject({total:1,page:1,limit:1});expect((await publicProviders(providerFilters.parse({city:'bj',category:'Painting',text:p.name}))).data).toEqual([]);expect((await publicProviders(providerFilters.parse({city:'bj',districtId:district,text:p.name,page:2,limit:1}))).data).toEqual([]);expect((await publicProvider(p.slug,'bj')).data.districtIds).toContain(district);await expect(publicProviders(providerFilters.parse({city:'sh',districtId:district}))).rejects.toMatchObject({status:400});expect((await publicProviders(providerFilters.parse({city:'bj',text:'%'+p.name}))).data).toEqual([]);
});
