import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {randomUUID} from 'node:crypto';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {DiscoveryController} from '../../apps/api/src/geography/controller';
import {publicRead,anonymousPublicRead} from '../../apps/api/src/geography/public-read-cache';
const admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin']};
afterAll(()=>pool.end());
async function fixture(){return transaction(admin,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'91.20',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0].id;const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'Q07 cache fixture','Synthetic cache visibility fixture','sale','residential','CNY','100.10','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit,'q07-cache-'+randomUUID()])).rows[0].id;return {unit,listing};});}
function read(id:string,scope='detail'){return transaction(null,c=>publicRead(c,{test:scope,id},async()=>{const rows=(await c.query('SELECT id,price,area FROM public_listings WHERE id=$1',[id])).rows;return rows;}));}
it('Q07 cached public records refresh after committed native changes and withdrawal, while private scope is refused',async()=>{const f=await fixture(),before=await read(f.listing);expect(before[0].price).toBe('100.10');expect(await read(f.listing)).toEqual(before);before[0].price='999.99';expect((await read(f.listing))[0].price).toBe('100.10');await transaction(admin,c=>c.query("UPDATE listings SET price='200.20',version=version+1 WHERE id=$1",[f.listing]));expect((await read(f.listing))[0].price).toBe('200.20');await transaction(admin,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[f.listing]));expect(await read(f.listing)).toEqual([]);await expect(transaction(admin,c=>publicRead(c,{private:randomUUID()},async()=>[{private:true}]))).rejects.toThrow('PUBLIC_CACHE_REQUIRES_ANONYMOUS_SCOPE');});
it('Q07 reusable current public snapshots coalesce reads without bypassing expiry when no mutation occurs',async()=>{const f=await fixture();await transaction(admin,c=>c.query("UPDATE listings SET expires_at=now()+interval '1 second',version=version+1 WHERE id=$1",[f.listing]));let loads=0;const cached=()=>transaction(null,c=>publicRead(c,{id:f.listing,test:'expiry'},async()=>{loads++;return(await c.query('SELECT id FROM public_listings WHERE id=$1',[f.listing])).rows;}));expect(await cached()).toHaveLength(1);expect(await cached()).toHaveLength(1);expect(loads).toBe(1);const revision=(await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision;await new Promise(r=>setTimeout(r,1100));expect(await cached()).toEqual([]);expect(loads).toBe(2);expect((await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision).toBe(revision);});
it('Q07 out-of-order source commits each invalidate the revision count and rolled-back writes never appear',async()=>{const a=await fixture(),b=await fixture(),first=await pool.connect(),second=await pool.connect();try{for(const c of [first,second]){await c.query('BEGIN');await c.query("SELECT set_config('app.actor',$1,true),set_config('app.admin','true',true)",[admin.id]);}const before=BigInt((await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision);await first.query("UPDATE units SET area='92.30',version=version+1 WHERE id=$1",[a.unit]);await second.query("UPDATE units SET area='93.40',version=version+1 WHERE id=$1",[b.unit]);await second.query('COMMIT');expect(BigInt((await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision)).toBe(before+1n);expect((await read(a.listing,'ordered'))[0].area).toBe('91.20');await first.query('COMMIT');expect(BigInt((await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision)).toBe(before+2n);expect((await read(a.listing,'ordered'))[0].area).toBe('92.30');await first.query('BEGIN');await first.query("SELECT set_config('app.actor',$1,true),set_config('app.admin','true',true)",[admin.id]);await first.query("UPDATE units SET area='94.50',version=version+1 WHERE id=$1",[a.unit]);await first.query('ROLLBACK');expect((await read(a.listing,'ordered'))[0].area).toBe('92.30');}finally{await first.query('ROLLBACK');await second.query('ROLLBACK');first.release();second.release();}});
it('Q07 the public revision journal refuses application insertion, deletion and truncation',async()=>{await expect(transaction(admin,c=>c.query("INSERT INTO public_read_revisions(source) VALUES('forged')"))).rejects.toMatchObject({code:'42501'});const before=(await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision;try{const result=await transaction(admin,c=>c.query('DELETE FROM public_read_revisions'));expect(result.rowCount).toBe(0);}catch(error){expect(error).toMatchObject({code:'42501'});}expect((await transaction(null,c=>c.query('SELECT revision FROM public_read_cache_stamp()'))).rows[0].revision).toBe(before);await expect(transaction(admin,c=>c.query('TRUNCATE public_read_revisions'))).rejects.toMatchObject({code:'42501'});});

it('Q07 pending reads cannot cross a publication deadline, and upcoming curation starts refresh without a write',async()=>{const f=await fixture();await transaction(admin,async c=>{await c.query("INSERT INTO curated_boosts(resource_type,resource_id,city,points,sponsored,public_label,starts_at,ends_at,created_by,updated_by) VALUES('listing',$1,'bj',5,true,'Q07 sponsored fixture',now()+interval '0.5 seconds',now()+interval '5 seconds',$2,$2)",[f.listing,admin.id]);});const readBoost=(slow=false)=>transaction(null,c=>publicRead(c,{test:'boost-deadline',id:f.listing},async()=>{const data=(await c.query("SELECT public_curated_boost('listing',$1) AS boost",[f.listing])).rows[0];if(slow)await new Promise(r=>setTimeout(r,1000));return data;}));const old=readBoost(true);await new Promise(r=>setTimeout(r,650));const current=await readBoost();expect(current.boost?.label).toBe('Q07 sponsored fixture');expect((await old).boost).toBeNull();expect((await readBoost()).boost?.label).toBe('Q07 sponsored fixture');});

it('Q07 committed residential facts invalidate the public detail cache',async()=>{const f=await fixture();const facts=()=>transaction(null,c=>publicRead(c,{test:'residential-facts',id:f.listing},async()=>(await c.query('SELECT finishing FROM public_listings WHERE id=$1',[f.listing])).rows));expect((await facts())[0].finishing).toBeNull();await transaction(admin,c=>c.query("INSERT INTO residential_details(listing_id,finishing) VALUES($1,'Q07 synthetic finishing')",[f.listing]));expect((await facts())[0].finishing).toBe('Q07 synthetic finishing');});

it('Q07 forged privileged anonymous transaction flags cannot supply a cache value',async()=>{await expect(transaction(null,async c=>{await c.query("SELECT set_config('app.admin','true',true)");return publicRead(c,{test:'forged-scope',id:randomUUID()},async()=>[{private:true}]);})).rejects.toThrow('PUBLIC_CACHE_REQUIRES_ANONYMOUS_SCOPE');});

it('Q07 indexed UUID and slug detail lookups retain the same public resource and selected-city refusal',async()=>{const f=await fixture(),record=(await transaction(null,c=>c.query('SELECT slug FROM public_listings WHERE id=$1',[f.listing]))).rows[0],controller=new DiscoveryController();expect((await controller.listing(f.listing,'bj')).data.id).toBe(f.listing);expect((await controller.listing(record.slug,'bj')).data.id).toBe(f.listing);await expect(controller.listing(f.listing,'sh')).rejects.toMatchObject({status:404});await expect(controller.listingAgents(f.listing,'sh')).rejects.toMatchObject({status:404});});

it('Q07 concurrent anonymous readers retain independent values and a caller submitted after committed withdrawal cannot inherit the prior SQL snapshot',async()=>{
 const f=await fixture(),criteria={test:'anonymous-batch',id:f.listing};let loads=0;
 const read=()=>anonymousPublicRead(()=>criteria,async c=>{loads++;return(await c.query('SELECT id,price FROM public_listings WHERE id=$1',[f.listing])).rows;});
 const readers=await Promise.all(Array.from({length:100},read));
 expect(readers.every(rows=>rows.length===1&&rows[0].price==='100.10')).toBe(true);expect(loads).toBe(1);
 readers[0][0].price='999.99';expect(readers[1][0].price).toBe('100.10');
 await transaction(admin,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[f.listing]));
 expect(await Promise.all(Array.from({length:100},read))).toEqual(Array.from({length:100},()=>[]));expect(loads).toBe(2);
});

it('Q07 copied public snapshots preserve independent nested dates, exact money and own prototype-named fields',async()=>{
 const at=new Date('2026-10-09T00:00:00.000Z'),source={nested:[{at,money:'9999999999999999.99'}],fields:JSON.parse('{"__proto__":{"polluted":true}}')};
 const criteria={test:'snapshot-types',id:randomUUID()};let loads=0;
 const read=()=>anonymousPublicRead(()=>criteria,async()=>{loads++;return source;});
 const first=await read();first.nested[0].at.setUTCFullYear(2000);first.fields.__proto__.polluted=false;
 source.nested[0].money='1.00';source.nested[0].at.setUTCFullYear(2001);
 const second=await read();expect(loads).toBe(1);expect(second.nested[0].at).toBeInstanceOf(Date);expect(second.nested[0].at.toISOString()).toBe('2026-10-09T00:00:00.000Z');expect(second.nested[0].money).toBe('9999999999999999.99');expect(Object.hasOwn(second.fields,'__proto__')).toBe(true);expect(second.fields.__proto__.polluted).toBe(true);expect(Object.getPrototypeOf(second.fields)).toBe(Object.prototype);
});

it('Q07 cached public search and detail normalize native dates before complete response-schema validation',async()=>{
 const {operations}=await import('../../packages/contracts/src/generated/operations'),f=await fixture(),controller=new DiscoveryController();
 const detail=await controller.listing(f.listing,'bj');expect(detail.data.publishedAt).toBeTypeOf('string');expect(operations.DiscoveryController_listing.response.safeParse(detail.data).success).toBe(true);
 const search=await controller.listings({city:'bj',transaction:'sale',sort:'newest'});expect(operations.DiscoveryController_listings.response.safeParse(search.data).success).toBe(true);expect(search.data.find(row=>row.id===f.listing)?.publishedAt).toBeTypeOf('string');
});
