import {fixtureAccountState} from '../support/account-fixture';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import {ConversationsController} from '../../apps/api/src/engagement/conversations';
import {replayConversation} from '../../apps/api/src/engagement/conversation-socket';
import {LeadAssignmentsController} from '../../apps/api/src/engagement/lead-assignments';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',foreign='10000000-0000-4000-8000-000000000005',buyer:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']},manager:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:org,roles:['admin','agency_manager']},people:(Actor&{agent:string})[]=[],leads:string[]=[],threads:string[]=[];
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),engagement=(a:Actor)=>new EngagementController(identity(a)),conversations=(a:Actor)=>new ConversationsController(identity(a)),req=(url='/api/v1/inquiries')=>({method:'POST',url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
beforeAll(async()=>{await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'M04 customer',true)",[buyer.id,'m04-'+buyer.id,'m04-'+buyer.id+'@example.test']);for(const agency of [org,org,foreign]){const id=crypto.randomUUID(),agent=crypto.randomUUID();await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'M04 professional',true)",[id,'m04-'+id,'m04-'+id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,'agent')",[id,agency]);await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'M04 synthetic agent',$4,'Synthetic membership acceptance fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,id,agency,'m04-'+agent]);people.push({id,agent,orgId:agency,roles:['agent']});}});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE leads SET status='lost',version=version+1 WHERE id=ANY($1::uuid[])",[leads]);await c.query("UPDATE conversations SET state='closed',version=version+1 WHERE id=ANY($1::uuid[])",[threads]);await c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=ANY($1::uuid[])",[people.map(p=>p.id)]);await fixtureAccountState(c,'suspended',"WHERE id=ANY($1::uuid[])",[[buyer.id,...people.map(p=>p.id)]]);});}finally{await pool.end();}});
async function inquiry(){const r=(await engagement(buyer).inquiry(req(),{resourceId:people[0].agent,resourceType:'agent',resourceVersion:1,city:'bj',name:'M04 customer',email:'conversation-'+buyer.id+'@example.test',phone:'123456789',message:'A real linked inquiry for this agent',consent:true})).data;leads.push(r.id);threads.push(r.conversationId!);return r;}

async function send(id:string,a:Actor,body:string){return (await engagement(a).message(req(),id,{version:0,conversationVersion:(await conversations(a).detail(req(),id)).data.version,clientId:crypto.randomUUID(),body})).data;}


it('M04 replay after a saved sequence returns ordered missing pages and no duplicate previously received records',async()=>{
 const id=(await inquiry()).conversationId!;for(let i=0;i<3;i++)await send(id,people[0],'Before disconnect '+i);const checkpoint='3';for(let i=0;i<3;i++)await send(id,people[0],'While disconnected '+i);const recovered=(await replayConversation(buyer,id,checkpoint)).data;expect(recovered.map(m=>m.sequence)).toEqual(['4','5','6']);expect((await replayConversation(buyer,id,'6')).data).toEqual([]);await expect(replayConversation(buyer,id,'7')).rejects.toMatchObject({status:400});
 await transaction(workerActor,async c=>{for(let seq=7;seq<=212;seq++)await c.query('INSERT INTO messages(conversation_id,sender_id,client_id,sequence,body) VALUES($1,$2,$3,$4,$5)',[id,people[0].id,crypto.randomUUID(),String(seq),'Persisted paging fixture '+seq]);});let cursor='6';const sequences:string[]=[];for(;;){const page=(await replayConversation(buyer,id,cursor)).data;if(!page.length)break;sequences.push(...page.map(m=>m.sequence));cursor=page.at(-1)!.sequence;}expect(sequences).toEqual(Array.from({length:206},(_,i)=>String(i+7)));
});
it('M04 current reassignment and revoked membership deny subsequent replay and send actions',async()=>{
 const lead=await inquiry(),id=lead.conversationId!;await send(id,buyer,'Persisted before reassignment');expect((await replayConversation(people[0],id,'0')).data).toHaveLength(1);await new LeadAssignmentsController(identity(manager)).assign(req('/api/v1/ops/leads/'+lead.id+'/assignment'),lead.id,{version:1,agentId:people[1].agent,reason:'Change the actual recipient'});await expect(replayConversation(people[0],id,'0')).rejects.toMatchObject({status:404});expect((await replayConversation(people[1],id,'0')).data).toHaveLength(1);await transaction(workerActor,c=>c.query("UPDATE memberships SET status='inactive',version=version+1 WHERE user_id=$1 AND organization_id=$2",[people[1].id,org]));try{await expect(replayConversation(people[1],id,'0')).rejects.toMatchObject({status:404});await expect(engagement(people[1]).message(req(),id,{version:0,conversationVersion:3,clientId:crypto.randomUUID(),body:'Revoked send'})).rejects.toMatchObject({status:404});}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='active',version=version+1 WHERE user_id=$1 AND organization_id=$2",[people[1].id,org]));}
});
it('M04 durable actor send admission denies new messages at the limit while committed client-ID retries return the original receipt',async()=>{
 const id=(await inquiry()).conversationId!,x={version:0,conversationVersion:(await conversations(buyer).detail(req(),id)).data.version,clientId:crypto.randomUUID(),body:'A prior receipt'};const saved=await engagement(buyer).message(req(),id,x);await transaction(workerActor,c=>c.query("INSERT INTO message_send_windows(user_id,window_start,attempts) VALUES($1,date_trunc('minute',clock_timestamp()),60) ON CONFLICT(user_id,window_start) DO UPDATE SET attempts=60",[buyer.id]));try{expect((await engagement(buyer).message(req(),id,x)).data.id).toBe(saved.data.id);await expect(engagement(buyer).message(req(),id,{...x,clientId:crypto.randomUUID(),body:'Over-limit new message'})).rejects.toMatchObject({status:429});expect((await engagement(buyer).messages(req(),id)).data).toHaveLength(1);await expect(transaction(buyer,c=>c.query('DELETE FROM message_send_windows WHERE user_id=$1',[buyer.id]))).resolves.toMatchObject({rowCount:0});}finally{await transaction(workerActor,c=>c.query('DELETE FROM message_send_windows WHERE user_id=$1',[buyer.id]));}
});
