import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {saveMarketPatch,marketAdmin,marketRequest} from '../support/market-admin';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {RecurringChargesController} from '../../apps/api/src/management/recurring-charges';
import {LeaseLifecycleController} from '../../apps/api/src/management/lease-lifecycle';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P06 verified synthetic tenant',true)",[tenant.id,'p06-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P06 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P06 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p06-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P06 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31'){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents:[]})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const charges=(a=manager)=>new RecurringChargesController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>,start='2028-02-15',end='2028-03-17'){const l=await draft(f,start,end);return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function preview(id:string,period='2028-02',a=manager){for(let page=1;page<50;page++){const p=(await charges(a).preview(req('GET'),{period,page})).data,row=p.items.find((i:any)=>i.leaseId===id);if(row)return row;if(page*20>=p.total)break;}return null;}
const item=(p:any)=>({leaseId:p.leaseId,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,configVersion:p.configVersion});
it('P06 leap-month proration uses exact cents, term-aware due date and one charge across retry and repeated month',async()=>{const f=await fixture(),l=await active(f),p=await preview(l.id);expect(p).toMatchObject({rent:'1234.56',amount:'638.57',occupiedDays:15,monthDays:29,dueDate:'2028-02-15',proration:'calendar_days',dueDaySource:'lease',exists:false});const r=req('POST','/api/v1/ops/charges/generate'),body={period:'2028-02',items:[item(p)],confirm:true},first=(await charges().generate(r,body)).data;expect(first).toMatchObject({generated:1,existing:0});expect((await charges().generate(r,body)).data).toEqual(first);expect((await charges().generate(req('POST','/api/v1/ops/charges/generate'),body)).data).toMatchObject({generated:0,existing:1,chargeIds:first.chargeIds});const facts=await transaction(workerActor,async c=>({charge:(await c.query('SELECT amount::text,due_date::text,currency,generation_snapshot,generated_by FROM charges WHERE id=$1',[first.chargeIds[0]])).rows[0],events:(await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='charge.posted'",[first.chargeIds[0]])).rows[0].n}));expect(facts.charge).toMatchObject({amount:'638.57',due_date:'2028-02-15',currency:'CNY',generated_by:manager.id,generation_snapshot:{leaseVersion:l.version,configVersion:p.configVersion,occupiedDays:15,monthDays:29,rounding:'half_up_to_cent'}});expect(facts.events).toBe(1);expect((await preview(l.id)).exists).toBe(true);});
it('P06 concurrent generators cannot duplicate a charge; ended and out-of-term leases are excluded',async()=>{const f=await fixture(),l=await active(f),p=await preview(l.id),body={period:'2028-02',items:[item(p)],confirm:true},r=await Promise.all([charges().generate(req('POST','/api/v1/ops/charges/generate'),body),charges().generate(req('POST','/api/v1/ops/charges/generate'),body)]);expect(r.map(x=>x.data.generated).sort()).toEqual([0,1]);expect(r[0].data.chargeIds).toEqual(r[1].data.chargeIds);expect(await preview(l.id,'2028-01')).toBeNull();expect(await preview(l.id,'2028-04')).toBeNull();await new LeaseLifecycleController(identity(manager)).end(req('POST','/api/v1/ops/leases/'+l.id+'/end'),l.id,{version:l.version,kind:'completed',reason:'Recorded completion before subsequent charge generation.',confirm:true});expect(await preview(l.id)).toBeNull();await expect(charges().generate(req('POST','/api/v1/ops/charges/generate'),body)).rejects.toMatchObject({status:409});});
it('P06 stale versions, wrong scope and missing confirmation deny generation; grant revocation denies cached receipt',async()=>{const f=await fixture(),l=await active(f),p=await preview(l.id),body={period:'2028-02',items:[item(p)],confirm:true};for(const patch of [{leaseVersion:999},{configVersion:999},{grantVersion:999},{unitVersion:999}])await expect(charges().generate(req('POST','/api/v1/ops/charges/generate'),{...body,items:[{...item(p),...patch}]})).rejects.toMatchObject({status:409});await expect(charges().generate(req(),{...body,confirm:false})).rejects.toBeDefined();await expect(charges({id:'00000000-0000-4000-8000-000000000011',orgId:manager.orgId,roles:['finance']}).generate(req(),body)).rejects.toMatchObject({status:403});const r=req('POST','/api/v1/ops/charges/generate');await charges().generate(r,body);await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Owner revoked recurring charge management authority.'});await expect(charges().generate(r,body)).rejects.toMatchObject({status:404});});
it('P06 market full-month policy and explicit historical due-day fallback are snapshotted without inventing original terms',async()=>{const saved=await transaction(workerActor,async c=>(await c.query("SELECT data FROM market_config WHERE id='bj'")).rows[0].data);try{await saveMarketPatch({chargeProration:'full_month',legacyChargeDueDay:8});const f=await fixture(),id=await transaction(workerActor,async c=>(await c.query("INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency,status) VALUES($1,$2,$3,'2028-02-15','2028-03-17','1234.56','CNY','active') RETURNING id",[manager.orgId,f.unit.id,f.tenantId])).rows[0].id);leases.push(id);const p=await preview(id);expect(p).toMatchObject({amount:'1234.56',proration:'full_month',dueDaySource:'configured_historical_default',dueDate:'2028-02-15'});const result=(await charges().generate(req('POST','/api/v1/ops/charges/generate'),{period:'2028-02',items:[item(p)],confirm:true})).data;expect(result.generated).toBe(1);expect((await transaction(workerActor,c=>c.query('SELECT due_day FROM leases WHERE id=$1',[id]))).rows[0].due_day).toBeNull();}finally{await saveMarketPatch(saved);}});
it('P06 actual finance-only membership can generate within its granted property; a manager without finance cannot',async()=>{const f=await fixture(),l=await active(f),financeOnly:Actor={id:crypto.randomUUID(),orgId:manager.orgId,roles:['finance']},managerOnly:Actor={id:crypto.randomUUID(),orgId:manager.orgId,roles:['property_manager']};await transaction(workerActor,async c=>{for(const a of [financeOnly,managerOnly]){await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P06 synthetic scoped professional',true)",[a.id,'p06-role-'+a.id,a.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,organization_id,role,status) VALUES($1,$2,$3,'active')",[a.id,a.orgId,a.roles[0]]);}});try{await expect(charges(managerOnly).preview(req('GET'),{period:'2028-02',page:1})).rejects.toMatchObject({status:403});const p=await preview(l.id,'2028-02',financeOnly),r=(await charges(financeOnly).generate(req('POST','/api/v1/ops/charges/generate'),{period:'2028-02',items:[item(p)],confirm:true})).data;expect(r.generated).toBe(1);expect((await transaction(workerActor,c=>c.query('SELECT generated_by FROM charges WHERE id=$1',[r.chargeIds[0]]))).rows[0].generated_by).toBe(financeOnly.id);}finally{await transaction(workerActor,c=>c.query("UPDATE memberships SET status='revoked',version=version+1 WHERE user_id=ANY($1::uuid[])",[[financeOnly.id,managerOnly.id]]));}});
it('P06 new market records receive explicit configured defaults and reject invalid policy values',async()=>{const key='p06-market-'+crypto.randomUUID();await marketAdmin.create(marketRequest('POST','/api/v1/ops/geography/cities'),'cities',{kind:'cities',name:'P06 synthetic configuration fixture',slug:key,aliases:[],country:'AE',currency:'AED',timezone:'Asia/Dubai'});const r=(await marketAdmin.marketRead(marketRequest(),key)).data;expect(r).toMatchObject({version:1,data:{chargeProration:'calendar_days',legacyChargeDueDay:1}});const {name:_name,...fields}=r.data;for(const raw of [[],42,'invalid',null])await expect(marketAdmin.market(marketRequest(),key,raw)).rejects.toThrow();for(const patch of [{chargeProration:'unknown'},{legacyChargeDueDay:29},{legacyChargeDueDay:'5'},{chargeProration:null}])await expect(marketAdmin.market(marketRequest(),key,{...fields,...patch,version:r.version,cityVersion:r.cityVersion})).rejects.toThrow();});
