import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import type {Identity} from '../../apps/api/src/platform/core';
afterAll(()=>pool.end());
const consumer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},controller=new EngagementController({actor:async()=>consumer} as unknown as Identity);
const request=()=>({method:'POST',url:'/api/v1/viewings',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
it('R03 public detail returns exact fixture deposit, explicit utilities and room facts without internal fields; absent terms are null; unavailable rentals cannot book',async()=>{
 const rows=await transaction(workerActor,async c=>{const rows=[];for(const missing of [false,true]){const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'R03 detail fixture',description,'rent','residential','CNY','4500.25','month',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug",['r03-'+crypto.randomUUID()])).rows[0];if(!missing)await c.query("INSERT INTO rental_terms(listing_id,rental_mode,billing_period,deposit_amount,currency,minimum_months,utilities,move_in_date) VALUES($1,'entire','month','9000.50','CNY',12,ARRAY['Water included','Electricity billed separately'],'2026-11-01')",[row.id]);rows.push(row);}return rows;});
 try{const response=await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[0].slug+'?city=bj');expect(response.status).toBe(200);const body=await response.json();expect(body.data.rentalTerms).toEqual({mode:'entire',billingPeriod:'month',depositAmount:'9000.50',currency:'CNY',minimumMonths:12,utilities:['Water included','Electricity billed separately'],moveInDate:'2026-11-01',roomAttributes:[],unitKind:'property',roomLabel:null});expect(JSON.stringify(body)).not.toMatch(/organization_id|owner_id|private_address|parent_unit_id/);expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[0].id+'?city=sh')).status).toBe(404);expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[1].id).then(r=>r.json())).data.rentalTerms).toBeNull();await transaction(workerActor,c=>c.query("UPDATE listings SET status='leased',version=version+1 WHERE id=$1",[rows[0].id]));expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[0].id)).status).toBe(404);await expect(controller.book(request(),{version:0,listingVersion:1,scheduleVersion:1,agentId:'10000000-0000-4000-8000-000000000060',listingId:rows[0].id,startAt:new Date(Date.now()+5*86400000).toISOString()})).rejects.toMatchObject({status:404});}finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[rows.map(row=>row.id)]));}
});
it('R03 shared detail labels the actual child room and attributes, with explicit zero deposit rather than an unknown fee',async()=>{
 const listing=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'19.75',1,0,0,id,'room',$1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id",['R03 room '+crypto.randomUUID()])).rows[0];const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'R03 shared detail fixture',description,'rent','residential','CNY','2250.50','month',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,'r03-shared-'+crypto.randomUUID()])).rows[0];await c.query("INSERT INTO rental_terms(listing_id,rental_mode,billing_period,deposit_amount,currency,room_attributes) VALUES($1,'shared','month','0.00','CNY',ARRAY['Private balcony','Shared kitchen'])",[row.id]);return row;});
 try{const data=(await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+listing.id).then(r=>r.json())).data;expect(data.area).toBe('19.75');expect(data.rentalTerms).toMatchObject({mode:'shared',unitKind:'room',depositAmount:'0.00',roomAttributes:['Private balcony','Shared kitchen']});expect(data.rentalTerms.roomLabel).toMatch(/^R03 room /);}finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[listing.id]));}
});
