import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {pool,transaction} from '../../packages/database/src/index';
import {workerActor,createProcessor,initializeSearch} from '../../apps/worker/src/processor';
import {listingFilters,listingSearchSchemaVersion} from '../../packages/contracts/src/index';
import {searchListings,compileListingSearch} from '../../apps/api/src/geography/search';
afterAll(()=>pool.end());
it('R02 indexed and SQL rental criteria isolate entire furnished monthly budgets, availability dates and yearly amounts',async()=>{
 await initializeSearch();const fixtures=await transaction(workerActor,async c=>{const rows=[];for(const entry of [{mode:'entire',period:'month',date:'2026-10-15',furnishing:'Furnished'},{mode:'entire',period:'year',date:'2026-10-15',furnishing:'Furnished'},{mode:'shared',period:'month',date:'2026-10-15',furnishing:'Furnished'},{mode:'entire',period:'month',date:'2026-12-01',furnishing:'Furnished'},{mode:'entire',period:'month',date:null,furnishing:'Furnished'},{mode:'entire',period:'month',date:'2026-10-15',furnishing:'Unfurnished'}]){let unit='10000000-0000-4000-8000-000000001000';if(entry.mode==='shared')unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'18.50',1,0,0,id,'room',$1 FROM units WHERE id=$2 RETURNING id",['R02 '+crypto.randomUUID(),unit])).rows[0].id;const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,available_from,furnishing,photos,features,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'R02 rental fixture',description,'rent','residential','CNY','4800.25',$3,$4,$5,photos,ARRAY['Near metro','Elevator'],'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit,'r02-'+crypto.randomUUID(),entry.period,entry.date,entry.furnishing])).rows[0];await c.query("INSERT INTO rental_terms(listing_id,rental_mode,currency,billing_period,deposit_amount,move_in_date) VALUES($1,$2,'CNY',$3,'4800.25',$4)",[listing.id,entry.mode,entry.period,entry.date]);const event=(await c.query("INSERT INTO outbox(aggregate_id,kind,payload,dispatched_at) VALUES($1,'listing.published','{}',now()) RETURNING id",[listing.id])).rows[0];rows.push({...listing,event:event.id});}return rows;});
 try{
  for(const row of fixtures)await createProcessor()({data:{id:row.event}});const criteria=listingFilters.parse({city:'bj',transaction:'rent',rentalMode:'entire',rentPeriod:'month',furnishing:'Furnished',availableBy:'2026-11-01',features:'Near metro',minPrice:'4800.25',maxPrice:'4800.25',sort:'price_asc'}),found=await searchListings(criteria);expect(found.data.map(row=>row.id)).toEqual([fixtures[0].id]);expect(found.meta).toMatchObject({searchMode:'meilisearch',rentalPeriod:'month',billingPeriodSource:'requested'});expect(found.data[0]).toMatchObject({rentalMode:'entire',rentPeriod:'month',price:'4800.25'});expect((await searchListings(criteria,'http://127.0.0.1:1')).data.map(row=>row.id)).toEqual([fixtures[0].id]);const yearly=await searchListings({...criteria,rentPeriod:'year'});expect(yearly.data.map(row=>row.id)).toEqual([fixtures[1].id]);expect(yearly.meta).toMatchObject({rentalPeriod:'year',billingPeriodSource:'requested'});const shared=await searchListings({...criteria,rentalMode:'shared'});expect(shared.data.map(row=>row.id)).toEqual([fixtures[2].id]);expect(shared.data[0].area).toBe('18.50');expect((await searchListings({...criteria,rentPeriod:undefined})).meta).toMatchObject({rentalPeriod:'month',billingPeriodSource:'market'});expect((await searchListings({...criteria,rentPeriod:undefined})).data.map(row=>row.id)).toEqual([fixtures[0].id]);const compiled=compileListingSearch(criteria);expect(compiled.filter).toContain('rentalMode = "entire"');expect(compiled.filter).toContain('availableKnown = true');expect(compiled.filter).toContain('projectionSchemaVersion = '+listingSearchSchemaVersion);expect(compiled.where).not.toContain('2026-11-01');
 }finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[fixtures.map(row=>row.id)]));}
});
it('R02 rental-only filters reject a sale/unspecified transaction, invalid mode and invalid calendar date',()=>{
 for(const input of [{transaction:'sale',rentalMode:'entire'},{availableBy:'2026-11-01'},{transaction:'rent',rentalMode:'other'},{transaction:'rent',availableBy:'2026-02-30'}])expect(listingFilters.safeParse(input).success).toBe(false);
});
