import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor,createProcessor,initializeSearch} from '../../apps/worker/src/processor';
import {changeListingState} from '../../apps/api/src/inventory/workflow';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import type {Identity} from '../../apps/api/src/platform/core';
import {searchListings} from '../../apps/api/src/geography/search';
import {listingFilters} from '../../packages/contracts/src/index';
afterAll(()=>pool.end());
const agent:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:'10000000-0000-4000-8000-000000000001',roles:['agent']},moderator:Actor={id:'00000000-0000-4000-8000-000000000008',orgId:null,roles:['moderator']},consumer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},engagement=new EngagementController({actor:async()=>consumer} as unknown as Identity);
const request=()=>({method:'POST',url:'/api/v1/inquiries',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
async function fixture(){return transaction(workerActor,async c=>{const parent=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'80.25',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0].id;const units=[parent];for(const label of ['A','B'])units.push((await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'20.25',1,0,0,id,'room',$2 FROM units WHERE id=$1 RETURNING id",[parent,'R04 '+label])).rows[0].id);const rows=[];for(const [i,unit] of units.entries()){const row=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,photos,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'R04 availability fixture',description,'rent','residential','CNY','7456.25','month',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,slug,unit_id",[unit,'r04-'+crypto.randomUUID()])).rows[0];await c.query("INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,'month','CNY')",[row.id,i?'shared':'entire']);rows.push(row);}return rows;});}
const archive=(rows:any[])=>transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[rows.map(row=>row.id)]));
it('R04 leased room invalidates whole-property search/detail/contact even with stale index; sibling room remains available and publication checks canonical occupancy',async()=>{
 await initializeSearch();const rows=await fixture();try{for(const row of rows){const e=await transaction(workerActor,async c=>(await c.query("INSERT INTO outbox(aggregate_id,kind,payload,dispatched_at) VALUES($1,'listing.published','{}',now()) RETURNING id",[row.id])).rows[0]);await createProcessor()({data:{id:e.id}});}const found=()=>searchListings(listingFilters.parse({city:'bj',transaction:'rent',rentPeriod:'month',minPrice:'7456.25',maxPrice:'7456.25',sort:'price_asc'}));expect((await found()).data.map(row=>row.id).sort()).toEqual(rows.map(row=>row.id).sort());await transaction(agent,async c=>{await changeListingState(c,agent,rows[1].id,{status:'leased',version:1});await c.query('UPDATE outbox SET dispatched_at=now() WHERE aggregate_id=ANY($1::uuid[]) AND dispatched_at IS NULL',[rows.map(row=>row.id)]);});const stale=await fetch(process.env.SEARCH_URL+'/indexes/listings/documents/'+rows[0].id,{headers:{Authorization:'Bearer '+process.env.SEARCH_KEY}});expect(stale.status).toBe(200);expect((await found()).data.map(row=>row.id)).toEqual([rows[2].id]);for(const row of rows.slice(0,2)){expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+row.id)).status).toBe(404);await expect(engagement.inquiry(request(),{resourceType:'listing',resourceId:row.id,name:'R04 consumer',email:'consumer@example.test',phone:'+861000000001',message:'Availability fixture inquiry',consent:true})).rejects.toMatchObject({status:404});}expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[2].id)).status).toBe(200);await transaction(workerActor,c=>c.query("UPDATE listings SET status='under_review',version=version+1 WHERE id=$1",[rows[0].id]));await expect(transaction(moderator,c=>changeListingState(c,moderator,rows[0].id,{status:'published',version:2,verified:true}))).rejects.toMatchObject({status:409});const queued=await transaction(workerActor,async c=>(await c.query("SELECT id FROM outbox WHERE aggregate_id=$1 AND kind='listing.availability_changed' ORDER BY created_at DESC LIMIT 1",[rows[0].id])).rows[0]);expect(queued).toBeTruthy();await createProcessor()({data:{id:queued.id}});expect((await fetch(process.env.SEARCH_URL+'/indexes/listings/documents/'+rows[0].id,{headers:{Authorization:'Bearer '+process.env.SEARCH_KEY}})).status).toBe(404);await expect(transaction(agent,c=>changeListingState(c,agent,rows[1].id,{status:'archived',version:1}))).rejects.toMatchObject({status:409});await transaction(agent,c=>changeListingState(c,agent,rows[1].id,{status:'archived',version:2}));expect((await transaction(null,c=>c.query('SELECT rental_unit_is_free($1) AS available',[rows[0].unit_id]))).rows[0].available).toBe(true);}finally{await archive(rows);}
});
it('R04 root lock serializes a whole-property leased transition against child publication and prevents publication after the committed occupancy',async()=>{
 const rows=await fixture();try{await transaction(workerActor,c=>c.query("UPDATE listings SET status='under_review',version=version+1 WHERE id=$1",[rows[1].id]));let release!:()=>void,held!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),ready=new Promise<void>(resolve=>held=resolve);const occupancy=transaction(agent,async c=>{await changeListingState(c,agent,rows[0].id,{status:'leased',version:1});held();await gate;});await ready;const publication=transaction(moderator,c=>changeListingState(c,moderator,rows[1].id,{status:'published',version:2,verified:true}));const outcome=publication.then(()=>({allowed:true}),e=>({allowed:false,status:e.status}));try{await expect.poll(async()=>(await pool.query("SELECT count(*)::int AS count FROM pg_locks WHERE locktype='advisory' AND NOT granted")).rows[0].count,{timeout:5000}).toBeGreaterThan(0);}finally{release();}await occupancy;expect(await outcome).toEqual({allowed:false,status:409});expect((await transaction(workerActor,c=>c.query('SELECT status,version FROM listings WHERE id=$1',[rows[1].id]))).rows[0]).toEqual({status:'under_review',version:2});expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[2].id)).status).toBe(404);}finally{await archive(rows);}
});
it('R04 active whole-unit lease denies every child contact and public detail; direct consumer lead insert cannot bypass eligibility',async()=>{
 const rows=await fixture();let leaseId='';try{leaseId=await transaction(workerActor,async c=>(await c.query("INSERT INTO leases(organization_id,unit_id,tenant_id,start_date,end_date,rent,currency,status) SELECT organization_id,$1,tenant_id,CURRENT_DATE,CURRENT_DATE+365,'7456.25','CNY','active' FROM leases WHERE status='active' ORDER BY id LIMIT 1 RETURNING id",[rows[0].unit_id])).rows[0].id);for(const row of rows){expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+row.id)).status).toBe(404);expect((await transaction(null,c=>c.query('SELECT * FROM published_listing_destination($1)',[row.id]))).rows).toEqual([]);}await expect(transaction(consumer,c=>c.query("INSERT INTO leads(user_id,resource_id,resource_type,name,email,phone,message) VALUES($1,$2,'listing','R04 bypass fixture','consumer@example.test','+861000000001','Direct insertion must fail')",[consumer.id,rows[1].id]))).rejects.toMatchObject({code:'23514'});await transaction(workerActor,c=>c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=$1",[leaseId]));expect((await fetch((process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088')+'/api/v1/listings/'+rows[1].id)).status).toBe(200);}finally{if(leaseId)await transaction(workerActor,c=>c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=$1",[leaseId]));await archive(rows);}
});
