import {fixtureAccountState} from '../support/account-fixture';
import {ViewingAvailabilityController} from '../../apps/api/src/engagement/viewing-availability';
import '../support/env';
import {it,expect,afterAll} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import {submitListingRevision,decideListingRevision} from '../../apps/api/src/inventory/revisions';
import type {Identity} from '../../apps/api/src/platform/core';
afterAll(()=>pool.end());
const consumer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},moderator:Actor={id:'00000000-0000-4000-8000-000000000008',orgId:null,roles:['moderator']};
const bookings=new EngagementController({actor:async()=>consumer} as unknown as Identity),origin=(process.env.INTEGRATION_WEB_URL||process.env.PUBLIC_WEB_URL||'http://localhost:8088');
const req=()=>({method:'POST',url:'/api/v1/viewings',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
it('D08 detail exposes only published facts and current eligible assigned agents; expired/unassigned agents and withdrawn listings cannot receive bookings',async()=>{
 let agentId='',listing:any;
 await transaction(workerActor,async c=>{agentId=(await c.query(`INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,verified_until,photo,public_email) SELECT gen_random_uuid(),user_id,organization_id,'D08 test agent',$1,biography,languages,districts,CURRENT_DATE+30,photo,public_email FROM agents WHERE id='10000000-0000-4000-8000-000000000060' RETURNING id`,['detail-agent-'+crypto.randomUUID()])).rows[0].id;listing=(await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,photos,status,published_at) SELECT unit_id,organization_id,owner_id,$2,$1,'Published D08 title','Published D08 description','sale','residential','CNY','2222222.25',photos,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING *`,['detail-'+crypto.randomUUID(),agentId])).rows[0];});
 const detail=()=>fetch(origin+'/api/v1/listings/'+listing.id+'?city=bj').then(r=>r.json()),agents=()=>fetch(origin+'/api/v1/listings/'+listing.id+'/agents?city=bj').then(r=>r.json());
 try{
  const eligible=await agents();expect(eligible.data.map((x:any)=>x.id)).toEqual([agentId]);expect(JSON.stringify(eligible)).not.toMatch(/user_id|organization_id|credential_document|private_address/);expect((await fetch(origin+'/api/v1/listings/'+listing.id+'/agents?city=sh')).status).toBe(404);
  const author:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:listing.organization_id,roles:['agent']};const revision=await transaction(author,c=>submitListingRevision(c,author,listing.id,{title:'Pending D08 title',description:'Pending D08 description',price:'3333333.75',version:1,reason:'Private pending fixture reason'}));
  expect((await detail()).data).toMatchObject({title:'Published D08 title',description:'Published D08 description',price:'2222222.25',version:1});await transaction(moderator,c=>decideListingRevision(c,moderator,revision.id,{status:'approved',version:1,reason:'Independent published facts reviewed',verified:true}));expect((await detail()).data).toMatchObject({title:'Pending D08 title',description:'Pending D08 description',price:'3333333.75',version:2});expect(JSON.stringify(await detail())).not.toContain('Private pending fixture reason');
  const availability=new ViewingAvailabilityController({actor:async()=>author} as unknown as Identity);await availability.save(req(),listing.id,{version:0,listingVersion:2,agentId,status:'active',durationMinutes:60,bufferMinutes:15,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'});const slots=(await availability.slots({listingId:listing.id,date:new Date(Date.now()+3*86400000).toISOString().slice(0,10),days:1})).data;const startAt=slots.slots[0].startAt,bookingInput={version:0,listingId:listing.id,listingVersion:2,scheduleVersion:1,agentId,startAt};expect((await bookings.book(req(),bookingInput)).data.agent_id).toBe(agentId);
  await transaction(workerActor,async c=>{await c.query('SAVEPOINT agent_eligibility_probe');await fixtureAccountState(c,'suspended',"WHERE id=(SELECT user_id FROM agents WHERE id=$1)",[agentId]);expect((await c.query('SELECT * FROM public_listing_agents($1)',[listing.id])).rows).toEqual([]);await c.query('ROLLBACK TO SAVEPOINT agent_eligibility_probe');await c.query("UPDATE memberships SET status='inactive' WHERE user_id=(SELECT user_id FROM agents WHERE id=$1)",[agentId]);expect((await c.query('SELECT * FROM public_listing_agents($1)',[listing.id])).rows).toEqual([]);await c.query('ROLLBACK TO SAVEPOINT agent_eligibility_probe');});
  await transaction(workerActor,c=>c.query('UPDATE agents SET verified_until=CURRENT_DATE-1 WHERE id=$1',[agentId]));expect((await agents()).data).toEqual([]);await expect(bookings.book(req(),{...bookingInput,startAt:new Date(Date.now()+4*86400000).toISOString()})).rejects.toMatchObject({status:409});
  await expect(transaction(consumer,c=>c.query('INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at) VALUES($1,$2,$3,now()+interval \'5 days\',now()+interval \'5 days 1 hour\')',[listing.id,consumer.id,agentId]))).rejects.toMatchObject({code:'23514'});
  await transaction(workerActor,c=>c.query('UPDATE listings SET agent_id=NULL WHERE id=$1',[listing.id]));expect((await agents()).data).toEqual([]);await expect(bookings.book(req(),bookingInput)).rejects.toMatchObject({status:409});
  await transaction(workerActor,c=>c.query("UPDATE listings SET status='paused',version=version+1 WHERE id=$1",[listing.id]));expect((await fetch(origin+'/api/v1/listings/'+listing.id)).status).toBe(404);expect((await fetch(origin+'/api/v1/listings/'+listing.id+'/agents')).status).toBe(404);await expect(bookings.book(req(),bookingInput)).rejects.toMatchObject({status:404});
 }finally{await transaction(workerActor,async c=>{await c.query('DELETE FROM viewings WHERE listing_id=$1',[listing.id]);await c.query("UPDATE listings SET agent_id=NULL,status='paused',version=version+1 WHERE id=$1",[listing.id]);await c.query('UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1',[agentId]);});}
});
