import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {SavedSearchController} from '../../apps/api/src/engagement/saved-searches';
import type {Identity} from '../../apps/api/src/platform/core';
import type {FastifyRequest} from 'fastify';
afterAll(()=>pool.end());
it('A04 normalized complex rental criteria restore, require city currency, update/pause/delete with versions and deny another actor',async()=>{
 const first=crypto.randomUUID(),other=crypto.randomUUID();await transaction(workerActor,async c=>{for(const id of [first,other])await c.query("INSERT INTO profiles(id,subject,display_name,email) VALUES($1,$2,'Search fixture','search@example.test')",[id,'search-'+id]);});
 const actor=(id:string):Actor=>({id,orgId:null,roles:['consumer']}),control=(id:string)=>new SavedSearchController({actor:async()=>actor(id)} as unknown as Identity),searches=control(first),outsider=control(other);
 const req=(method='POST',url='/api/v1/me/saved-searches',key=crypto.randomUUID())=>({method,url,headers:{'idempotency-key':key}} as unknown as FastifyRequest);
 const filters={city:'bj',transaction:'rent',segment:'residential',currency:'CNY',rentPeriod:'month',minPrice:'1000.00',maxPrice:'15000.00',beds:'2,1,2',minArea:'60',maxArea:'140',orientation:'South, East,South',features:'Near metro,Garden views',furnishing:'Furnished',elevator:'true',sort:'price_asc'};
 let id='';
 try{
  const request=req(),input={name:'  Rental criteria fixture  ',filters,cadence:'daily',version:0};const created=await searches.create(request,input);id=created.data.id;expect(created.data).toMatchObject({name:'Rental criteria fixture',version:1,criteriaVersion:1,paused:false,alertEligible:true,cadence:'daily',filters:{city:'bj',currency:'CNY',transaction:'rent',beds:'1,2',orientation:'East,South',minPrice:'1000.00',maxPrice:'15000.00',minArea:'60',maxArea:'140'}});expect(await searches.create(request,input)).toEqual(created);const restored=new URL(created.data.restoreUrl,'http://example.test');expect(restored.pathname).toBe('/bj/rent');for(const [key,value] of Object.entries(created.data.filters))if(key!=='city')expect(restored.searchParams.get(key)).toBe(value);expect((await searches.read(req('GET'))).data[0]).toEqual(created.data);
  expect((await searches.matches(req('GET'),id)).data.eligible).toBe(true);const active=(await searches.matches(req('GET'),id)).data.listings;expect(active.every(row=>row.city==='bj'&&row.currency==='CNY')).toBe(true);
  await expect(outsider.update(req('PATCH'),id,{...input,version:1,paused:true})).rejects.toMatchObject({status:404});await expect(outsider.remove(req('DELETE'),id,{version:1})).rejects.toMatchObject({status:404});await expect(outsider.matches(req('GET'),id)).rejects.toMatchObject({status:404});expect((await outsider.read(req('GET'))).data).toEqual([]);
  const paused=await searches.update(req('PATCH','/api/v1/me/saved-searches/'+id),id,{...input,filters:created.data.filters,name:'Edited rental criteria',cadence:'weekly',version:1,paused:true});expect(paused.data).toMatchObject({version:2,paused:true,alertEligible:false});expect((await searches.matches(req('GET'),id)).data).toEqual({eligible:false,reason:'paused',listings:[]});await expect(searches.update(req('PATCH'),id,{...input,version:1,paused:false})).rejects.toMatchObject({status:409});
  for(const invalid of [{...input,filters:{...filters,minPrice:'20000',maxPrice:'1000'}},{...input,filters:{...filters,unknown:'raw expression'}},{...input,filters:{...filters,page:'2'}},{...input,name:' '},{...input,userId:other}])await expect(searches.create(req(),invalid)).rejects.toMatchObject({name:'ZodError'});
  await expect(searches.create(req(),{...input,filters:{...filters,currency:'USD'}})).rejects.toMatchObject({status:400});await expect(searches.create(req(),{...input,filters:{...filters,city:'unknown-city'}})).rejects.toMatchObject({status:400});await expect(searches.create(req(),{...input,filters:{...filters,communityId:crypto.randomUUID()}})).rejects.toMatchObject({status:400});
  const resumed=await searches.update(req('PATCH'),id,{...input,filters:created.data.filters,version:2,paused:false});expect(resumed.data).toMatchObject({version:3,paused:false,alertEligible:true});const deleted=await searches.remove(req('DELETE'),id,{version:3});expect(deleted.data).toEqual({deleted:true,version:4});expect((await searches.read(req('GET'))).data).toEqual([]);await expect(searches.update(req('PATCH'),id,{...input,version:4,paused:false})).rejects.toMatchObject({status:404});
  await transaction(workerActor,async c=>{expect((await c.query("SELECT count(*)::int n FROM audit_events WHERE resource_id=$1 AND action='account.saved_search_created'",[id])).rows[0].n).toBe(1);expect((await c.query('SELECT paused,version,deleted_at IS NOT NULL deleted FROM saved_searches WHERE id=$1',[id])).rows[0]).toEqual({paused:true,version:4,deleted:true});});
 }finally{await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=ANY($1::uuid[])",[[first,other]]));}
});
it('A04 matching uses current SQL currency/availability and legacy criteria stay ineligible',async()=>{
 const actor:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},searches=new SavedSearchController({actor:async()=>actor} as unknown as Identity),request=(method='POST')=>({method,url:'/api/v1/me/saved-searches',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
 const ids=await transaction(workerActor,async c=>{const rows=[];for(const currency of ['CNY','USD'])rows.push((await c.query(`INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT unit_id,organization_id,owner_id,agent_id,$1,'A04_MATCH_SENTINEL',description,'sale',segment,$2,price,'published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id`,['a04-'+crypto.randomUUID(),currency])).rows[0].id);return rows;});
 let saved:any;
 try{saved=(await searches.create(request(),{name:'Currency isolation',filters:{city:'bj',transaction:'sale',currency:'CNY',text:'A04_MATCH_SENTINEL'},cadence:'weekly',version:0})).data;const matched=(await searches.matches(request('GET'),saved.id)).data;expect(matched.listings.map(row=>row.id)).toEqual([ids[0]]);await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[ids[0]]));expect((await searches.matches(request('GET'),saved.id)).data.listings).toEqual([]);await transaction(workerActor,c=>c.query("UPDATE saved_searches SET filters=jsonb_set(filters,'{currency}','\"USD\"'::jsonb) WHERE id=$1",[saved.id]));expect((await searches.read(request('GET'))).data.find(row=>row.id===saved.id)?.alertEligible).toBe(false);expect((await searches.matches(request('GET'),saved.id)).data).toEqual({eligible:false,reason:'city-or-currency-changed',listings:[]});const current=(await searches.read(request('GET'))).data.find(row=>row.id===saved.id)!;const paused=await searches.update(request('PATCH'),saved.id,{name:current.name,filters:current.filters,cadence:current.cadence,version:current.version,paused:true});expect(paused.data).toMatchObject({paused:true,alertEligible:false});
 const legacy=(await transaction(workerActor,c=>c.query("INSERT INTO saved_searches(user_id,name,filters,cadence) VALUES($1,'Legacy criteria','{}','weekly') RETURNING id",[actor.id]))).rows[0].id;expect((await searches.matches(request('GET'),legacy)).data).toMatchObject({eligible:false,listings:[]});await transaction(workerActor,c=>c.query('DELETE FROM saved_searches WHERE id=$1',[legacy]));
 }finally{await transaction(workerActor,async c=>{if(saved)await c.query('UPDATE saved_searches SET paused=true,deleted_at=now() WHERE id=$1',[saved.id]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[]) AND status='published'",[ids]);});}
});
