import {createRequire} from 'node:module';
import {leaseStatement,statementCSV,statementHTML} from '../../apps/api/src/management/statements';
import {TenantLeasesController} from '../../apps/api/src/management/tenant-leases';
import {DepositsController} from '../../apps/api/src/management/deposits';
import {FinancialReversalsController} from '../../apps/api/src/management/financial-reversals';
import {PaymentAllocationsController} from '../../apps/api/src/management/payment-allocations';
import {ManagementController} from '../../apps/api/src/management/controller';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtureDB=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});
const otherOwner:Actor={id:crypto.randomUUID(),orgId:null,roles:['owner']};
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P14 other synthetic owner',true)",[otherOwner.id,'p14-owner-'+otherOwner.id,otherOwner.id+'@example.test']);await c.query("INSERT INTO memberships(user_id,role,status) VALUES($1,'owner','active')",[otherOwner.id]);});await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P14 verified synthetic tenant',true)",[tenant.id,'p14-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string,currency='CNY',communityId?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT coalesce($4::uuid,community_id),organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P14 room '+crypto.randomUUID().slice(0,8):null,communityId||null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P14 synthetic rental offer',description,'rent','residential',$4,'1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p14-'+crypto.randomUUID(),currency])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month',currency]);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source,currency};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P14 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31',documents:{assetId:string;version:number;label:string}[]=[]){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:f.currency,rentPeriod:'month',dueDay:5,documents})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});await fixtureDB.end();});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2026-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
async function financial(amount='250.25',charged='200.20'){const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(l.id),amount})).data,posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(p))).data,ch=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2028-01-01','2028-01-05',$3,'CNY') RETURNING id,version",[l.id,manager.orgId,charged])).rows[0]);return {...f,l,p:posted,ch};}

const portal=(a=tenant)=>new TenantLeasesController(identity(a)),allocations=()=>new PaymentAllocationsController(identity(manager)),deposits=()=>new DepositsController(identity(manager)),reversals=()=>new FinancialReversalsController(identity(manager));
async function allocated(f:Awaited<ReturnType<typeof financial>>){const l=(await allocations().ledger(req('GET'),f.l.id,{})).data;return allocations().create(req('POST','/api/v1/ops/allocations'),{version:0,leaseId:f.l.id,leaseVersion:l.leaseVersion,unitVersion:l.unitVersion,grantVersion:l.grantVersion,paymentId:f.p.id,paymentVersion:f.p.version,chargeId:f.ch.id,chargeVersion:f.ch.version,amount:'50.05',currency:'CNY',confirm:true});}
async function deposit(id:string){const l=(await deposits().ledger(req('GET'),id,{})).data;return deposits().create(req('POST','/api/v1/ops/deposits'),{version:0,leaseId:id,leaseVersion:l.leaseVersion,unitVersion:l.unitVersion,grantVersion:l.grantVersion,liabilityVersion:l.liabilityVersion,kind:'received',direction:'increase',amount:'100.10',currency:'CNY',reason:'P14 PRIVATE OWNER NOTE SENTINEL bank account must remain staff private.',confirm:true});}
const statements=(a=owner)=>new ManagementController(identity(a));
it('P14 golden posted ledger reconciles opening, inclusive period movements and closing with linked reversals and allocation undo',async()=>{
 const f=await fixture(),l=await active(f);
 await transaction(workerActor,async c=>{
  const charge=async(amount:string,at:string,reverses:string|null=null)=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,created_at,reverses_id,kind) VALUES($1,$2,'2026-01-01','2026-01-05',$3,'CNY',$4,$5,$6) RETURNING id",[l.id,manager.orgId,amount,at,reverses,reverses?'reversal:'+reverses:'p14-synthetic-'+crypto.randomUUID()])).rows[0].id;
  const payment=async(amount:string,at:string,reverses:string|null=null)=>(await c.query("INSERT INTO payments(lease_id,organization_id,amount,currency,source,reference,actor_id,status,created_at,reverses_id) VALUES($1,$2,$3,'CNY','bank_statement','PRIVATE P14 LEGACY SOURCE SENTINEL',$4,'posted',$5,$6) RETURNING id",[l.id,manager.orgId,amount,manager.id,at,reverses])).rows[0].id;
  const ch=await charge('200.20','2026-01-01T00:00:00Z'),p=await payment('250.25','2026-01-02T00:00:00Z');await c.query("INSERT INTO allocations(payment_id,charge_id,organization_id,amount,created_at) VALUES($1,$2,$3,'50.05','2026-01-03T00:00:00Z')",[p,ch,manager.orgId]);
  await c.query("INSERT INTO deposits(lease_id,organization_id,kind,amount,currency,reason,actor_id,created_at) VALUES($1,$2,'received','100.10','CNY','PRIVATE P14 LEGACY SOURCE SENTINEL',$3,'2026-01-04T00:00:00Z')",[l.id,manager.orgId,manager.id]);
  const ch2=await charge('99.99','2026-02-01T00:00:00Z'),p2=await payment('30.03','2026-02-01T00:00:00Z');await c.query("INSERT INTO allocations(payment_id,charge_id,organization_id,amount,created_at,reversed_at,version) VALUES($1,$2,$3,'20.02','2026-02-02T00:00:00Z','2026-02-28T23:59:59Z',2)",[p2,ch2,manager.orgId]);await charge('99.99','2026-02-28T23:59:59Z',ch2);await payment('30.03','2026-02-28T23:59:59Z',p2);
  await c.query("INSERT INTO deposits(lease_id,organization_id,kind,amount,currency,reason,actor_id,created_at) VALUES($1,$2,'released','10.01','CNY','PRIVATE P14 LEGACY SOURCE SENTINEL',$3,'2026-02-28T23:59:59Z')",[l.id,manager.orgId,manager.id]);
 },fixtureDB);
 const x={from:'2026-02-01',to:'2026-02-28'},r=(await statements().statement(req('GET'),l.id,x)).data;
 expect(r.opening).toEqual({charges:'200.20',recordedPayments:'250.25',allocated:'50.05',outstanding:'150.15',credit:'200.20',depositHeld:'100.10'});expect(r.movements).toEqual({charges:'0.00',recordedPayments:'0.00',allocated:'0.00',outstanding:'0.00',credit:'0.00',depositHeld:'-10.01'});expect(r.totals).toEqual({...r.opening,depositHeld:'90.09'});expect(r.total).toBe(7);expect(r.entries.map(e=>e.kind)).toEqual(expect.arrayContaining(['charge_reversal','payment_reversal','allocation_undo','deposit']));expect(r.entries.every(e=>e.historical)).toBe(true);expect(JSON.stringify(r)).not.toContain('PRIVATE P14 LEGACY SOURCE SENTINEL');
 const own=(await statements(tenant).statement(req('GET'),l.id,x)).data;expect(own.scope).toBe('tenant');expect(own.totals).toEqual(r.totals);expect((await statements(manager).statement(req('GET'),l.id,x)).data.scope).toBe('professional');expect((await statements().statement(req('GET'),l.id,{from:'2026-03-01',to:'2026-03-01'})).data).toMatchObject({total:0,opening:r.totals,totals:r.totals});
 const csv=statementCSV(r),print=statementHTML(r);expect(csv).toContain('"Deposit liability","100.10","-10.01","90.09"');expect(csv).toContain('"allocation_undo"');expect(print).toContain('All 7 period entries');expect(print).not.toContain('PRIVATE P14 LEGACY SOURCE SENTINEL');
},90000);
it('P14 actual posted finance reconciles with the tenant portal and current grants deny other owners, forged staff and revoked exports',async()=>{
 const f=await financial();await allocated(f);await deposit(f.l.id);const unposted=(await payments().create(req(),{...await body(f.l.id),amount:'999.99'})).data,r=(await statements().statement(req('GET'),f.l.id)).data;expect(r.totals).toEqual((await portal().read(req('GET'),f.l.id,{})).data.totals);expect(r.entries.some(e=>e.id===unposted.id)).toBe(false);expect(JSON.stringify(r)).not.toContain('PRIVATE OWNER NOTE SENTINEL');
 for(const a of [otherOwner,{...otherOwner,orgId:manager.orgId,roles:['finance','property_manager','admin']}]){await expect(statements(a).statement(req('GET'),f.l.id)).rejects.toMatchObject({status:404});await expect(transaction(a,c=>leaseStatement(c,f.l.id,{},true))).rejects.toMatchObject({status:404});expect((await statements(a).ownerLeases(req('GET'),{})).data.some((l:any)=>l.id===f.l.id)).toBe(false);}
 const original=(await reversals().read(req('GET'),'payment',f.p.id)).data;await reversals().reversePayment(req(),f.p.id,{version:original.version,leaseVersion:original.leaseVersion,unitVersion:original.unitVersion,grantVersion:original.grantVersion,reason:'P14 PRIVATE reversal source reason.',confirm:true});expect((await statements().statement(req('GET'),f.l.id)).data.totals).toMatchObject({recordedPayments:'0.00',allocated:'0.00',outstanding:'200.20',credit:'0.00',depositHeld:'100.10'});
 await new ManagementGrantsController(identity(owner)).update(req('PATCH'),f.g.id,{action:'revoke',version:1,reason:'Owner revokes current statement service authority.'});await expect(statements().statement(req('GET'),f.l.id)).rejects.toMatchObject({status:404});await expect(statements(manager).statement(req('GET'),f.l.id)).rejects.toMatchObject({status:404});await expect(transaction(owner,c=>leaseStatement(c,f.l.id,{},true))).rejects.toMatchObject({status:404});expect((await statements(tenant).statement(req('GET'),f.l.id)).data.totals.outstanding).toBe('200.20');
},90000);
it('P14 separate USD/CNY leases preserve amounts above JavaScript integer precision and refuse historical currency conflicts',async()=>{
 const communityId=await transaction(workerActor,async c=>{const suffix=crypto.randomUUID(),ci=(await c.query("INSERT INTO cities(slug,name,country,currency,timezone) VALUES($1,'P14 synthetic US market','US','USD','America/New_York') RETURNING id",['p14-'+suffix])).rows[0],d=(await c.query("INSERT INTO districts(city_id,name,slug) VALUES($1,'P14 synthetic district',$2) RETURNING id",[ci.id,'p14-'+suffix])).rows[0];return (await c.query("INSERT INTO communities(district_id,slug,name,address) VALUES($1,$2,'P14 synthetic USD community','Synthetic address') RETURNING id",[d.id,'p14-'+suffix])).rows[0].id;});const cny=await active(await fixture()),usd=await active(await fixture(undefined,'USD',communityId));
 await transaction(workerActor,async c=>{for(const [l,currency] of [[cny,'CNY'],[usd,'USD']] as const)await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2026-10-01','2026-10-05','9007199254740993.01',$3)",[l.id,manager.orgId,currency]);});for(const l of [cny,usd]){const r=(await statements().statement(req('GET'),l.id)).data;expect(r.totals.outstanding).toBe('9007199254740993.01');expect(r.entries.every(e=>e.currency===r.lease.currency)).toBe(true);}expect((await statements().statement(req('GET'),usd.id)).data.lease.currency).toBe('USD');
 await transaction(workerActor,c=>c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind) VALUES($1,$2,'2026-10-01','2026-10-05','1.01','EUR','p14-currency-conflict')",[cny.id,manager.orgId]));await expect(statements().statement(req('GET'),cny.id)).rejects.toMatchObject({status:409});
},90000);
it('P14 bounded pages retain full totals and complete exports escape labels, while oversized exports and malformed periods refuse',async()=>{
 const f=await fixture(),l=await active(f);await transaction(workerActor,c=>c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind) SELECT $1,$2,'2026-10-01','2026-10-05','1.01','CNY','p14-'||n FROM generate_series(1,21) n",[l.id,manager.orgId]));const first=(await statements().statement(req('GET'),l.id,{page:1})).data,second=(await statements().statement(req('GET'),l.id,{page:2})).data;expect(first.entries).toHaveLength(20);expect(second.entries).toHaveLength(1);expect(second.totals.charges).toBe('21.21');const full=await transaction(owner,c=>leaseStatement(c,l.id,{},true));expect(full.entries).toHaveLength(21);expect(statementCSV(full)).toContain(second.entries[0].id);expect(statementHTML(full)).toContain('All 21 period entries');const label='=HYPERLINK("https://invalid.test")<script>alert(1)</script>';const evil={...full,lease:{...full.lease,community:label}};expect(statementCSV(evil)).toContain("\"'=HYPERLINK");expect(statementHTML(evil)).not.toContain('<script>');
 await expect(statements().statement(req('GET'),l.id,{from:'2026-02-30'})).rejects.toThrow();await expect(statements().statement(req('GET'),l.id,{from:'0000-01-01'})).rejects.toThrow();await expect(statements().statement(req('GET'),l.id,{from:'2026-10-10',to:'2026-10-01'})).rejects.toThrow();await transaction(workerActor,c=>c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind) SELECT $1,$2,'2026-10-01','2026-10-05','0.01','CNY','p14-cap-'||n FROM generate_series(1,10000) n",[l.id,manager.orgId]));await expect(transaction(owner,c=>leaseStatement(c,l.id,{},true))).rejects.toMatchObject({status:409});
},90000);
