import '../support/env';
import {beforeAll,it,expect} from 'vitest';
import {AdministrationController} from '../../apps/api/src/administration/controller';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import type {Identity} from '../../apps/api/src/platform/core';
import type {FastifyRequest} from 'fastify';
const buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},other:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},staff:Actor={id:'00000000-0000-4000-8000-000000000009',orgId:null,roles:['support']};
const api=(a=buyer)=>new AdministrationController({actor:async()=>a} as unknown as Identity),req=(method='POST')=>({method,url:'/api/v1/support-cases',headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);let listing:{id:string;version:number};
beforeAll(async()=>{listing=await transaction(workerActor,async c=>{const u=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id")).rows[0];return (await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status,published_at) SELECT $1,organization_id,owner_id,agent_id,$2,'S01 synthetic linked published property',description,'sale','residential','CNY','123456.78','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id,version",[u.id,'s01-'+crypto.randomUUID()])).rows[0];});});
const body=(extra:any={})=>({version:0,subject:'S01 synthetic support request '+crypto.randomUUID(),description:'The verified synthetic reporter requests a review of a published property fact.',category:'Listing complaint',listing,attachments:[],consent:true,...extra});
async function asset(owner=buyer.id,extra:any={}){return transaction(workerActor,async c=>(await c.query("INSERT INTO media_assets(owner_id,object_key,mime,size,rights,visibility,purpose,status,scan_at,variants) VALUES($1,$2,$3,100,'Synthetic test evidence rights',$4,$5,$6,$7,$8) RETURNING id,version",[owner,'s01-fixture-'+crypto.randomUUID(),extra.mime||'image/png',extra.visibility||'private',extra.purpose||'photo',extra.status||'approved',extra.unscanned?null:new Date(),{display:'s01-private-display-'+crypto.randomUUID()}])).rows[0]);}
it('S01 reporter creates and retrieves its versioned complaint while original listing and immutable public history remain intact',async()=>{
 const r=req(),x=body(),opened=(await api().support(r,x)).data;expect(opened).toMatchObject({status:'open',version:1,assigned:false,historical:false});expect(opened.listing).toMatchObject(listing);expect(opened.activity).toHaveLength(1);expect(opened.activity[0]).toMatchObject({version:1,status:'open',message:null});expect((await api().support(r,x)).data.id).toBe(opened.id);expect((await api().supportDetail(req('GET'),opened.id)).data).toEqual(opened);expect((await api().cases(req('GET'),{})).data.items.some(r=>r.id===opened.id)).toBe(true);
 const unchanged=await transaction(workerActor,c=>c.query('SELECT status,version FROM listings WHERE id=$1',[listing.id]));expect(unchanged.rows[0]).toEqual({status:'published',version:listing.version});await expect(api(other).supportDetail(req('GET'),opened.id)).rejects.toMatchObject({status:404});expect((await api(other).cases(req('GET'),{})).data.items.some(r=>r.id===opened.id)).toBe(false);expect(JSON.stringify(opened)).not.toContain('actor_id');expect(JSON.stringify(opened)).not.toContain('user_id');
 await expect(api().support(req(),body({listing:{...listing,version:listing.version+1}}))).rejects.toMatchObject({status:409});await expect(api().support(req(),body({listing:null}))).rejects.toThrow();await expect(api().support(req(),body({version:1}))).rejects.toThrow();
});
it('S01 current owned scanned private attachments bind exact versions and other actors or invalid sources cannot access them',async()=>{
 const own=await asset(),opened=(await api().support(req(),body({attachments:[{assetId:own.id,version:own.version,label:'Synthetic private support photo'}]}))).data;expect(opened.attachments).toHaveLength(1);expect(opened.attachments[0].url).toContain('/support-cases/'+opened.id+'/attachments/');expect(JSON.stringify(opened)).not.toContain('s01-private-display');
 const source=async(a:Actor)=>transaction(a,async c=>(await c.query('SELECT support_attachment_file($1,$2) source',[opened.id,own.id])).rows[0].source);expect(await source(buyer)).toMatchObject({mime:'image/webp'});expect(await source(staff)).toMatchObject({mime:'image/webp'});expect(await source(other)).toBeNull();expect((await transaction(other,c=>c.query('SELECT * FROM support_case_attachments WHERE case_id=$1',[opened.id]))).rowCount).toBe(0);
 for(const invalid of [await asset(other.id),await asset(buyer.id,{visibility:'public'}),await asset(buyer.id,{status:'rejected'}),await asset(buyer.id,{unscanned:true}),await asset(buyer.id,{purpose:'panorama'})])await expect(api().support(req(),body({attachments:[{assetId:invalid.id,version:invalid.version,label:'Invalid attachment must refuse'}]}))).rejects.toMatchObject({status:404});await expect(api().support(req(),body({attachments:[{assetId:own.id,version:own.version+1,label:'Stale source'}]}))).rejects.toMatchObject({status:404});
 await expect(transaction(buyer,c=>c.query('INSERT INTO support_case_attachments(case_id,asset_id,asset_version,label,mime,actor_id) VALUES($1,$2,$3,$4,$5,$6)',[opened.id,own.id,own.version,'Late attachment must refuse','image/png',buyer.id]))).rejects.toThrow();
});
it('S01 current support triages to actual platform staff with a visible reply; stale, forged, foreign and invalid assignment writes deny',async()=>{
 const opened=(await api().support(req(),body({category:'General',listing:null}))).data,command={version:1,assigneeId:staff.id,publicReply:'The authorized support team will review your request.'},r=req('PATCH'),triaged=(await api(staff).updateSupport(r,opened.id,command)).data;expect(triaged).toMatchObject({version:2,status:'triaged',assigned:true,assigneeId:staff.id});expect((await api(staff).updateSupport(r,opened.id,command)).data.version).toBe(2);const own=(await api().supportDetail(req('GET'),opened.id)).data;expect(own.assigneeId).toBeNull();expect(own.publicReply).toBe(command.publicReply);expect(own.activity.map(h=>h.status)).toEqual(['open','triaged']);await expect(api(staff).updateSupport(req('PATCH'),opened.id,command)).rejects.toMatchObject({status:409});
 const fresh=(await api().support(req(),body({category:'General',listing:null}))).data;await expect(api(staff).updateSupport(req('PATCH'),fresh.id,{...command,assigneeId:other.id})).rejects.toMatchObject({status:404});for(const a of [buyer,{...other,roles:['support','admin']}])await expect(api(a).updateSupport(req('PATCH'),fresh.id,command)).rejects.toMatchObject({status:403});expect((await api(staff).supportAssignees(req('GET'))).data.some(r=>r.id===staff.id)).toBe(true);await expect(api(other).supportProfessionalDetail(req('GET'),fresh.id)).rejects.toMatchObject({status:403});
 expect((await transaction(staff,c=>c.query("UPDATE support_case_history SET public_message='Changed immutable source' WHERE case_id=$1",[opened.id]))).rowCount).toBe(0);await expect(transaction(staff,c=>c.query("UPDATE support_cases SET description='Changed original facts',version=version+1,updated_by=$2,updated_at=statement_timestamp() WHERE id=$1",[fresh.id,staff.id]))).rejects.toMatchObject({code:'23514'});
});
