import '../support/env';
import {it,expect,afterAll} from 'vitest';
import {createRequire} from 'node:module';
import type {FastifyRequest} from 'fastify';
import type {Identity} from '../../apps/api/src/platform/core';
import {AdministrationController} from '../../apps/api/src/administration/controller';
import {transaction,type Actor} from '../../packages/database/src/index';
import {supportCSV} from '../../apps/api/src/administration/support-cases';
const buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},other:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},staff:Actor={id:'00000000-0000-4000-8000-000000000009',orgId:null,roles:['support']},admin:Actor={id:'00000000-0000-4000-8000-000000000010',orgId:null,roles:['admin']};
const api=(a=buyer)=>new AdministrationController({actor:async()=>a} as unknown as Identity),req=(method='POST',url='/api/v1/support-cases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),body=()=>({version:0,subject:'S02 PRIVATE USER SUBJECT '+crypto.randomUUID(),description:'S02 PRIVATE USER DESCRIPTION must not enter analytics or metadata export.',category:'Account',listing:null,attachments:[],consent:true});
const {Pool}=createRequire(new URL('../../packages/database/package.json',import.meta.url))('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});afterAll(()=>fixtures.end());
async function triaged(){const opened=(await api().support(req(),body())).data;return (await api(staff).updateSupport(req('PATCH','/api/v1/ops/support-cases/'+opened.id),opened.id,{version:1,assigneeId:staff.id,publicReply:'The current support assignee will review this request.'})).data;}
const action=(id:string,x:any,a=staff,r=req('POST','/api/v1/ops/support-cases/'+id+'/actions'))=>api(a).supportAction(r,id,x),publicAction=(id:string,x:any,a=buyer,r=req('PATCH','/api/v1/support-cases/'+id))=>api(a).supportPublicChange(r,id,x);
it('S02 assigned support escalates and resolves while reporter timeline, comments and reopening exclude all private notes',async()=>{
 let r=await triaged();r=(await publicAction(r.id,{version:r.version,action:'comment',publicReply:'The original reporter supplies another public account detail.'})).data;const sentinel='S02 PRIVATE NOTE SENTINEL '+crypto.randomUUID();r=(await action(r.id,{version:r.version,action:'note',internalNote:sentinel})).data;expect(r.internalNotes?.[0].body).toBe(sentinel);expect(r.activity.at(-1)).toMatchObject({action:'status_updated',message:null,status:'triaged'});const own=(await api().supportDetail(req('GET'),r.id)).data;expect(JSON.stringify(own)).not.toContain(sentinel);expect(JSON.stringify(own)).not.toContain('internalNotes');expect((await transaction(buyer,c=>c.query('SELECT * FROM support_case_internal_notes WHERE case_id=$1',[r.id]))).rowCount).toBe(0);
 r=(await action(r.id,{version:r.version,action:'escalate',publicReply:'Escalating this account case for an authorized deeper review.'})).data;expect(r.status).toBe('escalated');r=(await action(r.id,{version:r.version,action:'resolve',publicReply:'The authorized support team completed this account review and resolved the request.'})).data;expect(r).toMatchObject({status:'resolved',canComment:false});const resolved=(await api().supportDetail(req('GET'),r.id)).data;expect(resolved.publicReply).toContain('resolved');expect(resolved.canReopen).toBe(true);expect(resolved.activity.map(h=>h.status)).toEqual(['open','triaged','triaged','triaged','escalated','resolved']);await expect(publicAction(r.id,{version:r.version,action:'comment',publicReply:'A resolved case needs reopening before a new comment.'})).rejects.toMatchObject({status:409});
 const command={version:r.version,action:'reopen',publicReply:'The original account issue persists after the recorded resolution.'},retry=req('PATCH','/api/v1/support-cases/'+r.id);const reopened=(await publicAction(r.id,command,buyer,retry)).data;expect(reopened).toMatchObject({status:'open',assigned:false,canReopen:false,version:7});expect((await publicAction(r.id,command,buyer,retry)).data.version).toBe(7);await expect(publicAction(r.id,{...command,version:7},other)).rejects.toMatchObject({status:404});await expect(action(r.id,{version:7,action:'note',internalNote:'A reopened unassigned case must be triaged first.'})).rejects.toMatchObject({status:403});
});
it('S02 current handoff transfers private-note access and future actions; immutable and standalone private writes refuse',async()=>{
 let r=await triaged();const sentinel='S02 PRIVATE HANDOFF SENTINEL';r=(await action(r.id,{version:r.version,action:'note',internalNote:sentinel})).data;await expect(transaction(staff,c=>c.query('INSERT INTO support_case_internal_notes(case_id,case_version,body,actor_id,at) SELECT id,version,$2,$3,updated_at FROM support_cases WHERE id=$1',[r.id,'Standalone private append must refuse.',staff.id]))).rejects.toMatchObject({code:'23514'});expect((await transaction(staff,c=>c.query("UPDATE support_case_internal_notes SET body='Changed immutable note' WHERE case_id=$1",[r.id]))).rowCount).toBe(0);
 r=(await action(r.id,{version:r.version,action:'assign',assigneeId:admin.id,publicReply:'Handing this case to the current authorized administrator.'})).data;expect(r.canAct).toBe(false);expect(r.internalNotes).toBeUndefined();expect((await transaction(staff,c=>c.query('SELECT * FROM support_case_internal_notes WHERE case_id=$1',[r.id]))).rowCount).toBe(0);expect((await api(admin).supportProfessionalDetail(req('GET'),r.id)).data.internalNotes?.[0].body).toBe(sentinel);await expect(action(r.id,{version:r.version,action:'resolve',publicReply:'The previous assignee cannot resolve this handoff.'})).rejects.toMatchObject({status:403});for(const a of [other,{...other,roles:['support','admin']}])await expect(action(r.id,{version:r.version,action:'note',internalNote:'Forged private support role must refuse.'},a)).rejects.toMatchObject({status:403});await expect(publicAction(r.id,{version:r.version,action:'note',internalNote:'Consumer route cannot accept private fields.'})).rejects.toThrow();
 r=(await action(r.id,{version:r.version,action:'resolve',publicReply:'The current authorized administrator resolves the transferred case.'},admin)).data;expect(r.status).toBe('resolved');await expect(action(r.id,{version:r.version,action:'note',internalNote:'A resolved case cannot accept a hidden append.'},admin)).rejects.toMatchObject({status:409});
});
it('S02 filtered bounded queue and complete metadata CSV omit private text and deny foreign-role exports; concurrent source versions serialize',async()=>{
 const r=await triaged(),commands=[publicAction(r.id,{version:2,action:'comment',publicReply:'First competing public account update.'}),publicAction(r.id,{version:2,action:'comment',publicReply:'Second competing public account update.'})],results=await Promise.allSettled(commands);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);expect((await api().supportDetail(req('GET'),r.id)).data.version).toBe(3);
 const page=(await api(staff).supportQueue(req('GET'),{status:'triaged',category:'Account',assigneeId:staff.id})).data;expect(page.items.some(x=>x.id===r.id)).toBe(true);expect(page.items.every(x=>x.status==='triaged'&&x.category==='Account'&&x.assigneeId===staff.id)).toBe(true);const csv=await transaction(staff,c=>supportCSV(c,{status:'triaged',category:'Account',assigneeId:staff.id}));expect(csv).toContain(r.id);expect(csv).not.toContain('S02 PRIVATE');expect(csv).not.toContain('actor_id');expect(csv).not.toContain('/attachments/');for(const a of [buyer,other,{...other,roles:['support','admin']}])await expect(transaction(a,c=>supportCSV(c,{}))).rejects.toMatchObject({status:403});await expect(api().cases(req('GET'),{assigneeId:staff.id})).rejects.toMatchObject({status:400});
 const imported=(await fixtures.query("INSERT INTO support_cases(user_id,subject,description,category) SELECT $1,'S02 trusted historical page '||n,'S02 original attribution unknown','Other' FROM generate_series(1,25) n RETURNING id",[buyer.id])).rows;const one=(await api(staff).supportQueue(req('GET'),{category:'Other',page:1})).data,two=(await api(staff).supportQueue(req('GET'),{category:'Other',page:2})).data;expect(one.items).toHaveLength(20);expect(two.items.length).toBeGreaterThan(0);const complete=await transaction(staff,c=>supportCSV(c,{category:'Other'}));for(const row of imported)expect(complete).toContain(row.id);expect(complete).toContain(two.items[0].id);
});
