import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),fixtures=new Pool({connectionString:process.env.MIGRATION_DATABASE_URL});
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {ManagementController} from '../../apps/api/src/management/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},foreign:Actor={id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['property_manager']},people:Actor[]=[],invites:string[]=[];let grant:string,grantVersion:number;
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a:Actor)=>new TenantLinksController(identity(a)),req=(method='POST',url='/api/v1/ops/tenant-invitations')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest);
beforeAll(async()=>{await transaction(workerActor,async c=>{for(let n=0;n<4;n++){const id=crypto.randomUUID();await c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P02 synthetic recipient',$4)",[id,'p02-'+id,id+'@example.test',n!==2]);people.push({id,orgId:null,roles:['consumer']});}const g=(await c.query("SELECT id,version FROM management_grants WHERE unit_id='10000000-0000-4000-8000-000000001060' AND organization_id=$1",[manager.orgId])).rows[0];grant=g.id;grantVersion=g.version;});});
const body=(p=people[0])=>({version:0,grantId:grant,grantVersion,name:'P02 synthetic tenant',email:p.id+'@example.test'});
async function invite(p=people[0]){const i=(await api(manager).invite(req(),body(p))).data;invites.push(i.id);return i;}
afterAll(async()=>{try{await transaction(workerActor,c=>c.query("UPDATE tenant_invitations SET status='cancelled',version=version+1 WHERE id=ANY($1::uuid[]) AND status='pending'",[invites]),fixtures);}finally{await fixtures.end();}});
it('P02 verified recipient accepts exact grant invitation once and reads own linked profile without enumerating others',async()=>{const r=req(),i=(await api(manager).invite(r,body())).data;invites.push(i.id);expect((await api(manager).invite(r,body())).data.id).toBe(i.id);expect((await api(people[0]).ownInvitations(req('GET'))).data.map(x=>x.id)).toContain(i.id);expect((await api(people[1]).ownInvitations(req('GET'))).data.map(x=>x.id)).not.toContain(i.id);await expect(api(people[1]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this linkage.'})).rejects.toMatchObject({status:404});const decision=req('PATCH','/api/v1/tenant-invitations/'+i.id),x={version:1,action:'accept',consent:true,reason:'Verified account accepts this linkage.'},accepted=(await api(people[0]).decide(decision,i.id,x)).data;expect(accepted).toMatchObject({status:'accepted',version:2});expect((await api(people[0]).decide(decision,i.id,x)).data.tenantId).toBe(accepted.tenantId);expect(accepted.activity.map((a:any)=>a.action)).toEqual(['invited','accepted']);expect((await api(people[0]).profile(req('GET'),accepted.tenantId)).data.email).toBe(body().email);await expect(api(people[1]).profile(req('GET'),accepted.tenantId)).rejects.toMatchObject({status:404});expect((await api(people[1]).profiles(req('GET'))).data).toHaveLength(0);expect((await new ManagementController(identity(manager)).tenants(req('GET'))).data.map(x=>x.id)).toContain(accepted.tenantId);expect((await new ManagementController(identity(foreign)).tenants(req('GET'))).data.map(x=>x.id)).not.toContain(accepted.tenantId);const counts=await transaction(workerActor,async c=>(await c.query("SELECT (SELECT count(*) FROM tenants WHERE organization_id=$1 AND user_id=$2)::int tenants,(SELECT count(*) FROM outbox WHERE aggregate_id=$3 AND kind='tenant.invitation_accepted')::int events",[manager.orgId,people[0].id,i.id])).rows[0]);expect(counts).toEqual({tenants:1,events:1});});
it('P02 foreign unit grant, forged manager, unverified email, missing consent and stale invitation are denied',async()=>{await expect(api(foreign).invite(req(),body(people[1]))).rejects.toMatchObject({status:403});await expect(api(manager).invite(req(),{...body(people[1]),grantVersion:999})).rejects.toMatchObject({status:409});const i=await invite(people[2]);expect((await api(people[2]).ownInvitations(req('GET'))).data).toHaveLength(0);await expect(api(people[2]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Attempted unverified account acceptance.'})).rejects.toMatchObject({status:404});await expect(api(people[0]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',reason:'Consent omitted by account.'})).rejects.toMatchObject({name:'ZodError'});await expect(transaction(manager,c=>c.query("INSERT INTO tenants(organization_id,user_id,name,email) VALUES($1,$2,'Forged link','forged@example.test')",[manager.orgId,people[1].id]))).rejects.toBeDefined();});
it('P02 cancellation and expiry keep histories while blocking account linkage; recipient may decline',async()=>{let i=await invite(people[1]);expect((await api(manager).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'cancel',reason:'Manager cancelled this invitation.'})).data.status).toBe('cancelled');await expect(api(people[1]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Attempted cancelled invitation.'})).rejects.toMatchObject({status:409});i=await invite(people[1]);await transaction(workerActor,c=>c.query("UPDATE tenant_invitations SET expires_at=now()-interval '1 second',version=version+1 WHERE id=$1",[i.id]),fixtures);await expect(api(people[1]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:2,action:'accept',consent:true,reason:'Attempted expired invitation.'})).rejects.toMatchObject({status:409});expect((await api(people[1]).ownInvitations(req('GET'))).data.find(x=>x.id===i.id).status).toBe('expired');await api(manager).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:2,action:'cancel',reason:'Manager cancelled expired invitation.'});i=await invite(people[1]);expect((await api(people[1]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'decline',reason:'Recipient declined tenant account linkage.'})).data.status).toBe('declined');expect((await api(people[1]).profiles(req('GET'))).data).toHaveLength(0);});

it('P02 current private-property invitation exposes only its community context and revoked authority blocks acceptance; real foreign manager cannot link it',async()=>{const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths) SELECT community_id,organization_id,'88.50',2,1,1 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version")).rows[0];const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,status) SELECT $1,organization_id,'00000000-0000-4000-8000-000000000002',agent_id,$2,'P02 private property invitation fixture',description,'sale','residential','CNY','2400000.75','draft' FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,'p02-private-'+crypto.randomUUID()])).rows[0];const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,'00000000-0000-4000-8000-000000000002','recorded_listing',$2) RETURNING id",[unit.id,listing.id])).rows[0];const org=crypto.randomUUID();await c.query("INSERT INTO organizations(id,name,type) VALUES($1,'P02 foreign real manager','manager')",[org]);await c.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,'property_manager')",[people[1].id,org]);return {unit,source,org};});const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:1,organizationId:manager.orgId,expiresAt:'2030-12-31T00:00:00.000Z',consent:true})).data;const input={...body(people[3]),grantId:g.id,grantVersion:g.version};await expect(api({...people[1],orgId:f.org,roles:['property_manager']}).invite(req(),input)).rejects.toMatchObject({status:404});const i=(await api(manager).invite(req(),input)).data;invites.push(i.id);const read=(await api(people[3]).ownInvitations(req('GET'))).data.find(x=>x.id===i.id);expect(read).toMatchObject({unitId:f.unit.id,community:g.community});expect(JSON.stringify(read)).not.toContain('private_address');await transaction(workerActor,c=>c.query("UPDATE owner_unit_grants SET status='revoked',version=version+1 WHERE id=$1",[f.source.id]));await expect(api(people[3]).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Attempted acceptance after authority ended.'})).rejects.toBeDefined();expect((await api(people[3]).profiles(req('GET'))).data).toHaveLength(0);expect((await api(manager).invitations(req('GET'))).data.some(x=>x.id===i.id)).toBe(false);});
