import {TenantLeasesController} from '../../apps/api/src/management/tenant-leases';
import {DepositsController} from '../../apps/api/src/management/deposits';
import {FinancialReversalsController} from '../../apps/api/src/management/financial-reversals';
import {PaymentAllocationsController} from '../../apps/api/src/management/payment-allocations';
import {ManagementController} from '../../apps/api/src/management/controller';
import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ManagementGrantsController} from '../../apps/api/src/management/grants';
import {TenantLinksController} from '../../apps/api/src/management/tenant-links';
import {PaymentEvidenceController} from '../../apps/api/src/management/payment-evidence';
import {LeaseDraftsController} from '../../apps/api/src/management/lease-drafts';
import type {Identity} from '../../apps/api/src/platform/core';
const owner:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},manager:Actor={id:'00000000-0000-4000-8000-000000000004',orgId:'10000000-0000-4000-8000-000000000002',roles:['property_manager','finance']},tenant:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),api=(a=manager)=>new LeaseDraftsController(identity(a)),req=(method='POST',url='/api/v1/ops/leases')=>({method,url,headers:{'idempotency-key':crypto.randomUUID()}} as unknown as FastifyRequest),units:string[]=[],grants:string[]=[],leases:string[]=[],listings:string[]=[];
beforeAll(async()=>{await transaction(workerActor,c=>c.query("INSERT INTO profiles(id,subject,email,display_name,email_verified) VALUES($1,$2,$3,'P11 verified synthetic tenant',true)",[tenant.id,'p11-'+tenant.id,tenant.id+'@example.test']));});
async function fixture(parent?:string){const f=await transaction(workerActor,async c=>{const unit=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,'88.50',2,1,1,$1,$2,$3 FROM units WHERE id='10000000-0000-4000-8000-000000001000' RETURNING id,version",[parent||null,parent?'room':'property',parent?'P11 room '+crypto.randomUUID().slice(0,8):null])).rows[0];units.push(unit.id);const listing=(await c.query("INSERT INTO listings(unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,published_at) SELECT $1,organization_id,$2,agent_id,$3,'P11 synthetic rental offer',description,'rent','residential','CNY','1234.56','month','published',now() FROM listings WHERE id='10000000-0000-4000-8000-000000002000' RETURNING id",[unit.id,owner.id,'p11-'+crypto.randomUUID()])).rows[0];listings.push(listing.id);await c.query('INSERT INTO rental_terms(listing_id,rental_mode,billing_period,currency) VALUES($1,$2,$3,$4)',[listing.id,parent?'shared':'entire','month','CNY']);const source=(await c.query("INSERT INTO owner_unit_grants(unit_id,owner_id,source,source_listing_id) VALUES($1,$2,'recorded_listing',$3) RETURNING version",[unit.id,owner.id,listing.id])).rows[0];return {unit,listing,source};});const g=(await new ManagementGrantsController(identity(owner)).create(req('POST','/api/v1/me/management-grants'),{version:0,unitId:f.unit.id,unitVersion:f.unit.version,ownerGrantVersion:f.source.version,organizationId:manager.orgId,expiresAt:'2036-12-31T00:00:00.000Z',consent:true})).data;grants.push(g.id);const links=new TenantLinksController(identity(manager)),i=(await links.invite(req('POST','/api/v1/ops/tenant-invitations'),{version:0,grantId:g.id,grantVersion:g.version,name:'P11 synthetic tenant',email:tenant.id+'@example.test'})).data;const accepted=(await new TenantLinksController(identity(tenant)).decide(req('PATCH','/api/v1/tenant-invitations/'+i.id),i.id,{version:1,action:'accept',consent:true,reason:'Verified account accepts this synthetic property link.'})).data;return {...f,g,tenantId:accepted.tenantId};}
async function draft(f:Awaited<ReturnType<typeof fixture>>,startDate='2034-01-01',endDate='2034-12-31',documents:{assetId:string;version:number;label:string}[]=[]){const options=(await api().options(req('GET'),f.unit.id)).data,l=(await api().create(req(),{version:0,unitId:f.unit.id,tenantId:f.tenantId,unitVersion:options.unitVersion,grantVersion:options.grantVersion,tenantVersion:options.tenants.find((t:any)=>t.id===f.tenantId).version,startDate,endDate,rent:'1234.56',currency:'CNY',rentPeriod:'month',dueDay:5,documents})).data;leases.push(l.id);return l;}
const activation=(l:any)=>({version:l.version,unitVersion:l.unitVersion,grantVersion:l.grantVersion,tenantVersion:l.tenantVersion,confirm:true});
afterAll(async()=>{await transaction(workerActor,async c=>{await c.query("UPDATE leases SET status='ended',version=version+1 WHERE id=ANY($1::uuid[])",[leases]);await c.query("UPDATE management_grants SET status='revoked',version=version+1 WHERE id=ANY($1::uuid[])",[grants]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[listings]);});});
const payments=(a=manager)=>new PaymentEvidenceController(identity(a));
async function active(f:Awaited<ReturnType<typeof fixture>>){const l=await draft(f,'2028-01-01','2028-12-31');return (await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l))).data;}
async function body(id:string){const o=(await payments().options(req('GET'),id)).data;return {version:0,leaseId:id,...o,amount:'100.10',source:'bank_statement',reference:'Verified synthetic bank statement receipt'};}
const postBody=(p:any)=>({version:p.version,leaseVersion:p.leaseVersion,unitVersion:p.unitVersion,grantVersion:p.grantVersion,confirm:true});
async function financial(amount='250.25',charged='200.20'){const f=await fixture(),l=await active(f),p=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(l.id),amount})).data,posted=(await payments().post(req('POST','/api/v1/ops/payment-records/'+p.id+'/post'),p.id,postBody(p))).data,ch=await transaction(workerActor,async c=>(await c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency) VALUES($1,$2,'2028-01-01','2028-01-05',$3,'CNY') RETURNING id,version",[l.id,manager.orgId,charged])).rows[0]);return {...f,l,p:posted,ch};}

const portal=(a=tenant)=>new TenantLeasesController(identity(a)),allocations=()=>new PaymentAllocationsController(identity(manager)),deposits=()=>new DepositsController(identity(manager)),reversals=()=>new FinancialReversalsController(identity(manager));
async function allocated(f:Awaited<ReturnType<typeof financial>>){const l=(await allocations().ledger(req('GET'),f.l.id,{})).data;return allocations().create(req('POST','/api/v1/ops/allocations'),{version:0,leaseId:f.l.id,leaseVersion:l.leaseVersion,unitVersion:l.unitVersion,grantVersion:l.grantVersion,paymentId:f.p.id,paymentVersion:f.p.version,chargeId:f.ch.id,chargeVersion:f.ch.version,amount:'50.05',currency:'CNY',confirm:true});}
async function deposit(id:string){const l=(await deposits().ledger(req('GET'),id,{})).data;return deposits().create(req('POST','/api/v1/ops/deposits'),{version:0,leaseId:id,leaseVersion:l.leaseVersion,unitVersion:l.unitVersion,grantVersion:l.grantVersion,liabilityVersion:l.liabilityVersion,kind:'received',direction:'increase',amount:'100.10',currency:'CNY',reason:'P11 PRIVATE OWNER NOTE SENTINEL bank account must remain staff private.',confirm:true});}
it('P11 linked tenant sees exact reconciled own balance without private staff references, actor/org fields or draft payments',async()=>{const f=await financial();await allocated(f);await deposit(f.l.id);const draftPayment=(await payments().create(req('POST','/api/v1/ops/payment-records'),{...await body(f.l.id),amount:'999.99',reference:'P11 PRIVATE OWNER NOTE SENTINEL private unposted receipt'})).data;expect(draftPayment.status).toBe('draft');const r=(await portal().read(req('GET'),f.l.id,{})).data;expect(r.totals).toEqual({charges:'200.20',recordedPayments:'250.25',allocated:'50.05',outstanding:'150.15',credit:'200.20',depositHeld:'100.10'});expect(r.payments).toHaveLength(1);expect(r.documents).toEqual([]);expect(JSON.stringify(r)).not.toMatch(/PRIVATE OWNER NOTE SENTINEL|organizationId|organization_id|actorId|reference|reason|object_key|owner_id/);expect(r.note).toContain('no funds are transferred');const list=(await portal().list(req('GET'),{})).data;expect(list.items.some((l:any)=>l.id===f.l.id)).toBe(true);const legacy=(await new ManagementController(identity(tenant)).statement(req('GET'),f.l.id)).data;expect(JSON.stringify(legacy)).not.toContain('PRIVATE OWNER NOTE SENTINEL');expect(legacy.deposits[0].reason).toBe('Recorded deposit liability evidence');},90000);
it('P11 foreign users, owners and guessed finance personas cannot read another linked lease or its document',async()=>{const f=await fixture(),l=await active(f),foreign:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']};for(const a of [foreign,owner,{...foreign,orgId:manager.orgId,roles:['finance']}]){await expect(portal(a).read(req('GET'),l.id,{})).rejects.toMatchObject({status:404});await expect(portal(a).download(req('GET'),l.id,crypto.randomUUID(),{} as any)).rejects.toMatchObject({status:404});expect((await portal(a).list(req('GET'),{})).data.items.some((x:any)=>x.id===l.id)).toBe(false);}},90000);
it('P11 documents are private while draft, then exact approved bound PDF is readable only on its linked lease and revoked asset versions deny',async()=>{const f=await fixture(),asset=(await transaction(workerActor,c=>c.query("INSERT INTO media_assets(owner_id,object_key,mime,size,rights,visibility,purpose,status,scan_at) VALUES($1,$2,'application/pdf',100,'P11 synthetic DB-only scanned metadata fixture','private','document','approved',now()) RETURNING id,version",[manager.id,crypto.randomUUID()]))).rows[0],l=await draft(f,'2028-01-01','2028-12-31',[{assetId:asset.id,version:asset.version,label:'Synthetic signed tenancy terms'}]);expect((await portal().list(req('GET'),{})).data.items.some((r:any)=>r.id===l.id)).toBe(false);await expect(portal().read(req('GET'),l.id,{})).rejects.toMatchObject({status:404});expect((await transaction(tenant,c=>c.query('SELECT * FROM tenant_lease_document_lock($1,$2)',[l.id,asset.id]))).rowCount).toBe(0);await api().activate(req('POST','/api/v1/ops/leases/'+l.id+'/activate'),l.id,activation(l));const r=(await portal().read(req('GET'),l.id,{})).data;expect(r.documents).toEqual([{id:asset.id,version:asset.version,label:'Synthetic signed tenancy terms',url:'/api/v1/tenant/leases/'+l.id+'/documents/'+asset.id}]);expect((await transaction(tenant,c=>c.query('SELECT * FROM tenant_lease_document_lock($1,$2)',[l.id,asset.id]))).rowCount).toBe(1);const other=await active(await fixture());await expect(portal().download(req('GET'),other.id,asset.id,{} as any)).rejects.toMatchObject({status:404});await transaction(workerActor,c=>c.query("UPDATE media_assets SET status='rejected',version=version+1 WHERE id=$1",[asset.id]));expect((await portal().read(req('GET'),l.id,{})).data.documents).toEqual([]);await expect(portal().download(req('GET'),l.id,asset.id,{} as any)).rejects.toMatchObject({status:404});},90000);
it('P11 reversals reconcile own recorded balance and retained history without exposing correction reasons',async()=>{const f=await financial();await allocated(f);const payment=(await reversals().read(req('GET'),'payment',f.p.id)).data,x={version:payment.version,leaseVersion:payment.leaseVersion,unitVersion:payment.unitVersion,grantVersion:payment.grantVersion,reason:'P11 PRIVATE OWNER NOTE SENTINEL bookkeeping correction.',confirm:true};await reversals().reversePayment(req('POST','/api/v1/ops/payment-records/'+f.p.id+'/reverse'),f.p.id,x);let r=(await portal().read(req('GET'),f.l.id,{})).data;expect(r.totals).toMatchObject({recordedPayments:'0.00',allocated:'0.00',outstanding:'200.20',credit:'0.00'});expect(r.payments).toHaveLength(2);expect(r.payments.find((p:any)=>p.id===f.p.id).reversed).toBe(true);const charge=(await reversals().read(req('GET'),'charge',f.ch.id)).data;await reversals().reverseCharge(req('POST','/api/v1/ops/charges/'+f.ch.id+'/reverse'),f.ch.id,{...x,version:charge.version});r=(await portal().read(req('GET'),f.l.id,{})).data;expect(r.totals).toMatchObject({charges:'0.00',outstanding:'0.00'});expect(r.charges).toHaveLength(2);expect(JSON.stringify(r)).not.toContain('PRIVATE OWNER NOTE SENTINEL');},90000);
it('P11 bounded history pages keep full totals, tenant-link changes deny immediately and revoked professional grant does not erase tenant contract access',async()=>{const f=await fixture(),l=await active(f);await transaction(workerActor,c=>c.query("INSERT INTO charges(lease_id,organization_id,period,due_date,amount,currency,kind) SELECT $1,$2,'2028-01-01','2028-01-05','1.01','CNY','p11-synthetic-'||n FROM generate_series(1,21) n",[l.id,manager.orgId]));const first=(await portal().read(req('GET'),l.id,{page:1})).data,second=(await portal().read(req('GET'),l.id,{page:2})).data;expect(first.charges).toHaveLength(20);expect(second.charges).toHaveLength(1);expect(first.counts.charges).toBe(21);expect(second.totals.charges).toBe('21.21');await new ManagementGrantsController(identity(owner)).update(req('PATCH','/api/v1/me/management-grants/'+f.g.id),f.g.id,{action:'revoke',version:1,reason:'Professional grant revoked without changing the tenant contract.'});expect((await portal().read(req('GET'),l.id,{})).data.totals.charges).toBe('21.21');await transaction(workerActor,c=>c.query("UPDATE tenants SET user_id='00000000-0000-4000-8000-000000000001',version=version+1 WHERE id=$1",[f.tenantId]));try{await expect(portal().read(req('GET'),l.id,{})).rejects.toMatchObject({status:404});expect((await portal().list(req('GET'),{})).data.items.some((r:any)=>r.id===l.id)).toBe(false);}finally{await transaction(workerActor,c=>c.query('UPDATE tenants SET user_id=$2,version=version+1 WHERE id=$1',[f.tenantId,tenant.id]));}},90000);
