import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ViewingAvailabilityController} from '../../apps/api/src/engagement/viewing-availability';
import {ViewingCalendarController} from '../../apps/api/src/engagement/viewing-calendar';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import {ViewingReminderService,ViewingReminderWorkerController} from '../../apps/api/src/engagement/viewing-reminders';
import {CrmExportsController,csvCell,csvDocument} from '../../apps/api/src/engagement/crm-exports';
import {createAlertMailSender} from '../../apps/api/src/engagement/mail-sender';
import {NotificationsController} from '../../apps/api/src/engagement/notifications';
import {deliverViewingReminder} from '../../apps/worker/src/viewing-reminders';
import {createRequire} from 'node:module';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',listing=crypto.randomUUID(),agent=crypto.randomUUID(),pro:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:org,roles:['agent']},buyer:Actor={id:crypto.randomUUID(),orgId:null,roles:['consumer']},outsider:Actor={id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agent']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),calendar=(a:Actor)=>new ViewingCalendarController(identity(a)),engagement=(a:Actor)=>new EngagementController(identity(a)),availability=new ViewingAvailabilityController(identity(pro)),req=(url='/api/v1/viewings',key=crypto.randomUUID())=>({method:'POST',url,headers:{'idempotency-key':key}} as unknown as FastifyRequest);
const settings={version:0,listingVersion:1,agentId:agent,status:'active',durationMinutes:60,bufferMinutes:15,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'};let date:string;
const instant=(hour:string)=>new Date(date+'T'+hour+':00+08:00').toISOString();
async function input(){const s=(await availability.slots({listingId:listing,date,days:1})).data;return {version:0,listingId:listing,listingVersion:s.listingVersion,scheduleVersion:s.scheduleVersion!,agentId:agent,startAt:instant('09:00')};}
async function confirmed(){const x=await input(),row=(await engagement(buyer).book(req(),x)).data;return (await engagement(pro).confirm(req('/ops/viewings/'+row.id+'/confirm'),row.id,{version:row.version,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion})).data;}
async function cleanup(){await transaction(workerActor,c=>c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=$1 AND status IN('requested','confirmed')",[listing]));}
beforeAll(async()=>{date=new Date(Date.now()+86400000).toISOString().slice(0,10);await transaction(workerActor,async c=>{await c.query("INSERT INTO profiles(id,subject,display_name,email,email_verified) VALUES($1,$2,'L06 fixture',$3,true)",[buyer.id,'l06-'+buyer.id,'viewing-'+buyer.id+'@example.test']);await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'L06 synthetic calendar agent',$4,'Synthetic booking calendar acceptance fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,pro.id,org,'l06-'+agent]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,'L06 synthetic calendar property','Synthetic booking calendar fixture','sale','residential','CNY','2100000.25','published')",[listing,org,agent,'l06-'+listing]);});await availability.save(req(),listing,settings);});
afterAll(async()=>{try{await cleanup();await transaction(workerActor,async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[listing]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}finally{await transaction(workerActor,c=>c.query("UPDATE profiles SET state='archived' WHERE id=$1",[buyer.id]));await pool.end();}});
const service=new ViewingReminderService();
async function reminder(viewing:string){return transaction(workerActor,async c=>(await c.query('SELECT * FROM viewing_reminders WHERE viewing_id=$1 ORDER BY booking_version DESC LIMIT 1',[viewing])).rows[0]);}
async function accelerate(id:string){await transaction(workerActor,c=>c.query("UPDATE viewing_reminders SET due_at=now()-interval '1 second',updated_at=now()-interval '2 minutes' WHERE id=$1",[id]));}
async function mailCount(id:string){return(await fetch('http://mail:8025/api/v1/search?query='+encodeURIComponent('message-id:viewing-'+id+'@'+new URL(process.env.PUBLIC_WEB_URL!).hostname)).then(r=>r.json())).messages_count;}
async function queueDelivery(id:string){const require=createRequire(new URL('../../apps/worker/package.json',import.meta.url)),{Queue,Worker,QueueEvents}=require('bullmq'),redis=new URL(process.env.REDIS_URL!),connection={host:redis.hostname,port:Number(redis.port)||6379,maxRetriesPerRequest:null},name='l06-'+crypto.randomUUID(),queue=new Queue(name,{connection}),events=new QueueEvents(name,{connection}),worker=new Worker(name,(job:any)=>deliverViewingReminder(job.data.id),{connection});try{await events.waitUntilReady();const job=await queue.add('viewing-reminder',{id},{attempts:5,backoff:{type:'exponential',delay:100}});return await job.waitUntilFinished(events,20000);}finally{await worker.close();await queue.obliterate({force:true});await events.close();await queue.close();}}
it('L06 confirmation schedules one versioned reminder; actual BullMQ and SMTP receipt replay produce one email and one native notification',async()=>{const row=await confirmed();try{const r=await reminder(row.id);expect(r).toMatchObject({booking_version:row.version,status:'queued',attempts:0});expect(r.due_at.getTime()).toBeGreaterThanOrEqual(row.start_at.getTime()-86400000);expect((await transaction(workerActor,c=>c.query('SELECT count(*)::int n FROM viewing_reminders WHERE viewing_id=$1',[row.id]))).rows[0].n).toBe(1);await accelerate(r.id);expect(await queueDelivery(r.id)).toMatchObject({status:'accepted',attempts:1});await queueDelivery(r.id);expect(await mailCount(r.id)).toBe(1);const notices=(await new NotificationsController(identity(buyer)).read(req())).data.filter(n=>n.title.startsWith('Upcoming viewing'));expect(notices).toHaveLength(1);expect(notices[0]).toMatchObject({link:'/account/viewings',deliveryStatus:'accepted'});}finally{await cleanup();}});
it('L06 cancellation invalidates queued and failed reminders and all stale retries send no email',async()=>{for(const failed of [false,true]){const row=await confirmed();try{const r=await reminder(row.id);await accelerate(r.id);if(failed){const outage=new ViewingReminderService({lookup:async()=>{throw Error('provider outage');},send:async()=>{throw Error('must not send');}});expect((await outage.deliver(r.id,r.version)).data).toMatchObject({status:'failed',errorCode:'MAIL_UNCONFIRMED',acceptedAt:null});}await engagement(buyer).cancel(req(),row.id,{version:row.version});expect((await reminder(row.id)).status).toBe('cancelled');await service.deliver(r.id,r.version);await queueDelivery(r.id);expect(await mailCount(r.id)).toBe(0);}finally{await cleanup();}}});
it('L06 lost post-SMTP acknowledgement reconciles the frozen provider receipt without duplicate sending',async()=>{const row=await confirmed();try{const r=await reminder(row.id);await accelerate(r.id);await transaction(workerActor,c=>c.query('UPDATE viewing_reminders SET attempts=4 WHERE id=$1',[r.id]));const crashing=new ViewingReminderService(createAlertMailSender(),async()=>{throw Error('SIMULATED_AFTER_ACCEPTANCE');});await expect(crashing.deliver(r.id,r.version)).rejects.toThrow('SIMULATED_AFTER_ACCEPTANCE');expect(await mailCount(r.id)).toBe(1);expect((await reminder(row.id)).status).toBe('processing');await accelerate(r.id);expect((await service.deliver(r.id,(await reminder(row.id)).version)).data.status).toBe('accepted');expect(await mailCount(r.id)).toBe(1);}finally{await cleanup();}});
it('L06 rescheduling invalidates the former booking job and fresh confirmation schedules the new version; unsigned service calls and private table reads fail',async()=>{const row=await confirmed();try{const old=await reminder(row.id),x=await input();await calendar(buyer).reschedule(req(),row.id,{version:row.version,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion,startAt:instant('11:00')});expect((await reminder(row.id)).status).toBe('cancelled');await service.deliver(old.id,old.version);expect(await mailCount(old.id)).toBe(0);await engagement(pro).confirm(req(),row.id,{version:3,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion});expect(await reminder(row.id)).toMatchObject({booking_version:4,status:'queued'});await expect(new ViewingReminderWorkerController().due(req())).rejects.toMatchObject({status:401});expect((await transaction(buyer,c=>c.query('SELECT id,payload FROM viewing_reminders WHERE viewing_id=$1',[row.id]))).rows).toEqual([]);}finally{await cleanup();}});
it('L06 scoped reports share actual CRM filters, exclude foreign assignments and private note/message content, and neutralize all formula cells',async()=>{const lead=crypto.randomUUID(),text='L06'+crypto.randomUUID(),name=' =HYPERLINK("https://invalid.test","'+text+'")',row=await confirmed();try{await transaction(workerActor,c=>c.query("INSERT INTO leads(id,user_id,organization_id,resource_id,resource_type,agent_id,name,email,phone,message) VALUES($1,$2,$3,$4,'listing',$5,$6,'fixture@example.test','+86123456789','PRIVATE MESSAGE NOT EXPORTED')",[lead,buyer.id,org,listing,agent,name]));const exports=new CrmExportsController(identity(pro)),csv=(await exports.leads(req(),{text})).data;expect(csv).toMatchObject({scope:'assigned',records:1});expect(csv.content).toContain(csvCell(name));expect(csv.content).toContain('"\'+86123456789"');expect(csv.content).not.toContain('PRIVATE MESSAGE');expect((await new CrmExportsController(identity(outsider)).leads(req(),{text})).data.records).toBe(0);const own=(await exports.viewings(req(),{from:date,to:date})).data;expect(own.content).toContain(row.id);expect(own.content).toContain('Asia/Shanghai');expect((await new CrmExportsController(identity(outsider)).viewings(req(),{from:date,to:date})).data.content).not.toContain(row.id);expect(()=>csvDocument(['Header'],[['=1+1']])).not.toThrow();for(const value of ['=1+1','+SUM(1,2)','-1+1','@SUM(1)','\t=1','\r=1','\n=1','  =1'])expect(csvCell(value)).toBe('"\''+value+'"');await expect(exports.leads(req(),{page:1})).rejects.toBeDefined();}finally{await transaction(workerActor,c=>c.query('DELETE FROM leads WHERE id=$1',[lead]));await cleanup();}});
it('L06 transactional reminders never email unverified accounts, and inactive accounts receive no reminder',async()=>{for(const active of [true,false]){const row=await confirmed();try{const r=await reminder(row.id);await accelerate(r.id);await transaction(workerActor,c=>c.query("UPDATE profiles SET email_verified=false,state=$2 WHERE id=$1",[buyer.id,active?'active':'archived']));const result=(await service.deliver(r.id,r.version)).data;expect(result.status).toBe(active?'in_app':'cancelled');expect(result.acceptedAt).toBeNull();expect(await mailCount(r.id)).toBe(0);}finally{await transaction(workerActor,c=>c.query("UPDATE profiles SET email_verified=true,state='active' WHERE id=$1",[buyer.id]));await cleanup();}}});
