import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ViewingAvailabilityController} from '../../apps/api/src/engagement/viewing-availability';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',listing=crypto.randomUUID(),otherListing=crypto.randomUUID(),agent=crypto.randomUUID(),professional:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:org,roles:['agent']},buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},other:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']};
const controller=(actor:Actor)=>new EngagementController({actor:async()=>actor} as unknown as Identity),availability=new ViewingAvailabilityController({actor:async()=>professional} as unknown as Identity),bookings=controller(buyer),ops=controller(professional),req=(url='/api/v1/viewings',key=crypto.randomUUID())=>({method:'POST',url,headers:{'idempotency-key':key}} as unknown as FastifyRequest);
const settings={version:0,listingVersion:1,agentId:agent,status:'active',durationMinutes:45,bufferMinutes:30,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'};let date:string;
async function input(local='09:00',id=listing){const s=(await availability.slots({listingId:id,date,days:1})).data;return {version:0,listingId:id,listingVersion:s.listingVersion,scheduleVersion:s.scheduleVersion!,agentId:s.agentId!,startAt:new Date(date+'T'+local+':00+08:00').toISOString()};}
async function cancel(actor:Actor,row:any){return controller(actor).cancel(req('/api/v1/viewings/'+row.id+'/cancel'),row.id,{version:row.version});}
beforeAll(async()=>{date=new Date(Date.now()+86400000).toISOString().slice(0,10);await transaction(workerActor,async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'L04 synthetic booking agent',$4,'Synthetic transactional reservation fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,professional.id,org,'l04-'+agent]);for(const id of [listing,otherListing])await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,'L04 synthetic booking property','Synthetic current availability fixture','sale','residential','CNY','2100000.25','published')",[id,org,agent,'l04-'+id]);});await availability.save(req(),listing,settings);await availability.save(req(),otherListing,{...settings,bufferMinutes:0});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=ANY($1::uuid[]) AND status IN('requested','confirmed')",[[listing,otherListing]]);await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=ANY($1::uuid[])",[[listing,otherListing]]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}finally{await pool.end();}});
it('L04 a current slot reserves its configured duration once; lost-response retries preserve the same booking and event',async()=>{const x=await input(),request=req(),r=await bookings.book(request,x);try{expect(r.data).toMatchObject({user_id:buyer.id,agent_id:agent,status:'requested',version:1,listing_version:1,availability_version:1,property_zone:'Asia/Shanghai',buffer_minutes:30});expect(r.data.end_at.getTime()-r.data.start_at.getTime()).toBe(45*60000);expect(await bookings.book(request,x)).toEqual(JSON.parse(JSON.stringify(r)));await expect(bookings.book(request,{...x,startAt:new Date(date+'T04:00:00Z').toISOString()})).rejects.toMatchObject({status:409});await transaction(workerActor,async c=>{expect((await c.query('SELECT count(*)::int n FROM viewings WHERE id=$1',[r.data.id])).rows[0].n).toBe(1);expect((await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='viewing.requested'",[r.data.id])).rows[0].n).toBe(1);});}finally{await cancel(buyer,r.data);}});
it('L04 concurrent actual consumers yield one accepted reservation and one conflict',async()=>{const x=await input(),outcomes=await Promise.allSettled([bookings.book(req(),x),controller(other).book(req(),x)]);expect(outcomes.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(outcomes.filter(r=>r.status==='rejected').map(r=>(r as PromiseRejectedResult).reason.status)).toEqual([409]);const winner=(outcomes.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value.data;try{expect((await availability.slots({listingId:listing,date,days:1})).data.slots.some(s=>s.startAt===x.startAt)).toBe(false);expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM viewings WHERE listing_id=$1 AND status IN('requested','confirmed')",[listing]))).rows[0].n).toBe(1);}finally{await cancel(winner.user_id===buyer.id?buyer:other,winner);}});
it('L04 stale resource/availability/agent, off-cadence, outside hours, past and private-blocked requests fail without reservation',async()=>{const x=await input();await expect(bookings.book(req(),{...x,listingVersion:99})).rejects.toMatchObject({status:409});await expect(bookings.book(req(),{...x,scheduleVersion:99})).rejects.toMatchObject({status:409});await expect(bookings.book(req(),{...x,agentId:crypto.randomUUID()})).rejects.toMatchObject({status:409});await expect(bookings.book(req(),{...x,startAt:new Date(date+'T09:07:00+08:00').toISOString()})).rejects.toMatchObject({status:409});await expect(bookings.book(req(),{...x,startAt:new Date(date+'T18:00:00+08:00').toISOString()})).rejects.toMatchObject({status:409});await expect(bookings.book(req(),{...x,startAt:'2020-01-01T01:00:00.000Z'})).rejects.toMatchObject({status:400});const block=await availability.block(req(),listing,{version:0,listingVersion:1,scheduleVersion:1,startLocal:date+'T09:00',endLocal:date+'T10:00',reason:'Private L04 unavailable interval'});try{await expect(bookings.book(req(),x)).rejects.toMatchObject({status:409});}finally{await availability.cancelBlock(req(),listing,block.data.id,{version:1,listingVersion:1,scheduleVersion:1});}expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM viewings WHERE listing_id=$1 AND status IN('requested','confirmed')",[listing]))).rows[0].n).toBe(0);});
it('L04 only the current assigned professional confirms once; owning cancellation is versioned and releases capacity',async()=>{const x=await input(),r=await bookings.book(req(),x),body={version:1,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion},request=req('/api/v1/ops/viewings/'+r.data.id+'/confirm');await expect(bookings.confirm(request,r.data.id,body)).rejects.toMatchObject({status:403});const foreign=controller({id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agent']});await expect(foreign.confirm(request,r.data.id,body)).rejects.toMatchObject({status:404});await expect(transaction(buyer,c=>c.query("UPDATE viewings SET status='confirmed',version=version+1 WHERE id=$1",[r.data.id]))).rejects.toMatchObject({code:'42501'});const confirmed=await ops.confirm(request,r.data.id,body);expect(confirmed.data).toMatchObject({status:'confirmed',version:2});expect(await ops.confirm(request,r.data.id,body)).toEqual(JSON.parse(JSON.stringify(confirmed)));await expect(controller(other).cancel(req(),r.data.id,{version:2})).rejects.toMatchObject({status:404});await expect(bookings.cancel(req(),r.data.id,{version:1})).rejects.toMatchObject({status:409});const cancelled=await cancel(buyer,confirmed.data);expect(cancelled.data).toMatchObject({status:'cancelled',version:3});expect((await availability.slots({listingId:listing,date,days:1})).data.slots.some(s=>s.startAt===x.startAt)).toBe(true);});
it('L04 withdrawal between display and request/confirmation blocks booking and preserves the request',async()=>{const x=await input(),r=await bookings.book(req(),x);await transaction(workerActor,c=>c.query("UPDATE listings SET status='withdrawn',version=version+1 WHERE id=$1",[listing]));try{await expect(bookings.book(req(),{...x,startAt:new Date(date+'T05:00:00Z').toISOString()})).rejects.toMatchObject({status:404});await expect(ops.confirm(req(),r.data.id,{version:1,listingVersion:1,scheduleVersion:1})).rejects.toMatchObject({status:404});expect((await transaction(buyer,c=>c.query('SELECT status,version FROM viewings WHERE id=$1',[r.data.id]))).rows[0]).toEqual({status:'requested',version:1});}finally{await cancel(buyer,r.data);await transaction(workerActor,c=>c.query("UPDATE listings SET status='published',version=version+1 WHERE id=$1",[listing]));}});
it('L04 database writes require current metadata and retained travel gaps apply across properties',async()=>{const x=await input(),r=await bookings.book(req(),x);try{await expect(transaction(other,c=>c.query("INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at) VALUES($1,$2,$3,$4,$5)",[listing,other.id,agent,date+'T04:00:00Z',date+'T04:45:00Z']))).rejects.toMatchObject({code:'23514'});const read=(await availability.read(req(),listing)).data;await availability.save(req(),listing,{...settings,version:read.policy!.version,listingVersion:read.listing.version,bufferMinutes:0});const slots=(await availability.slots({listingId:otherListing,date,days:1})).data.slots;expect(slots.some(s=>s.startAt===date+'T02:00:00.000Z')).toBe(false);expect(slots.some(s=>s.startAt===date+'T02:15:00.000Z')).toBe(true);await expect(controller(other).book(req(),await input('10:00',otherListing))).rejects.toMatchObject({status:409});const second=await controller(other).book(req(),await input('10:15',otherListing));await cancel(other,second.data);}finally{await cancel(buyer,r.data);}});
