import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ViewingAvailabilityController} from '../../apps/api/src/engagement/viewing-availability';
import {ViewingCalendarController} from '../../apps/api/src/engagement/viewing-calendar';
import {EngagementController} from '../../apps/api/src/engagement/controller';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',listing=crypto.randomUUID(),agent=crypto.randomUUID(),pro:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:org,roles:['agent']},buyer:Actor={id:'00000000-0000-4000-8000-000000000001',orgId:null,roles:['consumer']},other:Actor={id:'00000000-0000-4000-8000-000000000002',orgId:null,roles:['owner']},outsider:Actor={id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agent']};
const identity=(a:Actor)=>({actor:async()=>a} as unknown as Identity),calendar=(a:Actor)=>new ViewingCalendarController(identity(a)),engagement=(a:Actor)=>new EngagementController(identity(a)),availability=new ViewingAvailabilityController(identity(pro)),req=(url='/api/v1/viewings',key=crypto.randomUUID())=>({method:'POST',url,headers:{'idempotency-key':key}} as unknown as FastifyRequest);
const settings={version:0,listingVersion:1,agentId:agent,status:'active',durationMinutes:60,bufferMinutes:15,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'};let date:string;
const instant=(hour:string)=>new Date(date+'T'+hour+':00+08:00').toISOString();
async function input(){const s=(await availability.slots({listingId:listing,date,days:1})).data;return {version:0,listingId:listing,listingVersion:s.listingVersion,scheduleVersion:s.scheduleVersion!,agentId:agent,startAt:instant('09:00')};}
async function confirmed(){const x=await input(),row=(await engagement(buyer).book(req(),x)).data;return (await engagement(pro).confirm(req('/ops/viewings/'+row.id+'/confirm'),row.id,{version:row.version,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion})).data;}
async function cleanup(){await transaction(workerActor,c=>c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=$1 AND status IN('requested','confirmed')",[listing]));}
beforeAll(async()=>{date=new Date(Date.now()+2*86400000).toISOString().slice(0,10);await transaction(workerActor,async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'L05 synthetic calendar agent',$4,'Synthetic booking calendar acceptance fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,pro.id,org,'l05-'+agent]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,'L05 synthetic calendar property','Synthetic booking calendar fixture','sale','residential','CNY','2100000.25','published')",[listing,org,agent,'l05-'+listing]);});await availability.save(req(),listing,settings);});
afterAll(async()=>{try{await cleanup();await transaction(workerActor,async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[listing]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);});}finally{await pool.end();}});
it('L05 consumer atomically reschedules a confirmed viewing, requiring fresh confirmation; idempotent receipt preserves one event and row',async()=>{const row=await confirmed();try{const slots=(await calendar(buyer).slots(req(),row.id,{date,days:1})).data;expect(slots.slots.some(s=>s.startAt===instant('09:15'))).toBe(true);const body={version:row.version,listingVersion:slots.listingVersion,scheduleVersion:slots.scheduleVersion!,startAt:instant('11:00')},request=req('/viewings/'+row.id+'/reschedule'),moved=await calendar(buyer).reschedule(request,row.id,body);expect(moved.data).toMatchObject({id:row.id,status:'requested',version:3});expect(moved.data.start_at.toISOString()).toBe(instant('11:00'));expect(await calendar(buyer).reschedule(request,row.id,body)).toEqual(JSON.parse(JSON.stringify(moved)));expect((await availability.slots({listingId:listing,date,days:1})).data.slots.some(s=>s.startAt===instant('09:00'))).toBe(true);await transaction(workerActor,async c=>{expect((await c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='viewing.rescheduled'",[row.id])).rows[0].n).toBe(1);expect((await c.query('SELECT count(*)::int n FROM viewings WHERE id=$1',[row.id])).rows[0].n).toBe(1);});}finally{await cleanup();}});
it('L05 conflicting/stale/unauthorized reschedules and cancellations preserve the original confirmed interval',async()=>{const row=await confirmed();try{const x=await input();await engagement(other).book(req(),{...x,startAt:instant('12:00')});const body={version:row.version,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion,startAt:instant('12:00')};await expect(calendar(buyer).reschedule(req(),row.id,body)).rejects.toMatchObject({status:409});await expect(calendar(buyer).reschedule(req(),row.id,{...body,version:1,startAt:instant('10:30')})).rejects.toMatchObject({status:409});await expect(calendar(other).reschedule(req(),row.id,body)).rejects.toMatchObject({status:404});await expect(calendar(other).slots(req(),row.id,{date})).rejects.toMatchObject({status:404});await expect(calendar(outsider).cancel(req(),row.id,{version:2})).rejects.toMatchObject({status:404});await expect(engagement(other).cancel(req(),row.id,{version:2})).rejects.toMatchObject({status:404});await expect(transaction(buyer,c=>c.query("UPDATE viewings SET start_at=$2,end_at=$3,version=version+1 WHERE id=$1",[row.id,instant('12:00'),instant('13:00')]))).rejects.toMatchObject({code:'42501'});const unchanged=(await transaction(buyer,c=>c.query('SELECT start_at,end_at,status,version FROM viewings WHERE id=$1',[row.id]))).rows[0];expect(unchanged).toEqual({start_at:row.start_at,end_at:row.end_at,status:'confirmed',version:2});}finally{await cleanup();}});
it('L05 assigned professional reschedule retains confirmation; professional cancellation releases the new slot',async()=>{const row=await confirmed();try{const x=await input(),body={version:2,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion,startAt:instant('11:00')},moved=(await calendar(pro).opsReschedule(req(),row.id,body)).data;expect(moved).toMatchObject({status:'confirmed',version:3});await expect(calendar(outsider).opsReschedule(req(),row.id,{...body,version:3,startAt:instant('14:00')})).rejects.toMatchObject({status:404});const cancelled=(await calendar(pro).cancel(req(),row.id,{version:3})).data;expect(cancelled).toMatchObject({status:'cancelled',version:4});expect((await availability.slots({listingId:listing,date,days:1})).data.slots.some(s=>s.startAt===instant('11:00'))).toBe(true);}finally{await cleanup();}});
it('L05 outcomes require a scoped confirmed viewing whose actual interval has ended, then become terminal',async()=>{const future=await confirmed();try{await expect(calendar(pro).terminal(req(),future.id,{version:2,status:'completed'})).rejects.toMatchObject({status:409});const past=await transaction(workerActor,async c=>{const rows=[];for(const [n,state] of ['confirmed','confirmed','requested'].entries())rows.push((await c.query("INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at,status,property_zone,buffer_minutes) VALUES($1,$2,$3,now()-make_interval(days=>$4)-interval '2 hours',now()-make_interval(days=>$4)-interval '1 hour',$5,'Asia/Shanghai',15) RETURNING *",[listing,buyer.id,agent,n+1,state])).rows[0]);return rows;});for(const [n,status] of ['completed','no_show'].entries()){await expect(calendar(buyer).slots(req(),past[n].id,{date,days:1})).rejects.toMatchObject({status:409});await expect(transaction(buyer,c=>c.query("UPDATE viewings SET start_at=$2,end_at=$3,status='requested',version=version+1,listing_version=1,availability_version=1,buffer_minutes=15 WHERE id=$1",[past[n].id,instant('14:00'),instant('15:00')]))).rejects.toMatchObject({code:'23514'});await expect(calendar(outsider).terminal(req(),past[n].id,{version:1,status})).rejects.toMatchObject({status:404});await expect(calendar(buyer).terminal(req(),past[n].id,{version:1,status})).rejects.toMatchObject({status:403});const request=req('/ops/viewings/'+past[n].id+'/outcome'),saved=await calendar(pro).terminal(request,past[n].id,{version:1,status});expect(saved.data).toMatchObject({status,version:2});expect(await calendar(pro).terminal(request,past[n].id,{version:1,status})).toEqual(JSON.parse(JSON.stringify(saved)));await expect(calendar(pro).cancel(req(),past[n].id,{version:2})).rejects.toMatchObject({status:409});}await expect(calendar(pro).terminal(req(),past[2].id,{version:1,status:'completed'})).rejects.toMatchObject({status:409});}finally{await cleanup();}});
it('L05 own withdrawn bookings remain visible with recorded zone and redacted property title; calendars never broaden assignment or ownership',async()=>{const row=await confirmed();await transaction(workerActor,c=>c.query("UPDATE listings SET status='withdrawn',title='PRIVATE UNPUBLISHED L05 TITLE',version=version+1 WHERE id=$1",[listing]));try{const own=(await engagement(buyer).viewings(req(),{})).data.find(r=>r.id===row.id);expect(own).toMatchObject({title:'Unavailable property',time_zone:'Asia/Shanghai',zone_source:'recorded',status:'confirmed'});expect(JSON.stringify(own)).not.toContain('PRIVATE UNPUBLISHED');expect((await engagement(other).viewings(req(),{})).data.some(r=>r.id===row.id)).toBe(false);expect((await engagement(outsider).opsViewings(req(),{})).data.some(r=>r.id===row.id)).toBe(false);expect((await engagement(pro).opsViewings(req(),{})).data.some(r=>r.id===row.id)).toBe(true);await expect(calendar(buyer).reschedule(req(),row.id,{version:2,listingVersion:1,scheduleVersion:1,startAt:instant('12:00')})).rejects.toMatchObject({status:404});await calendar(pro).cancel(req(),row.id,{version:2});}finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='published',title='L05 synthetic calendar property',version=version+1 WHERE id=$1",[listing]));await cleanup();}});
it('L05 concurrent reschedules from the same version yield one change and one conflict',async()=>{const row=await confirmed();try{const x=await input(),base={version:2,listingVersion:x.listingVersion,scheduleVersion:x.scheduleVersion},results=await Promise.allSettled([calendar(buyer).reschedule(req(),row.id,{...base,startAt:instant('11:00')}),calendar(buyer).reschedule(req(),row.id,{...base,startAt:instant('14:00')})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected').map(r=>(r as PromiseRejectedResult).reason.status)).toEqual([409]);expect((await transaction(buyer,c=>c.query('SELECT version,status FROM viewings WHERE id=$1',[row.id]))).rows[0]).toEqual({version:3,status:'requested'});expect((await transaction(workerActor,c=>c.query("SELECT count(*)::int n FROM outbox WHERE aggregate_id=$1 AND kind='viewing.rescheduled'",[row.id]))).rows[0].n).toBe(1);}finally{await cleanup();}});
it('L05 calendar date filters use the recorded property date, including times on the previous UTC day',async()=>{const policy=(await availability.read(req(),listing)).data;await availability.save(req(),listing,{...settings,version:policy.policy!.version,listingVersion:policy.listing.version,opensAt:'00:00'});const x=await input(),row=(await engagement(buyer).book(req(),{...x,startAt:instant('00:30')})).data;try{expect(row.start_at.toISOString().slice(0,10)).not.toBe(date);const filtered=await engagement(buyer).viewings(req(),{from:date,to:date,status:'requested',page:1});expect(filtered.data.some(r=>r.id===row.id)).toBe(true);expect(filtered.meta).toMatchObject({page:1,hasMore:false});expect((await engagement(buyer).viewings(req(),{from:date,to:date,status:'confirmed'})).data.some(r=>r.id===row.id)).toBe(false);}finally{await cleanup();}});

it('L05 property capacity remains reserved when assignment changes; the former appointment can be cancelled through actual professional scope',async()=>{
 const row=await confirmed(),next=crypto.randomUUID();try{await transaction(workerActor,async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'L05 reassignment fixture agent',$4,'Synthetic property capacity fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[next,pro.id,org,'l05-'+next]);await c.query('UPDATE listings SET agent_id=$2,version=version+1 WHERE id=$1',[listing,next]);});const old=(await availability.read(req(),listing)).data;await availability.save(req(),listing,{...settings,version:old.policy!.version,listingVersion:old.listing.version,agentId:next});const slots=(await availability.slots({listingId:listing,date,days:1})).data;expect(slots.slots.some(s=>s.startAt===instant('09:00'))).toBe(false);await expect(transaction(workerActor,c=>c.query('INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at) VALUES($1,$2,$3,$4,$5)',[listing,other.id,next,instant('09:00'),instant('10:00')]))).rejects.toMatchObject({code:'23P01',constraint:'viewing_property_interval_exclusion'});const body={version:0,listingId:listing,listingVersion:slots.listingVersion,scheduleVersion:slots.scheduleVersion!,agentId:next,startAt:instant('09:00')};await expect(engagement(other).book(req(),body)).rejects.toMatchObject({status:409});const second=(await engagement(other).book(req(),{...body,startAt:instant('11:00')})).data;await calendar(pro).cancel(req(),row.id,{version:row.version});expect((await availability.slots({listingId:listing,date,days:1})).data.slots.some(s=>s.startAt===instant('09:00'))).toBe(true);await calendar(pro).cancel(req(),second.id,{version:second.version});}finally{await cleanup();await transaction(workerActor,async c=>{await c.query('UPDATE listings SET agent_id=$2,version=version+1 WHERE id=$1',[listing,agent]);await c.query('UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1',[next]);});const record=(await availability.read(req(),listing)).data;await availability.save(req(),listing,{...settings,version:record.policy!.version,listingVersion:record.listing.version});}
});
