import '../support/env';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {FastifyRequest} from 'fastify';
import {pool,transaction,type Actor} from '../../packages/database/src/index';
import {workerActor} from '../../apps/worker/src/processor';
import {ViewingAvailabilityController} from '../../apps/api/src/engagement/viewing-availability';
import type {Identity} from '../../apps/api/src/platform/core';
const org='10000000-0000-4000-8000-000000000001',listing=crypto.randomUUID(),agent=crypto.randomUUID(),actor:Actor={id:'00000000-0000-4000-8000-000000000003',orgId:org,roles:['agent']},controller=new ViewingAvailabilityController({actor:async()=>actor} as unknown as Identity),req=(key=crypto.randomUUID())=>({method:'POST',url:'/api/v1/ops/viewing-availability',headers:{'idempotency-key':key}} as unknown as FastifyRequest);
const settings={version:0,listingVersion:1,agentId:agent,status:'active',durationMinutes:60,bufferMinutes:15,weekdays:[0,1,2,3,4,5,6],opensAt:'09:00',closesAt:'17:00'};
let tomorrow:string;
beforeAll(async()=>{tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);await transaction(workerActor,async c=>{await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'L03 synthetic availability agent',$4,'Synthetic availability acceptance fixture',ARRAY['English'],ARRAY['Chaoyang'],'bj','2035-01-01')",[agent,actor.id,org,'l03-'+agent]);await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,'L03 synthetic availability property','Synthetic viewing availability fixture','sale','residential','CNY','2100000.25','published')",[listing,org,agent,'l03-'+listing]);});});
afterAll(async()=>{try{await transaction(workerActor,async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[listing]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[agent]);await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE listing_id=$1",[listing]);});}finally{await pool.end();}});
it('L03 current assigned agent publishes versioned working hours; public future slots convert property local time to actual UTC',async()=>{expect((await controller.slots({listingId:listing,date:tomorrow,days:1})).data.slots).toEqual([]);const request=req(),first=await controller.save(request,listing,settings);expect(first.data).toMatchObject({version:1,time_zone:'Asia/Shanghai',agent_id:agent});expect(await controller.save(request,listing,settings)).toEqual(JSON.parse(JSON.stringify(first)));const s=(await controller.slots({listingId:listing,date:tomorrow,days:1})).data;expect(s).toMatchObject({listingVersion:1,agentId:agent,timeZone:'Asia/Shanghai',scheduleVersion:1,durationMinutes:60,bufferMinutes:15});expect(s.slots.length).toBeGreaterThan(0);expect(s.slots[0]).toEqual({startAt:tomorrow+'T01:00:00.000Z',endAt:tomorrow+'T02:00:00.000Z'});expect(s.slots.every(t=>Date.parse(t.startAt)>Date.parse(s.asOf))).toBe(true);expect(s.slots.every(t=>Date.parse(t.endAt)-Date.parse(t.startAt)===3600000)).toBe(true);expect(JSON.stringify(s)).not.toMatch(/organization_id|reason|created_by|email|phone/);expect((await controller.slots({listingId:listing,date:'2020-01-01',days:1})).data.slots).toEqual([]);});
it('L03 private blocked intervals and existing agent appointments remove overlapping or buffered slots; cancellation restores capacity',async()=>{const b=await controller.block(req(),listing,{version:0,scheduleVersion:1,listingVersion:1,startLocal:tomorrow+'T10:00',endLocal:tomorrow+'T11:00',reason:'Private synthetic unavailable interval'}),before=(await controller.slots({listingId:listing,date:tomorrow,days:1})).data;expect(before.slots.some(t=>t.startAt===tomorrow+'T01:00:00.000Z')).toBe(false);expect(before.slots.some(t=>t.startAt===tomorrow+'T03:00:00.000Z')).toBe(false);expect(before.slots.some(t=>t.startAt===tomorrow+'T03:15:00.000Z')).toBe(true);expect(JSON.stringify(before)).not.toContain('Private synthetic');await controller.cancelBlock(req(),listing,b.data.id,{version:1,scheduleVersion:1,listingVersion:1});expect((await controller.slots({listingId:listing,date:tomorrow,days:1})).data.slots.some(t=>t.startAt===tomorrow+'T01:00:00.000Z')).toBe(true);const viewing=await transaction(workerActor,c=>c.query("INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at,status) VALUES($1,'00000000-0000-4000-8000-000000000001',$2,$3,$4,'confirmed') RETURNING id",[listing,agent,tomorrow+'T02:00:00Z',tomorrow+'T03:00:00Z']));try{expect((await controller.slots({listingId:listing,date:tomorrow,days:1})).data.slots.some(t=>t.startAt===tomorrow+'T01:00:00.000Z')).toBe(false);}finally{await transaction(workerActor,c=>c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE id=$1",[viewing.rows[0].id]));}});
it('L03 scope/version/workflow checks deny foreign authoring, stale policies, past blocks, paused availability and withdrawn properties',async()=>{const foreign=new ViewingAvailabilityController({actor:async()=>({id:'00000000-0000-4000-8000-000000000011',orgId:'10000000-0000-4000-8000-000000000005',roles:['agent']})} as unknown as Identity);await expect(foreign.read(req(),listing)).rejects.toMatchObject({status:404});await expect(foreign.save(req(),listing,settings)).rejects.toMatchObject({status:404});await expect(controller.save(req(),listing,settings)).rejects.toMatchObject({status:409});await expect(controller.block(req(),listing,{version:0,scheduleVersion:1,listingVersion:1,startLocal:'2020-01-01T10:00',endLocal:'2020-01-01T11:00',reason:'Past block'})).rejects.toMatchObject({status:400});await controller.save(req(),listing,{...settings,version:1,status:'paused'});expect((await controller.slots({listingId:listing,date:tomorrow,days:1})).data.slots).toEqual([]);await expect(controller.block(req(),listing,{version:0,scheduleVersion:2,listingVersion:1,startLocal:tomorrow+'T10:00',endLocal:tomorrow+'T11:00',reason:'Paused block'})).rejects.toMatchObject({status:409});await controller.save(req(),listing,{...settings,version:2});await transaction(workerActor,c=>c.query("UPDATE listings SET status='withdrawn',version=version+1 WHERE id=$1",[listing]));try{await expect(controller.slots({listingId:listing,date:tomorrow,days:1})).rejects.toMatchObject({status:404});}finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='published',version=1 WHERE id=$1",[listing]));}});
it('L03 PostgreSQL round-trip validation excludes DST gaps and preserves one actual duration across clock transitions',async()=>{await transaction(null,async c=>{const row=(await c.query("SELECT viewing_local_instant('2027-03-14 02:30'::timestamp,'America/New_York') gap,viewing_local_instant('2027-03-14 03:30'::timestamp,'America/New_York') valid,viewing_local_instant('2026-11-01 01:30'::timestamp,'America/New_York') repeated")).rows[0];expect(row.gap).toBeNull();expect(row.valid.toISOString()).toBe('2027-03-14T07:30:00.000Z');expect(row.repeated.toISOString()).toBe('2026-11-01T06:30:00.000Z');});});

it('L03 public slot generation excludes spring gaps and clock-crossing durations and resolves autumn repeated times consistently',async()=>{
 const city=crypto.randomUUID(),district=crypto.randomUUID(),community=crypto.randomUUID(),unit=crypto.randomUUID(),dstAgent=crypto.randomUUID(),dstListing=crypto.randomUUID(),slug='l03-dst-'+city;
 try{await transaction(workerActor,async c=>{
 await c.query("INSERT INTO cities(id,slug,name,country,currency,timezone) VALUES($1,$2,'L03 synthetic DST market','US','USD','America/New_York')",[city,slug]);
 await c.query("INSERT INTO districts(id,city_id,name,slug) VALUES($1,$2,'Synthetic DST district',$3)",[district,city,slug]);
 await c.query("INSERT INTO communities(id,district_id,slug,name,address) VALUES($1,$2,$3,'Synthetic DST community','Synthetic reference address')",[community,district,slug]);
 await c.query("INSERT INTO units(id,community_id,organization_id,area,beds,living_rooms,baths) VALUES($1,$2,$3,'80.00',2,1,1)",[unit,community,org]);
 await c.query("INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,verified_until) VALUES($1,$2,$3,'L03 DST fixture agent',$4,'Explicit synthetic DST fixture',ARRAY['English'],ARRAY['Synthetic DST district'],$4,'2035-01-01')",[dstAgent,actor.id,org,slug]);
 await c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,$2,$3,$4,$5,'L03 DST property','Explicit synthetic DST fixture','sale','residential','USD','2100000.25','published')",[dstListing,unit,org,dstAgent,slug]);
 });
 await controller.save(req(),dstListing,{...settings,agentId:dstAgent,opensAt:'00:00',closesAt:'04:00',bufferMinutes:0});
 const spring=(await controller.slots({listingId:dstListing,date:'2027-03-14',days:1})).data;
 expect(spring.timeZone).toBe('America/New_York');expect(spring.slots.length).toBeGreaterThan(0);
 const local=(s:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:spring.timeZone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(s));
 expect(spring.slots.every(s=>!local(s.startAt).startsWith('02:')&&!local(s.endAt).startsWith('02:')&&Date.parse(s.endAt)-Date.parse(s.startAt)===3600000)).toBe(true);
 expect(spring.slots).toContainEqual({startAt:'2027-03-14T07:00:00.000Z',endAt:'2027-03-14T08:00:00.000Z'});
 const autumn=(await controller.slots({listingId:dstListing,date:'2026-11-01',days:1})).data.slots;
 expect(autumn).toContainEqual({startAt:'2026-11-01T06:30:00.000Z',endAt:'2026-11-01T07:30:00.000Z'});
 expect(autumn.some(s=>s.startAt==='2026-11-01T04:30:00.000Z')).toBe(false);
 expect(autumn.every(s=>Date.parse(s.endAt)-Date.parse(s.startAt)===3600000)).toBe(true);
 }finally{await transaction(workerActor,async c=>{await c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[dstListing]);await c.query("UPDATE agents SET verified_until=NULL,version=version+1 WHERE id=$1",[dstAgent]);await c.query("UPDATE cities SET status='archived',version=version+1 WHERE id=$1",[city]);await c.query("UPDATE districts SET status='archived',version=version+1 WHERE id=$1",[district]);await c.query("UPDATE communities SET status='archived',version=version+1 WHERE id=$1",[community]);});}
});

it('L03 concurrent initial policy publication preserves version zero semantics',async()=>{
 const fresh=crypto.randomUUID();await transaction(workerActor,c=>c.query("INSERT INTO listings(id,unit_id,organization_id,agent_id,slug,title,description,transaction,segment,currency,price,status) VALUES($1,'10000000-0000-4000-8000-000000001000',$2,$3,$4,'L03 initial policy race','Synthetic concurrent availability fixture','sale','residential','CNY','2100000.25','published')",[fresh,org,agent,'l03-'+fresh]));
 try{const outcomes=await Promise.allSettled([controller.save(req(),fresh,settings),controller.save(req(),fresh,{...settings,closesAt:'18:00'})]);expect(outcomes.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(outcomes.filter(r=>r.status==='rejected').map(r=>(r as PromiseRejectedResult).reason.status)).toEqual([409]);expect((await controller.read(req(),fresh)).data.policy?.version).toBe(1);}finally{await transaction(workerActor,c=>c.query("UPDATE listings SET status='archived',version=version+1 WHERE id=$1",[fresh]));}
});
