'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk,ApiError,type ChatMessageRecord} from '@haven/contracts';
import {ChatComposer,ChatMessage} from './chat-composer';
import {ConversationRealtime} from './conversation-realtime';
import {ConversationContext} from './conversation-context';
import {Spinner,ErrorBox,Empty} from './index';
type Summary=Awaited<ReturnType<typeof sdk.EngagementController_conversations>>['data'][number];
const label=(r:Summary)=>r.resource_type==='agent'?'Agent inquiry':r.resource_type==='development'?'Development inquiry':r.resource_type==='provider'?'Service inquiry':r.resource_type==='listing'?'Property inquiry':'Historical conversation';
const merge=(a:ChatMessageRecord[],b:ChatMessageRecord[])=>Array.from(new Map([...a,...b].map(m=>[m.id,m])).values()).sort((l,r)=>BigInt(l.sequence)<BigInt(r.sequence)?-1:1);
export function ConversationInbox({professional=false}:{professional?:boolean}){
 const [rows,setRows]=useState<Summary[]|null>(null),[active,setActive]=useState(''),[page,setPage]=useState(1),[listError,setListError]=useState(''),[messageError,setMessageError]=useState(''),[readError,setReadError]=useState(''),[messages,setMessages]=useState<ChatMessageRecord[]|null>(null),[older,setOlder]=useState(false),[loadingOlder,setLoadingOlder]=useState(false),[tick,setTick]=useState(0),[listTick,setListTick]=useState(0),[visited,setVisited]=useState<string[]>([]),[ready,setReady]=useState(false),[accessEnded,setAccessEnded]=useState(false),[readTick,setReadTick]=useState(0);
 const atBottom=useRef(true),current=useRef(''),panel=useRef<HTMLDivElement>(null);
 function locationState(){const q=new URLSearchParams(location.search);setActive(q.get('conversation')||'');setPage(Math.max(1,Math.min(10000,Number(q.get('inboxPage'))||1)));setReady(true);}
 function select(id:string,nextPage=page){if(nextPage!==page)setRows(null);const url=new URL(location.href);if(id)url.searchParams.set('conversation',id);else url.searchParams.delete('conversation');url.searchParams.set('inboxPage',String(nextPage));history.pushState(null,'',url);setActive(id);setPage(nextPage);}
 useEffect(()=>{locationState();const pop=()=>locationState(),interval=setInterval(()=>{setListTick(n=>n+1);},3000);const visible=()=>{if(document.visibilityState==='visible')setReadTick(n=>n+1);};document.addEventListener('visibilitychange',visible);window.addEventListener('popstate',pop);return()=>{document.removeEventListener('visibilitychange',visible);clearInterval(interval);window.removeEventListener('popstate',pop);};},[]);
 useEffect(()=>{if(!ready)return;const abort=new AbortController();void sdk.EngagementController_conversations({query:{page},signal:abort.signal}).then(r=>{setRows(r.data);setListError('');}).catch(e=>{if(!abort.signal.aborted)setListError(e.message);});return()=>abort.abort();},[page,listTick,ready]);
 useEffect(()=>{if(!ready||active||!rows?.length)return;const id=rows[0].id,url=new URL(location.href);url.searchParams.set('conversation',id);url.searchParams.set('inboxPage',String(page));history.replaceState(null,'',url);setActive(id);},[rows,active,ready,page]);
 useEffect(()=>{current.current=active;atBottom.current=true;setAccessEnded(false);setMessages(null);setOlder(false);setMessageError('');setReadError('');if(active)setVisited(ids=>ids.includes(active)?ids:[...ids,active]);},[active]);
 useEffect(()=>{if(!active)return;const abort=new AbortController();void sdk.EngagementController_messages({params:{id:active},signal:abort.signal}).then(r=>{setMessages(previous=>merge(previous??[],r.data));if(r.data.length===100)setOlder(true);setMessageError('');}).catch(e=>{if(!abort.signal.aborted)setMessageError(e.message);});return()=>abort.abort();},[active,tick]);
 useEffect(()=>{if(!active||!messages?.length||messageError||document.visibilityState!=='visible'||!atBottom.current)return;const abort=new AbortController(),sequence=messages.at(-1)!.sequence;panel.current?.scrollTo({top:panel.current.scrollHeight});void (async()=>{try{const cursor=(await sdk.ConversationsController_cursor({params:{id:active},signal:abort.signal})).data;if(BigInt(cursor.sequence)<BigInt(sequence))await sdk.ConversationsController_read({params:{id:active},body:{version:cursor.version,sequence},signal:abort.signal});if(!abort.signal.aborted){setReadError('');setListTick(n=>n+1);}}catch(e){if(!abort.signal.aborted&&!(e instanceof ApiError&&e.code==='READ_CURSOR_CHANGED'))setReadError(e instanceof Error?e.message:'Read state was not saved.');}})();return()=>abort.abort();},[messages,active,messageError,readTick]);
 async function loadOlder(){if(!messages?.length||loadingOlder)return;const id=active;setLoadingOlder(true);atBottom.current=false;const oldHeight=panel.current?.scrollHeight??0,oldTop=panel.current?.scrollTop??0;try{const r=await sdk.EngagementController_messages({params:{id},query:{before:messages[0].sequence}});if(current.current===id){setMessages(previous=>merge(r.data,previous??[]));setOlder(r.data.length===100);setMessageError('');requestAnimationFrame(()=>{if(panel.current)panel.current.scrollTop=oldTop+panel.current.scrollHeight-oldHeight;});}}catch(e){if(current.current===id)setMessageError(e instanceof Error?e.message:'Older messages could not be loaded.');}finally{setLoadingOlder(false);}}
 function refresh(){setTick(n=>n+1);setListTick(n=>n+1);}
 return <section aria-label="Conversation inbox">{listError&&<ErrorBox message={listError} retry={refresh}/>} {!rows&&!listError?<Spinner/>:rows?.length===0&&!active&&page===1?<Empty title={professional?'No client conversations':'Your conversations start here'} description="Send an inquiry to start a conversation with its team."/>:<div className="inbox"><aside aria-label="Conversations">{rows?.map(r=><button key={r.id} data-conversation-id={r.id} className={r.id===active?'selected':''} aria-pressed={r.id===active} onClick={()=>select(r.id)}><span>{label(r)}<small>{r.participants.join(', ')}</small><small>{new Date(r.created_at).toLocaleDateString('en-GB')}</small>{r.unread_count!=='0'&&<strong aria-label={r.unread_count+' unread messages'}>{r.unread_count} unread</strong>}</span></button>)}<div className="dialog-actions"><button className="button secondary small" disabled={page===1} onClick={()=>select('',page-1)}>Previous conversations</button><button className="button secondary small" disabled={!rows||rows.length<100} onClick={()=>select('',page+1)}>Next conversations</button></div></aside><div className="chat-panel">{active?<><h3>{professional?'Client conversation':'Property conversation'}</h3><ConversationContext key={active} id={active}/>{messages&&<ConversationRealtime key={active} id={active} sequence={messages.at(-1)?.sequence??'0'} received={incoming=>setMessages(previous=>merge(previous??[],incoming))} accessChanged={allowed=>setAccessEnded(!allowed)}/>} {messageError&&<ErrorBox message={messageError} retry={refresh}/>}<div className="messages" ref={panel} tabIndex={0} role="log" aria-label="Saved messages" onScroll={e=>{const el=e.currentTarget,next=el.scrollHeight-el.scrollTop-el.clientHeight<48;if(next&&!atBottom.current)setReadTick(n=>n+1);atBottom.current=next;}}>{older&&<button className="button secondary small" disabled={loadingOlder} onClick={()=>void loadOlder()}>{loadingOlder?'Loading older messages…':'Load older messages'}</button>}{!messages&&!messageError?<Spinner/>:messages?.length?messages.map(m=><ChatMessage key={m.id} message={m}/>):!messageError&&<p>No saved messages yet.</p>}</div>{readError&&<ErrorBox message={'Read state not saved: '+readError} retry={refresh}/>} {visited.map(id=><div key={id} hidden={id!==active}><fieldset disabled={id===active&&accessEnded} style={{border:0,padding:0,margin:0,minWidth:0}}><ChatComposer id={id} professional={professional} sent={refresh}/></fieldset></div>)}<p className="fine-print">Only saved messages appear above. Unconfirmed drafts stay in the composer.</p></>:<p>Select a conversation.</p>}</div></div>}</section>;
}
