'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk,depositMovement,type DepositLedgerRecord} from '@haven/contracts';
import {ErrorBox,Spinner} from './index';
export function DepositLedgerForm({id,onSaved}:{id?:string;onSaved:()=>void}){
 const [leases,setLeases]=useState<{id:string;community:string;tenant:string}[]>([]),[leaseId,setLeaseId]=useState(id||''),[ledger,setLedger]=useState<DepositLedgerRecord|null>(null),[kind,setKind]=useState<'received'|'released'|'adjusted'>('received'),[direction,setDirection]=useState<'increase'|'decrease'>('increase'),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[page,setPage]=useState(1),[tick,setTick]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),keys=useRef(new Map<string,string>());
 useEffect(()=>{let live=true;sdk.ManagementController_leases({}).then(r=>{if(live)setLeases(r.data.filter(l=>['active','ended'].includes(l.status)));}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setLedger(null);if(leaseId)sdk.DepositsController_ledger({params:{leaseId},query:{page}}).then(r=>{if(live)setLedger(r.data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[leaseId,page,tick]);
 return <form className="field-form" noValidate onSubmit={async e=>{e.preventDefault();setError('');if(!ledger){setError('Select a granted lease and load its deposit ledger.');return;}const x=depositMovement.safeParse({version:0,leaseId,leaseVersion:ledger.leaseVersion,unitVersion:ledger.unitVersion,grantVersion:ledger.grantVersion,liabilityVersion:ledger.liabilityVersion,kind,direction:kind==='adjusted'?direction:kind==='received'?'increase':'decrease',amount,currency:ledger.currency,reason,confirm});if(!x.success){setError('Enter a positive decimal amount, a reason of 5–500 characters and confirm the deposit evidence.');return;}const fingerprint=JSON.stringify(x.data);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());setBusy(true);try{await sdk.DepositsController_create({body:x.data,headers:{'idempotency-key':keys.current.get(fingerprint)!}});setAmount('');setReason('');setConfirm(false);setPage(1);setTick(t=>t+1);onSaved();}catch(e){setError(e instanceof Error?e.message:'Unable to record deposit evidence. Inputs are retained.');}finally{setBusy(false);}}}>
 <label className="field">Lease<select aria-label="Deposit lease" value={leaseId} disabled={busy||!!id} onChange={e=>{setLeaseId(e.target.value);setPage(1);setError('');}}><option value="">Select a lease</option>{leases.map(l=><option key={l.id} value={l.id}>{l.community} · {l.tenant} · {l.id.slice(0,8)}</option>)}</select></label>{leaseId&&!ledger&&!error&&<Spinner/>}{ledger&&<><p role="status">Deposit held: {ledger.currency} {ledger.held} · liability version {ledger.liabilityVersion}</p><p>{ledger.note}</p><label className="field">Movement<select aria-label="Deposit movement" value={kind} disabled={busy} onChange={e=>setKind(e.target.value as typeof kind)}><option value="received">Received</option><option value="released">Released</option><option value="adjusted">Adjustment</option></select></label>{kind==='adjusted'&&<label className="field">Adjustment direction<select aria-label="Adjustment direction" value={direction} disabled={busy} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="increase">Increase liability</option><option value="decrease">Decrease liability</option></select></label>}<label className="field">Amount ({ledger.currency})<input aria-label="Deposit amount" inputMode="decimal" value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Reason / reference<textarea aria-label="Deposit reason" value={reason} maxLength={500} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/> I confirm recording this deposit liability evidence. No funds are transferred.</label><button className="button" disabled={busy}>{busy?'Recording…':'Confirm deposit evidence'}</button><h3>Retained deposit movements</h3>{ledger.items.length?ledger.items.map(r=><article key={r.id}><p>{r.kind} · {r.direction||'Historical direction unavailable'} · {r.currency} {r.amount}</p><p>{r.reason}</p><p>{r.native?`Held after: ${r.currency} ${r.heldAfter} · liability version ${r.liabilityVersion}`:'Historical source versions and before/after liability are unavailable.'}</p><p>Recorded {new Date(r.at).toLocaleString('en-GB')}</p></article>):<p>No deposit evidence recorded.</p>}<div className="row-actions"><button className="button secondary" type="button" disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>Previous movements</button><span>Page {page} · {ledger.total} movements</span><button className="button secondary" type="button" disabled={busy||page*20>=ledger.total} onClick={()=>setPage(p=>p+1)}>Next movements</button></div></>}{error&&<ErrorBox message={error}/>}<button className="button secondary" type="button" disabled={busy||!leaseId} onClick={()=>{setError('');setTick(t=>t+1);}}>Refresh deposit ledger</button>
 </form>;
}
