'use client';
import {useState,useEffect,useCallback} from 'react';
import {Dialog,Spinner,ErrorBox,Empty,Badge} from './index';
type Request=(path:string,init?:RequestInit)=>Promise<any>;
const initial={title:'',description:'',transaction:'sale',segment:'residential',currency:'CNY',price:'',rentPeriod:'month',furnishing:'Unfurnished',availableFrom:'',features:''};
export function DraftListingWorkbench({request,owner=false,onChanged}:{request:Request;owner?:boolean;onChanged?:()=>void|Promise<void>}){
 const [submitting,setSubmitting]=useState('');const [rows,setRows]=useState<any[]|null>(null),[units,setUnits]=useState<any[]>([]),[communities,setCommunities]=useState<any[]>([]),[error,setError]=useState(''),[record,setRecord]=useState<any|null>(null),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{setError('');try{const results=await Promise.all([request(owner?'/me/listing-drafts':'/ops/listings'),request('/ops/listing-units'),request('/communities?city=bj&limit=50')]);setRows(results[0].data.filter((row:any)=>['draft','rejected'].includes(row.status)&&row.can_edit!==false));setUnits(results[1].data);setCommunities(results[2].data);}catch(error){setError(error instanceof Error?error.message:'Unable to load drafts');}},[request,owner]);
 useEffect(()=>{void refresh();},[refresh]);
 const close=useCallback(()=>setRecord(null),[]);
 async function submitDraft(row:any){setError('');setSubmitting(row.id);try{await request('/ops/listings/'+row.id+'/transition',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({status:'submitted',version:row.version,reason:'Submitted by the authorized property author'})});setNotice('Property submitted for review');await refresh();await onChanged?.();}catch(error){setError(error instanceof Error?error.message:'Unable to submit this property');}finally{setSubmitting('');}}
 async function edit(id:string){setError('');try{setRecord((await request('/ops/listings/'+id+'/draft')).data);}catch(error){setError(error instanceof Error?error.message:'Unable to edit this draft');}}
 return <section className="workspace-panel draft-workbench"><div className="section-heading"><h2>Property drafts</h2><button className="button" onClick={()=>setRecord({})}>Create property draft</button></div>{notice&&<p role="status">{notice}</p>}{error?<ErrorBox message={error} retry={()=>void refresh()}/>:!rows?<Spinner/>:!rows.length?<Empty title="No property drafts" description="Start a draft to prepare your property details before review."/>:<div className="record-list">{rows.map(row=><div className="record-row" key={row.id}><div><h3>{row.title}</h3><p>{row.transaction==='rent'?'To rent':'For sale'} · {row.currency} {row.price||'Price on request'}</p></div><Badge>{row.status}</Badge><button className="button secondary" onClick={()=>void edit(row.id)}>Edit draft</button><button className="button secondary" disabled={submitting===row.id} onClick={()=>void submitDraft(row)}>{submitting===row.id?'Submitting…':'Submit for review'}</button></div>)}</div>}{record&&<Dialog title={record.id?'Edit property draft':'Create property draft'} onClose={close}><DraftForm record={record} units={units} communities={communities} owner={owner} request={request} onSaved={async()=>{close();setNotice('Property draft saved');await refresh();await onChanged?.();}}/></Dialog>}</section>;
}
function DraftForm({record,units,communities,owner,request,onSaved}:{record:any;units:any[];communities:any[];owner:boolean;request:Request;onSaved:()=>Promise<void>}){
 const [values,setValues]=useState({...initial,...record,price:record.price||'',rentPeriod:record.rent_period||'month',availableFrom:record.available_from?.slice(0,10)||'',features:record.features?.join(', ')||''}),[unitId,setUnitId]=useState(''),[newUnit,setNewUnit]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string[]>>({});
 const [unit,setUnit]=useState({communityId:'',area:'',beds:'2',livingRooms:'1',baths:'1',orientation:'South',floor:'1',privateAddress:''});
 function field(name:string,label:string,type='text',options?:{value:string;label:string}[],disabled=false){return <label className="field" key={name}><span>{label}</span>{options?<select aria-label={label} value={values[name]} disabled={busy||disabled} onChange={event=>setValues({...values,[name]:event.target.value})}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:type==='textarea'?<textarea aria-label={label} value={values[name]} disabled={busy||disabled} rows={4} onChange={event=>setValues({...values,[name]:event.target.value})}/>:<input aria-label={label} type={type} value={values[name]} disabled={busy||disabled} onChange={event=>setValues({...values,[name]:event.target.value})}/ >}{fields[name]?.map(message=><small className="field-error" key={message}>{message}</small>)}</label>;}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setFields({});const body={title:values.title,description:values.description,transaction:values.transaction,segment:values.segment,currency:values.currency,price:values.price||null,rentPeriod:values.transaction==='rent'?values.rentPeriod:null,furnishing:values.furnishing,availableFrom:values.availableFrom||null,features:values.features.split(',').map((value:string)=>value.trim()).filter(Boolean),...(record.id?{version:record.version}:newUnit?{unit:{...unit,beds:Number(unit.beds),livingRooms:Number(unit.livingRooms),baths:Number(unit.baths),floor:Number(unit.floor)}}:{unitId})};try{await request(record.id?'/ops/listings/'+record.id+'/draft':'/ops/listings',{method:record.id?'PATCH':'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)});await onSaved();}catch(error){setError(error instanceof Error?error.message:'Could not save this draft');setFields((error as any).fieldErrors||{});}finally{setBusy(false);}}
 return <form className="field-form" onSubmit={submit}>{!record.id&&<>{!owner&&<label className="checkbox-field"><input type="checkbox" checked={newUnit} disabled={busy} onChange={event=>setNewUnit(event.target.checked)}/>Enter a new property unit</label>}{newUnit?<><label className="field"><span>Community</span><select aria-label="Community" value={unit.communityId} disabled={busy} onChange={event=>setUnit({...unit,communityId:event.target.value})}><option value="">Select a community</option>{communities.map(community=><option key={community.id} value={community.id}>{community.name}</option>)}</select></label>{[['privateAddress','Private unit address'],['area','Area (m²)'],['beds','Bedrooms'],['livingRooms','Living rooms'],['baths','Bathrooms'],['orientation','Orientation'],['floor','Floor']].map(([name,label])=><label className="field" key={name}><span>{label}</span><input aria-label={label} value={(unit as any)[name]} disabled={busy} onChange={event=>setUnit({...unit,[name]:event.target.value})}/></label>)}</>:<label className="field"><span>Existing property unit</span><select aria-label="Existing property unit" value={unitId} disabled={busy} onChange={event=>setUnitId(event.target.value)}><option value="">Select a property</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.community} · Floor {unit.floor} · {unit.beds} bedrooms · {unit.area} m²</option>)}</select>{fields.unitId?.map(message=><small className="field-error" key={message}>{message}</small>)}</label>}</>}{field('title','Property title')}{field('description','Property description','textarea')}<div className="form-columns">{field('transaction','Transaction','select',[{value:'sale',label:'For sale'},{value:'rent',label:'To rent'}],!!record.id)}{field('segment','Property segment','select',[{value:'residential',label:'Residential'},{value:'commercial',label:'Commercial'}],!!record.id)}</div>{field('currency','Currency','text',undefined,!!record.id)}{field('price','Asking price (decimal amount)')}{values.transaction==='rent'&&field('rentPeriod','Rental billing period','select',[{value:'month',label:'Monthly'},{value:'year',label:'Yearly'},{value:'day',label:'Daily'}])}{field('furnishing','Furnishing')}{field('availableFrom','Available from','date')}{field('features','Features (separate with commas)')}<p className="fine-print">A draft is private until it passes publication review. Private unit addresses are shared only through authorized property workflows.</p>{error&&<ErrorBox message={error}/>} {Object.entries(fields).filter(([name])=>name==='unit').flatMap(([name,messages])=>messages.map((message,index)=><p className="field-error" role="alert" key={name+index}>{message}</p>))}<button className="button" type="submit" disabled={busy}>{busy?'Saving draft…':'Save property draft'}</button></form>;
}
