'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk,financialReversal,type FinancialReversalRecord} from '@haven/contracts';
import {ErrorBox,Spinner} from './index';
export function FinancialReversalForm({id,recordType,onSaved}:{id:string;recordType:'charge'|'payment';onSaved:()=>void}){
 const [record,setRecord]=useState<FinancialReversalRecord|null>(null),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0),keys=useRef(new Map<string,string>());
 useEffect(()=>{let live=true;setRecord(null);sdk.FinancialReversalsController_read({params:{recordType,id}}).then(r=>{if(live)setRecord(r.data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id,recordType,tick]);
 if(!record)return error?<ErrorBox message={error}/>:<Spinner/>;
 return <form className="field-form" noValidate onSubmit={async e=>{e.preventDefault();setError('');const x=financialReversal.safeParse({version:record.version,leaseVersion:record.leaseVersion,unitVersion:record.unitVersion,grantVersion:record.grantVersion,reason,confirm});if(!x.success){setError('Enter a reason of 5–500 characters and confirm the reversal.');return;}const fingerprint=JSON.stringify(x.data);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());setBusy(true);try{const args={params:{id},body:x.data,headers:{'idempotency-key':keys.current.get(fingerprint)!}};if(recordType==='payment')await sdk.FinancialReversalsController_reversePayment(args);else await sdk.FinancialReversalsController_reverseCharge(args);onSaved();}catch(e){setError(e instanceof Error?e.message:'Unable to reverse. Your reason and confirmation are retained.');}finally{setBusy(false);}}}>
 <p>Original {recordType}: {record.currency} {record.amount} · {record.reference} · version {record.version}</p><p>A linked bookkeeping reversal preserves the original record and undoes its active allocations. No funds are transferred.</p>{record.reversal?<><h3>Retained reversal</h3><p>Recorded {new Date(record.reversal.at).toLocaleString('en-GB')}.</p><p>{record.reversal.reason||'Historical reversal: original reason and actor attribution may be unknown.'}</p>{record.reversal.native?<p>Retained allocation undo: {record.reversal.undoneAllocationIds.length}.</p>:<p>Original allocation undo attribution is unavailable.</p>}</>:record.eligible?<><label className="field">Reason for reversal<textarea aria-label="Reversal reason" value={reason} maxLength={500} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/> I confirm reversing this original record and undoing its allocations.</label></>:<p>This record cannot be reversed. Only original posted charges and payment evidence are eligible.</p>}{error&&<ErrorBox message={error}/>}<button type="button" className="button secondary" disabled={busy} onClick={()=>{setError('');setTick(t=>t+1);}}>Refresh reversal</button>{record.eligible&&<button className="button" disabled={busy}>{busy?'Reversing…':'Confirm bookkeeping reversal'}</button>}
 </form>;
}
