'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk,leaseRenewal,leaseEnding,type LeaseWorkflowRecord,type LeaseDraftSource} from '@haven/contracts';
import {ErrorBox,Spinner} from './index';
export function LeaseLifecycleForm({id,mode,onSaved}:{id:string;mode:'renew'|'end'|'history';onSaved:()=>void}){
 const [record,setRecord]=useState<LeaseWorkflowRecord|null>(null),[source,setSource]=useState<LeaseDraftSource|null>(null),[start,setStart]=useState(''),[end,setEnd]=useState(''),[rent,setRent]=useState(''),[due,setDue]=useState('1'),[reason,setReason]=useState(''),[kind,setKind]=useState<'completed'|'terminated'>('completed'),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),keys=useRef(new Map<string,string>());
 useEffect(()=>{let live=true;sdk.LeaseLifecycleController_read({params:{id}}).then(async r=>{if(!live)return;setRecord(r.data);setRent(r.data.rent);setDue(String(r.data.dueDay??1));if(mode==='renew'){const options=await sdk.LeaseDraftsController_options({params:{unitId:r.data.unitId}});if(live)setSource(options.data);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id,mode]);
 const receipt=(body:unknown)=>{const fingerprint=JSON.stringify(body);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());return keys.current.get(fingerprint)!;};
 if(!record)return error?<ErrorBox message={error}/>:<Spinner/>;
 return <form noValidate onSubmit={async e=>{e.preventDefault();if(mode==='history')return;setError('');const tenant=source?.tenants.find(t=>t.id===record.tenantId),next=leaseRenewal.safeParse({version:record.version,unitVersion:source?.unitVersion,grantVersion:source?.grantVersion,tenantVersion:tenant?.version,startDate:start,endDate:end,rent,currency:source?.currency,rentPeriod:'month',dueDay:Number(due),documents:[],reason}),ending=leaseEnding.safeParse({version:record.version,kind,reason,confirm});if(mode==='renew'&&(!next.success||start<=record.endDate)){setError('Choose a valid term after the original end date, a positive decimal rent, due day and reason.');return;}if(mode==='end'&&!ending.success){setError('Provide an ending reason and confirm availability review.');return;}setBusy(true);try{if(mode==='renew'&&next.success)await sdk.LeaseLifecycleController_renew({params:{id},body:next.data,headers:{'idempotency-key':receipt(next.data)}});else if(ending.success)await sdk.LeaseLifecycleController_end({params:{id},body:ending.data,headers:{'idempotency-key':receipt(ending.data)}});onSaved();}catch(e){setError(e instanceof Error?e.message:'Unable to save. Your entries are retained for retry.');}finally{setBusy(false);}}}>
 <p>{record.community} · {record.tenant}</p><p>Recorded term: {record.startDate}–{record.endDate} · {record.currency} {record.rent}/month · {record.status} · version {record.version}</p>{!record.native&&<p className="fine-print">Historical lease: original creator, approval and due-day details may be unknown. Stored terms are retained.</p>}
 {record.previousLeaseId&&<p>Previous term: {record.previousLeaseId}</p>}{record.nextLeaseId&&<p>Retained next term: {record.nextLeaseId}</p>}{record.ending&&<div role="status"><p>{record.ending.kind}: {record.ending.reason}</p><p>Recorded {new Date(record.ending.at).toLocaleString('en-GB')}. Availability review required; ending does not publish a rental listing.</p></div>}
 {mode==='renew'&&<><p>The original lease is retained. The next term is a draft until separately activated. Edit the new draft to attach its private documents; old files remain with their original term.</p><label>Next term starts<input aria-label="Next term starts" type="date" value={start} disabled={busy} onChange={e=>setStart(e.target.value)}/></label><label>Next term ends<input aria-label="Next term ends" type="date" value={end} disabled={busy} onChange={e=>setEnd(e.target.value)}/></label><label>Monthly rent ({source?.currency||record.currency})<input aria-label="Monthly renewal rent" inputMode="decimal" value={rent} disabled={busy} onChange={e=>setRent(e.target.value)}/></label><label>Monthly due day (1–28)<input aria-label="Monthly renewal due day" inputMode="numeric" value={due} disabled={busy} onChange={e=>setDue(e.target.value)}/></label></>}
 {mode==='end'&&<><p>Ending retains all terms, documents and financial history. Rental offers stay withdrawn until availability is reviewed through the publication workflow.</p><label>Ending type<select aria-label="Ending type" value={kind} disabled={busy} onChange={e=>setKind(e.target.value as 'completed'|'terminated')}><option value="completed">Completed term</option><option value="terminated">Early termination</option></select></label><label><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/> I confirm ending and understand that availability requires review.</label></>}
 {mode!=='history'&&<label>Reason<textarea aria-label="Lease workflow reason" value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>}{error&&<ErrorBox message={error}/>}<h3>Retained lease history</h3>{record.activity.length?<ol>{record.activity.map(h=><li key={h.version}>Version {h.version}: {h.action.replaceAll('_',' ')} · {new Date(h.at).toLocaleString('en-GB')}{h.reason&&' · '+h.reason}</li>)}</ol>:<p>No native history recorded for this historical term.</p>}{mode!=='history'&&<button className="button" disabled={busy||mode==='renew'&&!source}>{busy?'Saving…':mode==='renew'?'Create next term draft':'Confirm lease ending'}</button>}
 </form>;
}
