'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk,paymentAllocation,type AllocationLedgerRecord} from '@haven/contracts';
import {ErrorBox,Spinner} from './index';
export function PaymentAllocationForm({onSaved}:{onSaved:()=>void}){
 const [leases,setLeases]=useState<{id:string;community:string;tenant:string;start_date:string;end_date:string}[]>([]),[leaseId,setLeaseId]=useState(''),[ledger,setLedger]=useState<AllocationLedgerRecord|null>(null),[paymentId,setPaymentId]=useState(''),[chargeId,setChargeId]=useState(''),[paymentPage,setPaymentPage]=useState(1),[chargePage,setChargePage]=useState(1),[amount,setAmount]=useState(''),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0),keys=useRef(new Map<string,string>());
 useEffect(()=>{let live=true;sdk.ManagementController_leases({}).then(r=>{if(live)setLeases(r.data.filter(l=>['active','ended'].includes(l.status)));}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setLedger(null);if(leaseId)sdk.PaymentAllocationsController_ledger({params:{id:leaseId},query:{paymentPage,chargePage}}).then(r=>{if(live)setLedger(r.data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[leaseId,paymentPage,chargePage,tick]);
 const payment=ledger?.payments.find(p=>p.id===paymentId),charge=ledger?.charges.find(c=>c.id===chargeId);
 return <form className="field-form" noValidate onSubmit={async e=>{e.preventDefault();setError('');const x=paymentAllocation.safeParse({version:0,leaseId,leaseVersion:ledger?.leaseVersion,unitVersion:ledger?.unitVersion,grantVersion:ledger?.grantVersion,paymentId,paymentVersion:payment?.version,chargeId,chargeVersion:charge?.version,amount,currency:ledger?.currency,confirm});if(!x.success){setError('Select a posted payment and charge on this lease, enter a positive decimal amount and confirm.');return;}const fingerprint=JSON.stringify(x.data);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());setBusy(true);try{await sdk.PaymentAllocationsController_create({body:x.data,headers:{'idempotency-key':keys.current.get(fingerprint)!}});onSaved();}catch(e){setError(e instanceof Error?e.message:'Allocation failed. Your entries are retained for retry.');}finally{setBusy(false);}}}>
 <p>Allocate recorded payment credit to posted charges on the same lease. No funds are transferred. Reversed records and payment drafts are excluded.</p><label className="field">Lease<select aria-label="Allocation lease" value={leaseId} disabled={busy} onChange={e=>{setLeaseId(e.target.value);setPaymentId('');setChargeId('');setPaymentPage(1);setChargePage(1);setConfirm(false);setError('');}}><option value="">Choose a lease…</option>{leases.map(l=><option key={l.id} value={l.id}>{l.community} · {l.tenant} · {l.start_date.slice(0,10)}–{l.end_date.slice(0,10)}</option>)}</select></label>{leaseId&&!ledger&&!error&&<Spinner/>}{ledger&&<><div className="ops-summary">{[['Outstanding',ledger.totals.outstanding],['Unallocated credit',ledger.totals.credit],['Allocated',ledger.totals.allocated]].map(([label,value])=><p key={label}>{label}: {ledger.currency} {value}</p>)}</div><label className="field">Posted payment<select aria-label="Allocation payment" value={paymentId} disabled={busy} onChange={e=>setPaymentId(e.target.value)}><option value="">Select payment credit…</option>{ledger.payments.map(p=><option key={p.id} value={p.id}>{p.reference} · available {ledger.currency} {p.available}</option>)}</select></label>{payment&&<p>Available payment credit: {ledger.currency} {payment.available}</p>}<nav aria-label="Payment credit pages"><button type="button" className="button secondary" disabled={busy||paymentPage===1} onClick={()=>{setPaymentId('');setPaymentPage(p=>p-1);}}>Previous payments</button><button type="button" className="button secondary" disabled={busy||paymentPage*20>=ledger.paymentTotal} onClick={()=>{setPaymentId('');setPaymentPage(p=>p+1);}}>Next payments</button></nav><label className="field">Posted charge<select aria-label="Allocation charge" value={chargeId} disabled={busy} onChange={e=>setChargeId(e.target.value)}><option value="">Select outstanding charge…</option>{ledger.charges.map(c=><option key={c.id} value={c.id}>{c.period} · {c.kind} · outstanding {ledger.currency} {c.outstanding}</option>)}</select></label>{charge&&<p>Outstanding selected charge: {ledger.currency} {charge.outstanding}</p>}<nav aria-label="Outstanding charge pages"><button type="button" className="button secondary" disabled={busy||chargePage===1} onClick={()=>{setChargeId('');setChargePage(p=>p-1);}}>Previous charges</button><button type="button" className="button secondary" disabled={busy||chargePage*20>=ledger.chargeTotal} onClick={()=>{setChargeId('');setChargePage(p=>p+1);}}>Next charges</button></nav></>}
 <label className="field">Allocation amount ({ledger?.currency||'lease currency'})<input aria-label="Allocation amount" inputMode="decimal" value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/> I confirm this bookkeeping allocation on the selected lease.</label>{error&&<ErrorBox message={error}/>}<button type="button" className="button secondary" disabled={busy||!leaseId} onClick={()=>{setError('');setTick(t=>t+1);}}>Refresh balances</button><button className="button" disabled={busy||!ledger||!payment||!charge}>{busy?'Allocating…':'Record allocation'}</button>
 </form>;
}
