'use client';
import {useEffect,useRef,useState} from 'react';
import {sdk,paymentEvidenceCreate,paymentEvidenceUpdate,paymentEvidencePost,type PaymentEvidenceRecord,type PaymentEvidenceSource} from '@haven/contracts';
import {ErrorBox,Spinner} from './index';
export function PaymentEvidenceForm({id,mode='draft',onSaved}:{id?:string;mode?:'draft'|'post'|'history';onSaved:()=>void}){
 const [leases,setLeases]=useState<{id:string;community:string;tenant:string}[]>([]),[leaseId,setLeaseId]=useState(''),[authority,setAuthority]=useState<PaymentEvidenceSource|null>(null),[record,setRecord]=useState<PaymentEvidenceRecord|null>(null),[amount,setAmount]=useState(''),[source,setSource]=useState<'bank_statement'|'receipt'|'manual_evidence'>('bank_statement'),[reference,setReference]=useState(''),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),keys=useRef(new Map<string,string>());
 useEffect(()=>{let live=true;if(id)sdk.PaymentEvidenceController_read({params:{id}}).then(r=>{if(live){setRecord(r.data);setLeaseId(r.data.leaseId);setAmount(r.data.amount);setReference(r.data.reference);if(['bank_statement','receipt','manual_evidence'].includes(r.data.source))setSource(r.data.source as typeof source);}}).catch(e=>{if(live)setError(e.message);});else sdk.ManagementController_leases({}).then(r=>{if(live)setLeases(r.data.filter(l=>['active','ended'].includes(l.status)));}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id]);
 useEffect(()=>{let live=true;setAuthority(null);if(leaseId&&mode!=='history')sdk.PaymentEvidenceController_options({params:{leaseId}}).then(r=>{if(live)setAuthority(r.data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[leaseId,mode]);
 const stale=!!record&&!!authority&&(record.leaseVersion!==authority.leaseVersion||record.unitVersion!==authority.unitVersion||record.grantVersion!==authority.grantVersion);
 if(id&&!record)return error?<ErrorBox message={error}/>:<Spinner/>;
 return <form className="field-form" noValidate onSubmit={async e=>{e.preventDefault();if(mode==='history')return;setError('');if(!authority)return;const terms={leaseVersion:authority.leaseVersion,unitVersion:authority.unitVersion,grantVersion:authority.grantVersion,amount,currency:authority.currency,source,reference},create=paymentEvidenceCreate.safeParse({version:0,leaseId,...terms}),update=paymentEvidenceUpdate.safeParse({version:record?.version,...terms}),post=paymentEvidencePost.safeParse({version:record?.version,leaseVersion:record?.leaseVersion,unitVersion:record?.unitVersion,grantVersion:record?.grantVersion,confirm});const body=mode==='post'?post:id?update:create;if(!body.success){setError(mode==='post'?'Confirm posting of this saved payment evidence.':'Choose a granted lease, positive decimal amount, source and reference.');return;}const fingerprint=JSON.stringify(body.data);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());const headers={'idempotency-key':keys.current.get(fingerprint)!};setBusy(true);try{if(mode==='post'&&id&&post.success)await sdk.PaymentEvidenceController_post({params:{id},body:post.data,headers});else if(id&&update.success)await sdk.PaymentEvidenceController_update({params:{id},body:update.data,headers});else if(create.success)await sdk.PaymentEvidenceController_create({body:create.data,headers});onSaved();}catch(e){setError(e instanceof Error?e.message:'Unable to save. Your entries are retained for retry.');}finally{setBusy(false);}}}>
 <p>Payment records are bookkeeping evidence. No funds are transferred. Drafts do not affect the recorded balance; posted data is immutable.</p>{!id&&<label className="field">Lease<select aria-label="Payment evidence lease" value={leaseId} disabled={busy} onChange={e=>{setLeaseId(e.target.value);setError('');}}><option value="">Choose active or ended lease…</option>{leases.map(l=><option key={l.id} value={l.id}>{l.community} · {l.tenant} · {l.id}</option>)}</select></label>}{record&&<p>Recorded evidence: {record.currency} {record.amount} · {record.source.replaceAll('_',' ')} · {record.reference} · {record.status} · version {record.version}</p>}{record&&!record.native&&<p className="fine-print">Historical posted evidence. Original posting time and approving actor may be unknown; known stored data is retained.</p>}
 {mode==='draft'&&<><label className="field">Amount ({authority?.currency||record?.currency||'lease currency'})<input aria-label="Payment evidence amount" inputMode="decimal" value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Evidence source<select aria-label="Payment evidence source" value={source} disabled={busy} onChange={e=>setSource(e.target.value as typeof source)}><option value="bank_statement">Bank statement</option><option value="receipt">Receipt</option><option value="manual_evidence">Manual evidence</option></select></label><label className="field">Reference<input aria-label="Payment evidence reference" value={reference} disabled={busy} onChange={e=>setReference(e.target.value)}/></label></>}
 {mode==='post'&&<>{stale&&<p role="status">Lease or grant changed. Edit and save current draft authority before posting.</p>}<label><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/> I confirm posting the saved evidence without transferring funds.</label></>}{record?.postedAt&&<p>Posted {new Date(record.postedAt).toLocaleString('en-GB')}.</p>}{record&&<><h3>Retained payment history</h3>{record.activity.length?<ol>{record.activity.map(h=><li key={h.version}>Version {h.version}: {h.action.replaceAll('_',' ')} · {new Date(h.at).toLocaleString('en-GB')}</li>)}</ol>:<p>No native history recorded for this historical payment.</p>}</>}{error&&<ErrorBox message={error}/>} {mode!=='history'&&<button className="button" disabled={busy||!authority||mode==='post'&&stale}>{busy?'Saving…':mode==='post'?'Confirm payment posting':'Save payment draft'}</button>}
 </form>;
}
