'use client';
import {useEffect,useRef,useState} from 'react';
import {api,quoteChange} from '@haven/contracts';
import type {QuoteRecord} from '@haven/contracts';
import {Spinner,ErrorBox,Empty,Badge} from './index';
type Quote=QuoteRecord;
export function QuoteWorkspace({professional=false}:{professional?:boolean}){
 const [rows,setRows]=useState<Quote[]|null>(null),[selected,setSelected]=useState(''),[record,setRecord]=useState<Quote|null>(null),[page,setPage]=useState(1),[status,setStatus]=useState(''),[error,setError]=useState(''),[detailError,setDetailError]=useState(''),[tick,setTick]=useState(0),[busy,setBusy]=useState(false),pending=useRef<{body:string;key:string}|null>(null),root=professional?'/ops/quotes':'/me/quotes';
 useEffect(()=>{const load=()=>setSelected(new URLSearchParams(window.location.search).get('quote')||'');load();window.addEventListener('popstate',load);return()=>window.removeEventListener('popstate',load);},[]);
 useEffect(()=>{let live=true;setRows(null);setError('');api<Quote[]>(root+'?'+new URLSearchParams({page:String(page),...(status?{status}:{})})).then(r=>{if(live)setRows(r.data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[root,page,status,tick]);
 useEffect(()=>{let live=true;setRecord(null);setDetailError('');if(selected)api<Quote>(root+'/'+selected).then(r=>{if(live)setRecord(r.data);}).catch(e=>{if(live)setDetailError(e.message);});return()=>{live=false;};},[root,selected,tick]);
 const choose=(id:string)=>{const url=new URL(window.location.href);url.searchParams.set('quote',id);window.history.pushState(null,'',url);setSelected(id);};
 return <section className="workspace-panel" aria-label="Quote requests"><h2>{professional?'Assigned quote requests':'Your quote requests'}</h2><p>Nonbinding project inquiries. No payment, booking or contract is created by these statuses.</p><label className="field"><span>Request status</span><select aria-label="Request status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['requested','assigned','contacted','quoted','closed'].map(s=><option key={s}>{s}</option>)}</select></label><button className="button secondary" onClick={()=>setTick(t=>t+1)}>Refresh requests</button>{error?<ErrorBox message={error} retry={()=>setTick(t=>t+1)}/>:rows===null?<Spinner/>:!rows.length?<Empty title="No quote requests" description="Requests within your access will appear here."/>:<div className="record-list">{rows.map(q=><div className="record-row" key={q.id}><div><h3>{q.providerName}</h3><p>{q.serviceCategory||'Historical request'} · {q.budget===null?'Budget not supplied':(q.currency||'Currency unknown')+' '+q.budget}</p><Badge>{q.status}</Badge></div><button className="button secondary" onClick={()=>choose(q.id)}>View request</button></div>)}</div>}<div className="pagination"><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous page</button><span>Page {page}</span><button className="button secondary" disabled={!rows||rows.length<20} onClick={()=>setPage(p=>p+1)}>Next page</button></div>
 {selected&&<section aria-label="Selected quote request">{detailError&&<ErrorBox message={detailError} retry={()=>setTick(t=>t+1)}/>}{!record?!detailError&&<Spinner/>:<><h3>{record.providerName}</h3><Badge>{record.status}</Badge><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{record.description}</p><p style={{overflowWrap:'anywhere'}}>{record.contactName||'Contact not recorded'} · {record.contactEmail||'Email not recorded'} · {record.contactPhone||'Phone not recorded'}</p><p>{record.budget===null?'Budget not supplied':(record.currency||'Currency unknown')+' '+record.budget}</p><h4>Request timeline</h4>{record.historical&&<p>Historical request: recipient, consent and status history were not recorded. No missing facts have been inferred.</p>}<ol>{record.activity.map(a=><li key={a.version}><strong>{a.status}</strong> · {new Date(a.at).toLocaleString('en-GB')}<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{a.note}</p></li>)}</ol>{professional&&record.canManage&&record.status!=='closed'&&<form key={record.id+':'+record.version} onSubmit={async e=>{e.preventDefault();const parsed=quoteChange.safeParse({...Object.fromEntries(new FormData(e.currentTarget)),version:record.version});if(!parsed.success){setDetailError(parsed.error.issues.map(i=>i.message).join(' · '));return;}const body=JSON.stringify(parsed.data);if(pending.current?.body!==record.id+body)pending.current={body:record.id+body,key:crypto.randomUUID()};setBusy(true);try{await api(root+'/'+record.id,{method:'PATCH',headers:{'idempotency-key':pending.current.key},body});setTick(t=>t+1);}catch(e){setDetailError(e instanceof Error?e.message:'Status update failed');}finally{setBusy(false);}}}><label className="field"><span>Next status</span><select aria-label="Next status" name="status">{({requested:['assigned','contacted','closed'],assigned:['contacted','closed'],contacted:['quoted','closed'],quoted:['closed']} as Record<string,string[]>)[record.status]?.map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Update shared with customer</span><textarea name="note" required minLength={5} maxLength={1000}/></label><p>Record actual contact or discussion. The customer can read this note; do not include private internal information.</p><button className="button" disabled={busy}>{busy?'Saving…':'Save request status'}</button></form>}</>}</section>}</section>;
}
