'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {rentalTermsUpdate,type RentalTermsRecord} from '@haven/contracts';
import {Spinner,ErrorBox} from './index';
type Record=RentalTermsRecord;
type Request=(path:string,init?:RequestInit)=>Promise<any>;
export function RentalTermsForm({listingId,request,onSaved}:{listingId:string;request:Request;onSaved:()=>Promise<void>}){
 const [record,setRecord]=useState<Record|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[values,setValues]=useState({mode:'entire',billingPeriod:'month',depositAmount:'',minimumMonths:'',utilities:'',moveInDate:'',roomAttributes:'',roomLabel:'',roomArea:''});
 async function load(){try{const row=(await request('/ops/listings/'+listingId+'/rental-terms')).data as Record;setRecord(row);setValues({mode:row.mode||'entire',billingPeriod:row.billingPeriod||'month',depositAmount:row.depositAmount??'',minimumMonths:row.minimumMonths?.toString()||'',utilities:row.utilities.join(', '),moveInDate:row.moveInDate||'',roomAttributes:row.roomAttributes.join(', '),roomLabel:row.roomLabel||'',roomArea:row.unitKind==='room'?row.area:''});setError('');}catch(e){setError(e instanceof Error?e.message:'Rental terms could not be loaded.');}}
 useEffect(()=>{void load();},[listingId]);
 const labels=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean);
 async function submit(event:FormEvent){event.preventDefault();if(!record)return;const parsed=rentalTermsUpdate.safeParse({version:record.version,unitVersion:record.unitVersion,mode:values.mode,billingPeriod:values.billingPeriod,depositAmount:values.depositAmount||null,minimumMonths:values.minimumMonths?Number(values.minimumMonths):null,utilities:labels(values.utilities),moveInDate:values.moveInDate||null,roomAttributes:labels(values.roomAttributes),...(values.mode==='shared'?{room:{label:values.roomLabel,area:values.roomArea}}:{})});if(!parsed.success){setError(parsed.error.issues.map(issue=>issue.path.join('.')+': '+issue.message).join('. '));return;}setBusy(true);setError('');try{await request('/ops/listings/'+listingId+'/rental-terms',{method:'PATCH',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify(parsed.data)});await onSaved();}catch(e){setError(e instanceof Error?e.message:'Rental terms could not be saved.');}finally{setBusy(false);}}
 function field(name:keyof typeof values,label:string,type='text'){return <label className="field"><span>{label}</span><input aria-label={label} type={type} value={values[name]} disabled={busy} onChange={e=>setValues({...values,[name]:e.target.value})}/></label>;}
 if(!record)return error?<ErrorBox message={error} retry={()=>void load()}/>:<Spinner/>;
 return <section aria-labelledby="rental-terms-editor"><h3 id="rental-terms-editor">Rental terms and unit scope</h3><p>Rent and deposit amounts are in {record.currency}. Shared rentals use a separate room inside the selected property; room listings keep that room scope.</p>{error&&<ErrorBox message={error} retry={()=>void load()}/>}<form className="field-form" onSubmit={submit} noValidate><label className="field"><span>Rental mode</span><select aria-label="Rental mode" value={values.mode} disabled={busy||record.unitKind==='room'} onChange={e=>setValues({...values,mode:e.target.value})}><option value="entire">Entire property</option><option value="shared">Shared room</option></select></label><label className="field"><span>Terms billing period</span><select aria-label="Terms billing period" value={values.billingPeriod} disabled={busy} onChange={e=>setValues({...values,billingPeriod:e.target.value})}><option value="month">Monthly</option><option value="year">Yearly</option><option value="day">Daily</option></select></label>{field('depositAmount','Deposit amount ('+record.currency+')')}{field('minimumMonths','Minimum tenancy (months)')}{field('utilities','Utilities included (separate with commas)')}{field('moveInDate','Move-in date','date')}{field('roomAttributes','Room attributes (separate with commas)')}{values.mode==='shared'&&<>{field('roomLabel','Room label')}{field('roomArea','Room area (m²)')}</>}<p className="fine-print">Leave a deposit or minimum tenancy empty when not provided. Furnishing and the rent amount are recorded in the property draft above. Terms are editable before publication review.</p><button className="button" disabled={busy||!['draft','rejected'].includes(record.status)}>{busy?'Saving rental terms…':'Save rental terms'}</button></form></section>;
}
