'use client';
import {useEffect,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {sdk,supportCreate,supportTriage,type SupportRecord} from '@haven/contracts';
import {Dialog,ErrorBox,Spinner,Empty,Badge} from './index';
function caseURL(id:string,page:number){const u=new URL(location.href);if(id){u.searchParams.set('case',id);u.searchParams.delete('caseListing');}else u.searchParams.delete('case');if(page>1)u.searchParams.set('casePage',String(page));else u.searchParams.delete('casePage');history.replaceState(null,'',u);}
export function SupportCases({scopeKey,city='bj',professional=false}:{scopeKey:string;city?:string;professional?:boolean}){
 const [page,setPage]=useState(1),[selected,setSelected]=useState(''),[create,setCreate]=useState(false),[ready,setReady]=useState(false),[tick,setTick]=useState(0),[notice,setNotice]=useState('');
 useEffect(()=>{const q=new URLSearchParams(location.search);setSelected(q.get('case')||'');setPage(Math.max(1,Math.min(10000,Math.trunc(Number(q.get('casePage'))||1))));if(!professional&&q.get('caseListing'))setCreate(true);setReady(true);},[professional]);
 const q=useQuery({queryKey:['support-cases',scopeKey,professional,page,tick],enabled:ready,gcTime:0,retry:false,queryFn:({signal})=>(professional?sdk.AdministrationController_supportQueue:sdk.AdministrationController_cases)({query:{page},signal})});
 const choose=(id:string)=>{setSelected(id);caseURL(id,page);},saved=(id?:string)=>{setTick(t=>t+1);setNotice('Support case saved.');setCreate(false);if(id)choose(id);};
 return <section className="support-cases" aria-label={professional?'Support case queue':'Your support cases'}><div className="section-heading"><h2>{professional?'Support cases':'Your requests'}</h2>{!professional&&<button className="button" onClick={()=>setCreate(true)}>New support request</button>}</div>{notice&&<p role="status">{notice}</p>}<p className="fine-print">{professional?'Only current platform support staff can triage these cases.':'Your case and attachments are private to you and authorized support staff. A listing complaint does not automatically withdraw a property.'}</p>{q.isPending?<Spinner/>:q.isError?<ErrorBox message={q.error.message} retry={()=>q.refetch()}/>:!q.data.data.items.length?<Empty title="No support cases" description="Submitted requests will appear here."/>:<div className="record-list">{q.data.data.items.map(r=><article className="record-row" key={r.id}><div><h3>{r.subject}</h3><p>{r.category} · {r.createdAt.slice(0,10)}{r.assigned?' · Assigned to support':''}</p>{r.publicReply&&<p>{r.publicReply}</p>}</div><Badge>{r.status}</Badge><button className="button secondary" aria-label={'View support case '+r.id} onClick={()=>choose(r.id)}>View case</button></article>)}</div>}<nav className="row-actions" aria-label="Support case pages"><button className="button secondary" disabled={page<=1} onClick={()=>{setPage(page-1);caseURL(selected,page-1);}}>Previous cases</button><span>Page {page} · {q.data?.data.total||0} cases</span><button className="button secondary" disabled={page*20>=(q.data?.data.total||0)} onClick={()=>{setPage(page+1);caseURL(selected,page+1);}}>Next cases</button><button className="button secondary" onClick={()=>setTick(t=>t+1)}>Refresh cases</button></nav>{create&&<Dialog title="Support request" className="support-dialog" onClose={()=>setCreate(false)}><SupportCreateForm city={city} onSaved={saved}/></Dialog>}{selected&&<Dialog title="Support case" className="support-dialog" onClose={()=>choose('')}><SupportDetails id={selected} scopeKey={scopeKey} professional={professional} onSaved={()=>saved()}/></Dialog>}</section>;
}
function SupportCreateForm({city,onSaved}:{city:string;onSaved:(id:string)=>void}){
 const [subject,setSubject]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState<'General'|'Listing complaint'|'Account'|'Viewing'|'Other'>('General'),[text,setText]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[listing,setListing]=useState<{id:string;version:number;title:string}|null>(null),[attachments,setAttachments]=useState<{assetId:string;version:number;label:string}[]>([]),[rights,setRights]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),keys=useRef(new Map<string,string>());
 useEffect(()=>{const id=new URLSearchParams(location.search).get('caseListing');if(!id)return;let live=true;setCategory('Listing complaint');sdk.DiscoveryController_listing({params:{id},query:{city}}).then(r=>{if(live)setListing({id:r.data.id,version:r.data.version,title:r.data.title});}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[city]);
 const choices=useQuery({queryKey:['support-public-listings',city,search,page],enabled:category==='Listing complaint',queryFn:({signal})=>sdk.DiscoveryController_listings({query:{city,text:search,page,limit:20},signal}),retry:false});
 async function upload(file:File){setError('');if(rights.trim().length<5){setError('Describe your right to share this file before uploading.');return;}if(attachments.length>=6){setError('Attach at most six files.');return;}if(!['image/jpeg','image/png','application/pdf'].includes(file.type)){setError('Choose a JPEG, PNG or PDF.');return;}setBusy(true);try{const intent=(await sdk.MediaController_intent({body:{mime:file.type as 'image/png',size:file.size,rights,visibility:'private',purpose:file.type==='application/pdf'?'document':'photo'}})).data;const r=await fetch(intent.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!r.ok){const response=await r.json();throw new Error(response.error?.message||'File upload failed');}const asset=(await sdk.MediaController_status({params:{id:intent.id}})).data;if(asset.status!=='approved'||!asset.scan_at)throw new Error('File is not approved and scanned');setAttachments(a=>[...a,{assetId:asset.id,version:asset.version,label:file.name.slice(0,120).padEnd(2,'_')}]);}catch(e){setError(e instanceof Error?e.message:'Upload failed; your case inputs are retained.');}finally{setBusy(false);}}
 return <form className="field-form" noValidate onSubmit={async e=>{e.preventDefault();setError('');const x=supportCreate.safeParse({version:0,subject,description,category,listing:listing?{id:listing.id,version:listing.version}:null,attachments,consent});if(!x.success){setError('Enter a 5–120 character subject, 10–3000 character description, select a listing for complaints, label attachments and confirm.');return;}const fingerprint=JSON.stringify(x.data);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());setBusy(true);try{const r=await sdk.AdministrationController_support({body:x.data,headers:{'Idempotency-Key':keys.current.get(fingerprint)!}});onSaved(r.data.id);}catch(e){setError(e instanceof Error?e.message:'Case could not be saved; your inputs are retained.');}finally{setBusy(false);}}}>
 <label className="field">Subject<input aria-label="Support subject" maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="field">Category<select aria-label="Support category" value={category} onChange={e=>{setCategory(e.target.value as typeof category);if(e.target.value!=='Listing complaint')setListing(null);}}>{['General','Listing complaint','Account','Viewing','Other'].map(c=><option key={c}>{c}</option>)}</select></label>{category==='Listing complaint'&&<fieldset><legend>Published property</legend>{listing&&<p>Selected: {listing.title}</p>}<label className="field">Find a published listing<input aria-label="Find a published listing" value={text} onChange={e=>setText(e.target.value)}/></label><button type="button" className="button secondary" onClick={()=>{setSearch(text);setPage(1);}}>Search listings</button>{choices.isPending?<Spinner/>:choices.isError?<ErrorBox message={choices.error.message}/>:<><label className="field">Complaint listing<select aria-label="Complaint listing" value={listing?.id||''} onChange={e=>{const r=choices.data.data.find(l=>l.id===e.target.value);if(r)setListing({id:r.id,version:r.version,title:r.title});}}><option value="">Choose a listing</option>{listing&&!choices.data.data.some(r=>r.id===listing.id)&&<option value={listing.id}>{listing.title}</option>}{choices.data.data.map(r=><option value={r.id} key={r.id}>{r.title} · {r.community}</option>)}</select></label><div className="row-actions"><button type="button" className="button secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous listings</button><button type="button" className="button secondary" disabled={choices.data.data.length<20} onClick={()=>setPage(page+1)}>Next listings</button></div></>}</fieldset>}
 <label className="field">How can we help?<textarea aria-label="Support description" maxLength={3000} value={description} onChange={e=>setDescription(e.target.value)}/></label><fieldset><legend>Private attachments (optional)</legend><p>Up to six JPEG/PNG photos or PDF documents, scanned before attachment.</p><label className="field">Your right to share these files<input aria-label="Attachment sharing rights" maxLength={300} value={rights} onChange={e=>setRights(e.target.value)}/></label><label className="field">Upload a private attachment<input aria-label="Upload a private support attachment" type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy||attachments.length>=6} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>{attachments.map((a,i)=><div className="support-attachment" key={a.assetId}><label className="field">Attachment label<input aria-label={'Attachment label '+(i+1)} maxLength={120} value={a.label} onChange={e=>setAttachments(v=>v.map((r,j)=>j===i?{...r,label:e.target.value}:r))}/></label><button className="button secondary" type="button" onClick={()=>setAttachments(v=>v.filter(r=>r.assetId!==a.assetId))}>Remove attachment</button></div>)}</fieldset><label className="checkbox"><input aria-label="Confirm support case sharing" type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Share this case and its attachments with authorized support staff.</label>{error&&<ErrorBox message={error}/>}<button className="button" disabled={busy}>{busy?'Saving…':'Send request'}</button></form>;
}
function SupportDetails({id,scopeKey,professional,onSaved}:{id:string;scopeKey:string;professional:boolean;onSaved:()=>void}){
 const q=useQuery({queryKey:['support-case',scopeKey,id,professional],gcTime:0,retry:false,queryFn:({signal})=>(professional?sdk.AdministrationController_supportProfessionalDetail:sdk.AdministrationController_supportDetail)({params:{id},signal})});
 if(q.isPending)return <Spinner/>;if(q.isError)return <ErrorBox message={q.error.message} retry={()=>q.refetch()}/>;const r=q.data.data;
 return <section aria-label="Support case details"><h2>{r.subject}</h2><Badge>{r.status}</Badge><p>{r.description}</p><p>{r.category} · version {r.version}{r.assigned?' · Assigned to support':''}</p>{r.historical&&<p className="fine-print">Historical case: original actor attribution and timeline may be unavailable.</p>}{r.listing&&<p>Listing recorded at version {r.listing.version}: <a className="text-link" href={r.listing.url}>{r.listing.title}</a></p>}{r.publicReply&&<p className="public-note">{r.publicReply}</p>}<h3>Attachments</h3>{!r.attachments.length?<p>No attachments supplied.</p>:r.attachments.map(a=><p key={a.id}><a className="text-link" href={a.url} target="_blank" rel="noopener">{a.label}</a> · {a.mime==='application/pdf'?'PDF':'Private photo'}</p>)}<h3>Public case history</h3>{r.activity.map(h=><article className="support-history" key={h.version}><strong>{h.status} · version {h.version}</strong><p>{h.message||'Case opened'}</p><time>{h.at}</time></article>)}{professional&&r.status==='open'&&<SupportTriageForm record={r} onSaved={()=>{void q.refetch();onSaved();}}/>}</section>;
}
function SupportTriageForm({record,onSaved}:{record:SupportRecord;onSaved:()=>void}){const choices=useQuery({queryKey:['support-assignees'],gcTime:0,queryFn:()=>sdk.AdministrationController_supportAssignees({})}),[assignee,setAssignee]=useState(''),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),keys=useRef(new Map<string,string>());return <form className="field-form" noValidate onSubmit={async e=>{e.preventDefault();setError('');const x=supportTriage.safeParse({version:record.version,assigneeId:assignee,publicReply:reply});if(!x.success){setError('Choose a current support assignee and enter a public reply of at least five characters.');return;}const fingerprint=JSON.stringify(x.data);if(!keys.current.has(fingerprint))keys.current.set(fingerprint,crypto.randomUUID());setBusy(true);try{await sdk.AdministrationController_updateSupport({params:{id:record.id},body:x.data,headers:{'Idempotency-Key':keys.current.get(fingerprint)!}});onSaved();}catch(e){setError(e instanceof Error?e.message:'Unable to triage this case');}finally{setBusy(false);}}}><h3>Triage and assign</h3><label className="field">Support assignee<select aria-label="Support assignee" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Choose current support staff</option>{choices.data?.data.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{choices.isError&&<ErrorBox message={choices.error.message}/>}<label className="field">Reply visible to the reporter<textarea aria-label="Public support reply" maxLength={2000} value={reply} onChange={e=>setReply(e.target.value)}/></label>{error&&<ErrorBox message={error}/>}<button className="button" disabled={busy}>Triage case</button></form>;}
