import type pg from 'pg';
import {analyticsKind,analyticsFilters,auditFilters} from '@haven/contracts';
import type {z} from 'zod';
import {fail} from '../platform/core.js';
export const funnelDefinitions={listing_impression:'Opted-in signed-in account sees at least half a current property card; one account/property/UTC day.',listing_view:'Explicitly consented signed-in current property view; one account/property/UTC day.',favorite_added:'Opted-in account saves a current property; one account/property/UTC day, excluding removals.',inquiry_submitted:'One committed opted-in account inquiry request; same-receipt retry counts once.',viewing_requested:'One committed opted-in account viewing booking; confirmation/rescheduling adds no request.',quote_requested:'One committed opted-in account quote request; private project/contact text excluded.'};
const definition='Optional consented events only, not all visitors or a cohort conversion rate. Source outbox IDs and deduplication keys retain traceability. UTC date filters are inclusive. Async worker projections may lag; pending matched source count is reported. Event metadata has no private text, contact details, identity documents, or addresses.';
export async function analyticsRead(c:pg.PoolClient,x:z.output<typeof analyticsFilters>){if(x.city&&!(await c.query('SELECT 1 FROM cities WHERE slug=$1',[x.city])).rowCount)fail(404,'Analytics city not found');const params=[x.city||null,x.category||null,x.from,x.to],where="($1::text IS NULL OR city=$1) AND ($2::text IS NULL OR category=$2) AND day BETWEEN $3::date AND $4::date";const counts=(await c.query(`SELECT kind,sum(count)::text count FROM analytics_daily WHERE ${where} GROUP BY kind`,params)).rows;const lag=(await c.query("SELECT count(*)::int count FROM analytics_events WHERE projected_at IS NULL AND ($1::text IS NULL OR city=$1) AND ($2::text IS NULL OR category=$2) AND at>=$3::date AT TIME ZONE 'UTC' AND at<($4::date+1) AT TIME ZONE 'UTC'",params)).rows[0].count;return {asOf:new Date().toISOString(),projectionLag:lag,scope:{city:x.city||null,category:x.category||null,from:x.from,to:x.to},rows:analyticsKind.options.map(kind=>({kind,count:Number(counts.find(r=>r.kind===kind)?.count||0),definition:funnelDefinitions[kind]})),definition};}
export async function auditRead(c:pg.PoolClient,x:z.output<typeof auditFilters>){const params=[x.action||null,x.actorId||null,x.resourceId||null,x.from||null,x.to||null],where="action ~ '^[a-z][a-z0-9_.]{0,79}$' AND ($1::text IS NULL OR action=$1) AND ($2::uuid IS NULL OR actor_id=$2) AND ($3::uuid IS NULL OR resource_id=$3) AND ($4::date IS NULL OR created_at >= $4::date AT TIME ZONE 'UTC') AND ($5::date IS NULL OR created_at < ($5::date+1) AT TIME ZONE 'UTC')";const total=(await c.query('SELECT count(*)::int total FROM audit_events WHERE '+where,params)).rows[0].total;const rows=(await c.query('SELECT id,actor_id AS "actorId",resource_id AS "resourceId",action,created_at AS at FROM audit_events WHERE '+where+' ORDER BY created_at DESC,id LIMIT 20 OFFSET $6',[...params,(x.page-1)*20])).rows.map(r=>({...r,at:new Date(r.at).toISOString()}));return {page:x.page,total,rows};}
const csvCell=(v:unknown)=>'"'+String(v??'').replaceAll('"','""')+'"';
export function analyticsCSV(r:Awaited<ReturnType<typeof analyticsRead>>){return ['kind,count,city,category,from,to,definition',...r.rows.map(row=>[row.kind,row.count,r.scope.city,r.scope.category,r.scope.from,r.scope.to,row.definition].map(csvCell).join(','))].join('\r\n')+'\r\n';}
