import {managementDashboard} from '../management/dashboard.js';
import {AgentDashboardController} from './agent-dashboard.js';
import {agencyMembers} from '../identity/agency-memberships.js';
import {Controller,Get,Post,Patch,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import {z} from 'zod';
import {event} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
@Controller('api/v1')
export class AdministrationController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('support-cases') async cases(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT id,subject,description,category,status,public_reply,version,created_at FROM support_cases WHERE user_id=$1 ORDER BY created_at DESC',[a.id])).rows));}
 @Post('support-cases') async support(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req);const x=z.object({subject:z.string().min(5).max(120),description:z.string().min(10).max(3000),category:z.enum(['General','Listing complaint','Account','Viewing','Other'])}).parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const r=await c.query('INSERT INTO support_cases(user_id,subject,description,category) VALUES($1,$2,$3,$4) RETURNING id,status',[a.id,x.subject,x.description,x.category]);await event(c,a,r.rows[0].id,'support.opened');return data(r.rows[0]);}));}
 @Get('ops/support-cases') async supportQueue(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['support','admin']);return transaction(a,async c=>data((await c.query('SELECT * FROM support_cases ORDER BY created_at DESC')).rows));}
 @Patch('ops/support-cases/:id') async updateSupport(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['support','admin']);const x=z.object({status:z.enum(['triaged','escalated','resolved']),publicReply:z.string().min(5).max(2000),internalNote:z.string().max(2000).optional(),version:z.number().int()}).parse(body);return transaction(a,async c=>{const r=await c.query('UPDATE support_cases SET status=$2,public_reply=$3,internal_note=$4,version=version+1 WHERE id=$1 AND version=$5 RETURNING id,status,version',[id,x.status,x.publicReply,x.internalNote,x.version]);if(!r.rowCount)fail(409,'Case unavailable or changed');await event(c,a,id,'support.'+x.status);return data(r.rows[0]);});}
 @Get('ops/audit') async audit(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['admin']);return transaction(a,async c=>data((await c.query('SELECT id,actor_id,resource_id,action,created_at FROM audit_events ORDER BY created_at DESC LIMIT 200')).rows));}
 @Get('ops/users') async users(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['admin']);return transaction(a,async c=>data((await c.query('SELECT id,display_name,email,state FROM profiles ORDER BY display_name')).rows));}
 @Post('ops/users/:id/suspend') async suspend(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['admin']);if(a.id===id)fail(400,'You cannot suspend your own account');return transaction(a,async c=>{const r=await c.query("UPDATE profiles SET state='suspended' WHERE id=$1 RETURNING id,state",[id]);if(!r.rowCount)fail(404,'User not found');await c.query('DELETE FROM sessions WHERE user_id=$1',[id]);await event(c,a,id,'account.suspended');return data(r.rows[0]);});}
 @Get('ops/memberships') async memberships(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agency_manager','admin']);return transaction(a,async c=>data(await agencyMembers(c,a)));}
 @Get('ops/dashboard') async dashboard(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agent','agency_manager','developer','property_manager','finance','vendor','moderator','support','admin']);if(a.roles.some(r=>['property_manager','finance'].includes(r)))return transaction(a,async c=>data(await managementDashboard(c)));if(a.roles.some(r=>['agent','agency_manager'].includes(r)))return new AgentDashboardController(this.identity).overview(req);return transaction(a,async c=>{const count=async(table:string,where='true',params:unknown[]=[])=>Number((await c.query(`SELECT count(*) FROM ${table} WHERE ${where}`,params)).rows[0].count);return data({listings:await count('listings',"organization_id=$1 AND status='published'",[a.orgId]),leads:await count('leads'),leases:await count('leases',"status='active'"),maintenance:await count('maintenance',"status<>'closed'"),asOf:new Date().toISOString(),definition:'Current authorized records; published listings, all leads, active leases, open maintenance.'});});}
}
