import {platformUserQuery,platformAccountAction,platformStaffSave} from '@haven/contracts';
import {platformUsers,platformUserRecord,platformAccount,platformStaff,platformAdmin} from './platform-users.js';
import {homeContentQuery,homeSectionCreate,homeSectionEdit,homeSectionAction,homeTaxonomySave} from '@haven/contracts';
import {contentWorkspace,contentCreate,contentEdit,contentAction,contentTaxonomy,contentEditor,contentRecord} from './home-content.js';
import {supportCreate,supportTriage,supportWorkflow,supportPublicAction,supportPageQuery} from '@haven/contracts';
import {createSupport,triageSupport,changeSupport,supportCSV,supportList,supportDetail,supportStaff} from './support-cases.js';
import {readPrivateObject} from '../inventory/media.js';
import {managementDashboard} from '../management/dashboard.js';
import {AgentDashboardController} from './agent-dashboard.js';
import {agencyMembers} from '../identity/agency-memberships.js';
import {Controller,Get,Post,Patch,Param,Req,Body,Query,Res,Inject} from '@nestjs/common';
import type {FastifyRequest,FastifyReply} from 'fastify';
import {z} from 'zod';
import {Identity,data,fail,transaction} from '../platform/core.js';
@Controller('api/v1')
export class AdministrationController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('support-cases') async cases(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req),x=supportPageQuery.parse(input);return transaction(a,async c=>data(await supportList(c,x)));}
 @Get('support-cases/:id') async supportDetail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>data(await supportDetail(c,z.uuid().parse(id))));}
 @Post('support-cases') async support(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req),x=supportCreate.parse(body);return transaction(a,c=>createSupport(c,a,req,x));}
 @Get('ops/support-cases') async supportQueue(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,['support','admin']),x=supportPageQuery.parse(input);return transaction(a,async c=>data(await supportList(c,x,true)));}
 @Get('ops/support-cases/:id') async supportProfessionalDetail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['support','admin']);return transaction(a,async c=>data(await supportDetail(c,z.uuid().parse(id),true)));}
 @Patch('support-cases/:id') async supportPublicChange(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),x=supportPublicAction.parse(body);return transaction(a,c=>changeSupport(c,a,req,z.uuid().parse(id),x,false));}
 @Post('ops/support-cases/:id/actions') async supportAction(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['support','admin']),x=supportWorkflow.parse(body);return transaction(a,c=>changeSupport(c,a,req,z.uuid().parse(id),x,true));}
 @Get('ops/support-cases/export') async supportExport(@Req() req:FastifyRequest,@Query() input:unknown={},@Res() reply:FastifyReply){const a=await this.identity.actor(req,['support','admin']),x=supportPageQuery.parse(input);return transaction(a,async c=>reply.header('Content-Type','text/csv; charset=utf-8').header('Cache-Control','no-store').header('Content-Disposition','attachment; filename="support-case-metadata.csv"').send(await supportCSV(c,x)));}
 @Get('ops/support-assignees') async supportAssignees(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['support','admin']);return transaction(a,async c=>{await supportStaff(c);return data((await c.query('SELECT * FROM support_assignee_directory()')).rows);});}
 @Patch('ops/support-cases/:id') async updateSupport(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['support','admin']),x=supportTriage.parse(body);return transaction(a,c=>triageSupport(c,a,req,z.uuid().parse(id),x));}
 @Get('support-cases/:id/attachments/:assetId') async supportAttachment(@Req() req:FastifyRequest,@Param('id') id:string,@Param('assetId') assetId:string,@Res() reply:FastifyReply){const a=await this.identity.actor(req);return transaction(a,async c=>{const source=(await c.query('SELECT support_attachment_file($1,$2) source',[z.uuid().parse(id),z.uuid().parse(assetId)])).rows[0].source;if(!source||!source.key)fail(404,'Currently authorized support attachment not found');const content=await readPrivateObject(source.key);return reply.header('Content-Type',source.mime).header('Cache-Control','no-store').header('X-Content-Type-Options','nosniff').header('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'; base-uri 'none'").send(content);});}
 @Get('ops/home-content') async homeContent(@Req() req:FastifyRequest,@Query() input:unknown){const a=await this.identity.actor(req,['editor','admin']),x=homeContentQuery.parse(input);return transaction(a,async c=>data(await contentWorkspace(c,x.city)));}
 @Post('ops/home-content') async homeCreate(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['editor','admin']),x=homeSectionCreate.parse(body);return transaction(a,c=>contentCreate(c,a,req,x));}
 @Patch('ops/home-content/:id') async homeEdit(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['editor','admin']),x=homeSectionEdit.parse(body);return transaction(a,c=>contentEdit(c,a,req,z.uuid().parse(id),x));}
 @Post('ops/home-content/:id/actions') async homePublish(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['editor','admin']),x=homeSectionAction.parse(body);return transaction(a,c=>contentAction(c,a,req,z.uuid().parse(id),x));}
 @Get('ops/home-content/:id/preview') async homePreview(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['editor','admin']);return transaction(a,async c=>{await contentEditor(c);return data(await contentRecord(c,z.uuid().parse(id)));});}
 @Post('ops/home-taxonomy') async homeTaxonomy(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['editor','admin']),x=homeTaxonomySave.parse(body);return transaction(a,c=>contentTaxonomy(c,a,req,x));}
 @Get('ops/audit') async audit(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['admin']);return transaction(a,async c=>{await platformAdmin(c);return data((await c.query('SELECT id,actor_id,resource_id,action,created_at FROM audit_events ORDER BY created_at DESC LIMIT 200')).rows);});}
 @Get('ops/users') async users(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,['admin']),x=platformUserQuery.parse(input);return transaction(a,async c=>data(await platformUsers(c,x)));}
 @Get('ops/users/:id') async user(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['admin']);return transaction(a,async c=>data(await platformUserRecord(c,z.uuid().parse(id))));}
 @Post('ops/users/:id/suspend') async suspend(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['admin']),x=platformAccountAction.parse(body);return transaction(a,c=>platformAccount(c,a,req,z.uuid().parse(id),x));}
 @Post('ops/users/:id/staff') async staff(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['admin']),x=platformStaffSave.parse(body);return transaction(a,c=>platformStaff(c,a,req,z.uuid().parse(id),x));}
 @Get('ops/memberships') async memberships(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agency_manager','admin']);return transaction(a,async c=>data(await agencyMembers(c,a)));}
 @Get('ops/dashboard') async dashboard(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agent','agency_manager','developer','property_manager','finance','vendor','moderator','support','admin']);if(a.roles.some(r=>['property_manager','finance'].includes(r)))return transaction(a,async c=>data(await managementDashboard(c)));if(a.roles.some(r=>['agent','agency_manager'].includes(r)))return new AgentDashboardController(this.identity).overview(req);return transaction(a,async c=>{const count=async(table:string,where='true',params:unknown[]=[])=>Number((await c.query(`SELECT count(*) FROM ${table} WHERE ${where}`,params)).rows[0].count);return data({listings:await count('listings',"organization_id=$1 AND status='published'",[a.orgId]),leads:await count('leads'),leases:await count('leases',"status='active'"),maintenance:await count('maintenance',"status<>'closed'"),asOf:new Date().toISOString(),definition:'Current authorized records; published listings, all leads, active leases, open maintenance.'});});}
}
