import type pg from 'pg';
import type {Actor} from '@haven/database';
import {event} from '@haven/database';
import type {FastifyRequest} from 'fastify';
import {homeSectionCreate,homeSectionEdit,homeSectionAction,homeTaxonomySave,homeContentWorkspace,homeSectionRecord,homeTaxonomyRecord} from '@haven/contracts';
import {data,fail,idempotent} from '../platform/core.js';
export async function contentEditor(c:pg.PoolClient){if(!(await c.query('SELECT content_editor_lock() admitted')).rows[0].admitted)fail(403,'Current platform editor membership required');}
const dateSQL=(column:string)=>`to_char(${column} AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;
const projection=`SELECT s.id,s.version,s.city,s.category,s.title,s.copy,s.position,${dateSQL('s.starts_at')} AS "startsAt",${dateSQL('s.ends_at')} AS "endsAt",s.items,s.state,(s.published->>'version')::int AS "publishedVersion",s.published,${dateSQL('s.updated_at')} AS "updatedAt",coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'action',h.action,'at',h.at) ORDER BY h.version) FROM home_content_history h WHERE h.section_id=s.id),'[]') AS activity FROM home_sections s`;
export async function contentRecord(c:pg.PoolClient,id:string){const row=(await c.query(projection+' WHERE s.id=$1',[id])).rows[0];if(!row)fail(404,'Authorized home section not found');return homeSectionRecord.parse(row);}
export async function contentWorkspace(c:pg.PoolClient,city:string){await contentEditor(c);if(!(await c.query("SELECT 1 FROM cities WHERE slug=$1 AND status='active'",[city])).rowCount)fail(404,'Active city not found');return homeContentWorkspace.parse({sections:(await c.query(projection+' WHERE s.city=$1 ORDER BY s.position,s.id LIMIT 100',[city])).rows,taxonomy:(await c.query(`SELECT city,category,label,active,version,${dateSQL('updated_at')} AS "updatedAt",updated_by IS NULL AS historical FROM home_taxonomy WHERE city=$1 ORDER BY category`,[city])).rows});}
async function eligible(c:pg.PoolClient,x:{city:string;category:string;items:{id:string;version:number}[]}){if(!(await c.query("SELECT 1 FROM cities WHERE slug=$1 AND status='active' FOR SHARE",[x.city])).rowCount)fail(404,'Active city not found');if(!(await c.query('SELECT 1 FROM home_taxonomy WHERE city=$1 AND category=$2 AND active FOR SHARE',[x.city,x.category])).rowCount)fail(400,'Choose an active category for this city');for(const p of x.items)if(!(await c.query('SELECT content_source($1,$2,$3,$4,true) admitted',[p.id,p.version,x.city,x.category])).rows[0].admitted)fail(400,'Each selection must be current, published and eligible in the same city/category');}
export async function contentCreate(c:pg.PoolClient,a:Actor,req:FastifyRequest,input:unknown){await contentEditor(c);const x=homeSectionCreate.parse(input);return idempotent(c,a,req,x,async()=>{await eligible(c,x);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['home-sections:'+x.city]);if((await c.query('SELECT count(*)::int total FROM home_sections WHERE city=$1',[x.city])).rows[0].total>=100)fail(409,'This city has 100 retained sections; edit an existing section');const row=(await c.query("INSERT INTO home_sections(city,category,title,copy,position,starts_at,ends_at,items,last_action,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'created',$9,$9) RETURNING id",[x.city,x.category,x.title,x.copy,x.position,x.startsAt,x.endsAt,JSON.stringify(x.items),a.id])).rows[0];await event(c,a,row.id,'content.section_created',{version:1,city:x.city,category:x.category});return data(await contentRecord(c,row.id));});}
export async function contentEdit(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown){await contentEditor(c);const x=homeSectionEdit.parse(input);return idempotent(c,a,req,x,async()=>{const old=(await c.query('SELECT * FROM home_sections WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!old)fail(404,'Home section not found');if(old.version!==x.version||old.state==='archived')fail(409,'Refresh the current editable section');if(old.city!==x.city)fail(400,'A section cannot move between cities');await eligible(c,x);await c.query("UPDATE home_sections SET category=$2,title=$3,copy=$4,position=$5,starts_at=$6,ends_at=$7,items=$8,version=version+1,last_action='edited',updated_by=$9,updated_at=statement_timestamp() WHERE id=$1",[id,x.category,x.title,x.copy,x.position,x.startsAt,x.endsAt,JSON.stringify(x.items),a.id]);await event(c,a,id,'content.section_edited',{version:old.version+1,city:old.city});return data(await contentRecord(c,id));});}
export async function contentAction(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown){await contentEditor(c);const x=homeSectionAction.parse(input);return idempotent(c,a,req,x,async()=>{const old=await contentRecord(c,id);const locked=(await c.query('SELECT version,state FROM home_sections WHERE id=$1 FOR UPDATE',[id])).rows[0];if(locked.version!==x.version||locked.state==='archived'||old.version!==locked.version)fail(409,'Refresh the current editable section');if(x.action==='publish')await eligible(c,old);const snapshot=x.action==='publish'?{city:old.city,category:old.category,title:old.title,copy:old.copy,position:old.position,startsAt:old.startsAt,endsAt:old.endsAt,items:old.items,version:old.version+1}:old.published;await c.query('UPDATE home_sections SET state=$2,published=$3,version=version+1,last_action=$4,updated_by=$5,updated_at=statement_timestamp() WHERE id=$1',[id,x.action==='publish'?'published':'archived',snapshot?JSON.stringify(snapshot):null,x.action==='publish'?'published':'archived',a.id]);await event(c,a,id,'content.section_'+x.action,{version:old.version+1,city:old.city});return data(await contentRecord(c,id));});}
export async function contentTaxonomy(c:pg.PoolClient,a:Actor,req:FastifyRequest,input:unknown){await contentEditor(c);const x=homeTaxonomySave.parse(input);return idempotent(c,a,req,x,async()=>{if(!(await c.query("SELECT 1 FROM cities WHERE slug=$1 AND status='active' FOR SHARE",[x.city])).rowCount)fail(404,'Active city not found');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['home-taxonomy:'+x.city+':'+x.category]);const old=(await c.query('SELECT version FROM home_taxonomy WHERE city=$1 AND category=$2 FOR UPDATE',[x.city,x.category])).rows[0];if((old?.version||0)!==x.version)fail(409,'Refresh the current category version');const r=(await c.query(`INSERT INTO home_taxonomy(city,category,label,active,updated_by,updated_at) VALUES($1,$2,$3,$4,$5,statement_timestamp()) ON CONFLICT(city,category) DO UPDATE SET label=excluded.label,active=excluded.active,version=home_taxonomy.version+1,updated_by=excluded.updated_by,updated_at=excluded.updated_at RETURNING city,category,label,active,version,${dateSQL('updated_at')} AS "updatedAt",false AS historical`,[x.city,x.category,x.label,x.active,a.id])).rows[0];await event(c,a,a.id,'content.taxonomy_saved',{city:x.city,category:x.category,version:r.version,active:r.active});return data(homeTaxonomyRecord.parse(r));});}
