import type pg from 'pg';
import type {Actor} from '@haven/database';
import type {FastifyRequest} from 'fastify';
import {platformUserQuery,platformAccountAction,platformStaffSave,platformUser,platformUserPage} from '@haven/contracts';
import {data,fail,idempotent} from '../platform/core.js';
export async function platformAdmin(c:pg.PoolClient){if(!(await c.query('SELECT platform_admin_lock() admitted')).rows[0].admitted)fail(403,'Current platform administrator membership required');}
const projection=`SELECT p.id,p.display_name AS "displayName",p.email,p.state,p.version,coalesce((SELECT jsonb_agg(jsonb_build_object('id',m.id,'role',m.role,'status',m.status,'version',m.version) ORDER BY m.role) FROM memberships m WHERE m.user_id=p.id AND m.organization_id IS NULL AND m.role IN('moderator','support','editor','admin')),'[]') staff,coalesce((SELECT jsonb_agg(jsonb_build_object('id',h.id,'kind',h.kind,'actorId',h.actor_id,'at',h.at,'reason',h.reason,'before',h.before_snapshot,'after',h.after_snapshot) ORDER BY h.at,h.id) FROM platform_administration_history h WHERE h.target_id=p.id),'[]') activity FROM profiles p`;
export async function platformUserRecord(c:pg.PoolClient,id:string){await platformAdmin(c);const r=(await c.query(projection+' WHERE p.id=$1',[id])).rows[0];if(!r)fail(404,'Platform account not found');return platformUser.parse(r);}
export async function platformUsers(c:pg.PoolClient,input:unknown={}){await platformAdmin(c);const x=platformUserQuery.parse(input),params:unknown[]=['%'+x.text.replace(/[\\%_]/g,'\\$&')+'%'],where=['(p.display_name ILIKE $1 OR p.email ILIKE $1 OR p.id::text ILIKE $1)'];if(x.state){params.push(x.state);where.push('p.state=$'+params.length);}const total=(await c.query('SELECT count(*)::int total FROM profiles p WHERE '+where.join(' AND '),params)).rows[0].total,items=(await c.query(projection+' WHERE '+where.join(' AND ')+' ORDER BY p.display_name,p.id LIMIT 20 OFFSET $'+(params.length+1),[...params,(x.page-1)*20])).rows;return platformUserPage.parse({page:x.page,limit:20,total,items});}
export async function platformAccount(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown){await platformAdmin(c);const x=platformAccountAction.parse(input);if(a.id===id)fail(403,'You cannot change your own account state');return idempotent(c,a,req,x,async()=>{const r=(await c.query('SELECT version,state FROM profiles WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)fail(404,'Platform account not found');const next=x.action==='suspend'?'suspended':'active';if(r.version!==x.version||r.state===next||!['active','suspended'].includes(r.state))fail(409,'Refresh the current account version/state');await c.query("SELECT set_config('app.administration_reason',$1,true)",[x.reason]);await c.query('UPDATE profiles SET state=$2,version=version+1 WHERE id=$1',[id,next]);return data(await platformUserRecord(c,id));});}
export async function platformStaff(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown){await platformAdmin(c);const x=platformStaffSave.parse(input);if(a.id===id)fail(403,'You cannot grant or revoke your own staff authority');return idempotent(c,a,req,x,async()=>{const person=(await c.query('SELECT state,version FROM profiles WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!person)fail(404,'Platform account not found');if(person.state!=='active'||person.version!==x.profileVersion)fail(409,'Refresh the current active target account');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['platform-staff:'+id+':'+x.role]);const old=(await c.query('SELECT id,status,version FROM memberships WHERE user_id=$1 AND organization_id IS NULL AND role=$2 FOR UPDATE',[id,x.role])).rows[0];if((old?.version||0)!==x.version||old?.status===x.status||!old&&x.status!=='active')fail(409,'Refresh the current staff permission version/state');if(old)await c.query('UPDATE memberships SET status=$2,version=version+1,change_reason=$3 WHERE id=$1',[old.id,x.status,x.reason]);else await c.query("INSERT INTO memberships(user_id,organization_id,role,status,change_reason) VALUES($1,NULL,$2,'active',$3)",[id,x.role,x.reason]);return data(await platformUserRecord(c,id));});}
