import type pg from 'pg';
import type {Actor} from '@haven/database';
import type {FastifyRequest} from 'fastify';
import {supportCreate,supportTriage,supportPageQuery,supportRecord,supportPage} from '@haven/contracts';
import {supportListingSource} from '../inventory/support-source.js';
import {data,fail,idempotent} from '../platform/core.js';
import {event} from '@haven/database';
const projection=`SELECT s.id,s.version,s.subject,s.description,s.category,s.status,s.public_reply AS "publicReply",s.created_at::text AS "createdAt",s.updated_at::text AS "updatedAt",s.created_by IS NULL AS historical,s.listing_snapshot AS listing,s.assignee_id IS NOT NULL AS assigned,CASE WHEN support_staff_actor(actor_id()) THEN s.assignee_id ELSE NULL END AS "assigneeId",coalesce((SELECT jsonb_agg(jsonb_build_object('id',a.asset_id,'version',a.asset_version,'label',a.label,'mime',a.mime,'url','/api/v1/support-cases/'||s.id||'/attachments/'||a.asset_id) ORDER BY a.asset_id) FROM support_case_attachments a WHERE a.case_id=s.id),'[]') AS attachments,coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'status',h.status,'message',h.public_message,'at',h.at) ORDER BY h.version) FROM support_case_history h WHERE h.case_id=s.id),'[]') AS activity FROM support_cases s`;
export async function supportStaff(c:pg.PoolClient){if(!(await c.query('SELECT support_staff_lock(actor_id()) admitted')).rows[0].admitted)fail(403,'Current platform support membership required');}
export async function supportDetail(c:pg.PoolClient,id:string,professional=false){if(professional)await supportStaff(c);const r=(await c.query(projection+' WHERE s.id=$1 AND support_case_access(s.id)'+(professional?'':' AND s.user_id=actor_id()'),[id])).rows[0];if(!r)fail(404,'Authorized support case not found');return supportRecord.parse(r);}
export async function supportList(c:pg.PoolClient,input:unknown={},professional=false){const x=supportPageQuery.parse(input);if(professional)await supportStaff(c);const where=professional?'support_case_access(s.id)':'s.user_id=actor_id()',total=(await c.query('SELECT count(*)::int total FROM support_cases s WHERE '+where)).rows[0].total,items=(await c.query(projection+' WHERE '+where+' ORDER BY s.created_at DESC,s.id DESC LIMIT 20 OFFSET $1',[(x.page-1)*20])).rows;return supportPage.parse({page:x.page,limit:20,total,items});}
async function activity(c:pg.PoolClient,a:Actor,id:string){await c.query('INSERT INTO support_case_history(case_id,version,status,public_message,assignee_id,actor_id,at) SELECT id,version,status,public_reply,assignee_id,$2,updated_at FROM support_cases WHERE id=$1',[id,a.id]);}
export async function createSupport(c:pg.PoolClient,a:Actor,req:FastifyRequest,input:unknown){const x=supportCreate.parse(input);return idempotent(c,a,req,x,async()=>{const listing=x.listing?await supportListingSource(c,x.listing.id,x.listing.version):null;const r=(await c.query("INSERT INTO support_cases(user_id,subject,description,category,created_by,updated_by,updated_at,created_at,listing_id,listing_version,listing_snapshot) VALUES($1,$2,$3,$4,$1,$1,statement_timestamp(),statement_timestamp(),$5,$6,$7) RETURNING id",[a.id,x.subject,x.description,x.category,listing?.id||null,listing?.version||null,listing])).rows[0];for(const attachment of x.attachments){const source=(await c.query('SELECT support_owned_attachment($1,$2) source',[attachment.assetId,attachment.version])).rows[0].source;if(!source)fail(404,'Current owned approved scanned private attachment required');await c.query('INSERT INTO support_case_attachments(case_id,asset_id,asset_version,label,mime,actor_id) VALUES($1,$2,$3,$4,$5,$6)',[r.id,attachment.assetId,attachment.version,attachment.label,source.mime,a.id]);}await activity(c,a,r.id);await event(c,a,r.id,'support.opened',{version:1,category:x.category,hasListing:!!listing});return data(await supportDetail(c,r.id));});}
export async function triageSupport(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown){await supportStaff(c);const x=supportTriage.parse(input);await supportDetail(c,id,true);return idempotent(c,a,req,x,async()=>{const r=(await c.query('SELECT id,version,status FROM support_cases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)fail(404,'Authorized support case not found');if(r.version!==x.version||r.status!=='open')fail(409,'Refresh the current open case before triage');if(!(await c.query('SELECT support_staff_lock($1) admitted',[x.assigneeId])).rows[0].admitted)fail(404,'Current support assignee required');await c.query("UPDATE support_cases SET status='triaged',assignee_id=$2,public_reply=$3,version=version+1,updated_by=$4,updated_at=statement_timestamp() WHERE id=$1",[id,x.assigneeId,x.publicReply,a.id]);await activity(c,a,id);await event(c,a,id,'support.triaged',{version:r.version+1});return data(await supportDetail(c,id,true));});}
