import type pg from 'pg';
import type {Actor} from '@haven/database';
import type {FastifyRequest} from 'fastify';
import {supportCreate,supportTriage,supportWorkflow,supportPageQuery,supportRecord,supportPage} from '@haven/contracts';
import {supportListingSource} from '../inventory/support-source.js';
import {data,fail,idempotent} from '../platform/core.js';
import {event} from '@haven/database';
const projection=`SELECT s.id,s.version,s.subject,s.description,s.category,s.status,s.public_reply AS "publicReply",s.created_at::text AS "createdAt",s.updated_at::text AS "updatedAt",s.created_by IS NULL AS historical,s.listing_snapshot AS listing,s.assignee_id IS NOT NULL AS assigned,(support_staff_actor(actor_id()) AND (s.status='open' OR support_case_private_access(s.id))) AS "canAct",(s.status IN('open','triaged','escalated') AND (s.user_id=actor_id() OR support_case_private_access(s.id))) AS "canComment",(s.status='resolved' AND s.user_id=actor_id()) AS "canReopen",CASE WHEN support_staff_actor(actor_id()) THEN s.assignee_id ELSE NULL END AS "assigneeId",coalesce((SELECT jsonb_agg(jsonb_build_object('id',a.asset_id,'version',a.asset_version,'label',a.label,'mime',a.mime,'url','/api/v1/support-cases/'||s.id||'/attachments/'||a.asset_id) ORDER BY a.asset_id) FROM support_case_attachments a WHERE a.case_id=s.id),'[]') AS attachments,coalesce((SELECT jsonb_agg(jsonb_build_object('version',h.version,'status',h.status,'message',h.public_message,'at',h.at,'action',CASE WHEN h.action='note' THEN 'status_updated' ELSE h.action END) ORDER BY h.version) FROM support_case_history h WHERE h.case_id=s.id),'[]') AS activity FROM support_cases s`;
export async function supportStaff(c:pg.PoolClient){if(!(await c.query('SELECT support_staff_lock(actor_id()) admitted')).rows[0].admitted)fail(403,'Current platform support membership required');}
export async function supportDetail(c:pg.PoolClient,id:string,professional=false){if(professional)await supportStaff(c);const r=(await c.query(projection+' WHERE s.id=$1 AND support_case_access(s.id)'+(professional?'':' AND s.user_id=actor_id()'),[id])).rows[0];if(!r)fail(404,'Authorized support case not found');if(professional&&(await c.query('SELECT support_case_private_access($1) admitted',[id])).rows[0].admitted){r.internalNotes=(await c.query('SELECT id::text,case_version AS version,body,at::text,false AS historical FROM support_case_internal_notes WHERE case_id=$1 ORDER BY at,id',[id])).rows;const legacy=(await c.query('SELECT internal_note FROM support_cases WHERE id=$1',[id])).rows[0]?.internal_note;if(legacy)r.internalNotes.unshift({id:'historical',version:null,body:legacy,at:null,historical:true});}return supportRecord.parse(r);}
function filter(x:ReturnType<typeof supportPageQuery.parse>,professional:boolean){const conditions=[professional?'support_case_access(s.id)':'s.user_id=actor_id()'],params:unknown[]=[];for(const [column,value] of [['status',x.status],['category',x.category],['assignee_id',x.assigneeId]] as const){if(value!==undefined){params.push(value);conditions.push('s.'+column+'=$'+params.length);}}return {where:conditions.join(' AND '),params};}
export async function supportList(c:pg.PoolClient,input:unknown={},professional=false){const x=supportPageQuery.parse(input);if(professional)await supportStaff(c);if(!professional&&x.assigneeId)fail(400,'Assignee filters are limited to the support workbench');const {where,params}=filter(x,professional),total=(await c.query('SELECT count(*)::int total FROM support_cases s WHERE '+where,params)).rows[0].total,items=(await c.query(projection+' WHERE '+where+' ORDER BY s.created_at DESC,s.id DESC LIMIT 20 OFFSET $'+(params.length+1),[...params,(x.page-1)*20])).rows;return supportPage.parse({page:x.page,limit:20,total,items});}

async function activity(c:pg.PoolClient,a:Actor,id:string){await c.query(`INSERT INTO support_case_history(case_id,version,status,public_message,assignee_id,actor_id,at,action) SELECT id,version,status,CASE WHEN last_action='note' THEN NULL ELSE public_reply END,assignee_id,$2,updated_at,coalesce(last_action,'opened') FROM support_cases WHERE id=$1`,[id,a.id]);}
export async function createSupport(c:pg.PoolClient,a:Actor,req:FastifyRequest,input:unknown){const x=supportCreate.parse(input);return idempotent(c,a,req,x,async()=>{const listing=x.listing?await supportListingSource(c,x.listing.id,x.listing.version):null;const r=(await c.query("INSERT INTO support_cases(user_id,subject,description,category,created_by,updated_by,updated_at,created_at,listing_id,listing_version,listing_snapshot) VALUES($1,$2,$3,$4,$1,$1,statement_timestamp(),statement_timestamp(),$5,$6,$7) RETURNING id",[a.id,x.subject,x.description,x.category,listing?.id||null,listing?.version||null,listing])).rows[0];for(const attachment of x.attachments){const source=(await c.query('SELECT support_owned_attachment($1,$2) source',[attachment.assetId,attachment.version])).rows[0].source;if(!source)fail(404,'Current owned approved scanned private attachment required');await c.query('INSERT INTO support_case_attachments(case_id,asset_id,asset_version,label,mime,actor_id) VALUES($1,$2,$3,$4,$5,$6)',[r.id,attachment.assetId,attachment.version,attachment.label,source.mime,a.id]);}await activity(c,a,r.id);await event(c,a,r.id,'support.opened',{version:1,category:x.category,hasListing:!!listing});return data(await supportDetail(c,r.id));});}
export async function triageSupport(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown){await supportStaff(c);const x=supportTriage.parse(input);await supportDetail(c,id,true);return idempotent(c,a,req,x,async()=>{const r=(await c.query('SELECT id,version,status FROM support_cases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)fail(404,'Authorized support case not found');if(r.version!==x.version||r.status!=='open')fail(409,'Refresh the current open case before triage');if(!(await c.query('SELECT support_staff_lock($1) admitted',[x.assigneeId])).rows[0].admitted)fail(404,'Current support assignee required');await c.query("UPDATE support_cases SET status='triaged',last_action='triage',assignee_id=$2,public_reply=$3,version=version+1,updated_by=$4,updated_at=statement_timestamp() WHERE id=$1",[id,x.assigneeId,x.publicReply,a.id]);await activity(c,a,id);await event(c,a,id,'support.triaged',{version:r.version+1});return data(await supportDetail(c,id,true));});}

export async function changeSupport(c:pg.PoolClient,a:Actor,req:FastifyRequest,id:string,input:unknown,professional:boolean){const x=supportWorkflow.parse(input);if(!professional&&!['comment','reopen'].includes(x.action))fail(400,'Use an own public comment or reopening action');if(professional)await supportStaff(c);await supportDetail(c,id,professional);return idempotent(c,a,req,x,async()=>{const root=(await c.query('SELECT id,version,status,user_id,assignee_id,public_reply FROM support_cases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!root)fail(404,'Authorized support case not found');if(root.version!==x.version)fail(409,'Case changed. Refresh the current version');const assigned=(await c.query('SELECT support_case_private_access($1) admitted',[id])).rows[0].admitted;
 if(x.action==='reopen'){if(root.user_id!==a.id||root.status!=='resolved')fail(409,'Only the original reporter can reopen a resolved case');}
 else if(x.action==='comment'){if(root.user_id!==a.id&&!assigned)fail(403,'Assigned support staff or original reporter required');if(!['open','triaged','escalated'].includes(root.status))fail(409,'Reopen a resolved case before commenting');}
 else{if(!professional||!assigned)fail(403,'Current assigned support staff or administrator required');if(!['triaged','escalated'].includes(root.status))fail(409,'Triage the case before this support action');}
 if(x.action==='escalate'&&root.status!=='triaged'||x.action==='deescalate'&&root.status!=='escalated')fail(409,'Case is not in the required escalation state');if(x.action==='assign'&&!(await c.query('SELECT support_staff_lock($1) admitted',[x.assigneeId])).rows[0].admitted)fail(404,'Current support handoff target required');
 const status=x.action==='reopen'?'open':x.action==='resolve'?'resolved':x.action==='escalate'?'escalated':x.action==='deescalate'?'triaged':root.status,assignee=x.action==='reopen'?null:x.action==='assign'?x.assigneeId:root.assignee_id;
 await c.query('UPDATE support_cases SET version=version+1,status=$2,assignee_id=$3,public_reply=$4,last_action=$5,updated_by=$6,updated_at=statement_timestamp() WHERE id=$1',[id,status,assignee,x.action==='note'?root.public_reply:x.publicReply,x.action,a.id]);
 if(x.action==='note')await c.query('INSERT INTO support_case_internal_notes(case_id,case_version,body,actor_id,at) SELECT id,version,$2,$3,updated_at FROM support_cases WHERE id=$1',[id,x.internalNote,a.id]);await activity(c,a,id);await event(c,a,id,'support.'+x.action,{version:root.version+1,status});return data(await supportDetail(c,id,professional));});}
const csvCell=(v:string)=>'"'+(/^[\s]*[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';
export async function supportCSV(c:pg.PoolClient,input:unknown={}){await supportStaff(c);const x=supportPageQuery.parse(input),{where,params}=filter(x,true),rows=(await c.query('SELECT s.id::text,s.version::text,s.category,s.status,s.created_at::text,s.updated_at::text,s.assignee_id IS NOT NULL AS assigned FROM support_cases s WHERE '+where+' ORDER BY s.created_at DESC,s.id DESC LIMIT 10001',params)).rows;if(rows.length>10000)fail(409,'Export exceeds 10,000 cases. Select a narrower filter; no partial export was produced');return '\ufeff'+[['Case ID','Current version','Category','Status','Created at','Updated at','Assigned'],...rows.map(r=>[r.id,r.version,r.category,r.status,r.created_at,r.updated_at||'',r.assigned?'yes':'no'])].map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n';}
