import {Controller,Get,Post,Put,Delete,Patch,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import {z} from 'zod';
import {favoriteMutation,inquirySchema,leadTransitions,transition} from '@haven/contracts';
import {event} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
@Controller('api/v1')
export class EngagementController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('me/favorites') async favorites(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT CASE WHEN p.id IS NULL THEN jsonb_build_object(\'id\',f.listing_id,\'available\',false,\'title\',\'Saved property is unavailable\') ELSE to_jsonb(p)||jsonb_build_object(\'available\',true) END AS listing FROM favorites f LEFT JOIN public_listings p ON p.id=f.listing_id WHERE f.user_id=$1 AND f.saved ORDER BY f.created_at DESC',[a.id] )).rows.map(row=>row.listing)));}
 @Get('me/favorites/:id') async favoriteState(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);z.string().uuid().parse(id);return transaction(a,async c=>{const current=(await c.query('SELECT saved,version FROM favorites WHERE user_id=$1 AND listing_id=$2',[a.id,id])).rows[0],listing=(await c.query('SELECT version FROM public_listings WHERE id=$1',[id])).rows[0];return data({saved:current?.saved??false,version:current?.version??0,listingVersion:listing?.version??null});});}
 @Put('me/favorites/:id') async favorite(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req);z.string().uuid().parse(id);const input=favoriteMutation.parse(body);return this.toggleFavorite(a,req,id,input,true);}
 @Delete('me/favorites/:id') async unfavorite(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req);z.string().uuid().parse(id);const input=favoriteMutation.parse(body);return this.toggleFavorite(a,req,id,input,false);}
 private async toggleFavorite(a:import('@haven/database').Actor,req:FastifyRequest,id:string,input:import('zod').infer<typeof favoriteMutation>,saved:boolean){return transaction(a,c=>idempotent(c,a,req,input,async()=>{
  await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['favorite:'+a.id+':'+id]);
  const current=(await c.query('SELECT saved,version FROM favorites WHERE user_id=$1 AND listing_id=$2 FOR UPDATE',[a.id,id])).rows[0],listing=(await c.query('SELECT version FROM public_listings WHERE id=$1',[id])).rows[0];
  if((current?.version??0)!==input.version)fail(409,'Saved homes changed. Refresh and try again.','FAVORITE_CHANGED');
  if(saved&&!listing)fail(404,'Property is unavailable');if(saved&&listing.version!==input.listingVersion)fail(409,'Property changed. Refresh and try again.','LISTING_CHANGED');
  if((current?.saved??false)===saved)return data({saved,version:current?.version??0,listingVersion:listing?.version??null});
  const row=(await c.query('INSERT INTO favorites(user_id,listing_id,saved) VALUES($1,$2,$3) ON CONFLICT(user_id,listing_id) DO UPDATE SET saved=EXCLUDED.saved,version=favorites.version+1,created_at=CASE WHEN EXCLUDED.saved THEN now() ELSE favorites.created_at END RETURNING version',[a.id,id,saved])).rows[0];
  await event(c,a,id,saved?'favorite.saved':'favorite.removed',{userId:a.id,version:row.version});return data({saved,version:row.version,listingVersion:listing?.version??null});
 }));}
 @Post('inquiries') async inquiry(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req),x=inquirySchema.parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{let target;if(x.resourceType==='listing'){target=(await c.query("SELECT * FROM published_listing_destination($1)",[x.resourceId])).rows[0];}else if(x.resourceType==='development'){target=(await c.query('SELECT * FROM published_development_destination($1,$2)',[x.resourceId,x.floorPlanId??null])).rows[0];if(target&&x.resourceVersion!==undefined&&target.version!==x.resourceVersion)fail(409,'Project changed. Refresh and try again.');if(target&&x.floorPlanId){if(target.floor_plan_version===null)fail(404,'Selected unit type is unavailable');if(target.floor_plan_version!==x.floorPlanVersion)fail(409,'Unit type changed. Refresh and try again.');if(x.intent==='available_unit'&&(target.status!=='on_sale'||target.available<=0))fail(409,'No units are currently available for this type');}}else{const tables={agent:'agents',provider:'providers'};target=(await c.query(`SELECT organization_id FROM ${tables[x.resourceType]} WHERE id=$1`,[x.resourceId])).rows[0];}if(!target)fail(404,'This resource is no longer available');const r=await c.query('INSERT INTO leads(user_id,organization_id,agent_id,resource_id,resource_type,name,email,phone,message,floor_plan_id,inquiry_intent,resource_version,floor_plan_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id,status,created_at',[a.id,target.organization_id,target.agent_id,x.resourceId,x.resourceType,x.name,x.email,x.phone,x.message,x.floorPlanId??null,x.intent,x.resourceVersion??null,x.floorPlanVersion??null]);const conversation=await c.query('INSERT INTO conversations(user_id,organization_id,agent_id,resource_id) VALUES($1,$2,$3,$4) RETURNING id',[a.id,target.organization_id,target.agent_id,x.resourceId]);await event(c,a,r.rows[0].id,'inquiry.submitted',{email:x.email,resourceId:x.resourceId});return data({...r.rows[0],conversationId:conversation.rows[0].id});}));}
 @Get('me/inquiries') async inquiries(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT id,resource_id,status,created_at,message FROM leads WHERE user_id=$1 ORDER BY created_at DESC',[a.id])).rows));}
 @Get('ops/leads') async leads(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agent','agency_manager','developer','admin']);return transaction(a,async c=>data((await c.query('SELECT * FROM leads ORDER BY created_at DESC')).rows));}
 @Patch('ops/leads/:id') async lead(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager','developer','admin']);const x=z.object({status:z.string(),version:z.number().int()}).parse(body);return transaction(a,async c=>{const r=await c.query('SELECT * FROM leads WHERE id=$1 FOR UPDATE',[id]);if(!r.rowCount)fail(404,'Lead not found');if(r.rows[0].version!==x.version)fail(409,'This lead has changed; refresh and try again');transition(leadTransitions,r.rows[0].status,x.status);const updated=await c.query('UPDATE leads SET status=$2,version=version+1 WHERE id=$1 RETURNING *',[id,x.status]);await event(c,a,id,'lead.'+x.status);return data(updated.rows[0]);});}
 @Get('me/viewings') async viewings(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT v.*,l.title FROM viewings v JOIN listings l ON l.id=v.listing_id WHERE v.user_id=$1 ORDER BY start_at',[a.id])).rows));}
 @Get('ops/viewings') async opsViewings(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agent','agency_manager','admin']);return transaction(a,async c=>data((await c.query('SELECT v.*,l.title FROM viewings v JOIN listings l ON l.id=v.listing_id ORDER BY start_at')).rows));}
 @Post('viewings') async book(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req);const x=z.object({listingId:z.string().uuid(),startAt:z.string().datetime()}).parse(body);const start=new Date(x.startAt);if(start.getTime()<=Date.now())fail(400,'Choose a future viewing time');const end=new Date(start.getTime()+3600000);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const l=await c.query("SELECT agent_id FROM published_listing_destination($1)",[x.listingId]);if(!l.rowCount)fail(404,'Property is no longer available');if(!(await c.query('SELECT id FROM public_listing_agents($1) WHERE id=$2',[x.listingId,l.rows[0].agent_id])).rowCount)fail(409,'No eligible viewing agent is currently assigned','AGENT_UNAVAILABLE');const r=await c.query('INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at) VALUES($1,$2,$3,$4,$5) RETURNING *',[x.listingId,a.id,l.rows[0].agent_id,start,end]);await event(c,a,r.rows[0].id,'viewing.requested');return data(r.rows[0]);}));}
 @Post('viewings/:id/cancel') async cancel(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>{const r=await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE id=$1 AND user_id=$2 AND status IN ('requested','confirmed') RETURNING *",[id,a.id]);if(!r.rowCount)fail(404,'Active viewing not found');await event(c,a,id,'viewing.cancelled');return data(r.rows[0]);});}
 @Post('ops/viewings/:id/confirm') async confirm(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['agent','agency_manager','admin']);return transaction(a,async c=>{const r=await c.query("UPDATE viewings SET status='confirmed',version=version+1 WHERE id=$1 AND status='requested' RETURNING *",[id]);if(!r.rowCount)fail(404,'Requested viewing not found');await event(c,a,id,'viewing.confirmed');return data(r.rows[0]);});}
 @Get('conversations') async conversations(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT id,resource_id,created_at FROM conversations ORDER BY created_at DESC')).rows));}
 @Get('conversations/:id/messages') async messages(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>{if(!(await c.query('SELECT 1 FROM conversations WHERE id=$1',[id])).rowCount)fail(404,'Conversation not found');return data((await c.query('SELECT id,sender_id,sequence,body,created_at FROM messages WHERE conversation_id=$1 ORDER BY sequence LIMIT 500',[id])).rows);});}
 @Post('conversations/:id/messages') async message(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req);const x=z.object({body:z.string().trim().min(1).max(4000),clientId:z.string().uuid()}).parse(body);return transaction(a,async c=>{if(!(await c.query('SELECT 1 FROM conversations WHERE id=$1 FOR UPDATE',[id])).rowCount)fail(404,'Conversation not found');const r=await c.query('INSERT INTO messages(conversation_id,sender_id,client_id,sequence,body) VALUES($1,$2,$3,(SELECT coalesce(max(sequence),0)+1 FROM messages WHERE conversation_id=$1),$4) ON CONFLICT(sender_id,client_id) DO UPDATE SET client_id=EXCLUDED.client_id RETURNING id,sender_id,sequence,body,created_at',[id,a.id,x.clientId,x.body]);await event(c,a,id,'message.persisted');return data(r.rows[0]);});}
}
