import {Controller,Get,Post,Req,Param,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {leadQueueFilters,leadStageUpdate,leadNoteCreate,leadTransitions,transition} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,transaction,data,fail,idempotent} from '../platform/core.js';
export async function crmAuthority(c:pg.PoolClient,a:Actor){const rows=(await c.query("SELECT m.role FROM memberships m JOIN profiles p ON p.id=m.user_id AND p.state='active' JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 AND m.organization_id=$2 AND m.status='active' AND (m.role='admin' OR o.type='agency' AND m.role IN('agent','agency_manager') OR o.type='developer' AND m.role='developer' OR o.type='vendor' AND m.role='vendor') FOR SHARE OF m,p,o",[a.id,a.orgId])).rows;if(!rows.length)fail(403,'An active professional membership in the selected organization is required');return {team:rows.some(r=>['agency_manager','developer','vendor','admin'].includes(r.role))};}
export async function crmLead(c:pg.PoolClient,a:Actor,id:string,lock=false){z.uuid().parse(id);const authority=await crmAuthority(c,a);const l=(await c.query("SELECT l.* FROM leads l WHERE l.id=$1 AND l.organization_id=$2 AND ($3 OR EXISTS(SELECT 1 FROM agents ag WHERE ag.id=l.agent_id AND ag.user_id=$4 AND ag.organization_id=$2))"+(lock?' FOR UPDATE OF l':''),[id,a.orgId,authority.team,a.id])).rows[0];if(!l)fail(404,'Assigned inquiry not found');return l;}
export async function changeLeadStage(a:Actor,req:FastifyRequest,id:string,x:z.infer<typeof leadStageUpdate>){return transaction(a,c=>idempotent(c,a,req,x,async()=>{const l=await crmLead(c,a,id,true);if(l.version!==x.version)fail(409,'Lead changed; refresh before updating','LEAD_CHANGED');transition(leadTransitions,l.status,x.status);const updated=(await c.query('UPDATE leads SET status=$2,version=version+1 WHERE id=$1 RETURNING *',[id,x.status])).rows[0];await event(c,a,id,'lead.'+x.status,{version:updated.version});return data(updated);}));}
export async function crmQueueRows(c:pg.PoolClient,a:Actor,x:ReturnType<typeof leadQueueFilters.parse>,auth:{team:boolean},limit=51,offset=(x.page-1)*50){return (await c.query("SELECT l.* FROM leads l WHERE l.organization_id=$1 AND ($2 OR EXISTS(SELECT 1 FROM agents ag WHERE ag.id=l.agent_id AND ag.user_id=$3 AND ag.organization_id=$1)) AND ($4::text IS NULL OR l.status=$4) AND ($5::text IS NULL OR l.resource_type=$5) AND ($6::uuid IS NULL OR l.agent_id=$6) AND ($7::text IS NULL OR position(lower($7) in lower(l.name))>0 OR position(lower($7) in lower(l.email))>0 OR position($7 in l.phone)>0) ORDER BY l.created_at DESC,l.id LIMIT $9 OFFSET $8",[a.orgId,auth.team,a.id,x.status??null,x.resourceType??null,x.agentId??null,x.text||null,offset,limit])).rows;}
@Controller('api/v1')
export class CrmController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/lead-queue') async queue(@Req() req:FastifyRequest,@Query() input:unknown){const x=leadQueueFilters.parse(input),a=await this.identity.actor(req,['agent','agency_manager','developer','vendor','admin']);return transaction(a,async c=>{const auth=await crmAuthority(c,a);const rows=await crmQueueRows(c,a,x,auth);return data({organizationId:a.orgId,scope:auth.team?'team':'assigned',page:x.page,hasMore:rows.length>50,records:rows.slice(0,50)});});}
 @Get('ops/leads/:id') async detail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['agent','agency_manager','developer','vendor','admin']);return transaction(a,async c=>{const l=await crmLead(c,a,id);const label=(await c.query("SELECT CASE $1 WHEN 'listing' THEN (SELECT title FROM listings WHERE id=$2 AND organization_id=$3) WHEN 'development' THEN (SELECT name FROM developments WHERE id=$2 AND organization_id=$3) WHEN 'agent' THEN (SELECT name FROM agents WHERE id=$2 AND organization_id=$3) WHEN 'provider' THEN (SELECT name FROM providers WHERE id=$2 AND organization_id=$3) END AS label",[l.resource_type,l.resource_id,a.orgId])).rows[0];return data({...l,resourceLabel:label.label??null});});}
 @Get('ops/leads/:id/timeline') async timeline(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['agent','agency_manager','developer','vendor','admin']);return transaction(a,async c=>{await crmLead(c,a,id);return data((await c.query('SELECT * FROM lead_activity WHERE lead_id=$1 ORDER BY created_at,id',[id])).rows);});}
 @Post('ops/leads/:id/notes') async note(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager','developer','vendor','admin']),x=leadNoteCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const l=await crmLead(c,a,id,true);if(l.version!==x.version)fail(409,'Lead changed; refresh before adding a note','LEAD_CHANGED');if(['won','lost','closed','converted'].includes(l.status))fail(409,'Closed inquiries cannot receive new notes');const r=(await c.query('UPDATE leads SET version=version+1 WHERE id=$1 RETURNING *',[id])).rows[0];const note=(await c.query("INSERT INTO lead_activity(lead_id,kind,actor_id,version,status,agent_id,text) VALUES($1,'note',$2,$3,$4,$5,$6) RETURNING *",[id,a.id,r.version,r.status,r.agent_id,x.text])).rows[0];await event(c,a,id,'lead.note_added',{version:r.version});return data({lead:r,note});}));}
}
