import {Controller,Get,Patch,Post,Req,Param,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import {z} from 'zod';
import {event} from '@haven/database';
import {notificationPreferenceUpdate,notificationVersion,notificationPlanInput,notificationEventInput} from '@haven/contracts';
import {validNotificationWorker} from '@haven/config';
import {Identity,data,fail,transaction,idempotent,env} from '../platform/core.js';
import {AlertService,alertUserLock,alertView} from './alert-service.js';
async function preferences(c:import('pg').PoolClient,id:string){const row=(await c.query('SELECT * FROM notification_preferences WHERE user_id=$1',[id])).rows[0];return {emailEnabled:row?.email_enabled??false,inAppEnabled:row?.in_app_enabled??false,version:row?.version??0};}
@Controller('api/v1')
export class NotificationsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('me/notification-preferences') async preferences(@Req() req:FastifyRequest){const actor=await this.identity.actor(req);return transaction(actor,async c=>data(await preferences(c,actor.id)));}
 @Patch('me/notification-preferences') async update(@Req() req:FastifyRequest,@Body() body:unknown){const actor=await this.identity.actor(req),input=notificationPreferenceUpdate.parse(body);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{await alertUserLock(c,actor.id);const current=await preferences(c,actor.id);if(current.version!==input.version)fail(409,'Notification preferences changed. Reload before saving.','NOTIFICATION_PREFERENCES_CHANGED');if(input.emailEnabled){const profile=(await c.query('SELECT email,email_verified FROM profiles WHERE id=$1 AND state=\'active\'',[actor.id])).rows[0];if(!profile||profile.email_verified!==true||!z.email().safeParse(profile.email).success)fail(409,'Verify your email with the sign-in service, then sign in again before enabling email alerts.','EMAIL_VERIFICATION_REQUIRED');}if(current.emailEnabled!==input.emailEnabled||current.inAppEnabled!==input.inAppEnabled){await c.query('INSERT INTO notification_preferences(user_id,email_enabled,in_app_enabled) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET email_enabled=EXCLUDED.email_enabled,in_app_enabled=EXCLUDED.in_app_enabled,version=notification_preferences.version+1',[actor.id,input.emailEnabled,input.inAppEnabled]);await event(c,actor,actor.id,'account.notification_preferences_changed',{version:input.version+1,emailEnabled:input.emailEnabled,inAppEnabled:input.inAppEnabled});}return data(await preferences(c,actor.id));}));}
 @Get('me/notifications') async read(@Req() req:FastifyRequest){const actor=await this.identity.actor(req);return transaction(actor,async c=>data((await c.query(`SELECT n.id,n.title,n.body,n.version,n.read_at,n.created_at,COALESCE(d.status,n.email_status) status FROM notifications n LEFT JOIN alert_digests d ON d.id=n.alert_digest_id WHERE n.user_id=$1 ORDER BY n.created_at DESC,n.id LIMIT 100`,[actor.id])).rows.map(row=>({id:row.id,title:row.title,body:row.body,version:row.version,readAt:row.read_at?new Date(row.read_at).toISOString():null,createdAt:new Date(row.created_at).toISOString(),link:row.status?'/account/searches':null,deliveryStatus:row.status??null}))));}
 @Patch('me/notifications/:id/read') async markRead(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const actor=await this.identity.actor(req),input=notificationVersion.parse(body);z.uuid().parse(id);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{const row=(await c.query('SELECT * FROM notifications WHERE id=$1 AND user_id=$2 FOR UPDATE',[id,actor.id])).rows[0];if(!row)fail(404,'Notification not found');if(row.version!==input.version)fail(409,'Notification changed. Reload before marking it read.','VERSION_CONFLICT');if(!row.read_at){await c.query('UPDATE notifications SET read_at=now(),version=version+1 WHERE id=$1',[id]);await event(c,actor,id,'account.notification_read',{version:input.version+1});}return data({read:true});}));}
 @Get('me/alert-deliveries') async deliveries(@Req() req:FastifyRequest){const actor=await this.identity.actor(req);return transaction(actor,async c=>data((await c.query('SELECT * FROM alert_digests WHERE user_id=$1 ORDER BY created_at DESC,id LIMIT 100',[actor.id])).rows.map(alertView)));}
 @Post('me/alert-deliveries/:id/retry') async retry(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const actor=await this.identity.actor(req),input=notificationVersion.parse(body);z.uuid().parse(id);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{await alertUserLock(c,actor.id);const row=(await c.query('SELECT * FROM alert_digests WHERE id=$1 AND user_id=$2',[id,actor.id])).rows[0];if(!row)fail(404,'Alert not found');if(row.version!==input.version)fail(409,'Alert changed. Reload before retrying.','VERSION_CONFLICT');if(row.status!=='failed')fail(409,'This alert is not awaiting a retry.','INVALID_ALERT_STATE');const next=(await c.query("SELECT * FROM retry_own_alert($1,$2)",[id,input.version])).rows[0];if(!next)fail(409,'Alert changed. Reload before retrying.','VERSION_CONFLICT');await event(c,actor,id,'notification.digest_ready',{version:next.version,retry:true});return data(alertView(next));}));}
}
function service(req:FastifyRequest){if(!validNotificationWorker(req.method,req.url,req.body,req.headers,env.SESSION_KEY))fail(401,'Notification service authorization is required.','SERVICE_AUTH_REQUIRED');}
@Controller('api/v1')
export class NotificationWorkerController{
 private readonly alerts=new AlertService();
 @Post('internal/alerts/transactional/:id') async transactional(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){service(req);z.uuid().parse(id);notificationEventInput.parse(body);return this.alerts.confirmInquiry(id);}
 @Post('internal/alerts/plan/:id') async plan(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){service(req);z.uuid().parse(id);const input=notificationPlanInput.parse(body);return this.alerts.plan(id,input.listingVersion);}
 @Get('internal/alerts/due') async due(@Req() req:FastifyRequest){service(req);return this.alerts.due();}
 @Get('internal/alerts/:id') async read(@Req() req:FastifyRequest,@Param('id') id:string){service(req);z.uuid().parse(id);return this.alerts.read(id);}
 @Post('internal/alerts/:id/deliver') async deliver(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){service(req);z.uuid().parse(id);const input=notificationVersion.parse(body);return this.alerts.deliver(id,input.version);}
}
