import {Controller,Get,Post,Patch,Delete,Req,Param,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {savedSearchCreate,savedSearchUpdate,savedSearchDelete,listingFilters} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
import {compileListingSearch} from '../geography/search.js';
export const savedSearchCriteriaVersion=1;
export async function normalizeSavedSearch(c:pg.PoolClient,raw:Record<string,string>){
 const parsed=listingFilters.strict().parse(raw),market=(await c.query("SELECT c.id,c.currency,m.data FROM cities c LEFT JOIN market_config m ON m.id=c.slug WHERE c.slug=$1 AND c.status='active'",[parsed.city])).rows[0];if(!market)fail(400,'Choose an active city.','INVALID_CITY');if(parsed.currency&&parsed.currency!==market.currency)fail(400,'Search currency must match the selected city.','CURRENCY_MISMATCH');
 const filters:Record<string,string>=Object.fromEntries(Object.entries(parsed).filter(([key,value])=>value!==undefined&&!['page','cursor','limit'].includes(key)).map(([key,value])=>[key,String(value)]));filters.currency=market.currency;
 if(filters.segment!=='commercial'&&filters.transaction==='rent'&&!filters.rentPeriod)filters.rentPeriod=market.data?.rentPeriod||'month';
 for(const key of ['district','districtId','neighborhoodId','communityId','lineId','stationId','beds','livingRooms','orientation','features','floorCategory','buildingType','finishing','heating','ownership','holdingPeriod','furnishing'])if(filters[key])filters[key]=[...new Set(filters[key].split(','))].sort().join(',');
 const locations=[['districtId','districts d','d.id','d.city_id'],['neighborhoodId','neighborhoods n JOIN districts d ON d.id=n.district_id','n.id','d.city_id'],['communityId','communities co JOIN districts d ON d.id=co.district_id','co.id','d.city_id'],['lineId','transit_lines l','l.id','l.city_id'],['stationId','transit_stations s','s.id','s.city_id']];
 for(const [key,table,column,city] of locations)if(filters[key]){filters[key]=[...new Set(filters[key].toLowerCase().split(','))].sort().join(',');const ids=filters[key].split(',');const matches=(await c.query(`SELECT count(*)::int n FROM ${table} WHERE ${column}=ANY($1::uuid[]) AND ${city}=$2`,[ids,market.id])).rows[0].n;if(matches!==ids.length)fail(400,'Location filters must belong to the selected city.','INVALID_LOCATION');}
 return Object.fromEntries(Object.entries(filters).sort(([a],[b])=>a.localeCompare(b)));
}
export function savedSearchUrl(filters:Record<string,string>){const section=filters.segment==='commercial'?'commercial':filters.transaction==='rent'?'rent':filters.transaction==='sale'?'buy':'search',query=new URLSearchParams(filters);query.delete('city');return '/'+filters.city+'/'+section+'?'+query.toString();}
function view(row:any){const filters=row.filters as Record<string,string>;return {id:row.id,name:row.name,filters,cadence:row.cadence,version:row.version,criteriaVersion:row.criteria_version,paused:row.paused,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),restoreUrl:row.criteria_version===1?savedSearchUrl(filters):'/account/searches',alertEligible:row.criteria_version===1&&!row.paused&&!row.deleted_at&&(row.market_eligible??true)};}
@Controller('api/v1')
export class SavedSearchController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('me/saved-searches') async read(@Req() req:FastifyRequest){const actor=await this.identity.actor(req);return transaction(actor,async c=>data((await c.query("SELECT s.*,EXISTS(SELECT 1 FROM cities c WHERE c.slug=s.filters->>'city' AND c.currency=s.filters->>'currency' AND c.status='active') AS market_eligible FROM saved_searches s WHERE user_id=$1 AND deleted_at IS NULL ORDER BY created_at DESC,id",[actor.id])).rows.map(view)));}
 @Post('me/saved-searches') async create(@Req() req:FastifyRequest,@Body() body:unknown){const actor=await this.identity.actor(req),input=savedSearchCreate.parse(body);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{const filters=await normalizeSavedSearch(c,input.filters);const row=(await c.query('INSERT INTO saved_searches(user_id,name,filters,cadence,criteria_version,paused) VALUES($1,$2,$3,$4,$5,false) RETURNING *',[actor.id,input.name,filters,input.cadence,savedSearchCriteriaVersion])).rows[0];await event(c,actor,row.id,'account.saved_search_created',{version:1,criteriaVersion:savedSearchCriteriaVersion});return data(view(row));}));}
 @Patch('me/saved-searches/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const actor=await this.identity.actor(req),input=savedSearchUpdate.parse(body);z.uuid().parse(id);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{const current=await this.lock(c,actor,id,input.version);const unchanged=Object.keys(input.filters).length===Object.keys(current.filters).length&&Object.entries(input.filters).every(([key,value])=>current.filters[key]===value);const filters=input.paused&&unchanged&&current.criteria_version===savedSearchCriteriaVersion?current.filters:await normalizeSavedSearch(c,input.filters);const row=(await c.query('UPDATE saved_searches SET name=$3,filters=$4,cadence=$5,paused=$6,criteria_version=$7,version=version+1,updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING *',[current.id,actor.id,input.name,filters,input.cadence,input.paused,savedSearchCriteriaVersion])).rows[0];await event(c,actor,id,'account.saved_search_updated',{version:row.version,paused:row.paused});return data(view(row));}));}
 @Delete('me/saved-searches/:id') async remove(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const actor=await this.identity.actor(req),input=savedSearchDelete.parse(body);z.uuid().parse(id);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{await this.lock(c,actor,id,input.version);const row=(await c.query('UPDATE saved_searches SET deleted_at=now(),paused=true,version=version+1,updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING version',[id,actor.id])).rows[0];await event(c,actor,id,'account.saved_search_deleted',{version:row.version});return data({deleted:true,version:row.version});}));}
 @Get('me/saved-searches/:id/matches') async matches(@Req() req:FastifyRequest,@Param('id') id:string){const actor=await this.identity.actor(req);z.uuid().parse(id);return transaction(actor,async c=>{const row=(await c.query('SELECT * FROM saved_searches WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[id,actor.id])).rows[0];if(!row)fail(404,'Saved search not found');if(row.paused||row.criteria_version!==savedSearchCriteriaVersion)return data({eligible:false,reason:row.paused?'paused':'criteria-update-required',listings:[]});const market=(await c.query("SELECT currency FROM cities WHERE slug=$1 AND status='active'",[row.filters.city])).rows[0];if(!market||market.currency!==row.filters.currency)return data({eligible:false,reason:'city-or-currency-changed',listings:[]});const filters=await normalizeSavedSearch(c,row.filters);if(Object.keys(filters).length!==Object.keys(row.filters).length||Object.entries(filters).some(([key,value])=>row.filters[key]!==value))fail(409,'Search criteria need an update. Edit this saved search.','CRITERIA_CHANGED');const compiled=compileListingSearch(listingFilters.parse(filters));const listings=(await c.query(`SELECT id,slug,title,city,currency,price,version FROM public_listings WHERE ${compiled.where} ORDER BY ${compiled.order} LIMIT 50`,compiled.values)).rows;return data({eligible:true,reason:null,listings});});}
 private async lock(c:pg.PoolClient,actor:Actor,id:string,version:number){const row=(await c.query('SELECT * FROM saved_searches WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL FOR UPDATE',[id,actor.id])).rows[0];if(!row)fail(404,'Saved search not found');if(row.version!==version)fail(409,'Saved search changed. Reload before saving.','SAVED_SEARCH_CHANGED');return row;}
}
