import {Controller,Get,Post,Req,Param,Query,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {viewingCalendarQuery,viewingRescheduleQuery,viewingReschedule,viewingTerminalAction,viewingBookingCancel} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {crmAuthority} from './crm.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
async function scoped(c:pg.PoolClient,a:Actor,id:string,professional:boolean,lock=false){z.uuid().parse(id);if(professional)await crmAuthority(c,a);const row=(await c.query('SELECT * FROM viewings WHERE id=$1 AND (CASE WHEN $2 THEN professional_viewing_scope(id) ELSE user_id=$3 END)'+(lock?' FOR UPDATE':''),[id,professional,a.id])).rows[0];if(!row)fail(404,'Viewing not found in your calendar');return row;}
async function locked(c:pg.PoolClient,a:Actor,id:string,professional:boolean,version:number){const first=await scoped(c,a,id,professional);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['viewing-agent:'+first.agent_id]);const row=await scoped(c,a,id,professional,true);if(row.version!==version)fail(409,'Viewing changed; refresh your calendar before continuing','VIEWING_CHANGED');if(!['requested','confirmed'].includes(row.status))fail(409,'This viewing is no longer active');return row;}
export async function viewingCalendar(a:Actor,input:ReturnType<typeof viewingCalendarQuery.parse>,professional:boolean){return transaction(a,async c=>{if(professional)await crmAuthority(c,a);const rows=(await c.query('SELECT * FROM viewing_calendar_rows($1,$2,$3,$4,$5)',[professional,input.status??null,input.from??null,input.to??null,(input.page-1)*50])).rows;return data(rows.slice(0,50),{page:input.page,hasMore:rows.length>50});});}
async function rescheduleSlots(a:Actor,id:string,input:ReturnType<typeof viewingRescheduleQuery.parse>,professional:boolean){return transaction(a,async c=>{const row=await scoped(c,a,id,professional);if(!['requested','confirmed'].includes(row.status))fail(409,'This viewing is no longer active');if(row.end_at<=new Date())fail(409,'Past viewings cannot be rescheduled');const ctx=(await c.query('SELECT * FROM public_viewing_schedule($1)',[row.listing_id])).rows[0];if(!ctx)fail(404,'Property is no longer available for rescheduling');if(ctx.agent_id!==row.agent_id)fail(409,'The assigned viewing agent has changed; contact the property team');const time=(await c.query('SELECT statement_timestamp() AS now')).rows[0].now,slots=ctx.schedule_version?(await c.query('SELECT * FROM viewing_reschedule_slot_rows($1,$2,$3)',[id,input.date??null,input.days])).rows.map(r=>({startAt:new Date(r.start_at).toISOString(),endAt:new Date(r.end_at).toISOString()})):[];return data({listingId:row.listing_id,listingVersion:ctx.listing_version,agentId:ctx.agent_id,timeZone:ctx.time_zone,scheduleVersion:ctx.schedule_version??null,durationMinutes:ctx.duration_minutes??null,bufferMinutes:Math.max(row.buffer_minutes,ctx.buffer_minutes??0),asOf:new Date(time).toISOString(),slots,message:slots.length?null:'No future viewing times are available for rescheduling.'});});}
async function move(a:Actor,req:FastifyRequest,id:string,x:ReturnType<typeof viewingReschedule.parse>,professional:boolean){return transaction(a,c=>idempotent(c,a,req,x,async()=>{const initial=await scoped(c,a,id,professional),ctx=(await c.query('SELECT * FROM viewing_reservation_context($1)',[initial.listing_id])).rows[0];if(!ctx)fail(404,'Property is no longer available for rescheduling');if(ctx.agent_id!==initial.agent_id)fail(409,'The assigned viewing agent changed; contact the property team');if(ctx.listing_version!==x.listingVersion||ctx.schedule_version!==x.scheduleVersion)fail(409,'Property or availability changed; refresh its viewing times');const row=await scoped(c,a,id,professional,true);if(row.version!==x.version)fail(409,'Viewing changed; refresh before rescheduling');if(!['requested','confirmed'].includes(row.status))fail(409,'This viewing is no longer active');if(row.end_at<=new Date())fail(409,'Past viewings cannot be rescheduled');const start=new Date(x.startAt),end=new Date(start.getTime()+ctx.duration_minutes*60000),gap=Math.max(row.buffer_minutes,ctx.buffer_minutes);if(start.getTime()===row.start_at.getTime()&&end.getTime()===row.end_at.getTime())fail(409,'Choose a different viewing time');if(!(await c.query('SELECT viewing_slot_valid($1,$2,$3,$4,$5) AS valid',[row.listing_id,start,end,id,gap])).rows[0].valid)fail(409,'This viewing time is no longer available; your original booking is preserved','SLOT_UNAVAILABLE');const saved=(await c.query("UPDATE viewings SET start_at=$2,end_at=$3,status=$4,version=version+1,listing_version=$5,availability_version=$6,property_zone=$7,buffer_minutes=$8 WHERE id=$1 RETURNING *",[id,start,end,professional?row.status:'requested',ctx.listing_version,ctx.schedule_version,ctx.time_zone,gap])).rows[0];await event(c,a,id,'viewing.rescheduled',{version:saved.version});return data(saved);}));}
async function cancelProfessional(a:Actor,req:FastifyRequest,id:string,x:ReturnType<typeof viewingBookingCancel.parse>){return transaction(a,c=>idempotent(c,a,req,x,async()=>{await locked(c,a,id,true,x.version);const saved=(await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE id=$1 RETURNING *",[id])).rows[0];await event(c,a,id,'viewing.cancelled',{version:saved.version});return data(saved);}));}
async function outcome(a:Actor,req:FastifyRequest,id:string,x:ReturnType<typeof viewingTerminalAction.parse>){return transaction(a,c=>idempotent(c,a,req,x,async()=>{const row=await locked(c,a,id,true,x.version);if(row.status!=='confirmed'||row.end_at>new Date())fail(409,'Record an outcome only after a confirmed viewing has ended');const saved=(await c.query('UPDATE viewings SET status=$2,version=version+1 WHERE id=$1 RETURNING *',[id,x.status])).rows[0];await event(c,a,id,'viewing.'+x.status,{version:saved.version});return data(saved);}));}
@Controller('api/v1')
export class ViewingCalendarController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('viewings/:id/slots') async slots(@Req() req:FastifyRequest,@Param('id') id:string,@Query() input:unknown){const a=await this.identity.actor(req),x=viewingRescheduleQuery.parse(input);return rescheduleSlots(a,id,x,false);}
 @Get('ops/viewings/:id/slots') async opsSlots(@Req() req:FastifyRequest,@Param('id') id:string,@Query() input:unknown){const a=await this.identity.actor(req,['agent','agency_manager','admin']),x=viewingRescheduleQuery.parse(input);return rescheduleSlots(a,id,x,true);}
 @Post('viewings/:id/reschedule') async reschedule(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),x=viewingReschedule.parse(body);return move(a,req,id,x,false);}
 @Post('ops/viewings/:id/reschedule') async opsReschedule(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager','admin']),x=viewingReschedule.parse(body);return move(a,req,id,x,true);}
 @Post('ops/viewings/:id/cancel') async cancel(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager','admin']),x=viewingBookingCancel.parse(body);return cancelProfessional(a,req,id,x);}
 @Post('ops/viewings/:id/outcome') async terminal(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager','admin']),x=viewingTerminalAction.parse(body);return outcome(a,req,id,x);}
}
