import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {viewingBookingCreate,viewingBookingConfirm,viewingBookingCancel} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {crmAuthority} from './crm.js';
import {data,fail,transaction,idempotent} from '../platform/core.js';
async function context(c:pg.PoolClient,id:string,listingVersion:number,scheduleVersion:number){const ctx=(await c.query('SELECT * FROM viewing_reservation_context($1)',[id])).rows[0];if(!ctx)fail(404,'Property is no longer available');if(!ctx.agent_id)fail(409,'No eligible viewing agent is currently assigned','AGENT_UNAVAILABLE');if(ctx.listing_version!==listingVersion)fail(409,'Property changed; refresh its viewing times','LISTING_CHANGED');if(!ctx.schedule_version||ctx.schedule_version!==scheduleVersion)fail(409,'Availability changed; refresh its viewing times','AVAILABILITY_CHANGED');return ctx;}
async function valid(c:pg.PoolClient,listing:string,start:Date,end:Date,skip?:string,gap=0){if(!(await c.query('SELECT viewing_slot_valid($1,$2,$3,$4,$5) AS valid',[listing,start,end,skip??null,gap])).rows[0].valid)fail(409,'This viewing time is no longer available. Refresh and choose another time.','SLOT_UNAVAILABLE');}
export async function reserveViewing(a:Actor,req:FastifyRequest,x:ReturnType<typeof viewingBookingCreate.parse>){return transaction(a,c=>idempotent(c,a,req,x,async()=>{const ctx=await context(c,x.listingId,x.listingVersion,x.scheduleVersion);if(ctx.agent_id!==x.agentId)fail(409,'The assigned viewing agent changed; refresh its viewing times','AGENT_CHANGED');const start=new Date(x.startAt);if(start.getTime()<=Date.now())fail(400,'Choose a future viewing time');const end=new Date(start.getTime()+ctx.duration_minutes*60000);await valid(c,x.listingId,start,end);const row=(await c.query('INSERT INTO viewings(listing_id,user_id,agent_id,start_at,end_at,listing_version,availability_version,property_zone,buffer_minutes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[x.listingId,a.id,ctx.agent_id,start,end,ctx.listing_version,ctx.schedule_version,ctx.time_zone,ctx.buffer_minutes])).rows[0];await event(c,a,row.id,'viewing.requested',{version:row.version});return data(row);}));}
export async function confirmViewing(a:Actor,req:FastifyRequest,id:string,x:ReturnType<typeof viewingBookingConfirm.parse>){return transaction(a,c=>idempotent(c,a,req,x,async()=>{await crmAuthority(c,a);const initial=(await c.query('SELECT * FROM viewings WHERE id=$1',[id])).rows[0];if(!initial||(await c.query('SELECT viewing_schedule_scope($1,$2) AS allowed',[initial.listing_id,initial.agent_id])).rows[0].allowed!==true)fail(404,'Assigned viewing not found');const ctx=await context(c,initial.listing_id,x.listingVersion,x.scheduleVersion),row=(await c.query('SELECT * FROM viewings WHERE id=$1 FOR UPDATE',[id])).rows[0];if(row.version!==x.version)fail(409,'Viewing changed; refresh before confirming');if(row.status!=='requested'||row.agent_id!==ctx.agent_id)fail(409,'This viewing cannot be confirmed');const gap=Math.max(row.buffer_minutes,ctx.buffer_minutes);await valid(c,row.listing_id,row.start_at,row.end_at,row.id,gap);const saved=(await c.query("UPDATE viewings SET status='confirmed',version=version+1,listing_version=$2,availability_version=$3,property_zone=$4,buffer_minutes=$5 WHERE id=$1 RETURNING *",[id,ctx.listing_version,ctx.schedule_version,ctx.time_zone,gap])).rows[0];await event(c,a,id,'viewing.confirmed',{version:saved.version});return data(saved);}));}
export async function cancelOwnViewing(a:Actor,req:FastifyRequest,id:string,x:ReturnType<typeof viewingBookingCancel.parse>){return transaction(a,c=>idempotent(c,a,req,x,async()=>{const initial=(await c.query('SELECT * FROM viewings WHERE id=$1 AND user_id=$2',[id,a.id])).rows[0];if(!initial)fail(404,'Your viewing was not found');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['viewing-agent:'+initial.agent_id]);const row=(await c.query('SELECT * FROM viewings WHERE id=$1 AND user_id=$2 FOR UPDATE',[id,a.id])).rows[0];if(!row)fail(404,'Your viewing was not found');if(row.version!==x.version)fail(409,'Viewing changed; refresh before cancelling');if(!['requested','confirmed'].includes(row.status))fail(409,'This viewing cannot be cancelled');const saved=(await c.query("UPDATE viewings SET status='cancelled',version=version+1 WHERE id=$1 RETURNING *",[id])).rows[0];await event(c,a,id,'viewing.cancelled',{version:saved.version});return data(saved);}));}
