import {Controller,Get,Post,Patch,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {agencyInvite,agencyInviteDecision,agencyMembershipUpdate} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const fields=`i.id,i.organization_id AS "organizationId",o.name AS "organizationName",i.email,i.role,CASE WHEN i.status='pending' AND i.expires_at<=now() THEN 'expired' ELSE i.status END AS status,i.version,i.expires_at AS "expiresAt",i.created_at AS "createdAt"`;
async function manager(c:pg.PoolClient,a:Actor){if(!a.orgId||!(await c.query("SELECT 1 FROM organizations o WHERE o.id=$1 AND o.type='agency' AND EXISTS(SELECT 1 FROM memberships m WHERE m.user_id=$2 AND m.organization_id=o.id AND m.status='active' AND m.role='agency_manager')",[a.orgId,a.id])).rowCount)fail(403,'An active manager membership in this agency is required');}
export async function agencyMembers(c:pg.PoolClient,a:Actor){await manager(c,a);return (await c.query(`SELECT m.id,m.user_id AS "userId",p.display_name AS "displayName",m.role,m.status,m.version FROM memberships m JOIN profiles p ON p.id=m.user_id WHERE m.organization_id=$1 ORDER BY p.display_name,m.role,m.id`,[a.orgId])).rows;}
@Controller('api/v1')
export class AgencyMembershipsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/agency-invitations') async invitations(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agency_manager','admin']);return transaction(a,async c=>{await manager(c,a);return data((await c.query(`SELECT ${fields} FROM agency_invitations i JOIN organizations o ON o.id=i.organization_id WHERE i.organization_id=$1 ORDER BY i.created_at DESC LIMIT 100`,[a.orgId])).rows);});}
 @Post('ops/agency-invitations') async invite(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['agency_manager','admin']),x=agencyInvite.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{await manager(c,a);const self=(await c.query('SELECT email FROM profiles WHERE id=$1',[a.id])).rows[0];if(self.email.toLowerCase()===x.email)fail(400,'A manager cannot invite themselves');if((await c.query("SELECT 1 FROM memberships m JOIN profiles p ON p.id=m.user_id WHERE m.organization_id=$1 AND m.role=$2 AND m.status='active' AND lower(p.email)=$3",[a.orgId,x.role,x.email])).rowCount)fail(409,'This agency permission is already active');const expired=await c.query("UPDATE agency_invitations SET status='expired',version=version+1 WHERE organization_id=$1 AND email=$2 AND role=$3 AND status='pending' AND expires_at<=now() RETURNING id",[a.orgId,x.email,x.role]);for(const r of expired.rows)await event(c,a,r.id,'agency.invitation_expired');const r=(await c.query(`INSERT INTO agency_invitations(organization_id,email,role,created_by,reason) VALUES($1,$2,$3,$4,$5) RETURNING id`,[a.orgId,x.email,x.role,a.id,x.reason])).rows[0];await event(c,a,r.id,'agency.invited');return data((await c.query(`SELECT ${fields} FROM agency_invitations i JOIN organizations o ON o.id=i.organization_id WHERE i.id=$1`,[r.id])).rows[0]);}));}
 @Get('me/agency-invitations') async own(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query(`SELECT ${fields} FROM agency_invitations i JOIN organizations o ON o.id=i.organization_id JOIN profiles p ON p.id=$1 AND p.state='active' AND p.email_verified=true AND lower(p.email)=i.email ORDER BY i.created_at DESC LIMIT 100`,[a.id])).rows));}
 @Patch('agency-invitations/:id') async decision(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),x=agencyInviteDecision.parse(body);return transaction(a,async c=>{const r=(await c.query(`SELECT i.*,p.email AS actor_email,p.email_verified FROM agency_invitations i JOIN profiles p ON p.id=$2 AND p.state='active' WHERE i.id::text=$1 FOR UPDATE OF i,p`,[id,a.id])).rows[0];if(!r)fail(404,'Invitation not found');if(r.version!==x.version||r.status!=='pending'||new Date(r.expires_at).getTime()<=Date.now())fail(409,'Invitation changed or expired');if(x.action==='cancel'){await manager(c,a);if(r.organization_id!==a.orgId)fail(404,'Invitation not found');await c.query("UPDATE agency_invitations SET status='cancelled',version=version+1,reason=$2 WHERE id=$1",[r.id,x.reason]);}else{if(!r.email_verified||r.actor_email.toLowerCase()!==r.email)fail(403,'Only the verified invited recipient can decide');if(x.action==='accept')await c.query('SELECT * FROM accept_agency_invitation($1,$2,$3)',[r.id,x.version,x.reason]);else await c.query("SELECT decline_agency_invitation($1,$2,$3)",[r.id,x.version,x.reason]);}await event(c,a,r.id,'agency.invitation_'+x.action);return data((await c.query(`SELECT ${fields} FROM agency_invitations i JOIN organizations o ON o.id=i.organization_id WHERE i.id=$1`,[r.id])).rows[0]);});}
 @Get('ops/membership-history') async history(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agency_manager','admin']);return transaction(a,async c=>{await manager(c,a);return data((await c.query('SELECT id,membership_id,target_user_id,actor_id,role,status,previous_role,previous_status,version,reason,created_at FROM agency_membership_history WHERE organization_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100',[a.orgId])).rows);});}
 @Patch('ops/memberships/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agency_manager','admin']),x=agencyMembershipUpdate.parse(body);return transaction(a,async c=>{await manager(c,a);const r=(await c.query('SELECT * FROM memberships WHERE id::text=$1 AND organization_id=$2 FOR UPDATE',[id,a.orgId])).rows[0];if(!r||!['agent','agency_manager'].includes(r.role))fail(404,'Editable agency member not found');if(r.user_id===a.id)fail(403,'A manager cannot change their own agency authority');if(r.version!==x.version)fail(409,'Membership changed; refresh before editing');if(r.status==='active'&&x.status==='active'&&r.role===x.role)fail(409,'Membership already has this permission');await c.query('UPDATE memberships SET role=$2,status=$3,version=version+1,change_reason=$4 WHERE id=$1',[r.id,x.role,x.status,x.reason]);return data((await agencyMembers(c,a)).find(m=>m.id===r.id));});}
}
