import {fixtureId as id,personaId as person,fixtureClock} from './index';
export function beijingFixtures(){
 const organizationNames=[['Haven Beijing Agency','agency'],['Northstar Property Management','manager'],['Garden City Developments','developer'],['Studio Form Interiors','vendor'],['Independent Agency','agency']];
 const organizations=organizationNames.map(([name,type],i)=>({id:id(i+1),name,type}));
 const names=['buyer','owner','agent','manager','tenant','developer','vendor','moderator','support','admin','outsider'];
 const roles=[['consumer'],['owner','consumer'],['agent','consumer'],['property_manager','finance'],['tenant','consumer'],['developer'],['vendor'],['moderator'],['support'],['admin','finance','editor','agency_manager'],['agent']];
 const orgs=[1,1,1,2,2,3,4,1,1,1,5];
 const personas=names.map((name,i)=>({id:person(i+1),subject:person(i+1),displayName:name[0].toUpperCase()+name.slice(1)+' Demo',email:name+'@example.test',organizationId:id(orgs[i]),roles:roles[i]}));
 const city={id:id(10),slug:'bj',name:'Beijing',country:'CN',currency:'CNY',timezone:'Asia/Shanghai'};
 const districts=['Chaoyang','Haidian','Dongcheng','Xicheng','Fengtai','Shunyi'].map((name,i)=>({id:id(20+i),cityId:city.id,name,slug:name.toLowerCase()}));
 const communities=['Willow Park','Garden Residence','River Court','East Lake Gardens','Maple Quarter','Skyline Community'].map((name,i)=>({id:id(40+i),districtId:districts[i].id,slug:name.toLowerCase().replaceAll(' ','-'),name,address:districts[i].name+' district, Beijing',builtYear:2012+i,amenities:['Elevator','Garden','Near metro','Community security'],photos:['/homes/home-'+(i%6+1)+'.jpg'],longitude:116.38+i*.03,latitude:39.9+i*.015}));
 const agents=['Olivia Chen','Daniel Wang','Grace Liu','James Lin'].map((name,i)=>({id:id(60+i),userId:person(3),organizationId:id(1),name,slug:name.toLowerCase().replaceAll(' ','-'),biography:'Local property guidance with clear communication and careful attention to your priorities. Synthetic demonstration profile.',languages:['English','Mandarin'],districts:[districts[i].name],verifiedUntil:'2027-12-31',publicEmail:'agent@example.test'}));
 const titles=['Light-filled home beside the gardens','A calm retreat with room to grow','South-facing apartment near the metro','Open-plan living in a leafy community','Spacious family home with a balcony','Contemporary home with city views'];
 const listings=Array.from({length:102},(_,i)=>{
  const transaction=i<60?'sale':i<90?'rent':'sale',commercial=i>=90,community=communities[i%6];
  return {id:id(2000+i),unitId:id(1000+i),organizationId:id(i===101?5:1),ownerId:person(2),agentId:agents[i%4].id,slug:(commercial?'workspace-':transaction==='rent'?'rental-':'home-')+(i+1),title:commercial?'Flexible office space in '+community.name:titles[i%6],description:'A thoughtfully arranged property in '+community.name+'. Enjoy practical living spaces, natural light, nearby transport, and the convenience of an established neighborhood. All inventory is synthetic development data.',transaction,segment:commercial?'commercial':'residential',currency:'CNY',price:i===100?null:String(transaction==='rent'?4500+i%9*850:3200000+i%15*380000),rentPeriod:transaction==='rent'?'month':null,status:i===99?'sold':i===101?'draft':i===60?'leased':'published',features:['Near metro',i%2?'South-facing':'Garden views','Elevator'],photos:i===98?[]:['/homes/home-'+(i%6+1)+'.jpg','/homes/home-'+((i+1)%6+1)+'.jpg'],furnishing:i%2?'Furnished':'Unfurnished',availableFrom:'2026-11-01',publishedAt:new Date(Date.UTC(2026,9,4)-i*3600000).toISOString(),residential:commercial?null:{finishing:'Good condition',heating:'Central heating',ownershipAttributes:['Owner supplied'],holdingPeriodAttributes:[],occupancy:'unknown'},commercial:commercial?{propertyType:'office',grossArea:String(180+i),usableArea:String(160+i),fitOut:'Basic fit-out',floor:3+i%15,parkingSpaces:2,permittedUses:['Office'],rentBasis:'total'}:null,rental:transaction==='rent'?{rentalMode:'entire',minimumMonths:12,depositAmount:'6500.00',currency:'CNY',billingPeriod:'month',utilities:['Utilities billed separately'],moveInDate:'2026-11-01',roomAttributes:[]}:null,unit:{id:id(1000+i),communityId:community.id,organizationId:id(i===101?5:1),privateAddress:'PRIVATE_FIXTURE_UNIT_'+i,area:String(commercial?180+i:68+i%9*14),beds:commercial?0:1+i%4,livingRooms:1+i%2,baths:1+i%2,orientation:i%2?'South':'South East',floor:3+i%15}};
 });
 const developments=Array.from({length:8},(_,i)=>({id:id(3000+i),organizationId:id(3),communityId:communities[i%6].id,slug:'garden-collection-'+(i+1),name:['The Garden Collection','Lakeside Residences','Parkside Heights','The Willow Quarter'][i%4]+' '+(i+1),description:'New homes designed around green spaces, shared amenities and generous daylight. Synthetic development inventory.',status:'on_sale',priceMin:'52000.00',priceMax:'68000.00',completionDate:'2028-06-30',photos:['/homes/home-'+(i%6+1)+'.jpg'],features:['New development','Landscaped gardens','Community gym'],inventoryAt:fixtureClock}));
 const floorPlans=developments.flatMap((development,i)=>Array.from({length:3},(_,j)=>({id:id(3100+i*3+j),developmentId:development.id,name:'Type '+String.fromCharCode(65+j),beds:j+1,livingRooms:1,area:String(65+j*35),available:j===2?0:12-j*4,photo:null})));
 const providers=['Studio Form','Quiet Space Design','Green Room Renovation'].map((name,i)=>({id:id(4000+i),organizationId:id(4),slug:'studio-form-'+(i+1),name,description:'Thoughtful design and practical renovation for your next chapter. Synthetic provider profile.',categories:['Interior design','Renovation'],districts:districts.map(d=>d.name),photos:['/homes/home-'+(i+1)+'.jpg'],status:'approved'}));
 const additionalCities=[{id:id(11),slug:'sh',name:'Shanghai',country:'CN',currency:'CNY',timezone:'Asia/Shanghai'}];
 const additionalDistricts=[{id:id(26),cityId:id(11),slug:'pudong',name:'Pudong'}];
 const neighborhoods=districts.map((district,i)=>({id:id(70+i),districtId:district.id,slug:'garden-quarter',name:district.name+' Garden Quarter',aliases:['Garden Quarter']}));
 const transitLines=[{id:id(80),cityId:city.id,slug:'garden-line',name:'Garden Line',aliases:['Demo Metro']}];
 const transitStations=districts.map((district,i)=>({id:id(90+i),cityId:city.id,lineId:id(80),districtId:district.id,slug:district.slug+'-station',name:district.name+' Garden Station',aliases:[],latitude:39.9+i*.015,longitude:116.38+i*.03}));
 const buildings=communities.flatMap((community,i)=>Array.from({length:2},(_,j)=>({id:id(100+i*2+j),communityId:community.id,slug:'building-'+String.fromCharCode(97+j),name:'Building '+String.fromCharCode(65+j),floors:18+i,completedYear:community.builtYear})));
 return {schemaVersion:1,clock:fixtureClock,provenance:'Synthetic development inventory. No benchmark people or private property information.',organizations,personas,city,districts,additionalCities,additionalDistricts,neighborhoods,transitLines,transitStations,buildings,communities,agents,listings,developments,floorPlans,providers};
}
