import {Controller,Post,Get,Req,Res,Param,Body,Inject} from '@nestjs/common';
import type {FastifyRequest,FastifyReply} from 'fastify';
import {z} from 'zod';
import {chatUploadIntent} from '@haven/contracts';
import {event} from '@haven/database';
import {Identity,transaction,data,fail,idempotent,encrypt} from '../platform/core.js';
import {conversationGrant} from '../engagement/conversations.js';
import {readPrivateObject} from './media.js';
@Controller('api/v1')
export class ChatMediaController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Post('conversations/:id/attachment-intents') async intent(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),x=chatUploadIntent.parse(body);if(x.mime!=='application/pdf'&&x.size>10*1024*1024)fail(400,'Images must be at most 10 MB');return transaction(a,c=>idempotent(c,a,req,x,async()=>{const thread=await conversationGrant(c,id,true);if(thread.state!=='active'||thread.version!==x.conversationVersion)fail(409,'Conversation changed or became read-only');const asset=(await c.query("INSERT INTO media_assets(owner_id,object_key,mime,size,rights,visibility,purpose) VALUES($1,$2,$3,$4,$5,'private',$6) RETURNING id,version",[a.id,crypto.randomUUID(),x.mime,x.size,x.rights,x.mime==='application/pdf'?'document':'photo'])).rows[0];await c.query('INSERT INTO conversation_uploads(asset_id,conversation_id,creator_id,filename,mime) VALUES($1,$2,$3,$4,$5)',[asset.id,id,a.id,x.filename,x.mime]);await event(c,a,asset.id,'chat.upload_created',{conversationId:id});const signature=encrypt({assetId:asset.id,actorId:a.id,assetVersion:asset.version,conversationId:id,conversationVersion:thread.version,expires:Date.now()+600000});return data({id:asset.id,uploadUrl:'/api/v1/media/'+asset.id+'/content?signature='+signature,method:'PUT' as const,expiresIn:600});}));}
 @Get('conversations/:conversationId/attachments/:id') async download(@Req() req:FastifyRequest,@Param('conversationId') conversationId:string,@Param('id') id:string,@Res() reply:FastifyReply){z.uuid().parse(id);const a=await this.identity.actor(req);return transaction(a,async c=>{await conversationGrant(c,conversationId);const asset=(await c.query("SELECT a.* FROM media_assets a JOIN conversation_uploads cu ON cu.asset_id=a.id AND cu.conversation_id=$2 WHERE a.id=$1 AND a.visibility='private' AND a.status='approved' AND a.scan_at IS NOT NULL AND EXISTS(SELECT 1 FROM message_attachments ma JOIN messages m ON m.id=ma.message_id WHERE ma.asset_id=a.id AND m.conversation_id=$2 AND m.sender_id=a.owner_id)",[id,conversationId])).rows[0];if(!asset)fail(404,'Conversation attachment unavailable');const image=asset.mime.startsWith('image/'),key=image?asset.variants.display:'quarantine/'+asset.object_key;if(!key)fail(404,'Safe attachment variant unavailable');const bytes=await readPrivateObject(key);await event(c,a,id,'chat.attachment_downloaded',{conversationId});reply.header('Content-Type',image?'image/webp':'application/pdf').header('Content-Disposition','attachment; filename="conversation-attachment.'+(image?'webp':'pdf')+'"').header('Cache-Control','no-store');return reply.send(bytes);});}
}
