import {Controller,Get,Post,Param,Query,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import {developmentReviewSubmit,developmentReviewDecision,developmentReviewQuery} from '@haven/contracts';
import {event} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
@Controller('api/v1')
export class DevelopmentReviewController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/developments/:id/publication') async read(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['developer','admin']);return transaction(a,async c=>{const project=(await c.query('SELECT * FROM developments WHERE id=$1 AND (organization_id=$2 OR $3)',[id,a.orgId,a.roles.includes('admin')])).rows[0];if(!project)fail(404,'Assigned project not found');return data({project,review:(await c.query('SELECT * FROM development_publication WHERE development_id=$1',[id])).rows[0]});});}
 @Get('ops/developments/:id/leads') async leads(@Req() req:FastifyRequest,@Param('id') id:string,@Query() input:unknown){const a=await this.identity.actor(req,['developer','admin']),x=developmentReviewQuery.parse(input);return transaction(a,async c=>{const project=(await c.query('SELECT name FROM developments WHERE id=$1 AND (organization_id=$2 OR $3)',[id,a.orgId,a.roles.includes('admin')])).rows[0];if(!project)fail(404,'Assigned project not found');return data((await c.query("SELECT l.*,f.name AS type_name,$4::text AS project_name FROM leads l LEFT JOIN floor_plans f ON f.id=l.floor_plan_id AND f.development_id=l.resource_id WHERE l.resource_id=$1 AND l.resource_type='development' ORDER BY l.created_at DESC,l.id LIMIT $2 OFFSET $3",[id,x.limit,(x.page-1)*x.limit,project.name])).rows,{page:x.page,limit:x.limit,total:Number((await c.query("SELECT count(*) AS count FROM leads WHERE resource_id=$1 AND resource_type='development'",[id])).rows[0].count)});});}
 @Post('ops/developments/:id/submit') async submit(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['developer','admin']),x=developmentReviewSubmit.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const project=(await c.query('SELECT * FROM developments WHERE id=$1 AND (organization_id=$2 OR $3) FOR UPDATE',[id,a.orgId,a.roles.includes('admin')])).rows[0];if(!project)fail(404,'Assigned project not found');if(project.version!==x.version)fail(409,'Project changed. Reload before submitting.');const review=(await c.query('SELECT * FROM development_publication WHERE development_id=$1 FOR UPDATE',[id])).rows[0];if(review.state==='submitted')fail(409,'Project is already awaiting review');if(project.name.trim().length<2||project.description.trim().length<20)fail(400,'Complete the project overview before submitting');if(x.requestedStatus==='on_sale'&&!(await c.query("SELECT 1 FROM floor_plans WHERE development_id=$1 AND publication_status='published'",[id])).rowCount)fail(400,'Publish a floor-plan type before opening sales');const updated=(await c.query("UPDATE developments SET status='draft',version=version+1 WHERE id=$1 RETURNING *",[id])).rows[0];const result=(await c.query("UPDATE development_publication SET state='submitted',version=version+1,base_version=$2,submitted_by=$3,submitted_at=now(),reviewed_by=NULL,reviewed_at=NULL,reason='',requested_status=$4 WHERE development_id=$1 RETURNING *",[id,updated.version,a.id,x.requestedStatus])).rows[0];await event(c,a,id,'development.review_submitted',{version:updated.version,reviewVersion:result.version});return data({project:updated,review:result});}));}
 @Get('ops/development-reviews') async queue(@Req() req:FastifyRequest,@Query() input:unknown){const a=await this.identity.actor(req,['moderator','admin']),x=developmentReviewQuery.parse(input);return transaction(a,async c=>data((await c.query("SELECT d.*,to_jsonb(r) AS review FROM development_publication r JOIN developments d ON d.id=r.development_id WHERE r.state='submitted' ORDER BY r.submitted_at,r.development_id LIMIT $1 OFFSET $2",[x.limit,(x.page-1)*x.limit])).rows,{page:x.page,limit:x.limit,total:Number((await c.query("SELECT count(*) AS count FROM development_publication WHERE state='submitted'")).rows[0].count)}));}
 @Get('ops/development-reviews/:id') async detail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['moderator','admin']);return transaction(a,async c=>{const project=(await c.query('SELECT * FROM developments WHERE id=$1',[id])).rows[0];if(!project)fail(404,'Project not found');return data({project,review:(await c.query('SELECT * FROM development_publication WHERE development_id=$1',[id])).rows[0],types:(await c.query('SELECT * FROM floor_plans WHERE development_id=$1 ORDER BY name,id',[id])).rows,phases:(await c.query('SELECT * FROM development_phases WHERE development_id=$1 ORDER BY name,id',[id])).rows});});}
 @Post('ops/development-reviews/:id/decision') async decision(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['moderator','admin']),x=developmentReviewDecision.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const project=(await c.query('SELECT * FROM developments WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!project)fail(404,'Project not found');const review=(await c.query('SELECT * FROM development_publication WHERE development_id=$1 FOR UPDATE',[id])).rows[0];if(project.version!==x.version||review.version!==x.reviewVersion||review.base_version!==project.version||review.state!=='submitted')fail(409,'Project or review changed. Reload before deciding.');if(review.submitted_by===a.id||a.orgId===project.organization_id)fail(403,'An independent reviewer must decide this project');if(x.decision==='approved'&&review.requested_status==='on_sale'&&!(await c.query("SELECT 1 FROM floor_plans WHERE development_id=$1 AND publication_status='published'",[id])).rowCount)fail(400,'An on-sale project needs a published floor-plan type');const result=(await c.query('UPDATE development_publication SET state=$2,version=version+1,reviewed_by=$3,reviewed_at=now(),reason=$4 WHERE development_id=$1 RETURNING *',[id,x.decision,a.id,x.reason])).rows[0];const updated=(await c.query('UPDATE developments SET status=$2,version=version+1 WHERE id=$1 RETURNING *',[id,x.decision==='approved'?review.requested_status:'draft'])).rows[0];await event(c,a,id,'development.review_'+x.decision,{version:updated.version,reviewVersion:result.version,reason:x.reason});return data({project:updated,review:result});}));}
}
