import {createDevelopmentBuilding,updateDevelopmentBuilding} from '../geography/development-buildings.js';
import {Controller,Get,Post,Patch,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {projectCreate,projectUpdate,phaseCreate,phaseUpdate,projectBuildingCreate,projectBuildingUpdate,developmentSalesTransitions} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const roles=['developer','admin'];
async function project(c:pg.PoolClient,a:Actor,id:string,version?:number){const row=(await c.query('SELECT * FROM developments WHERE id=$1 AND (organization_id=$2 OR $3) FOR UPDATE',[id,a.orgId,a.roles.includes('admin')])).rows[0];if(!row)fail(404,'Assigned development not found');if(version!==undefined&&row.version!==version)fail(409,'Project changed. Reload before saving.','PROJECT_CHANGED');return row;}
async function changed(c:pg.PoolClient,a:Actor,id:string,kind:string){const row=(await c.query('UPDATE developments SET version=version+1 WHERE id=$1 RETURNING version',[id])).rows[0];await event(c,a,id,kind,{version:row.version});return row.version as number;}
@Controller('api/v1')
export class DevelopmentProjectsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Post('ops/developments') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=projectCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{if(!a.orgId||!(await c.query("SELECT 1 FROM organizations WHERE id=$1 AND type='developer'",[a.orgId])).rowCount)fail(403,'Select your developer organization','DEVELOPER_REQUIRED');const community=(await c.query("SELECT ci.currency FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE co.id=$1 AND co.status='active' AND d.status='active' AND ci.status='active'",[x.communityId])).rows[0];if(!community)fail(400,'Choose an active community','INVALID_COMMUNITY');const row=(await c.query("INSERT INTO developments(id,organization_id,community_id,slug,name,description,status,currency,photos,features) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,'draft',$6,'{}','{}') RETURNING *",[a.orgId,x.communityId,x.slug,x.name,x.description,community.currency])).rows[0];await event(c,a,row.id,'development.created',{version:1});return data(row);}));}
 @Patch('ops/developments/:id/project') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=projectUpdate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const source=await project(c,a,id,x.version);if(source.status==='sold_out')fail(409,'Reopen sales before editing project facts');const row=(await c.query('UPDATE developments SET name=$2,description=$3,completion_date=$4,version=version+1 WHERE id=$1 RETURNING *',[id,x.name,x.description,x.completionDate])).rows[0];await event(c,a,id,'development.updated',{version:row.version});return data(row);}));}
 @Get('ops/developments/:id/structure') async structure(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,roles);return transaction(a,async c=>{const source=await project(c,a,id);return data({project:source,phases:(await c.query('SELECT * FROM development_phases WHERE development_id=$1 ORDER BY name,id',[id])).rows,buildings:(await c.query('SELECT * FROM buildings WHERE development_id=$1 ORDER BY name,id',[id])).rows});});}
 @Post('ops/developments/:id/phases') async createPhase(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=phaseCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const source=await project(c,a,id,x.projectVersion);if(source.status==='sold_out')fail(409,'Reopen sales before adding a phase');const row=(await c.query('INSERT INTO development_phases(development_id,name,slug) VALUES($1,$2,$3) RETURNING *',[id,x.name,x.slug])).rows[0];return data({...row,projectVersion:await changed(c,a,id,'development.phase_created')});}));}
 @Patch('ops/developments/:id/phases/:phaseId') async updatePhase(@Req() req:FastifyRequest,@Param('id') id:string,@Param('phaseId') phaseId:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=phaseUpdate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{await project(c,a,id,x.projectVersion);const source=(await c.query('SELECT * FROM development_phases WHERE id=$1 AND development_id=$2 FOR UPDATE',[phaseId,id])).rows[0];if(!source)fail(404,'Project phase not found');if(source.version!==x.version)fail(409,'Phase changed. Reload before saving.');if(source.status!==x.status&&!developmentSalesTransitions[source.status]?.includes(x.status))fail(409,'This sales transition is not allowed');const row=(await c.query('UPDATE development_phases SET name=$2,status=$3,version=version+1 WHERE id=$1 RETURNING *',[phaseId,x.name,x.status])).rows[0];return data({...row,projectVersion:await changed(c,a,id,'development.phase_updated')});}));}
 @Post('ops/developments/:id/buildings') async createBuilding(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=projectBuildingCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const row=await createDevelopmentBuilding(c,a,id,x);return data({...row,projectVersion:await changed(c,a,id,'development.building_created')});}));}
 @Patch('ops/developments/:id/buildings/:buildingId') async updateBuilding(@Req() req:FastifyRequest,@Param('id') id:string,@Param('buildingId') buildingId:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=projectBuildingUpdate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const row=await updateDevelopmentBuilding(c,a,id,buildingId,x);return data({...row,projectVersion:await changed(c,a,id,'development.building_updated')});}));}
}
