import {Controller,Get,Post,Patch,Param,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {floorTypeCreate,floorTypeUpdate,offeredUnitCreate,offeredUnitUpdate,offeredUnitTransitions} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const roles=['developer','admin'];
async function project(c:pg.PoolClient,a:Actor,id:string,version?:number){const row=(await c.query('SELECT * FROM developments WHERE id=$1 AND (organization_id=$2 OR $3) FOR UPDATE',[id,a.orgId,a.roles.includes('admin')])).rows[0];if(!row)fail(404,'Assigned development not found');if(version!==undefined&&version!==row.version)fail(409,'Project inventory changed. Reload before saving.','PROJECT_CHANGED');return row;}
async function changed(c:pg.PoolClient,a:Actor,id:string,kind:string){const row=(await c.query('UPDATE developments SET version=version+1,inventory_at=now() WHERE id=$1 RETURNING version',[id])).rows[0];await event(c,a,id,kind,{version:row.version});return row.version as number;}
async function drawing(c:pg.PoolClient,projectId:string,typeId:string,mediaId:string|null,version:number|null){if(!mediaId)return null;const row=(await c.query("SELECT m.*,a.status AS asset_status,a.visibility,a.scan_at,a.purpose FROM listing_media m JOIN media_assets a ON a.id=m.asset_id WHERE m.id=$1 AND m.development_id=$2 AND m.kind='floor_plan' FOR UPDATE OF m",[mediaId,projectId])).rows[0];if(!row||row.status!=='approved'||row.asset_status!=='approved'||row.visibility!=='public'||!row.scan_at||row.purpose!=='floor_plan'||row.floor_plan_id&&row.floor_plan_id!==typeId)fail(400,'Choose an approved drawing belonging to this project and floor-plan type','INVALID_DRAWING');if(row.version!==version)fail(409,'Drawing changed. Reload before saving.');return row;}
@Controller('api/v1')
export class DevelopmentInventoryController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/developments/:id/offered-units') async units(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,roles);return transaction(a,async c=>{const source=await project(c,a,id);return data((await c.query('SELECT o.*,u.area::text,u.building_id,b.name AS building,f.name AS floor_plan_name FROM development_offered_units o JOIN units u ON u.id=o.unit_id JOIN buildings b ON b.id=u.building_id JOIN floor_plans f ON f.id=o.floor_plan_id WHERE o.development_id=$1 ORDER BY o.unit_label,o.id',[id])).rows,{projectVersion:source.version,inventoryAt:source.inventory_at});});}
 @Post('ops/developments/:id/floor-types') async createType(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=floorTypeCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const source=await project(c,a,id,x.projectVersion);if(source.status==='sold_out')fail(409,'Reopen sales before creating a type');const typeId=crypto.randomUUID(),media=await drawing(c,id,typeId,x.mediaId,x.mediaVersion),row=(await c.query("INSERT INTO floor_plans(id,development_id,name,beds,living_rooms,baths,area,area_min,area_max,available,publication_status,inventory_mode,photo) VALUES($1,$2,$3,$4,$5,$6,$7,$7,$8,0,'draft','units',$9) RETURNING *",[typeId,id,x.name,x.beds,x.livingRooms,x.baths,x.areaMin,x.areaMax,media?'/api/v1/media/'+media.asset_id+'/view':null])).rows[0];if(media)await c.query('UPDATE listing_media SET floor_plan_id=$2,version=version+1 WHERE id=$1',[media.id,typeId]);return data({...row,projectVersion:await changed(c,a,id,'development.floor_type_created')});}));}
 @Patch('ops/developments/:id/floor-types/:typeId') async updateType(@Req() req:FastifyRequest,@Param('id') id:string,@Param('typeId') typeId:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=floorTypeUpdate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{await project(c,a,id,x.projectVersion);const source=(await c.query('SELECT * FROM floor_plans WHERE id=$1 AND development_id=$2 FOR UPDATE',[typeId,id])).rows[0];if(!source)fail(404,'Project floor-plan type not found');if(source.version!==x.version)fail(409,'Floor-plan type changed. Reload before saving.');const media=await drawing(c,id,typeId,x.mediaId,x.mediaVersion);const row=(await c.query("UPDATE floor_plans SET name=$2,beds=$3,living_rooms=$4,baths=$5,area=$6,area_min=$6,area_max=$7,photo=$8,publication_status=$9,published_at=CASE WHEN $9='published' AND publication_status<>'published' THEN now() ELSE published_at END,version=version+1 WHERE id=$1 RETURNING *",[typeId,x.name,x.beds,x.livingRooms,x.baths,x.areaMin,x.areaMax,media?'/api/v1/media/'+media.asset_id+'/view':null,x.status])).rows[0];if(media&&media.floor_plan_id!==typeId)await c.query('UPDATE listing_media SET floor_plan_id=$2,version=version+1 WHERE id=$1',[media.id,typeId]);return data({...row,projectVersion:await changed(c,a,id,'development.floor_type_updated')});}));}
 @Post('ops/developments/:id/offered-units') async createUnit(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=offeredUnitCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const source=await project(c,a,id,x.projectVersion);if(source.status==='sold_out')fail(409,'Reopen sales before offering a unit');const type=(await c.query("SELECT * FROM floor_plans WHERE id=$1 AND development_id=$2 AND inventory_mode='units' FOR UPDATE",[x.floorPlanId,id])).rows[0];if(!type)fail(404,'Individual-inventory floor-plan type not found');if(type.baths===null)fail(400,'Record the bathroom count before offering an individual unit');if(type.version!==x.typeVersion)fail(409,'Floor-plan type changed. Reload before saving.');const building=(await c.query("SELECT * FROM buildings WHERE id=$1 AND development_id=$2 AND status='active'",[x.buildingId,id])).rows[0];if(!building)fail(400,'Choose an active building within this project');const unit=(await c.query('INSERT INTO units(community_id,organization_id,building_id,area,beds,living_rooms,baths) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[source.community_id,source.organization_id,building.id,x.area,type.beds,type.living_rooms,type.baths])).rows[0];const row=(await c.query('INSERT INTO development_offered_units(development_id,floor_plan_id,unit_id,unit_label,status) VALUES($1,$2,$3,$4,$5) RETURNING *',[id,type.id,unit.id,x.unitLabel,x.status])).rows[0];return data({...row,projectVersion:await changed(c,a,id,'development.offered_unit_created')});}));}
 @Patch('ops/developments/:id/offered-units/:unitId') async updateUnit(@Req() req:FastifyRequest,@Param('id') id:string,@Param('unitId') unitId:string,@Body() body:unknown){const a=await this.identity.actor(req,roles),x=offeredUnitUpdate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{await project(c,a,id,x.projectVersion);const source=(await c.query('SELECT * FROM development_offered_units WHERE id=$1 AND development_id=$2 FOR UPDATE',[unitId,id])).rows[0];if(!source)fail(404,'Offered unit not found');if(source.version!==x.version)fail(409,'Offered unit changed. Reload before saving.');if(source.status!==x.status&&!offeredUnitTransitions[source.status]?.includes(x.status))fail(409,'This inventory transition is not allowed');const row=(await c.query('UPDATE development_offered_units SET status=$2,version=version+1,updated_at=now() WHERE id=$1 RETURNING *',[unitId,x.status])).rows[0];return data({...row,projectVersion:await changed(c,a,id,'development.offered_unit_updated')});}));}
}
