import type pg from 'pg';
import {z} from 'zod';
import {ownerSchema} from '@haven/contracts';
import {fail} from '../platform/core.js';
export async function validateOwnerStep(c:pg.PoolClient,facts:Record<string,any>,step:number,ownerId:string){
 if(step>=1){ownerSchema.pick({title:true,districtId:true,communityId:true,area:true,beds:true,livingRooms:true,description:true}).parse(facts);if(!(await c.query("SELECT 1 FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE co.id=$1 AND co.district_id=$2 AND ci.slug=$3 AND co.status='active' AND d.status='active' AND ci.status='active'",[facts.communityId,facts.districtId,facts.city])).rowCount)fail(400,'Choose an active community in the selected city and district.','LOCATION_MISMATCH');}
 if(step>=2){ownerSchema.pick({transaction:true,price:true}).parse(facts);if(BigInt(facts.price.replace('.',''))<=0)fail(400,'Enter a positive asking price.','INVALID_PRICE');if(facts.transaction==='rent')z.enum(['day','month','year']).parse(facts.rentPeriod);}
 if(step>=3){const {photos,documents}=z.object({photos:z.array(z.uuid()).min(1,'Add at least one approved property photo.').max(10),documents:z.array(z.uuid()).min(1,'Add approved private ownership evidence.').max(10)}).parse({photos:facts.photos||[],documents:facts.documents||[]});const valid=(await c.query("SELECT id,visibility,mime FROM media_assets WHERE id=ANY($1::uuid[]) AND owner_id=$2 AND status='approved'",[[...photos,...documents],ownerId])).rows;if(photos.some(id=>!valid.some(row=>row.id===id&&row.visibility==='public'&&['image/jpeg','image/png'].includes(row.mime)))||documents.some(id=>!valid.some(row=>row.id===id&&row.visibility==='private'&&row.mime==='application/pdf')))fail(409,'Each photo and ownership document must be approved, owned by you and have the required file type.','MEDIA_REQUIRED');}
 if(step>=4)ownerSchema.pick({contact:true}).parse(facts);
}
export async function validOwnerSubmission(c:pg.PoolClient,row:Record<string,any>){const facts={...row.data};const communityId=z.uuid().parse(facts.communityId),market=(await c.query('SELECT ci.slug AS city,ci.currency FROM communities co JOIN districts d ON d.id=co.district_id JOIN cities ci ON ci.id=d.city_id WHERE co.id=$1',[communityId])).rows[0];if(!market)fail(400,'Choose a recorded community.');facts.city=facts.city||market.city;facts.currency=market.currency;await validateOwnerStep(c,facts,4,row.user_id);const validated=ownerSchema.parse({...facts,consent:true});return {...facts,...validated};}
