import {Controller,Get,Patch,Req,Param,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {rentalTermsUpdate} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,transaction,idempotent,data,fail} from '../platform/core.js';
async function scoped(c:pg.PoolClient,actor:Actor,id:string,lock=false){const row=(await c.query(`SELECT l.*,u.unit_kind,u.parent_unit_id,u.room_label,u.area::text unit_area,u.version unit_version,u.community_id,u.organization_id unit_organization FROM listings l JOIN units u ON u.id=l.unit_id WHERE l.id=$1 AND (l.owner_id=$2 OR $3 OR (l.organization_id=$4 AND ($5 OR l.agent_id IN(SELECT id FROM agents WHERE user_id=$2)))) ${lock?'FOR UPDATE OF l,u':''}`,[id,actor.id,actor.roles.includes('admin'),actor.orgId,actor.roles.includes('agency_manager')])).rows[0];if(!row)fail(404,'Assigned rental not found');if(row.transaction!=='rent')fail(409,'This property is not a rental.','INVALID_RENTAL_STATE');return row;}
async function view(c:pg.PoolClient,row:any){const terms=(await c.query('SELECT * FROM rental_terms WHERE listing_id=$1',[row.id])).rows[0];return{id:row.id,version:row.version,status:row.status,currency:row.currency,unitId:row.unit_id,unitVersion:row.unit_version,unitKind:row.unit_kind,parentUnitId:row.parent_unit_id,roomLabel:row.room_label,area:row.unit_area,mode:terms?.rental_mode??null,billingPeriod:terms?.billing_period??null,depositAmount:terms?.deposit_amount??null,minimumMonths:terms?.minimum_months??null,utilities:terms?.utilities??[],moveInDate:terms?.move_in_date?new Date(terms.move_in_date).toISOString().slice(0,10):null,roomAttributes:terms?.room_attributes??[]};}
@Controller('api/v1')
export class RentalTermsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('ops/listings/:id/rental-terms') async read(@Req() req:FastifyRequest,@Param('id') id:string){z.uuid().parse(id);const actor=await this.identity.actor(req,['owner','agent','agency_manager','admin']);return transaction(actor,async c=>data(await view(c,await scoped(c,actor,id))));}
 @Patch('ops/listings/:id/rental-terms') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){z.uuid().parse(id);const actor=await this.identity.actor(req,['owner','agent','agency_manager','admin']),input=rentalTermsUpdate.parse(body);return transaction(actor,c=>idempotent(c,actor,req,input,async()=>{
  const row=await scoped(c,actor,id,true);if(row.version!==input.version||row.unit_version!==input.unitVersion)fail(409,'Rental or unit changed. Reload before editing.','RENTAL_CHANGED');if(!['draft','rejected'].includes(row.status))fail(409,'Rental terms can be edited only before publication review.','INVALID_RENTAL_STATE');let unitId=row.unit_id;
  if(input.mode==='shared'){
   if(row.segment!=='residential')fail(400,'Shared-room scope requires a residential rental.');
   const parent=row.unit_kind==='property'?row:(await c.query('SELECT *,area::text unit_area FROM units WHERE id=$1 FOR UPDATE',[row.parent_unit_id])).rows[0];if(!parent)fail(404,'Room parent is unavailable');if(Number(input.room!.area)>Number(parent.unit_area))fail(400,'The room area exceeds the parent property area.','ROOM_AREA_EXCEEDED');
   if(row.unit_kind==='property'){
    if(!actor.roles.some(role=>['agent','agency_manager','admin'].includes(role)))fail(403,'New room units require an authorized property team.');if(row.unit_organization!==row.organization_id)fail(409,'A room for a different organization requires an ownership review.','ROOM_ORGANIZATION_REVIEW');
    const room=(await c.query("INSERT INTO units(community_id,organization_id,area,beds,living_rooms,baths,orientation,floor,elevator,parent_unit_id,unit_kind,room_label) SELECT community_id,organization_id,$2,1,0,0,orientation,floor,elevator,id,'room',$3 FROM units WHERE id=$1 RETURNING id",[row.unit_id,input.room!.area,input.room!.label])).rows[0];unitId=room.id;await c.query('UPDATE units SET version=version+1 WHERE id=$1',[row.unit_id]);await event(c,actor,unitId,'inventory.room_created',{parentUnitId:row.unit_id,parentVersion:input.unitVersion+1});
   }else{await c.query('UPDATE units SET area=$2,room_label=$3,version=version+1 WHERE id=$1',[unitId,input.room!.area,input.room!.label]);await event(c,actor,unitId,'inventory.room_updated',{version:input.unitVersion+1});}
  }else if(row.unit_kind==='room')fail(409,'A room listing cannot become an entire-property listing. Create a separate property listing.','ROOM_SCOPE_FIXED');
  await c.query('UPDATE listings SET unit_id=$2,rent_period=$3,available_from=$4,version=version+1,updated_at=now() WHERE id=$1',[id,unitId,input.billingPeriod,input.moveInDate]);
  await c.query('INSERT INTO rental_terms(listing_id,rental_mode,minimum_months,deposit_amount,currency,billing_period,utilities,move_in_date,room_attributes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(listing_id) DO UPDATE SET rental_mode=EXCLUDED.rental_mode,minimum_months=EXCLUDED.minimum_months,deposit_amount=EXCLUDED.deposit_amount,currency=EXCLUDED.currency,billing_period=EXCLUDED.billing_period,utilities=EXCLUDED.utilities,move_in_date=EXCLUDED.move_in_date,room_attributes=EXCLUDED.room_attributes,version=rental_terms.version+1',[id,input.mode,input.minimumMonths,input.depositAmount,row.currency,input.billingPeriod,input.utilities,input.moveInDate,input.roomAttributes]);await event(c,actor,id,'listing.rental_terms_updated',{version:input.version+1,unitId,mode:input.mode});return data(await view(c,await scoped(c,actor,id)));
 }));}
}
