import {Controller,Get,Post,Patch,Delete,Req,Param,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {propertyMediaMetadata} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const kind=z.enum(['photo','floor_plan','panorama','video']);
const metadata=propertyMediaMetadata;
type Resource='listings'|'developments';
function resource(value:string):Resource{if(value!=='listings'&&value!=='developments')fail(404,'Property media not found');return value as Resource;}
function parentColumn(type:Resource){return type==='listings'?'listing_id':'development_id';}
function parent(row:any):{type:Resource;id:string}{return row.listing_id?{type:'listings',id:row.listing_id}:{type:'developments',id:row.development_id};}
async function editable(c:pg.PoolClient,a:Actor,id:string,type:Resource){
 const record=(await c.query(type==='listings'?'SELECT id,title,owner_id,organization_id,agent_id,version,status FROM listings WHERE id=$1 FOR UPDATE':'SELECT id,name AS title,organization_id,version,status FROM developments WHERE id=$1 FOR UPDATE',[id])).rows[0];
 const allowed=type==='listings'?['agent','agency_manager']:['developer'];
 if(!record||!(a.roles.some(r=>['admin','moderator'].includes(r))||record.owner_id===a.id||record.organization_id===a.orgId&&a.roles.some(r=>allowed.includes(r))))fail(404,'Editable property not found');
 if(type==='listings'&&a.roles.includes('agent')&&!a.roles.some(r=>['admin','agency_manager'].includes(r))&&record.owner_id!==a.id&&!(await c.query('SELECT 1 FROM agents WHERE id=$1 AND user_id=$2',[record.agent_id,a.id])).rowCount)fail(404,'This property is not assigned to you');
 return record;
}
async function validateLinks(c:pg.PoolClient,id:string,type:Resource,value:z.infer<typeof metadata>,mediaKind:string){
 if(value.spatial&&mediaKind!=='floor_plan')fail(400,'Spatial floor data belongs to a floor-plan image');
 for(const room of value.spatial?.rooms||[])if(!(await c.query(`SELECT 1 FROM listing_media WHERE id=$1 AND ${parentColumn(type)}=$2 AND kind='panorama'`,[room.sceneId,id])).rowCount)fail(400,'Each mapped room must link to a panorama in this property');
 for(const target of value.hotspots)if(!(await c.query(`SELECT 1 FROM listing_media WHERE id=$1 AND ${parentColumn(type)}=$2 AND kind='panorama'`,[target.targetId,id])).rowCount)fail(400,'A tour hotspot must point to a scene in this property');
}
export async function publicRichMedia(c:pg.PoolClient,id:string,type:Resource='listings'){
 const rows=(await c.query(`SELECT m.id,m.asset_id,m.kind,m.title,m.position,m.metadata,m.floor_plan_id,a.width,a.height,a.duration FROM listing_media m JOIN media_assets a ON a.id=m.asset_id WHERE m.${parentColumn(type)}=$1 AND m.status='approved' AND a.status='approved' AND a.visibility='public' AND a.scan_at IS NOT NULL AND a.purpose=m.kind AND (m.kind<>'panorama' OR (a.width>=1024 AND a.height>0 AND abs(a.width::numeric/a.height-2)<=0.05)) AND CASE WHEN m.kind='video' THEN coalesce(a.variants->>'video','')<>'' ELSE coalesce(a.variants->>'display','')<>'' END ORDER BY m.position,m.id`,[id])).rows;
 const sceneIds=new Set(rows.filter(r=>r.kind==='panorama').map(r=>r.id));
 return rows.map(r=>({id:r.id,kind:r.kind,title:r.title,position:r.position,floorPlanId:r.floor_plan_id,url:'/api/v1/media/'+r.asset_id+(r.kind==='video'?'/video':'/view'),poster:r.kind==='video'?'/api/v1/media/'+r.asset_id+'/view':null,width:r.width,height:r.height,duration:r.duration,caption:r.metadata.caption||'',spatial:r.metadata.spatial?{...r.metadata.spatial,rooms:r.metadata.spatial.rooms.filter((room:any)=>sceneIds.has(room.sceneId))}:null,hotspots:(r.metadata.hotspots||[]).filter((h:any)=>sceneIds.has(h.targetId))}));
}
@Controller('api/v1')
export class RichMediaController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get(':resource/:id/media') async publicMedia(@Param('resource') value:string,@Param('id') id:string){const type=resource(value);return transaction(null,async c=>{const record=(await c.query(type==='listings'?'SELECT id FROM public_listings WHERE id::text=$1 OR slug=$1':"SELECT id FROM developments WHERE (id::text=$1 OR slug=$1) AND status IN ('coming_soon','on_sale','sold_out')",[id])).rows[0];if(!record)fail(404,'Published property not found');return data(await publicRichMedia(c,record.id,type));});}
 @Get('me/properties') async owned(@Req() req:FastifyRequest){const a=await this.identity.actor(req);return transaction(a,async c=>data((await c.query('SELECT id,title,slug,version,status FROM listings WHERE owner_id=$1 ORDER BY updated_at DESC',[a.id])).rows));}
 @Get('ops/:resource/:id/media') async workbench(@Req() req:FastifyRequest,@Param('resource') value:string,@Param('id') id:string){const a=await this.identity.actor(req),type=resource(value);return transaction(a,async c=>{const record=await editable(c,a,id,type);const rows=(await c.query(`SELECT m.*,a.purpose,a.width,a.height,a.duration,a.rights,a.scan_at FROM listing_media m JOIN media_assets a ON a.id=m.asset_id WHERE m.${parentColumn(type)}=$1 ORDER BY m.position,m.id`,[id])).rows;const plans=type==='developments'?(await c.query('SELECT id,name FROM floor_plans WHERE development_id=$1 ORDER BY name',[id])).rows:[];return data({listing:{id:record.id,title:record.title,version:record.version,status:record.status},media:rows,floorPlans:plans});});}
 @Post('ops/:resource/:id/media') async attach(@Req() req:FastifyRequest,@Param('resource') value:string,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),type=resource(value);const x=z.object({assetId:z.string().uuid(),kind,title:z.string().min(2).max(120),floorPlanId:z.string().uuid().optional(),position:z.number().int().min(0).max(1000).default(0),version:z.number().int(),metadata:metadata.default({hotspots:[],caption:''})}).parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const record=await editable(c,a,id,type);if(record.version!==x.version)fail(409,'Property changed. Refresh before attaching media');const asset=(await c.query("SELECT purpose FROM media_assets WHERE id=$1 AND owner_id=$2 AND status='approved' AND visibility='public' AND scan_at IS NOT NULL",[x.assetId,a.id])).rows[0];if(!asset||asset.purpose!==x.kind)fail(400,'Select an owned, scanned upload with the matching media type');if(x.floorPlanId&&(type!=='developments'||x.kind!=='floor_plan'||!(await c.query('SELECT 1 FROM floor_plans WHERE id=$1 AND development_id=$2',[x.floorPlanId,id])).rowCount))fail(400,'Choose a floor plan belonging to this development');await validateLinks(c,id,type,x.metadata,x.kind);const row=(await c.query(`INSERT INTO listing_media(${parentColumn(type)},asset_id,kind,title,position,metadata,submitted_by,floor_plan_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[id,x.assetId,x.kind,x.title,x.position,x.metadata,a.id,x.floorPlanId||null])).rows[0];await c.query(`UPDATE ${type} SET version=version+1 WHERE id=$1`,[id]);await event(c,a,id,'property.media_submitted',{mediaId:row.id});return data(row);}));}
 @Patch('ops/property-media/:id') async revise(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req);const x=z.object({title:z.string().min(2).max(120),position:z.number().int().min(0).max(1000),metadata,version:z.number().int()}).parse(body);return transaction(a,async c=>{const row=(await c.query('SELECT * FROM listing_media WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'Property media not found');const p=parent(row);await editable(c,a,p.id,p.type);if(row.version!==x.version)fail(409,'Media changed. Refresh before editing');await validateLinks(c,p.id,p.type,x.metadata,row.kind);const result=await c.query('UPDATE listing_media SET pending_title=$2,pending_position=$3,pending_metadata=$4,pending_submitted_by=$5,version=version+1 WHERE id=$1 RETURNING *',[id,x.title,x.position,x.metadata,a.id]);await event(c,a,p.id,'property.media_revision_submitted',{mediaId:id});return data(result.rows[0]);});}
 @Get('ops/property-media/reviews') async reviews(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['moderator','admin']);return transaction(a,async c=>data((await c.query("SELECT m.*,coalesce(l.title,d.name) AS property_title,a.rights,a.scan_at FROM listing_media m LEFT JOIN listings l ON l.id=m.listing_id LEFT JOIN developments d ON d.id=m.development_id JOIN media_assets a ON a.id=m.asset_id WHERE m.status='draft' OR m.pending_metadata IS NOT NULL ORDER BY m.created_at")).rows));}
 @Post('ops/property-media/:id/review') async review(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['moderator','admin']);const x=z.object({decision:z.enum(['approved','rejected']),reason:z.string().min(5).max(1000),version:z.number().int()}).parse(body);return transaction(a,async c=>{const row=(await c.query('SELECT * FROM listing_media WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'Property media not found');const p=parent(row);await editable(c,a,p.id,p.type);if(row.version!==x.version||row.status!=='draft'&&!row.pending_metadata)fail(409,'Media changed or has already been reviewed');const status=row.status==='approved'?'approved':x.decision;if(x.decision==='approved'){if((row.pending_submitted_by||row.submitted_by)===a.id)fail(403,'You cannot approve your own property media');await validateLinks(c,p.id,p.type,metadata.parse(row.pending_metadata||row.metadata),row.kind);await c.query('UPDATE listing_media SET title=coalesce(pending_title,title),position=coalesce(pending_position,position),metadata=coalesce(pending_metadata,metadata) WHERE id=$1',[id]);if(row.floor_plan_id)await c.query('UPDATE floor_plans SET photo=$2 WHERE id=$1 AND development_id=$3',[row.floor_plan_id,'/api/v1/media/'+row.asset_id+'/view',p.id]);}const result=await c.query('UPDATE listing_media SET status=$2,review_reason=$3,pending_title=NULL,pending_position=NULL,pending_metadata=NULL,pending_submitted_by=NULL,version=version+1 WHERE id=$1 RETURNING id,status,version',[id,status,x.reason]);await c.query(`UPDATE ${p.type} SET version=version+1 WHERE id=$1`,[p.id]);await event(c,a,p.id,'property.media_reviewed',{mediaId:id,decision:x.decision});return data(result.rows[0]);});}
 @Delete('ops/property-media/:id') async remove(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req),x=z.object({version:z.number().int()}).parse(body);return transaction(a,async c=>{const row=(await c.query('SELECT * FROM listing_media WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)fail(404,'Property media not found');const p=parent(row);await editable(c,a,p.id,p.type);if(row.version!==x.version)fail(409,'Media changed. Refresh before removing');if(row.floor_plan_id)await c.query('UPDATE floor_plans SET photo=NULL WHERE id=$1 AND photo=$2',[row.floor_plan_id,'/api/v1/media/'+row.asset_id+'/view']);await c.query('DELETE FROM listing_media WHERE id=$1',[id]);await c.query(`UPDATE ${p.type} SET version=version+1 WHERE id=$1`,[p.id]);await event(c,a,p.id,'property.media_removed',{mediaId:id});return data({removed:true});});}
}
