import {checkCredentialPolicy} from '../geography/market-policy.js';
import {Controller,Get,Post,Patch,Param,Query,Req,Body,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {randomUUID} from 'node:crypto';
import {agentProfileCreate,agentProfileUpdate,agentCredentialSubmit,agentCredentialReview,agentCredentialFilters} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const credentialFields=`c.id,c.agent_id AS "agentId",c.city,c.holder_name AS "holderName",c.registration_reference AS "registrationReference",c.issuer,c.expires_on::text AS "expiresOn",c.document_id AS "documentId",c.status,c.version,c.created_at AS "createdAt",c.reviewed_at AS "reviewedAt"`;
async function profiles(c:pg.PoolClient,a:Actor){return (await c.query(`SELECT a.id,a.name,a.slug,a.biography,a.languages,a.districts,a.city,a.public_email AS "publicEmail",a.version,a.identity_version AS "identityVersion",coalesce(b.status,'unverified') AS "credentialStatus",b.expires_on::text AS "credentialExpiresOn",ARRAY(SELECT d.id FROM districts d JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=a.city AND d.name=ANY(a.districts)) AS "districtIds" FROM agents a LEFT JOIN LATERAL agent_credential_badge(a.id,a.city) b ON true WHERE a.user_id=$1 AND a.organization_id=$2 ORDER BY a.name`,[a.id,a.orgId])).rows;}
async function own(c:pg.PoolClient,a:Actor,id:string){const p=(await c.query('SELECT * FROM agents WHERE id::text=$1 AND user_id=$2 AND organization_id=$3 FOR UPDATE',[id,a.id,a.orgId])).rows[0];if(!p)fail(404,'Agent profile not found');return p;}
async function market(c:pg.PoolClient,city:string,ids:string[]){const r=await c.query(`SELECT d.name FROM districts d JOIN cities ci ON ci.id=d.city_id WHERE ci.slug=$1 AND ci.status='active' AND d.id=ANY($2::uuid[]) AND d.status='active'`,[city,ids]);if(r.rowCount!==new Set(ids).size)fail(400,'Select active districts in this city');return r.rows.map(r=>r.name);}
export async function canReadAgentCredentialDocument(c:pg.PoolClient,a:Actor,id:string,ownerId:string){return Boolean((await c.query(`SELECT 1 FROM agent_credential_review_grants g JOIN agent_credentials cr ON cr.id=g.credential_id JOIN agents agent ON agent.id=cr.agent_id WHERE g.reviewer_id=$1 AND g.expires_at>now() AND cr.status IN('submitted','approved') AND cr.document_id::text=$2 AND agent.user_id=$3 AND agent.user_id<>$1`,[a.id,id,ownerId])).rowCount);}
@Controller('api/v1')
export class AgentCredentialsController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('me/agent-profiles') async read(@Req() req:FastifyRequest){const a=await this.identity.actor(req,['agent','agency_manager']);return transaction(a,async c=>data(await profiles(c,a)));}
 @Post('me/agent-profiles') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager']),x=agentProfileCreate.parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{if(!a.orgId)fail(403,'An agency membership is required');if((await profiles(c,a)).length)fail(409,'Edit your existing profile');const districts=await market(c,x.city,x.districtIds),id=randomUUID();await c.query(`INSERT INTO agents(id,user_id,organization_id,name,slug,biography,languages,districts,city,public_email) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,a.id,a.orgId,x.name,'agent-'+id,x.biography,x.languages,districts,x.city,x.contactConsent?x.publicEmail:null]);await event(c,a,id,'agent.profile_created');return data((await profiles(c,a)).find(p=>p.id===id));}));}
 @Patch('me/agent-profiles/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager']),x=agentProfileUpdate.parse(body);return transaction(a,async c=>{const p=await own(c,a,id);if(p.version!==x.version)fail(409,'Profile changed; refresh before editing');const districts=await market(c,x.city,x.districtIds);await c.query(`UPDATE agents SET name=$2,biography=$3,languages=$4,districts=$5,city=$6,public_email=$7,version=version+1 WHERE id=$1`,[p.id,x.name,x.biography,x.languages,districts,x.city,x.contactConsent?x.publicEmail:null]);await event(c,a,p.id,'agent.profile_updated');return data((await profiles(c,a)).find(row=>row.id===p.id));});}
 @Get('me/agent-profiles/:id/credentials') async credentials(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['agent','agency_manager']);return transaction(a,async c=>{await own(c,a,id);return data((await c.query(`SELECT ${credentialFields} FROM agent_credentials c WHERE c.agent_id=$1 ORDER BY c.created_at DESC`,[id])).rows);});}
 @Post('me/agent-profiles/:id/credentials') async submit(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['agent','agency_manager']),x=agentCredentialSubmit.parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const p=await own(c,a,id);if(p.version!==x.profileVersion)fail(409,'Profile changed; refresh before submitting');if(!p.city)fail(400,'Save the public profile city first');const today=(await c.query("SELECT (now() AT TIME ZONE timezone)::date::text AS today FROM cities WHERE slug=$1 AND status='active'",[p.city])).rows[0]?.today;if(!today||x.expiresOn<today)fail(400,'The credential must be unexpired');const marketVersion=await checkCredentialPolicy(c,p.city,x);const r=await c.query(`INSERT INTO agent_credentials(agent_id,city,holder_name,registration_reference,issuer,expires_on,document_id,profile_identity_version,market_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[p.id,p.city,x.holderName,x.registrationReference,x.issuer,x.expiresOn,x.documentId,p.identity_version,marketVersion]);await event(c,a,r.rows[0].id,'agent.credential_submitted');return data((await c.query(`SELECT ${credentialFields} FROM agent_credentials c WHERE c.id=$1`,[r.rows[0].id])).rows[0]);}));}
 @Get('ops/agent-credentials') async queue(@Req() req:FastifyRequest,@Query() input:unknown){const a=await this.identity.actor(req,['moderator','admin']),x=agentCredentialFilters.parse(input);return transaction(a,async c=>{const rows=(await c.query(`SELECT ${credentialFields},agent.name AS "agentName",o.name AS "organizationName",agent.user_id<>$1 AS "canReview" FROM agent_credentials c JOIN agents agent ON agent.id=c.agent_id JOIN organizations o ON o.id=agent.organization_id WHERE c.status=$2 ORDER BY c.created_at,c.id LIMIT $3 OFFSET $4`,[a.id,x.status,x.limit,(x.page-1)*x.limit])).rows;for(const row of rows)if(row.canReview&&['submitted','approved'].includes(row.status)){const grant=await c.query(`INSERT INTO agent_credential_review_grants(reviewer_id,credential_id,expires_at) VALUES($1,$2,now()+interval '30 minutes') ON CONFLICT(reviewer_id,credential_id) DO UPDATE SET expires_at=excluded.expires_at WHERE agent_credential_review_grants.expires_at<now() RETURNING credential_id`,[a.id,row.id]);if(grant.rowCount)await event(c,a,row.id,'agent.credential_evidence_granted');}return data(rows,{page:x.page,limit:x.limit});});}
 @Patch('ops/agent-credentials/:id') async review(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['moderator','admin']),x=agentCredentialReview.parse(body);return transaction(a,async c=>{const cr=(await c.query('SELECT c.*,agent.user_id FROM agent_credentials c JOIN agents agent ON agent.id=c.agent_id WHERE c.id::text=$1 FOR UPDATE OF c,agent',[id])).rows[0];if(!cr)fail(404,'Credential not found');if(cr.user_id===a.id)fail(403,'An independent reviewer must decide');if(cr.version!==x.version)fail(409,'Credential changed; refresh before reviewing');if(!(cr.status==='submitted'&&['approved','rejected'].includes(x.decision)||cr.status==='approved'&&x.decision==='revoked'))fail(409,'Invalid credential transition');if(x.decision==='approved'&&!x.verified)fail(400,'Confirm review of the actual private credential');if(x.decision==='approved'){await c.query(`UPDATE agent_credentials SET status='superseded',version=version+1,reviewed_by=$2,review_note='Replaced by independently approved credential',reviewed_at=now() WHERE agent_id=$1 AND status='approved'`,[cr.agent_id,a.id]);}await c.query(`UPDATE agent_credentials SET status=$2,version=version+1,reviewed_by=$3,review_note=$4,reviewed_at=now() WHERE id=$1`,[cr.id,x.decision,a.id,x.reason]);if(['approved','revoked'].includes(x.decision))await c.query('UPDATE agents SET verified_until=$2,version=version+1 WHERE id=$1',[cr.agent_id,x.decision==='approved'?cr.expires_on:null]);await c.query('SELECT revoke_agent_credential_grants($1)',[cr.id]);await event(c,a,cr.id,'agent.credential_'+x.decision);return data((await c.query(`SELECT ${credentialFields} FROM agent_credentials c WHERE c.id=$1`,[cr.id])).rows[0]);});}
}
