import type pg from 'pg';
import {agentDirectoryFilters} from '@haven/contracts';
import {data,fail,transaction} from '../platform/core.js';
import {publicAgentInventory} from '../inventory/agent-inventory.js';
const fields=`a.id,a.name,a.slug,a.biography,a.languages,a.districts,a.version,$1::text AS city,CASE WHEN b.status='approved' THEN b.expires_on ELSE NULL END AS "verifiedUntil",b.status AS "credentialStatus",a.photo,a.public_email AS "publicEmail",coalesce(a.verified_until>=(now() AT TIME ZONE ci.timezone)::date,false) AS "canContact"`;
const source=`FROM agents a JOIN cities ci ON ci.slug=$1 AND ci.status='active' JOIN LATERAL agent_credential_badge(a.id,$1) b ON true WHERE (a.city IS NULL OR a.city=$1) AND EXISTS(SELECT 1 FROM districts d WHERE d.city_id=ci.id AND d.status='active' AND d.name=ANY(a.districts))`;
export async function agentDirectory(input:unknown){const x=agentDirectoryFilters.parse(input),pattern='%'+x.q.replace(/[\\%_]/g,'\\$&')+'%';return transaction(null,async c=>{const predicate=`${source} AND a.name ILIKE $2 AND ($3::uuid IS NULL OR EXISTS(SELECT 1 FROM districts d WHERE d.id=$3 AND d.city_id=ci.id AND d.status='active' AND d.name=ANY(a.districts))) AND ($4::text IS NULL OR EXISTS(SELECT 1 FROM unnest(a.languages) language WHERE lower(language)=lower($4)))`,values=[x.city,pattern,x.districtId??null,x.language??null],total=(await c.query(`SELECT count(*)::int total ${predicate}`,values)).rows[0].total,rows=(await c.query(`SELECT ${fields} ${predicate} ORDER BY a.name,a.id LIMIT $5 OFFSET $6`,[...values,x.limit,(x.page-1)*x.limit])).rows;return data(rows,{total,page:x.page,limit:x.limit});});}
export async function publicAgentProfile(c:pg.PoolClient,id:string,city:string){const p=(await c.query(`SELECT ${fields} ${source} AND (a.id::text=$2 OR a.slug=$2)`,[city,id])).rows[0];if(!p)fail(404,'Agent not found');return p;}
export async function agentDetail(id:string,city:string){return transaction(null,async c=>{const p=await publicAgentProfile(c,id,city),inventory=await publicAgentInventory(c,p.id,city,1,1);return data({...p,statistics:{publishedListings:inventory.total,completedViewings:null,activityVerified:false,asOf:new Date().toISOString(),definition:'Published assigned offers with current availability and agent eligibility. Completed viewings, ratings and sales performance are unavailable without approved event sources.'}});});}
export async function publicAgentDestination(c:pg.PoolClient,id:string,expectedVersion:number|undefined,city:string|undefined){if(expectedVersion===undefined||!city)fail(400,'Choose a current agent profile before contacting');const p=(await c.query(`SELECT a.id AS agent_id,a.organization_id,a.version FROM agents a JOIN cities ci ON ci.slug=$3 AND ci.status='active' JOIN profiles person ON person.id=a.user_id AND person.state='active' WHERE a.id=$1 AND a.version=$2 AND a.verified_until>=(now() AT TIME ZONE ci.timezone)::date AND (a.city IS NULL OR a.city=ci.slug) AND EXISTS(SELECT 1 FROM districts d WHERE d.city_id=ci.id AND d.status='active' AND d.name=ANY(a.districts)) AND EXISTS(SELECT 1 FROM memberships m WHERE m.user_id=a.user_id AND m.organization_id=a.organization_id AND m.status='active' AND m.role IN('agent','agency_manager')) FOR SHARE OF a`,[id,expectedVersion,city])).rows[0];if(!p)fail(409,'Agent profile changed or contact is unavailable; refresh before sending');return p;}
