import {Controller,Get,Post,Patch,Param,Req,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {event} from '@haven/database';
import {quoteCreate,quoteChange,quoteFilters} from '@haven/contracts';
import {admitInquiry} from '../identity/inquiry-limits.js';
import {Identity,data,fail,transaction,idempotent} from '../platform/core.js';
const projection=`SELECT q.id,q.provider_id AS "providerId",coalesce(q.provider_snapshot->>'name','Historical provider') AS "providerName",q.provider_version AS "providerVersion",q.description,q.budget::text,q.currency,q.city,q.district_id AS "districtId",q.service_category AS "serviceCategory",q.contact_name AS "contactName",q.contact_email AS "contactEmail",q.contact_phone AS "contactPhone",q.status,q.version,q.created_at AS "createdAt",q.provider_version IS NULL AS historical,(q.provider_version IS NOT NULL AND (quote_vendor(q.id) OR quote_admin())) AS "canManage",coalesce((SELECT jsonb_agg(jsonb_build_object('version',a.quote_version,'status',a.status,'note',a.note,'at',a.at) ORDER BY a.quote_version) FROM quote_activity a WHERE a.quote_id=q.id),'[]') AS activity FROM quotes q`;
async function record(c:pg.PoolClient,id:string,own=false){const r=(await c.query(projection+' WHERE q.id=$1'+(own?' AND q.user_id=actor_id()':''),[id])).rows[0];if(!r)fail(404,'Quote request not found');return r;}
@Controller('api/v1')
export class ServicesController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Post('quote-requests') async quote(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req),x=quoteCreate.parse(body);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{
 const p=(await c.query('SELECT * FROM quote_destination($1)',[x.providerId])).rows[0];if(!p)fail(404,'Provider is unavailable');if(p.version!==x.providerVersion)fail(409,'Provider changed. Refresh and try again.');if(p.city!==x.city||!p.snapshot.categories.includes(x.serviceCategory)||!p.snapshot.districtIds.includes(x.districtId))fail(400,'Select a current service and area for this provider');if(p.snapshot.currency!==x.currency)fail(400,'Use the provider city currency');
 await admitInquiry(c,[{purpose:'quote-account',value:a.id,maximum:30}]);
 const r=(await c.query(`INSERT INTO quotes(provider_id,user_id,organization_id,description,budget,provider_version,assigned_vendor_id,city,district_id,service_category,currency,contact_name,contact_email,contact_phone,consent_at,policy_version,provider_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,now(),$15,$16) RETURNING id`,[x.providerId,a.id,p.organization_id,x.description,x.budget,p.version,p.recipient,x.city,x.districtId,x.serviceCategory,x.currency,x.contactName,x.contactEmail,x.contactPhone,x.policyVersion,p.snapshot])).rows[0];await c.query("INSERT INTO quote_activity(quote_id,quote_version,status,note,actor_id) VALUES($1,1,'requested','Nonbinding request submitted to the selected provider.',$2)",[r.id,a.id]);await event(c,a,r.id,'quote.requested',{providerId:x.providerId,providerVersion:p.version});return data(await record(c,r.id,true));}));}
 @Get('me/quotes') async own(@Req() req:FastifyRequest,@Query() input:unknown={}){return this.list(req,quoteFilters.parse(input),true);}
 @Get('ops/quotes') async quotes(@Req() req:FastifyRequest,@Query() input:unknown={}){return this.list(req,quoteFilters.parse(input),false);}
 private async list(req:FastifyRequest,query:unknown,own:boolean){const a=await this.identity.actor(req,own?[]:['vendor','admin']),x=quoteFilters.parse(query);return transaction(a,async c=>data((await c.query(projection+` WHERE ${own?'q.user_id=actor_id()':'(quote_vendor(q.id) OR quote_admin())'} AND ($1::text IS NULL OR q.status=$1) ORDER BY q.created_at DESC,q.id LIMIT 20 OFFSET $2`,[x.status||null,(x.page-1)*20])).rows,{page:x.page,limit:20}));}
 @Get('me/quotes/:id') async ownDetail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req);return transaction(a,async c=>data(await record(c,z.uuid().parse(id),true)));}
 @Get('ops/quotes/:id') async detail(@Req() req:FastifyRequest,@Param('id') id:string){const a=await this.identity.actor(req,['vendor','admin']);return transaction(a,async c=>{const r=await record(c,z.uuid().parse(id));if(!r.canManage)fail(404,'Quote request not found');return data(r);});}
 @Patch('ops/quotes/:id') async changeQuote(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['vendor','admin']),x=quoteChange.parse(body);z.uuid().parse(id);return transaction(a,async c=>idempotent(c,a,req,x,async()=>{const r=(await c.query('SELECT id,status,version,provider_version FROM quotes WHERE id=$1 AND (quote_vendor(id) OR quote_admin()) FOR UPDATE',[id])).rows[0];if(!r)fail(404,'Quote request not found');if(r.provider_version===null)fail(409,'Historical requests do not have a verified recipient');if(r.version!==x.version)fail(409,'Quote changed. Refresh before updating');const transitions:Record<string,string[]>={requested:['assigned','contacted','closed'],assigned:['contacted','closed'],contacted:['quoted','closed'],quoted:['closed'],closed:[]};if(!transitions[r.status]?.includes(x.status))fail(409,'Invalid quote transition');await c.query('UPDATE quotes SET status=$2,version=version+1 WHERE id=$1',[id,x.status]);await c.query('INSERT INTO quote_activity(quote_id,quote_version,status,note,actor_id) VALUES($1,$2,$3,$4,$5)',[id,r.version+1,x.status,x.note,a.id]);await event(c,a,id,'quote.'+x.status,{version:r.version+1});return data(await record(c,id));}));}
}
