import {Controller,Get,Post,Patch,Param,Req,Body,Query,Inject} from '@nestjs/common';
import type {FastifyRequest} from 'fastify';
import type pg from 'pg';
import {z} from 'zod';
import {providerCreate,providerUpdate,providerVersion,providerReview,providerFilters,providerReviewFilters,providerCategory,providerPage} from '@haven/contracts';
import {event,type Actor} from '@haven/database';
import {Identity,transaction,data,fail,idempotent,env} from '../platform/core.js';
import {providerAreas} from '../geography/provider-areas.js';
import {providerPhoto} from '../inventory/provider-portfolio.js';
async function vendor(c:pg.PoolClient,a:Actor){if(!a.orgId||!(await c.query("SELECT 1 FROM memberships m JOIN profiles p ON p.id=m.user_id JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 AND m.organization_id=$2 AND m.role='vendor' AND m.status='active' AND p.state='active' AND o.type='vendor' FOR SHARE OF m,p,o",[a.id,a.orgId])).rowCount)fail(403,'An active vendor membership is required');}
async function reviewer(c:pg.PoolClient){if(!(await c.query('SELECT provider_reviewer() valid')).rows[0].valid)fail(403,'Actual reviewer membership is required');}
async function own(c:pg.PoolClient,a:Actor,id:string){z.uuid().parse(id);await vendor(c,a);const row=(await c.query('SELECT * FROM providers WHERE id=$1 AND owner_id=$2 AND organization_id=$3 AND provider_owned(id) FOR UPDATE',[id,a.id,a.orgId])).rows[0];if(!row)fail(404,'Owned provider profile not found');return row;}
const select=`p.id,p.slug,p.name,p.description,p.city,p.categories,p.districts,p.district_ids AS "districtIds",p.status,p.version,p.review_note AS "reviewNote",p.provenance,coalesce((SELECT jsonb_agg(jsonb_build_object('assetId',pm.asset_id,'version',pm.asset_version,'alt',pm.alt,'caption',pm.caption,'rights',pm.rights) ORDER BY pm.position) FROM provider_portfolio pm WHERE pm.provider_id=p.id),'[]') portfolio`;
function publicLink(row:any){return {...row,publicUrl:row.status==='approved'&&row.city?env.PUBLIC_WEB_URL+'/'+row.city+'/renovation/'+row.slug:null};}
async function profile(c:pg.PoolClient,id:string){return publicLink((await c.query(`SELECT ${select} FROM providers p WHERE p.id=$1`,[id])).rows[0]);}
async function portfolio(c:pg.PoolClient,a:Actor,id:string,items:ReturnType<typeof providerCreate.parse>['portfolio']){if(new Set(items.map(i=>i.assetId)).size!==items.length)fail(400,'Choose distinct portfolio photos');for(const item of [...items].sort((l,r)=>l.assetId.localeCompare(r.assetId)))await providerPhoto(c,a.id,item.assetId,item.version);await c.query('DELETE FROM provider_portfolio WHERE provider_id=$1',[id]);for(const [position,item] of items.entries())await c.query('INSERT INTO provider_portfolio(provider_id,asset_id,asset_version,position,alt,caption,rights) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,item.assetId,item.version,position,item.alt,item.caption,item.rights]);}
export async function publicProviders(input:ReturnType<typeof providerFilters.parse>){return transaction(null,async c=>{if(input.districtId)await providerAreas(c,input.city,[input.districtId]);const params=[input.city,input.category??null,'%'+input.text.replace(/[\\%_]/g,'\\$&')+'%',input.districtId??null],where=`city=$1 AND ($2::text IS NULL OR $2=ANY(categories)) AND (name ILIKE $3 OR description ILIKE $3) AND ($4::uuid IS NULL OR $4=ANY(p."districtIds"))`,total=Number((await c.query(`SELECT count(*) FROM public_providers p WHERE ${where}`,params)).rows[0].count);return data((await c.query(`SELECT * FROM public_providers p WHERE ${where} ORDER BY name,id LIMIT $5 OFFSET $6`,[...params,input.limit,(input.page-1)*input.limit])).rows,{total,page:input.page,limit:input.limit});});}
export async function publicProvider(id:string,city?:string){return transaction(null,async c=>{const r=(await c.query('SELECT * FROM public_providers WHERE (id::text=$1 OR slug=$1) AND ($2::text IS NULL OR city=$2)',[id,city??null])).rows[0];if(!r)fail(404,'Provider is unavailable');return data(r);});}
export async function providerDestination(c:pg.PoolClient,id:string,version?:number,city?:string){const row=(await c.query('SELECT * FROM published_provider_destination($1)',[id])).rows[0];if(row&&version!==undefined&&row.version!==version)fail(409,'Provider changed. Refresh and try again.');if(row&&city&&row.city!==city)fail(400,'Select a provider in this city');return row;}
@Controller('api/v1')
export class ProviderCatalogController{
 constructor(@Inject(Identity) private readonly identity:Identity){}
 @Get('renovation/categories') categories(){return data(providerCategory.options);}
 @Get('me/providers') async list(@Req() req:FastifyRequest,@Query() input:unknown={}){const a=await this.identity.actor(req,['vendor']),x=providerPage.parse(input);return transaction(a,async c=>{await vendor(c,a);return data((await c.query(`SELECT ${select} FROM providers p WHERE p.owner_id=$1 AND p.organization_id=$2 ORDER BY p.name,p.id LIMIT 20 OFFSET $3`,[a.id,a.orgId,(x.page-1)*20])).rows.map(publicLink));});}
 @Post('me/providers') async create(@Req() req:FastifyRequest,@Body() body:unknown){const a=await this.identity.actor(req,['vendor']),x=providerCreate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{await vendor(c,a);const areas=await providerAreas(c,x.city,x.districtIds),id=crypto.randomUUID();await c.query("INSERT INTO providers(id,organization_id,owner_id,slug,name,description,categories,districts,photos,city,district_ids,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'{}',$9,$10,'native')",[id,a.orgId,a.id,'provider-'+id,x.name,x.description,x.categories,areas.map(d=>d.name),x.city,x.districtIds]);await portfolio(c,a,id,x.portfolio);await event(c,a,id,'provider.created');return data(await profile(c,id));}));}
 @Patch('me/providers/:id') async update(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['vendor']),x=providerUpdate.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const p=await own(c,a,id);if(p.version!==x.version)fail(409,'Provider changed; refresh before editing');if(p.status==='submitted')fail(409,'Withdraw the submitted profile before editing');const areas=await providerAreas(c,x.city,x.districtIds);await c.query("UPDATE providers SET name=$2,description=$3,categories=$4,districts=$5,city=$6,district_ids=$7,status='draft',version=version+1,provenance='native',reviewed_by=NULL,reviewed_at=NULL,review_note=NULL WHERE id=$1",[id,x.name,x.description,x.categories,areas.map(d=>d.name),x.city,x.districtIds]);await portfolio(c,a,id,x.portfolio);await event(c,a,id,'provider.updated');return data(await profile(c,id));}));}
 @Post('me/providers/:id/submit') async submit(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['vendor']),x=providerVersion.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const p=await own(c,a,id);if(p.version!==x.version)fail(409,'Provider changed; refresh before submitting');if(p.status!=='draft')fail(409,'Only a draft can be submitted');const items=(await profile(c,id)).portfolio;if(!items.length)fail(400,'Add a scanned portfolio photo and sharing rights before submitting');for(const item of items)await providerPhoto(c,a.id,item.assetId,item.version);await c.query("UPDATE providers SET status='submitted',version=version+1 WHERE id=$1",[id]);await event(c,a,id,'provider.submitted');return data(await profile(c,id));}));}
 @Post('me/providers/:id/withdraw') async withdraw(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['vendor']),x=providerVersion.parse(body);return transaction(a,c=>idempotent(c,a,req,x,async()=>{const p=await own(c,a,id);if(p.version!==x.version||p.status!=='submitted')fail(409,'Only the current submitted profile can be withdrawn');await c.query("UPDATE providers SET status='draft',version=version+1 WHERE id=$1",[id]);await event(c,a,id,'provider.withdrawn');return data(await profile(c,id));}));}
 @Get('ops/provider-reviews') async queue(@Req() req:FastifyRequest,@Query() input:unknown){const a=await this.identity.actor(req,['moderator','admin']),x=providerReviewFilters.parse(input);return transaction(a,async c=>{await reviewer(c);return data((await c.query(`SELECT ${select},p.owner_id<>$1 AS "canReview",o.name AS "organizationName" FROM providers p JOIN organizations o ON o.id=p.organization_id WHERE p.status=$2 AND p.owner_id IS NOT NULL ORDER BY p.name,p.id LIMIT 20 OFFSET $3`,[a.id,x.status,(x.page-1)*20])).rows.map(publicLink));});}
 @Patch('ops/provider-reviews/:id') async review(@Req() req:FastifyRequest,@Param('id') id:string,@Body() body:unknown){const a=await this.identity.actor(req,['moderator','admin']),x=providerReview.parse(body);z.uuid().parse(id);return transaction(a,c=>idempotent(c,a,req,x,async()=>{await reviewer(c);const p=(await c.query('SELECT * FROM providers WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p)fail(404,'Provider not found');if(!p.owner_id||p.owner_id===a.id)fail(403,'An independent reviewer must decide');if(p.version!==x.version)fail(409,'Provider changed; refresh before reviewing');if(!(p.status==='submitted'&&['approved','rejected'].includes(x.decision)||p.status==='approved'&&x.decision==='revoked'))fail(409,'Invalid provider decision');if(x.decision==='approved'){if(!x.verified)fail(400,'Confirm review of the actual profile, service areas and portfolio rights');const items=(await profile(c,id)).portfolio;if(!items.length)fail(400,'Portfolio is required');for(const item of items)await providerPhoto(c,p.owner_id,item.assetId,item.version);}await c.query("UPDATE providers SET status=$2,version=version+1,provenance='independent_review',reviewed_by=$3,reviewed_at=now(),review_note=$4 WHERE id=$1",[id,x.decision,a.id,x.reason]);await event(c,a,id,'provider.'+x.decision);return data(await profile(c,id));}));}
}
