import fs from 'node:fs';
import path from 'node:path';
import {createCipheriv,createDecipheriv,randomBytes,publicEncrypt,privateDecrypt,constants,createHash,createPublicKey,createPrivateKey,sign,verify} from 'node:crypto';
import {pipeline} from 'node:stream/promises';
const algorithm='aes-256-gcm';
function isolatedDestination(source,destination){source=path.resolve(source);destination=path.resolve(destination);if(destination===source||destination.startsWith(source+path.sep)||source.startsWith(destination+path.sep))throw Error('RECOVERY_DIRECTORIES_MUST_BE_SEPARATE');if(!fs.statSync(source).isDirectory())throw Error('RECOVERY_SOURCE_IS_NOT_DIRECTORY');}
export function safeRelative(name){if(typeof name!=='string'||!name||name.includes('\\')||name.startsWith('/')||name.split('/').some(p=>!p||p==='.'||p==='..'))throw Error('UNSAFE_RECOVERY_PATH');return name;}
export async function checksum(file){const h=createHash('sha256');for await(const chunk of fs.createReadStream(file))h.update(chunk);return h.digest('hex');}
function cipherJson(value,key){const iv=randomBytes(12),c=createCipheriv(algorithm,key,iv),ciphertext=Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]);return {iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')};}
function decipherJson(value,key){const d=createDecipheriv(algorithm,key,Buffer.from(value.iv,'base64'));d.setAuthTag(Buffer.from(value.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(value.ciphertext,'base64')),d.final()]).toString('utf8'));}
export async function encryptSnapshot(source,destination,publicKeyFile,metadata,signingPrivateKeyFile){isolatedDestination(source,destination);if(fs.existsSync(destination))throw Error('ENCRYPTION_DESTINATION_EXISTS');const publicKey=createPublicKey(fs.readFileSync(publicKeyFile));if(publicKey.asymmetricKeyType!=='rsa'||publicKey.asymmetricKeyDetails.modulusLength<3072)throw Error('RECOVERY_REQUIRES_RSA_3072_OR_STRONGER');if(!signingPrivateKeyFile||fs.statSync(signingPrivateKeyFile).mode&0o077)throw Error('BACKUP_SIGNING_PRIVATE_KEY_REQUIRED');const signingKey=createPrivateKey(fs.readFileSync(signingPrivateKeyFile));if(signingKey.asymmetricKeyType!=='ed25519')throw Error('BACKUP_SIGNING_KEY_MUST_BE_ED25519');fs.mkdirSync(destination,{mode:0o700});const key=randomBytes(32),files=[];
 async function walk(folder){for(const item of fs.readdirSync(folder,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(item.isSymbolicLink())throw Error('RECOVERY_SYMLINK_REFUSED');const file=path.join(folder,item.name);if(item.isDirectory())await walk(file);else if(item.isFile()){const name=safeRelative(path.relative(source,file).split(path.sep).join('/')),iv=randomBytes(12),cipher=createCipheriv(algorithm,key,iv),encrypted=String(files.length).padStart(6,'0')+'.bin';await pipeline(fs.createReadStream(file),cipher,fs.createWriteStream(path.join(destination,encrypted),{mode:0o600,flags:'wx'}));files.push({name,encrypted,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),sha256:await checksum(file),encryptedSha256:await checksum(path.join(destination,encrypted)),bytes:fs.statSync(file).size});}else throw Error('RECOVERY_SPECIAL_FILE_REFUSED');}}
 try{await walk(source);const envelope={version:2,algorithm:'AES-256-GCM/RSA-OAEP-SHA256/Ed25519',createdAt:new Date().toISOString(),wrappedKey:publicEncrypt({key:publicKey,padding:constants.RSA_PKCS1_OAEP_PADDING,oaepHash:'sha256'},key).toString('base64'),manifest:cipherJson({metadata,files},key)};envelope.signature=sign(null,Buffer.from(JSON.stringify(envelope)),signingKey).toString('base64');fs.writeFileSync(path.join(destination,'envelope.json'),JSON.stringify(envelope)+'\n',{mode:0o600,flag:'wx'});return {fileCount:files.length,envelopeSha256:await checksum(path.join(destination,'envelope.json'))};}catch(error){fs.rmSync(destination,{recursive:true,force:true});throw error;}finally{key.fill(0);}}
export async function decryptSnapshot(source,destination,privateKeyFile,trustedSigningPublicKeyFile){isolatedDestination(source,destination);if(fs.existsSync(destination))throw Error('RESTORE_DESTINATION_EXISTS');if(fs.statSync(privateKeyFile).mode&0o077)throw Error('RECOVERY_PRIVATE_KEY_PERMISSIONS');const outer=JSON.parse(fs.readFileSync(path.join(source,'envelope.json'),'utf8'));if(outer.version!==2||outer.algorithm!=='AES-256-GCM/RSA-OAEP-SHA256/Ed25519')throw Error('UNSUPPORTED_RECOVERY_ENVELOPE');if(!trustedSigningPublicKeyFile)throw Error('TRUSTED_BACKUP_SIGNING_KEY_REQUIRED');const trustedKey=createPublicKey(fs.readFileSync(trustedSigningPublicKeyFile)),{signature,...signed}=outer;if(trustedKey.asymmetricKeyType!=='ed25519'||typeof signature!=='string'||!verify(null,Buffer.from(JSON.stringify(signed)),trustedKey,Buffer.from(signature,'base64')))throw Error('BACKUP_SIGNATURE_INVALID');const key=privateDecrypt({key:fs.readFileSync(privateKeyFile),padding:constants.RSA_PKCS1_OAEP_PADDING,oaepHash:'sha256'},Buffer.from(outer.wrappedKey,'base64'));
 try{const {metadata,files}=decipherJson(outer.manifest,key);if(!Array.isArray(files)||!files.length)throw Error('EMPTY_RECOVERY_SNAPSHOT');const names=new Set();for(const file of files){safeRelative(file.name);if(names.has(file.name)||!/^\d{6}\.bin$/.test(file.encrypted)||file.bytes<0||!Number.isSafeInteger(file.bytes))throw Error('INVALID_RECOVERY_MANIFEST');names.add(file.name);if(!fs.existsSync(path.join(source,file.encrypted)))throw Error('REQUIRED_RECOVERY_CIPHERTEXT_MISSING');if(!fs.lstatSync(path.join(source,file.encrypted)).isFile())throw Error('RECOVERY_CIPHERTEXT_NOT_REGULAR');if(await checksum(path.join(source,file.encrypted))!==file.encryptedSha256)throw Error('RECOVERY_CIPHERTEXT_MISMATCH');}for(const name of metadata.requiredFiles||[])if(!names.has(safeRelative(name)))throw Error('REQUIRED_RECOVERY_FILE_MISSING');fs.mkdirSync(destination,{recursive:true,mode:0o700});for(const file of files){const target=path.join(destination,file.name);fs.mkdirSync(path.dirname(target),{recursive:true,mode:0o700});const d=createDecipheriv(algorithm,key,Buffer.from(file.iv,'base64'));d.setAuthTag(Buffer.from(file.tag,'base64'));await pipeline(fs.createReadStream(path.join(source,file.encrypted)),d,fs.createWriteStream(target,{mode:0o600,flags:'wx'}));if(fs.statSync(target).size!==file.bytes||await checksum(target)!==file.sha256)throw Error('RECOVERY_PLAINTEXT_MISMATCH');}return {metadata,fileCount:files.length};}catch(error){fs.rmSync(destination,{recursive:true,force:true});throw error;}finally{key.fill(0);}}
