import {performance} from 'node:perf_hooks';
import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {decryptSnapshot,safeRelative} from './envelope.mjs';
const input=process.env.RECOVERY_ENCRYPTED_INPUT,privateKey=process.env.RECOVERY_PRIVATE_KEY,signPublic=process.env.RECOVERY_SIGNING_PUBLIC_KEY,reportFile=process.env.RECOVERY_REPORT_FILE;
if(!input||!privateKey||!signPublic||!reportFile)throw Error('Declare encrypted input, protected recovery private key, trusted signing public key and report path');
const started=performance.now(),startedAt=new Date().toISOString(),parent=fs.mkdtempSync(path.join(path.dirname(path.resolve(reportFile)),'.haven-restore-')),plaintext=path.join(parent,'plaintext'),prefix='haven-recovery-'+randomUUID().slice(0,8),databaseVolume=prefix+'-database',walVolume=prefix+'-wal',objectsVolume=prefix+'-objects',network=prefix+'-private',db=prefix+'-db';
function docker(args,options={}){return execFileSync('docker',args,{encoding:'utf8',stdio:[options.input===undefined?'ignore':'pipe','pipe','pipe'],...options});}
function mount(source,target,ro=true){if(source.includes(','))throw Error('RECOVERY_BIND_PATH_COMMA_REFUSED');return 'type=bind,src='+source+',dst='+target+(ro?',readonly':'');}
try{
 const restored=await decryptSnapshot(input,plaintext,privateKey,signPublic),metadata=restored.metadata,image=metadata.images?.db;if(!/^sha256:[a-f0-9]{64}$/.test(image||''))throw Error('RECOVERY_DATABASE_IMAGE_DIGEST_REQUIRED');const proof=JSON.parse(fs.readFileSync(path.join(plaintext,'database/proof.json'),'utf8'));if(!/^[A-F0-9]+\/[A-F0-9]+$/.test(proof.lsn||''))throw Error('RECOVERY_SOURCE_LSN_REQUIRED');for(const segment of metadata.walSegments||[]){if(!/^[A-F0-9]{24}$/.test(segment)||!fs.existsSync(path.join(plaintext,'database/wal',segment)))throw Error('REQUIRED_WAL_SEGMENT_MISSING');}if(!metadata.lastSegment||!metadata.walSegments.includes(metadata.lastSegment))throw Error('FINAL_REQUIRED_WAL_SEGMENT_MISSING');
 const verbose=docker(['run','--rm','--network','none','--mount',mount(path.join(plaintext,'database/base.tar'),'/backup/base.tar'),'--entrypoint','tar',image,'-tvf','/backup/base.tar']);if(verbose.split('\n').some(line=>/^[lh]/.test(line)))throw Error('RESTORE_ARCHIVE_LINK_REFUSED');const listing=docker(['run','--rm','--network','none','--mount',mount(path.join(plaintext,'database/base.tar'),'/backup/base.tar'),'--entrypoint','tar',image,'-tf','/backup/base.tar']);for(const raw of listing.split('\n').filter(Boolean)){const entry=raw.replace(/^\.\//,'').replace(/\/$/,'');if(entry)safeRelative(entry);}
 for(const name of [databaseVolume,walVolume,objectsVolume]){if(spawnSync('docker',['volume','inspect',name],{stdio:'ignore'}).status===0)throw Error('RESTORE_VOLUME_ALREADY_EXISTS');docker(['volume','create','--label','com.haven.recovery='+prefix,name]);}docker(['network','create','--internal','--label','com.haven.recovery='+prefix,network]);
 docker(['run','--rm','--network','none','--user','0:0','--mount',mount(plaintext,'/backup'),'-v',databaseVolume+':/restore','-v',walVolume+':/archive','-v',objectsVolume+':/objects','--entrypoint','sh',image,'-c','tar -xf /backup/database/base.tar -C /restore && cp -a /backup/database/wal/. /archive/ && cp -a /backup/objects/. /objects/ && chown -R postgres:postgres /restore /archive && chmod 700 /restore /archive']);
 const configuration="restore_command = 'cp /archive/%f %p'\nrecovery_target_lsn = '"+proof.lsn+"'\nrecovery_target_action = 'promote'\n";const config=path.join(parent,'restore.conf');fs.writeFileSync(config,configuration,{mode:0o600});docker(['run','--rm','--network','none','--user','0:0','--mount',mount(config,'/run/restore.conf'),'-v',databaseVolume+':/restore','--entrypoint','sh',image,'-c','cat /run/restore.conf >> /restore/postgresql.auto.conf && touch /restore/recovery.signal && chown postgres:postgres /restore/postgresql.auto.conf /restore/recovery.signal']);
 docker(['run','-d','--name',db,'--label','com.haven.recovery='+prefix,'--network',network,'--network-alias','db','-v',databaseVolume+':/var/lib/postgresql/data','-v',walVolume+':/archive:ro',image,'postgres','-c','archive_mode=off']);let ready=false;for(let i=0;i<120;i++){const r=spawnSync('docker',['exec',db,'sh','-c','psql -U postgres -d haven -Atc "SELECT NOT pg_is_in_recovery();"'],{encoding:'utf8',stdio:['ignore','pipe','ignore']});if(r.status===0&&r.stdout.trim()==='t'){ready=true;break;}const state=JSON.parse(docker(['inspect',db]))[0];if(!state.State.Running)break;await new Promise(r=>setTimeout(r,500));}if(!ready)throw Error('RESTORE_TARGET_NOT_REACHED');
 const sourceCheck=docker(['exec','-i',db,'sh','-c','psql -U postgres -d haven -At'],{input:"SELECT json_build_object('schemaMax',(SELECT max(name) FROM schema_migrations),'listings',(SELECT count(*) FROM listings),'charges',(SELECT count(*) FROM charges),'financialDigest',(SELECT encode(sha256(convert_to(coalesce(string_agg(to_jsonb(c)::text,E'\\n' ORDER BY id),''),'UTF8')),'hex') FROM charges c),'paymentsDigest',(SELECT encode(sha256(convert_to(coalesce(string_agg(to_jsonb(c)::text,E'\\n' ORDER BY id),''),'UTF8')),'hex') FROM payments c));"}),current=JSON.parse(sourceCheck);for(const key of ['schemaMax','listings','charges','financialDigest','paymentsDigest'])if(current[key]!==proof[key])throw Error('RESTORED_DATABASE_RECONCILIATION_FAILED');
 const originalIdentity=JSON.parse(fs.readFileSync(path.join(plaintext,'database/identity-proof.json'),'utf8')),restoredIdentity=JSON.parse(docker(['exec','-i',db,'sh','-c','psql -U postgres -d haven_identity -At'],{input:"SELECT json_build_object('users',(SELECT count(*) FROM user_entity),'credentials',(SELECT count(*) FROM credential),'usersDigest',(SELECT encode(sha256(convert_to(coalesce(string_agg(to_jsonb(c)::text,E'\\n' ORDER BY id),''),'UTF8')),'hex') FROM user_entity c),'credentialsDigest',(SELECT encode(sha256(convert_to(coalesce(string_agg(to_jsonb(c)::text,E'\\n' ORDER BY id),''),'UTF8')),'hex') FROM credential c));"}));if(JSON.stringify(originalIdentity)!==JSON.stringify(restoredIdentity))throw Error('RESTORED_IDENTITY_RECONCILIATION_FAILED');
 const report={label:'P',status:'database-restored',startedAt,completedAt:new Date().toISOString(),durationMs:performance.now()-started,authenticatedEnvelope:true,restoredFiles:restored.fileCount,recoveryTargetLsn:proof.lsn,walSegments:metadata.walSegments.length,reconciled:current,identityReconciled:restoredIdentity,retained:{databaseContainer:db,databaseVolume,walVolume,objectsVolume,network},applicationVerified:false,offHostEvidence:!metadata.localDrill,rpoClaim:null};fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n',{mode:0o600,flag:'wx'});console.log(JSON.stringify(report));
}catch(error){const code=error instanceof Error&&/^[A-Z_]+$/.test(error.message)?error.message:'RESTORE_UNAVAILABLE';if(!fs.existsSync(reportFile))fs.writeFileSync(reportFile,JSON.stringify({label:'P',status:'failed',code,startedAt,completedAt:new Date().toISOString(),applicationVerified:false,rpoClaim:null},null,2)+'\n',{mode:0o600,flag:'wx'});console.error(JSON.stringify({status:'failed',code}));process.exitCode=1;}finally{fs.rmSync(parent,{recursive:true,force:true});}
