import {InquirySessionsController} from './identity/inquiry-sessions.js';
import {GuestInquiriesController} from './engagement/inquiries.js';
import {AgentDashboardController} from './administration/agent-dashboard.js';
import {LeadAssignmentsController} from './engagement/lead-assignments.js';
import {AssignmentDirectoryController} from './inventory/assignments.js';
import {AgencyMembershipsController} from './identity/agency-memberships.js';
import {AgentCredentialsController} from './services/agent-credentials.js';
import {DevelopmentReviewController} from './inventory/development-review.js';
import {DevelopmentPricingController} from './inventory/development-pricing.js';
import {DevelopmentInventoryController} from './inventory/development-inventory.js';
import {DevelopmentProjectsController} from './inventory/development-projects.js';
import {NotificationsController,NotificationWorkerController} from './engagement/notifications.js';
import {SavedSearchController} from './engagement/saved-searches.js';
import {BrowsingHistoryController} from './engagement/browsing-history.js';
import 'reflect-metadata';
import {HomeDiscoveryController} from './geography/home.js';
import {Module,Catch,type ExceptionFilter,type ArgumentsHost,HttpException} from '@nestjs/common';
import {NestFactory} from '@nestjs/core';
import {FastifyAdapter,type NestFastifyApplication} from '@nestjs/platform-fastify';
import {createOpenApi} from '@haven/contracts/openapi';
import {operations} from '@haven/contracts/operations';
import {ZodError} from 'zod';
import {randomUUID} from 'node:crypto';
import type {FastifyReply,FastifyRequest} from 'fastify';
import {Identity,env} from './platform/core.js';
import {RentalTermsController} from './inventory/rental-terms.js';
import {PrivacyController} from './identity/privacy.js';
import {ProfileController} from './identity/profile.js';
import {IdentityController} from './identity/controller.js';
import {GeographyController} from './geography/administration.js';
import {DiscoveryController} from './geography/controller.js';
import {RankingsController} from './geography/rankings.js';
import {RankingBoostsController} from './administration/ranking-boosts.js';
import {DiscoveryEventsController} from './engagement/discovery-events.js';
import {SearchHistoryController} from './engagement/search-history.js';
import {EngagementController} from './engagement/controller.js';
import {DraftInventoryController} from './inventory/drafts.js';
import {InventoryController} from './inventory/controller.js';
import {ManagementController} from './management/controller.js';
import {ServicesController} from './services/controller.js';
import {AdministrationController} from './administration/controller.js';
import {MediaController} from './inventory/media.js';
import {RichMediaController} from './inventory/rich-media.js';
import {HealthController} from './platform/health.js';
import {logEvent,traceStart,traceEnd} from './platform/observability.js';
@Catch() class Errors implements ExceptionFilter{catch(error:any,host:ArgumentsHost){const response=host.switchToHttp().getResponse<FastifyReply>();const req=host.switchToHttp().getRequest<FastifyRequest>();let status=500,code='INTERNAL_ERROR',message='Something went wrong. Please try again.',fieldErrors;if(error instanceof ZodError){status=400;code='VALIDATION_ERROR';message='Please check the highlighted fields';fieldErrors=error.flatten().fieldErrors;}else if(error instanceof HttpException||(typeof error?.getStatus==='function'&&typeof error?.getResponse==='function')){status=error.getStatus();const body=error.getResponse() as any;code=body.code||({400:'MALFORMED_REQUEST',401:'AUTH_REQUIRED',403:'FORBIDDEN',404:'NOT_FOUND',413:'PAYLOAD_TOO_LARGE',415:'UNSUPPORTED_MEDIA_TYPE'} as Record<number,string>)[status]||'REQUEST_ERROR';message=body.code?body.message:'Request rejected. Check the request and try again.';}else if(error.code==='INVALID_TRANSITION'){status=409;code=error.code;message='This workflow transition is not allowed';}else if([400,413,415].includes(error.statusCode)){status=error.statusCode;code=status===413?'PAYLOAD_TOO_LARGE':status===415?'UNSUPPORTED_MEDIA_TYPE':'MALFORMED_REQUEST';message=status===413?'Upload or request is too large':status===415?'Unsupported content type':'Malformed request';}else if(['23P01','23505','40001','40P01'].includes(error.code)){status=409;code='CONFLICT';message='This record or time slot conflicts with an existing reservation. Refresh and try again.';}else if(['22P02','23514','23503'].includes(error.code)){status=400;code='INVALID_DATA';message='Invalid record, amount or related resource';}else if(error.code==='42501'){status=403;code='FORBIDDEN';message='You do not have permission for this record';}if(status===500)logEvent({event:'request.error',requestId:req.id,code:error.code||error.name});response.header('Content-Type','application/json; charset=utf-8');response.removeHeader('Content-Length');response.removeHeader('Content-Range');response.status(status).send({error:{code,message,fieldErrors,requestId:req.id}});}}
@Module({controllers:[InquirySessionsController,GuestInquiriesController,AgentDashboardController,LeadAssignmentsController,AssignmentDirectoryController,AgencyMembershipsController,AgentCredentialsController,DevelopmentReviewController,DevelopmentPricingController,DevelopmentInventoryController,DevelopmentProjectsController,RentalTermsController,PrivacyController,NotificationsController,NotificationWorkerController,SavedSearchController,BrowsingHistoryController,RankingsController,HomeDiscoveryController,RankingBoostsController,DiscoveryEventsController,SearchHistoryController,DraftInventoryController,GeographyController,RichMediaController,MediaController,HealthController,IdentityController,ProfileController,DiscoveryController,EngagementController,InventoryController,ManagementController,ServicesController,AdministrationController],providers:[Identity]}) class AppModule{}
export async function start(){const adapter=new FastifyAdapter({bodyLimit:50*1024*1024,genReqId:()=>randomUUID(),trustProxy:false,logger:false});const server=adapter.getInstance();server.addContentTypeParser(['image/jpeg','image/png','application/pdf','video/mp4','video/webm'],{parseAs:'buffer'},(_req,body,done)=>done(null,body));const rates=new Map<string,{count:number,expires:number}>();server.addHook('onRequest',async(req,reply)=>{traceStart(req);reply.header('X-Request-Id',req.id);reply.header('X-Content-Type-Options','nosniff');if(req.url.includes('/inquir')||req.url.includes('/guest-inquiries')||req.url.includes('/me')||req.url.includes('/ops')||req.url.includes('/auth')||req.url.includes('/health/metrics'))reply.header('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=req.headers.origin;if(origin!==env.PUBLIC_WEB_URL&&origin!==env.PUBLIC_OPS_URL){reply.code(403).send({error:{code:'CSRF_REJECTED',message:'Untrusted request origin',requestId:req.id}});return;}}const key=req.ip+':'+(req.method==='GET'?'read':'write');let rate=rates.get(key);if(!rate||rate.expires<Date.now()){rate={count:0,expires:Date.now()+60000};rates.set(key,rate);}if(++rate.count>(req.method==='GET'?500:100)){reply.code(429).send({error:{code:'RATE_LIMITED',message:'Too many requests. Please try again in a minute.',requestId:req.id}});}if(rates.size>10000)for(const [k,v] of rates)if(v.expires<Date.now())rates.delete(k);});
 server.addHook('onResponse',async(req,reply)=>{const route=req.routeOptions.url||'unmatched';traceEnd(req,route,reply.statusCode);if(!route.startsWith('/api/v1/health'))logEvent({event:'request.completed',requestId:req.id,method:req.method,route,status:reply.statusCode});});
 server.get('/api/v1/openapi.json',async()=>createOpenApi());
 const contractEntries=Object.entries(operations);
 server.addHook('preValidation',async(req)=>{const entry=contractEntries.find(([,op])=>op.path===req.routeOptions.url&&op.method===req.method);if(!entry)return;const op=entry[1];op.params.parse(req.params);op.query.parse(req.query);if(entry[0]!=='MediaController_content'&&!op.body.safeParse(undefined).success)op.body.parse(req.body);});
 server.addHook('onSend',async(req,reply,payload)=>{if(reply.statusCode>=300||req.method==='HEAD'||typeof payload!=='string')return payload;const entry=contractEntries.find(([,op])=>op.path===req.routeOptions.url&&op.method===req.method);if(!entry||['MediaController_view','MediaController_video','MediaController_download','IdentityController_login','IdentityController_callback'].includes(entry[0]))return payload;const result=JSON.parse(payload),parsed=entry[1].response.safeParse(result.data);if(!parsed.success){logEvent({event:'response.contract_error',requestId:req.id,operation:entry[0],fields:parsed.error.issues.map(i=>i.path.join('.'))});reply.code(500);return JSON.stringify({error:{code:'INTERNAL_ERROR',message:'Something went wrong. Please try again.',requestId:req.id}});}return JSON.stringify({...result,data:parsed.data});});
 const app=await NestFactory.create<NestFastifyApplication>(AppModule,adapter,{logger:['error','warn','log']});app.useGlobalFilters(new Errors());app.enableShutdownHooks();await app.listen(env.API_PORT,'0.0.0.0');return app;}
await start();
