import {createRequire} from 'node:module';
import {performance} from 'node:perf_hooks';
import fs from 'node:fs';
import path from 'node:path';
const require=createRequire(new URL('../packages/database/package.json',import.meta.url)),{Pool}=require('pg'),url=new URL(process.env.MIGRATION_DATABASE_URL||process.env.DATABASE_URL);
if(!/^\/haven_q07_[a-z0-9_]+$/.test(url.pathname))throw new Error('Performance fixture requires a dedicated haven_q07_* database');
const output=process.env.HAVEN_PERFORMANCE_FIXTURE_REPORT;if(!output)throw new Error('Declare HAVEN_PERFORMANCE_FIXTURE_REPORT');
const pool=new Pool({connectionString:url.toString()}),c=await pool.connect(),start=performance.now();
try{await c.query('BEGIN');await c.query("SELECT set_config('app.actor','00000000-0000-4000-8000-000000000010',true),set_config('app.admin','true',true)");const initial=Number((await c.query('SELECT count(*) FROM listings')).rows[0].count);if(initial!==102)throw new Error('Run only on the untouched 102-listing synthetic seed');const count=100000-initial;
for(let first=1;first<=count;first+=1000){await c.query(`INSERT INTO units(id,community_id,organization_id,area,beds,living_rooms,baths,orientation,floor)
SELECT (substr(md5('q07-unit-'||i),1,8)||'-'||substr(md5('q07-unit-'||i),9,4)||'-4'||substr(md5('q07-unit-'||i),14,3)||'-8'||substr(md5('q07-unit-'||i),18,3)||'-'||substr(md5('q07-unit-'||i),21,12))::uuid,u.community_id,u.organization_id,(45+(i%200))::numeric+0.50,1+(i%5),1,1+(i%3),'South',1+(i%20) FROM generate_series($1::int,$2::int) i CROSS JOIN LATERAL (SELECT * FROM units WHERE id='10000000-0000-4000-8000-000000001000') u`,[first,Math.min(count,first+999)]);if(first===1||first%10000===1)await c.query('ANALYZE units');}

await c.query(`INSERT INTO listings(id,unit_id,organization_id,owner_id,agent_id,slug,title,description,transaction,segment,currency,price,rent_period,status,features,photos,furnishing,available_from,published_at,created_at,updated_at)
SELECT (substr(md5('q07-listing-'||i),1,8)||'-'||substr(md5('q07-listing-'||i),9,4)||'-4'||substr(md5('q07-listing-'||i),14,3)||'-8'||substr(md5('q07-listing-'||i),18,3)||'-'||substr(md5('q07-listing-'||i),21,12))::uuid,(substr(md5('q07-unit-'||i),1,8)||'-'||substr(md5('q07-unit-'||i),9,4)||'-4'||substr(md5('q07-unit-'||i),14,3)||'-8'||substr(md5('q07-unit-'||i),18,3)||'-'||substr(md5('q07-unit-'||i),21,12))::uuid,l.organization_id,l.owner_id,l.agent_id,'q07-synthetic-'||i,'Q07 synthetic property '||i,'Generated development performance fixture; no actual inventory or survey facts are claimed.',CASE WHEN i%10<3 THEN 'rent' ELSE 'sale' END,'residential','CNY',CASE WHEN i%10<3 THEN (3000+i%15000)::numeric+0.75 ELSE (2500000+(i%2000)*100000)::numeric+0.75 END,CASE WHEN i%10<3 THEN 'month' ELSE NULL END,'published',l.features,l.photos,'Unfurnished','2026-10-01',TIMESTAMPTZ '2026-10-01 00:00:00+00'-(i%365)*INTERVAL '1 day',TIMESTAMPTZ '2026-10-01 00:00:00+00',TIMESTAMPTZ '2026-10-01 00:00:00+00' FROM generate_series(1,$1::int) i CROSS JOIN LATERAL (SELECT * FROM listings WHERE id='10000000-0000-4000-8000-000000002000') l`,[count]);await c.query('COMMIT');await c.query('ANALYZE');const totals=(await c.query("SELECT (SELECT count(*)::text FROM listings) AS listings,(SELECT count(*)::text FROM public_listings) AS public,(SELECT count(*)::text FROM units) AS units")).rows[0];if(totals.listings!=='100000')throw new Error('Performance fixture count mismatch');const report={label:'P',database:url.pathname.slice(1),synthetic:true,listingMoney:'PostgreSQL NUMERIC; generated in SQL without floating-point posting',durationMs:performance.now()-start,initial,inserted:count,totals};fs.mkdirSync(path.dirname(path.resolve(output)),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();await pool.end();}
