import fs from 'node:fs';
import {randomBytes} from 'node:crypto';
import {mfaFlows,mfaConfigs,staffRole} from './identity-policy.mjs';
const envPath=process.env.SETUP_ENV_FILE||'.env',generated=process.env.SETUP_GENERATED_DIR||'infra/generated',project=process.env.SETUP_PROJECT_NAME||'haven';
const secret=()=>randomBytes(24).toString('hex');
if(!fs.existsSync(envPath)){const db=secret(),app=secret(),identity=secret(),session=secret()+randomBytes(8).toString('hex'),search=secret(),s3=secret(),admin=secret(),demo=secret();
fs.writeFileSync(envPath,`COMPOSE_PROJECT_NAME=${project}\nPOSTGRES_PASSWORD=${db}\nAPP_DB_PASSWORD=${app}\nIDENTITY_DB_PASSWORD=${identity}\nDATABASE_URL=postgres://haven_app:${app}@db:5432/haven\nMIGRATION_DATABASE_URL=postgres://haven_migrate:${db}@db:5432/haven\nSESSION_KEY=${session}\nSEARCH_KEY=${search}\nS3_ACCESS_KEY=haven-local\nS3_SECRET_KEY=${s3}\nKEYCLOAK_ADMIN_PASSWORD=${admin}\nDEV_PASSWORD=${demo}\nPUBLIC_WEB_URL=http://localhost:8088\nPUBLIC_OPS_URL=http://localhost:8089\nOIDC_ISSUER=http://localhost:8090/realms/haven\nOIDC_INTERNAL_URL=http://identity:8080/realms/haven\nOIDC_CLIENT_ID=haven-web\nAPI_INTERNAL_URL=http://api:4000\nSEARCH_URL=http://search:7700\nREDIS_URL=redis://cache:6379\nS3_ENDPOINT=http://storage:8333\nNODE_ENV=development\n`,{mode:0o600});}
const env=Object.fromEntries(fs.readFileSync(envPath,'utf8').trim().split('\n').map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)];}));
fs.mkdirSync(generated,{recursive:true});
const roles=[staffRole,'consumer','owner','agent','agency_manager','developer','property_manager','tenant','vendor','moderator','support','editor','admin','finance'];
const personas=['buyer','owner','agent','manager','tenant','developer','vendor','moderator','support','admin','outsider'];
const userRoles={buyer:['consumer'],owner:['owner','consumer'],agent:['agent','consumer'],manager:['property_manager','finance'],tenant:['tenant','consumer'],developer:['developer'],vendor:['vendor'],moderator:['moderator'],support:['support'],admin:['admin','finance','editor','agency_manager'],outsider:['agent']};
const otpPath=generated+'/otp.json';
const otpSecrets=fs.existsSync(otpPath)?JSON.parse(fs.readFileSync(otpPath,'utf8')):{};
function base32(bytes){let bits=[...bytes].map(b=>b.toString(2).padStart(8,'0')).join(''),value='';for(let i=0;i<bits.length;i+=5)value+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return value;}
for(const p of personas)if(userRoles[p].some(r=>!['consumer','owner','tenant'].includes(r))){userRoles[p].push(staffRole);otpSecrets[p]||=base32(randomBytes(20));}
fs.writeFileSync(otpPath,JSON.stringify(otpSecrets),{mode:0o600});
const users=personas.map((p,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,username:p,email:`${p}@example.test`,firstName:p[0].toUpperCase()+p.slice(1),lastName:'Demo',enabled:true,emailVerified:true,credentials:[{type:'password',value:env.DEV_PASSWORD,temporary:false},...(otpSecrets[p]?[{type:'otp',userLabel:'Local authenticator',secretData:JSON.stringify({value:otpSecrets[p]}),credentialData:JSON.stringify({subType:'totp',digits:6,counter:0,period:30,algorithm:'HmacSHA1',secretEncoding:'BASE32'})}]:[])],realmRoles:userRoles[p]}));
fs.writeFileSync(generated+'/haven-realm.json',JSON.stringify({realm:'haven',browserFlow:'haven-browser',authenticationFlows:mfaFlows,authenticatorConfig:mfaConfigs,enabled:true,displayName:'Haven local development',registrationAllowed:true,resetPasswordAllowed:true,loginWithEmailAllowed:true,roles:{realm:roles.map(name=>({name}))},clients:[{clientId:'haven-web',enabled:true,publicClient:true,standardFlowEnabled:true,directAccessGrantsEnabled:false,redirectUris:[env.PUBLIC_WEB_URL+'/api/v1/auth/callback',env.PUBLIC_OPS_URL+'/api/v1/auth/callback'],webOrigins:[env.PUBLIC_WEB_URL,env.PUBLIC_OPS_URL],attributes:{'pkce.code.challenge.method':'S256'},protocolMappers:[{name:'haven-audience',protocol:'openid-connect',protocolMapper:'oidc-audience-mapper',config:{'included.client.audience':'haven-web','id.token.claim':'false','access.token.claim':'true'}}]}],users},null,2),{mode:0o600});
fs.writeFileSync(generated+'/s3.json',JSON.stringify({identities:[{name:'haven',credentials:[{accessKey:env.S3_ACCESS_KEY,secretKey:env.S3_SECRET_KEY}],actions:['Admin','Read','List','Tagging','Write']}]},null,2),{mode:0o600});
fs.writeFileSync(generated+'/personas.md',`# Local development accounts\n\nSign in with: ${personas.join(', ')}\n\nGenerated local password: \`${env.DEV_PASSWORD}\`\n\nStaff accounts additionally require a six-digit authenticator code. Add the matching Base32 secret from infra/generated/otp.json to your authenticator app (TOTP, SHA1, 6 digits, 30 seconds). These secrets are local development fixtures only.\n\nIdentity bootstrap administrator: local-admin\n\nPassword is KEYCLOAK_ADMIN_PASSWORD in .env. These accounts are development-only.\n`,{mode:0o600});
console.log('Local environment and identity fixtures ready. Account credentials: '+generated+'/personas.md');
