import fs from 'node:fs';
import path from 'node:path';
import {randomBytes} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const directory=path.resolve(process.argv[2]||''),port=Number(process.env.HTTPS_PORT||8443);if(process.env.HAVEN_SYNTHETIC_STAGING!=='true'||!process.argv[2]||fs.existsSync(directory)||!Number.isInteger(port)||port<1024||port>65535)throw Error('Explicit synthetic staging flag, unused private output directory and unprivileged HTTPS port required');fs.mkdirSync(directory,{recursive:true,mode:0o700});const secret=()=>randomBytes(32).toString('hex'),db=secret(),app=secret(),identity=secret(),session=secret(),search=secret(),storage=secret(),admin=secret(),password=secret(),mailKey=secret();const domains={web:'web.haven.test',ops:'ops.haven.test',identity:'identity.haven.test'},origins=Object.fromEntries(Object.entries(domains).map(([k,v])=>[k,'https://'+v+':'+port]));
const application={NODE_ENV:'production',DATABASE_URL:'postgres://haven_app:'+app+'@db:5432/haven',SESSION_KEY:session,SEARCH_KEY:search,S3_ACCESS_KEY:'haven-staging',S3_SECRET_KEY:storage,PUBLIC_WEB_URL:origins.web,PUBLIC_OPS_URL:origins.ops,OIDC_ISSUER:origins.identity+'/realms/haven',OIDC_INTERNAL_URL:'http://identity:8080/realms/haven',OIDC_CLIENT_ID:'haven-web',API_INTERNAL_URL:'http://api:4000',SEARCH_URL:'http://search:7700',REDIS_URL:'redis://cache:6379',S3_ENDPOINT:'http://storage:8333',MAP_STYLE_URL:'https://tiles.openfreemap.org/styles/liberty',MAP_ATTRIBUTION:'© OpenStreetMap contributors · OpenFreeMap',MAIL_PROVIDER_URL:'https://mail-provider:9443',MAIL_PROVIDER_KEY:mailKey,MAIL_FROM:'notifications@haven-staging.example',NODE_EXTRA_CA_CERTS:'/run/tls/ca.pem'};
function env(file,values){fs.writeFileSync(path.join(directory,file),Object.entries(values).map(([k,v])=>k+'='+v).join('\n')+'\n',{mode:0o600});}
env('application.env',application);env('mail-provider.env',{MAIL_PROVIDER_KEY:mailKey,HAVEN_SYNTHETIC_STAGING:'true'});const provisioning={...application,POSTGRES_PASSWORD:db,APP_DB_PASSWORD:app,IDENTITY_DB_PASSWORD:identity,KEYCLOAK_ADMIN_PASSWORD:admin,DEV_PASSWORD:password,MIGRATION_DATABASE_URL:'postgres://haven_migrate:'+db+'@db:5432/haven'};env('provisioning.env',provisioning);execFileSync(process.execPath,['scripts/setup.mjs'],{env:{...process.env,SETUP_ENV_FILE:path.join(directory,'provisioning.env'),SETUP_GENERATED_DIR:path.join(directory,'identity'),SETUP_PROJECT_NAME:'haven-staging'},stdio:'ignore'});
const caKey=path.join(directory,'ca.key'),ca=path.join(directory,'ca.pem'),key=path.join(directory,'tls.key'),csr=path.join(directory,'tls.csr'),cert=path.join(directory,'tls.pem'),extensions=path.join(directory,'tls.extensions');fs.writeFileSync(extensions,'subjectAltName=DNS:'+Object.values(domains).join(',DNS:')+',DNS:mail-provider\nbasicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n',{mode:0o600});const openssl=args=>execFileSync('openssl',args,{stdio:'ignore'});openssl(['req','-x509','-newkey','rsa:3072','-nodes','-keyout',caKey,'-out',ca,'-days','7','-subj','/CN=Haven synthetic staging private CA','-addext','basicConstraints=critical,CA:TRUE','-addext','keyUsage=critical,keyCertSign,cRLSign']);openssl(['req','-new','-newkey','rsa:3072','-nodes','-keyout',key,'-out',csr,'-subj','/CN=web.haven.test']);openssl(['x509','-req','-in',csr,'-CA',ca,'-CAkey',caKey,'-CAcreateserial','-out',cert,'-days','7','-extfile',extensions]);for(const file of fs.readdirSync(directory)){const p=path.join(directory,file);if(fs.statSync(p).isFile())fs.chmodSync(p,0o600);}execFileSync(process.execPath,['scripts/production-routes.mjs',path.join(directory,'routes.json')],{env:{...process.env,PUBLIC_WEB_URL:origins.web,PUBLIC_OPS_URL:origins.ops,PUBLIC_IDENTITY_URL:origins.identity},stdio:'ignore'});
env('compose.env',{COMPOSE_PROJECT_NAME:'haven-staging',POSTGRES_PASSWORD:db,APP_DB_PASSWORD:app,IDENTITY_DB_PASSWORD:identity,KEYCLOAK_ADMIN_PASSWORD:admin,MIGRATION_DATABASE_URL:provisioning.MIGRATION_DATABASE_URL,PUBLIC_WEB_URL:origins.web,PUBLIC_OPS_URL:origins.ops,PUBLIC_IDENTITY_URL:origins.identity,HTTPS_PORT:port,APP_ENV_FILE:path.join(directory,'application.env'),TLS_CERT_FILE:cert,TLS_KEY_FILE:key,TLS_ROUTES_FILE:path.join(directory,'routes.json'),IDENTITY_IMPORT_FILE:path.join(directory,'identity/haven-realm.json'),S3_CONFIG_FILE:path.join(directory,'identity/s3.json'),EXTRA_CA_CERT_FILE:ca,STAGING_MAIL_ENV_FILE:path.join(directory,'mail-provider.env'),HAVEN_API_IMAGE:'',HAVEN_WORKER_IMAGE:'',HAVEN_WEB_IMAGE:'',HAVEN_OPS_IMAGE:'',HAVEN_MIGRATE_IMAGE:''});fs.writeFileSync(path.join(directory,'scope.json'),JSON.stringify({label:'P',synthetic:true,publicProduction:false,mail:'Local HTTPS adapter and private SMTP receipt only',tls:'Generated private CA, seven-day local certificates',origins},null,2)+'\n',{mode:0o600});console.log('Synthetic staging inputs generated in the private output directory; immutable image IDs still required. No secret values logged.');
