import {describe,it,expect} from 'vitest';
import {listingFilters,transition,listingTransitions,leadTransitions,maintenanceTransitions} from '../../packages/contracts/src/index';
import {csvCell} from '../../packages/contracts/src/mortgage';
import {mortgage} from '../../apps/api/src/geography/mortgage-engine';
import fs from 'node:fs';
import {assertImport,assertMutation} from '../../scripts/boundaries.mjs';
describe('F01/F03 architecture contract',()=>{
 it('has one owner per domain table',()=>{const modules=JSON.parse(fs.readFileSync('docs/adr/modules.json','utf8'));const tables=Object.values(modules).flatMap((m:any)=>m.tables);expect(new Set(tables).size).toBe(tables.length);expect(Object.keys(modules)).toEqual(['identity','geography','inventory','engagement','management','services','administration','platform']);});
 it('rejects undocumented cross-module mutations',()=>{expect(()=>assertMutation('geography','communities')).not.toThrow();expect(()=>assertMutation('geography','payments')).toThrow('Undocumented mutation');});
 it('rejects cross application and browser database imports',()=>{expect(()=>assertImport('apps/web/src/page.ts','@haven/contracts')).not.toThrow();expect(()=>assertImport('apps/web/src/page.ts','@haven/database')).toThrow('database boundary');expect(()=>assertImport('apps/web/src/page.ts','../../apps/api/src/core')).toThrow('Cross-application');});
});
describe('F08 discovery validation',()=>{it('accepts bounded filters',()=>expect(listingFilters.parse({minPrice:'300.00',maxPrice:'500.00'}).limit).toBe(20));it('rejects inverted ranges and oversized pages',()=>{expect(()=>listingFilters.parse({minPrice:'500',maxPrice:'10'})).toThrow();expect(()=>listingFilters.parse({limit:100})).toThrow();});});
describe('I03/L02/P12 transitions',()=>{it('allows declared transitions',()=>{expect(transition(listingTransitions,'under_review','published')).toBe('published');expect(transition(leadTransitions,'new','assigned')).toBe('assigned');expect(transition(maintenanceTransitions,'in_progress','resolved')).toBe('resolved');});it('rejects invalid shortcuts',()=>{expect(()=>transition(listingTransitions,'draft','published')).toThrow();expect(()=>transition(leadTransitions,'new','won')).toThrow();expect(()=>transition(maintenanceTransitions,'open','resolved')).toThrow();});});
describe('T01/T03 mortgage',()=>{it('repays 120000 principal at zero rate over 120 months exactly',()=>{const r=mortgage({price:'120000',downPayment:'0',annualRate:0,years:10,method:'equal_payment'});expect(r.monthlyPayment).toBe('1000.00');expect(r.totalInterest).toBe('0.00');expect(r.totalRepaid).toBe('120000.00');expect(r.schedule.at(-1)?.balance).toBe('0.00');});it('reconciles known nonzero-rate fixture in both methods',()=>{for(const method of ['equal_payment','equal_principal']){const r=mortgage({price:'120000',downPayment:'0',annualRate:6,years:10,method});expect(r.schedule.at(-1)?.balance).toBe('0.00');expect(r.schedule.reduce((s,p)=>s+BigInt(p.principal.replace('.','')),0n)).toBe(12000000n);expect(r.monthlyPayment).toBe(method==='equal_payment'?'1332.25':'1600.00');}});it('rejects zero term, negative rate and excessive down payment',()=>{for(const input of [{years:0},{annualRate:-1},{downPayment:'120001'}])expect(()=>mortgage({price:'120000',downPayment:'0',annualRate:0,years:10,method:'equal_payment',...input})).toThrow();});it('escapes CSV formula-like and Unicode titles',()=>{expect(csvCell('=SUM(A1)')).toBe('"\'=SUM(A1)"');expect(csvCell('A "home" · 北京')).toBe('"A ""home"" · 北京"');});});
