import {it,expect} from 'vitest';
import {mortgage} from '../../apps/api/src/geography/mortgage-engine';
const base={price:'120000',downPayment:'0',annualRate:'6',years:10,method:'equal_payment'};
const cents=(v:string)=>BigInt(v.replace('.',''));
const sum=(values:string[])=>{const n=values.reduce((n,v)=>n+cents(v),0n);return (n/100n).toString()+'.'+(n%100n).toString().padStart(2,'0');};
it('T01 known six-percent cent-rounded fixture reconciles first/final payment and aggregate totals',()=>{const r=mortgage(base);expect(r).toMatchObject({monthlyPayment:'1332.25',finalPayment:'1331.55',totalInterest:'39869.30',totalRepaid:'159869.30',annualRate:'6',method:'equal_payment',months:120});expect(sum(r.schedule.map(x=>x.principal))).toBe(r.principal);expect(sum(r.schedule.map(x=>x.interest))).toBe(r.totalInterest);expect(sum(r.schedule.map(x=>x.payment))).toBe(r.totalRepaid);expect(r.schedule.at(-1)?.balance).toBe('0.00');expect(r.assumptions).toContain('no lender approval');});
it('T01 zero-rate equal-payment and equal-principal fixtures repay exactly 1000 monthly with no interest',()=>{for(const method of ['equal_payment','equal_principal']){const r=mortgage({...base,annualRate:'0',method});expect(r.schedule).toHaveLength(120);for(const row of r.schedule)expect(row).toMatchObject({principal:'1000.00',interest:'0.00',payment:'1000.00'});expect(r.totalRepaid).toBe('120000.00');expect(r.totalInterest).toBe('0.00');expect(r.schedule.at(-1)?.balance).toBe('0.00');}});
it('T01 fractional-cent installments, tiny loans and high-value long schedules never grow principal or produce negative rows',()=>{for(const method of ['equal_payment','equal_principal'])for(const price of ['0.01','1.00','100.01','999999999999.99']){const r=mortgage({...base,price,years:40,annualRate:'30',method});let balance=cents(r.principal);for(const row of r.schedule){expect(cents(row.principal)>=0n).toBe(true);expect(cents(row.interest)>=0n).toBe(true);expect(cents(row.balance)<=balance).toBe(true);expect(cents(row.principal)+cents(row.interest)).toBe(cents(row.payment));balance=cents(row.balance);}expect(balance).toBe(0n);expect(sum(r.schedule.map(x=>x.principal))).toBe(r.principal);expect(sum(r.schedule.map(x=>x.payment))).toBe(r.totalRepaid);}});
it('T01 rejects floating money, zero/negative principal or term, negative/nonfinite rate and unbounded input',()=>{for(const patch of [{price:120000},{downPayment:0},{price:'0'},{downPayment:'120000'},{downPayment:'120001'},{years:0},{years:-1},{years:41},{annualRate:'-1'},{annualRate:Infinity},{price:'1000000000001'},{method:'unknown'},{unrecognized:true}])expect(()=>mortgage({...base,...patch})).toThrow();});
