import {it,expect} from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {generateKeyPairSync} from 'node:crypto';
import {encryptSnapshot,decryptSnapshot,safeRelative} from '../../scripts/recovery/envelope.mjs';
it('Q09 authenticated streaming backup restores exact decimal records and refuses missing WAL or modified ciphertext before successful restoration',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'haven-envelope-'));try{const source=path.join(root,'source'),encrypted=path.join(root,'encrypted'),restored=path.join(root,'restored');fs.mkdirSync(source);fs.mkdirSync(path.join(source,'wal'));fs.writeFileSync(path.join(source,'financial.json'),'[{"posted":"9007199254740993.01"}]\n');fs.writeFileSync(path.join(source,'wal','000000010000000000000001'),Buffer.alloc(4096,91));const pair=generateKeyPairSync('rsa',{modulusLength:3072,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}}),publicKey=path.join(root,'public.pem'),privateKey=path.join(root,'private.pem');fs.writeFileSync(publicKey,pair.publicKey);fs.writeFileSync(privateKey,pair.privateKey,{mode:0o600});const signing=generateKeyPairSync('ed25519',{publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}}),signPrivate=path.join(root,'sign-private.pem'),signPublic=path.join(root,'sign-public.pem');fs.writeFileSync(signPrivate,signing.privateKey,{mode:0o600});fs.writeFileSync(signPublic,signing.publicKey);const metadata={requiredFiles:['financial.json','wal/000000010000000000000001']};expect((await encryptSnapshot(source,encrypted,publicKey,metadata,signPrivate)).fileCount).toBe(2);expect((await decryptSnapshot(encrypted,restored,privateKey,signPublic)).fileCount).toBe(2);expect(fs.readFileSync(path.join(restored,'financial.json'),'utf8')).toBe(fs.readFileSync(path.join(source,'financial.json'),'utf8'));fs.rmSync(path.join(encrypted,'000001.bin'));await expect(decryptSnapshot(encrypted,path.join(root,'missing-wal'),privateKey,signPublic)).rejects.toThrow('REQUIRED_RECOVERY_CIPHERTEXT_MISSING');expect(fs.existsSync(path.join(root,'missing-wal'))).toBe(false);const encrypted2=path.join(root,'encrypted2');await encryptSnapshot(source,encrypted2,publicKey,metadata,signPrivate);const altered=path.join(encrypted2,'000000.bin'),bytes=fs.readFileSync(altered);bytes[0]^=1;fs.writeFileSync(altered,bytes);await expect(decryptSnapshot(encrypted2,path.join(root,'tampered'),privateKey,signPublic)).rejects.toThrow('RECOVERY_CIPHERTEXT_MISMATCH');expect(fs.existsSync(path.join(root,'tampered'))).toBe(false);const outerPath=path.join(encrypted2,'envelope.json'),outer=JSON.parse(fs.readFileSync(outerPath,'utf8'));outer.createdAt='forged';fs.writeFileSync(outerPath,JSON.stringify(outer));await expect(decryptSnapshot(encrypted2,path.join(root,'forged'),privateKey,signPublic)).rejects.toThrow('BACKUP_SIGNATURE_INVALID');expect(fs.existsSync(path.join(root,'forged'))).toBe(false);}finally{fs.rmSync(root,{recursive:true,force:true});}
});
it('Q09 recovery rejects path traversal and backup destinations inside source snapshots',async()=>{for(const name of ['../secret','/absolute','wal/../secret','wal\\secret','wal//segment'])expect(()=>safeRelative(name)).toThrow('UNSAFE_RECOVERY_PATH');const root=fs.mkdtempSync(path.join(os.tmpdir(),'haven-nested-'));try{await expect(encryptSnapshot(root,path.join(root,'nested'),'unused',{})).rejects.toThrow('RECOVERY_DIRECTORIES_MUST_BE_SEPARATE');}finally{fs.rmSync(root,{recursive:true,force:true});}});
